### ISSUE TITLE
Using FormKitSchema does not fully support reactivity

### ISSUE THREAD

**Issue by dimonixx** [formkit/formkit#1001]
### Reproduction

https://formkit.link/4481e5e95cccd7f4b2899d7296b68f2c

### Describe the bug

Hi 

using formkit schema input with an valueModel attribute looks to provide reactivity, but the value changes only one way - if it's changed externally, the value would be changed in the input. 

Changing the value in the input field itself has not effect.

In the example above:

- clicking on the button would increment the value and the UI would react 
- changing the value in the input field has no effect

### Environment

• OS: iOS
• Browser : Chrom, Firefox
• Version [e.g. 22]

**Comment by GustavoFenilli** [comment]
Even tho this looks like a bug, it is not the recommended way of using FormKit nor schemas, it all depends on what you're trying to do, but the recommended way is to not use `data` nor `schema` as a reactive property.

**Comment by GustavoFenilli** [comment]
After taking a look, this isn't a bug, `modelValue` is not a two way binding even in vue itself, `v-model` is.

**Comment by GustavoFenilli** [comment]
This is also not the recommended way of using schema and FormKit, we recommend that both data and schema to not be reactive at all.

**Comment by dimonixx** [comment]
How would you recommend to update an object without posting and reloading it ? Or it's not the way FormKit can be used at all?

**Comment by GustavoFenilli** [comment]
It depends, FormKit is a form library so most of the time schema will be used to create a form, in that sense you don't need to bind any reactive state, FormKit does this for you, `onSubmit` would have all values posted for you, and `getNode('form').input()` can be used to pass values programatically.

As for your case that you're not using form, you can still do two way binding, you're just not doing it right in vue so it won't work in schema either. `modelValue` is not two way binding: https://formkit.link/a100caa720a45075a0ab1b210a7af122

**Comment by dimonixx** [comment]
Sure, i needed a way to make it in schema. The declaration of onUpdate is what i was looking for. Will give it a try. Thanks for fast reply !
