### ISSUE TITLE
getNode in Nuxt 3: Returns undefined after Using navigateTo with Multistep Component

### ISSUE THREAD

**Issue by phillipmohr** [formkit/formkit#1002]
### Reproduction

https://stackblitz.com/edit/nuxt-starter-tthkpt?file=pages%2Findex.vue

### Describe the bug

**Issue:**

- I have two pages, both of which utilize the same multistep component.
- The component relies on the getNode function to retrieve the node of the FormKit multistep component.
- On the first page load, everything functions correctly.
- However, when I use navigateTo to transition to the second page, which also attempts to use getNode, the function returns undefined.

**Steps to Reproduce:**

1. Visit the Stackblitz link: https://stackblitz.com/edit/nuxt-starter-tthkpt?file=pages%2Findex.vue
2. Open the developer tools.
3. Observe that getNode initially returns a result.
4. Click on the "Next Step" button, which triggers navigateTo.
5. After navigating, getNode should return undefined.

<img width="189" alt="Bildschirmfoto 2023-10-18 um 15 04 42" src="https://github.com/formkit/formkit/assets/30236221/c1862f46-c144-425e-9d7f-fc68a08fce2d">

**Expected Behavior:**

The getNode function should consistently return a result, regardless of navigation between pages that use the same component.

### Environment

• OS: macOS
• Browser Chrome
• Version 100

**Comment by GustavoFenilli** [comment]
Couldn't not replicate with the link, it gives `Avoided redundant navigation to current location: "/campaign/edit/1".` instead of your expected behaviour.

**Comment by phillipmohr** [comment]
> Couldn't not replicate with the link, it gives `Avoided redundant navigation to current location: "/campaign/edit/1".` instead of your expected behaviour.

I provided the wrong default file inside the stackblitz link. Please try this one and make sure you're on the index.vue (Create) page: https://stackblitz.com/edit/nuxt-starter-tthkpt?file=pages%2Findex.vue

**Comment by BracketJohn** [comment]
One possibly related thing: In our Nuxt 3 setup `getNode` returns `undefined` when `autoImports: true` is configured, I commented more about this here: https://github.com/formkit/unplugin-formkit/issues/1#issuecomment-1883232861

Just leaving it here for the possible connection, I don't expect this to be re-opened / further adressed.
