### ISSUE TITLE
FormKit number input with number prop does not respect browser lang set on form

### ISSUE THREAD

**Issue by fdverwoerd** [formkit/formkit#1003]
### Reproduction

https://formkit.link/9cc5c188596c7e3f574219fcb12db030

### Describe the bug

number prop cast is good for output, but the input should maintain the lang comma separator.
For example in Dutch language decimals are separated with a comma `1,99`;

But when using the `number` prop on formkit number the input changes to a dot value `1.99` which is not correct in current language set for example on form tag?

Shouldn't this work or is this something to be fixed around FormKit?

```
<template>
  <FormKit type="form" lang="nl" :actions="false" #default="{ value: values }">
    <FormKit
      type="number"
      help="number float"
      label="Spoons of sugar (float)"
      number
      name="cast"
      value="3.25"
      step="0.01"
    />
    <FormKit
      type="number"
      help="not cast"
      label="change this and see the comma"
      name="not_cast"
      value="25.99"
      step="0.01"
    />
    <pre wrap>{{ values }}</pre>
  </FormKit>
</template>
```

Is this a bug or am I missing something :)

I think this was asked here as well: https://github.com/formkit/formkit/issues/325

### Environment

• OS: at least MacOS [e.g. iOS]
• Browser Firefox, Chrome (Safari is weird)
• Version Latest

**Comment by justin-schroeder** [comment]
As the docs point out, the number input uses a native `<input type="number">`. Localization of these native inputs is up to the browser and, unfortunately, has nothing to do with FormKit. You are welcome to use the mask input to try and force a specific format if that is what you are looking for.

In terms of the `<input type="number" />` itself — you can checkout the following resources:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number
https://www.ctrl.blog/entry/html5-input-number-localization.html

**Comment by fdverwoerd** [comment]
@justin-schroeder 
But it does not work like native does, I expect the behaviour that you can see here in this codepen I made:

Native input shows the value in localized version, in this case dutch and decimal is comma separated. Also changing it works. And the output is correct value.

But when I try to do this with FormKit I doesnt work as like the codepen version in my Playground example.



https://codepen.io/Wonky/pen/wvRVqmO

**Comment by justin-schroeder** [comment]
![image](https://github.com/formkit/formkit/assets/1950463/cfafc939-cedf-4c3b-a852-887d60e9e5a3)

Is this what you expected?

**Comment by fdverwoerd** [comment]
Hmm no that was not my intended example :) 
Hmm... I guess you are using Safari?
I am using Firefox mostly and just checked: FIrefox, Chrome and Safari. It seems Safari doesn't even do localisation or listens to lang attribute?

<img width="1257" alt="browser-madness" src="https://github.com/formkit/formkit/assets/7069087/cf125a43-396b-4c6c-86f2-eb70a2ec45b2">

**Comment by justin-schroeder** [comment]
I was using chrome on MacOS

**Comment by fdverwoerd** [comment]
I am lost now :) I thought I knew the input number and that it uses correct decimal separator based on lang attribute. But I guess this is not perfect.
