### ISSUE TITLE
Formkit Schema value start with $

### ISSUE THREAD

**Issue by m4riachi** [formkit/formkit#1009]
### Reproduction

https://formkit.com/playground?css-framework=genesis&fkv=latest&fileTab=generating.vue&imports=jc%28%27name%21%27ImportMap%27%7Elang%21%27json%27%7Eeditor%21%27%28*+1vue%5C%211https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fvue%403%2Fdist%2Fvue.esm-browser.min.js0*%29*%27%29*%5Cn0%5C%271+0%0110*_&files=jc%5B%28%27nM%21%27generYing.vue%27%7EeditX%21%27%3CEOexpX8defaul8%281JRZLturnB7J_C7sD%3A7*%5BW%28W*%24fXmkit4text3nM4firstnM3label4Firs8NM3help4This+will+be+used+fX+your+account.3validYion4LquiLd3value4%24T200%22WC7*%5DZ%291C1methods_Zasync+VR7awai8new+Promise%7B%7Br%7D+%3D%3E+setTimeout%7Br%2C+2000%7D%7D7alert%7B%22Accoun8cLYed%27%3A%22%7DZC1C5%2959EO5%3CH1z8typeIfXmQv-modelIJQ%40submitIV6U*ztSD+%3AsDIsDQ%2FU9GtU%3CpL+wrap%3E%28%28+J+%29%299pLO9H5%27%7Esyntax%21%27javaE%27%7Eadded%21true%29%5D*++15*3%22%2CW*4%3A+%225%5Cn6%5C%277Z*8t+9%3C%2FB+%28C%29%2CDchemaEscriptGFXmKiHtemplYe%3EI%3D6JdYaLreMameO%3E5Q6+R%7B%7DBU%3E1VLgisterW7**XorYatZ1*_%3ABz%3CG%01z_ZYXWVURQOMLJIHGEDCB98765431*_

### Describe the bug

I'm using formkit schema to create my form, if i put a value start with $ on a field the field will be empty

`{
            $formkit: 'text',
            name: 'firstname',
            label: 'First Name',
            help: 'This will be used for your account.',
            validation: 'required',
            value: '$T200'
          }`

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by GustavoFenilli** [comment]
That is indeed the case, any property that starts with $ will be considered to be parsed as a variable, for your case you should consider using the raw values for the properties: https://formkit.com/essentials/schema#raw-values

Like so: https://formkit.link/3e646586e2ad9bd712053daf11e912b2
