### ISSUE TITLE
Mimic the behavior of the select input for dropdown by preventing a user from deselecting an item

### ISSUE THREAD

**Issue by charliepy** [formkit/formkit#1012]
### Reproduction

https://formkit.link/4b5216e10aaa9ff02d09c1d6f28669f2

### Describe the bug

I would like to prevent a user from "deselecting" a currently selected item when clicking the list item again

### Environment

• OS: [Windows 10]
• Browser [Chrome]
• Version [FormKit 1.2]

**Comment by justin-schroeder** [comment]
This is now resolved with a new prop: `deselect="false"`

https://formkit.link/31bd8404d5a28a81ae2a1ab45060b60a

You’ll need to update to `0.119.1`. Thanks!

**Comment by charliepy** [comment]
Thank you @sashamilenkovic @justin-schroeder
