### ISSUE TITLE
autoImport: true lets fail tailwind classes on nuxt/content components

### ISSUE THREAD

**Issue by silvio-e** [formkit/formkit#1013]
### Reproduction

https://stackblitz.com/edit/nuxt-starter-zctdq2?file=nuxt.config.ts,content%2Findex.md

### Describe the bug

As soon as `autoImport` is set to `true` the Tailwind classes on the component in the `index.md` file, are not working anymore.

**Comment by justin-schroeder** [comment]
Resolved in 1.4.0 👍
