### ISSUE TITLE
Input "number" allows input of characters in Safari and Firefox

### ISSUE THREAD

**Issue by mhuijser** [formkit/formkit#1014]
### Reproduction

https://formkit.link/60b29be78f5dc0aa31a93e7c78c3fd50

### Describe the bug

When in Safari or Firefox, the input type "number" allows users to enter characters. In chrome that's not possible.
 
In Chrome on the other hand, only the upper ánd lower "e" character is allowed (which only makes sense to support a scientific notation). But an "E" or "e" should not be allowed all by itself, only in a certain format, like for example, 1e6 (which represents 1 * 10^6 or 1000000.0).

I would expect that chrome, safari and firefox has the same input-behaviour.

### Environment

• OS: MacOS
• Browser: Safari , Firefox
• Safari 17 , Firefox 118.0.2

**Comment by GustavoFenilli** [comment]
FormKit uses native inputs so that is browser dependent.

**Comment by DesertCookie** [comment]
Is there a way to manually circumvent this?

For example, by having a listener on the element that removes any letters? Right now, the element correctly returns `undefined` when also containing a letter, however, the user doesn't recognize this as his input persists in the number field.
