### ISSUE TITLE
Change event does not work on Slider input

### ISSUE THREAD

**Issue by andyjamesn** [formkit/formkit#1022]
### Reproduction

https://formkit.link/83c3fc225df5f57ab29deaed26c10ad0

### Describe the bug

I am trying to add a change event to the slider input. I use this to send a post request with an updated value in other inputs. But with the slider it does not work. The change event is not firing. Is there a different event for the slider? 

### Environment

• OS: OS X
• Browser Chrome
• Version 118.0.5993.70

**Comment by GustavoFenilli** [comment]
You shouldn't be using `@change`, you can instead get the node and listen to the commit event: https://formkit.link/4d1d4520cb0f098e8044262e803ba411

**Comment by andyjamesn** [comment]
Ok thanks, is this the common practice for all inputs instead of using change events?

**Comment by andyjamesn** [comment]
I am just getting started with Formkit and figuring out how to work with it. I have now found this in the docs

https://formkit.com/essentials/inputs#events

Thanks

**Comment by GustavoFenilli** [comment]
Indeed it is the common practice to use FormKit events instead of vue ones: https://formkit.com/essentials/architecture#events

Even tho we also send the commit event to `@input` it is still prefered to use the node directly.
