### ISSUE TITLE
Pro Input 'dropdown' spams upon selecting items when combined with 'behavior: overscroll' and 'multiple'

### ISSUE THREAD

**Issue by joshua1dg** [formkit/formkit#1023]
### Reproduction

https://formkit.link/ca1eedc0452cbab20c1aa1bec0a2625a

### Describe the bug

When using the dropdown input with the ability to select multiple options, the list 'spams' or jumps around after each item select.

### Environment

• Browser chrome

**Comment by sashamilenkovic** [comment]
@joshua1dg This should be fixed at FormKit Pro v0.122.4.
