### ISSUE TITLE
do not work suffix feature

### ISSUE THREAD

**Issue by yongho0605** [formkit/formkit#1031]
### Reproduction

https://formkit.link/7b941a1001e8383edeaaf0ff3e21bc41

### Describe the bug

The suffix is not working in formkit for email type, what can I do? (Doesn't work in the formkit playground either)

Example) I want to send the verification number in the email input, but the suffix doesn't work.

### Environment

• OS: macOS Sonoma 14.1.1
• Browser: chrome 119.0.6045.123
• Version :  (in package.json)
```json
"@formkit/i18n": "^1.3.0",
"@formkit/nuxt": "^1.2.2",
"@formkit/pro": "^0.117.5",
"@formkit/themes": "^1.2.2",
"@formkit/validation": "^1.2.2",
```

**Comment by GustavoFenilli** [comment]
Suffix by default has no output, use a slot to change the section: https://formkit.link/a0f8ee992cfecdb2f9d3b143dd7da2de

**Comment by yongho0605** [comment]
Thanks! Formkit always works great for me!
