### ISSUE TITLE
Pro inputs: use teleport/portal for dialogs

### ISSUE THREAD

**Issue by ohadsh535** [formkit/formkit#1035]
### Reproduction

https://formkit.link/bd4bc063fa7241ce9b9834f5c9c7ee14

### Describe the bug

Autocomplete options rendering on `position: absolute`, causes GUI break when element height is defined.
Suggest mod solution on the "Reproduction Link".

### Environment

• OS: [e.g. iOS] macOS
• Browser [e.g. chrome, safari] Chrome
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
we’d like to do something like this — currently we don’t have a cross framework (vue/react/native, currently only Vue is supported but the schema should be cross compatible) way to do teleport/portals. The ideal solution, imho, is the [Popover API](https://developer.mozilla.org/en-US/docs/Web/API/Popover_API) which is quickly [trending towards broad support](https://caniuse.com/mdn-api_htmlelement_popover).

In the meantime, perhaps there is a way we could write our own wrapper layer for each portal implementation...I’ll leave this open as a placeholder.

**Comment by ohadsh535** [comment]
Well, FormKit uses multiple named  `<template></template>` `<slot></slot>`.
Example from snippet `<template #dropdownWrapper="props">...</template>`, which is also unique for Vue development AFAIK opposed to others (React, Angular, etc..)

Anyway, feel free to reach out if needed ;)

**Comment by andrew-boyd** [comment]
You're correct, but the distinction here is that those slots are provided by the `@formkit/vue` package and are derived from the schema of the FormKit inputs. So yes, we do support slots in Vue — but they are generated from the schema. The actual schemas themselves (and anything else FormKit-related that's not in `@formkit/vue` or `@formkit/nuxt`) are intentionally framework agnostic for future cross-framework compatibility.

**Comment by justin-schroeder** [comment]
Yeah, we just had a big talk about this...teleport/portals are a great solution to the problem in general, but at the moment our plan is to wait for the popover api to be supported in firefox before we make changes. There are a number of reasons for this, not least of which is semantic styles break when teleporting dom nodes to the body if they relied on selectors and in genera we want to have a consistent way for everyone to write their styles for formkit.

The good news is the popover api is quickly gaining traction. [The latest (13 days ago) is that the popover api may start shipping in Firefox as early as 122](https://groups.google.com/a/mozilla.org/g/dev-platform/c/hrCP5RBO7mA).

Once support gets into the 85-90% range you can expect FormKit to use popover for all such UI.

PS — The fact that you got the autocomplete working with teleport is freakin awesome ❤️.

**Comment by andrew-boyd** [comment]
As of `0.120.0` which shipped today you can use the `popover` prop on the `autocomplete`, `colorpicker`, `datepicker`, `dropdown` and `taglist` inputs to render their contents using the browser Popover API. Firefox does not _yet_ support popover but will in upcoming version `125` — current version is `122`

https://caniuse.com/?search=popover
