### ISSUE TITLE
The plugin from the "add asterisk plugin" guide doesn't work for dynamic validation

### ISSUE THREAD

**Issue by gbyesiltas** [formkit/formkit#1036]
### Reproduction

https://formkit.link/465701012fc89ec73d7183f0c6a06330

### Describe the bug

[The example plugin guide for "automatically adding asterisk"](https://formkit.com/essentials/examples#page-container#plugins) does not work when the validation on the inputs are dynamic. Looking at the plugin code, I see it wasn't necessarily built for this but I still believe the expected behaviour for this plugin should be dynamic so I'm opening a bug report for this.

Thank you! :)

### Environment

• OS: All
• Browser: All

**Comment by GustavoFenilli** [comment]
Does this work for you as a new example for it?: https://formkit.link/06a3e7555c3ca4f28adbc135e77d658f

**Comment by gbyesiltas** [comment]
> Does this work for you as a new example for it?: https://formkit.link/06a3e7555c3ca4f28adbc135e77d658f

@GustavoFenilli 
Yes! from the repro you sent, it seems to work very well, I'll add it to the project and see how it works there too. Thanks!

**Comment by GustavoFenilli** [comment]
Great, changed at examples page: https://github.com/formkit/docs-content/pull/124 .

**Comment by gbyesiltas** [comment]
> Great, changed at examples page: [formkit/docs-content#124](https://github.com/formkit/docs-content/pull/124) .

@GustavoFenilli Hey man, I just realised that the version you linked to was causing some issues for autocomplete and group components for me so I made a small addition here: https://formkit.link/6db603c59d0a151139d06288cd3f218d

Does that look right? If so, I'll open a follow-up PR to yours :)

**Comment by GustavoFenilli** [comment]
Looks like autocomplete might not have a memokey? that is why it gives a problem? or they might share? @justin-schroeder

This indeed should fix it:
```ts
node.props.definition.schemaMemoKey = `required_${isCheckboxAndRadioMultiple(node) ? 'multi_' : ""}${node.props.definition.schemaMemoKey || Math.random()}`  
```

**Comment by last-partizan** [comment]
How to also add class to label, dependent on `context.isRequired`?

**Comment by fenilli** [comment]
> How to also add class to label, dependent on `context.isRequired`?

You can easily add that like so: https://formkit.link/0e49b9bf5187e28441571a16542242bb

**Comment by justin-schroeder** [comment]
@fenilli actually a cool thing we did in 1.4.0 is adding `context.state.required` — so this plugin could get even simpler now.

**Comment by last-partizan** [comment]
@fenilli this will replace classes completely. Is there a way to add to already existing classes?

**Comment by fenilli** [comment]
> @fenilli actually a cool thing we did in 1.4.0 is adding `context.state.required` — so this plugin could get even simpler now.

Oh that is awesome I will play around with it and make a new example with that.

**Comment by fenilli** [comment]
> @fenilli this will replace classes completely. Is there a way to add to already existing classes?

You can instead do this `then: '$classes.label + " bg-red-500"'`
