### ISSUE TITLE
remove data-complete attribute on group/list inputs

### ISSUE THREAD

**Issue by alasdair-richardson** [formkit/formkit#1038]
### Reproduction

https://formkit.link/c10317fc269b238f2ce34efe6b7b0839

### Describe the bug

It is suggested in the doc to use the attributes data-invalid and data-complete to style good and invalid inputs. I tried this in a multistep form and it did not work very well. In the playground you will see one text field 
What I expect to happen
as you type in the field as the required validatoin passes you should see a green border and green tick appear as it has the attribute data-complete. If you then delete the data that attribute should disappear and be replaced with data-invalid, causing the green border and green tick to disappear and be replaced with a red border
What actually happens
This appears to happen on the text node, but the div with class formkit-step, and the div with class formkit-outer just inder the <form> both retain the data-complete attribute. 
I tried initially selecting with .formkit-outer[data-complete] .formkit-inner {...} but of course the div under <form> stymies that. 
Anyhow it seems wrong that those node should keep the data-complete attribute when it patently is not. Also if oyu press the submit button then the same 2 places get data-invalid attribute (as well as data-complete), and this is obviously wrong ...

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by alasdair-richardson** [comment]
It seems to wokr fine in the form with selectors like ```.formkit-step-inner .formkit-outer[data-invalid] .formkit-inner {...}``` but I still think it is a bug

**Comment by justin-schroeder** [comment]
Hi @alasdair-richardson thank you for filing this — I sympathize with the confusion here, although technically it is working as expected. The `data-complete` attribute is not intended to be used with groups/lists/forms etc:

![image](https://github.com/formkit/formkit/assets/1950463/96dd8256-2cee-4602-b30c-f9141717e073)

However, the styling we have on that example is too broad. The selector `[data-complete] .formkit-inner::after` is too broad and will match any/all children. This is confusing!

I think perhaps we should _not_ include the data-complete attribute at all on group based inputs (like steps) that would clear up a lot of this confusion. An alternative approach would be to use a more finely scoped selector, or a slot/sections schema. Here is an example using a slot (no cascade to worry about):

https://formkit.link/92f97b7ba24d7b0d3d1cedeb516e5eab
