### ISSUE TITLE
`createAutoAnimatePlugin` does not work in Nuxt build

### ISSUE THREAD

**Issue by ineshbose** [formkit/formkit#1042]
### Reproduction

https://stackblitz.com/edit/github-8gbhmr?file=formkit.config.ts

### Describe the bug

1. By default, Stackblitz will run `npm run dev`, so play with the form (toggle the checkbox on and then off to trigger validation message) and notice the animations.
2. Now run `npm run build && npm run preview` and try again. Does not seem to animate.

### Environment

any

**Comment by justin-schroeder** [comment]
Thank you for the reproduction. We’ll look into it.

**Comment by justin-schroeder** [comment]
Closing in favor of #1016 (same underlying issue) — fix is in the `@next` release.
