### ISSUE TITLE
Radio buttons in repeaters 'stealing' selected status from each other

### ISSUE THREAD

**Issue by SDRACK** [formkit/formkit#1044]
### Reproduction

https://formkit.link/ac50f9736dc092ca2dfea003ccb95258

### Describe the bug

Here's a quick screen recording of the issue:

https://github.com/formkit/formkit/assets/8395303/f7b33fe2-7eca-4cb3-bc0a-8f85ba04e836

With radio buttons in repeaters, the radios seem to 'steal' the selected state of a different repeater child's radio of the same name. I'm pretty sure I've got everything setup correctly in the playground.

To reproduce:

1) add a repeater item so there's more than one item
2) select a radio button in the first repeater
3) select a radio from a different repeater item's radio: there will be a single radio showing as selected

Interestingly, the data / conditional fields relying on the input remain as they should, so I'm hopeful this is more of a visual issue.

There's a further issue viewable in the playground - if you re-order a repeated item that has conditionals attached, toggling the radio impacts a different repeater to the one changed. I presume this is due to the way I'm using the `$index` in the ID, but would be interested in hearing your thoughts on how this could be overcome. Think this is a bug or something I'm doing wrong in my code?

One final note, I've not found any docs on how to handle conditionals within repeaters. In our real world case, we've got nested repeaters, with conditions relying on both the inner and outer data. It's proving tricky ascertaining how to get ahold of what and where, and it would be lovely to read a bit more on how to tackle this (apologies if I've missed in the docs) :) In the case in the playground, I've used the `$index` in the IDs, but I'm not sure that's a great idea, and it wouldn't allow to access any outer repeater scope? All advice welcomed graciously.

### Environment

• OS: Ventura 13.5.1
• Browser Chrome Version 119.0.6045.159
• Version Formkit 1.3

**Comment by fenilli** [comment]
Not sure why this isn't being done automatically which It is supossed to do on repeaters, but for radios you need a unique name so we have a internal altName property for these specific cases, for now as a workaround you can do this simple plugin: https://formkit.link/2a83c9feba9c926bd313c41b61dde836

**Comment by SDRACK** [comment]
Brilliant, thanks @fenilli - that solves the first part! 

Still got an issue with the second part though, e.g. https://formkit.link/ac50f9736dc092ca2dfea003ccb95258.

To reproduce:

1) Select option 'Two'
2) Add a repeater
3) Use the controls to move the first repeater down (or second repeater up)

The result is that the new first item acts as if the condition is met for 'Two' being selected, despite there being no selection, while the new second item acts as if nothing is selected.

Any advise on this one / how to handle IDs for conditionals in repeaters?

**Comment by fenilli** [comment]
When inside a scope you can just do `$value.rad` instead, if you "bake" the index into it when you change it might have some strange behaviours.

**Comment by SDRACK** [comment]
Thanks @fenilli - agree having the index in the identifiers doesn't seem the way to go, though I was lacking for any other solution. 

Sounds like `$value.rad` will be what I need then, but I can't find any info / documentation on what it does - are you able to point me in the right direction please?

**Comment by justin-schroeder** [comment]
This 100% should just work. We’ll look into it.

**Comment by justin-schroeder** [comment]
Resolved in 1.4.0 👍
