### ISSUE TITLE
Adding values to options does not continue counting the __mask_ value

### ISSUE THREAD

**Issue by azertyalex** [formkit/formkit#1046]
### Reproduction

https://formkit.link/9f4a7fe1f8eaa3065e4e9e702d44d26f

### Describe the bug

When appending values to an already used options array, the internal masks are wrong resulting in wrong behavior for select items

### Environment

• OS: Ubuntu
• Browser: Chrome
• Version: 1.3

**Comment by justin-schroeder** [comment]
I think what we need to do here is clone the options prop when it is an object so it is not mutated outside the `<FormKit>` component.
