### ISSUE TITLE
incomplete message doesn't update when changing language without refreshing page or submitting

### ISSUE THREAD

**Issue by mmunkvold** [formkit/formkit#1047]
### Reproduction

https://formkit.link/605d0604f01195f5e11b61e47dac5a27

### Describe the bug

We use i18n to switch between norwegian and english, and we get all other instances of the form - the labels, error messages etc to change language instantly when pressing a language change button, but not the incomplete message. If I refresh the page or hit the submit button again, it updates.
We use Vue3, composition api - and I have tried different methods like watch, watchEffect etc with no luck.
Hard to reproduce, but have put the example in the playground. The incomplete message wont update, but the other example with the name input updates as expected without need of refreshing. 

I asked in the discord server, and Andrew Boyd answered that this might have to do with that attribute not being reactive.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
Resolved in 1.4.0 👍

**Comment by mmunkvold** [comment]
great! thanks for the quick fix!
