### ISSUE TITLE
addAsteriskPlugin not compatible with repeater

### ISSUE THREAD

**Issue by adsjim** [formkit/formkit#1048]
### Reproduction

https://formkit.link/574b84f69f2b205d11fdc10e24b41933

### Describe the bug

The repeater is visible but the inputs/labels are not. It is fine when the plugin is removed. This is using the basic example code from https://formkit.com/inputs/repeater
![bug](https://github.com/formkit/formkit/assets/99401546/bf3ea7f7-3e24-4f15-8165-6cde02847ad5)

### Environment

• OS: Windows 10
• Browser Chrome 119.0.6045.16

**Comment by andrew-boyd** [comment]
Looks like the plugin is not properly accounting for the `repeater` input having a `legend` section. This updated version should handle it. https://formkit.link/79d26284f4f28177d9a2a7c5e250a6bb

**Comment by fenilli** [comment]
Fixed the example to work with some inputs that would also fail like transferlist and the repeater.
