### ISSUE TITLE
Is there any method to reset to init state?

### ISSUE THREAD

**Issue by skimmilk6877** [formkit/formkit#105]
### Describe the feature

Is there any method to reset to init state?

Because we need use router to the form page, when router run, we want the page return to init state

**Comment by justin-schroeder** [comment]
It's a needed feature @skimmilk6877. There's a feature request for this:

https://github.com/formkit/formkit/issues/96

Will likely land in the next beta 👍

**Comment by skimmilk6877** [comment]
@justin-schroeder what I workaroud now is use v-if and nexttick to trigger rebuild。
