### ISSUE TITLE
Cursor jumping to end of Autocomplete input

### ISSUE THREAD

**Issue by markusgeert** [formkit/formkit#1051]
### Reproduction

https://formkit.link/869cccc65f171e604a45843b8ee63211

### Describe the bug

Editing an Autocomplete field with an existing value resets the cursor to the end of the field after the first character is entered. This is demonstrated in the provided example (just the default Autocomplete demo) by:

1. Selecting 'Austria', for example
2. Deselecting the field
3. Insert the cursor before 'ia', since we meant 'Australia' and want to add 'al'
4. Typing 'al'. The 'a' is inserted correctly, after which the cursor is reset to the end of the field.

### Environment

• OS: MacOs 13.4.1
• Browser: firefox and chrome
• Version 119

**Comment by sashamilenkovic** [comment]
@markusgeert This should be resolved at FormKit Pro v0.122.5.
