### ISSUE TITLE
Autocomplete input doesn't work when there is only one option

### ISSUE THREAD

**Issue by ClodClod** [formkit/formkit#1056]
### Reproduction

https://formkit.link/7e34d5ffc15adc8a427f7756e232f7e7

### Describe the bug

In the sample autocomplete input, if you have only one option, doesn't match any results in dropdown list.

A solution could be: https://formkit.link/f90c6532f5a62416c4aabc7129149235 
changing statement in schema section from if: '$matches.length < $options.length' to if: '$matches.lengh <= $options.length' solve the bug

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by fenilli** [comment]
This is an example of how to create an autocomplete, not a full implementation of one, could you elaborate on what the problem is? couldn't seen to duplicate it.

**Comment by ClodClod** [comment]
Hi @fenilli, now I've updated the description of the ticket.

**Comment by fenilli** [comment]
Do you want to make a PR to `docs-content` with that fix?

**Comment by ClodClod** [comment]
Hi @fenilli, yes! Could be useful for other users!
