### ISSUE TITLE
datepicker clearable button doesn't show when using tailwind theme

### ISSUE THREAD

**Issue by AddictivityDeveloper** [formkit/formkit#1059]
### Reproduction

https://formkit.link/7e851bf05ed7f4b3012dd680872a6db7

### Describe the bug

When using the datepicker with the tailwind theme, if you enable 'clearable' and select a date, the clear button isn't visible (it's there, but hidden).

I resolved this with the following in the datepicker section of the tailwind.theme.js file:

`removeSelection: 'w-2.5 mx-1 self-center text-black leading-none absolute top-1/2 right-10 -translate-y-1/2',`

### Environment

• OS: Windows
• Browser: Chrome
• Version: 119.0.6045.200

**Comment by justin-schroeder** [comment]
Ah yeah, looks like regenesis/starter need to add that. Thanks for pointing it out!

**Comment by justin-schroeder** [comment]
This is resolved using regenesis: https://themes.formkit.com
