### ISSUE TITLE
FormKit not working consistently in UnitTests

### ISSUE THREAD

**Issue by abrin** [formkit/formkit#1074]
### Reproduction

https://gist.github.com/abrin/017996308cf6b37ad52b8a3a8c0de137

### Describe the bug

I've been having a really hard time getting tests that use format to consistently work.  When running FormKit in the browser, the tests run properly and without issue, but when run in `vitest` changes to the `v-model` aren't happening, and we're not seeing the `commit` event emitted on the node. (gist with a test attached).  I've been testing this with v1.40.  I've tried:

`flushPromises`, `wrapper.vm.$nextTick()`, and seen in some tests people using `await new Promise((r) => setTimeout(r, 100));` but this too doesn't always work.  

I'm not 100% sure this is a bug, but it is something where documenting how to best test the library might be useful -- or it might be a lot of work that changes as Vue changes, but as this has tripped me up a few times, putting it out there.

### Environment

Vue 3.3, FormKit 1.40, Vitest

**Comment by justin-schroeder** [comment]
Keep in mind that the commit event is debounced by 20ms (by default, controlled by the `delay` prop), this means you do sometimes need await a delay in your tests. However, you shouldn‘t have any specific issues beyond that, feel free to look at the tests in here for any pointers: https://github.com/formkit/formkit/tree/master/packages/vue/__tests__

We often set the `delay` prop to "0" and then use a short timer like `await new Promise(r => setTimeout(r, 10))`.

**Comment by abrin** [comment]
I'll give that a try, thanks!

**Comment by abrin** [comment]
do you by chance know if there is a way to set that in the `config` so it's easy to turn on and off in all tests?
