### ISSUE TITLE
Toggle buttons does not reflect active value when selecting an option with `null` or `undefined` as its value.

### ISSUE THREAD

**Issue by skuhnow** [formkit/formkit#1076]
### Reproduction

https://formkit.link/952d7fefdb3149381a7c703e1d90793f

### Describe the bug

If you create an option like `{ label: 'Unklar', value: undefined, icon: 'schedule' },` or `{ label: 'Unklar', value: null, icon: 'schedule' },` the `value` is always `__mask_1`. 
I expect the value to be `null` or `undefined`

### Environment

• OS: Linux Mint 20.3
• Browser: Firefox 120.01

**Comment by sashamilenkovic** [comment]
@skuhnow This has been resolved at @formkit/pro 0.119.2 (latest tag).

**Comment by maartenvanhunsel** [comment]
@sashamilenkovic looks like the active state is not working when the value is `null` or `undefined`

**Comment by sashamilenkovic** [comment]
@maartenvanhunsel @skuhnow `undefined` is not meant to be used as a value of a FormKit option. However, the active state should now be reflected when selecting an option the value of `null` on version `0.119.5` of FormKit Pro.
