### ISSUE TITLE
nuxt: File is not defined

### ISSUE THREAD

**Issue by sasial-dev** [formkit/formkit#108]
### Reproduction

https://stackblitz.com/edit/github-vqvsuh-xhe2f3?devtoolsheight=33&file=app.vue

### Describe the bug

When creating a validation with an array, I'm getting `[worker] File is not defined`.
Please note that while stackblitz still shows the result, on my end it doesn't load at all.

### Environment

- Formkit: 1.0.0-beta.4 (also was able to repro on beta.5)
- Nuxt: 3.0.0-27428764.271289c (also was able to repro on latest)
- Platform: Mac

**Comment by sasial-dev** [comment]
I meant to put in here, a workaround to put up the top of your formkit config:
```js
// ! TEMP FIX UNTIL BETA 5. SEE FORMKIT ISSUE 108
if (typeof global !== 'undefined') {
    Object.assign(global, { File: function () {} });
}
```

**Comment by justin-schroeder** [comment]
Fixed in `@formkit/nuxt@next` and will be released in beta.5
