### ISSUE TITLE
Unable to update theme on local environment

### ISSUE THREAD

**Issue by alejandrolsca** [formkit/formkit#1082]
### Reproduction

n/a

### Describe the bug

Preconditions:

1. A formkit theme was created using https://themes.formkit.com/editor
2. A theme (formkit.theme.mjs) file exist on the root path of the project.

Steps to reproduce:

1. Run your local/dev server in port 3000
2. Run "npx formkit theme" in the terminal to update your theme

Actual result:

1. You're redirected to the online editor but won't be able to update your theme automatically in your local environment
<img width="472" alt="Captura de pantalla 2023-12-15 a la(s) 2 05 28 p m" src="https://github.com/formkit/formkit/assets/2780325/4fa0c399-1493-479c-9261-d42cc546d358">

Expected result:

1. You will be redirected to the online editor
2. You will be able to update your theme in your local environment (to update the formkit.theme.mjs file)

### Environment

• OS: MacOs Sonoma 14.0
• Browser: Chrome 
• Version: Versión 120.0.6099.71 (Build oficial) (arm64)
"@formkit/pro": "^0.119.2",
"@formkit/vue": "^1.4.0",

**Comment by fenilli** [comment]
Looks like you're running the code while there is something already running at port 3000 so it errors, can you stop the local dev server and try again?
