### ISSUE TITLE
Enable option groups usage with autocomplete

### ISSUE THREAD

**Issue by Maki1878** [formkit/formkit#1083]
### Reproduction

n/a

### Describe the bug

I have a case where I need to group options in an autocomplete input.
It would be nice to have that like it is currently available in select input. 
I need a search so I can't use select in this case.

### Environment

• OS: Windows
• Browser chrome
• Version 120.0.6099.72 (Official Build) (64-bit)

**Comment by davidwatson249** [comment]
Do we have a timeline for when this will be available? We need this as well.

**Comment by sashamilenkovic** [comment]
@Maki1878 @davidwatson249 We've just begun work on this. Hopefully we can have this implemented within the next couple of weeks.

**Comment by sashamilenkovic** [comment]
@Maki1878 @davidwatson249 Hey there! As of FormKit Pro v0.123.0, option groups are available to the `autocomplete`, `dropdown`, and `taglist` inputs: https://formkit.com/inputs/autocomplete#option-groups
