### ISSUE TITLE
Error: Unknown input type "multi-step" in kitchen sink

### ISSUE THREAD

**Issue by matsn0w** [formkit/formkit#1084]
### Reproduction

https://formkit.link/31bc4f96e6bb75042194f6eab18f2fff

### Describe the bug

The new `FormKitKitchenSink` component throws an error on the multi-step form component. There are more warnings, but they are probably a side-effect from the error.

### Environment

• OS: macOS Sonoma 14.2
• Browser: Google Chrome 120
• Version: 1.4.x

**Comment by sashamilenkovic** [comment]
@matsn0w This is just a matter of the required dependencies, such as `@formkit/addons`, not being added into the `formkit.config` of the playground. Here is a workaround with the appropriate import maps and `formkit.config`: https://formkit.link/03a2ddfc87b68677811ac6c9b8f45803. Alternatively, you can disable certain groups of inputs from the `FormKitKitchenSink` component by passing a `schemas` array prop with the values of the inputs you want to view, or remove `pro` entirely: https://formkit.link/7bad4be8b8bc6f9e20f0292804eabf05

**Comment by matsn0w** [comment]
🙈
