### ISSUE TITLE
Select input with placeholder is sometimes not navigatable via keyboard Firefox

### ISSUE THREAD

**Issue by fdverwoerd** [formkit/formkit#1085]
### Reproduction

https://formkit.link/e361f97f72d006602b89945cfd08c8c8

### Describe the bug

So when you focus the input before the select and then 'tab' into the select and press spacebar. You want to use arrow keys to choose one item. But the arrow keys do not seem to work;

It does work in Safari where the placeholder is shown as an option.
It does work in Chrome where using arrow keys properly focuses options.

### Environment

• OS: MacOS
• Browser Firefox
• Version 120

**Comment by sashamilenkovic** [comment]
@fdverwoerd Unfortunately, this is just seems to be the way Firefox is handling keyboard navigation with a disabled option value. As a workaround, you could remove the placeholder and assign your options like so: https://formkit.link/7f9dd2c1a17f0af306a95ff255561ce7.
