### ISSUE TITLE
`data-invalid` vs `data-errors` on inputs when validating

### ISSUE THREAD

**Issue by jjjrmy** [formkit/formkit#1097]
### Reproduction

https://formkit.link/a2a12ff70a8c5d59befd92df52508491

### Describe the bug

ZodPlugin sets `data-invalid="true"` and we get the nice red ring ...
But setting the error with `formNode.setErrors()` gives us `data-errors="true"`

### Environment

latest

**Comment by justin-schroeder** [comment]
@jjjrmy is the idea here to have *less* nuance between the two, or a suggestion that we should improve the styling of starter/regenesis? Validation and errors are not considered the same thing (for example — one is blocking one is not) and thus they could be styled differently.

**Comment by jjjrmy** [comment]
I made an issue for the styling on the theme, I think probably it should be addressed there because I understand what you're saying.
