### ISSUE TITLE
DatePicker access to min-date display error " Cannot read properties of null (reading 'getFullYear')"

### ISSUE THREAD

**Issue by ghost** [formkit/formkit#1101]
### Reproduction

https://formkit.com/inputs/datepicker

### Describe the bug

When i try to acces to years with lower of min-date "2023" in this case :

   ` <FormKit
      type="datepicker"
      name="date"
      label="Conference date"
      placeholder="Select a date"
      help="When are you hosting your next conference?"
      picker-only
      min-date="2023-12-30T22:29:13.113Z"
    />`
![date-picker](https://github.com/formkit/formkit/assets/99481334/78d2132e-fe0d-4e63-9470-2894a4e0d841)

### Environment

>  Browser [chrome]
> "@formkit/pro": "^0.119.2",
> "@formkit/vue": "^1.3.2",

**Comment by abde2022** [comment]
Hi @justin-schroeder,
I check it, But still the same bug.
![still-same-error](https://github.com/formkit/formkit/assets/99481334/ec442729-bdc6-46ad-81fa-92aeddb21bee)

**Comment by justin-schroeder** [comment]
correct, i was only making a reproduction with steps since there was none provided in the original post.

**Comment by sashamilenkovic** [comment]
This should be resolved at FormKit Pro v0.126.4
