### ISSUE TITLE
Email input causes hydration errors in Nuxt

### ISSUE THREAD

**Issue by hecktarzuli** [formkit/formkit#1104]
### Reproduction

https://codesandbox.io/p/devbox/formkit-nuxt-email-hydration-bug-yvlypj

### Describe the bug

If you use the email input, it causes hydration errors in Nuxt.

Recreate:
1) use an email input on a page in a nuxt project
2) slow down your browser network to Fast 4G (or similar)
3) refresh the page with the input (it may take a couple refreshes)
4) notice the hydration error in the browser console.

![image](https://github.com/formkit/formkit/assets/2112282/03ecdb4a-85fd-4683-8ccc-d9578f34f121)

### Environment

Nuxt 3.9.0 (and older versions too)
Formkit 1.4.0 (and 1.2.2 as well, probably more)

**Comment by andrew-boyd** [comment]
I'm not seeing this. Any other steps you can think of for reproducing the issue?

![Screenshot 2024-01-05 at 11 03 20 AM](https://github.com/formkit/formkit/assets/2946356/83949543-208a-41a9-8a38-8a780ac0ad30)
![Screenshot 2024-01-05 at 11 03 12 AM](https://github.com/formkit/formkit/assets/2946356/f9faff14-dd74-42f7-a65a-bd9b3d6c5a6c)

**Comment by hecktarzuli** [comment]
https://github.com/formkit/formkit/assets/2112282/d4522c00-7e50-4123-84ea-daf4cd9604f3

**Comment by hecktarzuli** [comment]
I've narrowed this down to our mandatory LastPass extension :(. I tested Chrome/Incogneto = clean, FF = Clean, Chrome in Browserstack = Clean.. ug.
