### ISSUE TITLE
formkit/cli use axios with vulnerabilities

### ISSUE THREAD

**Issue by ikreb7** [formkit/formkit#1107]
### Reproduction

https://github.com/formkit/

### Describe the bug

I run yarn audit and get this result:

![grafik](https://github.com/formkit/formkit/assets/18120230/dfcc633b-0256-4cd9-8274-1d68453d6f82)

You have only to upgrade the axios dependency.

### Environment

• OS: Linux
• Version "formkit": "^1.4.0"

**Comment by sashamilenkovic** [comment]
@ikreb7 This has been addressed on the upcoming FormKit release 1.5.x.

**Comment by ikreb7** [comment]
Thank you!
