### ISSUE TITLE
Unable to overwrite formkit inputs of multi-step plugin using sections-schemas

### ISSUE THREAD

**Issue by amueller82** [formkit/formkit#1110]
### Reproduction

https://formkit.link/d4f950d06b9cde63601a13b7db765b51

### Describe the bug

I was trying to overwrite the Inputs of the multi-step plugin using sections-schema. Against expectation - nothing is changing. So either it is not support or functionality is broken - please see my playground link (https://formkit.link/d4f950d06b9cde63601a13b7db765b51) for reproduction.

### Environment

• OS: macOs
• Browser chrome
• Version 120.0.6099.129
• Formkit: 1.4.0

**Comment by andrew-boyd** [comment]
This has been fixed in `1.5.4`. If you clear your cache on the playground you should now see the expected results in your playground link.
