### ISSUE TITLE
Not possible to set FormKit locale with `autoImport: true`

### ISSUE THREAD

**Issue by gbyesiltas** [formkit/formkit#1112]
### Reproduction

https://stackblitz.com/edit/github-wje2vn?file=app.vue

### Describe the bug

While using `autoImport` on Nuxt, using the strategy from [the docs](https://formkit.com/essentials/internationalization#using-root-config) to set the FormKit locale results in the following warning and the locale isn't set:
```
[Vue warn]: injection "Symbol(FormKitConfig)" not found.
```

It kind of makes sense that this happens, but I believe it's still a bug because at worst it's not possible to change the FormKit locale while this feature is on, and at best the docs are wrong.

### Environment

• OS: macOS
• Browser: Safari
• Version: 17.1.2

**Comment by justin-schroeder** [comment]
Thanks for the reproduction. We’ve added a new `changeLocale` function that you can import from `@formkit/vue` or `@formkit/i18n` that allows you to perform this swap globally without the provide/inject madness :) Currently it is published on the `@next` tag, and will be in general release whenever the next version is published.

**Comment by gbyesiltas** [comment]
> Thanks for the reproduction. We’ve added a new `changeLocale` function that you can import from `@formkit/vue` or `@formkit/i18n` that allows you to perform this swap globally without the provide/inject madness :) Currently it is published on the `@next` tag, and will be in general release whenever the next version is published.

Thank you! <3
