### ISSUE TITLE
"AddAsterixPlugin" breaks the Dropdown & Autocomplete Fields

### ISSUE THREAD

**Issue by coatesjonathan** [formkit/formkit#1113]
### Reproduction

https://formkit.link/fe81ddad8bd519d1af3451237f1653cc

### Describe the bug

When using the official "AddAsterixPlugin" provided on the Formkit docs, it breaks certain Pro fields, such as the `Dropdown` and `Autocomplete` field's layout, and the options do not appear.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by fenilli** [comment]
Ok so looking into it, seens like a problem with autocomplete and repeater autocomplete and dropdown: https://formkit.link/53b72e2a6eb3725163af184064d20923

**Comment by fenilli** [comment]
As a workaround ( not sure what the full implications it is yet ) you can remove the line:

```js
node.props.definition.schemaMemoKey = `required_${node.props.definition.schemaMemoKey}`  
```

**Comment by coatesjonathan** [comment]
> As a workaround ( not sure what the full implications it is yet ) you can remove the line:
> 
> ```js
> node.props.definition.schemaMemoKey = `required_${node.props.definition.schemaMemoKey}`  
> ```

Yeah this works as a fix, but does this have a knock on effect?

**Comment by justin-schroeder** [comment]
Thanks for the heads up!

In version 1.4 we introduced the `context.state.required` which indicates whether or not an input is actually required or not. This makes all this much easier.

https://formkit.link/39ef1ce063059b72671fc5f15d1295c6

Docs have been updated with this version too 👍

**Comment by coatesjonathan** [comment]
Awesome thanks @justin-schroeder this fixes it perfectly! :)
