### ISSUE TITLE
[Bug ] When i assign new id after destory node old id  getNode not Work

### ISSUE THREAD

**Issue by aakash-goswami-ciyaza** [formkit/formkit#1116]
### Reproduction

https://formkit.link/13d12d11c2dc527593d8b85658c6153e

### Describe the bug

When i try to assign id in drictly to node (ex = node.props.id = "item0")  after destory old node id (item1) and assign to new id ("item0") .Then i use getNode("item0") give to undifind 
How to assign new id ? then getNode Work.

**Comment by aakash-goswami-ciyaza** [comment]
can i reassign id using getNode ?

**Comment by justin-schroeder** [comment]
no
