### ISSUE TITLE
TouchEvent does not exist on Safari MacOS

### ISSUE THREAD

**Issue by taidaid** [formkit/formkit#1123]
### Reproduction

https://formkit.com/playground?fkv=latest&fileTab=Playground.vue&css-framework=genesis&files=jc%5B%28%27name%21%27PJd.vue%27%7EVitor%21%27%3Cscrip7setup68+ESM+im_5arBeDfrom+URLYhttps%3A8cdn...%7D08WwellWsecondary+pJDfileY.%2FOtherFile.vue%7D.09script6ZH3%3CFormKit033typeGtransferlistN3labelGFormKi7InputN3helpGVi7mQto+ge7startVN3%3AAsG%5BX1%22%2C+X2%22%5DN%2F69HZstylQscopV6%2F*0Thi5filB5TailwinDCSS.+00If+you+neeDvanilla+CSS+i7can+go+here.0*%2F09style6%27%7EaddV%21true%29%5D0%5Cn3++4%5C%275s+6%3E07t+8%2F%2F9%3C%2FAoptionBQsup_Dd+G%3D4Htemplate6JlaygrounN403Qe+VedW+a5X%22A-Y5%7BZ0%3C_port%01_ZYXWVQNJHGDBA98765430_

### Describe the bug

FormKit uses

```js
  if (e.event instanceof TouchEvent) {
    state2.longTouch = false;
    clearTimeout(state2.longTouchTimeout);
  }
```
in "@formkit/drag-and-drop/dist/index.js".

This is occurring on the Transfer List component for us.

I do not personally have access to Safari, but my colleagues are able to reliably reproduce this.

I received notification of this error via Sentry, let me know if you need any more information, I have access to stack traces, etc.

### Environment

• OS: Mac OS X
• Browser Safari 
• Version 17.2.1

**Comment by sashamilenkovic** [comment]
@taidaid This should be resolved at [@formkit/pro](https://www.npmjs.com/package/@formkit/pro/v/0.119.6) at v0.119.6.
