### ISSUE TITLE
single-select Dropdown `selection-removable` prop does not work as expected

### ISSUE THREAD

**Issue by parsajabbari** [formkit/formkit#1125]
### Reproduction

https://formkit.com/playground?fkv=latest&fileTab=dropdown-selection-removable.vue&css-framework=genesis&files=jc%5B%28%27nX%21%27L-sUecP-removable.vM%27%7Eedit_%21%27%3Cscripjsetup4consj6s+%3D+%5B8React1react2VM1vM2AnguTr1anguTr2SvUW1svUWQ0%5D07script4qJOD+Zf_mz%23default5%28BHz%3AacPs5false34*ODY*ZL9nX569TbU5ChoosNa+fronWnd+69G5ExamplNG9%3AopPs56s9valM5vM3Y%2F4*OprNwrap%3E%28%28BH%297pre4*7D47Jqstyle%3E7style4%27%7Eadded%21trM%29%5D*++0%5Cn1%22%2CBI2Q83%5C%274%3E05%3D36frXw_k7%3C%2F80*%28+TbUI93Y*B+valMDF_mKitGpTceholderH+%29I%3A+%22JWmpTW4LdropdownMueNe+O*%3CPtionQ%22H%2CTlaUelWteXameY0**Ztype5_orjt+q0%3Cz3+%01zqj_ZYXWUTQPONMLJIHGDB9876543210*_&imports=jc%28%27name%21%27ImportMap%27%7Elang%21%27json%27%7Eeditor%21%27%28*+1vue%5C%211https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fvue%403%2Fdist%2Fvue.esm-browser.min.js0*%29*%27%29*%5Cn0%5C%271+0%0110*_

### Describe the bug

We noticed that single-select Dropdowns still allow the user to deselect the current selection and go back into an unselected state, even though the  `selection-removable` boolean prop is documented as being `false` by default.

We have additionally tried explicitly setting the prop to false, e.g. `:selection-removable="false"` but this doesn't work either.

We have duplicated this using a FormKit Playground linked in this issue, using at least v1.4 and v1.5, though the issue may apply to other versions. 

### Environment

• OS: macOS 14.2.1
• Browser: Chrome
• Version: 120

**Comment by sashamilenkovic** [comment]
@parsajabbari Related issue here: https://github.com/formkit/formkit/issues/1012. You can use the prop `deselect` to prevent deselection from the listbox itself. We will get this added to the documentation. Here is an example where the prop is used based on your playground: https://formkit.link/c4a95320f89c65b880901c4080a8b79f

**Comment by parsajabbari** [comment]
This worked for us! Glad to know it's just a documentation issue and not a bug. Thanks @sashamilenkovic!

**Comment by krolc** [comment]
@sashamilenkovic do you know what the flag is for the "open-on-remove" as well? When we add deselect="false" we can't deselect an item which is good but also the dropdown stays open. We would like it to close every time something is selected regardless of if its currently selected or not.

**Comment by sashamilenkovic** [comment]
@krolc I've created a separate issue for this here: https://github.com/formkit/formkit/issues/1126
