### ISSUE TITLE
Colorpicker keyboard arrow keys do not work when value is set to null.

### ISSUE THREAD

**Issue by fenilli** [formkit/formkit#1127]
### Reproduction

https://formkit.link/0f45a111952c43584c6caf034b58a954

### Describe the bug

Colorpicker keyboard arrow keys do not work when value is set to null.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by andrew-boyd** [comment]
This was resolved in version `0.122.6` of FormKit Pro
