### ISSUE TITLE
Input mask loses the value

### ISSUE THREAD

**Issue by CavalcanteLeo** [formkit/formkit#1128]
### Reproduction

https://formkit.link/e6fe2459c0bcfd95bc27c8dd77bab5a1

### Describe the bug

Just type the number 1 a few times, easy to reproduce

### Environment

• OS: MacOS
• Browser chrome

**Comment by justin-schroeder** [comment]
By default incompletely masks return no value — when used an currency anytime those repeating sets of 3 digits are not found the mask is "incomplete". Just add the `allow-incomplete` prop:

https://formkit.link/fd6f46c8ebacc66bafcb2ec412c50325
