### ISSUE TITLE
Type Mismatch Error with v-model and TypeScript for FormKit's datetime-local Component

### ISSUE THREAD

**Issue by florivdg** [formkit/formkit#1129]
### Reproduction

https://stackblitz.com/edit/formkit-datetime-local?file=src%2FApp.vue

### Description

I encountered a type mismatch error in TypeScript when using the `datetime-local` component from FormKit with a v-model bound to a `ref<string>`. The TypeScript compiler throws an error stating that a string type is not assignable to an expected undefined type.

### Steps to reproduce

1. Create a Vue component using FormKit's `datetime-local` component.
2. Bind the `v-model` to a `ref<string>` in TypeScript.
3. Run `npm run build` and observe the TypeScript compilation error.

### Expected Behavior

The v-model binding with a `ref<string>` should be compatible with the `datetime-local` component without causing TypeScript errors since they both have strings as values.

### Actual Behavior

TypeScript compilation fails with the following error:

```sh
src/App.vue:4:5 - error TS2322: Type 'string' is not assignable to type 'undefined'.

4     v-model="d"
      ~~~~~~~

  node_modules/@formkit/inputs/dist/index.d.mts:591:5
    591     modelValue: PropType<Props, 'value'>;
            ~~~~~~~~~~
    The expected type comes from property 'modelValue' which is declared here on type 'NonNullable<(Omit<Partial<FormKitBaseProps>, "number" | "type" | "value"> & Omit<Partial<FormKitRuntimeProps<{ type: "datetime-local"; modelValue: string; label: string; help: string; validation: string; validationVisibility: string; }, unknown>>, "number" | ... 1 more ... | "value"> & Omit<...> & Partial<...> & { ....'


Found 1 error in src/App.vue:4
```

### Environment

FormKit Version: 1.5.0
Vue Version: 3.4.13
TypeScript Version: 5.2.2

**Comment by florivdg** [comment]
I just found out that the problem is caused by using `datetime-local` (kebab cased) as the input type (which is what the docs say). When using `datetimeLocal` (camel cased) it works fine.
So either the docs should be updated or the props key should be renamed or aliased to conform to web standards and the official `datetime-local` input.

**Comment by gbyesiltas** [comment]
Hey, we're still experiencing this exact issue. I think [this](https://github.com/formkit/formkit/pull/1486) should fix it?
