### ISSUE TITLE
Rollup (via Nuxt) shows a bunch of warnings at build time

### ISSUE THREAD

**Issue by hecktarzuli** [formkit/formkit#1130]
### Reproduction

https://no-preview-sorry.net

### Describe the bug

When using formkit with Nuxt, you get rollup warnings when you do a production build.

<img width="1317" alt="image" src="https://github.com/formkit/formkit/assets/2112282/17204dfa-dbbf-461d-956b-fdca07207ca9">

### Environment

Formkit 1.4.0
Node 3.9.1
Rollup 4.9.4

**Comment by justin-schroeder** [comment]
That should be fixed in 1.5 — try upgrading

**Comment by hecktarzuli** [comment]
> That should be fixed in 1.5 — try upgrading

What's the proper way to update?  Last time I just upgraded everything, but is there something better like just upgrading @formkit/core?
![image](https://github.com/formkit/formkit/assets/2112282/2a0075a6-f5b5-4d16-9aac-1df02214ab56)

**Comment by hecktarzuli** [comment]
Looks resolved in 1.5, thanks!
