### ISSUE TITLE
Version mismatch with @formkit/core when using the pro plugin

### ISSUE THREAD

**Issue by Rednas83** [formkit/formkit#1138]
**Formkit.config.ts**
![image](https://github.com/formkit/formkit/assets/25219229/1bde138f-4b02-46a9-a537-fd0992c2ffac)
**Github Copilot**
![image](https://github.com/formkit/formkit/assets/25219229/e2d589b8-ed86-4a81-8c71-159d9b7fbbbd)
**Package.json**
![image](https://github.com/formkit/formkit/assets/25219229/02451457-fbae-49d4-9f53-eda8fd64d156)

**Comment by sashamilenkovic** [comment]
@Rednas83 I just ran a fresh install and could not replicate this. Any chance you can try clearing out your node_modules and .lock files and reinstalling again?

**Comment by Rednas83** [comment]
Tried that, but only solution for me was to downgrade everything to `1.5.0`.

I am using pnpm btw. Could it be related with that?

**Comment by sashamilenkovic** [comment]
I don't think it has anything to do with the package manager; I just used `pnpm` myself. If the reinstall didn't work then I think the next step would be to make a reproduction.

**Comment by fenilli** [comment]
Are you using the create-app from FormKit or doing it yourself with the nuxt installer and installing the packages manually?

**Comment by Rednas83** [comment]
Just tried updating the packages on a different machine and it works.
