### ISSUE TITLE
Adding asterisk to required field, if it's a single checkbox

### ISSUE THREAD

**Issue by willans** [formkit/formkit#1141]
### Reproduction

https://formkit.link/be7a83f434809e0620093b4f147d1ed1

### Describe the bug

Hi

In frequent scenarios, I'd often have a single required (or accepted) checkbox - for example, 'I agree to the terms'.

I've [updated](https://formkit.link/be7a83f434809e0620093b4f147d1ed1) the asterisk demo simply by adding a new FormKit checkbox field. 

At this point, the checkbox label is neither a traditional label or a legend - so the checkbox won't appear. 

Been racking my brains over this one and can't make any progress. I'd also attempted to do a check at `legendOrLabel` to see if node.props.options exists. That seemed to do the trick if it was a one off - but as soon as I also included other checkbox/radios with options, it messed up everything depending on the order.

[Second demo here](https://formkit.link/d728b150e8dd14ea18aafe3f4dbfd5a0).

Any help would be appreciated.

### Environment

• OS: MacOS 14.2.1 
• Browser: Chrome
• Version: 120.0.6099.234

**Comment by justin-schroeder** [comment]
@fenilli can you update the example linked on the docs with this? Thanks!

**Comment by willans** [comment]
@fenilli thanks for taking a look, but it appears you got to the same point I did. 

If you look at your link, the 'hello' checkboxes, each value now has 'hello' as each checkbox option label.

**Comment by fenilli** [comment]
> @fenilli thanks for taking a look, but it appears you got to the same point I did.
> 
> If you look at your link, the 'hello' checkboxes, each value now has 'hello' as each checkbox option label.

Yes it seens we also removed the options check to see if its multi: https://formkit.link/81e730c233d09c516460eed4dfe7a9a5 this is the old one but with the schemaMemoKey fix and using the new `$state.required`.

**Comment by willans** [comment]
The `schemaMemoKey` fixed it. Thanks for your support @fenilli. Will mark this as closed now.
