### ISSUE TITLE
Issues with peer dependencies

### ISSUE THREAD

**Issue by michael-hillmann** [formkit/formkit#1142]
### Reproduction

not applicable

### Describe the bug

During installing the formkit, pnpm warn with an unmet peer dependency:

```
pnpm install @formkit/nuxt
 :
WARN Issues with peer dependencies found
.
└─┬ @formkit/nuxt 1.5.1
  └─┬ unplugin-formkit 0.2.12
    └── ✕ unmet peer rollup@^3: found 4.9.4
```

### Environment

- OS: Windows 11
- Browser: Chrome
- Version: Version 120.0.6099.225 (Offizieller Build) (64-Bit)
- Nuxt 3.9.1
- pnpm 8.14.2

**Comment by justin-schroeder** [comment]
This is in 1.5.2
