### ISSUE TITLE
Placing a Group inside a Repeater and adding an 'if' condition may lead to data confusion.

### ISSUE THREAD

**Issue by ruibaby** [formkit/formkit#1144]
### Reproduction

https://formkit.link/e4ffc8baf7ab40fa21422dfe9c820587

### Describe the bug

When the name is 'block1':

<img width="961" alt="image" src="https://github.com/formkit/formkit/assets/21301288/9b18a151-7e16-46f1-9c4d-5b4333f3e889">

When switching the name to 'block2':

<img width="1915" alt="image" src="https://github.com/formkit/formkit/assets/21301288/f4bd5a07-c1e2-45d1-8d10-81efccff30e6">

it must be:

```json
{
  "blocks": [
    {
      "name": "block2",
      "block2_config": {
        "title2": "Title 2",
        "url2": "Url"
      }
    }
  ]
}
```

### Environment

• OS: macOS
• Browser Chrome
• Version 1.5.x

**Comment by justin-schroeder** [comment]
Hi @ruibaby 👋 — for adjacent conditionals like that you’ll want to add a `key` to prevent inappropriate dom recycling:

https://formkit.link/dfa655fc6e7cbb0c1151a7f1782c2f18

Best of luck out there 👍
