### ISSUE TITLE
Autocomplete option holder scrolls to top after loading more options

### ISSUE THREAD

**Issue by zsilbi** [formkit/formkit#1149]
### Reproduction

https://formkit.link/8cd6148f9a4cb4998a6a2fc5726496b1

### Describe the bug

I tried the official examples here: [formkit.com: Autocomplete - Option loader](https://formkit.com/inputs/autocomplete#option-loader)
When I click on "Load more" after the last option, the option holder scrolls to the top. It should stay there after the options are populated.

### Environment

• OS: Windows
• Browser: Chrome, Firefox
• Version: latest stable

**Comment by sashamilenkovic** [comment]
@zsilbi Oh yeah, I see that as well. Will take a look.

**Comment by zsilbi** [comment]
@sashamilenkovic it works fine with the 0.118 version of @formkit/pro

**Comment by sashamilenkovic** [comment]
@zsilbi @formkit/pro v0.119.12 is not out. Can you give that a try and let me know if that solves this issue for you?

**Comment by zsilbi** [comment]
It's working, thanks a lot!
