### ISSUE TITLE
Behavior of global defined custom rules (not running in sequence)

### ISSUE THREAD

**Issue by ddoebertin** [formkit/formkit#1151]
### Reproduction

https://formkit.link/f33c1959a0880994198885221cce1c1b

### Describe the bug

Hi Team, I noticed a bug regarding the behavior of global custom rules.
My custom rule doesn't stop the validations being executed (they are not running in sequence).
As you can see here (https://formkit.link/f33c1959a0880994198885221cce1c1b) two error messages displayed instead of just one:

- please use monday or mon
- FormKit Input must be greater than or equal to 2 characters.

I thought that the rule "length:2" won't be executed before the "global monday" rule "is valid".

Please give me a hint on how to avoid this. 
Thanks a lot,
Daniel 

### Environment

• OS: macOS
• Browser chrome
• Version 100.x

**Comment by ddoebertin** [comment]
Hi, I noticed this bug in my local nuxt app, using the following versions:
 "@formkit/nuxt": "1.5.2",
 "vue": "3.4.15",
 "nuxt": "3.9.3"
So the behavior in my local app is the same as in the provided playground example.

**Comment by justin-schroeder** [comment]
Hey @ddoebertin we were able to isolate this down to your `formkit.config.js` in the example exporting the return of `defaultConfig()` which is already done for you — this was leading to 2 validation plugins running at the same time.

By some mysterious miracle of the earth and stars aligning with noorse god of thunder’s toenail it was not causing issues in 1.4.0.

I would check your local `formkit.config.ts` and see if there is something going on there like a double import. Feel free to post back here your setup and we can help sort it 👍

**Comment by ddoebertin** [comment]
Hey @justin-schroeder, you are right, without the defaultConfig it's working as expected. Thanks a lot.
I copied the code from here https://formkit.com/getting-started/installation 
![image](https://github.com/formkit/formkit/assets/136339793/964865ef-d748-4b39-92fd-c632f515d98b)
Maybe you should adopt this example snippet.
Have a nice day,
Daniel

**Comment by andrew-boyd** [comment]
@ddoebertin You're still going to want (probably) `defaultConfig()` in your local project. It's just that the config exported from `formkit.config.js` in the playground on formkit.com passes the exported object into `defaultConfig()` in the background. So - by exporting a call to `defaultConfig` in the playground you were inadvertently passing it through twice.

Kinda an edge-case with the playground — if you create a new playground and add a `formkit.config.js` file you'll see that it exports a plain object because of this.
