### ISSUE TITLE
FormKit #default="{ state: { valid } }" gives some TypeScript and eslint errors

### ISSUE THREAD

**Issue by lmc3s3f0r** [formkit/formkit#1154]
### Reproduction

https://formkit.com/playground?fkv=latest&fileTab=Playground.vue&css-framework=genesis&files=jc%5B%28%27name%21%27Playground.vue%27%7EedVT%21%27%3CscripWsetup3consWM+%3D+%7B%7D+%3D%3EXlert%7B%22A%27%3A%22%7DC6script3C%3CJ1%3C7*HfTmQ%3Aactions5falseQ%40sD5MQ%23default5YstaU%3A+IZ0C18h2+class5Uxt-xl+font-bold+mb-40%3EA6h287*1HeNQ1label5EBQ1help5EnUrGeB+toLGpOQ19ation5RquiRd%7CeNQj7+HsD_%3Adisabled5%27%3A9_jpR+wrap%3EFTm+9Vy%3A+%28I%296pR316736J%27%7Eadded%21true%29%5D*C110%5C%271++3%3EC5%3D06%3C%2F7FTmKV8%3E*%3C9validAPOLBNXddRssC%5CnDubmVG+your+Htype5IY9ZJUmplaU3L+RsetMhandleSDNmailOasswTdQ0*RreTorUteVitWt+X+aY%28+Z+%29_0+j%2F8%01j_ZYXWVUTRQONMLJIHGDCBA98765310*_

### Describe the bug

In FormKit 1.4.0, you could define 'v-slot#default="{ state: { valid } }"' to use that "valid" value however you want (in my case, I use it to enable/disable some buttons that are outside the FormKit, accessing valid with "const form = ref()" in <script> and ':enabled="form.node.context.state.valid"' in the <template>.

Since 1.5.0, 'v-slot#default="{ state: { valid } }"' must be defined as '#default="{ state: { valid } }"' (without "v-slot") to avoid some warnings in Chrome console. But this results one new warning and an error:

The warning: "Expected 'v-slot' instead of '#default'.eslint[vue/v-slot-style](https://eslint.vuejs.org/rules/v-slot-style.html)"
The error: "'valid' is defined but never used.eslint[vue/no-unused-vars](https://eslint.vuejs.org/rules/no-unused-vars.html)" (because, as I said, I'm checking valid in a component outside <FormKit>).

Both the warning and the error didn't appear when I used v-slot#default.

I have everything up-to-date (Nuxt, Vue, eslint, typescript, etc), but can't get rid of both the warning and the error message. What can I do?

### Environment

• OS: Ubuntu 22.04
• Browser: Chrome
• Version: 1.5.1
• Code editor: VS Code

**Comment by justin-schroeder** [comment]
I dont think these issues have anything to do with FormKit but rather your other dependencies being updated. If you provide a specific reproduction repository perhaps we can take a look.
