### ISSUE TITLE
1.5.x breaks reactivity in validation

### ISSUE THREAD

**Issue by paulhaem** [formkit/formkit#1155]
### Reproduction

https://formkit.link/191b7062c6c0cc4c154b4a2c3ab0aebb

### Describe the bug

In 1.4.x the second field gets re-validated after updating its value.
In 1.5.x the second field gets only re-validated after the value of the first field has been updated.

### Environment

• OS: Windows 10
• Browser: Firefox
• Version: 123.0b2 (64-bit)

**Comment by justin-schroeder** [comment]
This should be fixed in 1.5.3
