### ISSUE TITLE
Autocomplete Load More and hasNextPage Problems

### ISSUE THREAD

**Issue by kadirboylu** [formkit/formkit#1159]
### Reproduction

https://formkit.link/6f676e2de505d2356a06098a173f49d3

### Describe the bug

According to the documentation, if there is no search parameter, an empty array is returned. However, in some cases, we need to send a request and list the incoming data, even if the search is an empty string. In this case, we encounter a bug. What can we do to solve this problem?

Do this steps when search is empty string.

Steps for first problem:
- Focus and see dropdownWrapper. You will see the page (skip) as 1
- Lose focus and close dropdownWrapper and focus it again. You will see the page (skip) as 2

Video: https://streamable.com/mkz3hd

Steps for second problem:
- Focus and see dropdownWrapper. You will see the page (skip) as 1
- Click the load more button.
- Lose focus and close dropdownWrapper and focus it again. You will see the page (skip) as 3

Video: https://streamable.com/uxd93f

### Environment

• OS: Windows
• Browser Chrome
• Version 1.5.x

**Comment by sashamilenkovic** [comment]
@kadirboylu Good question! I can see why this would be a bit confusing.

The `autocomplete` input by default has the prop `always-load-on-open` set to true. This means anytime the autocomplete is expanded, we are directly calling the `options loader` function. This is why you are seeing the page increment erroneously (the `load options` function is being called too many times).

By setting the prop `always-load-on-open` to false, you will see this function behave more like how you would expect: https://formkit.link/01e8552a38d3a03faf8f187275f2ff1a

We could maybe point out this prop `always-load-on-open` a bit more in the autocomplete and taglist docs specifically.

Let me know if you have any more questions.

**Comment by kadirboylu** [comment]
@sashamilenkovic thank you for your quick response and detailed explanation 🙂 Is there an easy way to change the default value of the `always-load-on-open` prop for all autocomplete inputs? I dont want to add `:always-load-on-open="false"` by one by

**Comment by sashamilenkovic** [comment]
@kadirboylu No problem at all! Here's an example of using a FormKit plugin to always set `always-load-on-open` to false for the autocomplete: https://formkit.link/33c6705a1f7143317e0b636f50e3a7af.

**Comment by kadirboylu** [comment]
@sashamilenkovic thank you for everything!! 🥳😄
