### ISSUE TITLE
[Slider][Datepicker] Z-index problem between slider and datepicker

### ISSUE THREAD

**Issue by apiret** [formkit/formkit#1166]
### Reproduction

[Reproduction](https://formkit.com/playground?fkv=latest&fileTab=Playground.vue&css-framework=genesis&imports=jc%28%27name%21%27ImportMap%27%7Elang%21%27json%27%7Eeditor%21%27%28*+1vue%5C%211https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fvue%403%2Fdist%2Fvue.esm-browser.min.js0*%29*%27%29*%5Cn0%5C%271+0%0110*_&files=jc%5B%28%27name%21%27Playground.vue%27%7Eeditor%21%27%3CI8+HdApickerBtart+DALinG3EELaxG5EE9+%2F8Hslider*name4duration*%3Avalue4%5B1%2C+15%5DLin41Lax430*tooltip4trueBlider9%2FJ%3C%2FIJ%27%7Eadded%21true%29%5D*974%3D9C77++8%3E6%3CFormKit9%5C%276AateB*label4SC%5CnE-01G-dA4202H67type4ItemplAJ%3ECL*m%01LJIHGECBA98764*_)

### Describe the bug

When you place a datepicker above a slider in a form and open the datepicker, you get what you can see in the screenshot.

![z-index issue](https://github.com/formkit/formkit/assets/1142871/113f3455-3a28-48cd-838a-f9d66f5b6b56)

### Environment

• OS: [osx]
• Browser [chrome/firefox]
• Version [chrome version: 121.0.6167.85]

**Comment by andrew-boyd** [comment]
We'll still be fixing this for the theme, but if you use the new `popover` prop that was released today in FormKit Pro `0.120.0` then you should no longer have z-indexing conflicts.

https://formkit.com/changelog?view=pro#_01200-beta

**Comment by andrew-boyd** [comment]
This has been fixed — run `npx formkit@latest theme` in your project to update your theme.
