### ISSUE TITLE
Include FormKitIcon in Nuxt automatic imports 

### ISSUE THREAD

**Issue by Rednas83** [formkit/formkit#1168]
### Reproduction

https://formkit.link/7fb65430cfb6106cb96dea2d8a9d66cb

### Describe the bug

**Terminal**
![image](https://github.com/formkit/formkit/assets/25219229/62f12494-311e-4663-94cd-bbba2efe9949)
**Tried**
* AutoImporting
`<FormKitIcon icon="heart" />`
* Registering 
```
import { defaultConfig } from "@formkit/vue";
import { en } from "@formkit/i18n";
import { createProPlugin, inputs } from "@formkit/pro";
import { genesisIcons, heart } from "@formkit/icons";
import { rootClasses } from "./formkit.theme";
import { env } from "./env";

const pro = createProPlugin(env.FORMKIT_PASSWORD, inputs);
export default defaultConfig({
  plugins: [pro],
  locales: { en },
  locale: "en",
  config: { rootClasses },
  icons: { ...genesisIcons, heart }
});
```

The only way I get them to work is directly with FormKit
```
<FormKit prefix-icon="email" />
<FormKit suffix-icon="settings" />
<FormKit type="select" select-icon="caretDown" />
```

Looks like `FormKitIcon` is missing. Should it be registered or should it be available on default?

### Environment

```
------------------------------
- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     3.10.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.15.0
- Builder:          -
- User Config:      telemetry, vite, modules, build, routeRules, components, content, formkit, imports, css, devtools
- Runtime Modules:  @vueuse/nuxt@10.7.2, normalizedModule(), @nuxt/content@2.11.0, @pinia/nuxt@0.5.1, @nuxtjs/tailwindcss@6.11.2, nuxt-icon@0.6.8, @formkit/nuxt@1.5.3
- Build Modules:    -
------------------------------
```
### Package.json
```
    "@formkit/core": "^1.5.3",
    "@formkit/icons": "1.5.3",
    "@formkit/nuxt": "1.5.3",
    "@formkit/pro": "0.119.13",
    "@formkit/themes": "^1.5.3",
```

**Comment by andrew-boyd** [comment]
@sashamilenkovic is correct — we do not automatically import the standalone `FormKitIcon` component. You will need to either register it globally or import it into the components that use it.

**Comment by Rednas83** [comment]
@andrew-boyd This works but why not `AutoImport` this too when **autoImport** is enabled? Especially for nuxt users its confusing to import something and especially when you need to import something from **@formkit/vue** which is not even installed for nuxt users.
```
  // https://formkit.com/getting-started/installation#configuring-nuxt
  formkit: {
    autoImport: true, // In the future this will become the default
  },
```
