### ISSUE TITLE
Docs website nearly unusable without a scrollwheel

### ISSUE THREAD

**Issue by thepurpleblob** [formkit/formkit#1169]
### Reproduction

n/a

### Describe the bug

The left hand menu is very tall and is hidden top and bottom... with a trackpad or scrollwheel it's fine. However, on my dev machine I just have a trackball and it's awkward to use. 

I either have to repeatedly click the top or bottom item or click once and then use arrows. Either way, it's clumsy. Although the menu looks pretty, something with an old-fashioned scroll bar would be easier to use.

### Environment

Chrome browser on linux

**Comment by andrew-boyd** [comment]
@thepurpleblob From my research most trackball users have a keybind of some sort set that turns the trackball from mouse position movement to scroll-wheel emulation. The area itself is indeed a scrollable area so there should be no issues scrolling provided you're able to determine what shortcut/keybind is neccessarry to enable scrolling with your trackball input.

In the event your hardware does not natively support this or there is no support for your combination of hardware / flavor of Linux it looks like there are chrome extensions you can install to create scrolling functionality: https://chromewebstore.google.com/detail/trackball-scroller/digndhblfngkigcehjiddacoibjmkkdf

I'm going to close this issue for now unless you feel there is more to this.
