### ISSUE TITLE
Error generating the formkit.theme.ts file of a local custom theme

### ISSUE THREAD

**Issue by alcidesrh** [formkit/formkit#1170]
### Reproduction
It is not playable on playgond. The link below is not useful.
https://formkit.com/playground?fkv=latest&fileTab=Playground.vue&css-framework=genesis

### Describe the bug

I created a custom theme following [doc]( https://formkit.com/guides/create-a-tailwind-theme)) . Released on npm package management and I installed  as package.json dependency. like any other. No issues.

Then when  I try to generate the formkt.theme.ts file using `npx formkit@latest theme --theme="path-to-mytheme`  I get the following errorr:  `Could not generate theme — Bad Request`

![Screenshot_20240131_234149](https://github.com/formkit/formkit/assets/29238564/615fabff-8d06-4c67-b385-f63a42ddfede)

### Environment

• OS: [Ubuntu 22.04]
• Browser [ chrome, safari]
• Version [latest]

**Comment by andrew-boyd** [comment]
This is on my agenda — there is an issue with local generation. We hope to have it resolved and provide updated documentation by the end of today. 

I’ll follow-up with you here when it’s ready to roll. Sorry for the inconvenience!

**Comment by andrew-boyd** [comment]
This is fixed in `1.5.4`. New docs available here: https://formkit.com/guides/create-a-tailwind-theme#installing-a-published-theme
