### ISSUE TITLE
Formkit playground is not rendering

### ISSUE THREAD

**Issue by Rednas83** [formkit/formkit#1171]
### Reproduction

https://formkit.com/plugins/zod

### Describe the bug

Tried with chrome and edge
![image](https://github.com/formkit/formkit/assets/25219229/595e45e0-71d9-4441-a16e-3fca3e6f2b16)

### Environment

Windows10

**Comment by Rednas83** [comment]
Looks like actually **all** formkit playgrounds are broken at the moment🤔

**Comment by sashamilenkovic** [comment]
@Rednas83 Thank you for reporting this, we're looking into it.

**Comment by sashamilenkovic** [comment]
@Rednas83 Can you take a look at the playground for me and let me know if that issue is still persisting? You may need to hard reload/disable cache in dev tools.

**Comment by andrew-boyd** [comment]
We should be good — thanks for the report and thanks @sashamilenkovic for the quick resolution!
