### ISSUE TITLE
Issue caused by interaction AutoAnimate + autocomplete input

### ISSUE THREAD

**Issue by Aellynd** [formkit/formkit#1172]
### Reproduction

https://formkit.link/2982dbb81b7594c580a7a7b3b0849dc4

### Describe the bug

Hi, I have been trying out the autocomplete input in combination with a repeater and believe I have found a bug.

Scenario 1: Open dropdown using the select input
1) Go to reproduction
2) Click on 'Add'
3) Click on the select input to open the option dropdown
4) Click on an option
For **all options except the first option**: it will not select the option and show 'Input is required', while for the **first** option it works as expected. All subsequent tries to select any option will work as expected.

Scenario 2: Open dropdown using the arrow
1) Go to reproduction
2) Click on 'Add'
3) Click on arrow to open option dropdown
4) Click on an option
For the **first** option: it will not select the option and show 'Input is required', while for **all other options** it works as expected. All subsequent tries to select any option will work as expected.

Turning off the auto animate plugin fixes the issue, hence I believe the issue to be related.

I hope it is clear, otherwise feel free to ask me more questions.
Thanks in advance!

### Environment

• Windows 10 Pro
• Chrome 121.0.6167.140

**Comment by sashamilenkovic** [comment]
@Aellynd Closing this in favor of https://github.com/formkit/formkit/issues/1182.
