### ISSUE TITLE
Styling issue select input placeholder/options (regenesis theme)

### ISSUE THREAD

**Issue by Aellynd** [formkit/formkit#1173]
### Reproduction

https://formkit.link/426dfc9bdc415e4e4118e03d259325b3

### Describe the bug

Hi, I have an issue with the select input regarding the styling of the options whenever there is a placeholder using the regenesis theme. 

Steps to reproduce:
1) Go to reproduction
2) Click on the select
The option are light gray while I expected them to be dark. In my case, this is caused by the `data-[placeholder]:text-neutral-400` on `select__input` in the regenesis theme I am using.

This is what I see in my browser:
![options-actual](https://github.com/formkit/formkit/assets/127315748/45cd3106-a8eb-4201-a345-c9ac30f3cc10)

This is what I expected to see:
![options-expected](https://github.com/formkit/formkit/assets/127315748/e61610e2-1ca8-4351-baf5-e50e5634881f)

Adding a ` option-class="text-neutral-700"` resolves the issue on input level, but it would be greatly appreciated if this could be resolved at theme level.

I hope it is clear, otherwise feel free to ask me more questions.
Thanks in advance!

### Environment

• Windows 10 Pro
• Chrome 121.0.6167.140

**Comment by andrew-boyd** [comment]
This has been fixed — run `npx formkit@latest theme` in your project to update your theme.

**Comment by Trixpua** [comment]
If use the default slot for `<option>`, has the same problem.

**Reproduction**
https://formkit.link/e623920210856d806ca7ed8941801b3a
