### ISSUE TITLE
Importing 'createZodPlugin' returns 'Module not found' when using typescript

### ISSUE THREAD

**Issue by Rednas83** [formkit/formkit#1175]
### Reproduction

https://formkit.com/plugins/zod

### Describe the bug

According to the docs only `@formkit/addons` needs to be installed but I get an error on.
![image](https://github.com/formkit/formkit/assets/25219229/61e506f1-6275-4a33-9531-9358d269f0ca)

Tried
- Installing `@formkit/zod`

Idk what the problem is but perhaps there is a type definition missing for `@formkit/addons`?

### Environment

```
------------------------------
- Operating System: Windows_NT
- Node Version:     v20.11.0
- Nuxt Version:     3.10.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.15.1
- Builder:          -
- User Config:      telemetry, vite, modules, build, routeRules, components, content, formkit, imports, css, devtools
- Runtime Modules:  @vueuse/nuxt@10.7.2, normalizedModule(), @nuxt/content@2.11.0, @pinia/nuxt@0.5.1, @nuxtjs/tailwindcss@6.11.2, nuxt-icon@0.6.8, @formkit/nuxt@1.5.3
- Build Modules:    -
------------------------------
```

**Comment by andrew-boyd** [comment]
Oops, that's definitely a typo in the docs. `@formkit/zod` is its own package and not part of the addons package because of its dependency on Zod.

Regarding your type declaration issue — does it resolve if you change your module resolution to "bundler" in your `.tsconfig` file?

**Comment by Rednas83** [comment]
@andrew-boyd Thanks for this quick workaround. It seems to work without issues for my application👌
`"moduleResolution": "bundler"`

I have no idea what it does, but will it also work with the default "node" in the future?
![image](https://github.com/formkit/formkit/assets/25219229/68ef0642-83ff-45ea-8170-5480e021180c)
