### ISSUE TITLE
Typescript autocomplete not working

### ISSUE THREAD

**Issue by Lol1chw** [formkit/formkit#1179]
### Reproduction

https://github.com/Lol1chw/formkit-ts-autocomplete-issue

### Describe the bug

I have an issue with typescript autocomplete in VSC. Suggestions highlighting in VS Code does not work.
Highlighting props for custom input doesn't work either.

![image](https://github.com/formkit/formkit/assets/94941930/1a6bf67f-36a4-4944-9187-63837a040248)

### Environment

• OS: Windows 11 Pro
• IDE: Visual Stuidio Code, Version: 1.86.0 (user setup)

• Typesciprt - 5.2.2 (takeover)
• Vue - 3.3.11
• Typescript Vue Plugin (Volar) - v1.8.27
• Vue Language Features (Volar) - v1.8.27

**Comment by justin-schroeder** [comment]
Unfortunately I dont think typescript is able to provide suggestions for discriminated unions (which the props are).

```
type Props = { type: 'text' } | { type: 'select' }
```

I would love to be wrong on this, but until there is enough data to narrow down which union is being used I dont think the ts lsp gives us much help.

**Comment by Lol1chw** [comment]
I think the problem is not with discriminated unions, but with how the type works for inputs whose type is not specified.
I mean, the following:
``` 
_: {
    type? Props['type'] extends keyof FormKitInputProps<Props>
      ? never
      : Props['type']
    value ?: string
  }

should be

_: {
        type? Props['type'] extends keyof FormKitInputProps<Props>
          ? Props['type']
          : never
        value?: string
    }
```
![image](https://github.com/formkit/formkit/assets/94941930/4fb3122b-7b5b-40dc-bb66-2402d0b82e84)
We get a warning if the type is there, but it's empty. But if type is not specified, then type='text' is used by default.
![image](https://github.com/formkit/formkit/assets/94941930/fb741e88-f580-48cd-9f32-7bf888108d21)
This also works for custom input, as you can see in the screenshot there is a type "myRadio"

It works like this: if Props['type'] is a FormKitInputProps<Props> key, then FormKitInputType<Props> will be equal to Props['type']. Otherwise, FormKitInputType<Props> will be equal to never. 
I could be wrong, correct me if I am.

**Comment by justin-schroeder** [comment]
@Lol1chw this is really close. You can see there is a slight unintended consequence here: https://github.com/formkit/formkit/actions/runs/8174587760/job/22349714133

Essientially by doing this:

```ts
  _: {
    type?: Props['type'] extends keyof FormKitInputProps<Props>
      ? never
      : Props['type']
    value?: string
  }
```

we’ve added a value type of `string` to all know input types since there are now 2 `type` unions that can match. So something the test checking that `<FormKit type="file" value="abc" />` throws a ts error no longer passes (you can run these locally by doing a build and then running `pnpm test typecheck`).

**Comment by justin-schroeder** [comment]
Ok, I think I got this all working now.
