### ISSUE TITLE
Dropdown/autocomplete option selection fails when using validation and auto-animate

### ISSUE THREAD

**Issue by andrewIAED** [formkit/formkit#1182]
### Reproduction

https://formkit.link/ffef849e7595eb250f73bd8abacea5a6

### Describe the bug

Seems the validation-visibility="live" on Dropdown and Autocomplete input types clashes with auto-animate's functionality, preventing the option you clicked from the list from being selected on the first attempt. Once the error has been displayed, selecting an option again does work. 
![dropdown-error](https://github.com/formkit/formkit/assets/95426946/4e1df06a-8b68-4f8e-92e8-b797319f1b4e)
 

### Environment

• OS: MacOS
• Browser: Chrome
• Version 120.0.6099.216

**Comment by sashamilenkovic** [comment]
@andrewIAED Appreciate the reproduction. We'll take a look at this.

**Comment by sashamilenkovic** [comment]
@andrewIAED This is fixed at v0.121.1 of FormKitPro.
