### ISSUE TITLE
Unable to use src="<imported file>" instead of script setup inside template.

### ISSUE THREAD

**Issue by bootsmann1995** [formkit/formkit#1183]
### Reproduction

https://formkit.com/playground?fkv=latest&fileTab=Playground.vue&css-framework=genesis&files=jc%5BHPJd.vueD%3Cscrip4srcB.%2FNts137+ESM+impVt2ar9eAfrom+URLqhttps%3A7cdn...z7YwellYsecondary+pJAfiXq.%2FOtherFiX.vue%7D.-8script3-%3CG0%3CFVmKitZ0typeBkxt1Z0labelBFVmKi4Input1Z0helpBWi4mQto+ge4startW1Z%2F38G-%3CstylQscopW3%2F*-Thi2fil92TailwinACSS.+--If+you+neeAvanilla+CSS+i4can+go+here.-*%2F-8styX3%276%2CHNjsDexpV4defineC5%7B%28%5CrZ%5Cr-%29z%27%7EremovabX_%7EsiXnt%21false6%5D-%5Cn0++1%5C%272s+3%3E-4t+5omponent6%7EaddW_%297%2F%2F8%3C%2F9QsuppVtAd+B%3D1D%27%7EWitV%21%27Gkmplak3H%28%27name%21%27JlaygrounNkst.c5.Qe+VorWedXleY+a2Z-0_%21truekteq2%7Bz%7D-%01zqk_ZYXWVQNJHGDBA9876543210-_

### Describe the bug

I have a nuxt 3 setup where i split view and functionality in seperate files: component.vue and component.ts. 

my template looks like this: 

``` 
<div>
	<FormKit type="form" label="" add-label="Add Movie">
		<FormKit
			type="select"
			label="Country"
			name="country"
			:options="['Danamrk', 'United states', 'China', 'Africa']"
		/>
		<FormKit type="text" label="Fornavn" name="first_name" validation="required" />
	</FormKit>
</div>
<script lang="ts" src="./component.ts" />
```

I get an error when i use a script file (src import ) as my component definition. 

Error message: 
_**Internal server error: <script> cannot use the "src" attribute when <script setup> is also present because they must be processed together.**_  

if I change my template to this: 
```
<template>
	<div>
		<FormKit type="form" label="" add-label="Add Movie">
			<FormKit
				type="select"
				label="Country"
				name="country"
				:options="['Danamrk', 'United states', 'China', 'Africa']"
			/>

			<FormKit type="text" label="Fornavn" name="first_name" validation="required" />
		</FormKit>
	</div>
</template>
<script lang="ts" setup>
definePageMeta({
	layout: "checkout",
});
</script>
```

it works a intended, but I want to to use the same setup structure throughout the whole project.

### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.19.1
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@8.19.3
- Builder:          -
- User Config:      devtools, experimental, app, modules, swiper, delayHydration, runtimeConfig, laitRobots, formkit, nitro, css
- Runtime Modules:  nuxt-delay-hydration@1.3.3, @nuxtjs/tailwindcss@6.10.4, nuxt-icons@3.2.1, @vueuse/nuxt@10.7.1, @nuxtjs/fontaine@0.4.1, nuxt-payload-analyzer@0.1.4, nuxt-swiper@1.2.2, @formkit/nuxt@1.5.5
- Build Modules:    -
------------------------------

**Comment by justin-schroeder** [comment]
@bootsmann1995 can you re-file this on [unplugin-formkit](https://github.com/formkit/unplugin-formkit)?
