### ISSUE TITLE
A11y: removeSelection button has no text.

### ISSUE THREAD

**Issue by DEPT-ch** [formkit/formkit#1195]
### Reproduction

https://formkit.link/e8d5b9df550843dd62e3b1a7604ccf9c

### Describe the bug

The autocomplete features a reset button (optionally). There are two accessibility issues, of which one is serious:

1. If you point your screenreader cursor to this button, you will hear no explanation whatsoever. There's no text at all. Now people might argue "no problem, its tabindex is set to "-1", so no keyboard user will focus that button anyway. But that ignores that a screen reader user is not only tabbing, but can move to any "aria visible" element. I also think it would be wrong to remove that element from the accessibility tree by setting aria-hidden to true, because we show that button to make it clear to the user how they can reset the value, and if we feel that's necessary, it should also be necessary for the non-sighted user. Long story short: this button needs a label text (I personally would put it into the title attribute, so sighted users profit as well).
2. This is less critical, but from a screenreader user point of view, you could argue that the reset button is hard to get to. You can't tab to it, which you expect from buttons. Personally I think that's a good compromise, as it makes navigating faster and less interruptive. But an accessibility audit might point that out as an issue.

### Environment

• OS: Mac
• Browser: Chrome
• Version 121

**Comment by sashamilenkovic** [comment]
@DEPT-ch Hey there! I've gone ahead with your suggestion and added a title attribute to the resetSelection section of the autocomplete. This has been addressed at v0.121.5 of FormKitPro (you should see this reflected in your playground example if you hard reload, clear cache and make sure you are pulling down the latest version of Pro). I've also went ahead and set the removeSelection tabindex back to `0`. 

While we plan to have our own formal accessibility audit at some point of all of our FormKit Pro inputs (hopefully in the near future), we really appreciate getting feedback. Thank you for taking the time to let us know.

**Comment by DEPT-ch** [comment]
Fantastic, thanks for the quick fix!
