### ISSUE TITLE
Datepicker `week-day-format` prop not working

### ISSUE THREAD

**Issue by timrovict** [formkit/formkit#1200]
### Reproduction

https://formkit.com/playground?fkv=latest&fileTab=datepicker-tokens.vue&css-framework=genesis&files=jc%5B%28%27name%21%279-tokens.vue%27%7Eeditor%21%27%3CB7%3C4+EfCJ%23default25J%3Aactions2false0G41**E98name2launch8label2Product+launch+d38week-day-fCat2ddd8%3Amin-d32new+D3%7B%7D01*%2FGprHwrap%3E%285%296pre764I6BI%27%7Eadded%21true%29%5D*++0%5C%271A*2%3D03ate4FCKit5%28+valuH%296%3C%2F7%3E1801**9d3pickerA%5CnBtempl3CormEtype2G7*%3CHe+I%3EAJ0+%01JIHGECBA9876543210*_&imports=jc%28%27name%21%27ImportMap%27%7Elang%21%27json%27%7Eeditor%21%27%28*+1vue%5C%211https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fvue%403%2Fdist%2Fvue.esm-browser.min.js0*%29*%27%29*%5Cn0%5C%271+0%0110*_

### Describe the bug

When I create a datepicker with `<FormKit type="datepicker" week-day-format="ddd"`, I expect it to render the days as "Mon/Tue/Wed" ("maa/din/woe" in Dutch as in the screenshot)
![image](https://github.com/formkit/formkit/assets/148314337/b701bb92-54f6-4d50-afed-92d5a702aa7c)
It remains at the default "d" format.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
This is an incorrectly documented prop — it should be `weekday-format`:

https://formkit.link/04ad932bdfd8887cc6c1f62baad4958f

Docs have been updated to reflect this. Thank you for pointing it out!

**Comment by timrovict** [comment]
Great, thanks for pointing that out @justin-schroeder !
