### ISSUE TITLE
Input text - message slot prop not working

### ISSUE THREAD

**Issue by NicholasAntidormi** [formkit/formkit#1202]
### Reproduction

[Playground](https://formkit.com/playground?fkv=latest&fileTab=text.vue&css-framework=genesis&imports=jc%28%27name%21%27ImportMap%27%7Elang%21%27json%27%7Eeditor%21%27%28*+1vue%5C%211https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fvue%403%2Fdist%2Fvue.esm-browser.min.js0*%29*%27%29*%5Cn0%5C%271+0%0110*_&files=jc%5B%28%27name%21%27Gxt.vue%27%7Eeditor%21%27%3C43+21%2703583021%2703I4+%237A%287%2963*IE3B7%3F.valueDBJof+7D**5E3*54358H54H%27%7Esyntax%21%27html%27%7Eadded%21true%29%5D*++0C*1nArequired9n-visibiEtyAEve%5C2%3C80*JAGxt93%3E04GmplaG5%3C%2F6%5C%277message8FormKit960*vaEdatioA%3D6B***%28%28+C%5CnD+%29%290EliGteH%3ECI*%3CJtype%01JIHGEDCBA9876543210*_)

### Describe the bug

Hi, the message slot prop seems to be undefined, am I missing something?

Thanks

### Environment

• OS: macOS
• Browser chrome

**Comment by justin-schroeder** [comment]
Since the li is the actual element being looped over you just need to recreate the loop yourself:

https://formkit.link/254d7fcf58ce2f57d533bed6da64c1ae

Good luck 👍
