### ISSUE TITLE
Drag doesn't work on nested repeater 

### ISSUE THREAD

**Issue by Lazerproof** [formkit/formkit#1211]
### Reproduction

https://formkit.link/7ebf808372ca149e5f46145c120feaae

### Describe the bug

After adding a new item to the nested repeater and trying to change it order via drag this item gets and stay in blurred state. 

### Environment

• OS: [e.g. iOS] Win 11
• Browser [e.g. chrome, safari] Chrome 121.0.6167.185 (Official Build) (64-bit)
• Version [e.g. 22] 1.5

**Comment by sashamilenkovic** [comment]
@Lazerproof Nested repeaters weren't considered when implementing drag and drop. This is something we can look into including though.

**Comment by sashamilenkovic** [comment]
@Lazerproof This should now be working. Make sure to hard reload the playground to see the correct drag and drop dependency being referenced (^0.0.23). Locally, you may need to clear you .lock file/node_modules and reinstall @formkit/pro to ensure the correct drag and drop dependency is being installed
