### ISSUE TITLE
Slider in Multi-step form errors when using v-model 

### ISSUE THREAD

**Issue by ShonGee** [formkit/formkit#1213]
### Reproduction

https://formkit.link/721b9ec9d21ae6ea951dc8694f2375a3

### Describe the bug

Describe the bug
Expected: When the a slider is present in a multi-step form the value should be able to bound by using v-model

Actual: When adding v-model data to a slider in a multi-step form the page will error, "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'forward')", 

Reproduction context
Add a slider to a multi-step form, then add v-model data to bind to the slider

To reproduce the issue:

In Playground, uncomment the data ref() and the error will occur, https://formkit.link/721b9ec9d21ae6ea951dc8694f2375a3. 

To make the form work:
Remove the data, or change the slider to to a range. 

This is the only component within multi-step that exhibits this behaviour

Issue seems to be the same on formkit versions 1.4 - 1.5.1

### Environment

Environment
• OS: MacOS 14.3.1 
• Browser: Safari, Chrome
• Version: Safari Version 17.3.1, Chrome Version 121.0.6167.160

**Comment by justin-schroeder** [comment]
Hmm...this does seem to be somehow related to the slider. We’ll take a look 👀

**Comment by ShonGee** [comment]
Updated to 1.6, and testing in the Formkit sandbox (https://formkit.link/721b9ec9d21ae6ea951dc8694f2375a3) and the issue still seems to be present.

**Comment by andrew-boyd** [comment]
Working for me on `1.6`: https://formkit.link/bde792fe9b2545394ea070f2d8ab864e

Note that there's a missing `}` in your demo playground that needs to be fixed when you uncomment it.
