### ISSUE TITLE
Colorpicker with `value=""` should default to some color

### ISSUE THREAD

**Issue by Tragio** [formkit/formkit#1215]
### Reproduction

https://formkit.link/10ccc38deba495db18502a3c4a02eed8

### Describe the bug

Thank you for your incredible work 🚀 

At this moment when the color picker component is with `value=""` it gets `undefined` and an error is triggered.

`Uncaught TypeError: Cannot destructure property 'r' of 'e2.props.rgba' as it is undefined.`

It should default to some color, as it gets when the value is `null` or `undefined`.

**Comment by sashamilenkovic** [comment]
@Tragio Hey there! This should be resolved at FormKit Pro v0.122.6 (should see it reflected in the playground after a hard reload).
