### ISSUE TITLE
Loop through nested schema objects in custom input

### ISSUE THREAD

**Issue by engram-design** [formkit/formkit#1220]
### Reproduction

https://stackblitz.com/edit/vitejs-vite-tnjt8j?file=src%2Ftable.js

### Describe the bug

This very well could be just an incorrect implementation, but this might also be a bug. Please deal with as required.

I have a custom input that is for a table. It's essentially a list with multiple group fields (for each row), and the data for the field is an array of objects. You can see this in action from the reproduction, but it should look like:

<img width="656" alt="image" src="https://github.com/formkit/formkit/assets/1221575/c1bdbe19-d467-496c-9482-01c751a41429">

What I would like to do, is store the child fields in a prop, as opposed to the default slot and `children`. This allows me to loop through the inner fields, which you can't _really_ do with slot components. One main reason I want to do this is to generate the `<td>` elements automatically for example, but also be able to use data for the `thead th` elements.

So, schema-wise, I envisage:
```
schema: [
  {
    $formkit: 'table',
    name: 'rows',
    columns: [
      {
        $formkit: 'text',
        label: 'Name',
        name: 'name',
        autocomplete: 'off',
      },
    ],
  },
],
```

Where I define my custom `table` input, and in the `columns` prop, I store information about the column as inputs, elements, whatever. Just as you would for top-level schema items.

When it comes to actually implementing this in my schema-based custom input, I can't seem to actually loop through those column items. They just print `[object Object]`. I would have thought that if you output an object for a schema item, it would process it as normal, rendering the input.

```
inner({
  $el: 'table',
  children: [
    {
      $el: 'tbody',
      children: [
        {
          $el: 'tr',
          for: ['item', 'index', '$value'],
          children: [
            {
              $formkit: 'group',
              children: [
                {
                  $el: 'td',
                  for: ['column', 'index', '$columns'],
                  children: '$column',
                },
              ],
            },
          ],
        },
      ],
    },
  ],
}),
```

So my custom input looks like this, where we output a table element. We loop through the value of the field (rows), wrap it in a group input for namespacing, then loop over columns for table columns (`td's`). But the call `children: '$column'` doesn't seem to work correctly.

I've tried all sorts of different combinations, so I figured I should ask if this is by design, or a bug?

Notably, this _does_ work using `children` instead of `columns`, and changing things to use `$slots.default`, but that's not quite what I want, and fails to wrap `td` elements around things. I would need to include those.

```
schema: [
  {
    $formkit: 'table',
    name: 'rows',
    children: [
      {
        $el: 'td',
        children: [
          {
            $formkit: 'text',
            label: 'Name',
            name: 'name',
            autocomplete: 'off',
          },
        ],
      },
    ],
  },
],
```

```
inner({
  $el: 'table',
  children: [
    {
      $el: 'tbody',
      children: [
        {
          $el: 'tr',
          for: ['item', 'index', '$value'],
          children: [
            {
              $formkit: 'group',
              children: '$slots.default',
            },
          ],
        },
      ],
    },
  ],
}),
```

But as I've mentioned, this loses the ability to loop through column definitions, which I need in my input class.

### Environment

• OS: MacOs
• Browser Chrome
• Version 118

**Comment by justin-schroeder** [comment]
Essentially what you have is a variable `$column` that contains some schema and you would like to render that schema. You cannot just output it of course as it would be a security risk if variables could execute themselves as if they were scripts, however if you’re confident that `$column` is safe, you can re-invoke the `<FormKitSchema>` component:

```
...
[
        {
          $el: 'tr',
          for: ['item', 'index', '$value'],
          children: [
            {
              $formkit: 'group',
              children: [
                {
                  $el: 'td',
                  for: ['column', 'index', '$columns'],
                  children: [
                    {
                      $cmp: 'FormKitSchema',
                      props: {
                        schema: '$column'
                      }
                    }
                  ],
                },
              ],
            },
          ],
        },
      ],
...
```

Good luck!

**Comment by engram-design** [comment]
Oh, of course - that makes perfect sense. Thanks for that!
