### ISSUE TITLE
Dropdown multi-select with tags: cannot tab out of select after cycling through tags

### ISSUE THREAD

**Issue by jmbrunet** [formkit/formkit#1221]
### Reproduction

https://formkit.link/cfe075ad27abd84bcf10152cdbaff8a8

### Describe the bug

When I have a mutli-select dropdown using tags and I try to tag through my page the focus stops at the last tag and won't exit the dropdown.

### Environment

• OS: macOS Sonoma 14.2.1
• Browser: chrome
• Version: 121.0.6167.184

**Comment by sashamilenkovic** [comment]
@jmbrunet This issue should be resolved at @formkit/pro v0.122.3. Went ahead and made the decision to remove the tabindex of 0 on the dropdown and taglist tags. Instead, these are now "selectable" by the use of arrow keys (and click of course). I'll close this for now, but let me know if you have any other issues.
