### ISSUE TITLE
Can't add fontawesome for <toggle> componet

### ISSUE THREAD

**Issue by altas-innova-tech** [formkit/formkit#1228]
@justin-schroeder 
### Reproduction

https://formkit.com/inputs/toggle

### Describe the bug

When we want to add custom icon from library like  fontawesome.

EX : 
<FormKit
  type="toggle"
  :thumb-icon="<FIcon icon="icon_name"></FIcon >"
/>
OR
<FormKit
  type="toggle"
  thumb-icon="icon_name"
/>

### Environment

• OS: [windows]
• Browser [chrome]

**Comment by fenilli** [comment]
All FormKit inputs uses the Icons https://formkit.com/essentials/icons

We have an example using FontAwesome there https://formkit.com/essentials/icons#using-fontawesome-with-a-custom-iconloaderurl
