### ISSUE TITLE
Form Builder UI

### ISSUE THREAD

**Issue by totalhack** [formkit/formkit#124]
### Describe the feature

I was wondering if you guys have any plans to incorporate some sort of form builder UI into the FormKit product, even if as a paid feature? It could be a drag and drop UI similar to JotForm or some other builders out there, or simply more of a code pen tool that allows live building/rendering of the forms by editing the form schema in one pane, perhaps some custom CSS control in another, and seeing the output form in another pane. 

I imagine you'd pair this with a small JS snippet users could plop on their page, target a div, pass a form ID that you've saved from the edit UI, and then it renders that form as a widget on your site. If you guys happen to be heading in this direction I'd be interested in hearing more. The other products out there are all lacking in one feature or another.

Thanks for your work on this.

**Comment by sasial-dev** [comment]
You've got options here:
- The [playground](formkit.com/playground)
- [Schema](https://formkit.com/essentials/generation) (use JSON to build your forms)

**Comment by totalhack** [comment]
Hey @sasial-dev, thanks for the reply. 

I am familiar with the schema approach, which is why I mentioned it in my description. The playground looks like a useful way to do basic prototyping / sandboxing but not quite the full picture of what I'm asking. Comparing again to a service like JotForm, you'd want the ability to save and manage multiple form definitions in the UI for your account, get code snippets for deployment, etc. 

So I guess I'm just wondering if you guys have any plans to take that playground feature to the next level so it can be used to create/manage/deploy production forms, potentially with non-coders in mind as end users as well. It doesn't have to be drag and drop like JotForm, our business users are capable of managing the logic in JSON as a starting point. It's a feature we'd be willing to pay for if a similar pricing model to [JotForm](https://www.jotform.com/pricing/) were used. 

If that's not in your plans, can you point me to where the playground code lives in your repo? 

Thanks.

**Comment by justin-schroeder** [comment]
That is part of the plan @totalhack. We plan to offer several first-party DX improvements as layers on top of the underlying open source project. We don't have this feature slotted for the next 2 quarters however, so I wouldn't want you to make near term decisions based in its availability — but yes, the short story a form builder interface is absolutely on the roadmap.

**Comment by totalhack** [comment]
Thanks @justin-schroeder, looking forward to that. In the meantime, is the code you guys use for the playground open source, or based on another open source project?

**Comment by justin-schroeder** [comment]
Unfortunately no, the playground is not open source. It's not super secret or anything and we may open source it someday, but we aren't currently prepared to support it. It took a lot of effort to build, and most of the excellent work was done by @andrew-boyd.

If you're looking for an open source version — the official [Vue SFC playground](https://sfc.vuejs.org/) is very similar in it's final product and is [open source](https://github.com/vuejs/core/tree/main/packages/sfc-playground) (we share zero code with it, they both ended up looking really similar).

**Comment by andrew-boyd** [comment]
@totalhack to add on to what Justin said, the reason our Playground exists is because we wanted a 1st-party way to show FormKit examples. The FormKit docs are Vue2 and the FormKit codebase depends on Vue3, so we needed to author a way to encapsulate examples in a sandbox and run Vue3 code inside a Vue2 app. If you're entirely in Vue3-land then the Vue SFC playground is definitely going to be a better starting point for you since you'll be able to do all of your preparation and compilation _before_ passing data to the iFrame.

**Comment by justin-schroeder** [comment]
Ok great @totalhack — ping us on discord if you have any thoughts/suggestions in this regard. We've got listening ears.
