### ISSUE TITLE
Multi-step schema doesn't render last step "next" action.

### ISSUE THREAD

**Issue by ArneMangelschots** [formkit/formkit#1240]
### Reproduction

https://formkit.link/cae78b36189601b72e5acd948ae5c7ca

### Describe the bug

Hello, 

I'm creating a multi-step form with a Formkit Schema.
I would like to put the submit button int the `stepNext` slot on the last step but it doesn't seem to render.

As you can see in this Formkit example https://formkit.link/39e4c5b901c75ba9df7eb509a572dccb it does render on the last step. 

I don't really see any big differences between my Schema and the normal example.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by andrew-boyd** [comment]
This a DX rough spot — but you need to add `if: 'true'` to your `sectionsSchema` for the last `stepNext` in order to override the existing default conditional that hides it.

https://formkit.link/4daafbc7548b2457523dfa8e5a5181ba

**Comment by ArneMangelschots** [comment]
Thank you very much!
