### ISSUE TITLE
setErrors fails without any response if second parameter is array. 

### ISSUE THREAD

**Issue by dl-ias** [formkit/formkit#1248]
### Reproduction

https://formkit.com/playground?fkv=latest&fileTab=Playground.vue&css-framework=genesis&files=jc%5B%28%27name%21%27Playground.vue%27%7EeditX%21%27%3Cscript+setupDBESMYmpXt8ar9suppXtejfrom+URL8%7Bhttps%3A%2F%2Fcdn...%7D3Ba8well+a8secondary+playgrounjfile8%7B.%2FOthxFile.vue%7D.33functiozZ%7Bdata%2C+node%7D+%28336if+%7Bdata.uV9%27%3A%3D%3D+%22fXmkit4life%22%7D+%280node.setErrXs%7B06BArg+1Y8fXm-wid9xrXs06%5B%22Thx9wa8azxrXYzthi8fXm%22%5D%2C06BArg+2Y8field-specific+xrXs06%5B%5D0%7D36%29+els9%280alxt%7B%22Great%2CJar9registxed%22%7D36%293%293NscriptD3%3CtemplateD%3C_+typeQfXm7+%40submitQZ7%3E06%3C_066nameQuVe7066labelQUVe7066helpQWhat+uV9wouldJlike%3F7066validationQrequired%7Clength%3A5706%2F%3E0N_DNtemplateD3%3Cstyl9scopedD%2F*3Thi8fil9suppXt8TailwinjCSS.+33IfJneejvanilla+CSSYt+cazgo+hxe.3*%2F3NstyleD%27%7Eadded%21true%29%5D03663%5Cn6%5Ct7%5C%278s+9e+B%2F%2F+D%3E3J+you+N%3C%2FQ%3D7VsxnamXorY+iZsubmitHandlx_FXmKitjd+xerzn+%01zxj_ZYXVQNJDB987630_

### Describe the bug

If pass to setErrors second parameter as array, then it does not set any errors, and does not throw any error.

``` 
node.setErrors(
			// Arg 1 is form-wide errors
			['There was an error in this form'],
			// Arg 2 is field-specific errors
			[]
		)
 ```

### Environment

• OS: wsl+node@18+nuxt@3.10.0
• Browser chrome/any
• Version formkit@1.5.x

**Comment by dl-ias** [comment]
Problem is, that if you set general form error in first parameter(in correct way), and second as array, then it's also not shown. This is inconsistent. It should throw an error, or at least work correctly with general error.

**Comment by justin-schroeder** [comment]
Sure, maybe we can throw a warning or something when you are in development mode.
