### ISSUE TITLE
Transfer List Max Not Working

### ISSUE THREAD

**Issue by hcam99** [formkit/formkit#1250]
### Reproduction

https://formkit.link/f98585dc8a62ebc2bb5d2868523cac0c

### Describe the bug

When the Transfer List max is reached, the option list is grayed out and cursor changes but list is still transferable. 

### Environment

• OS: Windows 10
• Browser Chrome, Edge

**Comment by sashamilenkovic** [comment]
@hcam99 This should be resolved at FormKit Pro v0.122.10
