### ISSUE TITLE
Multiple Formkit with same schema

### ISSUE THREAD

**Issue by amirmasoud** [formkit/formkit#1251]
### Reproduction

https://formkit.link/89f87f21221990e232b6bed22c68abc6

### Describe the bug

For some reason, I need to have the same form but repeated multiple times on the same page/component. But it seems they somehow get connected/react to each other input.

I faced this issue in two scenarios:

1. one schema, multiple forms.
2. different same schemas, and multiple forms.

I understand that I'm using the same `name` attribute and I was wondering if it's an issue with the autocomplete component or with the FormSchema component, or maybe it is the intended behavior.

Thanks!

### Environment

• OS: [e.g. iOS] MacOS 14.4 (23E214)
• Browser [e.g. chrome, safari] Firefox
• Version [e.g. 22] 123.0.1 (64-bit)

**Comment by justin-schroeder** [comment]
Good question, there are 2 things I see:

1. You should not have the same id repeated on the page 2x. `id` should be globally unique.
2. The name must be unique per `group` it is inside (the `form` being the outermost group, but inside a repeater, for example, each repeated item is its own `group` too).

Happy coding 👍

**Comment by amirmasoud** [comment]
Great! Thanks!

I think by the same logic this example is also wrong:

https://formkit.link/25e9e86556c46122b73a5f821f7a5445

As I am using the same id inside of a repeater and it causes the datepicker to only change the first item in the repeater.

It would be great if it was mentioned in the docs, I would be more than happy to update the doc for repeater section to mention this, if you see that can be a useful information.
