### ISSUE TITLE
Dark mode text hard to read (select type)

### ISSUE THREAD

**Issue by Nova38** [formkit/formkit#1253]
### Reproduction

https://stackblitz.com/edit/github-vqvsuh-hjw8pz?file=app.vue

### Describe the bug

The replication requires you to force the page to be in dark mode. It can easily be seen by just going to the theme website, enabling the dark mode and then selecting the select  elements and looking at the drip down

For the dropdown for the select element, is there a easy way to get its background to not be white when dark mode is enabled? I am using the regenesis. I double checked and it does apear to be the behavior on the theme website as well (https://themes.formkit.com/editor?theme=regenesis)

https://discord.com/channels/793529058377072650/940340536747896842/1212681021926015056

### Environment

• OS: [e.g. iOS] windows
• Browser [e.g. chrome, safari] edge, chrome, firefox
![Uploading image.png…]()

• Version [e.g. 22]

**Comment by andrew-boyd** [comment]
Whoops! Yes this is a regression. I'll get a fix pushed out today.

**Comment by andrew-boyd** [comment]
This has been fixed on the latest version of the themes — if you run `npx formkit@latest theme` in your project it should allow you to edit the theme, and by saving you'll grab the latest copy.
