### ISSUE TITLE
Hydration warnings on page refresh using Radio in a List

### ISSUE THREAD

**Issue by TimDirks** [formkit/formkit#1256]
### Reproduction

https://github.com/TimDirks/FormKit-Hydration-Warning

### Describe the bug

During development I get Hydration warnings when I manually refresh the page. This happens when you use a Radio input within a List (I've tried some other inputs inside a List but so far I only got Hydration warnings with a Radio Input). The warnings are about mismatching name attributes so it might be related to [this issue](https://github.com/formkit/formkit/issues/1245).

The Hydration warnings don't appear on initial page load, only when refreshing it causes some counter in the `name` attribute to increment on server side only causing the mismatch.

<img width="1782" alt="Screenshot 2024-03-12 at 08 37 11" src="https://github.com/formkit/formkit/assets/18048711/ac29a130-14e5-41a8-8fb7-c1c9c9a44344">

### Environment

• OS: macOS Sonoma 14.3.1
• Browser: Chrome version 122.0.6261.112
• Version: FormKit 1.6.0, Node v20.11.0

**Comment by justin-schroeder** [comment]
Thanks for the reproduction! This is fixed and will be in the next release.

**Comment by maartenvanhunsel** [comment]
@justin-schroeder, in addition to the radio buttons, the same behavior occurs with multiple checkboxes and even search fields. If you need a reproduction, please inform me.

<img width="752" alt="image" src="https://github.com/formkit/formkit/assets/7252657/7bff4290-73d7-40f8-8810-09f234539a28">

**Comment by justin-schroeder** [comment]
@maartenvanhunsel are you seeing that in nuxt? Im unable to duplicate it
