### ISSUE TITLE
The autocomplete selection does not appear the second time

### ISSUE THREAD

**Issue by apiret** [formkit/formkit#1259]
### Reproduction

[Reproduction Link](https://formkit.com/playground?fkv=latest&fileTab=autocomplete-single.vue&css-framework=genesis&imports=jc%28%27name%21%27ImportMap%27%7Elang%21%27json%27%7Eeditor%21%27%28*+1vue%5C%211https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fvue%403%2Fdist%2Fvue.esm-browser.min.js0*%29*%27%29*%5Cn0%5C%271+0%0110*_&files=jc%5B%28%27name%21%27autocomplete-single.vue%27%7Eeditor%21%27%3Cscript+setup%3E7import+%5E+from+%22.%2F%5E.js%227%3C%2Fscript%3E77%3Ctemplate%3E73%3CFormKit+type%3D8form8+%23default%3D8%28+value+%298+%3Aactions%3D8false8%3E733%3Cdiv+class%3D8bg-green%26%40%7Clabel%3D8Search+for+a+country%7Cplacehol%258%5E8%3Bdiv+class%3D8bg-red%26%40Popover%7Clabel%3D8Error+with+select%7Cplacehol%258%5E%7Cpopover%3Bpre+wrap%3E%28%28+value+%29%29%3C%2Fpre%3E73%3C%2FFormKit%3E7%3C%2Ftemplate%3E77%27%7Eadded%21true%29%2C%28%27name%21%27%5E.js%27%7Eeditor%21%27export+default+%5B73%28+label%3A+%22Afghanistan1AF*%C3%85land5s1AX*Albania1AL*Algeria1DZ*Americ%7FSamoa1AS*AndorrA1AD*Angola1AO*Anguilla1AI*Antarctica1AQ*Antigua9Barbuda1AG*Argentina1AR*Armenia1AM*Aruba1AW*Australia1AU*Austria1AT*Azerbaijan1AZ*Bahamas1BS*Bahrain1BH*Bangladesh1BD*Barbados1BB*Belarus1BY*Belgium1BE*Belize1BZ*Benin1BJ*Bermuda1BM*Bhutan1BT*Bolivia1BO*Bosnia9Herzegovina1BA*Botswana1BW*Bouvet51BV*Brazil1BR*British+Indi%7FOce%7FTerritory1IO*Brunei+Darussalam1BN*Bulgaria1BG*Burkina+Faso1BF*Burundi1BI*Cambodia1KH*Cameroon1CM*Canada1CA*Cape+Verde1CV*Cayman5s1KY*Central+African61CF*Chad1TD*Chile1CL*China1CN*Christmas51CX*Cocos+%7BKeeling%7D5s1CC*Colombia1CO*Comoros1KM*Congo1CG*Congo%2BThe+Democratic6+of+the1CD*Cook5s1CK*Costa+Rica1CR_8Cote+D%22Ivoire8%24CI*Croatia1HR*Cuba1CU*Cyprus1CY*Czech61CZ*Denmark1DK*Djibouti1DJ*Dominica1DM*Dominican61DO*Ecuador1EC*Egypt1EG*El+Salvador1SV*Equatorial+Guinea1GQ*Eritrea1ER*Estonia1EE*Ethiopia1ET*Falkland5s+%7BMalvinas%7D1FK*Faroe5s1FO*Fiji1FJ*Finland1FI*France1FR*French+Guiana1GF*French+Polynesia1PF*French+Southern+Territories1TF*Gabon1GA*Gambia1GM*Georgia1GE*Germany1DE*Ghana1GH*Gibraltar1GI*Greece1GR*Greenland1GL*Grenada1GD*Guadeloupe1GP*Guam1GU*Guatemala1GT*Guernsey1GG*Guinea1GN*Guinea-Bissau1GW*Guyana1GY*Haiti1HT*Heard59Mcdonald5s1HM*Holy+See+%7BVatic%7FCity+State%7D1VA*Honduras1HN*Hong+Kong1HK*Hungary1HU*Iceland1IS*India1IN*Indonesia1ID*Iran%2BIslamic6+Of1IR*Iraq1IQ*Ireland1IE*Isle+of+Man1IM*Israel1IL*Italy1IT*Jamaica1JM*Japan1JP*Jersey1JE*Jordan1JO*Kazakhstan1KZ*Kenya1KE*Kiribati1KI_8Korea%2BDemocratic+People%22S6+of8%24KP*Korea%2C6+of1KR*Kuwait1KW*Kyrgyzstan1KG_8Lao+People%22S+Democratic68%24LA*Latvia1LV*Lebanon1LB*Lesotho1LS*Liberia1LR*Liby%7FArab+Jamahiriya1LY*Liechtenstein1LI*Lithuania1LT*Luxembourg1LU*Macao1MO*Macedonia%2BThe+Former+Yugoslav6+of1MK*Madagascar1MG*Malawi1MW*Malaysia1MY*Maldives1MV*Mali1ML*Malta1MT*Marshall5s1MH*Martinique1MQ*Mauritania1MR*Mauritius1MU*Mayotte1YT*Mexico1MX*Micronesia%2BFedera%3F+of1FM*Moldova%2C6+of1MD*Monaco1MC*Mongolia1MN*Montenegro1ME*Montserrat1MS*Morocco1MA*Mozambique1MZ*Myanmar1MM*Namibia1NA*Nauru1NR*Nepal1NP*Netherlands1NL*Netherlands+Antilles1AN*New+Caledonia1NC*New+Zealand1NZ*Nicaragua1NI*Niger1NE*Nigeria1NG*Niue1NU*Norfolk51NF*Northern+Mariana5s1MP*Norway1NO*Oman1OM*Pakistan1PK*Palau1PW*Palestini%7FTerritory%2BOccupied1PS*Panama1PA*Papua+New+Guinea1PG*Paraguay1PY*Peru1PE*Philippines1PH*Pitcairn1PN*Poland1PL*Portugal1PT*Puerto+Rico1PR*Qatar1QA*Reunion1RE*Romania1RO*Russi%7FFederation1RU*RWANDA1RW%60Helena1SH%60Kitts9Nevis1KN%60Lucia1LC%60Pierre9Miquelon1PM%60Vincent9the+Grenadines1VC*Samoa1WS*S%7FMarino1SM*Sao+Tome9Principe1ST*Saudi+Arabia1SA*Senegal1SN*Serbia1RS*Seychelles1SC*Sierra+Leone1SL*Singapore1SG*Slovakia1SK*Slovenia1SI*Solomon5s1SB*Somalia1SO*South+Africa1ZA*South+Georgia9the+South+Sandwich5s1GS*Spain1ES*Sri+Lanka1LK*Sudan1SD*Suriname1SR*Svalbard9J%7FMayen1SJ*Swaziland1SZ*Sweden1SE*Switzerland1CH*Syri%7FArab61SY*Taiwan%2BProvince+of+China1TW*Tajikistan1TJ*Tanzania%2BUnited6+of1TZ*Thailand1TH*Timor-Leste1TL*Togo1TG*Tokelau1TK*Tonga1TO*Trinidad9Tobago1TT*Tunisia1TN*Turkey1TR*Turkmenistan1TM*Turks9Caicos5s1TC*Tuvalu1TV*Uganda1UG*Ukraine1UA*United+Arab+Emirates1AE*United+Kingdom1GB*Uni%3F1US*Uni%3F+Minor+Outlying5s1UM*Uruguay1UY*Uzbekistan1UZ*Vanuatu1VU*Venezuela1VE*Viet+Nam1VN*Virgin5s%2BBritish1VG*Virgin5s%2BU.S.1VI*Wallis9Futuna1WF*Western+Sahara1EH*Yemen1YE*Zambia1ZM*Zimbabwe1ZW%22+%29%2C7%5D7%27%7Eadded%21true%29%5D*_%221%22%243++5+Island6+Republic7%5Cn8%5C%279+and+_%22+%29%2C73%28+label%3A+%24%2Bvalue%3A+%22%25der%3D8Example%3A+Uni%3F%7C%3Aoptions%3D%26-200+p-48%3E7333%3CFormKit73333type%3D8autoc%2B%2C+%3B7333%2F%3E733%3C%2Fdiv%3E733%3C%3Fted+States%40omplete%7Cname%3D8country%5Ecountries%60*Saint+%7C873333%7Fan+%01%7F%7C%60%5E%40%3F%3B%2B%26%25%24_9876531*_)

### Describe the bug

Hi,

With Chrome, since version 1.6.0 of Formkit, the selection of the autocomplete component (maybe other components as well) does not work.

Steps to reproduce: 
1. Open the selection
2. Select a value
3. Delete the value
4. Try to reopen the selection

Thanks in advance

### Environment

• OS: [OXS]
• Browser [chrome]
• Version [22.0.6261.112]

**Comment by andrew-boyd** [comment]
Yep! That's on me. With popover I'm delaying the setting of `opacity` until the positioning is computed — but looks like I'm not re-applying full opacity once the computation has been done. Working on a fix that will be out soon, but in the mean time you can force full opacity with a class like so:

https://formkit.link/2745e8f81bcc4b7b16ecac5f655a4ee4

**Comment by andrew-boyd** [comment]
@apiret This should be fixed in `0.122.9`. Would you mind giving it a try?

**Comment by apiret** [comment]
It works very well on Chrome. 

I took the opportunity to test it on Firefox and it works less well. But I don't know if it's the select or my popin (primevue). I'll investigate. 

![Screenshot 2024-03-12 at 16 23 30](https://github.com/formkit/formkit/assets/1142871/6560edec-bc40-48bc-8931-7f885e4b228c)

Thanks for the quick fix.

**Comment by andrew-boyd** [comment]
Firefox does not yet support the Popover API — but should soon: https://caniuse.com/?search=popover

**Comment by apiret** [comment]
Oh ok perfect, good to know. Thanks again
