### ISSUE TITLE
Inputs break all component slots except `default`

### ISSUE THREAD

**Issue by LouisHaftmann** [formkit/formkit#1266]
### Reproduction

https://stackblitz.com/edit/nuxt-starter-uqs28w?file=app.vue

### Describe the bug

Using `<FormKit type="..." />` in a component with slots breaks all slots except `default`. This bug only occurs if the component with slots is the root of the template of another component:

```vue
<template>
  <ExampleLayout>
    <!-- this slot does not work -->
    <template #title> Some Title </template>
    
    <!-- commenting out this line makes the slot above work again -->
    <FormKit type="text" />
  </ExampleLayout>
</template>
```

This is probably caused by `unplugin-formkit`.

### Environment

• OS: macos
• Browser: chrome

**Comment by Archetipo95** [comment]
I was working with the same bug yesterday and I found that if you wrap the content of app.vue in a div it starts working.
I thing there is a bug in Vue or Nuxt but I'm not so sure.

```
<template>
	<div>
		<ExampleLayout>
			<template #title> Some Title </template>
			
			<FormKit type="text" />
		</ExampleLayout>
	</div>
</template>`

**Comment by justin-schroeder** [comment]
Yeah, this is silly of us. We used to inject a lazy provider to check for a suspense boundary, but that is no longer necessary. We should just inject `useConfig` instead. I’m going to close this issue in favor of formkit/unplugin-formkit#7.

Thanks for the report ❤️
