### ISSUE TITLE
`v-if` not working on messages empty object

### ISSUE THREAD

**Issue by Archetipo95** [formkit/formkit#1267]
### Reproduction

https://formkit.link/fc2e6eca2f12909c868e3ebf846bb05f

### Describe the bug

I'm not sure if this is a bug but as I described in the playground the `ul` tag keeps rendering even if the object messages is empty and Im checking with `v-if`

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
messages is a `Record<string, FormKitMessage>` not an array. Good news is its an easy fix!

https://formkit.link/75e103329153bc4e2205326e85bdc4ec

Happy coding 👍
