### ISSUE TITLE
How to verify a field separately

### ISSUE THREAD

**Issue by aegorx** [formkit/formkit#127]
### Describe the feature

like this `node.validate('input');`

and

how to remove all errors?

**Comment by aegorx** [comment]
maybe，I can use context.handlers.blur().

**Comment by justin-schroeder** [comment]
@aegorx inputs are always validated in realtime — no need to explicitly call `validate`. The node is always aware of its validation state. There are a few ways to access this information. The error messages are _always there_, but they are either shown or not shown based on the `validation-visibility`.

Here's an example that can help explain some: https://formkit.link/665c49d10d81cbb1f29d2da8acc229a9
