### ISSUE TITLE
FormKit Pro not synced with the current version

### ISSUE THREAD

**Issue by Archetipo95** [formkit/formkit#1274]
### Reproduction

nope

### Describe the bug

I’m currently working with a slightly older version of FormKit, and I recently had to update my lock file. However, I’ve noticed that @formkit/pro has the latest FormKit dependencies, and unfortunately, they don’t align with my project installation. As a result, I’m encountering the following error:

```
Argument of type '() => { plugins: FormKitPlugin[]; }' is not assignable to parameter of type 'DefaultConfigOptions | (() => DefaultConfigOptions)'.
  Type '() => { plugins: FormKitPlugin[]; }' is not assignable to type '() => DefaultConfigOptions'.
    Type '{ plugins: FormKitPlugin[]; }' is not assignable to type 'DefaultConfigOptions'.
      Type '{ plugins: FormKitPlugin[]; }' is not assignable to type 'Partial<Omit<FormKitContext, "children" | "plugins" | "config" | "hook"> & { config: Partial<FormKitConfig>; props: Partial<FormKitProps<unknown>>; ... 5 more ...; schemaAlias: string; }>'.
        Types of property 'plugins' are incompatible.
```

I resolved this issue by manually renaming all instances of FormKit 1.6.0 versions to 1.5.9 in the lock file.

![Screenshot 2024-03-19 at 15 16 07](https://github.com/formkit/formkit/assets/11798239/26fb4445-4f5f-46e0-80a4-9f3d60eb53aa)
![Screenshot 2024-03-19 at 15 16 25](https://github.com/formkit/formkit/assets/11798239/6de1a111-cf7a-4176-8308-72b3d3e0dabb)

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by Archetipo95** [comment]
This could be the problem:

```
/@formkit/pro@0.122.1(@formkit/core@1.6.0)(@formkit/inputs@1.6.0):
    resolution: {integrity: sha512-IGuvBCEQqhc9Lw5DEIhdbfaJ45CvgNgARD0moypCCUcyTpJjQiYYAOHupNw+wb/nTVVeNvKAloGS/CbxTinEmw==}
    peerDependencies:
      '@formkit/core': ^1.5.9
      '@formkit/inputs': ^1.5.9
    dependencies:
      '@formkit/core': 1.6.0
      '@formkit/drag-and-drop': 0.0.16
      '@formkit/inputs': 1.6.0
      '@formkit/tempo': 0.0.8
    dev: true
```

**Comment by justin-schroeder** [comment]
FormKit Pro no longer explicitly depends on formkit/core or formkit/inputs — it now only uses `peerDependencies`, so this should no longer be an issue ❤️
