### ISSUE TITLE
Custom taglist validation error only shows up when you focus out

### ISSUE THREAD

**Issue by abdelrahmansafwat** [formkit/formkit#1278]
### Reproduction

[Repro](https://formkit.com/playground?fkv=latest&fileTab=custom-validation-dependency.vue&css-framework=genesis&imports=jc%28%27name%21%27ImportMap%27%7Elang%21%27json%27%7Eeditor%21%27%28*+1vue%5C%211https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fvue%403%2Fdist%2Fvue.esm-browser.min.js0*%29*%27%29*%5Cn0%5C%271+0%0110*_&files=jc%5B%28%27name%21%27cuGom-8-dependency.vue%27%7Eeditor%21%27%3Cscript+setup6functioI5%7BnodeC%280*let7BMnode.vHue.forEach%7B%7BtagC%3D%3E+%283**if+%7Btag+%27%3A%3DD%22hello%22%7D7fHseM%29%7DJ3returI2J%29L%2Fscript6LA*%3CFormKit3*label4FirG+item9type4tagliG9name4firGO8-rules4%28+5+%299845OHlowNewVHues4B13%2F6%3C%2FA%27%7Eadded%21B%29%5D*++0%5Cn1%5C%272vHid30**4%3D15diGinct6%3E07+2+D82ation913*Atemplate6BtrueC%7D+D%3D+GstHalIn+J%3B0L0%3CM%3B3O9%3A%01OMLJIHGDCBA9876543210*_)

### Describe the bug

If I use a taglist field, with allowNewValues, and custom validation, the validation errors don't show up as I add a new tag. The errors only show up when I focus out of the field. This is kinda inconvenient for our users, since they will never know that a problematic tag was added until they click away from the field itself.

I debugged it and the validation does happen with every tag added, but it's just the error label that doesn't render.

### Environment

• OS: Ubuntu
• Browser: Firefox, Chrome
• Version: 1.6.0, 1.5.9

**Comment by sashamilenkovic** [comment]
You can set `validation-visibility="live"`. 
Here's the updated playground: https://formkit.link/55bcf4e3721115242eddde4709dee50a 
Here's the docs: https://formkit.com/essentials/validation#showing-errors.
