### ISSUE TITLE
Nuxt autoImport: true makes it necessary to import FormKitSchema

### ISSUE THREAD

**Issue by silvio-e** [formkit/formkit#1286]
### Reproduction

https://stackblitz.com/edit/nuxt-starter-khnmgv?file=nuxt.config.ts

### Describe the bug

The `FormKitSchema` component is globally available in Nuxt and ready to use like the `FormKit` component when `autoImport: false`.

When setting `autoImport: true` this doesn't work anymore and the component needs to be imported manually.

**What I would expect:**

I would expect that `FormKitSchema` is still available like `FormKit` is too.

### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.5
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, modules, formkit
- Runtime Modules:  @nuxtjs/tailwindcss@6.11.4, @formkit/nuxt@1.6.1
- Build Modules:    -
------------------------------

**Comment by justin-schroeder** [comment]
You are 100% correct

**Comment by Tragio** [comment]
Hi @justin-schroeder 👋 

Just bringing this up. Do you think would be possible to see this in an upcoming release? 🤔 

Thank you for the awesome work! 🚀
