### ISSUE TITLE
Website is down 

### ISSUE THREAD

**Issue by Ochoja** [formkit/formkit#1287]
### Reproduction

https://formkit.com/

### Describe the bug

Formkit documentation is not accessible.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by sashamilenkovic** [comment]
@Ochoja I'm not seeing this on my end. Are there any errors you are seeing in your dev tools/anyway to reproduce?

**Comment by Ochoja** [comment]
![Screenshot_20240402-052052_Chrome.jpg](https://github.com/formkit/formkit/assets/37149152/7fff3328-4a73-41f0-843e-e487789ece41)

This has been the result for me for the past 1 week

**Comment by sashamilenkovic** [comment]
@Ochoja We're having a hard time replicating this. I'll reopen this for now in case other people are running into the same issue.

**Comment by ilwk** [comment]
Same issue
