### ISSUE TITLE
Select prevents rendering if options are empty

### ISSUE THREAD

**Issue by RDelorier** [formkit/formkit#129]
### Reproduction

https://formkit.link/2503ee4a3a9247b2ded2e5a4d6624594

### Describe the bug

Select inputs prevent entire form from rendering if there is no placeholder and the options are empty.

When loading options for a select async the initial array is empty. If there is no placeholder then the input attempts to set the value using the first available option which doesn't exist.

### Environment

• OS: macOS Monterey
• Browser chrome
• Version 98.0.4758.109 (Official Build) (x86_64)

**Comment by justin-schroeder** [comment]
hmm, yeah thats no bueno. thanks for the report 👍

**Comment by justin-schroeder** [comment]
This is fixed and published on the `@next` tag. You can see it working in the playground on the beta.6 version:

https://formkit.link/6cc4859a272eadfbc848f7706fca8a72

(might need a hard refresh)

**Comment by RDelorier** [comment]
Awesome, that was fast 👏
