### ISSUE TITLE
Icons broken when using Nuxt

### ISSUE THREAD

**Issue by MalachiDraven** [formkit/formkit#1296]
### Reproduction

https://github.com/MalachiDraven/Nuxt_FormKit_BrokenIcons

### Describe the bug

The prefix, suffix, and other icons are broken when using Nuxt (@formkit/nuxt). They're gigantic lol. 

My site:
![Screenshot 2024-04-06 at 20-44-00 Screenshot](https://github.com/formkit/formkit/assets/21045455/95fc58aa-0306-4e64-9e02-b09282b3fc98)

app.vue:
```html
<template>
  <div>
    <h1>Hello World!</h1>
    <FormKit type="text" prefix-icon="eye" name="password" />
  </div>
</template>
```

nuxt.config.ts
```ts
export default defineNuxtConfig({
  devtools: { enabled: true },

  modules: ['@formkit/nuxt'],
})
```

package.json
```json
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "dependencies": {
    "@formkit/nuxt": "^1.6.1",
    "nuxt": "^3.11.2",
    "vue": "^3.4.21",
    "vue-router": "^4.3.0"
  }
}
```

This is on a fresh install / new Nuxt project. No other modules/plugins installed. 

### Environment

• OS: Windows 10
• Browser: Firefox
• Version: 1.6.1

**Comment by sashamilenkovic** [comment]
This is a theming issue. I'd suggest taking a look at the theming section of the installation guide: https://formkit.com/getting-started/installation

**Comment by MalachiDraven** [comment]
> This is a theming issue. I'd suggest taking a look at the theming section of the installation guide: https://formkit.com/getting-started/installation

You were right. Installing the Genesis them fixed it. The documentation for the new Tailwind themes is very confusing though. How exactly do I add a basic/starter theme to my existing project? I tried following the documentation here - https://formkit.com/essentials/styling#tailwind-css - but it didn't work.
