### ISSUE TITLE
Formkit Number in Float mode fails to submit 

### ISSUE THREAD

**Issue by Nova38** [formkit/formkit#1299]
### Reproduction

https://formkit.link/edda9b935fc8f5906b4a5a5902b8fadc

### Describe the bug

Formkit Number input fails on submit if the number is a float instead of an int. It says that it needs to be one of the two closest intigers. The replication is from the docs https://formkit.com/inputs/number#cast-to-number with a submit handler enabled.

I

### Environment

• OS: windows
• Browser: edge
• Version: 1.6.2

**Comment by sashamilenkovic** [comment]
@Nova38 When using the `number` attribute to use a float, you need to set the html attribute `step` to `any`: https://formkit.link/6cd9f0de75ef445eae2a0fd23ee91540

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#step
