### ISSUE TITLE
Taglist options wrong position when searching

### ISSUE THREAD

**Issue by azertyalex** [formkit/formkit#1310]
### Reproduction

https://formkit.link/cfde31cae5eee4932f3ba53189bca05c

### Describe the bug

When searching in the taglist, the available options won't always be in the correct position

![image](https://github.com/formkit/formkit/assets/9082988/2d8ada8d-96f4-4e8c-8db4-9de66234e4cf)
![image](https://github.com/formkit/formkit/assets/9082988/466a6af3-f314-41bc-a7b4-d47e42035416)

### Environment

• OS: Ubuntu
• Browser: Chrome
• Version 1.6 & 0.122.16

**Comment by sashamilenkovic** [comment]
@azertyalex Hey there! Yes, that's quite odd. It seems to behave correctly when not using the `popover` prop. Definitely something we can take a look at.

**Comment by jdelrue** [comment]
any update @sashamilenkovic ?

**Comment by andrew-boyd** [comment]
hey @jdelrue This one's on me — I'll be sitting down to work through issues hopefully today so that we can ship some QoL updates before we're on the road for VueConf US.
