### ISSUE TITLE
Dropdown Popover: Non-text id leads to "is not a valid selector"

### ISSUE THREAD

**Issue by lud-hu** [formkit/formkit#1313]
### Reproduction

https://formkit.link/0b54327f8f8a6497e3578bdc77af924d

### Describe the bug

```html
  <FormKit
    type="dropdown"
    label="dropdown"
    value="A"
    :options="['A', 'B', 'C']"
    id="0test"
    popover
  />
```

When using the `popover` option in combination with element ids that do not contain only text (e.g. `0test` or 0.test`) for a dropdown, the dropdown is not shown and an error is shown in the console:

```
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#0test_popover[popover]' is not a valid selector.
```

### Environment

• OS: macOS
• Browser: Chrome

**Comment by lud-hu** [comment]
As https://stackoverflow.com/a/46399063/3920200 suggests, maybe escaping the id when using the querySelector would already help?

**Comment by andrew-boyd** [comment]
Have a fix for this. Instead of accessing by `id` directly:

```
document.querySelector(`#${node.context.id}_popover[popover]`)
```

We can access by property selector: 

```
document.querySelector(`[id="${node.context.id}_popover"][popover]`)
```
