### ISSUE TITLE
Autocomplete input doesn't update its options correctly

### ISSUE THREAD

**Issue by Coconut7807** [formkit/formkit#1316]
### Reproduction

https://formkit.link/e1219056c4422951195cbdb7ef9a329e

### Describe the bug

I have an autocomplete input that has options that are dependent on another input.
For example: First you select a food (pizza or ice cream), then a flavour (either pepperoni / cheese / other, or chocolate / vanilla / other). 

If I select an option in the autocomplete input that also happens to be available after I switch the dependent input (in my example 'other' is available for both pizza and ice cream), then the list of options is not updated; so for ice cream I still see the pizza flavors or vice versa.

Reproduction (see link):
* For food, select 'Pizza'
* For flavor, select 'Other'
* For food, switch to 'Ice cream'
* Click on the autocomplete input to see the available options: This shows 'Pepperoni', 'Cheese' and 'Other'
-> I would expect the available options to be 'Chocolate', 'Vanilla' and 'Other' instead.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by sashamilenkovic** [comment]
@Coconut7807 I'm going to close this for now; feel free to reopen if you have any questions/issues.
