### ISSUE TITLE
Custom @remove-icon-click function doesn't override native remove handler

### ISSUE THREAD

**Issue by Lazerproof** [formkit/formkit#1318]
### Reproduction

https://formkit.link/7c490f564ab10f93d75482d4651ccc31

### Describe the bug

Hi. 
I want to show a confirmation modal before the deletion of an item from the repeater field. I supposed that I could accomplish it by setting a custom handler for the 'removeIconClick' event, but, while the custom handle function gets called, the native event handler also gets called. 

### Environment

• OS: [e.g. iOS] Win 11
• Browser [e.g. chrome, safari] Chrome 123.0.6312.122
• Version [e.g. 22] Playground 1.6.x

**Comment by sashamilenkovic** [comment]
@Lazerproof Hey there! Here's a solution I came up with: https://formkit.link/b979ebf86564e5c47ec870bcc2e10a25. Maybe someone else on the team can jump in with a more elegant solution.

**Comment by fenilli** [comment]
You could also use a plugin to add this globally https://formkit.link/70def50b29441b16d0c6810d782eb1b1.

**Comment by sashamilenkovic** [comment]
@Lazerproof I'm going to close this for now. Feel free to reopen/comment back if you have any issues/questions.

**Comment by Lazerproof** [comment]
@fenilli @sashamilenkovic Thanks for examples. I went with the plugin approach, but there is an issue that handleRemove function get called twice on remove icon click with different arguments. 
Take a look at console on this example https://formkit.link/f7254ad18d3e7b8a9e9d0e507bee397c
![image](https://github.com/formkit/formkit/assets/5707348/e3f96374-66e9-450e-ad16-2f0334c7cc6e)

**Comment by fenilli** [comment]
That would be correct indeed, as we changed the `removeControl` but not the icon itself that also has a click handler, there might be two ways to deal with it, one would be to also change the icon itself removing the onClick event from it, the other a bit simpler would be to just pass the handler directly to the plugin: https://formkit.link/723d2c437382a7732515c78a66d4dfdf

**Comment by Lazerproof** [comment]
@fenilli Great, thanks!
