### ISSUE TITLE
Datepicker cannot parse escaped tokens

### ISSUE THREAD

**Issue by justin-schroeder** [formkit/formkit#1319]
### Reproduction

https://formkit.link/f575ac9529e21c8bc0f0b90695fc56c7

### Describe the bug

This example is from the docs. For some reason the datepicker is unable to parse escaped tempo tokens.

### Environment

• OS: macOS
• Browser: chrome
• Version: 1.6.1

**Comment by sashamilenkovic** [comment]
This appears to be resolved at the latest version of @formkit/pro (v0.126.6). Will close for now.
