### ISSUE TITLE
i18n - add language - Macedonian

### ISSUE THREAD

**Issue by jpetrov** [formkit/formkit#1320]
### Reproduction

https://github.com/formkit/formkit/tree/master/packages/i18n/src/locales

### Describe the bug

I have prepared the initial version for the mk.ts package (just rename .txt->tx the form didn't allow me to upload it as .ts)

[mk.ts.txt](https://github.com/formkit/formkit/files/15049799/mk.ts.txt)

### Environment

Latest version

**Comment by sashamilenkovic** [comment]
@jpetrov Thank you! This will be included in the 1.7.0 release.
