### ISSUE TITLE
Form flickers between valid and invalid state while user is typing

### ISSUE THREAD

**Issue by angel200sdnot** [formkit/formkit#1324]
### Reproduction

https://formkit.link/94b23f0e9993ee103638d4a50b6c724f

### Describe the bug

After applying a styling to a formkit component based on its validity state, flickering between the applied style occurs when the user is typing on the input

In the provided reproduction link, you must first get the input form to show the error message, and then start typing fast on it and you should see the green border popping up every now and then

### Environment

• OS: Windows 10 Pro
• Browser: Chrome
• Version 1.6.1

**Comment by leemartin** [comment]
Likely related to this slider number input flickering I'm seeing:

https://x.com/leemartin/status/1788637235916533913

**Comment by imranalieee** [comment]
i am also facing the validation state flickering issue, for reference video is attached

https://github.com/formkit/formkit/assets/6704744/ad49e106-f2e7-4e51-bee3-a020dc8a183a
