### ISSUE TITLE
Togglebuttons: Certain ARIA roles must be contained by particular parents [accessibility]

### ISSUE THREAD

**Issue by Aellynd** [formkit/formkit#1326]
### Reproduction

https://formkit.link/cd719fb7236742ebf0d39717ad863c9e

### Describe the bug

Hi, we have recently started using the togglebuttons input and have found an accessibility issue:

- Certain ARIA roles must be contained by particular parents (User Impact: Critical, Guidelines: WCAG 2.1 (A), WCAG 2.0 (A), WCAG 2.2 (A), EN 301 549)

This is due to <li> elements that have role="listitem" that are not contained by a parent with role="list". 

I hope it is clear, otherwise feel free to ask me more questions.
Thanks in advance!

### Environment

• Windows 10 Pro
• Chrome 124.0.6367.61

**Comment by Aellynd** [comment]
I appreciate the swift action and response @sashamilenkovic! 

I did notice while upgrading that now a new accessibility issue has been created:
- <li> elements must be contained in a <ul> or <ol>. 

This is due to the wrapper ul having role="group". Should I create a new issue for this?

As a general tip for anybody interested in accessibility, you can use all kinds of tools to review the accessibility of your application, e.g. lighthouse in chrome or the accessible web helper extension (or any other tool driven by axe-core) to identify these issues. There are also axe-core related tools that can be used in unit tests (e.g. vitest-axe) to ensure new accessibility issues have no chance to appear without the developer knowing.

Thank you for your time and effort!

**Comment by sashamilenkovic** [comment]
@Aellynd Hey there! Whoops! Oversight on my part. Yes, if you wouldn't mind filing another issue that would be great.
