### ISSUE TITLE
Togglebuttons: Elements must only use supported ARIA attributes & Required ARIA attributes must be provided [accessibility]

### ISSUE THREAD

**Issue by Aellynd** [formkit/formkit#1327]
### Reproduction

https://formkit.link/cd719fb7236742ebf0d39717ad863c9e

### Describe the bug

Hi, we have recently started using the togglebuttons input and have found two related accessibility issues:

- Elements must only use supported ARIA attributes (User Impact: Critical, Guidelines: WCAG 2.1 (A), WCAG 2.0 (A), WCAG 2.2 (A), EN 301 549)
- Required ARIA attributes must be provided. (User Impact: Critical, Guidelines: WCAG 2.1 (A), WCAG 2.0 (A), WCAG 2.2 (A), EN 301 549)

This is due to the buttons having role="radio" and aria-pressed. There is a missmatch here, either they need to be role="button" and aria-pressed (as expected for togglebuttons I believe) or role="radio" and aria-checked.

I hope it is clear, otherwise feel free to ask me more questions.
Thanks in advance!

### Environment

• Windows 10 Pro
• Chrome 124.0.6367.61

**Comment by sashamilenkovic** [comment]
@Aellynd Hey there! Appreciate the feedback on accessibility. I've gone ahead and removed `role="button"` seeing as the element is a button already. You can see this at FormKit Pro 0.122.19. Feel free to reopen if you see any remaining issues.

**Comment by Aellynd** [comment]
Thank you for your swift action and reply, it is much appreciated!
