### ISSUE TITLE
Mask removes fractional separator

### ISSUE THREAD

**Issue by dreamerrrrrrrrr** [formkit/formkit#1333]
### Reproduction

https://bit.ly/4b4xpl0

### Describe the bug

I use mask as money input. When I want to change value, for example, from 1.00 to 2.00, I remove number up to the point and then put 2, it becomes not 2.00, but 200.

https://github.com/formkit/formkit/assets/162573544/32c32176-0d71-448f-bb01-83fb4a88b9cf

### Environment

• OS: macOS Sonoma 14.3.1
• Browser: chrome
• Version: 124.0.6367.62

**Comment by sashamilenkovic** [comment]
@dreamerrrrrrrrr Hey there! We actually just released a new FormKit Pro currency input you can check out here: https://formkit.com/inputs/currency.
