### ISSUE TITLE
Taglist-Options flying in with AutoAnimatePlugin 

### ISSUE THREAD

**Issue by MaxZelinka** [formkit/formkit#1336]
### Reproduction

https://formkit.link/f12d1ec7971ddef4ec5f9cb2b28ac91e

### Describe the bug

It seems the `createAutoAnimatePlugin` has some problems with the FormKit taglist. Whenever the Taglist is open, the itemlist flying from the left-top corner to the input field, once every re-loading of the page.

Discord-Discussion: https://discord.com/channels/793529058377072650/940340536747896842/1232298563434713160

### Environment

• OS: MacOS 14.4.1
• Browser Opera 109.0.5097.45
• Version  "@formkit/addons": "^1.6.2",

**Comment by andrew-boyd** [comment]
While we look into this (not ETA) you can prevent this behavior by removing the `inner` section from the `global` animation parent targets as part of your setup of the plugin: https://formkit.link/ca0dca0de14c4fc16b05cf67ac3159e8
