### ISSUE TITLE
Module not found: Error: Can't resolve 'tailwindcss/plugin'  (with possible fix)

### ISSUE THREAD

**Issue by ixperiencenl** [formkit/formkit#134]
### Reproduction

https://github.com/formkit/formkit/

### Describe the bug

While trying to use the TailwindCSS plugin, I got this error:
`ERROR in ./node_modules/@formkit/tailwindcss/dist/index.mjs 1:0-40
Module not found: Error: Can't resolve 'tailwindcss/plugin' in '/node_modules/@formkit/tailwindcss/dist'
Did you mean 'plugin.js'?
BREAKING CHANGE: The request 'tailwindcss/plugin' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.` 

**Package.json contents:**
"devDependencies": {
        "autoprefixer": "^10.4.2",
        "axios": "^0.21.4",
        "browser-sync": "^2.27.7",
        "browser-sync-webpack-plugin": "^2.3.0",
        "laravel-mix": "^6.0.43",
        "lodash": "^4.17.19",
        "mix-tailwindcss": "^1.3.0",
        "resolve-url-loader": "^4.0.0",
        "sass": "^1.49.9",
        "vue": "^3.2.29",
        "vue-loader": "^17.0.0",
        "vue-template-compiler": "^2.6.14"
    },
    "dependencies": {
        "@formkit/tailwindcss": "^1.0.0-beta.5",
        "@formkit/vue": "^1.0.0-beta.5",
        "@fortawesome/fontawesome-free": "^6.0.0",
        "@popperjs/core": "^2.11.2",
        "@tailwindcss/forms": "^0.4.0",
        "@tailwindcss/typography": "^0.5.2",
        "browser-sync-webpack-plugin": "^2.3.0",
        "chart.js": "^3.7.1",
        "chartjs": "^0.3.24",
        "postcss": "^8.4.8",
        "sass-loader": "^12.6.0",
        "tailwindcss": "^3.0.23",
        "vue": "^3.2.29",
        "vue-axios": "^3.4.1",
        "vue-router": "^4.0.12",
        "vuex": "^4.0.2"
    }

**Fix for this was to change** 
`import plugin from 'tailwindcss/plugin';`
to 
`import plugin from 'tailwindcss/plugin.js';`

in **@formkit/tailwindcss/index.mjs** 

I hope this helps someone :) Thanks for this great package.

### Environment

• OS: Ubuntu 18.03 / Node v16.14.0 / Webpack 5.70.0 / VueJS 3 in combination with Laravel Mix (latest)
• Browser: Chromium / Firefox
• Version: n/a

**Comment by andrew-boyd** [comment]
Thank you for the report @ixperiencenl. I'll look into this.

**Comment by andrew-boyd** [comment]
@ixperiencenl This has been fixed and will ship in `beta.6`. If you'd like to use it _now_ you can update your `@formkit/tailwindcss` in your `package.json` to target `next`.
