### ISSUE TITLE
Pro Slider show-input inputs not reactive

### ISSUE THREAD

**Issue by leemartin** [formkit/formkit#1341]
### Reproduction

https://formkit.link/65550963434f345c48d27195c8d17b7a

### Describe the bug

I'm attempting to use the Pro Slider input as a way for users to be able to trim audio files. In order to do this, the user selects an audio file and I get the file's duration. I then pass that duration back to the Pro slider input as a new dynamic `max` value. In addition, I have written a custom rule called duration which makes sure the difference of the multiple values (start/end) are less than a max duration I specify. (In the case of this reproduction, 30 seconds.) If you click the "change" button, I use a ref element to reactively update the `max` prop of the Slider input. In order to reproduce the issue, first click the "Change" button to simulate a `max` prop change from the default of 60 to 360. You must then select a portion of the track beyond the the 60 second mark. Finally, click submit on the form and you'll see the input warning on the `show-input` field. If you look at the output code of the FormKit Playground, you'll see that the `show-input` fields `max` props are not updating with the reactive element. This is also the case for dynamically changing the `disabled` prop and I'd suspect other props. I posted about this on the forum with videos here:

https://discord.com/channels/793529058377072650/1233787079247528056/1233787079247528056

Any help is much appreciated!

### Environment

• OS: macOS, iOS
• Browser Chrome, Safari

**Comment by leemartin** [comment]
I should mention that, for now, I am using it without the `show-input` and it works fine.

**Comment by andrew-boyd** [comment]
More context: https://twitter.com/0xBOYD/status/1788544209026232734
