### ISSUE TITLE
beforeStepChange in multi step plugin is fired without step change

### ISSUE THREAD

**Issue by dulnan** [formkit/formkit#1343]
### Reproduction

https://formkit.link/1ba7c9017f2a41c01965c6fb86dc3d7e

### Describe the bug

When using the beforeStepChange event on a multi step form in combination with `:allow-incomplete="false"`, the event is fired even when the step did not actually change. Maybe this is by design, in which case there should probably be a "afterStepChange" event, so that it's possible to keep track of the current visible step. In my case I'd like to add this information to the URL so that a browser refresh shows the same step again.

### Environment

• Version 1.6.2

**Comment by andrew-boyd** [comment]
This is a good catch — I think an adding an `afterStepChange` event is probably the correct move here.

**Comment by andrew-boyd** [comment]
Upon inspecting the code, I feel that the `beforeStepChange` firing when the step is not actually going to change is a bug, so I have corrected that behavior. `beforeStepChange` should now only file when the step actually will change and that behavior can be depended on to do what you're trying to do in your project.
