### ISSUE TITLE
Prefix Icon not aligned in Datepicker

### ISSUE THREAD

**Issue by MalachiDraven** [formkit/formkit#1347]
### Reproduction

https://formkit.link/68113e7500c071fd9206382030696382

### Describe the bug

Using the `prefix-icon` setting with the Datepicker input isn't working correctly. The icon isn't aligned properly, even when using the Playground.

![image](https://github.com/formkit/formkit/assets/21045455/b08085ea-e2c7-4c58-b33d-cb3e9e16f04c)

### Environment

• OS: Windows 10
• Browser: Firefox latest

**Comment by andrew-boyd** [comment]
@MalachiDraven — This has been fixed and if you run `npx formkit@latest theme` in your project you should get the latest version. Will get the docs site updated to include the latest version of the Regenesis theme shortly.

**Comment by andrew-boyd** [comment]
Also deployed for formkit.com. 👍
