### ISSUE TITLE
Styling discrepency for select in firefox

### ISSUE THREAD

**Issue by Archetipo95** [formkit/formkit#135]
### Reproduction

https://formkit.link/8245b0e56878480866419f9b5b92730b

### Describe the bug

Select options are visualy different. It's the same browser window.

![Schermata 2022-03-09 alle 17 15 18](https://user-images.githubusercontent.com/11798239/157485392-8fd6d685-04fd-482b-b79c-1f09f99c9125.png)
![Schermata 2022-03-09 alle 17 15 30](https://user-images.githubusercontent.com/11798239/157485416-8c18da64-ea46-433a-bbe0-67874d73843d.png)

### Environment

• OS: MacOS 12.1
• Browser firefox
• Version 98

**Comment by GustavoFenilli** [comment]
It seens to be because there is a `data-placeholder="true"`, if you select a value the style changes.

**Comment by Archetipo95** [comment]
Yes I confirm, that's it. For example in chrome I didn't notice it because it was styled the same always.

**Comment by andrew-boyd** [comment]
To confirm, this is not a bug it's just the way Firefox chooses to render a select with and without a placeholder?

**Comment by GustavoFenilli** [comment]
@andrew-boyd I think its more about Firefox rendering different styles based on if there is or not a value selected.

**Comment by justin-schroeder** [comment]
@andrew-boyd some of our styles assume the system will take over rendering and ignore them, but on some platforms like firefox, the styles "bleed" through
