### ISSUE TITLE
Not able To pass Validation condition On input Field 

### ISSUE THREAD

**Issue by yogendrarr** [formkit/formkit#1357]
### Reproduction

https://formkit.com/essentials/validation

### Describe the bug

1. If i am giving required to given field so i want to be validate given field By using True False.
2. If my condition is false then given input should not Validate it  should optional . 
3. for example in in vee-validate. for ex->
4.   v-validate="{ required: (isEntityRoleMandatory == 1) }" 
5. can we do this in formkit validation?

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
You can do this using a conditional prop:

https://formkit.link/8078c60918386346316fbc4f74d332a8
