### ISSUE TITLE
Hovering dates in datepicker is very slow

### ISSUE THREAD

**Issue by dulnan** [formkit/formkit#1360]
### Reproduction

https://formkit.link/fe4ec94aa80661e9281fea631334bd90

### Describe the bug

I haven't yet looked at exactly what might cause it specifically, but I was able to reproduce it with the most basic example from the docs.

Opening the datepicker and just moving the mouse over the dates felt very sluggish. Upon looking at it in the performance tab I saw that every mousenter event takes ~160ms.

![image](https://github.com/formkit/formkit/assets/4155003/a418f25c-b45d-42af-aa5f-d39c32ec2b60)

Looking at it locally in dev mode, it seems to call `createNodes` a lot of times. I assume it re-renders the entire (or most of the) datepicker, because opening the datepicker initially only takes 20ms more (~180ms).

### Environment

- Browser Chromium: Version 124.0.6367.155 (Official Build)

**Comment by justin-schroeder** [comment]
I do see a performance hit when using the `value-format` prop and having a value applied:

https://formkit.link/49d30a3d2b8049386969bec88e0b41b9

However I don’t see the same performance issue in the example you posted. Either way we need to address this, but are you still seeing the issue in your posted example: https://formkit.link/fe4ec94aa80661e9281fea631334bd90

Maybe some screen captures and more environment details would be helpful too such as the OS and version of formkit and formkit pro.

**Comment by dulnan** [comment]
I was using my notebook (~5 year old, rather low-performance Intel Core i7-7500U) when creating this issue. Now back on my PC (much more performant AMD Ryzen 9 7950X) the same example renders at around 40ms for the mouseenter event. However a 4x CPU slowdown (to get to more "average" CPU levels) again results in quite a lag and >100ms for the event.

On both my notebook and PC I'm using Manjaro Linux (running 6.9.0-1) and version 124.0.6367.155 of chromium.
In my local setup I'm using the latest FormKit versions (1.6.3 and 0.125.8 for pro), I assume the same versions as in the playground.

I can also confirm that the example you posted with the `value-format` prop has quite the lag, even without CPU throttling. The mouseenter event takes about 130ms. And with 4x CPU slowdown it's 600ms :sweat_smile:

**Comment by sashamilenkovic** [comment]
@dulnan Hey there! We took a look at this issue. Our initial benchmarks for performance at 6x CPU throttle when hovering over the day cells was ~72ms and ~185ms with the `value-format` prop assigned. At FormKit Pro v0.126.5, these numbers are now both down to around ~22ms. Let us know if you're seeing this improvement as well after updating.

**Comment by sashamilenkovic** [comment]
@dulnan Hey, I'm actually going to close this for now. Let me know if you are still having significant latency issues.
