### ISSUE TITLE
Transferlist has accessibility issues. Can be seen by using dev tools lighthouse

### ISSUE THREAD

**Issue by sashamilenkovic** [formkit/formkit#1364]
### Reproduction

https://formkit.link/07d65b515f0982e30d4185d3e6d95e45

### Describe the bug

Transferlist has various accessibility issues.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by Mleng89** [comment]
Hi @sashamilenkovic I had recently updated FormKit Pro v0.126.0 from v0.125 to view these fixes. 

I still seem to be getting the ARIA issue with lighthouse as seen in the attached screenshot. This is pointing towards the target table as the source table issue is no longer popping up.

![Screen Shot 2024-05-17 at 2 58 06 PM](https://github.com/formkit/formkit/assets/60058291/7504004c-b102-422e-a55d-902c231e4335)

**Comment by sashamilenkovic** [comment]
@Mleng89 I'll take a look at this tomorrow.

**Comment by sashamilenkovic** [comment]
@Mleng89 I just tried this out and am not receiving that issue in lighthouse. If you check your node_modules is @formkit/pro installed at 0.126.0? Is your local dev using an example that differs from the playground reproduction?

**Comment by sashamilenkovic** [comment]
@Mleng89 I'm going to close this for now, but please respond with a reproduction if you are able to make one.
