### ISSUE TITLE
Currency field doesn't fire dom-input-event on user's input

### ISSUE THREAD

**Issue by dreamerrrrrrrrr** [formkit/formkit#1366]
### Reproduction

https://formkit.link/91ee471316785e54b4360bc7074c8cd2

### Describe the bug

Simple text field (type="text") fires dom-input-event, but field with currency (type="currency") not. 

### Environment

• OS: macOS
• Browser: Chrome
• Version: 118.0.5993.88 (Official Build) (arm64)

**Comment by sashamilenkovic** [comment]
@dreamerrrrrrrrr this has been resolved at FormKit Pro v0.126.8
