### ISSUE TITLE
Currency input - label slot not recognised by TS

### ISSUE THREAD

**Issue by Pajicc** [formkit/formkit#1368]
### Reproduction

https://formkit.com/inputs/currency

### Describe the bug

Label slot is not recognized by TS, but other slots are.
Versions used:
"@formkit/pro": "^0.125.8",
 "@formkit/vue": "^1.6.3",
 "typescript": "^5.4.5"
    
<img width="925" alt="image" src="https://github.com/formkit/formkit/assets/18647471/6d6f9774-eeb5-4a99-b73c-26d63f69bb33">
<img width="558" alt="image" src="https://github.com/formkit/formkit/assets/18647471/53360863-306b-43f3-86f1-5ccfed05819e">

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by sashamilenkovic** [comment]
This is resolved at FormKit Pro v0.125.9
