### ISSUE TITLE
Is this available for Svelte too?

### ISSUE THREAD

**Issue by frederikhors** [formkit/formkit#138]
### Describe the feature

Is this available for Svelte too?

**Comment by GustavoFenilli** [comment]
Not right now https://formkit.com/advanced/custom-inputs#future-proofing

**Comment by justin-schroeder** [comment]
Ha, the fact the @GustavoFenilli knew exactly where that little nugget was in the docs is impressive.

Short answer @frederikhors is no....but, stay tuned........😉
