### ISSUE TITLE
Dropdown selected option has a tabindex of 1

### ISSUE THREAD

**Issue by LindaMeijering** [formkit/formkit#1382]
### Reproduction

https://formkit.link/80bb114dcfee13cc6ca3db43a247be85

### Describe the bug

Select an option. The new element has a tabindex of 1. It should not be greater than 0 for accessibility reasons.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by sashamilenkovic** [comment]
@LindaMeijering The link you posted doesn't have the reproduction. Be sure to click "share" before pasting.

**Comment by sashamilenkovic** [comment]
@LindaMeijering Actually, this might be an issue with all of the recent issues you filed.

**Comment by sashamilenkovic** [comment]
@LindaMeijering This should be resolved at FormKit Pro v0.126.4
