### ISSUE TITLE
Colorpicker field is weirdly rendered

### ISSUE THREAD

**Issue by Lazerproof** [formkit/formkit#1387]
### Reproduction

https://formkit.link/

### Describe the bug

For some reason, color picker fields render in this way 

```
 <FormKit
        type="colorpicker"
        value="#DE1B1B"
        label="A default colorpicker input"
        popover
        help="Just the way it comes out of the box."
    />

    <FormKit
        type="colorpicker"
        inline
        value="hsla(240, 75%, 35%, 0.75)"
        label="An inline colorpicker input"
        help="Shows the colorpicker inline."
    />
```

![image](https://github.com/formkit/formkit/assets/5707348/aa335c32-674a-42ae-8cc9-0429ceeefc71)

### Environment

• OS: Winsows 11
• Browser 124.0.6367.208 (Official Build) (64-bit)
• Version
"@formkit/pro": "^0.126.4",
"@formkit/vue": "^1.6.5",

**Comment by fenilli** [comment]
Are you using the theme regenisis?

**Comment by Lazerproof** [comment]
> Are you using the theme regenisis?

Yes, here is the formkit.theme.js 
https://gist.github.com/Lazerproof/f3de4d6fccd2651e62734945e73d0b04

**Comment by fenilli** [comment]
It looks fine in the playground: https://formkit.link/80fe33e4aacc38d6ca142af5bcabef92

anything else you have there, like divs, manual changes to the classes?

**Comment by sashamilenkovic** [comment]
@Lazerproof I'm going to close this for now, but if you're able to reproduce this in a new project please reopen and let us know.
