### ISSUE TITLE
Type error on Hidden Input

### ISSUE THREAD

**Issue by luca-smartpricing** [formkit/formkit#1389]
### Reproduction

https://formkit.link/b71ceeae6c0199067da244bb9d3c2115

### Describe the bug

  I encounter a typing error in type="hidden" input

<img width="263" alt="Screenshot 2024-05-30 alle 11 31 59" src="https://github.com/formkit/formkit/assets/115626063/cac955a0-c001-4b37-8a57-93e358e9a166">
<img width="433" alt="Screenshot 2024-05-30 alle 11 32 07" src="https://github.com/formkit/formkit/assets/115626063/90dc2354-8a80-4dd0-b2ef-fdad86dc3c75">

### Environment

- Operating System: Darwin
- Node Version:     v20.11.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      telemetry, nitro, vite, experimental, runtimeConfig, app, css, modules, site, sitemap, schemaOrg, i18n, gtm, tailwindcss, formkit, postcss, devtools, routeRules
- Runtime Modules:  @nuxt/eslint@0.3.13, @zadigetvoltaire/nuxt-gtm@0.0.13, @nuxtjs/tailwindcss@6.12.0, @vueuse/nuxt@10.9.0, @nuxtjs/prismic@3.2.1, @nuxtjs/i18n@8.3.1, @nuxtjs/seo@2.0.0-rc.10, @nuxt/image@1.7.0, nuxt-icon@0.6.10, @formkit/nuxt@1.6.3, @nuxt/fonts@0.6.1
- Build Modules:    -

**Comment by justin-schroeder** [comment]
I am unable to duplicate these errors in vscode using the latest vue language tools. Can you provide any further reproduction?

**Comment by luca-smartpricing** [comment]
You are right, in a clean installation this Type error does not appear.
I really don't know what it could be. 
Thank you very much, I apologise for the fake bug
