### ISSUE TITLE
Using keyboard to navigate outside of current month closes datepicker.

### ISSUE THREAD

**Issue by justin-schroeder** [formkit/formkit#1394]
### Reproduction

https://formkit.link/f6892737e66a78c2bb7dfe7f3769dff7

### Describe the bug

When using the arrow keys to navigate around the popup calendar, the popup should *not* close when the selected day is outside the current month. Instead it should advance the calendar to that month.

https://github.com/formkit/formkit/assets/1950463/c05a209d-181e-4529-aa4f-74b2f9a80435

### Environment

• OS: macOS
• Browser Chrome
• Version FormKit Pro 126

**Comment by sashamilenkovic** [comment]
@justin-schroeder This is resolved at FormKit Pro v0.126.7
