### ISSUE TITLE
Bullets are displayed in repeater inside schema

### ISSUE THREAD

**Issue by Rednas83** [formkit/formkit#1399]
### Reproduction (only shows up in my development area)

https://formkit.link/901c3fad0e0c6891ccd9f70b8d788b34

### Describe the bug

Somehow my development  envrionment shows bullets inside the repeater object.
![image](https://github.com/formkit/formkit/assets/25219229/d4996a87-a736-4fb5-9980-1dc5dc52dc15)

It's not showing up in the Formkit PlayGround and I am using the latest theme.

Any idea how to remove it? Could it be a theme issue? 

Btw it's not showing up in a standalone repeater.

### Environment

```
------------------------------
- Operating System: Windows_NT
- Node Version:     v20.12.2
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  pnpm@8.15.1
- Builder:          -
- User Config:      telemetry, modules, icon, build, routeRules, components, content, formkit, imports, css, devtools
- Runtime Modules:  @vueuse/nuxt@10.9.0, normalizedModule(), @nuxt/content@2.12.1, @pinia/nuxt@0.5.1, @nuxtjs/tailwindcss@6.12.0, nuxt-icon@0.6.10, @formkit/nuxt@1.6.2
- Build Modules:    -
------------------------------
```

**Comment by andrew-boyd** [comment]
hey @Rednas83 — i'm going to guess you have some other styles in your project that are affecting list items in that context? The Tailwind Regenesis theme shouldn't have any styling that would add bullets to list items. If you inspect the element and take a look at the computed styles in your dev tools you should be able to see where those styles are coming from.

**Comment by Rednas83** [comment]
Thanks

I found the issue by commenting out some custom styles
```
li ul {
  padding-left: 2rem;
  list-style-type: disc;
}

li ul ul {
  padding-left: 2.5rem;
  list-style-type: square;
}
li ul ul ul {
  padding-left: 3rem;
  list-style-type: circle;
}
```
