### ISSUE TITLE
Focus state triggered when setting value programmatically

### ISSUE THREAD

**Issue by nhedger** [formkit/formkit#1400]
### Reproduction

https://formkit.link/66dd359a22099a64e6abb17a021cce1a

### Describe the bug

I'm using an `input` event on a `checkbox` input to trigger a prefill on an `autocomplete` field and for some reason, calling `node.input` on that autocomplete field triggers some kind of "focus" state. I was wondering if it's possible at all to set the value of a field _silently_.

In the following example, the issue becomes even more apparent when combined with `open-on-focus` and `close-on-select=false`.

https://formkit.link/66dd359a22099a64e6abb17a021cce1a

When setting the value programmatically using `input`, my expectation was that it wouldn't trigger any focus state, and wouldn't open the dropdown. 

### Environment

• OS: macOS
• Browser Arc (chromium)
• Version: Chromium Engine Version 125.0.6422.113

**Comment by sashamilenkovic** [comment]
@nhedger This should be resolved at FormKit Pro v0.126.10
