### ISSUE TITLE
`datepicker`: Weekdays do not honor locale

### ISSUE THREAD

**Issue by hognevevle** [formkit/formkit#1413]
### Reproduction

https://formkit.link/2d98a51f6efde07396480dd6576401a9

### Describe the bug

In your [YouTube video](https://youtu.be/c-P-DUZeU1U?si=7ja5dz2VB7TiObYM&t=304), the weekdays seem to follow the locale (as shown in your `uk` example). This longer seems to be the case, and I cannot figure out how to change the display of the weekdays to reflect my locale. 

![CleanShot 2024-06-11 at 15 35 30](https://github.com/formkit/formkit/assets/2721188/42a2a8e4-af3b-4444-b349-7aa881278653)

### Environment

• OS: macOS
• Browser Chrome
• Version 124.0.6367.203

**Comment by hognevevle** [comment]
It seems to work in the playground if I select `1.7.x (next)`, so maybe it's already fixed? When is 1.7 scheduled to be released?

**Comment by sashamilenkovic** [comment]
@hognevevle Hey there. 1.7.x is referencing an older version of FormKit Pro. This issue is likely a regression. We will take a look at this.

**Comment by sashamilenkovic** [comment]
@hognevevle Hey there! This appears to be working now (when I open up your reproduction I am seeing the weekday locales changed). I'm closing this for now. Feel free to comment back if I'm missing something and I'll reopen.
