### ISSUE TITLE
Custom classes for text inputs broken

### ISSUE THREAD

**Issue by csakis** [formkit/formkit#1416]
### Reproduction

https://formkit.link/0092ce8b8eea61b298d884ed2cf4821b

### Describe the bug

If I apply custom classes such as this:
```
classes: {
    outer: "$reset flex m-2",
    input: "$reset extra",
  },
```
this will apply the `extra` class not just to text inputs but all inputs, including buttons.
if I try to specify:

```
 classes: {
    text: {
      outer: "$reset flex m-2",
      input: "$reset extra",
    },
  },
```

no classes will be applied to the text inputs.
 

### Environment

• OS: Windows 10
• Chrome
• 126

**Comment by andrew-boyd** [comment]
You can use the `generateClasses` helper function with takes the object shape you're expecting and coverts in to the structure necessary for FormKit internals.

https://formkit.link/e2cbc18cfd1af33ff6dfa7bba02734a3

**Comment by csakis** [comment]
Indeed, that worked. Thank you, Andrew!
