### ISSUE TITLE
Typescript: Property 'label' does not exist on type FormKitTogglebuttonsSlots

### ISSUE THREAD

**Issue by jjjrmy** [formkit/formkit#1426]
### Reproduction

https://formkit.link/1f5d06ccff7653c39ceb200ec9ccba52

### Describe the bug

Getting a typescript warning/error when using the `#label` slot for ToggleButtons

I think the slot should instead be `#legend` to match with Radiobutton and Checkboxes slots

### Environment

latest

**Comment by sashamilenkovic** [comment]
@jjjrmy The typing for the label should be resolved at FormKit Pro v0.127.15. As for whether or not the section should be that of a label or legend, I am of the belief that the togglebuttons semantically is different than the radio or checkbox inputs and would be better served with a label. If anyone feels differently, feel free to ping me back here and we can discuss.
