### ISSUE TITLE
Number Input Clamp Value

### ISSUE THREAD

**Issue by SDIjeremy** [formkit/formkit#1430]
### Reproduction

https://formkit.link/b23a99954d7b7188f331fd3f82cf8d52

### Describe the bug

This plugin is supposed to not allow numbers above or below the maximum.
It only seems to work once, after you set the value if the number is too large it won't set it again.

Example:
1) type 99 -> it goes to 10
2) type 9 again -> now we're at 109

It should never go above 10

### Environment

Latest

**Comment by SDIjeremy** [comment]
Other failed solutions:
https://formkit.link/2dfe1a7ae74c6c762f648e8346da3d12
https://formkit.link/b1bfaf632566bef0e60b124d3078ef33

It seems like the VALUE shows correctly but the input text is wrong.

**Comment by justin-schroeder** [comment]
Yes, in Vue inputs are only partially controlled. meaning vue allows the native input to be modified even if the underlying model has not changed (related, if you loot the code for v-model youll notice it manually controls for this on HTML inputs). Unfortunately, this means you have to do a bit of extra chicanery to achieve the desired state with native html inputs:

https://formkit.link/ddf7fb1f5a27a810c9ce6d1b49f48e71

**Comment by SDIjeremy** [comment]
amazing work!

**Comment by SDIjeremy** [comment]
@justin-schroeder 
When using a currency input, this fix doesn't work as we lose the `$`
```js
domElement.value = node._value
```
https://formkit.link/b585d43685746c9d06d832d137eab0e1

**Comment by justin-schroeder** [comment]
The currency input is not "native" as we are already doing a lot of hijacking of the input state. But it already has a min/max prop

**Comment by SDIjeremy** [comment]
@justin-schroeder 

https://formkit.link/66a6a018a996fec28fee42f8eb8d3e98

https://github.com/formkit/formkit/assets/115488848/ca22ed03-47bf-4933-a654-e932f6926307

if you delete the currency a few times then edit the number, the currency input dies.
possibly related to the reactive max?

**Comment by justin-schroeder** [comment]
You should not use your clamp plugin on the currency
