### ISSUE TITLE
Currency Input Min/Max Limit

### ISSUE THREAD

**Issue by SDIjeremy** [formkit/formkit#1431]
### Reproduction

https://formkit.link/d72f2299d4a7f154ca70fd0612a29c94

### Describe the bug

If you set `minDecimals` to `0`, then when you delete the value it just goes to empty.
You can compare the 2 inputs in the example.
The expected behavior is the first one where the value will be set to the minimum.

### Environment

Latest

**Comment by sashamilenkovic** [comment]
@SDIjeremy This seems to be working at the latest version, no?
