### ISSUE TITLE
`loadOnCreated` should check if `optionsLoader` is function before calling it.

### ISSUE THREAD

**Issue by justin-schroeder** [formkit/formkit#1434]
### Reproduction

https://formkit.link/753caf37d11f88223f1c5cf203ce7c6a

### Describe the bug

`load-on-created` immediately calls the optionsLoader assuming it is a function, but in some cases, this isnt true.

### Environment

• OS: macOS
• Browser: Chromium
• Version: 1.6.x

**Comment by sashamilenkovic** [comment]
@justin-schroeder This is resolved at FormKit Pro v0.126.12
