### ISSUE TITLE
Autocomplete input unselecting values after collapsing and opening again

### ISSUE THREAD

**Issue by rahman-anz** [formkit/formkit#1444]
### Reproduction

https://formkit.link/663fb587035f4362856b35217473af18

### Describe the bug

The bug happens in autocomplete input with multiple set to true. Steps to reproduce

1.Select 4 or more options in the input initially.
2.Collapse the dropdown
3.Reopen and the dropdown & select another item. You'll see that the one of last chosen item is unselected automatically.

This bug happens only in autocomplete-input, the dropdown-input seems fine.

### Environment

• OS: Windows 11
• Browser: Chrome
• Version: Formkit 1.6.2 Pro 0.123.1

**Comment by sashamilenkovic** [comment]
@rahman-anz I'm seeing that the value itself remains but that the truncation at the end of the input makes it appear to be removed. Can you confirm this is the behavior you're seeing?

**Comment by rahman-anz** [comment]
@sashamilenkovic No, the value also disappears from the selected values. You can see it here clearly, where I am v-modeling the selected values

https://formkit.link/535e176c3d85e89db2c7594d32560b27

**Comment by justin-schroeder** [comment]
@rahman-anz I also am not seeing the described behavior. Could you provide a screen capture of the issue you are seeing?

**Comment by rahman-anz** [comment]
@justin-schroeder You can see it here
https://jam.dev/c/61bb4a85-0dc2-442a-aa71-700632143f8c

**Comment by sashamilenkovic** [comment]
@rahman-anz Oh, I see, appreciate the reproduction.

So, the autocomplete multi-text input (the one in question), has a unique feature where the values rendered within the text input itself become selectable. As in, clicking "REQUESTED" for example **within** the text input will actually perform a cursor selection on it. This allows for direct replacement, so the user can cursor-select a previously selected value and selection of a new value will replace it inline directly. The user can also traverse up and down values by using arrow keys.

Now, in your reproduction, it appears that you are clicking not the listbox button (the button to the right of the text input), but on the text input near the last selected value, resulting in the cursor selection, resulting in a direct replacement (the behavior you are seeing where a value appears to become deselected). I could be wrong about my assumption I'm making in your reproduction as it's a bit difficult to see where you're clicking.

So with all that being said, I am seeing one issue:

Steps to reproduce:

1). Select "Requested" and "Pending" from the autocomplete in the previous example.
2). While the listbox is still open, click the text "Requested" to perform the cursor-selection
3). Blur the text input to close the listbox. The cursor-selection is now gone.
4). Reopen the listbox by specifically clicking the listbox button the right of the input.

Assertion: You will see that the text "Requested" is again cursor-selected.

Conclusion: Cursor-selection memory should not be remembered in between opening and closing of the listbox itself.

@justin-schroeder Let me know if you agree with this when you have the chance.
@rahman-anz Let me know if you agree with my assertion about your reproduction if you click specifically the listbox button.

**Comment by rahman-anz** [comment]
@sashamilenkovic Thank you. That was it 😆
Btw, do we have a prop to control/disable this cursor-selection ?

**Comment by sashamilenkovic** [comment]
@rahman-anz There is not a prop for that currently. Have you checked out using the prop `selection-appearance="option"` or even maybe just using the `taglist` input instead?

**Comment by rahman-anz** [comment]
@sashamilenkovic  I think taglist would fit in with our needs. Thanks guys for the prompt response.
