### ISSUE TITLE
The preserve attribute will invalidate the submit

### ISSUE THREAD

**Issue by aegorx** [formkit/formkit#145]
### Reproduction

https://formkit.link/9b7fb788bcc2d15516d3c7825638e9e9

### Describe the bug

Switch to checkbox and submit again, @ submit will not be triggered

### Environment

• OS: WIN10
• Browser Chrome 99.0.4844.51
• Version beta.6 next.7

**Comment by justin-schroeder** [comment]
@aegorx good catch. This is now fixed in the `@next` tag and will be released in beta.7
