### ISSUE TITLE
valid state only correctly changes when other inputs are present

### ISSUE THREAD

**Issue by rubinlinux** [formkit/formkit#1454]
### Reproduction

https://formkit.com/playground?fkv=latest&fileTab=forms.vue&css-framework=genesis&files=jc%5B%28%27name%21%27Bs.vue%27%7Eeditor%21%27%3CscripCsetup9%26WMounted+%29+fromHvue%225%26getNodX%29+fromH%40Bkit%2Fcore%2255cWsCdata+%3D+%2853V%3AHhello%40Bkit.comJ53favorite_food%3AHPizzaJ53i7%3AHJ5%2955WMounted%7B%7BZ53cWsCBNodX%3D+getNode%7B%22BID%22%7D553BNode.W%7B%22commitJ+async+%7B%28T+%29Z*%2B8awaiCBNode.settled5*if+83%2B%7B%22UidT%3AJT%7D53%29%7D5%29%7D5Qscript95%3Ctemplate93%3Cj*type6B4*%23default6%28+UuX%294*id6BID4*%3AactiWs6false4*%3AUue6data453%3EGRlabel6Your+EmailRname6VRprefix-icW6V%25V%40domain.comRhelp6Order+cWfirmatiW+will+bXsenCto+your+addressRUidatiW6required%7CVRUidatiW-visibility6live4*%2F9GareaRname6i7Rlabel6Special+I7%25Allergies%3F+No-cWtacCdelivery%3F+LeCus+know.R%3Ahelp6%60%24%28Uue.i7+%3F+Uue.i7.length+%3A+0%29+%2F+120%604*%2F9*%3CprXwrap%3E%28%28+UuX%29%29Qpre93Qj9Qtemplate95%3Cstyle9pre%5Bwrap%5D+%2853margin-bottom%3A+1em+%27%3Aimportant%3B5%295Qstyle9%27%7Esyntax%21%27html%27%7Eadded%21true%29%5D*5333++4%5C%275%5Cn6%3D47nstructiWs8%7BBNode.cWtext.state.Uid%7D*9%3E5BformCt+G*%3Cj*3type6textH+%22J%22%2CQ%3C%2FR4*3T+payloadUvalVemailWonXe+Z%7D+%3D%3E+%28jFormKit%25Rplaceholder6%26imporC%28+%2BcWsole.log%01%2B%26%25jZXWVUTRQJHGCB9876543*_&imports=jc%28%27name%21%27ImportMap%27%7Elang%21%27json%27%7Eeditor%21%27%28*+1vue%5C%211https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fvue%403%2Fdist%2Fvue.esm-browser.min.js0*%29*%27%29*%5Cn0%5C%271+0%0110*_

### Describe the bug

I'm expecting to see the console.log output when the email field is changed between valid and invalid, but it does not trigger unless you also edit the other field. Gustavo Fenilli suggested this may be a bug.

### Environment

• Linux (mint 21)
• Firefox
• 128

**Comment by justin-schroeder** [comment]
@rubinlinux I think the issue is simply one of timing. The commit handler is called synchronously during the commit itself, validation has not yet run. If you are trying to deduce validity state, you could listen to something like the number of blocking messages (~ correlated with validation errors, although some messages are system ones, like waiting for an input to finish debouncing). For example:

https://formkit.link/34151061a83f28f75594e407c4dda6ac
