### ISSUE TITLE
Repeater sortability not functioning properly

### ISSUE THREAD

**Issue by sashamilenkovic** [formkit/formkit#1455]
### Reproduction

https://formkit.link/184c8c55493974ac4e09ad349b65f8c4

### Describe the bug

Sortability in repeater is not working properly. This is because the style `pointer-events-none` is being applied to class `formkit-dropZone` that is applied in the `repeater__item` class. This should be removed from the regenesis theme.

Current workaround would be to remove that style.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by andrew-boyd** [comment]
This has been resolved
