### ISSUE TITLE
`autocomplete`: Async options not filterable

### ISSUE THREAD

**Issue by hognevevle** [formkit/formkit#1459]
### Reproduction

https://formkit.link/7f005786238fdc277886d6380666e771

### Describe the bug

When loading options through an (async) function, the options are not filterable.

https://github.com/user-attachments/assets/e04c0d8e-3b65-4db1-a9a2-0fe0a90c7200

### Environment

• OS: Windows
• Browser: Chrome
• Version: 126.0.6478.127

**Comment by hognevevle** [comment]
Is there any way to contribute to Pro inputs?

**Comment by sashamilenkovic** [comment]
@hognevevle When providing your own asynchronous function to the options prop, you are in charge of your own filtration (which options are returned). Docs on this are here: https://formkit.com/inputs/autocomplete#search-parameter

**Comment by sashamilenkovic** [comment]
@hognevevle If you have any more questions, feel free to reopen this issue.

**Comment by hognevevle** [comment]
Thanks a lot for the guidance @sashamilenkovic, sorry for missing that :)

**Comment by sashamilenkovic** [comment]
@hognevevle no worries at all! I can see how that might be confusing.
