### ISSUE TITLE
Wrong values when using multiple $get

### ISSUE THREAD

**Issue by pop123123123** [formkit/formkit#146]
### Reproduction

https://formkit.link/080cd6d758d614a68aaac2334331ec0e

### Describe the bug

When using multiple `$get` in **one** expression (in a `children` or `if` for instance), the first `$get` propagates its results to all subsequent `$get`.
Our use case involve complex `if` with boolean logic, but as shown in the playground and with our testing, the issue arises anywhere as soon as more than one `$get` is used.

If this is a design decision, a fix would be to display a warning / error when the parser detects multiple `$get` in one expression, and add a big warning in the docs.

In the meantime, we just use multi-layered `if`, but for other types of expressions (boolean or), it can't be replaced that easily.

### Environment

• Kernel: Linux 5.15
• Browser: Firefox@latest
• Version: 1.0.0-beta.6

**Comment by justin-schroeder** [comment]
This is now fixed in the `release/beta.7` branch and published under the `@next` tag
