### ISSUE TITLE
Mask input and autocomplete failing validation

### ISSUE THREAD

**Issue by ArneMangelschots** [formkit/formkit#1461]
### Reproduction

https://formkit.link/50bee0cad7ba9dad4b8b7c88e1a0f5c3

### Describe the bug

When a mask input gets filled in by the browser autocomplete validation still says it's required.

![Screenshot 2024-07-25 at 15 25 36](https://github.com/user-attachments/assets/86db4bd6-0148-48fa-a909-b45c9f6a070f)

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by sashamilenkovic** [comment]
Related issue here: https://github.com/formkit/formkit/issues/1315. I'm going to close this one in favor of the existing one.
