### ISSUE TITLE
Repeater should consistently render when the default slot is empty

### ISSUE THREAD

**Issue by justin-schroeder** [formkit/formkit#1465]
### Reproduction

https://formkit.link/5557f152689b790e9c0f1e923384a161

### Describe the bug

The default behavior of a repeater that has no children should be to display, at a minimum, an empty box with controls when it has a value of at least 1 item.

### Environment

1.6.x

**Comment by sashamilenkovic** [comment]
This should be resolved at FormKit Pro v0.126.15
