### ISSUE TITLE
<FormKit type="mask"> renders <input type="mask">

### ISSUE THREAD

**Issue by kswedberg** [formkit/formkit#1467]
### Reproduction

https://formkit.link/ebdb38586ac8430ec5ff6cc048ca230e

### Describe the bug

When using `<FormKit type="mask">` or `<FormKit type="barcode">` the type attribute of the rendered `input` matches that type value. It should instead be `type="text"`.  See [discussion on discord](https://discord.com/channels/793529058377072650/940340536747896842/1268283479142043758).

### Environment

• OS: MacOS
• Browser: all
• Version: 1.6.x (latest)

**Comment by kswedberg** [comment]
Unfortunately, the plugin used in the reproduction link above for `<FormKit type="mask">` doesn't work for `<FormKit type="barcode">` without breaking the styles.

**Comment by sashamilenkovic** [comment]
@kswedberg This should be resolved at FormKit Pro v0.126.15
