### ISSUE TITLE
Nested repeater causes recursive updates

### ISSUE THREAD

**Issue by madsh93** [formkit/formkit#1495]
### Reproduction

https://formkit.link/a083cd47eaf0d0c6d81ac247f535d854

### Describe the bug

When having nested repeaters, it causes an error after about 7 objects in the array to log:

```js
Uncaught (in promise) Maximum recursive updates exceeded in component <FormKit>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.
```

When having many more, it crashes my app entirely.

### Environment

• OS: macOS
• Browser: Arc (Chrome)
• Version: 1.57.2

**Comment by justin-schroeder** [comment]
Indeed. this is no bueno. Thank you for the minimal reproduction ❤️

**Comment by justin-schroeder** [comment]
iiiinteresting...i wonder if Vue 3.5 fixed something?
