### ISSUE TITLE
After Update to Vue 3.5.x FormKitSchema cleanup on unmount throws Exception 

### ISSUE THREAD

**Issue by sfxcode** [formkit/formkit#1496]
### Reproduction

https://github.com/formkit/formkit/blob/6b4542a3e013bfff810e126eb20eb2fbce6f25af/packages/vue/src/FormKitSchema.ts

### Describe the bug

Hi,

sorry for passing only the link to the code where the exception is thrown, but you need some more complex application where you toggle between multiple components that includes a FormkitSchema component.

After switching to Vue 3.5 it seems that data on cleanup can be null.

```
    /**
     * Perform cleanup operations when the component is unmounted. This should
     * remove any memory allocations that were made during the render process.
     */
    function cleanUp() {
      // Perform cleanup operations
      clean(props.schema, props.memoKey, instanceKey)
      /* eslint-disable @typescript-eslint/no-non-null-assertion */
      if (data.node) data.node.destroy()
      data.slots = null!
      data = null!
      render = null!
      /* eslint-enable @typescript-eslint/no-non-null-assertion */
    }```

Access data.node throws part throws exception:

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'node')
    at cleanUp (@formkit_vue.js?v=c3cff561:1581:16)
    at chunk-CXSE3S54.js?v=c3cff561:4847:40
    at callWithErrorHandling (chunk-CXSE3S54.js?v=c3cff561:2288:19)
    at callWithAsyncErrorHandling (chunk-CXSE3S54.js?v=c3cff561:2295:17)
    at hook.__weh.hook.__weh (chunk-CXSE3S54.js?v=c3cff561:4827:19)
    at flushPostFlushCbs (chunk-CXSE3S54.js?v=c3cff561:2474:28)
    at flushJobs (chunk-CXSE3S54.js?v=c3cff561:2516:5)
```

Changing back to Vue 3.4 fix the issue.

Greetings,

Tom
 

### Environment

• OS: MacOS 14.6.1
• Browser Chrome
• Version 128.0.6613.120 (Offizieller Build) (arm64)

**Comment by sfxcode** [comment]
It does not happen always, maybe some kind of timing problem.

**Comment by sfxcode** [comment]
```
  if (data?.node) {
    data.node.destroy()
  }
  if (data?.slots) {
    data.slots = null!
  }
  data = null!
```

should be a possible fix ...

**Comment by russo97** [comment]
I am facing an issue after update Vue to 3.5.x too

I cant submit a form programatically, and them was working normally before with Vue 3.3.x

**Comment by OlaAlsaker** [comment]
We are also experiencing this issue. It does not happen all the time but randomly. It makes the whole frontend crash and requires a refresh. Really frustrating.

**Comment by jpcarpenter** [comment]
I was encountering this same issue with my Nuxt 3 project.  After updating to 1.6.6, I now get a fatal error on page loads:

```
500
Cannot read properties of null (reading 'props')

at refreshComputed (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:365:28)
at isDirty (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:335:68)
at get dirty [as dirty] (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:268:12)
at job (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:1811:40)
at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:200:33)
at flushJobs (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:408:9)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

The weird thing is the error disappears whenever I remove the `help` prop from any/all `FormKit` inputs on the page... 

```javascript
<FormKit
  type="email"
  label="Busniess Email Address"
  name="businessEmailAddress"
  help="The primary email address for the business."  // <--- error disappears when help prop is removed
  validation="required|email"
  validation-visibility="blur"
  placeholder="name@business.com"
/>
```

My `package.json` is as follows:

```
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "dependencies": {
    "@formkit/addons": "^1.6.5",
    "@formkit/drag-and-drop": "^0.1.6",
    "@formkit/icons": "^1.6.5",
    "@formkit/pro": "^0.127.0",
    "@pinia/nuxt": "^0.5.3",
    "graphql": "^16.9.0",
    "graphql-tag": "^2.12.6",
    "jsonwebtoken": "^9.0.2",
    "nuxt": "^3.12.4",
    "pinia": "^2.2.2",
    "vue": "latest",
    "vue3-google-map": "^0.21.0",
    "vue3-toastify": "^0.2.2"
  },
  "devDependencies": {
    "@formkit/auto-animate": "^0.8.2",
    "@formkit/nuxt": "^1.6.6",
    "@iconify-json/heroicons-solid": "^1.1.11",
    "@nuxt/icon": "^1.4.5",
    "@nuxtjs/google-fonts": "^3.2.0",
    "@nuxtjs/tailwindcss": "^6.12.1",
    "@pinia-plugin-persistedstate/nuxt": "^1.2.1",
    "@tailwindcss/forms": "^0.5.7",
    "@types/google.maps": "^3.58.0",
    "@types/jsonwebtoken": "^9.0.6",
    "@vueuse/nuxt": "^10.11.1",
    "sass": "^1.77.8",
    "typescript": "^5.5.4"
  }
}

```

**Comment by justin-schroeder** [comment]
Truly bizzare! Try making sure all your @formkit 1.6.5 versions are bumped to 1.6.6 (looks like a couple still say 1.6.5, although the version constraint should in theory still use the correct versions there), nuke your node_modules and try a re-install — the only think I can think of that would cause something that bizzare is mismatched versions

**Comment by jpcarpenter** [comment]
Bizarre indeed! So, I've tried that at least a dozen times, and each time I get the same error. Crazy thing is that I even had to run `npm cache clean --force` in order to effectively revert back to 1.6.5 so that the app could get back up and running.

One thing I've noticed this time is that after updating all @formkit version from 1.6.5 to 1.6.6, my package-lock.json still has "@formkit/core" and "@formkit/inputs" peer dependencies of @formkit/pro set to 1.6.5. Not sure if this is expected, but it is the only two instances of 1.6.5 inside my package-lock.json file after bumping everything up to 1.6.6.

**Comment by jpcarpenter** [comment]
I can confirm that removing `"@formkit/pro": "^0.127.0",` from package.json fixes the issue. Is there another version I need to bump this up to as well?

**Comment by justin-schroeder** [comment]
Hmm, the version constraint `^` should allow those to resolve to the same version (1.6.6)... also since they are just peerDependencies there should not be any 1.6.5 code in your code base.

**Comment by jpcarpenter** [comment]
Got ya. I'm gonna revert back to 1.6.5 for the time being, as I don't have time to dig into this any further at the moment. I'll report back if I come across a fix in the future.

**Comment by sashamilenkovic** [comment]
> I can confirm that removing `"@formkit/pro": "^0.127.0",` from package.json fixes the issue. Is there another version I need to bump this up to as well?

FormKit Pro should be using peer dependencies. I would suggest maybe deleting your node_modules and .lock file and reinstalling. That might fix the version mismatch you're running into.

**Comment by jpcarpenter** [comment]
It looks like it's something to do with Vue 3.5.6. I changed my Vue version from having `"vue": "^3.5",` to `"vue": "3.5.5"`, and the error no longer appears. All my formkit versions are set to 1.6.6 as well. 

The Vue changelog for 3.5.6 mentions some updates to reactivity and how it relies on a dirty check when computed has deps:
>reactivity: rely on dirty check only when computed has deps (https://github.com/vuejs/core/issues/11931) ([aa5dafd](https://github.com/vuejs/core/commit/aa5dafd2b55d42d6a29316a3bc91aea85c676a0b)), closes https://github.com/vuejs/core/issues/11929

That's the one thing that stuck out to me based on the context of the error message I was receiving. I could be completely wrong however.

**Comment by justin-schroeder** [comment]
I am arriving at the same conclusion — although I also can only reproduce this issue in nuxt and not in vite.

**Comment by justin-schroeder** [comment]
@jpcarpenter can you checkout 1.6.7? I think this is fixed there now.

**Comment by jpcarpenter** [comment]
All seems well now! Thanks for taking the time looking into this!
