### ISSUE TITLE
compatibility with Vue 3.5.6

### ISSUE THREAD

**Issue by Rednas83** [formkit/formkit#1501]
### Reproduction

https://github.com/Rednas83/formkit-app

### Describe the bug

v-model is not populated with form data when using `FormKitSchema`

Also there are hydration mismatch warnings in the client
![image](https://github.com/user-attachments/assets/f7e51713-0b5f-4973-b836-2553f40886b1)

Tried:
* Updating packages

### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.17.0
- Nuxt Version:     3.13.2
- CLI Version:      3.13.2
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.10.0
- Builder:          -
- User Config:      compatibilityDate, devtools, modules, formkit
- Runtime Modules:  @formkit/nuxt@1.6.6
- Build Modules:    -
------------------------------

**Comment by Rednas83** [comment]
After downgrading nuxt it works again
```
pnpm uninstall nuxt
pnpm install nuxt@3.13.1
```

So, it seems to be an issue with the latest nuxt version

**Comment by sashamilenkovic** [comment]
Thank you @Rednas83 we'll look into this.

**Comment by Rednas83** [comment]
![MarcaMicaelaViciconteGIF](https://github.com/user-attachments/assets/10d8075b-7f99-4f85-9a35-148a5295ac53)

**Comment by Rednas83** [comment]
The hydration mismatch warnings are gone, but the `v-model` is still not updated with the form values.

For now I will keep using `nuxt@3.13.1` as a workaround

**Comment by Joe-Dracup** [comment]
Hi @justin-schroeder. we are experiencing problems on form submission when upgrading to vue 3.5, is this still something that you are seeing any problems around? is this worth trying to create a small reproduction of or do you believe formkit is stable when used with vue 3.5?

**Comment by justin-schroeder** [comment]
There are no known issues with 1.6.7 and vue 3.5. If you have a reproduction please share.
