### ISSUE TITLE
CSS/Timing Issue with validation

### ISSUE THREAD

**Issue by JontyMC** [formkit/formkit#1503]
### Reproduction

https://formkit.link/fb11c252df0af881b5a987741ea98f08

### Describe the bug

1. Enter some text in the field
2. Click top of submit button
3. Observe submit invalid is not called

This seems to be because the field validation is pushing the submit button down and the click event is then outside the button. Would expect the click event to register before the field validation is displayed.

### Environment

All browsers

**Comment by justin-schroeder** [comment]
this is because your error on the first input is being displayed on blur which occurs before the submit even fired. there is nothing we can do about this at a framework level, but you could change the validation-visibility on your form to be something else, perhaps "submit" instead.
