### ISSUE TITLE
[docs] new validation rules isnt working at documentation page

### ISSUE THREAD

**Issue by russo97** [formkit/formkit#1504]
### Reproduction

https://formkit.com/essentials/validation#date-after-or-equal

### Describe the bug

I tested the documentation page and the new rules from v1.6.7 are not working in the docs page (only in Microsoft Edge, Firefox runs it normally)

https://formkit.com/essentials/validation#date-after-or-equal

### Environment

• OS: Windows 10 Pro
• Browser Firefox Developer Edition, Microsoft Edge
• Version: 1.6.7

**Comment by justin-schroeder** [comment]
This is most likely your browser’s cache of the CDN where formkit is getting pulled from, try a hard reload.

**Comment by russo97** [comment]
you're right!

working fine, thanks
