### ISSUE TITLE
How to :action and @submit?

### ISSUE THREAD

**Issue by billnbell3** [formkit/formkit#1505]
### Reproduction

??

### Describe the bug

What is best practice for checking form @submit function and then using an action for "https://domain/form.js" ?

### Environment

• OS: linux
• Browser chrome
• Version latest

**Comment by fenilli** [comment]
If by action you mean the action property of a html form, you can get that inside the `@submit` using JS.

Otherwise you don't use an action, just pass it directly to the function you're using in the `@submit`.

**Comment by billnbell3** [comment]
Sorry what I meant is we have a form that we need to check a few values and create an account using fetch, then we need to submit the form to the action url like a normal form. Kinda like onsubmit and action.

We tried submitting the form to the action using fetch but the form is missing Cors and errors…

We are investigating enabling cors.

I assume that the submit will fire before the action if I have nothing defined ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by billnbell3** [comment]
Also do you have an example of getting that in submit using JS ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by fenilli** [comment]
Well FormKit is not a normal form, when you add `@submit` it won't fire the events that call action, what I mean by it is, use `@submit` and add the `:action` to the url you're calling on your submit function.

Do you have a small reproduction in the playground so I can see what you mean by your structure?

**Comment by billnbell3** [comment]
OK see https://formkit.link/8b2b123faa3a0e724099f31987ccee75

From: Gustavo Fenilli ***@***.***>
Date: Sunday, September 22, 2024 at 10:55 AM
To: formkit/formkit ***@***.***>
Cc: Bill Bell ***@***.***>, Author ***@***.***>
Subject: Re: [formkit/formkit] How to :action and @submit? (Issue #1505)
EXTERNAL: This message originated from outside of Exclusive Resorts. BE CAUTIOUS before clicking any links or attachments.


Well FormKit is not a normal form, when you add @submit it won't fire the events that call action, what I mean by it is, use @submit and add the :action to the url you're calling on your submit function.

Do you have a small reproduction in the playground so I can see what you mean by your structure?

**Comment by fenilli** [comment]
That is the thing, you don't use either for most cases, you're using vue and FormKit there, so `@submit` is all you do: https://formkit.link/46791b9fe342e28c09e8f7a4257d53a3

**Comment by billnbell3** [comment]
OK but the PARDOT url does not allow CORS, which is why I need to submit the form. Also the response from that does a redirect to a page result. I guess I can do the redirect no problem....

Let me see if I can inject a CORS header.

**Comment by fenilli** [comment]
So if it is a page request you can always submit as a page request normally, FormKit does create a normal html form: https://formkit.com/inputs/form#submitting-as-a-page-request

**Comment by billnbell3** [comment]
OK. It is pretty confusing. You call it submit() to submit the :action. It would be easier to understand if you called it submitForm() or submitAction() or something.

So the :action does not fire if you have a @submit. That is not clear in the docs. Then you can call fetch() to submit it, or use the submit() if you defined the :action.

https://formkit.link/46d908901af8fc0616e8b2e42ece0be5 is my latest example of fixing this for my form.

It is simpler to understand - but I also now know you can do a this:

```
this.$refs.form.$el.submit();
```

Which was pretty confusing. The issue with the submit() is you lose control. With the fetch() you can look for a response.status != 200.

The docs needs to be updated for sure. Not clear at all for us newbies.

**Comment by fenilli** [comment]
This is probably more of a confusion on using Vue vs Pure HTML, in the vue space it is quite normal to have `@submit` prevent the default behaviour of the browser.

When you add `@submit` it means " do what formkit should be doing ".
When you remove `@submit` it means " do what the browser should be doing ".
