### ISSUE TITLE
Reset handling not working correctly when fields have initial value "null" or "false"

### ISSUE THREAD

**Issue by dominikklein** [formkit/formkit#1509]
### Reproduction

https://formkit.link/0cc0db8bd7f704a27c20d4630765bf60

### Describe the bug

When you have a form where some fields have an initial value `null` or `false` and use the reset function on the form node: 
The values are reset to "undefined" instead of the real "initial" values.

In the playground, you should first use the discard button. Then change the title field and reset it again (no complete reset). But the comparison will still say the form is dirty, because of the "undefined" situation.

When I saw it correctly the problem was the following line:

https://github.com/formkit/formkit/blob/8ee9d515f72ae7887622b11d9a5a6647cb3684f1/packages/core/src/reset.ts#L46

Here it's always going in the right part and this leads to undefined as the next value.

### Environment

-

**Comment by dominikklein** [comment]
My try to fix it already: https://github.com/formkit/formkit/pull/1510

**Comment by justin-schroeder** [comment]
Published in 1.6.8 — Thanks!
