### ISSUE TITLE
@formkit/utils eq has an error, cannot be set with context.node.input

### ISSUE THREAD

**Issue by aegorx** [formkit/formkit#151]
### Describe the feature

TypeError: Cannot convert undefined or null to object
in eq function
Suggest improvement.

**Comment by aegorx** [comment]
eq(null, [])

**Comment by justin-schroeder** [comment]
Please provide a reproduction, thanks

**Comment by aegorx** [comment]
@justin-schroeder 

Please look at the previous message.

**Comment by aegorx** [comment]
OK
