### ISSUE TITLE
FormKit Pro `togglebuttons` - type of `value` is incorrect

### ISSUE THREAD

**Issue by bearguns** [formkit/formkit#1513]
### Reproduction

https://formkit.link/9dea1a52a13e651a090aeb11253e565d

### Describe the bug

When using FormKit Pro with the `togglebuttons` input type, TypeScript fails to transpile and provides this error, both in-editor and when running `vue-tsc`:
``` 
Argument of type '{ type: "togglebuttons"; options: string[]; multiple: true; value: string[]; }' is not assignable to parameter of type '(FormKitInputs<{ type: "togglebuttons"; options: string[]; multiple: true; value: string[]; }> & VNodeProps) & AllowedComponentProps & ComponentCustomProps'.
      Types of property 'value' are incompatible.
        Type 'string[]' is not assignable to type 'boolean | undefined'. [2345]
```

Here is a basic example of the component usage, which produces the error:
```vue
<FormKit type="togglebuttons" :options="['1', '2', '3']" multiple :value="['1']"/>
```

This occurs whether or not `multiple` is `true` or `false`. This means that trying to use toggle buttons either with a `v-model`, or trying to pre-populate the component value on page load, either way we get this error.

### Environment

• OS: macOS/Linux
• Browser: Chrome, Safari, Firefox
• Version [e.g. 22]

**Comment by sashamilenkovic** [comment]
This has been resolved at @formkit/pro v0.127.3
