### ISSUE TITLE
Formkit mask not working within additional repeater items

### ISSUE THREAD

**Issue by TradeMark-2** [formkit/formkit#1516]
### Reproduction

https://formkit.com/playground?fkv=latest&fileTab=repeater-insert-control.vue&css-framework=genesis&imports=jc%28%27name%21%27ImportMap%27%7Elang%21%27json%27%7Eeditor%21%27%28*+1vue%5C%211https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fvue%403%2Fdist%2Fvue.esm-browser.min.js0*%29*%27%29*%5Cn0%5C%271+0%0110*_&files=jc%5B%28%27E%21%27W-B.vue%27%7Eedit_%21%27%3CO3Mgroup1%3AactiZsY1%23default2%28+valuR%298*4*3*id2no-modelqMWqCI5qhelp2Addjmany+i5jyou+want.q%3AB2U14T3TE2E7CPLsZ+thiD_dL+iDf_q%2F4T3TidJNumbL7innL-cxss2inputS7MG7EJ7CHomRphZe7pxceholdL2%7B000%7D-000-00007G2%7B6%7D-6-6%237show-GY7unG-value2U8%2F4*99XO%27%7Eadded%21U%29%5D*++18T2%3Dz3*%3CVQT4%3EQ5cRcream+_dLs6%23%23%2371T8zQ9*XV4BinsLt-cZtrolCxbel2Ds+EnameGmaskJ2homePhZeLerMtype2Otempxte4Q%5CnRe+T**UtrueVF_mKitWrepeatLX%3C%2FY2falseZon_orj+aDq1*xlaz%5C%27%01zxqj_ZYXWVUTRQOMLJGEDCB987654321*_

### Describe the bug

If there is a repeater input that uses a mask input, the mask only works on the initial item. 
Any additional items that get added, will/do not have a functional mask input.

I would expect all additional items to have a mask that works.

### Environment

• OS: Windows
• Browser: Chrome

**Comment by justin-schroeder** [comment]
this is due to the explicit `id`s used. Since those get repeated the same id is used and you cannot have duplicate ids. There really shouldnt be any need for an explicit id like that and formkit will generate a unique one for you, so the easiest fix is to just remove it:

https://formkit.link/9913a50cc71ff4aa020d1a2999e1eb1a
