### ISSUE TITLE
Unable to leave Datepicker component once focused in Safari

### ISSUE THREAD

**Issue by parsajabbari** [formkit/formkit#1519]
### Reproduction

https://formk.it/089fa0

### Describe the bug

We noticed that in Safari on macOS and at least in Safari and Chrome on iOS, once the Datepicker input is focused, you cannot exit out of it, whether by clicking/tapping outside of it or by tabbing. The linked example is just the standard FormKit playground for the Datepicker but with a single additional text field to demo how when you tab inside the Datepicker, once you get to the year, tabbing just takes you back to the month instead of going to the next field. It also doesn't seem to make a difference if you fill out the individual date fields inside of it or not.

The trick to get it to close is to open the picker popover and then click outside of the component to remove focus.

Our temporary workaround for customers has been to apply the `picker-only` prop for Safari users so they can't get trapped.

Demo:
https://github.com/user-attachments/assets/70669ad9-2954-4ece-8869-2914160ed8b9

### Environment

• OS: macOS and iOS
• Browser: Safari (macOS and iOS), Chrome (iOS)
• Version 18.0.1 (Safari), 129 (Chrome)

**Comment by bradjnewman** [comment]
➕ Thanks for adding this @parsajabbari

**Comment by sashamilenkovic** [comment]
@parsajabbari @bradjnewman This should be resolved at FormKit Pro v0.127.6

**Comment by parsajabbari** [comment]
Thanks Sasha! I am happy we get to delete our Plan B code now 😁
