### ISSUE TITLE
$reset does not work with generateClass

### ISSUE THREAD

**Issue by GustavoFenilli** [formkit/formkit#152]
### Reproduction

https://formkit.link/efa75600e9062b6e57ce0fd1e1dd3104

### Describe the bug

When using the new generateClasses from @formkit/tailwindcss the reset removes the bass classes but not the generated ones from global.

### Environment

• OS: [e.g. iOS] Ubuntu
• Browser [e.g. chrome, safari] Chrome
• Version [e.g. 22] @formkit/tailwindcss@next

**Comment by dominikklein** [comment]
I have also a problem with the "$reset" when I'm using it in a feature together with some global added classes (with "generateClasses").
Maybe I will find the time to add a playground, don't know if this is related.

**Comment by dominikklein** [comment]
Ah, my problem is working now, maybe it was another side-effect during the development.
