### ISSUE TITLE
Datepicker traps focus on safari

### ISSUE THREAD

**Issue by ArneMangelschots** [formkit/formkit#1522]
### Reproduction

https://formkit.link/8721768d9c7ddad388aadcf5dd3314d4

### Describe the bug

After selecting a date the datepicker is closed but the focus is trapped so you are not able to fill in any other fields.

### Environment

• OS: [e.g. iOS]
• Browser [safari]
• Version [e.g. 22]

**Comment by sashamilenkovic** [comment]
@ArneMangelschots Appreciate you filing the issue. I'm going to close this in favor of #1519.
