### ISSUE TITLE
Pro Dropdown Input w/ Multiple truncation message UI bug

### ISSUE THREAD

**Issue by yhtomitim** [formkit/formkit#1527]
### Reproduction

```https://formkit.com/playground?fkv=latest&fileTab=Playground.vue&css-framework=genesis&files=jc%5B%28%27name%21%27Playground.vue%27%7Eeditor%21%27%3Cscript+setup6const+8s+%3D+%5B9HNwuhdgSmShkGUymRR-rZVGJCIVQd*XkSADHqmGpaHXwGP-vMnaoMGbZECmu*dMOthZHR-RVBLzx*MkqRcdDOiXylaB-wyVCvyIyali*pqGYVOKtnZLmaQCLu-xmltEtxtu*CWeNJNhjHQpJxqqPHLm-QMvLdlZblgFBjB*nshLprsgsx-RrsTFZLrFb*hNwroWYNOlaspNxNDx-VbsfFGtbmnKj*ClExdqx-iEBVeXb*vPvWkangI-mDuuUCvJ4+%295%5D5%24script65%3Ctemplate60%3C%25+type7form4+%23default7%224+%3Aactions7false4600%3C%25_type7dropdown4_name7randomness4_label7Select+as+many+8s+as+you+would+like4_placeholder78+1%2C+2%2C+3+weee4_%3A8s78s4_multiple_popover500%2F600%3Cpre+wrap%3E%28%22%29%24pre60%24%256%24template6%27%7Eadded%21true%29%5D*4+%29%2C9-4%2C+4value%5C%21+40++4%5C%275%5Cn6%3E57%3D48option950%28+4label%5C%21+4_5000%22%28+value+%29%24%3C%2F%25FormKit%01%25%24%22_9876540-*_```
### Describe the bug

When selecting the first three options in order from top -> bottom in the playground, the truncation message will rapidly appear and disappear. While the data in the options is nonesense, the options passed are character length analogues to real values I'm using in our production application.

### Environment

• OS: MacOS Sequoia
• Browser Chrome
• Version 129.0.6668.100

**Comment by yhtomitim** [comment]
I can generate the playground link again easily if the provided one is dead.

**Comment by yhtomitim** [comment]
code used for playground:

```<script setup>
const options = [
  { "label": "iCjlNxyPQVbGAPQ", "value": "IBlUJRoIkT" },
  { "label": "eaOKqWAPqXtuuZujkEBR", "value": "gVbtWPAlINfQFnc" },
  { "label": "uCLtyDbgpfSN", "value": "ZVYnwGALNfsi" },
  { "label": "HNwuhdgSmShkGUymRR", "value": "rZVGJCIVQd" },
  { "label": "XkSADHqmGpaHXwGP", "value": "vMnaoMGbZECmu" },
  { "label": "dMOthZHR", "value": "RVBLzx" },
  { "label": "MkqRcdDOiXylaB", "value": "wyVCvyIyali" },
  { "label": "pqGYVOKtnZLmaQCLu", "value": "xmltEtxtu" },
  { "label": "CWeNJNhjHQpJxqqPHLm", "value": "QMvLdlZblgFBjB" },
  { "label": "nshLprsgsx", "value": "RrsTFZLrFb" },
  { "label": "hNwroWYNOlaspNxNDx", "value": "VbsfFGtbmnKj" },
  { "label": "ClExdqx", "value": "iEBVeXb" },
  { "label": "vPvWkangI", "value": "mDuuUCvJ" }
]
</script>

<template>
  <FormKit type="form" #default="{ value }" :actions="false">
    <FormKit
      type="dropdown"
      name="randomness"
      label="Select as many options as you would like"
      placeholder="option 1, 2, 3 weee"
      :options="options"
      multiple
      popover
    />
    <pre wrap>{{ value }}</pre>
  </FormKit>
</template>```

**Comment by sashamilenkovic** [comment]
@yhtomitim Closing in favor of #1488
