### ISSUE TITLE
Inputs with type=group cannot handle nulls

### ISSUE THREAD

**Issue by strokirk** [formkit/formkit#1528]
### Reproduction

https://formkit.link/ba1b9a1fc90f6f388ca4957b2d7abb07

### Describe the bug

When editing a nested form using `<FormKit type="group">`, formkit crashes if the form value for the group is `null`.

```
Uncaught (in promise) Error: Cannot set g2 to non object value: null
```

Is there any way to handle this gracefully, aside from inspecting and preparing the initial values?

Nested nullable objects are fairly common in backend responses, so it would be useful to have some sort of default handling of this pattern.

### Environment

Environment
• OS: MacOS Sequoia
• Browser Chrome
• Version 129.0.6668.101

**Comment by justin-schroeder** [comment]
You can use the input hook to prevent null values from reaching the input.

**Comment by strokirk** [comment]
If I understand correctly, this is done by adding a plugin, something like this:
```
<FormKit type="group" name="g2" :plugins="[(node) => {
  if (node.props.type !== 'group') return;
  node.hook.input((value, next) => next(value || {}));
}]">
```
