### ISSUE TITLE
Change default section html order for sibling selectors

### ISSUE THREAD

**Issue by mwohlan** [formkit/formkit#153]
### Describe the feature

Hey,

I am proposing a change to the default order of the html elements. Currently the elements are ordered like this:

```html
<div class="formkit-outer" data-type="text">
  <div class="formkit-wrapper">
    <label for="input_0" class="formkit-label">FormKit Input</label>
    <div class="formkit-inner">
      <input type="text" class="formkit-input" name="text_1" id="input_0" aria-describedby="help-input_0">
    </div>
  </div>
  <div id="help-input_0" class="formkit-help">edit me to get started</div>
</div>
```

Switching the order of the inner/input element with the label would enable the use of sibling selectors ([Tailwind Reference](https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-sibling-state)) to style the the label with Tailwind/Sibling Combinator based on the state of the input (focus, placeholder-shown etc.).

```html
<div class="formkit-outer" data-type="text">
  <div class="formkit-wrapper">
     <div class="formkit-inner">
          <input type="text" class="formkit-input" name="text_1" id="input_0" aria-describedby="help-input_0">
     </div>
     <label for="input_0" class="formkit-label">FormKit Input</label>
  </div>
  <div id="help-input_0" class="formkit-help">edit me to get started</div>
</div>
```

If this change doesn't cause any other side effects, it would be a win-win imo. Maybe the FormKit Team can look into this. Thanks for the great work btw.

**Comment by GustavoFenilli** [comment]
I thought the same, but that would come with a problem. The label would be rendered under the input without css.

**Comment by dominikklein** [comment]
I think there is some idea to make the order configurable, there was some chat in the discord (in VueFormulate is the same functionality available).

**Comment by GustavoFenilli** [comment]
> I think there is some idea to make the order configurable, there was some chat in the discord (in VueFormulate is the same functionality available).

That would be cool, but what about children elements? If they were all siblings would be easy, but they can be in any depth.

**Comment by justin-schroeder** [comment]
This will not be explicitly implemented beyond allowing users to modify the schema (see this example @mwohlan: https://formkit.link/81efab356e3c6459ee1501d5acb42d60) however I do think we'll add some optionality around where labels appear. Track this: https://github.com/formkit/formkit/issues/174
