### ISSUE TITLE
single-select Dropdown `selection-removable` does not work, `deselect` has to be used instead

### ISSUE THREAD

**Issue by antony-k1208** [formkit/formkit#1530]
### Reproduction

https://formkit.com/playground?fkv=latest&fileTab=dropdown-selection-removable.vue&css-framework=genesis&files=jc%5B%28%27n_%21%27M-B.vN%27%7Eeditq%21%27%3Cscripzsetup5consz6s+%3D+%5B9React1react2VN1vN2AnguXr1anguXr2SvYZ1svYZT0%5D08script50%3CLPG+jfqm3+%23default4%28DI3+%3AacQsU5*PG7jMWn_46WXbY4ChoosOa+fronZnd+6WH4ExamplOHW%3AopQs46sWvalN4vNWpopover7%3ABU0**%2F5*PprOwrap%3E%28%28DI%298pre5*8G58L0%3Cstyle%3E8style5%27%7Eadded%21trN%29%5D*++0%5Cn1%22%2CDJ2T93%5C%274%3D35%3E06fr_wqk70***8%3C%2F90*%28+XbYJBsYecQ-removableD+valNGFqmKitHpXceholderI+%29J%3A+%22LZmpXZ5MdropdownNueOe+P*%3CQtionT%22I%2CU4false3W37XlaYelZte_amejtype4qorzt+%01zqj_ZYXWUTQPONMLJIHGDB9876543210*_&imports=jc%28%27name%21%27ImportMap%27%7Elang%21%27json%27%7Eeditor%21%27%28*+1vue%5C%211https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fvue%403%2Fdist%2Fvue.esm-browser.min.js0*%29*%27%29*%5Cn0%5C%271+0%0110*_

### Describe the bug

The `selection-removable` option does not work as described in the docs and therefore expected.
Setting it to `false` still results in a deselection when clicking on the currently selected item in a single-select Dropdown.

With `deselect` everything works as expected: https://formkit.com/playground?fkv=latest&fileTab=dropdown-selection-removable.vue&css-framework=genesis&files=jc%5B%28%27nZ%21%27L-sWecP-removable.vM%27%7Eeditj%21%27%3Cscripqsetup5consq6s+%3D+%5B9React1react2VM1vM2AnguXr1anguXr2SvWY1svWYQ0%5D08script5zJOD+_fjm3+%23default4%28BH3+%3AacPsT5*OD7_LUnZ46UXbW4ChoosNa+fronYnd+6UG4ExamplNGU%3AopPs46sUvalM4vMUpopover7%3AdesWectT0**%2F5*OprNwrap%3E%28%28BH%298pre5*8D58Jzstyle%3E8style5%27%7Eadded%21trM%29%5D*++0%5Cn1%22%2CBI2Q93%5C%274%3D35%3E06frZwjk70***8%3C%2F90*%28+XbWIB+valMDFjmKitGpXceholderH+%29I%3A+%22JYmpXY5LdropdownMueNe+O*%3CPtionQ%22H%2CT4false3U37WelXlaYteZame_type4jorqt+z0%3C%01zqj_ZYXWUTQPONMLJIHGDB9876543210*_&imports=jc%28%27name%21%27ImportMap%27%7Elang%21%27json%27%7Eeditor%21%27%28*+1vue%5C%211https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fvue%403%2Fdist%2Fvue.esm-browser.min.js0*%29*%27%29*%5Cn0%5C%271+0%0110*_

Is this prop redundant or am I missing something?

### Environment

• OS: macOS 14.16.1
• Browser: Arc
• Version: 1.63.1

**Comment by sashamilenkovic** [comment]
@antony-k1208 `selection-removable` dictates whether or not to rendder the little close icon to the right of the actual text input field. `deselect` refers to whether or not your can actually "deselect" a selected option from the listbox. 

Completely understandable for it to be a bit confusing, but it is what it is for the time bieng.
