### ISSUE TITLE
Autocomplete - return value of the option loader dosen't change the selected option

### ISSUE THREAD

**Issue by tobiasharth** [formkit/formkit#1535]
### Reproduction

https://formkit.link/b1a7f714acc5c30e9910fb92b5122a51

### Describe the bug

I am using the "Option Loader" prop to hydrate the selected options in an autocomplete. However, the return from the Option Loader has no effect on the selected option. The expected behavior would be that the value in the example contains the imdb ID after selecting the option. 

### Environment

• OS: macOS 14.16.1
• Browser: Chrome
• Version: 129.0.6668.101

**Comment by sashamilenkovic** [comment]
@tobiasharth The id you are setting in your request is causing a 404. The id is an object literal. Additionally, the value you are assigning the option you are loading does not match the value you are assigning the component. Here is a working example: https://formkit.link/a78cc64f71a977f2f8e5b68a52e93bb4

**Comment by sashamilenkovic** [comment]
@tobiasharth The option loader is meant to take something like an ID as a value and be able to to actually fetch the option and its label that is associated with it. In the option-loader example, you see that we are assigning the autocomplete a value/id (597). To the end-user, this value is meaningless. The option loader allows us to look up that option by its ID and get the appropriate label along with it "Titanic". I hope that clear/helps.
