### ISSUE TITLE
Datepicker selected month/year doesn't recieve aria-selected="true"

### ISSUE THREAD

**Issue by lasseitorp** [formkit/formkit#1537]
### Reproduction

https://formkit.com/playground?fkv=latest&fileTab=Playground.vue&css-framework=genesis&files=jc%5B%28%27name%21%27Playground.vue%27%7Eeditor%21%27%3Cscrip4setup3impor4%28+ref+%29+from+8vue811cons4A%3D+ref%7B%7D115scriptB9D%3CFormKit*6v-model2d70type2d7picker0label2FormKi4Input0help2edi4mCto+ge4started0%3Asequence2%5B%22month%22%5D0clearable*%2F3*%3CpreD6%28%28+A%29%29*5pre359BstylCscoped35style3%27%7Eadded%21true%29%5D*1608*61%5Cn2%3D83%3E14t+5%3C%2F6++7ate8%5C%279templ7Ad7+B31%3CCe+D%3E*%01DCBA9876543210*_

### Describe the bug

1. Open the panel.
2. Focus is set on the current month.
3. Choose another month.
4. Open panel again.
5. Focus is set on the selected month.
6. Inspect the selected month
7. Verify that aria-selected="false", expected "true"
8. The same is true for the Year panel.

### Environment

• OS: MacOS 15.0.1
• Browser: Chrome
• Version: 130

**Comment by sashamilenkovic** [comment]
@lasseitorp This should be resolved at FormKit Pro v0.127.13
