### ISSUE TITLE
i18n: Thai (th) translation

### ISSUE THREAD

**Issue by Pessmccool1** [formkit/formkit#154]
I’ve completed the Thai language translation.

```ts
// Please copy and paste the file your just downloaded here
```

**Comment by justin-schroeder** [comment]
@Pessmccool1 looks like you are missing the actual translation here?

**Comment by justin-schroeder** [comment]
@Pessmccool1 would still love to get Thai in here — so feel free to re-open this, but it looks like maybe youve moved on now.
