### ISSUE TITLE
Date Picker won't render resetted value

### ISSUE THREAD

**Issue by DEPT-ch** [formkit/formkit#1542]
### Reproduction

https://formkit.link/ed163c8d2dd0a779c02d1dc2c6f70b6d

### Describe the bug

When "resetting" a datepicker's model value to "", the date picker will continue to show the last set value.

### Environment

• OS: every OS
• Browser every browser
• Formkit Version: 0.127.5 (pro)

**Comment by justin-schroeder** [comment]
the correct reset value is `undefined`. In formkit we consider all values to be values (even null) except for `undefined`.
