### ISSUE TITLE
Focus is trapped in Datepicker field

### ISSUE THREAD

**Issue by betabong** [formkit/formkit#1543]
### Reproduction

https://formkit.link/c1178f7abb660a88b9f5857c5a763908

### Describe the bug

Navigating into the date picker field on Safari will keep the focus trapped within the field. I have found no way to escape it – apart from reloading the page. 

This is a severe bug, I sincerely hope for quick fix.

### Environment

• OS: Mac OS 14.6.1
• Browser Safari 
• Version 17.6

**Comment by justin-schroeder** [comment]
@betabong we are looking into it now

**Comment by sashamilenkovic** [comment]
@betabong This should be resolved at FormKit Pro v0.127.6

**Comment by DEPT-ch** [comment]
Fantastic, thanks for the quick fix!
