### ISSUE TITLE
@formkit/pro uses @formkit/utils but does not declare it as dependency

### ISSUE THREAD

**Issue by RomainLanz** [formkit/formkit#1549]
### Reproduction

None

### Describe the bug

Hey there!

I've noticed that the `@formkit/pro` package has an internal reference to `@formkit/utils`:

```ts
import {isRecord as e,isObject as t,isPojo as o,eq as n,undefine as r,whenAvailable as s,clone as a} from "@formkit/utils"
```

However, `@formkit/utils` isn't listed as a dependency in the `package.json` file, which causes issues in strict dependency managers like `pnpm` or Yarn. When using these package managers in strict mode, the missing dependency leads to build errors.

```json
{
  "name": "@formkit/pro",
  "version": "0.127.6",
  "dependencies": {
    "@formkit/drag-and-drop": "^0.0.38",
    "@formkit/tempo": "^0.1.1"
  },
  "peerDependencies": {
    "@formkit/core": "^1.6.5",
    "@formkit/inputs": "^1.6.5"
  }
}
```

To fix this, adding `@formkit/utils` as a dependency in `package.json` should resolve the issue.

### Environment

Not needed

**Comment by sashamilenkovic** [comment]
@RomainLanz This should be resolved at @formkit/pro v0.127.7.
