### ISSUE TITLE
togglebuttons remain disabled when parent changes to enabled

### ISSUE THREAD

**Issue by RemyAlbanes** [formkit/formkit#1554]
### Reproduction

https://formkit.com/playground?fkv=latest&fileTab=Playground.vue&css-framework=genesis&files=jc%5B%28%27name%21%27Playground.vue%27%7EzitQ%21%27UcripVsetup8impQV%28+ref*%29+from+%22vue%22LconsVOref%7Bfalse%7DL9script85%3CS*%3Cb%3EErrQ+enM+TRBHs9bj%3CbH+%40clickGOq%3ETR+disM9bHjNfQmW%3AdisMGqj*NtextWplaceholderGClassic+InputW%2Fj*%3CJ_XGtRbHs6_nameGX6_enfQcz_%3AoptionsG%5B1%2C2%2C3%2C4%5D65D**%2Fj**Upan%3EThese+bHs+will+never+reactivate...9spanj9J89S5Utyle+scopz8bH%285*display%3AblockL*background-Z%2317243fL*marginY+0L*paddingYL*Zwhite5%2959style8%27%7Eaddz%21true%29%5D*++5%5Cn6%5C%278%3E59%3C%2FAenMFQmD***G%3D6HuttonJFQmKitL%3B5MablzN%3CJ+XGOA+%3D+QorRoggleStemplate8U%3CsVt+W6+XtypeY%3A10pxZcolQ%3A_5DDj8Dq%27%3AA6zed%01zqj_ZYXWVUSRQONMLJHGDA9865*_

### Describe the bug

When my form or group pass is 'disabled' at default, et i toggle it, my togglebuttons elements remain disabled 

### Environment

• OS: Window 11
• Browser Chrome
• Version latest
• Vuejs 3 
• Nuxtjs 3 
• Nuxtkit pro

**Comment by sashamilenkovic** [comment]
@RemyAlbanes This is resolved at FormKit Pro v0.127.11
