### ISSUE TITLE
"null" as Form Element Value throws Uncaught Exception

### ISSUE THREAD

**Issue by marfnk** [formkit/formkit#156]
When working with my API which returns `null` for empty attributes of entities by default, I found this error.
In my opinion, `null` is a valid value for _empty or unset properties_ and should work just like `undefined`.

**Steps to reproduce**
https://formkit.link/fa65f181201faa3bfa7cbf8acb79228d
- create a FormKit-form with a `v-model`-reference to an object with properties
- add text inputs for those properties
- set any of the model properties to `null`
- compile

**Expected**
- empty text inputs for all `null`, `""` or `undefined` model properties
- working form

**Actual** 
- Uncaught error
- view does not render
Error thrown is:
```
Uncaught (in promise) TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (<anonymous>)
```

**Environment**
Desktop (please complete the following information):

OS: Mac 11.2.3
Browser: Chrome 99.0.4844.51

**Comment by aegorx** [comment]
@marfnk 

#151  This issue has been fixed and will work in the next version.

**Comment by marfnk** [comment]
Awesome, thanks for the update.
Didn't match #151 to my issue when reading it.

**Comment by justin-schroeder** [comment]
Thanks for spending the time on a quality reproduction @marfnk. You should be able to installed the fix if you install the @next tag from npm. I'll close this in favor of #151.
