### ISSUE TITLE
Enter in `currency`-field won't trigger submit in form

### ISSUE THREAD

**Issue by OlaAlsaker** [formkit/formkit#1563]
### Reproduction

https://formkit.link/39ea8cd696914708464d880b27bda138

### Describe the bug

If you are inside of a `currency`-field and press `Enter` on your keyboard, it won't trigger `@submit` on the parent form. Check reproduction for example.

### Environment

• OS: macOS
• Browser Chrome
• Version FormKit 1.6.9 (Pro 0.127.8)

**Comment by sashamilenkovic** [comment]
@OlaAlsaker Appreciate you pointing this out. This has been resolved at FormKit Pro v0.127.9
