### ISSUE TITLE
Autocomplete dropdown focuses on disabled item

### ISSUE THREAD

**Issue by F4eNn** [formkit/formkit#1566]
### Reproduction

https://formkit.link/46f713b17ed9a63540c20e0dcf0025d1

### Description:

When the first item in the autocomplete dropdown array is set to disabled, the dropdown still focuses on this item when opened. This behavior seems counterintuitive, as the dropdown should skip disabled items and target the next available (non-disabled) item instead.

### Expected Behavior:
The autocomplete dropdown should automatically focus on the first non-disabled item when opened.

### Actual Behavior:
The autocomplete dropdown incorrectly focuses on the disabled item, requiring manual navigation to reach an active option.

### Steps to Reproduce:

1 .Populate an autocomplete dropdown array.
2 .Set the first item in the array to disabled.
3 .Open the autocomplete dropdown.

### Environment

• Linux: [e.g. Ubuntu]
• Browser [e.g. chrome, brave]
• Version [e.g. 22]

**Comment by sashamilenkovic** [comment]
@F4eNn This should be resolved at FormKit Pro v0.127.10
