### ISSUE TITLE
Reverse mask input doesn't display initial value from schema

### ISSUE THREAD

**Issue by m4riachi** [formkit/formkit#1571]
### Reproduction

https://formkit.link/062e5c5b6996f068cad424c1cda12949

### Description
When using FormKit's schema to generate a price mask input with a reverse attribute and initial value, the value is not displayed in the input field. However, the same schema structure works correctly for other input types (e.g., text inputs).

### Expected Behavior
- The price mask input should display the initial value set in the schema
- The value should be properly formatted according to the price mask rules

### Actual Behavior
- The price mask input remains empty despite having an initial value set
- Other input types (like text) display their initial values correctly

Thank you

### Environment

• OS: Ubuntu 24.04
• Browser: Google Chrome Version 131.0.6778.108 (Official Build) (64-bit)
• Version: 1.16

**Comment by justin-schroeder** [comment]
I would highly recommend using the currency input instead of the mask for currency based inputs.

**Comment by m4riachi** [comment]
Thank you
