### ISSUE TITLE
Schema not work with kebabCase key

### ISSUE THREAD

**Issue by aegorx** [formkit/formkit#161]
### Reproduction

https://formkit.link/e8cee4506dae46999f13b811204b1248

### Describe the bug

Schema not work with kebabCase key.

### Environment

• OS: WIN10
• Browser: chrome
• Version next.7

**Comment by justin-schroeder** [comment]
No schema does not support `kebab-case` variables (similar to javascript) — they should be provided as `camelCase` only. For performance reasons I’m not sure its worth the transform cost when devs can provide them the formatted way.

Is there a common use case youve found where defining kebab-case properties is really helpful?

**Comment by aegorx** [comment]
@justin-schroeder 

The custom attribute data-* is an HTML specification. Sections schema should be used in combination with the value of attrs.

**Comment by justin-schroeder** [comment]
Just like in JavaScript our compiler cannot accept `-` in variable names. For this reason, I would recommend converting any `kebab-case` variables to `camelCase` — you can even use a utility provided in `@formkit/utils` to do so:

https://formkit.link/1de8ff9de07887f1e3e940349c8480ea
