### ISSUE TITLE
Changes to input label is not observed by validation messages

### ISSUE THREAD

**Issue by dajpes** [formkit/formkit#170]
### Reproduction

https://stackblitz.com/edit/vitejs-vite-a1jffs?file=src/components/HelloWorld.vue

### Describe the bug

Hey all!

The bug happens when you are working with an external internationalization library like [vue I18n](https://vue-i18n.intlify.dev/). 

When my FormKit component uses a dynamic label (that changes when you change the language), and then you have an error in your input, the error message doesn't show your current label value, but the previous one.

The StackBlitz repo show the error (if the repo doesn't run, try running npm run install & npm run dev until it shows something on the screen)

### Environment

• OS: [Linux Mint]
• Browser [chrome]
• Version [Beta 6]

**Comment by justin-schroeder** [comment]
Thanks @dajpes I was able to reproduce this without any i18n involved, so definitely something we'll look to fix.

Additional reproduction: https://formkit.link/102672993422b032053801a464681570

**Comment by receptopalak** [comment]
Hello, error persists. Can you help me?

**Comment by justin-schroeder** [comment]
@receptopalak its provably working, so you'll need to open a new issue with a full reproduction using beta.8 or later.
