### ISSUE TITLE
[Feature Request] Add `trim` argument to validation rule

### ISSUE THREAD

**Issue by prescience-data** [formkit/formkit#171]
### Describe the feature

The `required` rule validates as success if the user enters whitespace in a `text` input. 

It would be great to have a built-in `required|trim` _(or `trimmed`)_ rule to ensure it fails on spaces.

**Comment by justin-schroeder** [comment]
I think we could add this feature pretty easily with an argument on the required rule:

```
<FormKit validation="required:trim" />
```

We'll mark this for Beta 7, thanks for the suggestion 👍
