### ISSUE TITLE
Dynamically setting validation prop has an error

### ISSUE THREAD

**Issue by aegorx** [formkit/formkit#172]
### Reproduction

https://formkit.link/4ad4c15e4e20c749a1e5facdadd7c6a3

### Describe the bug

bug 1:
click changeArr print:
index.mjs:298 Uncaught (in promise) TypeError: args.shift is not a function.

bug 2:
If the focus is lost once and there is no value in the input box, the dynamic setting will be triggered immediately.

### Environment

• OS: WIN10
• Browser chrome 99
• Version next.7

**Comment by justin-schroeder** [comment]
`['required']` is not a valid validation prop validation rules are either pipe-delimited strings, or an array of _arrays_ so:

```
:validation="[ // notice wrapping array
 ['required']
]"
```

Here's the playground with a wrapping array: https://formkit.link/d75fbdf3a7742c3c5657a885fe18841c

Good luck 👍

**Comment by aegorx** [comment]
@justin-schroeder 

THX. Can you help me with the second question?

**Comment by justin-schroeder** [comment]
The state of the input at this point is considered "blurred" so it automatically considers the validation rules visible. If you want to "reset" the blurred state, you can remove the `blurred` message from the core node at any time:

https://formkit.link/4d218721deb4b62732726d76a3c45e69
