### ISSUE TITLE
Allow schema sections to be moved

### ISSUE THREAD

**Issue by titusdecali** [formkit/formkit#174]
### Describe the feature

Similar to Vuetify's default inline-label option, I'd like to be able to easily add labels which replace the need for placeholders and also serve an aestethic purpose. I'm currently replacing a Vuetify project (yuk) with custom styling + FormKit, but have found the above to be a useful feature for this project that I miss.

While I understand FormKit wanting to leave most styling options to the user, in this case it's a hurdle that would be easier to add internally.

Here's a codepen to display the styling I want to accomplish, and why it doesn't work in FormKit out of the box.
https://codepen.io/TitusDecali/pen/QWagGJj?editors=1100

Due to the `formkit-inner` wrapper, the CSS cannot properly target the `:focus` state.

I do understand that this can be removed with

```
 :sections-schema="{
    inner: { $el: null }
 }"
```

However that then removes a ton of wanted styling for borders, focus states, error highlighting, etc.

As this requires quite significant modification to achieve (as well as adding the above code to every input), and the time required for each person to figure out how to properly achieve this look, I would like to suggest an `inline-label` prop be available that gives us this functionality out of the box, automatically removes placeholders, and give us a class to target the label when in these given states to allow for font-size adjustment depending on if it is in a focused state or not (if needed).

As always, thanks for this great library!

**Comment by justin-schroeder** [comment]
@titusdecali we might need to dip our toes into more style related features eventually. We chose to go with "absurd levels of flexibility" in FormKit core to start with so even if the DX isnt perfect initially we can solve almost any form related challenges.

Here's an example of floating labels I just worked up as an example. It uses a global plugin to move the label from the outer to the suffix location, and then does some basic focus styling (it is not a complete example, yet, doesnt maintain styling when the input has a value etc)

https://formkit.link/18d36fc7a241e66c45feec51330c9f98

**Comment by justin-schroeder** [comment]
Dang it — I got sucked into this — been having too much fun. Here's a more fleshed out example:

https://formkit.link/81efab356e3c6459ee1501d5acb42d60

**Comment by titusdecali** [comment]
@justin-schroeder You never cease to amaze me brother!

As your example suggests, FormKit, its team, and you my friend, are indeed the best! A million thanks!

**Comment by titusdecali** [comment]
You've inspired me. I'm now a monthly sponsor of FormKit.

**Comment by justin-schroeder** [comment]
Thanks @titusdecali! I appreciate the kind words and the sponsorship ❤️

So the `formkit.config.js` is automatically used if you are using the Nuxt module, but all it really does is give you a place to add your configuration. You can do the same thing in your own `main.js` (wherever you boot the vue app). While youre at it you might as well isolate that plugin. Here's a proposed structure:

```
./moveLabelPlugin.js
./main.js
./App.vue
```

```
// main.js
import { createApp } from 'vue'
import App from './App.vue'
import { plugin, defaultConfig } from '@formkit/vue'
import moveLabelPlugin from './moveLabelPlugin.js'

const app = createApp(App)

// Define your FormKit global config/plugins here:
app.use(plugin, defaultConfig({
  plugins: [moveLabelPlugin]
})
app.mount('#app')
```

Good luck! 👍

**Comment by pjmanning** [comment]
@justin-schroeder thanks so much for that plugin! I had the same issue trying to replicate a material design-y input and was able to hack it thanks to your help.

Would love a prop as requested - as I was using tailwinds `peer` utility to handle all the css and transitions for the same input but it became much more hacky with FormKit.  Seems the tailwind `peer` classes weren't working as expected when adding them in my `assets/css/index.css` where tailwind is loaded. 

I'm also using a theme.js file as suggested for a config with tailwind where I added most of the tailwindcss but getting a bit bloated.

**Comment by pjmanning** [comment]
Lol for sure ... I meant more on files and logic in many places... 

`./formkit.config.js` - to move the labels
`./theme.js` - to add the base custom styles (i guess this is optional but probably helpful long-term)
`assets/css/index.css` custom styles to handle the label transition

Just painful moving from a simple `BaseInput.vue` 😢 (without simple validation of course ;)

**Comment by titusdecali** [comment]
@justin-schroeder I've followed as you instructed above, but am getting the following. FYI I'm using Vue3 CLI without Nuxt or Vite.

![image](https://user-images.githubusercontent.com/4532534/160953775-e18fabae-b820-4a61-a01b-11c6051ff3d1.jpeg)

**Comment by justin-schroeder** [comment]
Based on that stacktrace I think the plugin must not be exported/imported correctly. Assuming you put the plugin in `./moveLabelPlugin.js`, it should look like:


```js
// moveLabelPlugin.js
import { clone } from '@formkit/vue'

export default function moveLabelPlugin (node) {
  node.on('created', () => {
    const inputDefinition = clone(node.props.definition)
    if (['radio', 'checkbox', 'select'].includes(node.props.type)) return
    const originalSchema = inputDefinition.schema
    const higherOrderSchema = (extensions) => {
      // This kills the original label
      extensions.label = { $el: null, children: null }
      extensions.suffix = {
        $el: 'label',
        children: '$label',
        attrs: {
          'data-has-value': '$_value !== "" && $_value !== undefined',
          class: '$classes.floating',
          for: '$id'
        }
      }
      return originalSchema(extensions)
    }
    
    inputDefinition.schema = higherOrderSchema
    node.props.definition = inputDefinition
  })
}


```

**Comment by titusdecali** [comment]
Der, my boneheaded mistake. It's working as expected now. Thanks again!

**Comment by pjmanning** [comment]
> @pjmanning definitely looking to remove pain not add it. What suggestions do you have for how to simplify this? If there was a "floating labels" off the shelf plugin that included a best-guess at styles would you prefer something like that?

@justin-schroeder you guys are definitely taking all the pain out of validation! Thank you 🙏🏼

I think in my head the cleanest way for dev experience would be to have something like a `label-position` prop which would then allow for styling on the component itself.  With adding the plugin and then adding the CSS to the main tailwind css file I start to lose flexibility with the inputs.

**Comment by justin-schroeder** [comment]
Exporting inputs has deprecated the need for this feature, so im closing it. If you want to move sections around, simply export your input, move the sections in schema a to your liking and re-import it into your config.
