### ISSUE TITLE
Custom Classes not working

### ISSUE THREAD

**Issue by nefejames** [formkit/formkit#176]
Hi. I tried setting up custom classes, but it's not working.

The class gets added to the element, but the styles don't get applied or show up in the CSS dev tools.

I thought that the Genesis theme may be the reason, but I removed that and it didn't work.

In your [Alpha Update Theming Video](https://www.youtube.com/watch?v=kkL4CRU6Pak), it worked.

Am I missing something?

FormKit Vue Playground link:
https://formkit.link/75ae5e338e0d1ede1dbaaeeb013b3d9c

**Comment by justin-schroeder** [comment]
@nefejames this is just because your style block is scoped and you are trying to apply properties of a nested component. You can just remove the `scoped` attribute: https://formkit.link/1f239413442639d083ab959887c96288

or use vue's deep selectors.
