### ISSUE TITLE
[Feature Request] Add `data-{state}` attributes to `formkit-outer` div

### ISSUE THREAD

**Issue by prescience-data** [formkit/formkit#178]
### Describe the feature

Currently the `formkit-outer` div automatically applies `data-invalid` and `data-complete` attributes based on state which are really useful for creating css overrides of the base theme. 

However, (unless I'm mistaken) there doesn't appear to be a way to access the `dirty` or `blurred` state by css selectors alone when using the `$formkit: "text"` default inputs.

It would be great to get these additional states propagating to the `outer` container the same way that `invalid` and `complete` do. 

For additional context / use case - this is an issue when passing a schema directly to a Form:

```typescript

export const useTeamProfileForm = (): FormKitInstance => ({
    id: TEAM_PROFILE_FORM,
    schema: reactive([
      {
        $formkit: "text",
        name: "name",
        label: "Team name",
        placeholder: "Team name...",
        autocomplete: "organization-title",
        validation: "required|length:1,255",
        validationVisibility: "dirty"
      },
    ...useRefs()
  })

```

```vue

<script setup lang="ts">

// ....

const loader: Loader = useLoader()

const { schema, form, isValid, isDirty, id } = useTeamProfileForm()

const initialValues = toTeamProfile(profile.value)
const data = toTeamProfile(profile.value)

const canSubmit: ComputedRef<boolean> = computed(
  () => isValid.value && isDirty.value && !loader.isLoading
)

// ....

</script>

<template> 

// ...
          <FormKit
            :id="id"
            ref="form"
            v-model="data"
            type="form"
            :actions="false"
            @submit="onSubmit"
          >
            <FormKitSchema :schema="schema" />
          </FormKit>

</template>
```

**Comment by GustavoFenilli** [comment]
I think you can do it using a plugin like so:
```js
const additionalDataPlugin = (node: any) => {
  const definition = clone(node.props.definition);
  const originalSchema = definition.schema;

  node.props.definition.schema = (extensions: any) => {
    const localExtensions = {
      ...extensions,
      outer: {
        attrs: {
          'data-blurred':  '$node.context.blurred',
          'data-dirty':  '$node.context.dirty'
        }
      }
    };

    return originalSchema(localExtensions);
  };
};
```

**Comment by prescience-data** [comment]
Hmm I've just tried a few variations of this, and does not seem to do anything:

```typescript
    {
        $formkit: "text",
        name: "name",
        label: "Team name", 
        validation: "required|length:1,255",
        validationVisibility: "dirty",
        classes: {
          outer: {
            "is-dirty": "$node.context.state.dirty"
          }
        },
    }
```

**Comment by justin-schroeder** [comment]
@prescience-data The `classes` prop is not schema-enabled, although that could be a cool feature potentially. You can however modify your schema attributes by using the `sections-schema` prop, or as @GustavoFenilli pointed out a global plugin to do this would be fairly easy to setup too. Here's an example:

https://formkit.link/842bd68294148c148dabb713fdd72073

**Comment by prescience-data** [comment]
Global plugin works - My feeling is that if "some" (ie `data-complete`, `data-invalid`) are emitted to the data attributes, it makes sense that developers might expect all states to be emitted, however more than happy with the global plugin solution if there is a specific design decision that's been made around this previously. ❤️
