### ISSUE TITLE
[Feature Idea] [Vue 3] Form ref composable

### ISSUE THREAD

**Issue by prescience-data** [formkit/formkit#180]
### Describe the feature

Disclaimer: Not sure if this is something more specific to my personal use case or if others might find it convenient as well.

After playing around with FormKit for about a week now I've found that I ended up generating a common set of refs for every form, so abstracted the generator to a composable.

Still very early days getting used to the overall patterns of FormKit, but though it might be worth suggesting to see if others have a better pattern or implement something similar frequently that might be useful providing as part of the `vue` package?

```typescript

export const useFormKitRefs = (): FormKitRefs => {
  const form: FormRef = ref()

  const context: ComputedRef<FormKitFrameworkContext | undefined> = computed(
    () => form.value?.node.context
  )

  const state: ComputedRef<FormKitState | undefined> = computed(
    () => context.value?.state
  )

  const isValid: ComputedRef<boolean> = computed(() => !!state.value?.valid)

  const isDirty: ComputedRef<boolean> = computed(() => !!state.value?.dirty)

  const isComplete: ComputedRef<boolean> = computed(
    () => !!state.value?.complete
  )

  return {
    form,
    context,
    state,
    isDirty,
    isValid,
    isComplete
  }
}

```

```vue
<script setup lang="ts">
const { form, isDirty, isValid } = useFormKitRefs()

const data: AccountProfile = reactive({
   firstName: "",
   lastName: "",
   // ...
})

const onSubmit = async (data: AccountProfile) => {
  // ....
}
</script>

<template>
<div>
    <FormHeader>
      <template #text>
        <h3>Account Profile</h3>
      </template>
      <template #buttons>
        <V-Button :disabled="isDirty" @click="onReset">
          Reset
        </V-Button>
        <V-Button :disabled="!isValid" @click="onSubmit">
          Submt
        </V-Button>
      </template>
    </FormHeader>
    <FormBody> 

        <FormKit
          :id="id"
          ref="form"
          v-model="data"
          type="form"
          :actions="false"
          @submit="onSubmit"
        >
          <FormKitSchema :schema="schema" />
        </FormKit>

    </FormBody> 
</div>
</template>
```

**Comment by justin-schroeder** [comment]
I like the idea of something like `useInputContext(id)` as syntactic sugar for `toRefs(getNode(id).context)`. Beyond that we would just be picking and choosing features to include since all of them are in the context object, but this would allow users to quicky grab the data they want:

```html
<script>
const { state: { valid }, value } = useInputContext('form')
</script>
```

**Comment by prescience-data** [comment]
> _since all of them are in the context object_

Ah yes, this is much better (the second-order destructuring) given they are all full `ref` objects and won't lose reactivity. I'd gotten so used to dealing with objects wrapped in `reactive` breaking I didn't even think of this. 👌
