### ISSUE TITLE
Dependencies are missing when installing with pnpm

### ISSUE THREAD

**Issue by aegorx** [formkit/formkit#185]
### Reproduction

-

### Describe the bug

      "@formkit/inputs": {
        "dependencies": {
          "@formkit/utils": "*"
        }
      },
      "@formkit/validation": {
        "dependencies": {
          "@formkit/utils": "*"
        }
      }

### Environment

• OS: WIN10
• Browser chrome 99
• Version .7

**Comment by justin-schroeder** [comment]
I cannot duplicate this. I was able to setup a new vite project with pnpm and do `pnpm add @formkit/vue` — all dependencies were added properly.
