### ISSUE TITLE
[Feature Request] Add prop `read-only` state

### ISSUE THREAD

**Issue by titusdecali** [formkit/formkit#187]
### Describe the feature

Correct me if I'm wrong, but I didn't see support in the docs for a `read-only` prop that will pass it down to the inner input.

This seems like a minor update that would help to better support base HTML input features.

We have `disabled` support, but there are cases where you want to display normal styles while preventing input.

**Comment by andrew-boyd** [comment]
Anything that you put on the outer `FormKit` component will pass down to the input element if it's not a special prop that FormKit intercepts. 

https://formkit.link/20fcbe489a0d8e1ac8b7dc85008259f8

**Comment by titusdecali** [comment]
Ha, thanks. I was using `read-only` instead of `readonly` and thinking it just wasn't picking it up. Closing issue.
