### ISSUE TITLE
Export functions from input features

### ISSUE THREAD

**Issue by burgalon** [formkit/formkit#188]
### Describe the feature

We're using [MDB Bootstrap Vue](https://mdbootstrap.com/docs/standard/forms/input-fields/) for our project and would like to incorporate FormKit.
In order to use the MDB components but use FormKit state I'm extending the components. Specifically I would like to to re-use the `features` directory and avoid duplicating code as much as possible, however it does not seem possible to import the `features` as FormKit is published without source code.

Maybe we can switch to publishing the package as raw source instead ?

Example:
```
forms/index.ts
export const checkbox = {
    features: [formatLabel, formatsOptions, checkboxes],
    type: "input",
    props: ["options", "onValue", "offValue"],
    component: MFCheckbox,
};


// forms/MFCheckbox.vue
<script setup>
import { map, xor } from "lodash";
import { computed } from "vue";

const props = defineProps({
    context: Object,
});

function handleInput(e) {
    const currentValue = props.context.node.value;
    const value = xor(currentValue || [], [e.target.value]);
    props.context.node.input(value);
}

const messagesStr = computed(() => map(props.context.messages, "value").join("\n"));
</script>

<template>
    <fieldset :class="{ 'checkbox-fieldset': true }">
        <legend>{{ context.label }}</legend>
        <div v-if="context.help" class="form-text mb-3">{{ context.help }}</div>
        <div class="options">
            <div v-for="option in props.context.options">
                <MDBCheckbox
                    :id="option.attrs?.id"
                    :label="option.label"
                    :value="option.value"
                    :model-value="props.context.fns.isChecked(option.value)"
                    :name="context.name"
                    :is-valid="!messagesStr"
                    v-bind="option.$attrs"
                    :disabled="option.disabled || context.disabled"
                    :aid="option.aid"
                    @change="handleInput"
                />
                <label :for="option.attrs?.id" v-if="option.help" class="form-text ms-4">{{ option.help }}</label>
            </div>
        </div>
    </fieldset>
</template>

```

--- as a side note
What do you think about decoupling the components from the state management for the form more similarly to https://react-hook-form.com/ ?

**Comment by justin-schroeder** [comment]
Lots of questions in here @burgalon, and happy to answer them. Although, you might get a higher bandwidth asking some of these in a conversational format on Discord (https://discord.gg/Vhu97pAC76)

In general publishing source code to NPM is frowned upon (by us included) as it tends to bloat the node_modules directory of all users even further — but the good news is that ESMs largely solve this for us by allowing us to export whatever functions/features you want in the rolled up ESM. You are correct that we dont currently export the functions in the `features` directory, but that can absolutely be done.

There are so many ways to "wrap" third party libraries that we dont currently have a published canonical way of doing it, but what you have there seems to be just fine.

As for decoupling components and state management — good news — it is decoupled :) In fact you can use FormKit with native javascript + html and no vue at all if you want (we call this "headless" FormKit, and will publish more on it in the future). Ultimately all that is necessary to map input state to formkit is calling `node.input()` and then reading the `node.value` back out to html. This is why core nodes have their own event system, middleware (hooks), and data store.

That said, the Vue plugin (`@formkit/vue`) is easily the best path forward for 99.9% of Vue users, but if you need more horsepower — it is there for you.

-----

I'll change this issue title to represent the current ask which is exporting the `features` functions.

Good luck 👍

**Comment by justin-schroeder** [comment]
@burgalon Good news — just published the `@next` branch and it includes all the input features. You should be able to just do:

```
import { features } from '@formkit/inputs`
```

**Comment by burgalon** [comment]
thank you @justin-schroeder for the exports and quick response
