### ISSUE TITLE
Get all invalid inputs

### ISSUE THREAD

**Issue by lavolpecheprogramma** [formkit/formkit#189]
### Describe the feature

Hi, i haven't find a way to get all input that have state.valid === false in a smart way.
Is there a way to achieve it?

The use case is to set to the tab that contains this field an error state.

Thank you very much!

**Comment by justin-schroeder** [comment]
We'll be publishing some documentation with recommendations for how to handle these kinds of multi-step form validations. Will post here when that goes out.

**Comment by andrew-boyd** [comment]
The guide for creating a multi-step form has been published! https://formkit.com/guides/build-a-multi-step-form
