### ISSUE TITLE
Genesis theme missing disabled styling of submit button, when form is disabled

### ISSUE THREAD

**Issue by tosling** [formkit/formkit#195]
### Reproduction

https://formkit.link/8bd10fbde2f098dab9bfb83b673c8f94

### Describe the bug

When reading through the docs, I found that a [disabled form](https://formkit.com/essentials/forms#disabling) `<FormKit type="form" disabled>` is still showing a blue button, with a pointer cursor. Technically the button is disabled, so it's really a minor.

**Expected:**
I suggest the button should appear disabled, probably greyed out as in https://formkit.com/essentials/forms#validity-state

### Environment

• OS: MacOS
• Browser: Chrome
• Version: 100

**Comment by tosling** [comment]
Just figured out, that using using an explicit `<FormKit type="form" :disabled="true">` or `<FormKit type="form" disabled="anystring">` shows a grey button.

https://formkit.link/77dfb935f1eade1b2d53f99ea1788386

Maybe it's sufficient, to change the documentation.

**Comment by andrew-boyd** [comment]
Thanks for the report! This is indeed a bug, I think it should work with `disabled` without requiring `disabled="true"`. Looks like it's some sort of gap in our detection specifically for the form actions generated by FormKit.
