### ISSUE TITLE
autofocus on input[text]

### ISSUE THREAD

**Issue by NgaNguyenDuy** [formkit/formkit#199]
Hi, I would to use useFocus() from vueuse [1] to autofocus on input at the first page loading.
I need to specific a ref to input tag, is there a way to do that?

[1]. https://vueuse.org/core/usefocus/

**Comment by andrew-boyd** [comment]
Hey @NgaNguyenDuy, Here's a playground that illustrates how to get a `ref` that points to an internal `input` element inside of a FormKit component. 

https://formkit.link/badd56bf305e088ee5a2f232df4d107c

Should be a little simpler in your own code as I'm doing some gymnastics here to get it working in the Playground editor.

**Comment by andrew-boyd** [comment]
also, Justin and I discussed while looking at this one and are opening #200 to make accessing `refs` on FormKit internals easier moving forward.

**Comment by NgaNguyenDuy** [comment]
Thank @andrew-boyd.
