### ISSUE TITLE
Add a way to remove field errors

### ISSUE THREAD

**Issue by krazzer** [formkit/formkit#210]
### Describe the feature

When setting an error for a specific field using `node.setErrors`, I cannot remove this error later. 

I could set the specific field to have error `''`, but then still space is taken up to show the error. And it's also quite tedious to have to unset every specific field error.

`node.setErrors([], {});` doesn't remove existing field errors. It would be nice if it did. Or add a function like `node.resetErrors()`

**Comment by justin-schroeder** [comment]
@krazzer resetting should be easier — I agree. I'll mark this as a feature for future inclusion. That said, it is possible to remove errors using setErrors, can you provide an example in the playground of how you're trying to do it? I might be able to help solve your immediate problem

**Comment by krazzer** [comment]
@justin-schroeder thanks! I fixed it for myself now by using the `:errors` attribute for fields, and `setErrors` only for form errors.

**Comment by justin-schroeder** [comment]
Issue #277 addresses some of these concerns. Closing till we have a more specific issue.
