### ISSUE TITLE
Add ability to add rootClasses to Form errors

### ISSUE THREAD

**Issue by wernerbihl** [formkit/formkit#213]
### Describe the feature

Form error messages can be changed like this: `<formkit type="form" incomplete-message="Foo">`,
but there is no elegant way to theme said error messages. Currently we are stuck with theming "li.formkit-message" using css, which is not very tailwind friendly.

It would be great to add classes to theses error messages, or even better, have the ability to globally add classes to them using rootClasses

**Comment by GustavoFenilli** [comment]
There is already a way to add classes to each error message, you can use the `generateClasses` from `@formkit/tailwindcss` to write their classes like so:
```json
generateClasses({
  text: {
    message: 'text-red-500 border border-red-500'
  }
});
```

**Comment by wernerbihl** [comment]
I've found an elegant solution, thank you. For future devs, here's the code:

In your formkit.config.js:

`
import { generateClasses } from '@formkit/tailwindcss'

export default {
  config: {
    classes: generateClasses({
      form: {
        messages: 'class1 class2'
      },
    }
  }
}
`
