### ISSUE TITLE
"Disabled" prop does not disable buttons as expected

### ISSUE THREAD

**Issue by lupas** [formkit/formkit#215]
# Not Working
When disabling a button or form via `disabled`, as [documented](https://formkit.com/essentials/forms#disabling), the inputs get disabled properly. The buttons however do not get disabled as expected.  This applies to submit buttons in forms, as well as single buttons.

<img width="432" alt="Screenshot 2022-04-28 at 21 59 02" src="https://user-images.githubusercontent.com/4020037/165835536-550c550f-9a5a-452d-bca5-38f2f7e91247.png">

# Working
When setting `disabled="true"` it is working as expected.

<img width="429" alt="Screenshot 2022-04-28 at 21 59 16" src="https://user-images.githubusercontent.com/4020037/165835561-ff9a6d91-2f60-455b-b942-1033074765a6.png">

# FormKit Vue Playground link:
https://formkit.link/38d955e9fa4f6841f48a5a5dec58d109

**Comment by GustavoFenilli** [comment]
I think this is the same issue as #184

**Comment by justin-schroeder** [comment]
This one is a little clearer so I'm going to keep this one and close the other — but will target for beta.7

**Comment by dominikklein** [comment]
@justin-schroeder at the moment a manually added button without the usage of `actions` will not be disabled, is this like expected? (https://formkit.link/3b051bb6fea28c3a24deee1125d5383b)

**Comment by dominikklein** [comment]
> @justin-schroeder at the moment a manually added button without the usage of `actions` will not be disabled, is this like expected? (https://formkit.link/3b051bb6fea28c3a24deee1125d5383b)

@justin-schroeder Should I create a new issue about this topic or is it expected?

**Comment by luan-nk-nguyen** [comment]
Hey @dominikklein your example appears to be working to me. It has `disabled="false"` which means "don't disable it", or "enable all inputs". Flip the value to `true` and it should work.

If you want inputs disabled, any of the following will work:
`disabled`
`disabled="[any truthy value]"`

Let me know if I'm missing something.

**Comment by dominikklein** [comment]
My problem is not the general "disabled" state. When I do a submit the form fields will be disabled, but not my own submit button, but the default submit button (without the actions="false") will also be disabled in this situation.

**Comment by luan-nk-nguyen** [comment]
@dominikklein Ah yes so this bug report already exists: https://github.com/formkit/formkit/issues/236.

You can actually do this in the meantime: https://formkit.link/263d488b49df210f82dbd27149210e1b as mentioned in the issue.

**Comment by dominikklein** [comment]
Ah, thanks, I didn't find the created issue, I already use the workaround, but was not sure if we created the issue after the discord discussion.
