### ISSUE TITLE
Change Form Width

### ISSUE THREAD

**Issue by gutorsantos** [formkit/formkit#220]
I'm testing the FormKit and I ended up facing a problem, how can I change the form width? Apparently the default size is defined by the tailwind class "w-1/2".

I would like change this values, I tried some ways described on documentation but without success.

Current behavior:

![image](https://user-images.githubusercontent.com/12007361/166810324-32291120-e386-4739-b69d-6bd7ae1864ab.png)

**Comment by justin-schroeder** [comment]
The default theme (genesis) is not tailwind and the `.formkit-wrapper` class has a max width. You can just disable this in your css:

```css
.formkit-wrapper {
  max-width: none;
}
```

https://formkit.link/9efbe30e550d54bd4d4d3cddd0e41cab

Good luck with your testing 👍

**Comment by aeagerman** [comment]
Is it possible to override the width for a single FormKit element as opposed to the more globally like above?
ex.

<template>
  <div class="grid grid-cols-2>
	<FormKit type="text" />      
	<FormKit type="text" />      
	<div class="grid-cols-2">    
	   <FormKit type="textarea" />
	</div>
  </div>
</template>
