### ISSUE TITLE
@update:model-value doesn't work

### ISSUE THREAD

**Issue by lavolpecheprogramma** [formkit/formkit#226]
### Reproduction

https://formkit.com/playground?fkv=1.0.0-beta.7&fileTab=Playground.vue&files=JTVCJTdCJTIybmFtZSUyMiUzQSUyMlBsYXlncm91bmQudnVlJTIyJTJDJTIyZWRpdG9yJTIyJTNBJTIyJTNDc2NyaXB0JTIwc2V0dXAlM0UlNUNuaW1wb3J0JTIwJTdCcmVmJTdEJTIwZnJvbSUyMCd2dWUnJTVDbiUyRiUyRiUyMEVTTSUyMGltcG9ydHMlMjBhcmUlMjBzdXBwb3J0ZWQlMjBmcm9tJTIwVVJMcyUyMChodHRwcyUzQSUyRiUyRmNkbi4uLiklNUNuJTJGJTJGJTIwYXMlMjB3ZWxsJTIwYXMlMjBzZWNvbmRhcnklMjBwbGF5Z3JvdW5kJTIwZmlsZXMlMjAoLiUyRk90aGVyRmlsZS52dWUpLiU1Q25jb25zdCUyMGElMjAlM0QlMjByZWYoJ3Rlc3QnKSU1Q25jb25zdCUyMHVwZGF0ZSUyMCUzRCUyMChlKSUzRCUzRSUyMCU3QiU1Q24lMjAlMjBjb25zb2xlLmxvZyhlKSU1Q24lMjAlMjBhLnZhbHVlJTIwJTNEJTIwZSU1Q24lN0QlNUNuJTNDJTJGc2NyaXB0JTNFJTVDbiU1Q24lM0N0ZW1wbGF0ZSUzRSU1Q24lMjAlMjAlN0IlN0JhJTdEJTdEJTVDbiUyMCUyMCUzQ0Zvcm1LaXQlNUNuJTIwJTIwJTIwJTIwJTNBdmFsdWUlM0QlNUMlMjJhJTVDJTIyJTVDbiUyMCUyMCUyMCUyMHR5cGUlM0QlNUMlMjJ0ZXh0JTVDJTIyJTVDbiUyMCUyMCUyMCUyMGxhYmVsJTNEJTVDJTIyRm9ybUtpdCUyMElucHV0JTVDJTIyJTVDbiUyMCUyMCUyMCUyMGhlbHAlM0QlNUMlMjJlZGl0JTIwbWUlMjB0byUyMGdldCUyMHN0YXJ0ZWQlNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTQwdXBkYXRlJTNBbW9kZWwtdmFsdWUlM0QlNUMlMjJ1cGRhdGUlNUMlMjIlNUNuJTIwJTIwJTJGJTNFJTVDbiUzQyUyRnRlbXBsYXRlJTNFJTVDbiU1Q24lM0NzdHlsZSUyMHNjb3BlZCUzRSU1Q24lMkYqJTVDbnZhbmlsbGElMjBDU1MlMjBjYW4lMjBnbyUyMGhlcmUuJTVDbktlZXAlMjBzdHlsZXMlMjBzY29wZWQlMjB0byUyMGF2b2lkJTIwbXVsdGlwbGUlMjBmaWxlcyU1Q25vdmVyd3JpdGluZyUyMGVhY2glMjBvdGhlciUyMGluJTIwdGhlJTIwcmVuZGVyJTIwb3V0cHV0LiU1Q24qJTJGJTVDbiUzQyUyRnN0eWxlJTNFJTVDbiUyMiUyQyUyMmFkZGVkJTIyJTNBdHJ1ZSU3RCU1RA

### Describe the bug

Hi,
seems that in the @next branch the event @update:model-value is not triggered any more.
I have reproduced the bug in the playground.

Thanks in advance

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
This is correct, but is an intended change in beta.7. From beta.7 on `update:-model-value` will only be triggered if you are using the actual `v-model` directive. If you just want to know when updates are made (as you would if you were listening to `update:modelValue` you can listen on `input-raw` (new, but noisy) or `input` (changed to only be updated on debounce).

These changes will be reflected in the `beta.7` docs when that is published.
