### ISSUE TITLE
Child with null value throws error

### ISSUE THREAD

**Issue by mgiraud** [formkit/formkit#227]
Open this playground and check the console to get the error

https://formkit.link/8fcac0fde05a490bd19a5f7f966dd5fc

I don't think this is an expected behaviour. 
The use case which lead me to find this bug  was the edition of an object article where the category is currently null

**Comment by justin-schroeder** [comment]
Thanks for filing this issue, the good news is this is fixed in the `beta.7` tag which is available to install as the @next tag. Beta 7 will likely be released as the active version in just a few days if you prefer to wait.
