### ISSUE TITLE
Error when installing `@formkit/themes`

### ISSUE THREAD

**Issue by engram-design** [formkit/formkit#229]
### Reproduction

NA

### Describe the bug

I'm getting the following error when trying to install `@formkit/themes`. I'm not actually wanting to use any theme, just access to `import { generateClasses } from '@formkit/themes'`.

```
✘ [ERROR] Could not resolve "tailwindcss/plugin.js"

    ../../../../node_modules/@formkit/themes/dist/index.mjs:1:19:
      1 │ import plugin from 'tailwindcss/plugin.js';
        ╵                    ~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "tailwindcss/plugin.js" as external to exclude it from the bundle, which
  will remove this error.

✘ [ERROR] Could not resolve "windicss/plugin"

    ../../../../node_modules/@formkit/themes/dist/index.mjs:2:21:
      2 │ import plugin$1 from 'windicss/plugin';
        ╵                      ~~~~~~~~~~~~~~~~~

  You can mark the path "windicss/plugin" as external to exclude it from the bundle, which will
  remove this error.

11:46:01 am [vite] error while updating dependencies:
Error: Build failed with 2 errors:
../../../../node_modules/@formkit/themes/dist/index.mjs:1:19: ERROR: Could not resolve "tailwindcss/plugin.js"
../../../../node_modules/@formkit/themes/dist/index.mjs:2:21: ERROR: Could not resolve "windicss/plugin"
    at failureErrorWithLog (node_modules/esbuild/lib/main.js:1603:15)
    at node_modules/esbuild/lib/main.js:1249:28
    at runOnEndCallbacks (node_modules/esbuild/lib/main.js:1034:63)
    at buildResponseToResult (node_modules/esbuild/lib/main.js:1247:7)
    at node_modules/esbuild/lib/main.js:1356:14
    at node_modules/esbuild/lib/main.js:666:9
    at handleIncomingPacket (node_modules/esbuild/lib/main.js:763:9)
    at Socket.readFromStdout (node_modules/esbuild/lib/main.js:632:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
```

Stab in the dark, but maybe the export needs to be [updated](https://github.com/formkit/formkit/blob/478db8761efeeea92b6e74591de58eedde01f86e/packages/themes/package.json#L10) to include those other folders, which are in the [source](https://github.com/formkit/formkit/tree/release/beta.8/packages/themes/src)?

I'm using Vite if that makes a difference. But I can confirm those files are missing in `node_modules` 
<img width="245" alt="image" src="https://user-images.githubusercontent.com/1221575/167526516-44305cb0-a0aa-4639-ad4a-746e9ddf7c8c.png">

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by engram-design** [comment]
Actually just realised that this is referring to `tailwindcss` and `windicss` packages, not files in formkit. Running `npm install -D tailwindcss windicss` to include those packages works, but there seems to be something wrong with the [`devDependencies`](https://github.com/formkit/formkit/blob/release/beta.8/packages/themes/package.json) because I would assume that'd be done already...

**Comment by GustavoFenilli** [comment]
I will try to check this using peerDependencies and peerDependenciesMeta marking all plugins as options dependencies and just requiring it when needed.

**Comment by andrew-boyd** [comment]
@engram-design Yep, 'tis borked. We'll have a fix out shortly — sorry for the hassle.

**Comment by justin-schroeder** [comment]
This should all be fixed now in beta 8!
