### ISSUE TITLE
Performance issues when using conditions and `context.slots.default` in component

### ISSUE THREAD

**Issue by engram-design** [formkit/formkit#231]
### Reproduction

https://stackblitz.com/edit/vitejs-vite-he5rap?file=src/ToggleBlock.vue

### Describe the bug

This is a bit of a strange and niche issue, but have managed to put a reproduction together for it.

I'm translating Vue components from Formulate, and just for ease-of-migration, I'm keeping them as components (for now). One of my components is a "toggle block", if you're interested with how it looks:

![image](https://user-images.githubusercontent.com/1221575/167752296-3191adb4-2053-4c9e-a70e-7add8e422342.png)

But basically it's a pass-thru components on two levels. Kind of like a group within a group. There are two components, `ToggleBlocks` and `ToggleBlock`.

`ToggleBlocks` is a very simple pass-thru, so I'm just using the schema:
```js
toggleBlocks: createInput({
  $el: 'div',
  children: '$slots.default',
}),
```

And for the `ToggleBlock` is a Vue component (which is cut-down):
```vue
<template>
  <component :is="context.slots.default" />
</template>

<script>
export default {
  props: {
    context: {
      type: Object,
      required: true,
    },
  },

  created() {
    console.log('created');
  },
};
</script>
```

As you can see, I'm using `<component :is="context.slots.default" />` which I _believe_ is similar to `ToggleBlocks` in the schema. This component will have a few more controls in it for enabling and collapsing the block that I've omitted.

Maybe this is incorrectly architected in the first place, so feel free to pull me up on that.

**So the actual issue** is that when rendering the component, I get an incredible slowness (a good 10 seconds of unresponsive UI). The console seems to show an issue:

```
[Vue warn]: Maximum recursive updates exceeded in component <FormKitSchema>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.
```

Please note that in the reproduction link, you'll need to open web developer tools to see this, it won't appear in the Terminal window there. You'll actually probably get better results downloading the StackBlitz project, and running it locally `npm install && npm run dev`.

This can also be further illustrated when I make a change in the component. I've added a `console.log('created')` call, and just quickly renaming that to `created2` will produce what looks like an infinite loop:

![image](https://user-images.githubusercontent.com/1221575/167752423-1627c028-ac4d-484c-9cc3-365d9b82397a.png)

I've tracked down the issue to using a conditional. In the reproduction, I have some other inputs there, unrelated to the toggle blocks:

```diff
{
  $formkit: 'checkbox',
  label: 'Limit',
  id: 'limit',
},
{
  $formkit: 'text',
  label: 'Limit Settings',
-  if: '$get(limit).value',
},
```

If I remove that single line, there are no more errors and recursion.

(Had to use StackBlitz due to some bugs in the Playground being unable to [import Vue components](https://github.com/formkit/formkit/issues/202))

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
I think the issue might be this guy:

```js
toggleBlocks: createInput({
  $el: 'div',
  children: '$slots.default',
}),
```
First off, I'm not sure this should be an input at all. Makes more sense (in my mind) for this to just be a plain ol' component with a default slot. Inputs in FormKit do some pretty special things, but most notably they create core nodes and add themselves to the form’s tree graph. So unless you want to structure your output data as such, it seems unnecessary. I'm not sure `ToggleBlock` needs to be an input either. Keep in mind FormKit nodes are happy to be nested at any depth in the dom and they will still communicate with the appropriate parent form no matter how far up the tree it is.

Either way though — inputs can only come in three variety's `input`, `group`, `list`. **Only groups and lists can have children.** In your case you are creating an input and then adding children to it. This should have lit up the console like a Christmas tree with warnings. The default type of input created by `createInput` is an `input` — no children. So if you really did want `toggleBlocks` to be an input — it should be declared as a group:

```js
 createInput({
  $el: 'div',
  children: '$slots.default',
}, { type: 'group' }),
```

This should at least get your files to boot up properly: https://stackblitz.com/edit/vitejs-vite-4ce2mo?file=src/main.js

Also worth noting that I changed the `<component :is="context.slots.default">` to use a computed prop instead. Pretty sure there was some deep object-referencing happening there that was causing the infinite loops — not 100% sure on that though. However, if it were up to me I'm not sure I would create inputs for those toggle wrappers, but just an component instead, something like this: https://stackblitz.com/edit/vitejs-vite-bdvcnv?file=src/main.js

Anyway — hope this helps move it along for you. To summarize:

1. Are you sure you need those to be inputs?
2. Children inputs can only be added to groups.
3. `<component :is="context.slots.default">` Appears to need some additional help to get it to work properly like passing it through a computed function first.

**Comment by engram-design** [comment]
Thanks for the awesome feedback!

So in that reduced test, `ToggleBlocks` could indeed be a component, but I do want to add validation to it - for example in the screenshot below:

![image](https://user-images.githubusercontent.com/1221575/167761982-d51b840e-31ee-4b65-9c80-62b9b97bd246.png)

Similarly with `ToggleBlock` if this isn't an input, I don't have access to the `context` object, which I'll need to access the `enabled` and `disabled` states. But having said that, maybe I can update those outside of Formkit inputs altogether, as they don't _quite_ fit to the normal setup of fields and input (there are two bits of data to one "input").

In terms of data structure (which I should've mentioned, as that might help with context), it'd be:

```
{
  address1Enabled: true,
  address1Collapsed: true,
  address1Label: 'Address 1',
  address1Placeholder: '',
}
```

Given the below schema:
```
{
  $formkit: 'toggleBlocks',
  validation: 'required|minBlock:2',
  children: [
    {
      $formkit: 'toggleBlock',
      blockLabel: 'Address 1',
      blockHandle: 'address1',
      children: [
        {
          name: 'address1Label',
          $formkit: 'text',
        },
        {
          name: 'address1Placeholder',
          $formkit: 'text',
        },
      ],
    },
  ],
},
```

So you'll see its actually a pretty flat data structure, so there's no need for the nested structuring that a group brings. In terms of "inputs" it's just the label/placeholder which are regular inputs - easy. the `toggleBlock` could likely become a component.

I've added more detail/context to my original reproduction: https://stackblitz.com/edit/vitejs-vite-xo52xz?file=src/ToggleBlock.vue

I should also mention that if I model the `toggleBlock` Vue component as a schema this issue also goes away (or maybe just masks it because I can't see the `console.log()` shown in the component).

**Comment by GustavoFenilli** [comment]
I liked your component idea ( will be using something similar in my project if you don't mind ), but I would go with a objects of objects for that to work, and at the end I would just flatten the result if needed.

Something on the lines of having this structure.
```js
{
  address1: {
    label: ' ',
    placeholder: ' ',
  },
  address2: {
    label: ' ',
    placeholder: ' ',  
  },
}
```
And run it to flatten aftwards.
```js
const flattenObject = (ob) => {
    var toReturn = {};

    for (var i in ob) {
        if (!ob.hasOwnProperty(i)) continue;

        if ((typeof ob[i]) == 'object' && ob[i] !== null) {
            var flatObject = flattenObject(ob[i]);
            for (var x in flatObject) {
                if (!flatObject.hasOwnProperty(x)) continue;

                toReturn[i + x.charAt(0).toUpperCase() + x.slice(1)] = flatObject[x];
            }
        } else {
            toReturn[i] = ob[i];
        }
    }
    return toReturn;
};

{
  'address1Label': ' ',
  'address1Placeholder': ' ',
  'address2Label': ' ',
  'address2Placeholder': ' ',  
}
```

**Comment by engram-design** [comment]
Go right ahead @GustavoFenilli and I'll look at maybe refactoring this to use groups and go with your suggestion of flattening it. Starting to uncover some more issues with performance that I can't figure out, so this might be the safe bet.

**Comment by justin-schroeder** [comment]
@engram-design very keen to resolve performance issues if you find any. I would put infinite loops in a different bucket. Those are often more about how things are implemented. If you see generalized performance issues, please create a reproduction and pass it along.

**Comment by engram-design** [comment]
I'll probably close this for now, as you say it might just be me, and if it continues to be an issue, will put through some more detail.
