### ISSUE TITLE
Add `required` indicator (asterisk)

### ISSUE THREAD

**Issue by ikadix** [formkit/formkit#233]
### Describe the feature

It would be good if we could specific a specific `required` parameter within a schema to add the [required attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required#accessibility_concerns) to the `input` element. 

It would also be nice to add some default (potentially customised required icon) I believe a red asterisk  is fairly standard. 

For example this very form has that asterisk. 

![image](https://user-images.githubusercontent.com/10099540/168493063-03aff39d-2fc2-4736-922a-2495f5c2e06e.png)

if it's possible to take the presence of the required validation rule to apply this that would also be fantastic. 

This is primarily an [accessibility concern](https://developer.mozilla.org/en-US/docs/Web/CSS/:required#accessibility_concerns) but is also generally expected I think, indicating what users should do first, rather than giving them a validation error after the fact.

I would be happy to help implementing this if you wish, although a pointer as to where to start to add this would be fantastic :pray: 

Apologies if I have missed such an attribute.

**Comment by ikadix** [comment]
I'm so sorry, I noticed that I can add the following to my schema to get the attribute.
```JSON
"required!": true
```

I will leave this open as I believe there may be some benefit for other developers if we can get the required asterisk out of the box.

**Comment by GustavoFenilli** [comment]
Maybe a `hasRule` utility function would work fine for that, so it would be easy to add this functionality via plugin by just checking if `hasRule('required')` and add to the label an `$label + '*'`.

`label: "$: hasRule('required') ? $label + '*' : $label"`

**Comment by ikadix** [comment]
If such a function can be written and opted into that would be great, you could also use it to added the `required` attribute if the `required` rule is selected, that would remove the need to explicitly add the attribute.

**Comment by GustavoFenilli** [comment]
I made a PR for it to be added to the utils #234. lets wait to see if the it passes and it gets added to the schema.

**Comment by justin-schroeder** [comment]
We have a plugin example of this here: https://formkit.link/b48228435ec7770fbc81de811fbe35d8

No plans (at the moment) to add this to core.

**Comment by ruibaby** [comment]
> We have a plugin example of this here: [formkit.link/b48228435ec7770fbc81de811fbe35d8](https://formkit.link/b48228435ec7770fbc81de811fbe35d8)
> 
> No plans (at the moment) to add this to core.

In FormKit 0.17.x, there seems to be something wrong with this plugin, as shown in the figure:

0.17.x:

<img width="1365" alt="image" src="https://github.com/formkit/formkit/assets/21301288/6dcf6c11-d799-4cc2-85d4-ef5fc0dba134">

0.16.x:

<img width="1356" alt="image" src="https://github.com/formkit/formkit/assets/21301288/72ca8382-715b-406e-ba0f-e1ca2b624fb0">
