### ISSUE TITLE
When using :actions false the submit button does not get disabled

### ISSUE THREAD

**Issue by GustavoFenilli** [formkit/formkit#236]
### Reproduction

https://formkit.link/5c2de2b8d6db152964a1513169a5ec78

### Describe the bug

When using a manual submit button inside a form, it does not receive the data-disabled attribute.

### Environment

• OS: popos 22.04
• Browser chrome
• Version: beta.9

**Comment by andrew-boyd** [comment]
It's verbose, but until this is fixed you can track it yourself with a `ref` and assign to the button directly. https://formkit.link/00a9b1e102c8d18e9976ac48053a9ed7

**Comment by luan-nk-nguyen** [comment]
Disabled is top-level in the context object so we can also just pull it out of the slot prop: https://formkit.link/263d488b49df210f82dbd27149210e1b

**Comment by franzwilding** [comment]
For everyone who is looking for a solution that works just with schema definition, this is our current approach: 
https://formkit.link/6e6d3e9b251a3662af15bd0c1c55e4be

(I also included a little example how to dynamically show a loading spinner etc.)

**Comment by justin-schroeder** [comment]
Ok — thinking on this more, I dont think is a bug actually. If someone wants to implement their own submit handler, we cannot assume that they want to disable it during submission. However, we should make it very easy and clear how to re-implement this behavior.

Re-tagging this as a documentation issue. For the record, you can do this:

```vue
<FormKit type="form" :actions="false" #default="{ state: { loading } }" @submit="handler">
  <FormKit type="submit" :disabled="loading" />
</FormKit>
```

https://formkit.link/9956ffe4a8779ffbb995da68eac845b4

**Comment by luan-nk-nguyen** [comment]
This is now documented on the [submit documentation page](https://formkit.com/inputs/submit#provided-submit-button). @franzwilding, we also included your schema-based implementation on our [examples page](https://formkit.com/essentials/examples). Thank you!

**Comment by phillipmohr** [comment]
What would be the best approach if my submit button is within a custom component?

```ts
const schema = [
    {
        $cmp: CrudHeader,
        props: {
            title: t('new_client'),
            submit: props.context === 'create' ? t('create_client') : t('update_client'),
            cancelRoute: '/clients',
           disabled: [How to pass disabled state here?]
        }
    },
    ...
```

**Comment by justin-schroeder** [comment]
It looks to me like you’re assembling your schema using javascript rather than using the `FormKitSchema` components `data` property and then referencing your data using expressions `$fooBar`. FWIW, thats what I would recommend — pass a `reactive()` object to the `data` prop of your `FormKitSchema` and then reference that in your custom component’s prop (including your `t` function):

```js
const schema = [
    {
        $cmp: CrudHeader,
        props: {
            title: '$t(new_client)',
            submit: '$context === create && $t(create_client) || $t(update_client)',
            cancelRoute: '/clients',
           disabled: '$disabled'
        }
    },

...

const data = reactive({
  // ... some context stuff based on your example
 t: translateFunction,
 disabled: false
})

...

<FormKitSchema
  :schema="schema"
  :data="data"
/>
```
