### ISSUE TITLE
Label and Prefix Sections on Buttons not working as expected from documentation.

### ISSUE THREAD

**Issue by jhillacre** [formkit/formkit#243]
### Reproduction

https://formkit.link/e4ec68296566da07d5d62c3feb25f3b9

### Describe the bug

After reading some documentation about buttons, section-keys, slots and tailwind themes, I came away with some expectations that the implementation did not meet. In the reproduction link, it seems like the two buttons should act the same, but do not. I break down these expectations and observations in point form below.

1. I expected that slots are always named after their section keys, based on these documentation sections: 
https://formkit.com/inputs/button#section-keys & https://formkit.com/essentials/inputs#slots. 
   
    I observed that this was not the case on buttons because the label was used as the default slot.
   
    I think this could be resolved by updating the button documentation to indicate the slots available or indicate exceptions of which slots are not available as expected from section-keys.
   
2. I expected that the label-class prop would be available on buttons, based on these documentation sections: https://formkit.com/essentials/styling#section-key-class-props & https://formkit.com/inputs/button#section-keys.

   I observed this was not the case on buttons for providing labels via props or slots.
   
   I think this could be resolved by wrapping the label with an element when a class is provided.
   
3. I expected that the prefix-class prop would be available on buttons when a prefix is passed by slot, based on this documentation sections: https://formkit.com/essentials/styling#section-key-class-props & https://formkit.com/inputs/button#section-keys.
   
   I observed that this was not the case on buttons with prefixes.

   I think this could be resolved by wrapping the label with an element when a prefix and a class is provided.

4. I expected to be able to force labels and prefixes to have wrapping elements using sections-schema, based on this documentation section:
https://formkit.com/essentials/inputs#sections-schema.
   
   I observed that this did not have an effect.

   I think that this could be resolved by allowing users to select different wrapping elements for label and prefix, or to not wrap these sections with elements as described in the documentation.

5. I expected to be able to style button labels and prefixes when creating a custom tailwind theme for formkit, based on these documentation sections: https://formkit.com/guides/create-a-tailwind-theme#our-first-tailwind-input & https://formkit.com/inputs/button#section-keys.

   I observed that the label and prefix keys had no effect on buttons from a `formkit.theme.js` because there were no elements to hang these classes on.
   
   I think this could be resolved where elements are added to wrap sections that are not normally wrapped if a class is desired on the section-key.

### Environment

• OS: Windows 10
• Browser: Chrome 101.0.4951.67 (Official Build) (64-bit)
• Version: 1.0.0-beta.8 & 1.0.0-beta.9 on playground.

**Comment by jhillacre** [comment]
edited to include formkit version, which I had filled in as the chrome version.

**Comment by GustavoFenilli** [comment]
You're are correct, the documentation should exclude some of those sections from the button as those are not provided.

But you can add to the button using section-schemas like so https://formkit.link/8fd815b22e4fce8bf926d5fa3ba167de

**Comment by jhillacre** [comment]
> You're correct, the documentation should exclude some of those sections from the button as those are not provided.
> 
> But you can add to the button using section-schemas like so https://formkit.link/8fd815b22e4fce8bf926d5fa3ba167de

Thanks for the quick response. I'm not sure what I was to take away from this playground example. It seems to show specifying the prefix content via `sections-schema`, but my example as already successful in doing that via vue.js `slots`. Your example doesn't seem to address the expectations I laid out above of having classes applied to prefixes & labels based on `label-class` or `prefix-class` props, or via `label` or `prefix` keys in a `formkit.theme.js` like below. (`input` below works as expected, but the other two keys do not.)
```js
export default {
  button: {
    input: "w-full flex items-center justify-items-center gap-1"
    label: "text-green-500 font-bold grow text-center",
    prefix: "text-orange-500"
  },
};
```

**Comment by GustavoFenilli** [comment]
Sorry, I get what you mean now, the label of an button is actually the input because its the default slot, so you would style using the input.

The case for the prefix, is that a prefix needs to exist and by default prefix has no schema enabled to it, so when you specify your own schema you also need to make sure the classes are applied to it like so https://formkit.link/296b15822fa201df9e85c0b4dc630af9

**Comment by GustavoFenilli** [comment]
You can also do it via slots like you did, by getting the `context.classes`.
https://formkit.link/9065aa6c99a1dc1112ef6f2e00915ad7

**Comment by jhillacre** [comment]
This is the workaround I implemented for the moment, using a component to wrap formkit when it comes to `button` or `submit` types.

```vue
<script setup>

import {get} from "lodash";
import formkitTheme from "../../formkit.theme.js";

const props = defineProps({
    type: {
        type: String,
        default: "button",
    },
    'labelClass': {
        type: String,
        default: '',
    },
    'prefixClass': {
        type: String,
        default: '',
    },
    'suffixClass': {
        type: String,
        default: '',
    },
});

const slotWrapper = name => {
    // label is default for buttons.
    return ['prefix', 'suffix', 'default'].includes(name) ? 'span' : 'v-fragment';
}
const slotClass = name => {
    // label is default for buttons.
    return {
        prefix: props.prefixClass || get(formkitTheme, `${props.type}.prefix`) || get(formkitTheme, 'global.prefix') || '',
        default: props.labelClass || get(formkitTheme, `${props.type}.label`) || get(formkitTheme, 'global.label') || '',
        suffix: props.suffixClass || get(formkitTheme, `${props.type}.suffix`) || get(formkitTheme, 'global.suffix') || '',
    }[name];
}
</script>

<template
    ><form-kit
        :type="props.type"
    ><template
        v-for="(_, name) in $slots" v-slot:[name]="slotData"
        ><component
            :is="slotWrapper(name)"
            :class="slotClass(name)"
            ><slot
                :name="name"
                v-bind="slotData"
            /></component
        ></template
    ></form-kit
></template>

<style scoped>

</style>
```

**Comment by jhillacre** [comment]
> This is a misunderstanding of how slots work. When you use a slot you are opting to replace the content rendered in that slot — if you want to use the classes designated for that slot on the custom element you define, you can access it from the scoped-slot data `context.classes.{slotName}`

If the intention is not to support class props for every section, I think each input should list the available class props independent of any section listing. Without this, a reader needs to read between the lines for which classes are supported, specifically when creating a tailwind theme. If a class is only supported in absence of a slot being filled, that should also be indicated in the documentation with your example of how to make it work.

I don't think expecting a slot to be wrapped "misunderstands how slot work." Seems like more detail in the [section documentation](https://formkit.com/essentials/inputs#sections) could rectify any implied expectation that all sections have slots and class props that work simultaneously.

**Comment by justin-schroeder** [comment]
I'm all for trying to make the documentation more clear 👍. To be clear — the intention is that all sections have a corresponding class prop, can be addressed with `sections-schema`, or can be overridden via slot — there's a big warning directly under slots that explains if you are using a slot its up to you to re-implement any structure or logic that section previously had.

![slot warning](https://user-images.githubusercontent.com/1950463/170318263-41ecb4fa-13c9-4e27-a4c3-b6f877984049.png)

In an effort to address your concern I've updated that warning to use the classes example:

![updated slot warning](https://user-images.githubusercontent.com/1950463/170318389-3d7a3cb5-4450-473d-9833-b896f3975aba.png)

So on that front I think we're probably covered — not to mention its pretty standard practice in vue for slots to work this way. If we had wrappers *around* ever section, then users would be frustrated they could not use slots to target _those_ dom elements. But hopefully that updated message helps clear up any confusion 👍

**Comment by jhillacre** [comment]
Sounds good. Better documentation sounds great, and I have a workaround for how I hoped things worked.
