### ISSUE TITLE
`normalizeOptions` - Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by engram-design** [formkit/formkit#244]
### Reproduction

https://formkit.link/e5045aaf1bd7e27fa2ec16b34c261162

### Describe the bug

This is a bit of a strange one, and seems to be only due to a very specific set of field setups. Refer to the reproduction link, but it seems like fields are getting mixed up!

Here's a screenshot of how it should look:

<img width="580" alt="image" src="https://user-images.githubusercontent.com/1221575/169539047-4262586d-51bd-4df8-96dc-4d54377ed6a0.png">

Which you can actually check, by commenting out any conditionals on the inputs. Otherwise, you'll see:

<img width="457" alt="image" src="https://user-images.githubusercontent.com/1221575/169539301-193e2eaa-5dd5-4498-be68-02ec2a8d6ff6.png">

And you can see the "Instructions" field is messed up! Somehow being used for both the "Subfield Label Position" (a select) and "Instructions" (textarea - the correct one).

As such, this issue title might not be correct, because it's **technically** a correct error in that one of the fields (the first "Instructions" field that's a select), has no `options`, but it shouldn't be that field in any case.

Any ideas what's messing up these fields for these circumstances?

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
This can happen in Vue when it recycles DOM elements. The key to fixing it is....keys!

https://formkit.link/c665b129c64e64980a35084ec8d5e234

**Comment by engram-design** [comment]
Ah, of course - that makes sense! At least now I know about the `key` param as well.

For some reason, the playground links seem to be down?

**Comment by justin-schroeder** [comment]
Hmm, not down for me? Maybe try a hard-refresh?

**Comment by engram-design** [comment]
Weird, it's just a "connection reset" error.

![image](https://user-images.githubusercontent.com/1221575/169935538-3b542fb7-d0a3-4296-b8a3-9b84cc9cbee0.png)

But you're right, just tried outside of out network, and it's fine. Thanks!
