### ISSUE TITLE
Set optional field as required, when another optional field is filled

### ISSUE THREAD

**Issue by rix1337** [formkit/formkit#245]
### Describe the feature

I've read the docs and have implemented various of formkit's features in my own project.
What I have not been able to do, even with [form groups](https://formkit.com/inputs/group) or [custom validation rules](https://formkit.com/essentials/validation) is the following:

Some optional form fields in my app depend on each other.
A user can for example set a URL and an API-Key to enable notifications from a third party service.

I do not want the fields to be required (URL/API-Key), since it is completely valid for a user not to provide this information.
What I want instead is: if a user fills out URL, then API-Key must also be provided.

Example:
https://github.com/rix1337/FeedCrawler/blob/88873c628e141bfe3cd1c68a43eca6b69657911b/feedcrawler/web/src/components/Settings.vue#L516

I have been struggling with this all day, and have concluded that either myself, or FormKit does not allow this functionality right now.

Thus the request, hope you find it useful - or can provide me directions how to implement this as-is.

**Comment by justin-schroeder** [comment]
👋 @rix1337

Sorry to hear this was so tough for you. There's a number of ways you can handle this, but you mentioned groups (which work the same as forms) and custom validation so I'll share examples of those two methods:

- Using a "group" (form in this case): https://formkit.link/9e8853ae974bde18d815de94a8d65bc6
- Using a custom validation rule: https://formkit.link/793266c9aa0a624552241c437beb2281

Hope this helps! Good luck 👍

PS: It might be worth noting that in your example you are v-modeling every single input, there generally isn't any reason to do that with FormKit. Its not necessarily "wrong", just seems like a lot of extra work when FormKit can model your entire structure with a single v-model, you can use groups/lists to structure the data as you like.

**Comment by rix1337** [comment]
Thanks for the quick and helpful reply.

Ill look into your examples.

PS: the v modeling is a direct result from refactoring the mess I had to maintain before switching to FormKit. I'll have to do another refactor then 👍🏻

**Comment by rix1337** [comment]
Using a "group" (form in this case): https://formkit.link/9e8853ae974bde18d815de94a8d65bc6 worked very well for me.
Closing this
