### ISSUE TITLE
RFC: Add `meta` property to FormKitSchemaNode

### ISSUE THREAD

**Issue by justin-schroeder** [formkit/formkit#248]
## Motivation

FormKit uses the concept of "sections" in FormKit inputs to describe each "chunk" of HTML (usually a single DOM element). These sections are purely conventional and have no semantic relationship the the underlying schema. In other words — the actual schema parsed by `FormKitShchema` has no concept of a "section" or any other meta information. Instead, FormKit uses function composition create these "sections" before the final schema is assembled. For example, a simple FormKit input with only a `<label>` and `<input>` tag is currently defined like this (pseudo-code):

```js
const section = (sectionName, schemaNode, extendWith = {}) => {
  return {
    if: `$slots.${sectionName}`,
    them: `$slots.${sectionName}`,
    else: extend(schemaNode, extendWith)
  }
}

const inputSchema = (extensions = {}) => {
  return [
    section('label', {
      $el: 'label',
      attrs: {
        for: '$id',
      },
      children: '$label',
    }, extensions.label),
    section('input', {
      $el: 'input',
      attrs: {
        id: '$id'
      }
    })
  ]
}
```

When executed the output is a well-formed schema object, but notably absent is any indication of which element is conventionally associated with each section:

```js
[
  {
    if: '$slots.label',
    then: '$slots.label',
    else: {
      $el: 'label',
      attrs: {
        for: '$id',
      },
      children: '$label'
    }
  },
  {
    if: '$slots.input',
    then: '$slots.input',
    else: {
      $el: 'input',
      attrs: {
        for: '$id'
      }
    }
  }
]
```

Why is this a problem? Without any meta-information about these nodes, it makes it difficult to create new tooling around schemas. For example, in our example above if we wanted to move our `<label>` after the `<input>` it would be challenging to identify what objects needed to move where.

While providing section context to the final schema is one use case, there are certainly others. Any third-party plugin could assign meta information about a given node during the assembly of a schema and then act on this information in its final assembled format.

## Proposal

Currently, all valid properties of `FormKitSchemaNode` are used in the compiling or rendering process. This proposal introduces a new root property `meta`. This new property would be valid on `FormKitSchemaDOMNode`, `FormKitSchemaComponent`, `FormKitSchemaFormKit` nodes:

```ts
type FormKitSchemaMeta =  Record<string, string | number | boolean | null | FormKitSchemaMeta>

export declare interface FormKitSchemaProps {
    children?: string | FormKitSchemaNode[] | FormKitSchemaCondition;
    key?: string;
    if?: string;
    for?: FormKitListStatement;
    meta: FormKitSchemaMeta
}
type FormKitSchemaDOMNode = {
    $el: string | null;
    attrs?: FormKitSchemaAttributes;
} & FormKitSchemaProps;

type FormKitSchemaFormKit = {
    $formkit: string;
} & Record<string, any> & FormKitSchemaProps;

type FormKitSchemaComponent = {
    $cmp: string;
    props?: Record<string, any>;
} & FormKitSchemaProps;
```

The `meta` property would not directly impact the parsing or output of the final DOM elements but would be very useful for processing the schema before it is parsed and compiled.

To make this practical, FormKit’s core nodes should also implement a `schema` hook that allows plugins to perform modifications to the assembled schema immediately before it is parsed. This hook would allow first-party and third-party plugins to modify the final schema, with section precision.

## Example

Let’s take our earlier example of a 2 node input:

```js
const inputSchema = (extensions = {}) => {
  return [
    section('label', {
      $el: 'label',
      attrs: {
        for: '$id',
      },
      children: '$label',
    }, extensions.label),
    section('input', {
      $el: 'input',
      attrs: {
        id: '$id'
      }
    })
  ]
}
```
The schema output of executing this schema function would include meta data:

```js
[
  {
    if: '$slots.label',
    then: '$slots.label',
    meta: {
      section: 'label',
      weight: 0,
    },
    else: {
      $el: 'label',
      attrs: {
        for: '$id',
      },
      children: '$label'
    }
  },
  {
    if: '$slots.input',
    then: '$slots.input',
    meta: {
      section: 'input',
      weight: 1
    },
    else: {
      $el: 'input',
      attrs: {
        for: '$id'
      }
    }
  }
]
```
Meta properties (like `section` and `weight` above) could be added at will and would be discarded durring the parsing of the schema.

Additionally, we propose a new hook be introduced: `node.hook.schema`. Plugin authors could leverage meta properties before the schema is parsed and perform modifications. For example, a plugin could sort schema nodes based on their `meta.weight` property and letting end users change the order using the `sections-schema` prop to change the `meta.weight` properties of a given section.

A hypothetical `sortPlugin` example:

```js
function sortPlugin (node) {
  node.hook.schema((schema, next) => {
    schema.sort((nodeA, nodeB) => nodeA.meta.weight > nodeB.meta.weight ? -1 : 1)
    return next(schema)
  })
}
```

Importantly, the `meta` attribute would have no effect *inside* the schema parser or compiler — it would be inaccessible. The parser would regard these meta properties as comments and discard them entirely during parsing.

## Outcome

If implemented, this change would lay the groundwork for a series of additional utilities and developer enhancements in the FormKit. Most notably (and urgently), this change would allow plugin authors to easily move sections or even create new ones.

```js
/**
 * A plugin that moves the label after the input
 */
function labelAfterInputPlugin (node) {
  if (node.props.type === 'text') {
    node.hook.schema((schema, next) => next(move({
      section: 'label',
      to: 'inner',
      atIndex: 2
    }))
  }
}
```

**Comment by GustavoFenilli** [comment]
With in mind that we could create out own sections by adding meta section, what would it happen to props that use the already defined sections? like `:section-schema` and `{section}-class` props, would those look for the meta information to know which one to change, even custom made ones?

**Comment by justin-schroeder** [comment]
I suppose that depends on how the custom added sections are created. Sections-schema would be executed before the schema hook, so as long as section additions occur before the schema is "assembled" then sections-schema would work properly
