### ISSUE TITLE
How can I modify the existing schema to move the label field in a checkbox to after the checkbox?

### ISSUE THREAD

**Issue by cbeckner12** [formkit/formkit#253]
This isn't a bug or feature request, per se, but I need the ability to move the label field after the checkbox. I have tried modifying the schema and was able to use create a plugin with a custom type, however, I would like to be able to modify the built-in checkbox, multiple-checkbox list.

Is there a way I can re-create the base schema (outer, wrapper, label, inner, prefix...) and have the checkbox use a different schema instead?

Thank you.

**Comment by GustavoFenilli** [comment]
This is the same as #174, you can check out the progress of schema modifications there ( there is also a example on how to move and modify specific sections there )

**Comment by cbeckner12** [comment]
I have tried that, but am not seeing "how" to move the label in that example. I see deleting the original label (i.e. extensions.label = { $el: null, children: null }). So, basically, how can I move the label from the original place to just after the input? This is not working for a checkbox (the example actually filters out checkboxes).

**Comment by GustavoFenilli** [comment]
The hability to move a schema isn't implemented yet, you can check out the RFC here: #248.

For now if you want to move it, you have to remove the old label, and add it to where you want it, by changing the schema of the wrapper of the element you want to move to.

I think checkboxes are inside the label, so if you remove the label you also remove the checkbox, so you would have to change the label and add back the checkbox logic back.

**Comment by cbeckner12** [comment]
Is there a way that I can implement the useSchema (maybe create it using a different name) and change the checkbox schema using the new definition? Something like below? I've made some attempts, but couldn't find where I could import the outer, wrapper, inner, etc.

export function useSchemaChkBox (
  inputSchema: FormKitInputSchema
): FormKitExtendableSchemaRoot {
  return (extensions = {}) => {
    const input = composable('input', inputSchema)(extensions.input)
    return [
      outer(extensions.outer, [
        wrapper(extensions.wrapper, [
          inner(extensions.inner, [
            prefix(extensions.prefix),
            ...(Array.isArray(input) ? input : [input]),
            label(extensions.label, '$label'),
            suffix(extensions.suffix),
          ]),
        ]),
        help(extensions.help, '$help'),
        messages(extensions.messages, [
          message(extensions.message, '$message.value'),
        ]),
      ]),
    ]
  }
}

Thanks for all your help!

**Comment by GustavoFenilli** [comment]
I think those are not exported, only classifications and features are at the moment, you can instead just check out how they are made here: https://github.com/formkit/formkit/tree/master/packages/inputs/src/composables

**Comment by cbeckner12** [comment]
Thank you - I have a somewhat working solution now, can't wait to see beta-9, this is an excellent project! Please all keep up the great work!

**Comment by justin-schroeder** [comment]
Glad you found something that is working for you 👍 It's a valid question, but I'm closing to consolidate with #174
