### ISSUE TITLE
How to modify input classes and message(s) classes on error

### ISSUE THREAD

**Issue by cbeckner12** [formkit/formkit#254]
Is there a way to add classes to the input and messages/message elements on an error? I would like to display an icon to the left of the error message also. For instance (using an svg icon/path):

Textbox with red border (input)
(x) The Username is invalid (message)

Is there a way also to put html in the messages, currently, it seems that it only accepts text.   For instance:
defaultConfig({
  messages: {
        en: {
          validation: {
            required({ name }) {
              return `Please fill out the <strong>${name}</strong> field.`
            }
          }
        }
      },
})

Thanks.

**Comment by justin-schroeder** [comment]
Here's the basic concept — feel free to rif on it from here: https://formkit.link/ed8f1808e835e4ee8c44c96b51d87745

If you have more generalized questions, we'd love for you to join us on the discord support channel so we can have higher bandwidth communication about it: https://discord.gg/bF7JQKrp3X

Good luck! 👍
