### ISSUE TITLE
Plugins on type="form" are not inherited by "button" and "submit" input types

### ISSUE THREAD

**Issue by andrew-boyd** [formkit/formkit#256]
### Reproduction

https://formkit.link/dbf13aec6f984655a2c830d5767e19a3

### Describe the bug

Came across this issue while working on the upcoming icon plugin.

current behavior: Plugins applied to a `<FormKit type="form">` element are not inherited by `<FormKit type="button" />` or `<FormKit type="submit" />` FormKit elements. 

expected behavior: All FormKit elements should inherit plugins from their parent, regardless of type.

### Environment

• OS: macOS
• Browser: Chrome
• Version: 101.0.4951.64 (Official Build) (arm64)

**Comment by justin-schroeder** [comment]
Went to fix this and realized we already had a solution. Most of the time we *want* a button to be ignored in a given form, but occasionally we don’t. The `:ignore="false"` prop can turn off this default behavior.

Beta 13 enables this for `submit-attrs` as well:
https://formkit.link/af57e198b433d3e0b38bc686c55eeb8b

@luan-nk-nguyen we need to document this behavior on the button/submit pages and form page.

**Comment by luan-nk-nguyen** [comment]
Docs are written: https://formkit.com/inputs/submit#ignored-input
