### ISSUE TITLE
When will there be a stable version of this package?

### ISSUE THREAD

**Issue by StefanGhiban** [formkit/formkit#257]
Hi! So far from what I have seen, this project is insanely good, but still in beta. Any idea when we will have a stable version of it so we can safely use it in a production environment? Thank you.

**Comment by justin-schroeder** [comment]
Likely in the 1-2 month time range for the first RC version. However, its pretty stable today and we publish breaking changes on every release so quite a few users are already using it in production. Feel free to join us on discord to ask about any specifics too:  https://discord.gg/bF7JQKrp3X
