### ISSUE TITLE
Prepop Values Without Specifying Groups

### ISSUE THREAD

**Issue by totalhack** [formkit/formkit#258]
### Describe the feature

From what I can tell, in order to pre-populate input values when using groups you need to specify the name of the group node and then nest the input values under that. For example, let's say I had a group called `dateAndZip` which had two input nodes named `date` and `zip_code` within it. In order to prepop values it seems I need to do the following (using schema in this example):

```javascript
const schema = [
  {
    $cmp: 'FormKit',
    props: {
      type: 'form',
      id: 'form',
      value: {
        dateAndZip: {
          zip_code: "12345",
          date: "2022-05-01"
        }
      }
    },
```

Since all node names need to be unique as far as I can tell (since they get entered into a global registry), shouldn't it be possible to prepop without specifying the group name? The groups, at least in my case of a multi-step form, are purely organizational with somewhat arbitrary names, and the position of the inputs may shift to other groups over time. On top of that if I want to share a form I don't really want the consumer to have to get tied to my group naming just to prepop values. Then any change in input position to a different group/step, or any change in group name would break the front end code unnecessarily, as well as making things like prepop-ing from URL values more cumbersome -- i.e requiring something like `&dateAndZip.zip_code=12345` or passing JSON structures in a URL param value which is even more painful.

I suppose I may be able to work around this with a plugin that handles a flat `value` structure, or passing and using a custom prop altogether, but it would be nice to be built in. Thanks for hearing me out!

**Comment by GustavoFenilli** [comment]
I have the same "problem" the backend does not care about the grouping, the group should only be visual in itself, so prepending values to a group is quite cumbersome.

But the idea of a unique name is based on the node it is in, because between two groups, those could have children with the same name like so: https://formkit.link/52c06d195db241e17b9bcb038f28b714, so it wouldn't be able to tell where It should pass your values.

So what I would sugest to be implemented is a ghost group, where its idea is only grouping fields for logical interaction, but it would not have a name and its values would be flat to the root of it ( like a list, but not an array ).

**Comment by totalhack** [comment]
@GustavoFenilli I also don't need it for the backend, so +1 for maybe having an option to post a flattened structure, but I'll leave that to a different issue. If the names need to be scoped to the group due to non-uniqueness I'm not sure that's going to be doable -- could use the ID, but the auto-generated ones wouldn't work and it seems to pre-pop and post by name at the moment.

I was wrong about how [the registry](https://github.com/formkit/formkit/blob/0d8eae96b5f9c82c977d9da97f954b732c971d11/packages/core/src/registry.ts#L64) works. The [example](https://formkit.link/da55ac3f0088bffc6b00625dd979ed5b) I was working off of used `getNode` and passed the node name, but I missed that they were also setting the `id` to equal to `name` explicitly. 

So if the names don't have to be unique I can see why it's done the way it is. Perhaps there needs to be a way to either A) post by ID, in which case I'd make sure to set my own user-friendly unique IDs on everything or B) have a "flat" mode that requires unique input node names and takes a flat structure for prepop, also posts a flat structure on submit.

**Comment by totalhack** [comment]
My preliminary, hacky workaround to the prepop issue is to create a simple plugin that looks for a `prepop` attribute on the root:

```javascript
const schema = [
  {
    $cmp: 'FormKit',
    props: {
      type: 'form',
      id: 'form',
      prepop: '$prepop'
    },
```

Then if a `prepop` object is set on the data passed to `FormKitSchema`, this plugin will look for nodes with names that match the object attributes and set the input value. So a flat object will work as long as the node name matches, and of course if you have duplicate node names they will all be set to that value:

```javascript
let prepopValues = {}

const prepopPlugin = (node) => {
  if (node.props.type == "form") {
    prepopValues = node.props.attrs.prepop || {}
    return true
  }

  if (node.props.type == "group") {
    return true
  }

  if (prepopValues[node.name]) {
    console.debug('Setting prepop value for:', node.name, prepopValues[node.name])
    node.input(prepopValues[node.name])
  }
}
```

There is likely some easier/cleaner way to do this, but this seems to work in preliminary testing.

**Comment by totalhack** [comment]
Also, if you want to flatten before submitting you could do that in your submit handler with something like this before posting:

```javascript
export const flattenObject = (obj) => {
  const flattened = {}

  Object.keys(obj).forEach((key) => {
    const value = obj[key]

    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      Object.assign(flattened, flattenObject(value))
    } else {
      flattened[key] = value
    }
  })

  return flattened
}
```

Credit: https://stackoverflow.com/a/55251598/10682164

**Comment by justin-schroeder** [comment]
A few things I wanted to clarify on this:

> Since all node names need to be unique as far as I can tell (since they get entered into a global registry), shouldn't it be possible to prepop without specifying the group name?

Node names are not entered into a global registry, and do not need to be globally unique (only unique within their given object-depth). Only nodes with an explicitly defined `id` are entered into the global registry. I'm betting you knew this and just slipped on the semantics, but in case that was unclear its worth pointing out 👍

> I suppose I may be able to work around this with a plugin that handles a flat `value` structure, or passing and using a custom prop altogether, but it would be nice to be built in. Thanks for hearing me out!

This is a valid limitation that @GustavoFenilli has brought up before. It can be frustrating for pre-pop and submission. The solution would be to add a 4th type of node (currently: `list`, `group`, `input`) — perhaps something like `provider` that operates as a group, but forwards all values to the parent without contributing its own wrapper. This is technically possible, and probably worth putting on the roadmap, but it does require modifying FormKit core substantially and it raises almost as many questions as it answers. Like, what is the `node.value` of this node? Not saying we cannot answer those questions, but it would need to be a careful and considered process.

I think a more reasonable approach is to create plugins and helpers to accomplish the desired outcomes, like a step component, and other helper components or functions.

**Comment by GustavoFenilli** [comment]
It could be cool to have at the how to create multi step form guide some mention about this, and maybe a approach on how to deal with a flat input and output using the plugin for step already build, just to clarify this "limitation".
