### ISSUE TITLE
Wrap section using Schemas

### ISSUE THREAD

**Issue by benjaminrobinet** [formkit/formkit#259]
Hello !

Maybe I have missed something. But how can we wrap a section using Schema.
I mean: I would like to keep children as FormKit default schema.

The fact is that in a list of radio inputs, I just want to wrap all the li items with a `{$cmp: TransitionGroup}` without rewriting all the childrens.

Thanks !
Have a good day

**Comment by justin-schroeder** [comment]
It can be done, although I'd highly recommend using [AutoAnimate](url) for this (one of the reasons we made it)

**Comment by justin-schroeder** [comment]
Oops, didnt mean to close it — here's an example of schema wrapping from a while back: https://formkit.link/4dc10f3365ca112bbca1b8818fb5824d

Not exactly what you are going after but you should be able to work it out from there. All in all though, auto-animate is gonna solve this even better.

**Comment by benjaminrobinet** [comment]
> Oops, didnt mean to close it — here's an example of schema wrapping from a while back: https://formkit.link/4dc10f3365ca112bbca1b8818fb5824d
> 
> Not exactly what you are going after but you should be able to work it out from there. All in all though, auto-animate is gonna solve this even better.

This way, we still need to rewrite childrens ? Can't we just "wrap" with another component ?

**Comment by justin-schroeder** [comment]
The schema is just a javascript, so sure, if you want to write a higher order function to do so you can! But there is no built in "magic" way to wrap something.

**Comment by justin-schroeder** [comment]
Feel free to carry this conversation on in the [Discord](https://discord.gg/Vhu97pAC76). However, I'm going to close this as its not a feature request or bug report.
