### ISSUE TITLE
Custom select

### ISSUE THREAD

**Issue by JakubChimiak** [formkit/formkit#261]
Hi guys, can u recommend an approach how to use this library alongside with [SlimSelect](https://slimselectjs.com/)

**Comment by JakubChimiak** [comment]
I was trying to init SlimSelect with plugin using `created `event but when callback on this event is running DOM element still doesn't exists

**Comment by GustavoFenilli** [comment]
You can create a custom input https://formkit.com/advanced/custom-inputs, you can use the `context._value` to show the values using their `setData` on prop change, and to make it set you can use their `set` with `context.node.input`.

**Comment by JakubChimiak** [comment]
Works almost everytime with `await new Promise((r) => setTimeout(r, 50));`

```javascript
import SlimSelect from "slim-select";

export default function useSlimSelect() {
  const slimSelectPlugin = (node) => {
    if (node.props.type === "select") {
      node.on("created", async (payload) => {
        await new Promise((r) => setTimeout(r, 50)); // "next tick"

        if (document.querySelector(`#${payload.payload.props.id}`)) {
          new SlimSelect({
            showSearch: false,
            select: `#${payload.payload.props.id}`,
          });
        }
      });
    }
  };

  return { slimSelectPlugin };
}

```
