### ISSUE TITLE
Config classes can not be extended inside of a form or single field

### ISSUE THREAD

**Issue by dominikklein** [formkit/formkit#262]
### Reproduction

https://formkit.link/e11450953673688c79860ae3af353e21

### Describe the bug

At the moment the global created classes inside of the config, can not be extended with the config prop of a form or single field.

I would expect that the classes can/will be extended and not completely overridden.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by GustavoFenilli** [comment]
They are being overwritten by your configuration, I think this is expected, if you want to extend you should use the other forms of extending styles like using `classes` prop or `section-key`.

**Comment by dominikklein** [comment]
I think we can work around this in our project

I added this report because in discord it was described that it should work like this. So that you can extend the classes on a form level without overwriting the complete "default" classes config from the initialization of the formkit plugin.
In the end, I would expect it like this because otherwise, you need always to add all classes from the initialization also to such a form usage.

**Comment by GustavoFenilli** [comment]
What use case do you believe this would solve? do you think this could be a improvement, and how do you think it would work for overwritting instead of extending?

**Comment by justin-schroeder** [comment]
The `config` object is not deeply extended, nor will it be. The config object performs a shallow merge ontop of the global properties and allows you to reset any config properties, including classes. However this is why we created the `classes` prop — specifically so you can achieve a bulk deep extension.

I dont think the expectation that config would deep merge is incorrect, but unfortunately its would be an architectural change that would add too much weight to the package.
