### ISSUE TITLE
Modify formData before submitting form

### ISSUE THREAD

**Issue by JakubChimiak** [formkit/formkit#263]
What is the best approach to for example format all date inputs before submitting form?

**Comment by GustavoFenilli** [comment]
You can get the fields and transform before submiting to your backend.
```html
<FormKit type="form" @submit="fields => send(transform(fields))" />
```
```js
const send = (fields) => {
  // send to your backend
}

const transform = (fields) => {
  return newFielsd;
}
```

**Comment by JakubChimiak** [comment]
I was rather thinking of plugin for form that's gonna handle just all date fields
so I would do `:plugins="[dateFormatter, timeFormatter]"`

**Comment by GustavoFenilli** [comment]
You could use a plugin to change the input to your formatted state, but that would also change it visually. I think you may be able to change the submit prop to run a transform before calling it.
```js
const formatter = (node) => {
  if (node.props.type === 'form' && node.props.onSubmit) {
    const oldSubmit = node.props.onSubmit;
    node.props.onSubmit =  (fields, node) => oldSubmit(formatDate(fields), node);
  }
}
```

**Comment by JakubChimiak** [comment]
Would be nice if I could access type of field in `onSubmit`
