### ISSUE TITLE
Why do we have to add a plugin to tailwind config when creating a theme with tailwind.

### ISSUE THREAD

**Issue by StefanGhiban** [formkit/formkit#266]
### Reproduction

Not relevant

### Describe the bug

This is not a bug per se. I was just wondering why we have to do this: ```Add the formKitTailwind plugin from @formkit/themes to our project's tailwind.config.js file.```.

Creating a tailwind theme works just by overriding the default theme in a main.js/ts file of a vue project.

### Environment

Not relevant

**Comment by justin-schroeder** [comment]
You dont *have* to of course, but the reasons you might *want* to [are explained in the guide](https://formkit.com/guides/create-a-tailwind-theme#using-formkitthemes)

Mostly its for things like variants

**Comment by GustavoFenilli** [comment]
The formkit plugin for tailwindcss is to add formkit [variants](https://formkit.com/essentials/styling#outer-attributes) to tailwindcss, its not an actual theme with default styles and so on, if you want for example to style the input when there is an error you use the variant `formkit-invalid:border-red-500`. Maybe we could change its name to make it more obvious what the plugin does.

**Comment by StefanGhiban** [comment]
> [](https://formkit.com/guides/create-a-tailwind-theme#using-formkitthemes)

Ah, my bad. Thank you for the answer!
