### ISSUE TITLE
Getting typescript error when trying to type the form data argument of a submit function.

### ISSUE THREAD

**Issue by StefanGhiban** [formkit/formkit#273]
### Reproduction

-

### Describe the bug

I am using the formkit type form component to wrap multiple inputs. When I try to type the form data argument of the submit functiontthat is being passed to @submit, Im getting a typescript error with a type mismatch.

![unknown](https://user-images.githubusercontent.com/47953165/172160997-29bbf1e7-3b9c-4c5c-8c31-4a51038c6a1a.png)
![unknown2](https://user-images.githubusercontent.com/47953165/172161006-b446cf82-33cf-44df-9a1d-edc08bf24720.png)

### Environment

• OS: macOs
• Browser: chrome

**Comment by justin-schroeder** [comment]
I believe this is no longer an issue in later versions of FormKit. We've made the second argument optional, and the first is `any`
