### ISSUE TITLE
Can't get formkit to pick up config file

### ISSUE THREAD

**Issue by milos5593** [formkit/formkit#286]
### Reproduction

https://stackblitz.com/edit/nuxt-starter-lhicgd?file=tailwind.config.js,package.json,app.vue,formkit.config.ts

### Describe the bug

I am trying to setup Formkit with Nuxt 3 and Tailwind, but for some reason I can't get Formkit to pick up config file.

### Environment

• OS: macOS
• Browser Firefox
• Version 1.0.0-beta.8

**Comment by justin-schroeder** [comment]
The `classes` option is a child of the `config` options:

https://stackblitz.com/edit/nuxt-starter-51dncb?file=formkit.config.ts

Enjoy ❤️

**Comment by milos5593** [comment]
@justin-schroeder thanks, I guess I was confused by the top const being named config, didn't realize I needed another nested option named config too.
