### ISSUE TITLE
Extra input error not being shown anywhere

### ISSUE THREAD

**Issue by dakujem** [formkit/formkit#289]
### Describe the feature

We have a server request handler that catches server exceptions and then distributes the errors to the form. 
Errors with a known source are bound to "input errors", generic errors without known source are bound to the "form errors".

An issue happens when there is an extra field in the request, say `whatever` is the extra field, and the server replies with validation failure, where `whatever` input is the source, this is then set to formkit to handle, but since thete is no input named `whatever`, this message is lost (not shown anywhere). 
```
this.$formkit.setErrors('test', {}, {whatever: "This error message will not be shown anywhere."})
```

I believe it should appear in the "form errors" when it's not rendered/related to any input, because the form simply does not submit and the user has no visual feedback.

At the moment of calling the code above we do not know the structure of the form, so it's not possible (or would be very complicated) to redirect the message to form errors.

> I'm sorry, I'm in a hurry and was unable to create a playground, so I'm using the Feature template

**Comment by dakujem** [comment]
Good idea! If there is an option for a callback to be invoked for errors that would not be seen, either via `this.$formkit` or via the call to `setErrors` (i.e. a parameter of the call), then that would be even better, I a ssume.

I could simply add the errors to the form errors via this function manually, while the others would bake in the functionality tailored to their app. 💪

**Comment by dakujem** [comment]
I'm not sure what `Record` is, but if it's a value of `inputErrors`, or something that wraps that original value and the original value is accessible via `Record`, then I'm fine with the interface.

**Comment by dakujem** [comment]
Any plans to implement this feature?

I took a while to look into the source code, but it is beyond my current JS coding capabilities and my understanding of the inner workings, I must admit.

I can see there is some kind of `ChildMessageBuffer` and a `releaseMissed` function. I also see the problem - the buffer is _waiting_ till the child node gets created, but if that never happens, the error is lost in space.

I think the `applyMessages` should not only collect the "missed" messages (calling `missed`), but also report back (either return a value or accept a callback), and then the `setErrors` could accept the `remainingErrors` callback parameter mentioned above that would either be invoked for the individual messages or a collection of missed messages.

Sorry I am not able to help more.

**Comment by GustavoFenilli** [comment]
Hey, there is now a hook for setErrors where you could run your logic in there, sadly I does not know the remaningErrors but you can get those using a bit of plugin magic.

> Not tested, but something like this should work
```js
const setRemainingErrorsPlugin = (node) => {
  if (node.props.type !== 'form') return;

  node.hook.setErrors((payload, next) => {
    const childErrors = {};
    
    node.children.forEach((n) => {
      if (!payload.childErrors[n.name]) return;

      childErrors[n.name] = payload.childErrors[n.name];
      delete payload.childErrors[n.name];
    });
    
    return next({ localErrors: [...payload.localErrors, Object.values(payload.childErrors)] , childErrors });
  });
};
```

**Comment by dakujem** [comment]
Thanks for the suggestion, I'll give it a try and report back.
