### ISSUE TITLE
Tailwind support for custom inputs

### ISSUE THREAD

**Issue by chemeng** [formkit/formkit#291]
### Describe the feature

I'm trying to create an `autocomplete` input component using the example here: https://formkit.com/advanced/custom-inputs#autocomplete-input

I'm also using tailwind css and created successfully a configuration that works great for the standard formkit inputs. However, I haven't been able to figure out how I can use tailwind classes with my custom component. It looks like no matter how I define the "type" of the component, no tailwind classes are automatically mapped and added to the formkit elements.

This is how a custom and a standard element are rendered:
```
<div class="formkit-wrapper">
   <label for="input_0" class="formkit-label">Address lookup</label>
   <div class="formkit-inner">
      <!---->test<!---->
   </div>
</div>
<div id="help-input_0" class="formkit-help text-xs text-gray-500">What location are you looking for?</div>
<!----></div>
<div class="formkit-outer mb-5 formkit-disabled:opacity-50" data-type="text">
   <div class="formkit-wrapper">
      <label for="input_1" class="formkit-label block mb-1 font-bold text-sm formkit-invalid:text-red-500">Your username</label>
      <div class="formkit-inner max-w-md
         border
         border-gray-400
         formkit-invalid:border-red-500
         rounded-lg
         mb-1
         overflow-hidden
         focus-within:border-blue-500">
         <!----><input type="text" class="formkit-input w-full h-10 px-3 border-none text-base text-gray-700 placeholder-gray-400" name="text_2" id="input_1" aria-describedby="help-input_1"><!---->
      </div>
   </div>
   <div id="help-input_1" class="formkit-help text-xs text-gray-500">Pick a username people will remember!</div>
   <!---->
</div>
</div>
```

Is that something currently supported?

**Comment by GustavoFenilli** [comment]
do you have a reproduction so we could see how are you setting those?

**Comment by chemeng** [comment]
@GustavoFenilli thank your for the quick follow up. 

Here is a quick repro: https://stackblitz.com/edit/vitejs-vite-7dk1xz

**Comment by GustavoFenilli** [comment]
I think the problem comes down to using a "one time" input like you did with `:type="autocomplete"`, so instead you can globaly enable it using the `inputs: { autocomplete }` so the generateClasses does know about it when generating the classes.

Here are the changes to make it work https://stackblitz.com/edit/vitejs-vite-seq2eh?file=formkit.config.js

**Comment by chemeng** [comment]
Great, this is even better. Thanks a lot!
