### ISSUE TITLE
using v-model on type form unable to submit on mounted

### ISSUE THREAD

**Issue by davideapvd** [formkit/formkit#292]
### Reproduction

https://formkit.com/playground?files=JTVCJTdCJTIybmFtZSUyMiUzQSUyMmZvcm0tc3VibWl0LnZ1ZSUyMiUyQyUyMmVkaXRvciUyMiUzQSUyMiUzQ3NjcmlwdCUyMHNldHVwJTNFJTVDbmltcG9ydCUyMCU3QiUyMHJlZiUyQyUyMG9uTW91bnRlZCUyMCU3RCUyMGZyb20lMjAndnVlJyU1Q25jb25zdCUyMGZvcm0lMjAlM0QlMjByZWYoJTdCJTdEKSU1Q25jb25zdCUyMGRhdGElMjAlM0QlMjByZWYoJTdCJTVDbiUyMCUyMGVtYWlsJTNBJTIwJ2FzZGYlNDBhc2RmLml0JyU1Q24lN0QpJTVDbmZ1bmN0aW9uJTIwc3VibWl0VG9NYWlsY2hpbXAoZGF0YSklMjAlN0IlNUNuJTIwJTIwYWxlcnQoJTYwU3VibWl0dGVkJTIwJTI0JTdCZGF0YS5lbWFpbCU3RCUyMHN1Y2Nlc3NmdWxseSElNjApJTVDbiU3RCU1Q24lMjAlMjAlNUNub25Nb3VudGVkKCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHNldFRpbWVvdXQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwJTIwJTIwZm9ybS52YWx1ZS5ub2RlLnN1Ym1pdCgpJTVDbiUyMCUyMCU3RCklNUNuJTdEKSU1Q24lM0MlMkZzY3JpcHQlM0UlNUNuJTVDbiUzQ3RlbXBsYXRlJTNFJTVDbiUyMCUyMCUzQ0Zvcm1LaXQlNUNuJTIwJTIwJTIwJTIwdHlwZSUzRCU1QyUyMmZvcm0lNUMlMjIlNUNuJTIwJTIwJTIwJTIwcmVmJTNEJTVDJTIyZm9ybSU1QyUyMiU1Q24lMjAlMjAlMjAlMjB2LW1vZGVsJTNEJTVDJTIyZGF0YSU1QyUyMiU1Q24lMjAlMjAlMjAlMjBpZCUzRCU1QyUyMm5ld3NsZXR0ZXIlNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTNBYWN0aW9ucyUzRCU1QyUyMmZhbHNlJTVDJTIyJTVDbiUyMCUyMCUyMCUyMCU0MHN1Ym1pdCUzRCU1QyUyMnN1Ym1pdFRvTWFpbGNoaW1wJTVDJTIyJTVDbiUyMCUyMCUzRSU1Q24lMjAlMjAlMjAlMjAlM0NGb3JtS2l0JTVDbiUyMCUyMCUyMCUyMCUyMCUyMHR5cGUlM0QlNUMlMjJlbWFpbCU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBuYW1lJTNEJTVDJTIyZW1haWwlNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwdmFsaWRhdGlvbiUzRCU1QyUyMnJlcXVpcmVkJTdDZW1haWwlNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwbGFiZWwlM0QlNUMlMjJFbWFpbCUyMGFkZHJlc3MlNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwaGVscCUzRCU1QyUyMldoYXQlMjBlbWFpbCUyMGFkZHJlc3MlMjBzaG91bGQlMjB3ZSUyMHNlbmQlMjBvdXIlMjBuZXdzbGV0dGVyJTIwdG8lM0YlNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTJGJTNFJTVDbiUyMCUyMCUzQyUyRkZvcm1LaXQlM0UlNUNuJTIwJTIwJTNDcCUzRVRoaXMlMjBidXR0b24lMjBpcyUyMG5vdCUyMHBhcnQlMjBvZiUyMHRoZSUyMGFib3ZlJTIwZm9ybSUzQSUzQyUyRnAlM0UlNUNuJTIwJTIwJTNDIS0tJTIwJUYwJTlGJTkxJTgwJTIwTG9vayUyQyUyMHRoaXMlMjBpcyUyMG5vdCUyMHBhcnQlMjBvZiUyMHRoZSUyMGZvcm0uJTIwLS0lM0UlNUNuJTVDbiUzQyUyRnRlbXBsYXRlJTNFJTVDbiUyMiUyQyUyMmFkZGVkJTIyJTNBdHJ1ZSU3RCU1RA&css-framework=genesis&fkv=1.0.0-beta.8&fileTab=form-submit.vue&imports=JTdCJTIybmFtZSUyMiUzQSUyMkltcG9ydE1hcCUyMiUyQyUyMmVkaXRvciUyMiUzQSUyMiU3QiU1Q24lMjAlMjAlNUMlMjJ2dWUlNUMlMjIlM0ElMjAlNUMlMjJodHRwcyUzQSUyRiUyRmNkbi5qc2RlbGl2ci5uZXQlMkZucG0lMkZ2dWUlNDAzJTJGZGlzdCUyRnZ1ZS5lc20tYnJvd3Nlci5taW4uanMlNUMlMjIlNUNuJTdEJTVDbiUyMiU3RA

### Describe the bug

I would like to prefill the form with data, and automatically submit the form, leveraging the internal validation, so I created a ref and put it on v-model on the form, like this

```
<FormKit
    type="form"
   ref="form"
    v-model="data"
>
```

now in the onMounted hook of the component I would like to do `form.value.node.submit()`, the thing is that it doesn't work, for it to work I need to wrap the submit inside a setTimeout (line 12 of the repro).

is this expected behaviour?

### Environment

any

**Comment by justin-schroeder** [comment]
Fair question, its sort of working as intended but I agree its a bit counter intuitive. When you call submit() immediately on mounted, the values have already been hydrated, but the validation rules have not yet completed. Technically in that precise moment on your example, the `required` rule has not finished re-evaluating from the v-model value that was applied to the `email` input so when you try to submit it blocks you.

A timeout is a fine way to handle this in the short term but I'm going to keep this open to see if there isn't a way to make that behave more inline with expectations in the future.

**Comment by davideapvd** [comment]
Hello @justin-schroeder thank you for your answer; ok I'll stick with setTimeout in the meantime.
