### ISSUE TITLE
List index stability improvements

### ISSUE THREAD

**Issue by jhillacre** [formkit/formkit#293]
### Describe the feature

Had a discussion with @GustavoFenilli on the formkit discord where I was asking about not being able to remove items using `Array#splice`. (starting here: https://discord.com/channels/793529058377072650/940340536747896842/988938273785249912)

He was able to link me a previous answer to the same question within the discord. In that answer, @justin-schroeder had suggested using `Node#destroy` to remove children by index. @GustavoFenilli also linked to the examples page where removal is done via replacing the array with the results of a `Array#filter`.

I think the documentation could help folks skip the discord on this question with some additional documentation on this issue.

1. Under the performance call out box on the [list input page](https://formkit.com/inputs/list), regarding "Vue’s handy v-model is fully supported in FormKit with bi-directional data flow even on lists and groups.", a warning call-out box could describe a caveat to this support regarding using array mutation to remove items. As a start, that call out could look something like:
   
    > ## Warning
    >
    > There is an issue with mutation of list arrays to remove items from lists that causes an infinite chain of effects. This is related to removal of an array item from the v-model side looks the same as adding a new item from the v-for loop side for the effects involved. Instead of mutating the array via `Array#splice`, use `Array#filter` to remove the undesired items and replace the existing array. See [Using a list to repeat an input](https://formkit.link/b7cc2c4ae2b02807065d6617ead62783) from the examples page.

2. Using `Node#destroy` method was suggested as a solution. Searching the documentation for 'destroy' yields no results. This method should be documented if it is desired for formkit users to call this method.

**Comment by jhillacre** [comment]
After submitting this issue and going back to implement in my own project, I realized that removal of items requires `Node#destroy`. Replacing the array for me still leads to infinite effects, as in this updated playground example: https://formkit.link/4d598469befcaec7d8d0a3c61cf432f2. Not sure if this is related to using a list of groups, using v-model to populate at the form level rather than at a list level, or how I am iterating the groups from the list.

**Comment by GustavoFenilli** [comment]
You need to remove the group before you remove the value, otherwise the group is still there to populate the field.
if you call your `removeSignDestroy(sign)` inside the `removeSignFilter` it should work fine.

**Comment by jhillacre** [comment]
> You need to remove the group before you remove the value, otherwise the group is still there to populate the field. if you call your `removeSignDestroy(sign)` inside the `removeSignFilter` it should work fine.

Seems like `removeSignDestroy` works to remove items from the `formValues` without help from `removeSignFilter`.

**Comment by justin-schroeder** [comment]
Most of these issues should now be well resolved by using the dynamic lists feature.
