### ISSUE TITLE
@change not firing for FormKit  type="checkbox" with more than one checkbox (via :options)

### ISSUE THREAD

**Issue by leprincehector** [formkit/formkit#294]
### Reproduction

https://formkit.link/9aa364fbcdd477b594889267a6f00f7f

### Describe the bug

 <FormKit  type="checkbox"  
with one single checkbox @input and @change will fire when the selection changes.  However, if using more than one checkbox using options like :options="['uno','dos']" then @change will no longer fire.

See the console output on the  FormKit Playground link provided above.

### Environment

MacOS
Chrome and Safari
Formkit version beta 7, 8 and 9.

**Comment by justin-schroeder** [comment]
`@change` is not a supported event at this time, we recommend using `@input`. Supported events are:

`@input`, `@input-raw`, and `@node`.

https://formkit.com/essentials/inputs#events

If you think there is some nuance in the `@change` event that should be supported feel free to let us know. Thanks 👍
