### ISSUE TITLE
Mask input field for id or phone?

### ISSUE THREAD

**Issue by hermesalvesbr** [formkit/formkit#296]
Hi there, this feature already exists?

Input form mask field for custom models? Like document Id and phone number?

**Comment by hermesalvesbr** [comment]
Thanks for responding. This roadmap is public?

**Comment by luan-nk-nguyen** [comment]
It is not currently but we plan to release a public roadmap soon!

**Comment by CavalcanteLeo** [comment]
any plan to release it?

**Comment by chemeng** [comment]
would this include support for money formats as well? like 300.000,31 ?

**Comment by chemeng** [comment]
any updates on this?

**Comment by GustavoFenilli** [comment]
Mask is still not a feature, the team is working a lot to have the pro inputs delivered.

**Comment by bilalmalkoc** [comment]
Waiting for the mask update :) thanks.

**Comment by justin-schroeder** [comment]
Good news @hermesalvesbr, @CavalcanteLeo, @chemeng, and @bilalmalkoc — the mask input has been released. You can check it out here: https://formkit.com/inputs/mask
