### ISSUE TITLE
Radio and Select extra option added on Safari < 13 

### ISSUE THREAD

**Issue by totalhack** [formkit/formkit#299]
### Reproduction

https://github.com/totalhack/formkit-starter

### Describe the bug

On somewhat older versions of Safari, such as Safari 12 which is on my 2017 Macbook Pro, it seems an extra option is added to radio and select inputs. This does not happen in Safari 13 or any recent versions of Chrome/Firefox. I searched and could not find any particular issue or bug report for Safari < 13 that would explain this, so I'm thinking this could be a formkit issue. 

The radio in the demo app is defined as follows, with two options:

```javascript
        <FormKit
          name="opinion"
          label="Opinion"
          help="How excited are you about FormKit?"
          type="radio"
          value="A lot"
          :options="['A little', 'A lot']"
        />
```

But it renders html like this, with a third blank option added:

```html
<ul class="formkit-options">
   <li class="formkit-option">
      <label class="formkit-wrapper">
         <div class="formkit-inner">
            <!----><input type="radio" class="formkit-input" name="opinion" id="opinion-option-a-little" value="A little"><span class="formkit-decorator" aria-hidden="true"></span><!---->
         </div>
         <span class="formkit-label">A little</span>
      </label>
      <!---->
   </li>
   <li class="formkit-option">
      <label class="formkit-wrapper">
         <div class="formkit-inner">
            <!----><input type="radio" class="formkit-input" name="opinion" id="opinion-option-a-lot" value="A lot"><span class="formkit-decorator" aria-hidden="true"></span><!---->
         </div>
         <span class="formkit-label">A lot</span>
      </label>
      <!---->
   </li>
   <li class="formkit-option">
      <label class="formkit-wrapper">
         <div class="formkit-inner">
            <!----><input type="radio" class="formkit-input" name="opinion"><span class="formkit-decorator" aria-hidden="true"></span><!---->
         </div>
         <!---->
      </label>
      <!---->
   </li>
</ul>
```

The "modeled group values" output also shows an unusual value, note the `__init` key being set which doesn't happen in normal behavior:

```
{
  "__init": true,
  "opinion": "A lot"
}
```

Why do I need Safari 12 to work? I'm trying to use formkit in a scenario where I will use the standard module/nomodule pattern to load my "modern" bundle in all [browsers that support es6 modules](https://caniuse.com/es6-module) and a more heavily polyfilled bundle to the `nomodule` browsers. Safari 12 is in the group that supports es6 modules and something I would consider modern enough that it probably should work. Even with polyfills to match es6+ browsers it doesn't seem to work.

The reproduction link is a copy of of the [formkit starter project](https://github.com/formkit/formkit-vue-starter-project) with some modifications to the postcss behavior and a vite target of `es6` to get things close to working in Safari 12. This "extra item" bug is the only thing preventing this from working that I've found.

Thanks for taking a look.

### Environment

• OS: Mac OS
• Browser: Safari
• Version: < 13

**Comment by justin-schroeder** [comment]
Very odd. I dont see any reason why that shouldn't work — the `__init` is actually always there in values, but its added as a non-enumerable property, so in general you shouldn't see it — maybe a polyfill is clobbering that somehow? I dont have a readily available mac with safari 12 so it might be a bit before i can dig into this one.

**Comment by totalhack** [comment]
The reproduction repo actually doesn't have any polyfills -- I have those in another private project that is also seeing the issue on "module" and"nomodule" bundles. The vite build target of es6 only does some syntax transforms [according to their docs](https://vitejs.dev/guide/build.html#browser-compatibility). 

Yea I wish I could give you an easier way to reproduce this on your end besides relying on a tool like Browserstack. I'd just ignore it but these kinda-old browsers still generate enough traffic as to be a meaningful revenue impact for the client.

**Comment by totalhack** [comment]
I actually just noticed that selection of the radio options doesn't work either. I missed that because I was using a prepop plugin in another project, which does effectively set the value, but selecting in the browser has no effect.

**Comment by justin-schroeder** [comment]
hmmmph. I'm able to reproduce the super strange "new radio", on Safari <= 12 but I am able to select using the browser without any issues.

**Comment by totalhack** [comment]
To clarify, it selects and graphically displays it as selected in the browser, but it does not update/set the value in the model and therefore does not pass validation such as `required`.

**Comment by justin-schroeder** [comment]
Hm, it does on mine, for 12.1 with the same repo you posted

**Comment by justin-schroeder** [comment]
Was able to identify the extra option issue. I have not been able to duplicate any non-selection issues. Checking why __init isn't being hidden. that might be unavoidable.

**Comment by justin-schroeder** [comment]
I think the fact that the `__init` is being output is some artifact of how old safari iterates or serializes, but it shouldn't cause the form to not work. I'm going to mark this is release ready for beta 9, but if there are further reproducible issues, always happy to squash any issues.

**Comment by totalhack** [comment]
Thanks @justin-schroeder. I'll retest once this is released and let you know if I still hit the radio click issue. I can also work around `__init` with some filtering before posting if needed.
