### ISSUE TITLE
Disabled checkboxes don't appear to re-enable

### ISSUE THREAD

**Issue by zerbash** [formkit/formkit#307]
Genesis Theme: If a start a checkbox out with disabled="true" it is indeed disabled. Changing the disabled attribute to false re-enables the checkbox, but the opacity is set on [data-disabled], not [data-disabled=true], so it _appears_ to remain disabled.

FormKit Vue Playground link:
https://formkit.link/d9ffc4ede9e68a31286dda2650dd17f0

**Comment by justin-schroeder** [comment]
This is worth working out so i'll tag it for a future version, but the solution is to use a nullish value:

https://formkit.link/759e6b91156d9efb17a60959c3e0ecef

Thanks for the report!
