### ISSUE TITLE
Checkbox and radio do no longer show a help text

### ISSUE THREAD

**Issue by dominikklein** [formkit/formkit#310]
### Reproduction

https://formkit.link/7d1e5f904302e39b6ff918963b051400

### Describe the bug

After the update to beta 9 the checkbox and radio field do not longer show the help text.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
Geez, thats an unfortunate regression. We rewrote all the inputs in beta.9 so not entirely unsurprising, but still too bad. Thanks for catching it. It's been fixed in beta.10 and published on the `@next` tag.\

https://formkit.link/8069ff0fa62186dd3e3370a02b1020c1
