### ISSUE TITLE
[FormKit Schemas] Conditional Options in Select Inputs don't work with Value/Label Arrays

### ISSUE THREAD

**Issue by lupas** [formkit/formkit#317]
### Reproduction

https://formkit.link/45372b58b9085a12485dfbb868c06c18

### Describe the bug

# Description

FormKit Schemas and conditional options in select inputs don't seem to be parsing the options correclty if provided as value/label arrays.

It works when I am using conditional objects as string arrays, but not when I use them as array of value/label objects.

Working:
https://formkit.link/ed394dc69094cc223179abdef1a6ed92
Not working:
https://formkit.link/45372b58b9085a12485dfbb868c06c18

As discussed with @justin-schroeder this looks like its somehow interpreting it incorrectly: 
https://discord.com/channels/793529058377072650/940340536747896842/995048809941966858

<img width="601" alt="Screenshot 2022-07-08 at 21 42 29" src="https://user-images.githubusercontent.com/4020037/178059941-9a8902f2-6318-4117-b504-a0b9e8f8ed36.png">

# Workaround
This seems to work for now:
https://formkit.link/97175d1b55f32fd1a937cc09b9aaaf48

### Environment

• Version [Beta 8](https://github.com/formkit/formkit/releases/tag/1.0.0-beta.8)

**Comment by justin-schroeder** [comment]
This is fixed in the latest @next release (will be released in beta.10)
