### ISSUE TITLE
Unhandled error during execution of watcher callback when changing select

### ISSUE THREAD

**Issue by nyambe** [formkit/formkit#318]
### Reproduction

https://formkit.link/abcb3b13f8a629e184a0b42da942b95f

### Describe the bug

Steps to reproduce
Select: Enlace a contenido interno, if Radio: Select any of the options

Re Select another option: Enlace a contenido externo

What is expected?
Radio Options to go away since they do not meet current filter

What is actually happening?
You get a warning. The radio options remain

Unhandled error during execution of watcher callback

### Environment

System:
    OS: macOS 11.5.2
    CPU: (8) arm64 Apple M1
    Memory: 103.81 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Safari: 14.1.2
  npmPackages:
    vue: ^3.2.29 => 3.2.31

**Comment by justin-schroeder** [comment]
You just need to slap some keys on it and you're all good: https://formkit.link/196810f8ad5e0cbc0a05101f99587d2a
