### ISSUE TITLE
Reset set File Input value to undefined, when it should reset to an empty list

### ISSUE THREAD

**Issue by OrIOg** [formkit/formkit#319]
### Reproduction

https://formkit.link/24b3c799ffb7ca74fe6d3c398476a90a

### Describe the bug

When using reset on a node which is a File input. The value is **undefined**. Making the input render weirdly.
By default a File Input should be  an empty list

### Environment

• OS: Ubuntu 20.04.4 LTS
• Browser: Firefox 102.0 64bits
• Version: "@formkit/vue": "^1.0.0-beta.9"

**Comment by justin-schroeder** [comment]
Thanks! Appreciate the reproduction and the quality bug report.
