### ISSUE TITLE
State value from form 

### ISSUE THREAD

**Issue by Dezek85** [formkit/formkit#322]
### Describe the feature

<FormKit
    type="form"
    :actions="false"
    #default="{ state: { valid } }"
    v-model="data"
  >
<FormKitSchema :schema="models" :data="data" />
    <pre wrap>Form validity: {{ valid }}</pre>
  </FormKit>

How to get valid state and emit value to parent ? 
watch doesn't work , and change event too
Form validity: {{ valid }} show the good value but impossible to send at the parent.

**Comment by justin-schroeder** [comment]
Hi @Dezek85 👋

Quick tip: In the future, please ask your "how to" questions in [Discord](https://discord.gg/Vhu97pAC76).

You can also access the validity state by accessing the core node — this can be done from anywhere: 

https://formkit.link/43eb672856d6bb94a0c44c6dc575aa73
