### ISSUE TITLE
Passing custom function to formkit

### ISSUE THREAD

**Issue by Bassonlinho** [formkit/formkit#323]
Hello, I'd like to know how to pass custom function that gets emitted to the wrapper component I have in Formkit.
If I use markup it works and I can pass my function easy
like this
<FormKit v-bind="args" v-model="phone"
validation="isPhoneValid"
:validation-rules="{ isPhoneValid }"
validation-visibility="live" @ validate="validate"
But I would like to pass it with schema as well, is it possible?
Thanks in advance!

**Comment by justin-schroeder** [comment]
There is no validate event. Events are available here: https://formkit.com/essentials/inputs#events

Validation is never "triggered" in FormKit, it is always being computed deterministically so developers can use a declarative syntax. If there's a specific use case you'd like help with, please jump into the [Discord](https://discord.gg/Vhu97pAC76) and I'm sure someone would be happy to help out 👍
