### ISSUE TITLE
When is the repeater going to be available?

### ISSUE THREAD

**Issue by ivan006** [formkit/formkit#329]
### Describe the feature

When is the repeater going to be available?

**Comment by ivan006** [comment]
apparently next moth or so

**Comment by edwardsf** [comment]
Do you have a recommendation in advance of the repeater field being ready? Use case is the ability for a user to add _n_ staff members with various property attributes such as Name, Title, Role.

**Comment by luan-nk-nguyen** [comment]
Hi @edwardsf — our roadmap is here: https://formkit.com/about. The repeater will be released with the first batch of Pro Inputs, which we're hoping to release by the end of Q3, 2022 (Sep 30).

In the meantime, you can build your own repeater with the existing primitives! Here's an example: https://formkit.link/b7cc2c4ae2b02807065d6617ead62783 which you can also find on the [examples page](https://formkit.com/essentials/examples).

**Comment by Vivek-Hotti** [comment]
@luan-nk-nguyen Thanks for the example, was super helpful.
