### ISSUE TITLE
How to adapt imported component like native component

### ISSUE THREAD

**Issue by Dezek85** [formkit/formkit#332]
### Describe the feature

I used schema component like this 

`{
    $formkit: 'checkbox',
    name: 'modules',
    label: 'Accès aux modules',
    options: ['test1', 'test2', 'test3', 'test4'],
    classes: {
      outer: 'new-outer-class',
    },
  },`

I was getting this 
<img width="450" alt="Capture d’écran 2022-07-19 à 15 43 47" src="https://user-images.githubusercontent.com/109215170/179766310-aef87e33-11f1-46e3-a473-c0a81c9bcdd4.png">

And now I import my component named CheckboxInput

`{
    $formkit: CheckboxInput,
    name: 'modules',
    label: 'Accès aux modules',
    options: ['test1', 'test2', 'test3', 'test4'],
    classes: {
      outer: 'new-outer-class',
    },
  },`

And my component :

import {
  outer,
  inner,
  help,
  boxHelp,
  messages,
  message,
  prefix,
  suffix,
  fieldset,
  decorator,
  box,
  legend,
  boxOption,
  boxOptions,
  boxWrapper,
  boxLabel,
  options,
  checkboxes,
  $if,
  $extend,
} from '@formkit/inputs'

/**
 * Input definition for a checkbox(ess).
 * @public
 */
export const CheckboxInput = {
  /**
   * The actual schema of the input, or a function that returns the schema.
   */
  schema: outer(
    $if(
      '$options == undefined',
      /**
       * Single checkbox structure.
       */
      boxWrapper(
        inner(prefix(), box(), decorator(), suffix()),
        $if('$label', boxLabel('$label'))
      ),
      /**
       * Multi checkbox structure.
       */
      fieldset(
        legend('$label'),
        help('$help'),
        boxOptions(
          boxOption(
            boxWrapper(
              inner(
                prefix(),
                $extend(box(), {
                  bind: '$option.attrs',
                  attrs: {
                    id: '$option.attrs.id',
                    value: '$option.value',
                    checked: '$fns.isChecked($option.value)',
                  },
                }),
                decorator(),
                suffix()
              ),
              $if('$option.label', boxLabel('$option.label'))
            ),
            boxHelp('$option.help')
          )
        )
      )
    ),
    // Help text only goes under the input when it is a single.
    $if('$options.length === 0 && $help', help('$help')),
    messages(message('$message.value'))
  ),
  /**
   * The type of node, can be a list, group, or input.
   */
  type: 'input',
  /**
   * An array of extra props to accept for this input.
   */
  props: ['options', 'onValue', 'offValue'],
  /**
   * Additional features that should be added to your input
   */
  features: [options, checkboxes],
}

But 
<img width="450" alt="Capture d’écran 2022-07-19 à 15 42 38" src="https://user-images.githubusercontent.com/109215170/179767076-2c2b5f23-0411-4703-9ea7-2414de63ff83.png">

I don't know how to adapt this checkbox Component

**Comment by justin-schroeder** [comment]
@Dezek85 beta.10 (installable with the `@next` tag) has a solution to this with `forceTypeProp` in the input definition. Going forward this will be included by default in exported inputs. You can see this working in beta.10 here (and see it broken in beta.9 if you switch the version back down): https://formkit.link/a80a3ed8ddb16d6eb926c9a744d1590e

I'll add this as "release ready" in for beta.10
