### ISSUE TITLE
Better Date Inputs

### ISSUE THREAD

**Issue by totalhack** [formkit/formkit#333]
### Describe the feature

The regular html date inputs have some ugly limitations, such as the lack of placeholder control, only the little calendar icon being clickable on Chrome desktop, no placeholder shows at all on chrome mobile, and it falls back to a basic text input on some browsers like Safari < 14.1. 

Since it's such an important/common input I was wondering if you guys had any plans to release an improved date picker as part of FormKit. A quick google search yields a couple Vue 3 date picker libraries I could experiment with and try to input as a custom FormKit input, but if there is anything built-in coming down the road, or someone has already solved this problem with a custom FormKit input, I'd be interested in that.

Thanks!

**Comment by totalhack** [comment]
I got a basic example working with [Vue 3 Datepicker](https://icehaunter.github.io/vue3-datepicker/) using a custom input that seems to have better behavior than html 5 date inputs...but it adds 70kb to my (unzipped) bundle size! I'll live with this until FormKit hopefully packs a better batteries-included solution, and will leave this open until there is a conclusion on that. 

Below is what I have for reference, though I'm omitting some custom styles and tailwind settings, just showing the general structure of how to use a custom date input with a schema-driven approach:

```javascript
// main.js
import { defaultConfig, createInput } from '@formkit/vue'
// ... stuff omitted
import DatePicker from './components/DatePicker.vue'

// ...Down in the Vue createApp call which fits my use case
      defaultConfig({
        inputs: {
          DatePicker: createInput(DatePicker)
        }
      })
```

```html
<! -- DatePicker.vue -->
<template>
  <datepicker
    v-model="picked"
    :upperLimit="new Date()"
    placeholder="Select a date"
  />
</template>

<script setup>
import Datepicker from 'vue3-datepicker'
import { watch, ref } from 'vue'
const picked = ref()

const props = defineProps({
  context: Object
})

watch(picked, (newValue, oldValue) => {
  const offset = newValue.getTimezoneOffset()
  newValue = new Date(newValue.getTime() - (offset * 60 * 1000))
  newValue = newValue.toISOString().split('T')[0]
  props.context.node.input(newValue)
});
</script>
```

Then reference "DatePicker" in the schema. I expected this to work via `$cmp` when I first read the docs but it didn't and was surprised to see this worked...maybe because of the way I registered the component. Note that I prefix tailwind classes with `t-`.

```json
                      {
                        "$formkit": "DatePicker",
                        "validation": "required",
                        "validationMessages": {
                          "required": "Field is required"
                        },
                        "labelClass": "required t-block t-mb-3 t-font-semibold t-text-base formkit-invalid:t-text-red-500",
                        "innerClass": "t-border t-border-gray-400 formkit-invalid:t-border-red-500 t-rounded t-mb-1 focus-within:t-border-blue-500",
                        "label": "Date:",
                        "name": "date",
                      },
```

I also had to apply some style overrides (there is likely a better way to pass these to Vue 3 Datepicker but the docs are thin):

```css
.v3dp__input_wrapper input {
    /* Similar to Tailwind settings I was trying to use for date input */
    width: 100%;
    height: 2.5rem;
    padding-left: 0.75rem; /* 12px */
    padding-right: 0.75rem; /* 12px */
    border-style: none;
}
```

**Comment by justin-schroeder** [comment]
I think your wrapper looks totally fine to be honest, and to answer the larger question — yes we probably will release some first-party date picker inputs as well as date-range inputs, although likely not for browser support reasons and instead for use cases where native inputs don't provide enough nuanced capability.

The reality is we should all try to adopt native inputs as rapidly as possible when possible since it provides the most accessible and native experience possible. The native experience of the date picker (especially on mobile) is much better than nearly all synthetic date pickers. So I think we would prefer to see the > 99% of users get the best experience rather than degrade the experience of the picker for all but the < 0.3% who are still using an unsupported browser.

Now that said, I think the way you wrapped the date-picker input is top notch and is a great example of falling back to alternatives too. Well done 👍

**Comment by totalhack** [comment]
I'm not overly concerned with older browsers in this case, though Safari <= 14.1 is already 1% of users so I thought it was worth mentioning. 

The native experience is inconsistent and can have bad UX or missing features in some very high usage browsers. Notably the lack of placeholder control (or no placeholder at all on chrome mobile) and the entire input not being clickable to open the calendar (chrome desktop). There are some browser-specific hacks that can be added to work around some of this but that's not desirable/reliable. 

I look forward to seeing what you guys add! My workaround is temporary as I continue trying to get formkit to match the conversion performance of a previous solution. The native date inputs were the last major variable, but I don't plan to live with the doubled form bundle size forever.
