### ISSUE TITLE
HTML in labels

### ISSUE THREAD

**Issue by aristid** [formkit/formkit#334]
Hello, what is a proper way to include a link in a checkbox label? Use case: "I accept _terms and conditions_" Is it possible to put HTML there? Thank you!

**Comment by luan-nk-nguyen** [comment]
Hi @aristid! Here are 2 ways you can do it: https://formkit.link/a8ed01530d62d03187a6d93539da562a

Also, feel free to ask these "how-tos" in the [Discord](https://discord.gg/Vhu97pAC76)

**Comment by aristid** [comment]
Thank you very much!
> Also, feel free to ask these "how-tos" in the [Discord](https://discord.gg/Vhu97pAC76).
Will do!

**Comment by willans** [comment]
Is it possible to do the above, but within a form schema? Stand alone example works fine, but label appears as `[object Object]` when part of schema.
