### ISSUE TITLE
When the field to be modified is undefined, the value will not be updated normally after triggering the change

### ISSUE THREAD

**Issue by YqngQB** [formkit/formkit#335]
### Reproduction

https://formkit.link/527be27f177fd40563dcda50a509f01c

### Describe the bug

When the field to be modified is undefined, the value will not be updated normally after triggering the change

### Environment

• Browser [chrome]
• Version [1.0.0-beta.9]

**Comment by justin-schroeder** [comment]
Beta 10 fixes this now by deferring the change event till _after_ the input event.
