### ISSUE TITLE
Only inputs on the first level can be set to node setErrors

### ISSUE THREAD

**Issue by misaon** [formkit/formkit#336]
### Reproduction

sample below

### Describe the bug

If I define a `form` and a `group` in it. I don't have the possibility to set error messages to inputs embedded in the group via `node.setErrors(...)`.

I tried to set setErrors via:
```js
<my-form-instance>.node.setErrors({
  <my-group-name>: {
    firstName: 'Test error message'
  }
})
```

but the tread doesn't work. It is probably due to the logic in the `createMessages` method, which counts on assigning error messages only to first level inputs.

### Environment

• OS: Linux
• Browser Chrome (beta)
• Version 1.0.0-beta.10-54f014c

**Comment by justin-schroeder** [comment]
Keys should be a flat object and use dot-notation, as specified here https://formkit.com/essentials/forms#input-errors and linked to here https://formkit.com/advanced/core#traversal:

So:

```js
formNode.setErrors({
  'topLevelInputName': ['error1, 'error2'],
  'groupName.inputName': 'deep error'
})
```

**Comment by misaon** [comment]
Sorry, i’ll try ❤️
