### ISSUE TITLE
I get a literal string "undefined" when reading data through $_POST with PHP for empty text fields

### ISSUE THREAD

**Issue by guyinpv** [formkit/formkit#340]
### Reproduction

cantuseplaygroundforphpsubmission.com

### Describe the bug

I hesitate putting this as a bug versus a feature, but it feels buggish to me.

In my setup, I'm using Vue3 + Vite + FormKit 1.0.0-beta.9 + Axios + options API.

I'm using the FormData() object when submitting data to a PHP backend as part of WordPress. Something like this for the submission method:
```
submitMyForm: function(data) {
      var fd = new FormData()
      for (var key in data) {
        fd.append(key, data[key])
      }
      axios.post(myajaxurl, fd)
          .then(response => {
            this.postResponse = response.data.message
          })
          .catch(error => {
            this.postResponse = error
          })
    },
```
Note that I'm using FormData() due to some other issue a while back with the multipart formdata encoding, it wasn't submitting the data right without doing this.

The problem is that when a text field is left empty (a textarea to be exact), and then I go to read the submitted data in the PHP `$_POST` global, the empty field comes through as a literal string with the text "undefined" in it. Note this is not an undefined data type, it's a string type that has the literal word "undefined" in it. Here is the output of doing `var_dump($_POST);`:
```
array(18) {
  ["UserMessage"]=>
  string(9) "undefined"
  ["Company"]=>
  string(4) "blah"
  ["FirstName"]=>
  string(3) "boo"
  ["LastName"]=>  .......
```

As you can see, it sends a string rather than empty text like I would get using a normal HTML form.
This can be more or less verified in the playground but you have to submit the data to the console since we can't actually do a full POST and get the data in PHP using the playground, but you CAN see that the empty fields are submitted and end up as `undefined` data types. 
Somewhere along the line, the JS undefined value is being converted to literal string text.

If this is not a bug, then somewhere in JS or Axios or FormData() or FormKit or Vue/Vite or somewhere, the empty/undefined text field from FormKit submission is being converted to a literal string, and I don't know where/how that happens.

In my opinion, an empty text field should just stay as an empty string, just as we'd expect from a normal HTML form. 

If there is some trick to avoid this conversion, I didn't find it in the docs. I don't see a config variable or anything like that for "empty string default values" etc.

My input field looks like this:
`<FormKit type="textarea" name="UserMessage" placeholder="How can we help?" rows="4" maxlength="5000" />`
There is no validation so I don't think anything is getting in the way. I'm not doing any fancy custom code or plugins/addons to FormKit, it's all pretty basic right off the docs setup.

Thanks!

### Environment

Ubuntu server with CyberPanel/Litespeed
Chrome
1.0.0-beta.9
Vue3
Vite
Axios
Options API

**Comment by guyinpv** [comment]
After troubleshooting more, I found that FormKit passes the data to the submission handler with those empty text fields as `undefined` values rather than empty text strings or null or whatever else.

My workaround was to simply test appropriate fields for `typeof == 'undefined'` and then set it to empty string instead.

I still kinda feel like this is buggy. Can anyone explain why you would want any fields in your form to submit as `undefined`? The normal behavior of an HTML form is to submit something, even null, or mostly empty strings, which can be tested from a PHP backend. The usual way to grab a value might be:
`$myvar = $_POST['something'] ?: "--a default--";`
The "elvis" operator `?:` would check against anything falsey, and under normal circumstances, all HTML fields would be in the $_POST and this would work, assuming you don't expect falsey values normally.
Another one is null coalesce using `??` which might work in other situations where the POST value doesn't exist or is null. But neither of these two handle 'undefined' or in this case a standard text string that has the word "undefined" in it. I don't even think you can receive an undefined value through POST variables, so I'm still not sure what's the typical workflow to avoid undefined values from the form.

**Comment by justin-schroeder** [comment]
I'll take a stab at it — `undefined` values are not included when you do a `JSON.stringify()`. Most form submissions from FormKit will be XHR/Fetch requests with a JSON body — although, as in your case, not all submissions are. This gives us a somewhat happy balance in that the data is there to extract if you really want it, but for most users the value with be removed when they send it to the backend via XHR/Fetch.

Also, `undefined` is the most accurate representation of the state of a field when it has yet to be interacted with. We use it explicitly in FormKit for that exact purpose. Happy to hear pushback on this though as we are still in beta and have opportunities to shift the api still.

**Comment by guyinpv** [comment]
Ok, my reasoning would be this: you've got a text field in which the user typed nothing. Is this really undefined, or have they decided to leave an empty string on purpose, which is valid data? How can a user purposefully leave an empty string if they wanted to? Should they press the spacebar and then delete the space they just made, will this "interaction" trigger an empty string rather than undefined?

Another argument is that, under normal circumstances, every field of an HTML form will exist in POST. The standard value would be blank/empty string, or null/nonexistent. 
Let's say you have a dynamic form where some fields might not be generated at all. In my PHP backend, these could be tested with `isset()` or the null coalesce structure like `$maybe_var = $_POST['othername'] ?? "default";` This makes sure the variable is set in POST and not NULL, otherwise I get the default.

Another argument is, in my case, I wanted the values as a `FormData()` object, but when setting the undefined variable, that's when it converted `undefined` into a string with the word "undefined" in the string. An improper conversion in any estimation. I would think undefined should be converted to empty string, or the word `null`. I guess that conversion could be left up to the programmer?
Or then again, maybe undefined should simply not exist or become part of `FormData()`. At least this way I can test with `isset()` in the normal way if the data doesn't exist at all.

Another possible solution is to have a config switch to allow empty string as a default for text fields instead of undefined. Maybe it can be set per-field as a prop, what the default value would be.

**Comment by justin-schroeder** [comment]
Yeah, this sounds like something you'd want to sus out in your own conversion to FormData, if the value is undefined just don't set it in the FormData. Or, in those cases, if you prefer an empty string use that. FormKit opts to not initialize values that have not yet been interacted with in as many cases as possible, and that is unlikely to change, but if you really want empty strings as initial values, it is pretty trivial to write a little plugin that would do that for you. Should be roughly 1 line of code.

https://formkit.link/63dfb0faefc83ab48ad355829abfe3db
