### ISSUE TITLE
sections-schema is not reactive

### ISSUE THREAD

**Issue by aegorx** [formkit/formkit#345]
### Reproduction

https://formkit.link/03343c84732d1e7e4e1d0e2844c4f112

### Describe the bug

The sections-schema parameter does not support dynamic change

### Environment

• OS: mac
• Browser  103.0.5060.134 (arm64)
• Version latest

**Comment by justin-schroeder** [comment]
The schemas themselves are reactive, but changing the schema is not. This would require re-parsing and re-compiling the schema, which we don't want to do. However you can use conditions in your schema to achieve the same results.
