### ISSUE TITLE
How to bind select options from API?

### ISSUE THREAD

**Issue by yopichy** [formkit/formkit#347]
I've try to fetch Countries data from API but sources is empty.
But no issue when set options titles from setup()

how to trigger dropdown countries so that the data is updated?

Countries Array:
![image](https://user-images.githubusercontent.com/2038089/183159386-56ead6a3-a4ee-4446-b618-11bf3674969b.png)

![image](https://user-images.githubusercontent.com/2038089/183158924-97113acb-c50b-47fb-8807-6d5abdc1b816.png)
![image](https://user-images.githubusercontent.com/2038089/183158950-7c4cf476-a167-4e51-b4af-016167af85c5.png)

`<FormKit type="select" label="Country" help="Negara" validation="required" :options="countries" />`
`<FormKit type="select" label="Job Level" help="Jenjang Jabatan" validation="required" placeholder="==Select=="
            :options="titles" />`
            
            
![image](https://user-images.githubusercontent.com/2038089/183158920-99897838-d28f-47f0-a5d8-337193abac20.png)

![image](https://user-images.githubusercontent.com/2038089/183158777-568cc35d-d2f0-4d62-af85-26c7cc78e713.png)

**Comment by justin-schroeder** [comment]
It appears to me you aren't returning a ref or reactive object from your setup function which is required when using the composition API if you want reactivity, but if you do that, it should work fine: https://formkit.link/299c20f91d9de92758a45435d212c5cc
