### ISSUE TITLE
$formkit is undefined

### ISSUE THREAD

**Issue by raphaelbernhart** [formkit/formkit#348]
### Reproduction

https://formkit.link/05eeb6dd42fb174919dbcd109260ac3b

### Describe the bug

I can reproduce this bug in nuxt3. So don't take the formkit reproduction link to serious. (just Vue3)

The plugin is working perfectly but when trying to defining it with `const { $formkit } = useNuxtApp();` and using it with e.g. `$formkit.submit()` I get the error `$formkit is undefined`. Also when logging the nuxt app I cannot find the $formkit property.

I seems like the nuxt plugin doesn't get provided.

![Bildschirmfoto 2022-08-06 um 21 37 22](https://user-images.githubusercontent.com/48283236/183263801-8c65f2b6-e4cc-4402-bffa-5851ea6383cc.png)

### Environment

• OS: MacOS
• Browser: Firefox Dev Edition
• Version 104.0b6

**Comment by justin-schroeder** [comment]
I believe `useNuxtApp` returns the nuxt app object, not the vue app. You probably need something like:

```js
const { vueApp } = useNuxtApp()
vueApp.$formkit
```

**Comment by raphaelbernhart** [comment]
Thanks for the reply.

I think it would be nice as it is a nuxt Plugin to get the this.$formkit prop. Also this isn't difficulty at all to implement (just return the {provide: $formkit} object)

Is this planned anytime soon?

**Comment by justin-schroeder** [comment]
Not currently no, but I think we'd be happy to look at a pull request for this!

**Comment by gbyesiltas** [comment]
> I believe `useNuxtApp` returns the nuxt app object, not the vue app. You probably need something like:
> 
> ```js
> const { vueApp } = useNuxtApp()
> vueApp.$formkit
> ```

This unfortunately doesn't work for me. `vueApp.$formkit` returns undefined.

@formkit/nuxt: 0.17.0
nuxt: 3.4.3

Any ideas?

**Comment by justin-schroeder** [comment]
This isn't really the intended mechanism of use. If you want `$formkit` use the options API, otherwise use the composition functions formkit provides.

**Comment by gbyesiltas** [comment]
oh that's nice to know. I didn't see the documentation for composition api before. thanks!
