### ISSUE TITLE
Manage Tailwind's cache better

### ISSUE THREAD

**Issue by draganescu** [formkit/formkit#349]
### Describe the feature

Sometimes the Tailwind classes specified in `formkit.theme.js` - following the Tailwind theme setup tutorial from [here](https://formkit.com/guides/create-a-tailwind-theme) don't get applied. For example there would be a `bg-blue-500 hover:bg-blue-700` for `buttonClassification` -  all the other classes get applied but not these.

This only happened to me on a `vite` ran Vue 3 project With the project running locally via `npm run dev` suddenly the `bg-*` classes stopped being applied to FormKit elements. They were imposiible to get back (with Vite restarts, editing `index.css`, editing `formkit.theme.js`), **untill I've added in the same page some other HTML element with the missing classes.** Then they got applied to FormKit elements as well. 

Not sure this is a FormKit or Tailwind issue, feel free to point me with a better explanation if I should open this on Tailwind's issue repo 😁  

Thank you!

**Comment by timhanlon** [comment]
Add `formkit.config.{js,ts}` to the content array in your Tailwind config. Was just scratching my head about this one myself.

**Comment by draganescu** [comment]
@timhanlon Thank you! I had that added - the Tw classes did apply just fine for a long time. The problem here is that sometimes they randomly? stop working.

**Comment by GustavoFenilli** [comment]
This is probably a tailwindcss bug and not ours, we don't really do anything with tailwindcss. I think its related to this https://github.com/tailwindlabs/tailwindcss/discussions/6749

**Comment by draganescu** [comment]
Excellent find @GustavoFenilli I'll close this 👍🏻

**Comment by DanjBethel** [comment]
> 

Did you find a fix? Experiencing the same issue.

**Comment by GustavoFenilli** [comment]
> Did you find a fix? Experiencing the same issue.

This is not a formkit bug, it is a tailwindcss cache issue.
