### ISSUE TITLE
Add data-type "checked" to formkit-option

### ISSUE THREAD

**Issue by TomDeSmet** [formkit/formkit#350]
### Describe the feature

Add data-type "checked" to formkit-option, this way we can style the options much easier (I don't think there is a good way now to do that).
We can't use the input `checked` state as we can't jump to a parent div using CSS selectors.
And the data-complete` property on the parent element doesn't allow us to know which option wrapper was selected.

**Comment by justin-schroeder** [comment]
Which section are you trying to style based on the checked attr. The `decorator` can be used for easy styling using a sibling selector `input:checked ~ .formkit-decorator`, but maybe you need styles somewhere else?

**Comment by TomDeSmet** [comment]
I need to be able to style the option wrapper as the client want the radio buttons to look like, well, buttons. So without a decorator on the left.

**Comment by justin-schroeder** [comment]
Closing in favor of #477
