### ISSUE TITLE
onMounted is being called prior to FormKit being ready on page transitions

### ISSUE THREAD

**Issue by JohnCampionJr** [formkit/formkit#352]
### Reproduction

https://github.com/JohnCampionJr/nuxt3-net6-starter/tree/wip

### Describe the bug

Setting up a test / starter nuxt3 app for my use.  

Trying out the auto prop plugin and I'm finding a problem in the onMounted() lifecycle hook.

It appears that the FormKit has not always updated the DOM by the time this event fires, so on back to back pages with similarly named inputs, the onmounted is not catching the right element.

You can see it in my repo (no need for dot net backend) just start it up and click between the two validation pages and watch the console.  It's not grabbing the right element.

I've tried nextTick and setTimeout, with no luck. I've also disabled the plugin for testing.  

### Environment

• OS: Windows
• Browser Edge, Chrome
• Version latest

**Comment by JohnCampionJr** [comment]
Maybe a different question, is there a better event to call focus() in to ensure that the FormKit form is ready?

**Comment by justin-schroeder** [comment]
onMounted should work just fine, we use that pretty frequently. I checked out the reproduction but I'm unable to get it to boot up — could you make a minimum repro on stackblitz or a vanilla nuxt3?

**Comment by JohnCampionJr** [comment]
Strange.  Let me see if I can narrow it down.

**Comment by JohnCampionJr** [comment]
Here you go.  View console.  You'll see the element being found in onMounted is not the one rendered.

https://stackblitz.com/edit/github-vqvsuh-bnkwij?file=pages/second.vue

**Comment by justin-schroeder** [comment]
Thanks for those repros. So it looks like Nuxt wraps its pages in a `<Transition>` by default, so `onMounted` is not a reliable way to know when a page actually mounts to the DOM. This is not FormKit specific (for example, [here is the same but with a raw `<input>`](https://stackblitz.com/edit/github-vqvsuh-re7tjd?file=pages/second.vue)), but I do wonder what their recommendation would be on the best way to ensure a given DOM node is mounted or not.

If you want to disable this default `<Transition>` behavior, you can add `definePageMeta({ pageTransition: false })` to your pages and that will prevent these kind of issues: https://stackblitz.com/edit/github-vqvsuh-bsbmjr?file=pages%2Fsecond.vue

If you find an alternate workaround I'd be interested.

**Comment by JohnCampionJr** [comment]
Thank you!  Found the upstream bugs:
Nuxt:
https://github.com/nuxt/framework/issues/3587

Vue3 Bug:
https://github.com/vuejs/core/issues/5844
