### ISSUE TITLE
Icons are not reactive

### ISSUE THREAD

**Issue by mweghorst** [formkit/formkit#354]
### Reproduction

https://formkit.link/d5e5e2a38772fe928d9b045cd50d21ab

### Describe the bug

I'm trying to use a reactive icon with a custom iconLoader / iconLoaderUrl but unfortunately this doesn't work. When the icon value changes, FormKit attempts to load it using the 'default' loader: the Playground link above results in a 404 at https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/svgs/solid/eyeClosed.svg.

### Environment

• Browser [Chrome]
• Version [103]

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
Hm, you're asking for `eyeClosed` from Font Awesome — that just isn't an icon. If you're wanting to load icons from font awesome, you need to use their icon names. For example `eye-slash`: https://formkit.link/15d590fd45cf75e362c89c23db48a12e

Their icons are available here:
https://fontawesome.com/icons

**Comment by mweghorst** [comment]
Thank you for your quick response Justin. I see I've made a mistake in my Playground link, but it also doesn't work with `eye-slash` if the createThemePlugin is loaded: https://formkit.link/9d39ec72df6bdc0ec33a9f1411daa09f

**Comment by justin-schroeder** [comment]
`createThemePlugin` is already loaded on the playground since it is part of the defaultConfig. You only need to use that if you are creating your own blank configuration. By calling it again you have 2 theme plugins running competing for the icon url. What is the end result you are trying to achieve?

**Comment by mweghorst** [comment]
Removing `plugins: [createThemePlugin()],` did the trick, thanks!

Perhaps it's possible to throw a warning when `createThemePlugin` is loaded more than once, but up to you of course. Thanks again!
