### ISSUE TITLE
AutoAnimate doesn't work in Nuxt

### ISSUE THREAD

**Issue by adinvadim** [formkit/formkit#361]
### Reproduction

https://formkit.com/playground

### Describe the bug

Reproduction link doesn't work, because bug in Nuxt enviroment.

formkit.config.js
```javascript
import { createAutoAnimatePlugin } from "@formkit/addons";

export default {
  plugins: [createAutoAnimatePlugin()],
};

```

500
Error: MutationObserver is not defined
<img width="1028" alt="Screenshot 2022-08-22 at 22 13 32" src="https://user-images.githubusercontent.com/8646071/186000425-28a7ed70-d91d-4490-8a9c-65fbdf3e1b84.png">

### Environment

• OS: Mac OS 12.2 (21D49)
• Browser chrome 104.0.5112.101 
•  formkit "^1.0.0-beta.10",

**Comment by justin-schroeder** [comment]
Thanks for the report, I just published an updated to the `@next` tag that should fix this.

**Comment by adinvadim** [comment]
Thank you!
