### ISSUE TITLE
Example for importing formkit into a single component rather than defining it globally?

### ISSUE THREAD

**Issue by cookiejest** [formkit/formkit#366]
### Describe the feature

I am trying to use formkit within one component, since we are building it into a web component we cant use app.use() so need an example of how to use the formkit just within one component is it possible?

Thanks!

**Comment by justin-schroeder** [comment]
We need to improve this. Currently its possible, but....not enjoyable.

**Comment by riderx** [comment]
Hey @justin-schroeder do you have the not enjoyable example to share maybe ?
I try to optimize my bundle.

**Comment by riderx** [comment]
Thanks @justin-schroeder, the stackblitz gave 404.
Your recommendation is still to global import, with a little scope. right ?
Do your stackblitz is as single component ?

**Comment by justin-schroeder** [comment]
Hey, this is now doable with the `<FormKitProvider>` component: https://formkit.com/guides/optimizing-for-production
