### ISSUE TITLE
Using @nuxt/kit-edge@latest" breaks FormKit with nuxt3 rc8.

### ISSUE THREAD

**Issue by JohnCampionJr** [formkit/formkit#370]
### Reproduction

N/A

### Describe the bug

If using beta 10 with rc8, with a clean install, pulls in a later version of the  nuxt/kit that is newer than rc8.

At some point, it would be good to get FormKit off of the edge release of Nuxt Kit.

### Environment

Any

**Comment by minasvisual** [comment]
Yeap, breaks the new releases. Thanks for report!

warning "@formkit/nuxt > @formkit/vue@1.0.0-beta.10" has unmet peer dependency "vue@^3.2.1".

**Comment by justin-schroeder** [comment]
Can you try this with`@formkit/nuxt@next`?
