### ISSUE TITLE
Nuxt 3.0.0-rc.8 incompatible?

### ISSUE THREAD

**Issue by daniel7912** [formkit/formkit#371]
### Reproduction

N/A

### Describe the bug

I have been using the module without problems, then I needed to upgrade Nuxt Content so I followed these instructions https://content.nuxtjs.org/guide/migration/edge-channel/

After deleting node_modules & yarn.lock, and re-running yarn install, I now get the following warning on running 'yarn dev':

 WARN  Module FormKit is disabled due to incompatibility issues:                                                                                                                                                                        
 - [nuxt] Nuxt version `^3.0.0` is required but currently using `3.0.0-rc.8`

My package.json file looks like this:

{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "devDependencies": {
    "@nuxt/content": "npm:@nuxt/content-edge@latest",
    "@nuxtjs/supabase": "^0.1.23",
    "@nuxtjs/tailwindcss": "^5.3.2",
    "nuxt": "3.0.0-rc.8"
  },
  "dependencies": {
    "@formkit/nuxt": "1.0.0-beta.10",
    "@formkit/themes": "^1.0.0-beta.10",
    "@headlessui/vue": "^1.6.7",
    "@heroicons/vue": "^2.0.10"
  }
}

### Environment

• OS: Mac
• Browser Chrome
• Version 1.0.0-beta.10

**Comment by albericobenhur** [comment]
i have the same problem

**Comment by justin-schroeder** [comment]
This was a change on the nuxt side, you can now install it with `@formkit/nuxt@next` until the new version is launched.

**Comment by albericobenhur** [comment]
> @formkit/nuxt@next

that worked to me

**Comment by bennyzen** [comment]
Tried the latest beta `@formkit/nuxt@1.0.0-beta.11-0dd967c` with Nuxt-RC9 here on [stackblitz](https://stackblitz.com/edit/nuxt-starter-apxaw7?file=package.json) . Unfortunately, no chance to get it working.

**Comment by bennyzen** [comment]
@marcel-wtfoxtrot oh yes, your stack works. many thanks
