### ISSUE TITLE
Unable to import `@formkit/themes/tailwindcss` with TypeScript

### ISSUE THREAD

**Issue by dzcpy** [formkit/formkit#376]
### Reproduction

https://codesandbox.io/s/goofy-currying-rnursq?file=/tailwind.config.ts

### Describe the bug

![image](https://user-images.githubusercontent.com/203980/188419778-e8cf1a1f-d97d-4199-8165-7d6fbe04fdeb.png)

__Error message:__
```Cannot find module '@formkit/themes/tailwindcss' or its corresponding type declarations.ts(2307)```
### Environment

• OS: not related
• Browser: not related
• Version: ^1.0.0-beta.11-0dd967c

**Comment by justin-schroeder** [comment]
We'll need more information than this — what build tool are you use (nuxt/vite etc) what version of node. Ideally you could provide a reproduction.

**Comment by dzcpy** [comment]
Well I'm using `nuxt 3`, but I think it's platform / configuration agnostic. The problem is that there is no actual typescript type for it. Here is the test enviroment:
https://codesandbox.io/s/goofy-currying-rnursq?file=/tailwind.config.ts

**Comment by GustavoFenilli** [comment]
After looking it up it seens to not be a bug with formkit but with typescript itself as per [#33079](https://github.com/microsoft/TypeScript/issues/33079)
