### ISSUE TITLE
Choose location of displayed error

### ISSUE THREAD

**Issue by azertyalex** [formkit/formkit#378]
### Describe the feature

We use custom buttons for actions (submit, cancel, etc..). The problem we have is that general form errors are displayed at the bottom of the form, behind the last element.
![image](https://user-images.githubusercontent.com/9082988/188687298-792d9816-d956-42e3-bd9f-a463596a607e.png)

We would like a way to say where the error is supposed to go, for example:
```vue
<FormKit type="form" :actions="false" @submit="doCreateUser">
            <div class="px-6 py-4">
                <FormKit
                    label="Voornaam"
                    type="text"
                    v-model="newUser.firstName"
                />
                <FormKit
                    label="Familienaam"
                    type="text"
                    v-model="newUser.lastName"
                />
                <FormKit
                    label="Email"
                    type="email"
                    v-model="newUser.email"
                />
                <FormKitErrors />
            </div>
            <div class="grey">
                <Button
                    bgColor="bg-white"
                    textColor="text-gray-700"
                    border="border border-gray-100"
                    class="h-min mr-2"
                    @click="$emit('update:show', false)"
                >
                    Annuleren
                </Button>
                <FormKit type="submit" label="Aanmaken" />
            </div>
        </FormKit>
```

**Comment by justin-schroeder** [comment]
Thanks for the suggestion, this might be something worth doing in the future, in the meantime you can use the actions slot to place your buttons below the message location.

https://formkit.link/16a5ffb9c05c36deca903858e111d5e0

Also, its worth noting that you do not need to v-model each input with FormKit. FormKit automatically collects all child inputs into an object, and that object is automatically passed to the submit handler. The key of each value in that object is the `name` property (Ive done this in the example). Also you can v-model your entire form in a single location if you really do want 2 way binding.

**Comment by azertyalex** [comment]
Thanks, that helped me for now :D

**Comment by justin-schroeder** [comment]
This is now a feature in the upcoming beta.13 with a new `<FormKitMessages />` component you can place anywhere in your form, or even outside your form if you pass it the `node`.
