### ISSUE TITLE
`No form element with id: input_0` in Nuxt 3 + SSR on a form with a custom submit button and schema

### ISSUE THREAD

**Issue by jf908** [formkit/formkit#379]
### Reproduction

https://stackblitz.com/edit/github-maaa5z-88ge5k?file=app.vue

### Describe the bug

The reproduction link is supposed to post the form's data to the console on submit but instead prints a warning after reloading the page at least once.

I'm using the recommended methods for [rendering a form with a schema](https://formkit.com/essentials/generation#forms) and  [submitting with node.submit](https://formkit.com/essentials/forms#submitting-with-nodesubmit) in Nuxt but every time the page is reloaded, the form's id is incremented by 1 but FormKit still tries to find #input_0 in the document so the form cannot be submitted.

### Environment

• OS: WSL
• Browser: Chrome
• Version: beta.10 and beta.11-1c50a05

**Comment by justin-schroeder** [comment]
For SSR it's generally useful to provide explicit ids since stable deterministic ids are (nearly) impossible to communicate across the server barrier. So in this case you can just set the id yourself 👍

https://stackblitz.com/edit/github-maaa5z-npnnfg?file=app.vue

**Comment by jf908** [comment]
Thank you, your stackblitz link didn't work for me but it does when I add an id attribute to the parent <Formkit type="form"> element.

That works for me, I'll leave it up to you if you think this issue can be closed.
