### ISSUE TITLE
Reordering groups in list

### ISSUE THREAD

**Issue by lukapozega** [formkit/formkit#381]
Hello,

I would like to know how to reorder elements in list node. I have tried by adding nodes to list node's children and deleting other nodes, but I cannot get it to work. I have also tried by manipulating the form's model but then I would just get duplicated nodes.

Here is a small example of what I am trying to achieve: [example](https://formkit.com/playground?fkv=latest&fileTab=Playground.vue&files=JTVCJTdCJTIyZWRpdG9yJTIyJTNBJTIyJTNDc2NyaXB0JTIwc2V0dXAlM0UlNUNuJTIwJTIwJTIwJTIwaW1wb3J0JTIwJTdCJTIwcmVmJTIwJTdEJTIwZnJvbSUyMCd2dWUnJTVDbiUyMCUyMCUyMCUyMGltcG9ydCUyMCU3QiUyMHRva2VuJTIwJTdEJTIwZnJvbSUyMCclNDBmb3Jta2l0JTJGdXRpbHMnJTVDbiUyMCUyMCUyMCUyMCU1Q24lMjAlMjAlMjAlMjBjb25zdCUyMHZhbHVlcyUyMCUzRCUyMHJlZiglN0JkYXlzJTNBJTIwJTVCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCU3QnRpdGxlJTNBJTIwJ2RheSUyMDEnJTJDJTIwaWQlMjAlM0EwJTJDJTIwdGhpbmdzSW5EYXklM0ElMjAlNUIlN0JuYW1lJTNBJ2ZpcnN0JyU3RCUyQyUyMCU3Qm5hbWUlM0Enc2Vjb25kJyU3RCU1RCU3RCUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlN0J0aXRsZSUzQSUyMCdkYXklMjAyJyUyQyUyMGlkJTNBJTIwMSUyQyUyMHRoaW5nc0luRGF5JTNBJTIwJTVCJTdCbmFtZSUzQSdmaXJzdCclN0QlNUQlN0QlMkMlNUNuJTIwJTIwJTIwJTIwJTVEJTdEKSU1Q24lMjAlMjAlMjAlMjAlNUNuJTIwJTIwJTIwJTIwY29uc3QlMjBtb3ZlVXAlMjAlM0QlMjAoZGF5SW5kZXgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMGlmJTIwKGRheUluZGV4JTIwJTNEJTNEJTNEJTIwMCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwcmV0dXJuJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMkYlMkYlMjAlNUJ2YWx1ZXMudmFsdWUuZGF5cyU1QmRheUluZGV4LTElNUQlMkMlMjB2YWx1ZXMudmFsdWUuZGF5cyU1QmRheUluZGV4JTVEJTVEJTIwJTNEJTIwJTVCdmFsdWVzLnZhbHVlLmRheXMlNUJkYXlJbmRleCU1RCUyQyUyMHZhbHVlcy52YWx1ZS5kYXlzJTVCZGF5SW5kZXgtMSU1RCU1RCU1Q24lMjAlMjAlMjAlMjAlMjAlMjB2YWx1ZXMudmFsdWUuZGF5cy51bnNoaWZ0KHZhbHVlcy52YWx1ZS5kYXlzJTVCMSU1RCklM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCUyMCUyMCUzQyUyRnNjcmlwdCUzRSU1Q24lMjAlMjAlMjAlMjAlNUNuJTIwJTIwJTIwJTIwJTNDdGVtcGxhdGUlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDRm9ybUtpdCUyMHR5cGUlM0QlNUMlMjJmb3JtJTVDJTIyJTIwdi1tb2RlbCUzRCU1QyUyMnZhbHVlcyU1QyUyMiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NGb3JtS2l0JTIwdHlwZSUzRCU1QyUyMmxpc3QlNUMlMjIlMjBuYW1lJTNEJTVDJTIyZGF5cyU1QyUyMiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0N0ZW1wbGF0ZSUyMCUyM2RlZmF1bHQlM0QlNUMlMjIlN0IlMjB2YWx1ZSUzQSUyMGxpc3RWYWx1ZSUyMCU3RCU1QyUyMiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NGb3JtS2l0JTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHYtZm9yJTNEJTVDJTIyKGRheSUyQyUyMGRheUluZGV4KSUyMG9mJTIwbGlzdFZhbHVlJTVDJTIyJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQWtleSUzRCU1QyUyMmRheS5pZCU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0FpZCUzRCU1QyUyMiU2MCUyNCU3QmRheS5pZCU3RCU2MCU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB0eXBlJTNEJTVDJTIyZ3JvdXAlNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwY2xhc3MlM0QlNUMlMjJkYXklNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ0Zvcm1LaXQlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwdHlwZSUzRCU1QyUyMnRleHQlNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwbGFiZWwlM0QlNUMlMjJOYW1lJTVDJTIyJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMG5hbWUlM0QlNUMlMjJ0aXRsZSU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBoZWxwJTNEJTVDJTIyRGF5JTIwdGl0bGUuJTVDJTIyJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NGb3JtS2l0JTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMG5hbWUlM0QlNUMlMjJ0aGluZ3NJbkRheSU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB0eXBlJTNEJTVDJTIybGlzdCU1QyUyMiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NGb3JtS2l0JTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHYtZm9yJTNEJTVDJTIyKHRoaW5nJTJDJTIwdGhpbmdJbmRleCklMjBvZiUyMGRheS50aGluZ3NJbkRheSU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0FrZXklM0QlNUMlMjJ0aGluZyU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0FpZCUzRCU1QyUyMiU2MCUyNCU3QnRoaW5nJTdEJTYwJTVDJTIyJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHR5cGUlM0QlNUMlMjJncm91cCU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDRm9ybUtpdCU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB0eXBlJTNEJTVDJTIydGV4dCU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBsYWJlbCUzRCU1QyUyMk5hbWUlNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwbmFtZSUzRCU1QyUyMm5hbWUlNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaGVscCUzRCU1QyUyMlRoaW5nJTIwbmFtZS4lNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRkZvcm1LaXQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGRm9ybUtpdCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NidXR0b24lMjAlNDBjbGljayUzRCU1QyUyMm1vdmVVcChkYXlJbmRleCklNUMlMjIlM0VNb3ZlJTIwdG8lMjBmaXJzdCUyMHBsYWNlJTNDJTJGYnV0dG9uJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRkZvcm1LaXQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGRm9ybUtpdCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NwcmUlMjB3cmFwJTNFJTdCJTdCJTIwdmFsdWVzJTIwJTdEJTdEJTNDJTJGcHJlJTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRnRlbXBsYXRlJTNFJTVDbiUyMCUyMCUyMCUyMCU1Q24lMjAlMjAlMjAlMjAlM0NzdHlsZSUzRSU1Q24lMjAlMjAlMjAlMjAuZm9ybWtpdC1yZW1vdmUlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwcG9zaXRpb24lM0ElMjBhYnNvbHV0ZSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBsZWZ0JTNBJTIwY2FsYygxMDAlMjUlMjAlMkIlMjAuNWVtKSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBjb2xvciUzQSUyMHJlZCUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBmb250LXNpemUlM0ElMjAuNzVlbSUzQiU1Q24lMjAlMjAlMjAlMjAlN0QlNUNuJTIwJTIwJTIwJTIwYnV0dG9uJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMGFsaWduLXNlbGYlM0ElMjBmbGV4LXN0YXJ0JTNCJTVDbiUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlM0MlMkZzdHlsZSUzRSU1Q24lMjIlMkMlMjJuYW1lJTIyJTNBJTIyUGxheWdyb3VuZC52dWUlMjIlN0QlNUQ&imports=JTdCJTIybmFtZSUyMiUzQSUyMkltcG9ydE1hcCUyMiUyQyUyMmVkaXRvciUyMiUzQSUyMiU3QiU1Q24lMjAlMjAlNUMlMjJ2dWUlNUMlMjIlM0ElMjAlNUMlMjJodHRwcyUzQSUyRiUyRmNkbi5qc2RlbGl2ci5uZXQlMkZucG0lMkZ2dWUlNDAzJTJGZGlzdCUyRnZ1ZS5lc20tYnJvd3Nlci5qcyU1QyUyMiU1Q24lN0QlNUNuJTIyJTdE)

If you have any suggestions on how to do this I would very much appreciate it.

Thank you!

**Comment by justin-schroeder** [comment]
Hi @lukapozega 👋. This is admittedly a bit complicated right now (although your playground is using submit buttons whcih cause the form to reset) — I'd highly recommend [using the repeater for now](https://formkit.com/inputs/repeater) — we do have plans to improve general manipulation support for lists.
