### ISSUE TITLE
Submit event is missing form data during tests

### ISSUE THREAD

**Issue by maartenvanhunsel** [formkit/formkit#382]
### Reproduction

https://stackblitz.com/edit/github-k2bhcr?file=app.vue,nuxt.config.ts,components%2FFormExample.vue,.vscode%2Fsettings.json,components%2FFormExample.test.js

### Describe the bug

When doing some tests for my form interactions, I'm getting an error `Cannot convert undefined or null to object` which means that the submit data of the form is empty. [See line 52](https://github.com/formkit/formkit/blob/master/packages/inputs/src/features/forms.ts#L52)

If logging the input fields in the test, the value exists but does not get passed through the @submit event.

Any thoughts?

### Environment

• OS: Mac OS
• Browser chrome
• Formkit: @next

**Comment by justin-schroeder** [comment]
Hmm, that looks odd to me, I've never used testing-library though, so I can't speak to the syntax at all. My guess is somehow the app when in the testing context is not fully loading the plugins, but I cannot confirm that very easily.

**Comment by GustavoFenilli** [comment]
I did some tests and getting the node using `getNode` and doing `getNode(form).value` seens to have the values, doing `@getNode(form).submit()` tho, fails with undefined.

also removing the `:values` from the component seen to make `getNode(form).value` undefined, so this doesn't seen to add anything.
```js
const emailField = getByLabelText('E-mailadres');
const passwordField = getByLabelText('Wachtwoord');

await fireEvent.update(emailField, 'example@email.com');
await fireEvent.update(passwordField, 'password');
```

**Comment by maartenvanhunsel** [comment]
Well found it: `await new Promise((r) => setTimeout(r, 10))` after the component render function did the job.
