### ISSUE TITLE
FormKit disabled in Nuxt 3.0.0-rc.9

### ISSUE THREAD

**Issue by dpmillerau** [formkit/formkit#383]
WARN  Module FormKit is disabled due to incompatibility issues:                                                                                                                              17:03:33
 - [nuxt] Nuxt version `^3.0.0` is required but currently using `3.0.0-rc.9`
 and I tried @formkit/nuxt@next

**Comment by tobychidiu** [comment]
Yes ooo. I have this same issue [https://github.com/nuxt/framework/issues/7196]

**Comment by Tunji-Olakunle** [comment]
I also have this same issue.

**Comment by GustavoFenilli** [comment]
If you take a look at `node_modules` and at `@formkit/nuxt` which version shows there? maybe there are some cache problems.

**Comment by dpmillerau** [comment]
I wa using @

David Miller
________________________________

**Comment by justin-schroeder** [comment]
At the moment you need `@formkit/nuxt@next`

**Comment by shoaibsharif** [comment]
seems like it also got disabled when I upgrade to Nuxt 3.0.0-rc.10.
