### ISSUE TITLE
bug when update shema (adding property) inside form

### ISSUE THREAD

**Issue by comhon-project** [formkit/formkit#384]
### Reproduction
[playground with schema](
https://formkit.com/playground?fkv=1.0.0-beta.10&fileTab=Playground.vue&files=JTVCJTdCJTIybmFtZSUyMiUzQSUyMlBsYXlncm91bmQudnVlJTIyJTJDJTIyZWRpdG9yJTIyJTNBJTIyJTNDc2NyaXB0JTIwc2V0dXAlM0UlNUNuaW1wb3J0JTIwJTdCJTIwcmVmJTIwJTdEJTIwZnJvbSUyMCd2dWUnJTVDbiU1Q25jb25zdCUyMG1vZGVsJTIwJTNEJTIwcmVmKCU3QiU1Q24lMjAlMjAlMjAlMjB0ZXN0JTNBJTIwJ3ZhbHVlJyU1Q24lN0QpJTNCJTVDbiU1Q25jb25zdCUyMHNjaGVtYSUyMCUzRCUyMHJlZiglNUIlNUNuJTIwJTIwJTIwJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyNGNtcCUzQSUyMCdGb3JtS2l0JyUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBwcm9wcyUzQSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB0eXBlJTNBJTIwJ3RleHQnJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGxhYmVsJTNBJTIwJ3Rlc3QnJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMG5hbWUlM0ElMjAndGVzdCclMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCUyMCUyMCU3RCU1Q24lNUQpJTNCJTVDbiU1Q25mdW5jdGlvbiUyMHVwZGF0ZVNjaGVtYSgpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHNjaGVtYS52YWx1ZSUyMCUzRCUyMCU1QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTI0Y21wJTNBJTIwJ0Zvcm1LaXQnJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHByb3BzJTNBJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHR5cGUlM0ElMjAndGV4dCclMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwbGFiZWwlM0ElMjAnZm9vJyUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBuYW1lJTNBJTIwJ2ZvbyclMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3RCUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTI0Y21wJTNBJTIwJ0Zvcm1LaXQnJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHByb3BzJTNBJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHR5cGUlM0ElMjAndGV4dCclMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwbGFiZWwlM0ElMjAndGVzdCclMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwbmFtZSUzQSUyMCd0ZXN0JyUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0QlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTJDJTVDbiUyMCUyMCUyMCUyMCU1RCU1Q24lN0QlNUNuJTVDbiU1Q24lM0MlMkZzY3JpcHQlM0UlNUNuJTVDbiUzQ3RlbXBsYXRlJTNFJTVDbiUyMCUyMCUyMCUyMCUzQ0Zvcm1LaXQlMjB0eXBlJTNEJTVDJTIyZm9ybSU1QyUyMiUyMCU0MHN1Ym1pdCUzRCU1QyUyMnN1Ym1pdCU1QyUyMiUyMHYtbW9kZWwlM0QlNUMlMjJtb2RlbCU1QyUyMiUyMCUzQWFjdGlvbnMlM0QlNUMlMjJmYWxzZSU1QyUyMiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NGb3JtS2l0U2NoZW1hJTIwJTNBc2NoZW1hJTNEJTVDJTIyc2NoZW1hJTVDJTIyJTIwJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ0Zvcm1LaXQlMjAlNDBjbGljayUzRCU1QyUyMnVwZGF0ZVNjaGVtYSU1QyUyMiUyMHR5cGUlM0QlNUMlMjJidXR0b24lNUMlMjIlMjBsYWJlbCUzRCU1QyUyMmFkZCUyMCdmb28nJTIwYmVmb3JlJTIwJ3Rlc3QnJTVDJTIyJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRkZvcm1LaXQlM0UlNUNuJTNDJTJGdGVtcGxhdGUlM0UlNUNuJTIyJTJDJTIyYWRkZWQlMjIlM0F0cnVlJTdEJTVE&imports=JTdCJTIybmFtZSUyMiUzQSUyMkltcG9ydE1hcCUyMiUyQyUyMmVkaXRvciUyMiUzQSUyMiU3QiU1Q24lMjAlMjAlNUMlMjJ2dWUlNUMlMjIlM0ElMjAlNUMlMjJodHRwcyUzQSUyRiUyRmNkbi5qc2RlbGl2ci5uZXQlMkZucG0lMkZ2dWUlNDAzJTJGZGlzdCUyRnZ1ZS5lc20tYnJvd3Nlci5taW4uanMlNUMlMjIlNUNuJTdEJTVDbiUyMiU3RA)

[playground with v-for](https://formkit.com/playground?fkv=1.0.0-beta.10&fileTab=Playground.vue&files=JTVCJTdCJTIybmFtZSUyMiUzQSUyMlBsYXlncm91bmQudnVlJTIyJTJDJTIyZWRpdG9yJTIyJTNBJTIyJTNDc2NyaXB0JTIwc2V0dXAlM0UlNUNuaW1wb3J0JTIwJTdCJTIwcmVmJTIwJTdEJTIwZnJvbSUyMCd2dWUnJTVDbiU1Q25jb25zdCUyMG1vZGVsJTIwJTNEJTIwcmVmKCU3QiU1Q24lMjAlMjAlMjAlMjB0ZXN0JTNBJTIwJ3ZhbHVlJyU1Q24lN0QpJTNCJTVDbiU1Q25jb25zdCUyMGlucHV0cyUyMCUzRCUyMHJlZiglNUIlNUNuJTIwJTIwJTIwJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMHR5cGUlM0ElMjAndGV4dCclMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwbGFiZWwlM0ElMjAndGVzdCclMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwbmFtZSUzQSUyMCd0ZXN0JyUyQyU1Q24lMjAlMjAlMjAlMjAlN0QlNUNuJTVEKSUzQiU1Q24lNUNuZnVuY3Rpb24lMjB1cGRhdGVJbnB1dHMoKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBpbnB1dHMudmFsdWUlMjAlM0QlMjAlNUIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHR5cGUlM0ElMjAndGV4dCclMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwbGFiZWwlM0ElMjAnZm9vJyUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBuYW1lJTNBJTIwJ2ZvbyclMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB0eXBlJTNBJTIwJ3RleHQnJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGxhYmVsJTNBJTIwJ3Rlc3QnJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMG5hbWUlM0ElMjAndGVzdCclMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTJDJTVDbiUyMCUyMCUyMCUyMCU1RCU1Q24lN0QlNUNuJTVDbiU1Q24lM0MlMkZzY3JpcHQlM0UlNUNuJTVDbiUzQ3RlbXBsYXRlJTNFJTVDbiUyMCUyMCUyMCUyMCUzQ0Zvcm1LaXQlMjB0eXBlJTNEJTVDJTIyZm9ybSU1QyUyMiUyMCU0MHN1Ym1pdCUzRCU1QyUyMnN1Ym1pdCU1QyUyMiUyMHYtbW9kZWwlM0QlNUMlMjJtb2RlbCU1QyUyMiUyMCUzQWFjdGlvbnMlM0QlNUMlMjJmYWxzZSU1QyUyMiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NGb3JtS2l0JTIwdi1mb3IlM0QlNUMlMjIoaW5wdXQlMkMlMjBpbmRleCklMjBpbiUyMGlucHV0cyU1QyUyMiUyMCUzQWtldCUzRCU1QyUyMmluZGV4JTVDJTIyJTIwdi1iaW5kJTNEJTVDJTIyaW5wdXQlNUMlMjIlMkYlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDRm9ybUtpdCUyMCU0MGNsaWNrJTNEJTVDJTIydXBkYXRlSW5wdXRzJTVDJTIyJTIwdHlwZSUzRCU1QyUyMmJ1dHRvbiU1QyUyMiUyMGxhYmVsJTNEJTVDJTIyYWRkJTIwJ2ZvbyclMjBiZWZvcmUlMjAndGVzdCclNUMlMjIlMkYlM0UlNUNuJTIwJTIwJTIwJTIwJTNDJTJGRm9ybUtpdCUzRSU1Q24lM0MlMkZ0ZW1wbGF0ZSUzRSU1Q24lMjIlMkMlMjJhZGRlZCUyMiUzQXRydWUlN0QlNUQ&imports=JTdCJTIybmFtZSUyMiUzQSUyMkltcG9ydE1hcCUyMiUyQyUyMmVkaXRvciUyMiUzQSUyMiU3QiU1Q24lMjAlMjAlNUMlMjJ2dWUlNUMlMjIlM0ElMjAlNUMlMjJodHRwcyUzQSUyRiUyRmNkbi5qc2RlbGl2ci5uZXQlMkZucG0lMkZ2dWUlNDAzJTJGZGlzdCUyRnZ1ZS5lc20tYnJvd3Nlci5taW4uanMlNUMlMjIlNUNuJTdEJTVDbiUyMiU3RA)

### Describe the bug

when adding a new property in schema before an existing one, the value (the ref) inside first existing property input is duplicated in the new one 

Edit: the bug appears when using Formkit components with a `v-for`

### Environment

• ubuntu 20.04
• chrome (v 103), firefox (v 104)
• FormKit v 1.0.0-beta.10

**Comment by justin-schroeder** [comment]
Hi @comhon-project — you just need keys on your inputs: https://formkit.link/49baefe1472afb79b304061bb11afee1

**Comment by GustavoFenilli** [comment]
`name` couldn't be unique as it is totally possible to have two of the same name inside the form ( we have groups ).
unless key would be a combination of `{parent.name}.name`.

**Comment by comhon-project** [comment]
ok I understand, so can it be mentioned in documentation that when we update schema we should add `key` otherwise we have an unexpected behavior ? should i do another issue for this ?

**Comment by comhon-project** [comment]
another proposal : is it's possible to implicitly build `key` by concatenate `name` of current and parents in case of group ?
somthing like said @GustavoFenilli :
- first level : key = `name`
- nested levels : key = `{grand_parent.name}.{parent.name}.name`

**Comment by GustavoFenilli** [comment]
Maybe we should add `key` to the universal props from `Props & Attributes` @justin-schroeder what do you think?
> Allow vue to render inputs in the correct order when the DOM needs to make changes.

**Comment by GustavoFenilli** [comment]
> another proposal : is it's possible to implicitly build `key` by concatenate `name` of current and parents in case of group ? somthing like said @GustavoFenilli :
> 
> * first level : key = `name`
> * nested levels : key = `{grand_parent.name}.{parent.name}.name`

This is already possible with plugins, I don't think this should be a magically applied property to all inputs by default. ( needs some testing but this could be made with something like this )
```js
const addUniqueKeyPlugin = (node) => {
  node.props.key = node.parent ? `${node.parent.props.key}.${node.name}` : node.name;
}
```

**Comment by dominikklein** [comment]
I think you need also to be careful when you are updating the complete schema. At least at the beginning from the beta it was mention that the Schema should be something static and the Schema data should be used for reactivity.

**Comment by comhon-project** [comment]
@GustavoFenilli about the `name` that is not unique, I just realize that there is a behavior that is probably not consistent.
when I have several properties with the same name in my object but in diferent level.
[example with schema](https://formkit.com/playground?fkv=1.0.0-beta.10&fileTab=Playground.vue&files=JTVCJTdCJTIybmFtZSUyMiUzQSUyMlBsYXlncm91bmQudnVlJTIyJTJDJTIyZWRpdG9yJTIyJTNBJTIyJTNDc2NyaXB0JTIwc2V0dXAlM0UlNUNuaW1wb3J0JTIwJTdCJTIwcmVmJTIwJTdEJTIwZnJvbSUyMCd2dWUnJTVDbiU1Q25jb25zdCUyMG1vZGVsJTIwJTNEJTIwcmVmKCU3QiU1Q24lMjAlMjAlMjAlMjBmb28lM0ElMjAndmFsdWUnJTJDJTVDbiUyMCUyMCUyMCUyMGdyb3VwJTNBJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMGZvbyUzQSUyMCduZXN0ZWQlMjB2YWx1ZSclNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiU3RCklM0IlNUNuJTVDbmNvbnN0JTIwc2NoZW1hJTIwJTNEJTIwcmVmKCU1QiU1Q24lMjAlMjAlMjAlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTI0Y21wJTNBJTIwJ0Zvcm1LaXQnJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHByb3BzJTNBJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHR5cGUlM0ElMjAndGV4dCclMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwbGFiZWwlM0ElMjAnZm9vJyUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBuYW1lJTNBJTIwJ2ZvbyclMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCUyMCUyMCU3RCUyQyU1Q24lMjAlMjAlMjAlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTI0Y21wJTNBJTIwJ0Zvcm1LaXQnJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHByb3BzJTNBJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHR5cGUlM0ElMjAnZ3JvdXAnJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMG5hbWUlM0ElMjAnZ3JvdXAnJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3RCUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBjaGlsZHJlbiUzQSUyMCU1QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTI0Y21wJTNBJTIwJ0Zvcm1LaXQnJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHByb3BzJTNBJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHR5cGUlM0ElMjAndGV4dCclMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwbGFiZWwlM0ElMjAnbmVzdGVkJTIwZm9vJyUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBuYW1lJTNBJTIwJ2ZvbyclMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3RCUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlNUQlNUNuJTIwJTIwJTIwJTIwJTdEJTJDJTVDbiU1RCklM0IlNUNuJTNDJTJGc2NyaXB0JTNFJTVDbiU1Q24lM0N0ZW1wbGF0ZSUzRSU1Q24lMjAlMjAlMjAlMjAlM0NGb3JtS2l0JTIwdHlwZSUzRCU1QyUyMmZvcm0lNUMlMjIlMjAlNDBzdWJtaXQlM0QlNUMlMjJzdWJtaXQlNUMlMjIlMjB2LW1vZGVsJTNEJTVDJTIybW9kZWwlNUMlMjIlMjAlM0FhY3Rpb25zJTNEJTVDJTIyZmFsc2UlNUMlMjIlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDRm9ybUtpdFNjaGVtYSUyMCUzQXNjaGVtYSUzRCU1QyUyMnNjaGVtYSU1QyUyMiUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlM0MlMkZGb3JtS2l0JTNFJTVDbiUyMCUyMCUyMCUyMCUzQ3ByZSUyMHdyYXAlM0UlN0IlN0IlMjBtb2RlbCUyMCU3RCU3RCUzQyUyRnByZSUzRSU1Q24lM0MlMkZ0ZW1wbGF0ZSUzRSU1Q24lMjIlMkMlMjJhZGRlZCUyMiUzQXRydWUlN0QlNUQ&imports=JTdCJTIybmFtZSUyMiUzQSUyMkltcG9ydE1hcCUyMiUyQyUyMmVkaXRvciUyMiUzQSUyMiU3QiU1Q24lMjAlMjAlNUMlMjJ2dWUlNUMlMjIlM0ElMjAlNUMlMjJodHRwcyUzQSUyRiUyRmNkbi5qc2RlbGl2ci5uZXQlMkZucG0lMkZ2dWUlNDAzJTJGZGlzdCUyRnZ1ZS5lc20tYnJvd3Nlci5taW4uanMlNUMlMjIlNUNuJTdEJTVDbiUyMiU3RA)
[example without schema](https://formkit.com/playground?fkv=1.0.0-beta.10&fileTab=Playground.vue&files=JTVCJTdCJTIybmFtZSUyMiUzQSUyMlBsYXlncm91bmQudnVlJTIyJTJDJTIyZWRpdG9yJTIyJTNBJTIyJTNDc2NyaXB0JTIwc2V0dXAlM0UlNUNuaW1wb3J0JTIwJTdCJTIwcmVmJTIwJTdEJTIwZnJvbSUyMCd2dWUnJTVDbiU1Q25jb25zdCUyMG1vZGVsJTIwJTNEJTIwcmVmKCU3QiU1Q24lMjAlMjAlMjAlMjBmb28lM0ElMjAndmFsdWUnJTJDJTVDbiUyMCUyMCUyMCUyMGdyb3VwJTNBJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMGZvbyUzQSUyMCduZXN0ZWQlMjB2YWx1ZSclNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiU3RCklM0IlNUNuJTVDbiUzQyUyRnNjcmlwdCUzRSU1Q24lNUNuJTNDdGVtcGxhdGUlM0UlNUNuJTIwJTIwJTIwJTIwJTNDRm9ybUtpdCUyMHR5cGUlM0QlNUMlMjJmb3JtJTVDJTIyJTIwJTQwc3VibWl0JTNEJTVDJTIyc3VibWl0JTVDJTIyJTIwdi1tb2RlbCUzRCU1QyUyMm1vZGVsJTVDJTIyJTIwJTNBYWN0aW9ucyUzRCU1QyUyMmZhbHNlJTVDJTIyJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ0Zvcm1LaXQlMjB0eXBlJTNEJTVDJTIydGV4dCU1QyUyMiUyMGxhYmVsJTNEJTVDJTIyZm9vJTVDJTIyJTIwbmFtZSUzRCU1QyUyMmZvbyU1QyUyMiUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NGb3JtS2l0JTIwdHlwZSUzRCU1QyUyMmdyb3VwJTVDJTIyJTIwbmFtZSUzRCU1QyUyMmdyb3VwJTVDJTIyJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ0Zvcm1LaXQlMjB0eXBlJTNEJTVDJTIydGV4dCU1QyUyMiUyMGxhYmVsJTNEJTVDJTIybmVzdGVkJTIwZm9vJTVDJTIyJTIwbmFtZSUzRCU1QyUyMmZvbyU1QyUyMiUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZGb3JtS2l0JTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRkZvcm1LaXQlM0UlNUNuJTIwJTIwJTIwJTIwJTNDcHJlJTIwd3JhcCUzRSU3QiU3QiUyMG1vZGVsJTIwJTdEJTdEJTNDJTJGcHJlJTNFJTVDbiUzQyUyRnRlbXBsYXRlJTNFJTVDbiUyMiUyQyUyMmFkZGVkJTIyJTNBdHJ1ZSU3RCU1RA&imports=JTdCJTIybmFtZSUyMiUzQSUyMkltcG9ydE1hcCUyMiUyQyUyMmVkaXRvciUyMiUzQSUyMiU3QiU1Q24lMjAlMjAlNUMlMjJ2dWUlNUMlMjIlM0ElMjAlNUMlMjJodHRwcyUzQSUyRiUyRmNkbi5qc2RlbGl2ci5uZXQlMkZucG0lMkZ2dWUlNDAzJTJGZGlzdCUyRnZ1ZS5lc20tYnJvd3Nlci5taW4uanMlNUMlMjIlNUNuJTdEJTVDbiUyMiU3RA)
the object is updated well but the generated html inputs have same name. I don't expect that (I suppose i'm not the only one).
several properties with same name (nested objects) should not have same html name to be consistent I guess. it is confusing if we look only at html to have several inputs with same name but that correspond to different things.

perhaps I have the wrong way to do...

**Comment by justin-schroeder** [comment]
@dominikklein is right — schema is not really intended to be updated — it should be thought of as a `<template>` which is immutable. You are *able* to update schema, but its not the intention. That said, keys are just as important in schema as they are in an actual vue template file. Perhaps we can do some hand holding about this in the docs — although the use case for keys in schema is exactly the same as standard Vue
