### ISSUE TITLE
How do I add a loading indicator to the button while the form is being submitted?

### ISSUE THREAD

**Issue by phillipmohr** [formkit/formkit#390]
### Describe the feature

I'm using FormKit with Nuxt 3 and the schema option and I'd like to add an loading indicator while the form is being submitted.

`Form.vue`
```vue
<FormKit type="form" @submit="handleSubmit" :submit-label="submitLabel">
    <FormKitSchema
        :schema="schema"
    />
</FormKit>
```

I already have a <LoadingSpinner /> component - is it possible to replace the submit button text with the component, while it's being submitted?

Or, is it possible to use my <Button> component as a submit button? 

`Button.vue`
```vue
<button v-bind="{ type }" class="btn btn-primary" :class="`btn-${size}`" :disabled="isLoading">
    <span v-if="!isLoading">
        <slot></slot>
    </span>
    <LoadingSpinner v-else />
</button>
```

Thanks in advance

**Comment by justin-schroeder** [comment]
Easiest way to is to put the form into the schema as well. Then you have direct access to all the context properties (of each immediate parent) https://formkit.link/8876041ff5a822fc4d8e0b60eb376ac6

https://formkit.com/api-reference/context
