### ISSUE TITLE
i18n: French (fr) translation

### ISSUE THREAD

**Issue by Dorkside** [formkit/formkit#392]
I’ve completed the French language translation.

```ts
// Please copy and paste the file your just downloaded here
```

[fr.ts.zip](https://github.com/formkit/formkit/files/9633256/fr.ts.zip)

PS: Github does not directly allow the generated typescript file.

**Comment by justin-schroeder** [comment]
Was there an issue with the [existing french one](https://github.com/formkit/formkit/blob/master/packages/i18n/src/locales/fr.ts) @Dorkside?

**Comment by Dorkside** [comment]
No I actually thought it was missing but I hadn't looked hard enough.

**Comment by justin-schroeder** [comment]
Ok! Thanks for the effort, if you see room for improvement feel free to create a better one!
