### ISSUE TITLE
Problem when two properties have same name in nested object

### ISSUE THREAD

**Issue by comhon-project** [formkit/formkit#394]
### Reproduction

[playground](https://formkit.com/playground?fkv=1.0.0-beta.10&fileTab=Playground.vue&files=JTVCJTdCJTIybmFtZSUyMiUzQSUyMlBsYXlncm91bmQudnVlJTIyJTJDJTIyZWRpdG9yJTIyJTNBJTIyJTNDc2NyaXB0JTIwc2V0dXAlM0UlNUNuJTIwJTIwJTIwJTIwaW1wb3J0JTIwJTdCJTIwcmVmJTIwJTdEJTIwZnJvbSUyMCU1QyUyMnZ1ZSU1QyUyMiUzQiU1Q24lNUNuY29uc3QlMjBmb28lMjAlM0QlMjByZWYoJTdCJTVDbiU1Q24lN0QpJTNCJTVDbiU1Q24lM0MlMkZzY3JpcHQlM0UlNUNuJTVDbiUzQ3RlbXBsYXRlJTNFJTVDbiUyMCUyMCUzQ0Zvcm1LaXQlNUNuJTIwJTIwJTIwJTIwdHlwZSUzRCU1QyUyMmZvcm0lNUMlMjIlNUNuJTIwJTIwJTIwJTIwdi1tb2RlbCUzRCU1QyUyMmZvbyU1QyUyMiU1Q24lMjAlMjAlM0UlNUNuJTIwJTIwJTIwJTIwJTNDRm9ybUtpdCU1Q24lMjAlMjAlMjAlMjAlMjAlMjB0eXBlJTNEJTVDJTIycmFkaW8lNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwbGFiZWwlM0QlNUMlMjJyYWRpbzElNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwbmFtZSUzRCU1QyUyMnJhZGlvMSU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0FvcHRpb25zJTNEJTVDJTIyJTVCJ29uZSclMkMlMjAndHdvJyU1RCU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlMkYlM0UlNUNuJTIwJTIwJTIwJTIwJTVDbiUyMCUyMCUyMCUyMCUzQ0Zvcm1LaXQlNUNuJTIwJTIwJTIwJTIwJTIwJTIwdHlwZSUzRCU1QyUyMmdyb3VwJTVDJTIyJTVDbiUyMCUyMCUyMCUyMCUyMCUyMGxhYmVsJTNEJTVDJTIyYmFyJTVDJTIyJTVDbiUyMCUyMCUyMCUyMCUyMCUyMG5hbWUlM0QlNUMlMjJiYXIlNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ0Zvcm1LaXQlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwdHlwZSUzRCU1QyUyMnJhZGlvJTVDJTIyJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGxhYmVsJTNEJTVDJTIycmFkaW8yJTVDJTIyJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMG5hbWUlM0QlNUMlMjJyYWRpbzElNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNBb3B0aW9ucyUzRCU1QyUyMiU1Qid5ZWxsb3cnJTJDJTIwJ2dyZWVuJyU1RCU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMkYlM0UlNUNuJTIwJTIwJTIwJTIwJTNDJTJGRm9ybUtpdCUzRSU1Q24lMjAlMjAlMjAlMjAlNUNuJTIwJTIwJTNDJTJGRm9ybUtpdCUzRSU1Q24lMjAlMjAlM0NwcmUlMjB3cmFwJTNFJTdCJTdCJTIwZm9vJTIwJTdEJTdEJTNDJTJGcHJlJTNFJTVDbiUzQyUyRnRlbXBsYXRlJTNFJTVDbiU1Q24lM0NzdHlsZSUyMHNjb3BlZCUzRSU1Q24lMkYqJTVDbnZhbmlsbGElMjBDU1MlMjBjYW4lMjBnbyUyMGhlcmUuJTVDbktlZXAlMjBzdHlsZXMlMjBzY29wZWQlMjB0byUyMGF2b2lkJTIwbXVsdGlwbGUlMjBmaWxlcyU1Q25vdmVyd3JpdGluZyUyMGVhY2glMjBvdGhlciUyMGluJTIwdGhlJTIwcmVuZGVyJTIwb3V0cHV0LiU1Q24qJTJGJTVDbiUzQyUyRnN0eWxlJTNFJTVDbiUyMiUyQyUyMmFkZGVkJTIyJTNBdHJ1ZSU3RCU1RA&imports=JTdCJTIybmFtZSUyMiUzQSUyMkltcG9ydE1hcCUyMiUyQyUyMmVkaXRvciUyMiUzQSUyMiU3QiU1Q24lMjAlMjAlNUMlMjJ2dWUlNUMlMjIlM0ElMjAlNUMlMjJodHRwcyUzQSUyRiUyRmNkbi5qc2RlbGl2ci5uZXQlMkZucG0lMkZ2dWUlNDAzJTJGZGlzdCUyRnZ1ZS5lc20tYnJvd3Nlci5taW4uanMlNUMlMjIlNUNuJTdEJTVDbiUyMiU3RA)

### Describe the bug

Using form and group,
when nested properties of an object have same name, html inputs have same name too. 
I guess inputs should not have the same name because it's clearly not same "things" they just share same property name.
We can see the unexpected behavior with radio buttons in playground example. the good properties are set but there can be only one radio button selected.

maybe input names should include parents names like "grand_parent.parent.name"
or maybe we should be able to set an `input-name` and an `property-name` when setting formkit component

### Environment

• Formkit : 1.0.0-beta.10

**Comment by justin-schroeder** [comment]
This is, unfortunately, how HTML works. radios are linked by name. However, if you take a look at the internals of radio inputs, you'll see this in the schema definition:

```js
{
  $el: 'input',
  attrs: {
    name: '$node.props.altName || $node.name',
    ...
  }
}
```

So we can write a simple plugin that changes the HTML name of a radio input, while leaving the name used in the data. For example:

https://formkit.link/e99b1ff402ae7fdea897e5652bfa87ae

**Comment by comhon-project** [comment]
@justin-schroeder your workaround works fine but, IMHO i should not have to create a plugin it should works without any changes from me.
for example by setting a kind of unique input name implicitly. or let me differentiate input name and property name for any formkit type (not in custom plugin).
the library permit to manage nested object so IMHO it should manager this case and maybe other cases that involve conflict on input name

**Comment by GustavoFenilli** [comment]
@justin-schroeder what if by default if not specified, radios that are part of a group get their parent name + their name for specificity? `${parent.name}.${name}`, or we could use the `token()` + their name, `${token()}.${name}`. this would improve DX.

**Comment by comhon-project** [comment]
up!
@GustavoFenilli , @justin-schroeder 
the right way to do is to use `alt-name` ? should I open another issue for the `alt-name` that doesn't work ?

**Comment by justin-schroeder** [comment]
Alt-name is not a content prop (yet) meaning you cannot use it outside the node, only by directly modifying the value on the node `node.props.altName`. It was intended mostly as an internal API for the [repeater](https://formkit.com/inputs/repeater) (which does this for you automatically)

**Comment by comhon-project** [comment]
So how can I handle my case (and others cases with input name conflicts) without using a custom plugin ?

**Comment by justin-schroeder** [comment]
Plugins aren't scary :) Just pop this into your project’s plugin’s and you'll be good to go:

```js
const radioAlt = (node) => {
  if (node.props.type === 'radio') {
    node.props.altName = `radio_number_${++i}`
  }
}
```

**Comment by comhon-project** [comment]
i'm not scared of plugins :) but IMHO it should be handled natively without any plugin.
What do you think ?
