### ISSUE TITLE
[Feature request] Populate forms with $formkit.load() and only pick schema data

### ISSUE THREAD

**Issue by maartenvanhunsel** [formkit/formkit#395]
### Describe the feature

While we populate forms with the value prop it would also be nice to load API responses directly into <Formkit> and only pick the defined schema values / structure. 

The downside of the :value prop is that all values that have been added will be directly transfered as form data when submitting the form (even if they are not in the schema).

With a new `$formkit.load` method it will be easy to populate data by e.g. API's and send only the fields you've defined.
```
onMounted(async () => {
      const { data } = await $fetch('/projects')
      $formkit.load.load(data)
})
```

**Comment by GustavoFenilli** [comment]
1. Where would load set its values to?
2. There is already the `node.input()` inside the form that sets the values.
3. You can remove any unwanted elements from the submit output using the `node.hook.submit`.

What would the advantages of this load method be over the current one?

**Comment by justin-schroeder** [comment]
These are good qualifying questions I'm also interested in knowing ☝️. Definitely not opposed to adding new features that improve the DX, just want to understand exactly what we're talking about here.

**Comment by maartenvanhunsel** [comment]
Well first of all @justin-schroeder you're right it's more / less a DX improvement because you can achieve this by submitting the form and removing the unnecessary data before sending to the server. (as  @GustavoFenilli told).

However I'm pretty convinced that adding this feature will keep your forms clean and maintainable. So for example: when we do have an upsert form for creating or updating a user. We want to populate the form when updating an existing user.
The server will return some data like:  (https://jsonplaceholder.typicode.com/users/1)
```
{
  "id": 1,
  "name": "Leanne Graham",
  "username": "Bret",
  "email": "Sincere@april.biz",
  "address": {
    "street": "Kulas Light",
    "suite": "Apt. 556", 
    "city": "Gwenborough",
    "zipcode": "92998-3874",
    "geo": {
      "lat": "-37.3159",
      "lng": "81.1496"
     }
  },
  "phone": "1-770-736-8031 x56442",
  "website": "hildegard.org",
  "company": {
    "name": "Romaguera-Crona",
    "catchPhrase": "Multi-layered client-server neural-net",
    "bs": "harness real-time e-markets"
  }
}
```

Let's say our form is filled with the following fields: (we only want to send these fields to the server)
- name
- email
- address.street
- address.city
- address.geo.lat
- address.geo.lng

The problem now is that we always need to manually perpare our forms (1) before populating our :value prop or (2) before submitting onSubmit. Not a real problem for small forms, but if you have many nested fields it's bad DX.

What I want to tell is that best practice for me is that the Form schema is leading how we prepare our data (for 95%) before submitting. The other 5% is for adding an ID to update an existing user for example.

Finally to give @GustavoFenilli answer on point 1: I would suggest to use $formkit.load for initially setting the form value, just as the same as the :value prop does. The only difference is that $formkit.load only populates if fields are matching the schema.

**Comment by justin-schroeder** [comment]
I see, so the idea here is you remove non-matching values from the form’s data object — is that correct? That's funny because Vue Formulate used to work that way and we got lots of complaints that people wanted it to work the other way around. However, I think you're right that we could provide a method to do so without needing to change the default behavior.

I'll look into this.

**Comment by justin-schroeder** [comment]
On that note, what if it was more explicitly named: `node.setMatchingValues({ ... })`

**Comment by maartenvanhunsel** [comment]
Yep that's correct. Well I do not really mind about the name, however I agree `setMatchingValues` is a better explanation of the function. Other examples: `setInitialValues()` | `loadInitial()`

Thanks!

**Comment by maartenvanhunsel** [comment]
If I do understand the usage of `node` correctly, it's meant to be used for single fields right?

If that's correct I would suggest to use `setMatchingValues` as a global function: (e.g. `$formkit.setMatchingValues(dataObjectFromServer)`
- Populate your entire form once, as a one-time action.
- Remove non-matching values from the form’s data object 

I tried to create a demo for better understanding: 
https://stackblitz.com/edit/nuxt3-formkit-fm8ugc?file=components/good-practice.vue

**Comment by GustavoFenilli** [comment]
Well the thing is, `$formkit` is not the form, and `node` is the node itself, meaning a form node is also a node.

`$formkit.setMatchingValues(dataObjectFromServer)` this in your example would be just a helper function, that removes unwanted fields before setting the values, it does not know about the node you're using, so it doesn't know about its schema.

If there was a global `setMatchingValues` it would need to specify in which node you're setting the values of so it would be more like `$formkit.setMatchingValues('nodeId', dataObjectFromServer)` or better using the current API already to get the node ( as `setMatchingValues` would be a node function instead ) `$formkit.get('nodeId').setMatchingValues(dataObjectFromServer)`

So what you want from `setMatchingValues` is basically what `input` already does [here](https://formkit.link/11fe869c7a63a9d9d79718efc39edd5b.), but populating only values that exist as children of that node.

**Comment by pitcher-maarten** [comment]
@GustavoFenilli ahaa that's perfect if we can extend  the current api like this: `$formkit.get('nodeId').setMatchingValues(dataObjectFromServer)`.

**Comment by GustavoFenilli** [comment]
Just as also a clarification it is already possible to do what you want with the current API using a plugin. [this](https://formkit.link/04cce49d6bf5491497127b8e00577f03) is a really simple way of doing only to the form level ( also not a plugin ) to just show you that removing fields before setting is possible using `node.input` and `node.hook.commit` ( pardon my crude example as it is just an example )

I think there is indeed a good point on adding a new function or extending the `node.input` API to do that automatically to improve DX tho.

**Comment by justin-schroeder** [comment]
I still think this is a great feature request, but I'm not sure the demand is there for it at the moment. if we include it in core it adds additional page weight to everyone’s site. Sadly, im going to close this in favor of being able to do this external to the package (userland). Fenilli’s example should be sufficient for most use cases.

https://formkit.link/1ebb5ff9ba0ef67ed35c69ec7fd79880
