### ISSUE TITLE
@formkit/vue FormKitIcon component: icon property is not reactive

### ISSUE THREAD

**Issue by nkoehring** [formkit/formkit#396]
### Reproduction

https://formkit.link/ae0bc9450d17c40940cd9d69f8cb1f80

### Describe the bug

`FormKitIcon` from `@formkit/vue` is not reactive. The icon does not change.

### Environment

• OS: any
• Browser: any
• Version: 1.0.0-beta.10

**Comment by justin-schroeder** [comment]
Thanks for the reproduction @nkoehring!
