### ISSUE TITLE
Input disappearing from node registry

### ISSUE THREAD

**Issue by totalhack** [formkit/formkit#397]
Using a schema-based multi-step form approach with `1.0.0-beta.10` I'm seeing some weird behavior with `get(some_node_name).value` where it stops being able to find the node. After adding a custom version of `get` and calling `getNode` directly in this situation I see indeed it no longer exists in the registry. Yet the input still exists on the form and using the form node's `value` shows the value is set. So it's like the registry is drifting from the actual form inputs/data.

I don't have any code that interacts with the registry to remove nodes, but do have some conditional schema logic to control when certain inputs are shown. I also tried to use `watchRegistry` but I'm not sure that can tell me much about what caused something to be removed. So my general question is -- what under the hood might be causing a node to be removed from the registry?

Apologies for not having an example repo on this -- it's in a private project at the moment so building a sharable reproduction might take a good chunk of time.

**Comment by GustavoFenilli** [comment]
A node could be removed if you have conditional logic to show inputs, as doing a `if` does remove the node, and the value could still exist if they have the `:preserve` prop at some level.

**Comment by totalhack** [comment]
OK, so this must somehow be related to the conditional logic, but it still doesn't quite make sense. There is no `:preserve` prop being set that I can see but the particular input is still there in the form and still has a value in the form `value` (this is expected based on my logic/settings, what's not expected is it for to be missing from the registry). 

I do reuse this question across multiple groups of questions within the schema. It is "reused" in the sense that it's the same schema structure and name, but I'm guessing formkit doesn't always reuse the node object and may be destroying/recreating it as answers on the first step change but failing to maintain the registry (maybe some weird race condition?) in the process. 

I have a workaround, which is to not use `$get` but instead pass the form node to a custom function since the `value` object is correct.

**Comment by justin-schroeder** [comment]
@totalhack nodes are stored in the registry according to their `id` — so if you re-use that id it *will* overwrite previous nodes (in the registry)

**Comment by totalhack** [comment]
hey @justin-schroeder, that makes sense, but still doesn't quite explain the scenario I'm seeing. If a new node is used with the same ID you'd still expect `$get(my_node_id)` in schema land or `getNode(my_node_id)` to work and just return the new node. Here neither of those work but the node with that ID exists on the form and is accessible in the form `value` object. So the registry is losing sync with the form.

**Comment by justin-schroeder** [comment]
Yeah you would expect that. The only other scenario that is possible here is if you have multiple instances of Vue running or multiple instances of FormKit running. This can happen "accidentally" by importing vue or formkit from disparate sources. It’s really easy to do, for example, using CDNs. However, I kinda doubt that is your scenario. One other thing you can do is is watch the registry explicitly to see what is going in and out:

```
import { watchRegistry } from '@formkit/core'

watchRegistry(({ payload: node }) => {
  // console.log or something
})

```

If you can provide a reproduction repository I'd be happy to take a look at it.

**Comment by justin-schroeder** [comment]
If we can get a reproduction for this we'll investigate further

**Comment by totalhack** [comment]
Hey @justin-schroeder, this is in a private project and I don't have cycles to recreate it at the moment. This multi-step form has a number of groups of conditional questions based on answers on the first step, and some common questions may be reused across those groups. I'm doing this all in schema land so they are at least the same question by name/schema, but duplicated JSON under another group in the schema. The groups themselves all have unique names. I'm not sure there is a better way to do it given my requirements (some questions repeat across groups, need to use JSON schema). 

I've worked around it with a custom utility function that just pulls from the value returned by `$get(form)` since that seems to always have the right value even if something has "disappeared" from the registry. 

I had tried to use `watchRegistry` in the past but couldn't interpret anything useful from it.

**Comment by justin-schroeder** [comment]
The `id` is what needs to be unique (rather than the `name`). Happy to take a look with a reproduction but sounds like you have a work around for now, so for housekeeping I'll close this out.

**Comment by totalhack** [comment]
Hey @justin-schroeder that's understandable. I just want to clarify one part though -- I **am** setting the ID of the input node in the schema and reusing that node across multiple conditional paths (again, this is a common question of a multi-step form that may conditionally occur in multiple paths, but always has the same "schema" defining it). The node name actually equals the node ID in this case.

So I know the same node name and ID are being used, and can observe that the node shows up in the output of `$get(form).value` and the input is usable in the form itself, but it is missing from the registry so `getNode` does not work. Shouldn't this be impossible? Even if there is something I'm doing that FormKit doesn't like, it has to be a bug that the registry and form could get out of sync, right?

FWIW I'm not sure if there is another way to achieve reusing questions cleanly in schema land. If you have ideas there, let me know, but hard-coding different IDs for the same question based on the subtree it shows up in is not a good maintainable solution IMO. Open to suggestions there but will have to stick with my workaround for now.

**Comment by totalhack** [comment]
I'm not comparing `$get(form).value` to `getNode(form)`. I'm saying `$get(form).value` has some input value nested in its structure as expected, but `getNode(my_input_node_id)` for that same node is blank because it's not in the registry. So it's set in the forms value but no equivalent node exists in the registry for that ID since it seems to be getting removed at some point due to conditional visibility logic.

**Comment by justin-schroeder** [comment]
Ok, I believe you but likewise dont have the cycles to stab in the dark till I can re-create it. If you get a playground reproduction worked (breaking? haha) — I'll gladly take a look!

**Comment by totalhack** [comment]
Totally understandable, and thank you for being so responsive. I'm only reiterating some things for clarity because I do believe it's possible there is a tricky bug underneath this, clearly not impacting other folks though (i know my use case is a bit more complicated) so I need to get you a reproduction at some point.
