### ISSUE TITLE
The outer section function does not work with $attrs.

### ISSUE THREAD

**Issue by fenilli** [formkit/formkit#399]
### Reproduction

https://formkit.link/416d1b23ed7f8eacf296bd61b21e81f9

### Describe the bug

When using the `$attrs` with the `outer()` it seens to be ignored, as using with the `boxLabel` works fine.

### Environment

• Version: `@formkit/vue: 1.0.0-beta.11`

**Comment by justin-schroeder** [comment]
this is true actually. utility functions don’t work on root nodes — this is worth addressing.

**Comment by justin-schroeder** [comment]
This has been working for quite some time.
