### ISSUE TITLE
Can't click the remove all button from the file type

### ISSUE THREAD

**Issue by GustavoFenilli** [formkit/formkit#400]
### Reproduction

https://formkit.link/1b0f2c7fd04f3664669a180f7430c32b

### Describe the bug

When click the `Remove All` inside the file type, the file input opens instead of removing the items.

### Environment

• OS: PopOS 22.04
• Browser: Chrome 106.0.5249.91
• Version: `@formkit/vue:1.0.0-beta.11`

**Comment by justin-schroeder** [comment]
Hmm, looks like some styles got jacked on genesis here 😬

**Comment by andrew-boyd** [comment]
I'm going to adjust the genesis theme to better account for this, but the _real_ issue here is that the `multiple` attribute is not creating a `data-multiple="true"` attribute on the `outer` section for the `file` input if you don't set it as `multiple="true"` in your template.

🚫 Broken
```
<FormKit
  type="file"
  multiple
/>
```

✅ Working
```
<FormKit
  type="file"
  multiple="true"
/>
```

https://formkit.link/d2c9187242bde934810e6283041dd751
