### ISSUE TITLE
Easy way to change field width

### ISSUE THREAD

**Issue by cookiejest** [formkit/formkit#402]
### Describe the feature

Seems really difficult to change the width of input fields with this library.

Does anyone have an example of how to do this?

Thanks!

**Comment by justin-schroeder** [comment]
Seems easy? https://formkit.link/04aea779b2f7f16dfee66f94f680dfa1

**Comment by cookiejest** [comment]
And what if you want to pass a dynamic width?

**Comment by GustavoFenilli** [comment]
Like so https://formkit.link/0a3893e578db56df21bf569f48b6852b

**Comment by cookiejest** [comment]
approach doesn't work when using formschema it seems?

**Comment by justin-schroeder** [comment]
Styling the inputs is up to you — if you're looking for style props `width="xxx"` — you won't find that in this library. FormKit is style agnostic so there is not overly tight coupling going on like that.
