### ISSUE TITLE
expect require('@formkit/vue/package.json'), but got require('@formkit/vue/dist/package.json')

### ISSUE THREAD

**Issue by lisonge** [formkit/formkit#404]
### Reproduction

https://runkit.com/lisonge/634410f2a9f7fc000807cf53

### Describe the bug

![image](https://user-images.githubusercontent.com/38517192/194868680-22c603e2-5701-40ff-816f-546ab1c5f854.png)

because of `package.json#exports`
<https://github.com/formkit/formkit/blob/c77a28c40bfecb8dbd4dca22f12e980abcaf55d9/packages/vue/package.json#L15>

I can not get package.json by require
[vite-plugin-monkey/src/node/_util.ts#L137-L142](https://github.com/lisonge/vite-plugin-monkey/blob/v2.7.0/packages/vite-plugin-monkey/src/node/_util.ts#L137-L142)
![image](https://user-images.githubusercontent.com/38517192/194869461-c9a4052e-8102-43f0-887f-3c0df3816728.png)

you can fix it by 
```json5
{
  "exports": {
    "./package.json": "./package.json",
  },
}
```

### Environment

• OS: [e.g. win10 or linux]
• Browser [e.g. chrome, safari]
• Version [1.0.0-beta.11]

**Comment by lisonge** [comment]
@justin-schroeder 

<https://github.com/formkit/formkit/commit/d1f04fd4dcaf1437b89d1544e96dc8f79c6fed9f>, hello, can you fix it ?

**Comment by justin-schroeder** [comment]
@lisonge this will be resolved in the next release (beta.12) Thanks for the report!
