### ISSUE TITLE
Validation message doesn't refresh label on i18n locale swap

### ISSUE THREAD

**Issue by albinabc** [formkit/formkit#405]
### Reproduction

https://github.com/albinabc/formkit-issue

### Describe the bug

Clone the repo and run `npm install` and `npm run dev`. 
Click the textbox and then outside it to get the validationmessage "Email is required", when pressing Swap language, you'll notice that the "is required" does get changed to (in our case) Swedish, but the string from i18n, which actually gets updated on the label property of the object, which is visible above the textbox, does not. Because of this, we get a mix of languages until you re-do the validation.

The behavior I'd expect is that the `data.messages.rule_required.value` gets updated with the value from `data.label`. It seems to be like this is a case of one property not being reactive, that maybe we're just passing a string somewhere instead of a reactive object? 

I followed this example to reproduce: https://formkit.com/essentials/internationalization#using-root-config
But it was not entirely covering, as you have no difference between the languages there, as "email" is used for both english and german. Here I'm using i18n as standalone, and would like to keep it that way to hold the translations in one place.

I'd be very grateful for a solution!

### Environment

• OS: macOS
• Browser: Firefox
• Version: 1.0.0-beta.11

**Comment by justin-schroeder** [comment]
Thanks for the quality reproduction — we're already tracking this issue on #297 so we'll close this one in favor of that one.
