### ISSUE TITLE
Date object methods inaccessible from Schema

### ISSUE THREAD

**Issue by justin-schroeder** [formkit/formkit#406]
### Reproduction

https://formkit.link/4aa42fbdea92d502c1e892b676111f5f

### Describe the bug

Requires further investigation, but chained calls to native date methods are not able to be called from schema. They result in a cryptic `TypeError: this is not a Date object.`. Likely this is due to these functions being called without the appropriate `this` context.

### Environment

• OS: MacOS
• Browser Chromium
• Version 106

**Comment by GustavoFenilli** [comment]
This also happens when trying to read `this` inside a `reactive` vue state as mentioned here https://formkit.link/d11c751d96b5d05ace9f4428aa67e08e

**Comment by justin-schroeder** [comment]
This is working now with the `@next` tag (hard reload on beta.12 in the payground) — although the second example in yours @GustavoFenilli still seems to be upset. Not sure why though, but I'm not sure that one is related?

**Comment by GustavoFenilli** [comment]
I think arrow functions do not have this attached to the reactive state, that was a mistake in example of mine, so probably fine as arrow functions should not be used as methods. I think this behaviour is expected as JS expecification.

**Comment by justin-schroeder** [comment]
Thats correct. Good catch I didnt notice that in the example. Arrow fns dont have a lexical this.
