### ISSUE TITLE
Add automatic `key` to FormKit inputs.

### ISSUE THREAD

**Issue by ruibaby** [formkit/formkit#407]
### Reproduction

https://formkit.link/42897b1eac7268cdb591541e2b2e4033

### Describe the bug

Reproduction steps:

1. According to https://formkit.link/42897b1eac7268cdb591541e2b2e4033
2. Enter some text in the `What coffee do you need?` input box
3. Toggle "Pick your drink" to tea
4. You can see that the content of the input box is still there, but the `data.tea` has no value

View the generated html:

```diff
  <div class="formkit-outer" data-family="text" data-type="text" data-complete="true">
    <div class="formkit-wrapper">
      <label class="formkit-label" for="coffee">What coffee do you need?</label>
      <div class="formkit-inner">
-        <!-- When Pick your drink for coffee -->
-        <input class="formkit-input" type="text" name="coffee" id="coffee">
+        <!-- When Pick your drink for tea -->
+        <input class="formkit-input" type="text" name="coffee" id="tea">
      </div>
    </div>
  </div>
```

I'm not sure if I'm missing something, please let me know if I need to provide additional information, and thanks to the contributors of formkit for such a powerful project.

### Environment

• OS: macOS 13
• Browser: Google Chrome Version 106.0.5249.91
• Version: 1.0.0-beta.11

**Comment by GustavoFenilli** [comment]
Vue is reusing the component that is why the contents are still there, you can add `key` to the inputs so that vue knows to not reuse it.

https://formkit.link/8f0da50b6ea89e6705178ad7543410e3

**Comment by ruibaby** [comment]
Thanks to @GustavoFenilli, this works, but when I try to build the form using the FormKit component, using v-if and v-else does not cause this issue. So I'm not really sure if this is a bug or not.

**Comment by justin-schroeder** [comment]
This is related to #528 — input root nodes are fragments. We could fix this by allowing singular root nodes.

**Comment by justin-schroeder** [comment]
Closing this in favor of #528
