### ISSUE TITLE
Autocomplete options are not reactive on search.

### ISSUE THREAD

**Issue by sashamilenkovic** [formkit/formkit#410]
### Reproduction

https://formkit.link/1f6acb64312d0ac4d912d0cc33b57d35

### Describe the bug

The autocomplete cannot handle reactive options when searching

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by GustavoFenilli** [comment]
Would this be related to autocomplete losing the ability to open the menu again after any value that is not inside the options is written?
