### ISSUE TITLE
Reactive value for 'hidden' input type

### ISSUE THREAD

**Issue by feend78** [formkit/formkit#411]
### Describe the feature

I am working on an application that uses formkit to collect information leading to the form making a 'recommendation' that the user can then choose to override or not. This means that in addition to my form's user-entered inputs, I have **initialRecommendation** and **finalRecommendation** values that I would like to include in the form data.

I am using schema to build this form, and I have tried to use **hidden** inputs with an if/then object in their **value** keys in order to serve as a sort of 'calculated field' for these values, but I am finding that, as is stated in the documentation, setting an input's values with the **value** prop/attribute only sets the inputs initial state, and is not reactive. As expected, I am seeing no updates the input's value as the user changes their selections.

Would it be possible to enable reactive if/then expression evaluation for **hidden** inputs used in schemas to allow them to serve as 'calculated fields'? Is there an alternative approach to this that I missed within the documentation?

**Comment by GustavoFenilli** [comment]
If I understand it correctly, you have a single hidden field where you want, based on other fields, change this fields value correct?

If so those nodes could have events at `commit` where you can then set the value of the hidden input using its id by `getNode(hiddenID).input()`

```js
getNode('name').on('commit', ({ payload }) => {
 getNode('initialRecommendation').input(payload); 
});
```

**Comment by feend78** [comment]
@GustavoFenilli, your read is correct, I appreciate the suggestion for an alternative, but my current approach uses FormKitSchema for the entire tool, and the calculations determining the recommendations frequently involve the value of several other related inputs, so the idea of having to access and set commit hooks on several inputs that have to all be aware of each others' current value seems like it will be a challenge to implement in a schema-friendly way.

To elaborate more on the use case, here is an example schema

```
const schema = [
  {
    $formkit: 'radio',
    name: 'somethingWrong',
    label: 'Has something bad happened?'
    options: ['yes', 'no'],
  },
  {
    $formkit: 'radio',
    name: 'isMyProblem',
    label: 'Is it your responsibility to fix?',
    options: ['yes', 'no'],
  },
  {
    $formkit: 'hidden',
    name: 'initialRecommendation'
    value: {
      if: '$formData.somethingWrong == yes && $formData.isMyProblem == yes',
      then: 'FIXIT',
      else: 'CHILL',
    },
  },
  {
    $el: 'h2',
    children: {
      if: '$formData.initialRecommendation == FIXIT',
      then: 'Better get to fixin it',
      else: 'Better relax',
    },
  {
    $formkit: 'radio',
    name: 'doIt',
    label: 'Gonna do that?',
    options: ['yes', 'no'],
  },
  {
    $formkit: 'hidden',
    name: 'finalRecommendation',
    value: {
      if: '$:($formData.initialRecommendation == FIXIT && $formData.doIt== no ) || ($formData.initialRecommendation == CHILL && $formData.doIt == yes)',
      then: 'CHILL',
      else: 'FIXIT',
    },
  },
  {
    $el: 'h2',
    children: {
      if: '$formData.finalRecommendation == FIXIT'
      then: 'Going to fix it',
      else: 'Going to chill',
    },
  },
]
```
In this instance, `formData` is a ref that is passed to the FormKit form component as `v-model` and to its FormKitSchema element as a key on the `data` prop. This example is also fairly simplified from my full-scale form, which calculates the recommendations based on 5 different inputs/values throughout the form. The fact that the schema expression engine can resolve the expressions reactively makes it the ideal mechanism for executing this logic, but the challenge has been how to save the computed outcome in a way that can make it back into the form data at submission time.

**Comment by GustavoFenilli** [comment]
Well for now you can use v-if to render nodes for those cases, even tho its not the most beatiful of methods as value is meant for a initial setup. But your case seens to have a valid point.
```js
{
    if: '$formData.somethingWrong == yes && $formData.isMyProblem == yes',
    then: {
        $formkit: 'hidden',
        name: 'initialRecommendation'
        value: 'FIXIT'
    },
    else: {
        $formkit: 'hidden',
        name: 'initialRecommendation'
        value: 'CHILL'
    }
}
```

**Comment by feend78** [comment]
Thank you for the workaround suggestion. Unfortunately, it doesn't appear to work. I modified your suggested code so that it also added a unique ID for each of the hiddden fields, and when I inspect the running code, I do see that the `id` changes, but the `value` doesn't.
```
{
    if: '$formData.somethingWrong == yes && $formData.isMyProblem == yes',
    then: {
        $formkit: 'hidden',
        id: 'fixitRec',
        name: 'initialRecommendation'
        value: 'FIXIT'
    },
    else: {
        $formkit: 'hidden',
        id: 'chillRec',
        name: 'initialRecommendation'
        value: 'CHILL'
    }
}
```
I will continue to experiment and try to find other options. How likely would it be that this feature would be implemented? I would be willing to work on it and submit a PR, but it's obvious this codebase is complex and sophisticated, so I'd likely need some coaching or advice on where to start.

**Comment by justin-schroeder** [comment]
Its unlikely that we would change the hydration model for just for hidden inputs — I think this would lead to mode confusion than it solves — but thats the good thing about plugins! This would be a pretty easy feature to add/solve using a simple plugin you can install globally.

Here’s an example @feend78 — in this case I have a plugin that creates a new "prop" called `computedValue` if that prop changes value, it automatically updates the actual value of the input:

https://formkit.link/36462739aeb7877febc86a8e5216daaf

That little plugin adds the functionality to any input in your app :)

**Comment by justin-schroeder** [comment]
Oh — and one other thing I would note, is the node architecture of FormKit doe not preclude you from adding arbitrary nodes to a form that are not even in the DOM. You can just do `createNode()` and then add that arbitrary node to a form, in that solution path hidden inputs aren’t even really necessary.

**Comment by feend78** [comment]
Thanks so much for the plugin suggestion, @justin-schroeder. It works exactly as I'd hoped!
