### ISSUE TITLE
The Brave browser password manager on iOS fills forms on page load; FormKit is not aware of these values

### ISSUE THREAD

**Issue by onodera-punpun** [formkit/formkit#414]
### Reproduction

https://formkit.com/playground?fkv=1.0.0-beta.11&fileTab=Playground.vue&files=JTVCJTdCJTIybmFtZSUyMiUzQSUyMlBsYXlncm91bmQudnVlJTIyJTJDJTIyZWRpdG9yJTIyJTNBJTIyJTNDc2NyaXB0JTIwc2V0dXAlM0UlNUNuY29uc3QlMjBzdWJtaXQlMjAlM0QlMjBhc3luYyUyMChjcmVkZW50aWFscyklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwY29uc29sZS5sb2coY3JlZGVudGlhbHMpJTVDbiU3RCUzQiU1Q24lM0MlMkZzY3JpcHQlM0UlNUNuJTVDbiUzQ3RlbXBsYXRlJTNFJTVDbiUyMCUzQ0Zvcm1LaXQlNUNuJTIwJTIwdHlwZSUzRCU1QyUyMmZvcm0lNUMlMjIlNUNuJTIwJTIwc3VibWl0LWxhYmVsJTNEJTVDJTIySW5sb2dnZW4lNUMlMjIlNUNuJTIwJTIwJTQwc3VibWl0JTNEJTVDJTIyc3VibWl0JTVDJTIyJTVDbiUzRSU1Q24lMjAlMjAlM0NGb3JtS2l0JTVDbiUyMCUyMCUyMCUyMG5hbWUlM0QlNUMlMjJlbWFpbCU1QyUyMiU1Q24lMjAlMjAlMjAlMjB0eXBlJTNEJTVDJTIyZW1haWwlNUMlMjIlNUNuJTIwJTIwJTIwJTIwcGxhY2Vob2xkZXIlM0QlNUMlMjJFLW1haWwlNUMlMjIlNUNuJTIwJTIwJTIwJTIwdmFsaWRhdGlvbiUzRCU1QyUyMnJlcXVpcmVkJTdDZW1haWwlNUMlMjIlNUNuJTIwJTIwJTJGJTNFJTVDbiU1Q24lMjAlMjAlM0NGb3JtS2l0JTVDbiUyMCUyMCUyMCUyMG5hbWUlM0QlNUMlMjJwYXNzd29yZCU1QyUyMiU1Q24lMjAlMjAlMjAlMjB0eXBlJTNEJTVDJTIycGFzc3dvcmQlNUMlMjIlNUNuJTIwJTIwJTIwJTIwcGxhY2Vob2xkZXIlM0QlNUMlMjJXYWNodHdvb3JkJTVDJTIyJTVDbiUyMCUyMCUyMCUyMHZhbGlkYXRpb24lM0QlNUMlMjJyZXF1aXJlZCU1QyUyMiU1Q24lMjAlMjAlMkYlM0UlNUNuJTNDJTJGdGVtcGxhdGUlM0UlNUNuJTVDbiUzQ3N0eWxlJTIwc2NvcGVkJTNFJTVDbiUyRiolNUNudmFuaWxsYSUyMENTUyUyMGNhbiUyMGdvJTIwaGVyZS4lNUNuS2VlcCUyMHN0eWxlcyUyMHNjb3BlZCUyMHRvJTIwYXZvaWQlMjBtdWx0aXBsZSUyMGZpbGVzJTVDbm92ZXJ3cml0aW5nJTIwZWFjaCUyMG90aGVyJTIwaW4lMjB0aGUlMjByZW5kZXIlMjBvdXRwdXQuJTVDbiolMkYlNUNuJTNDJTJGc3R5bGUlM0UlNUNuJTIyJTJDJTIyYWRkZWQlMjIlM0F0cnVlJTdEJTVE

### Describe the bug

The Brave browser on iOS has a password manager that instantly prefills values such as username and password upon loading a page. However formkit seems to be unaware of these filled fields and instead sees them as just being empty.

This is strange, because the Firefox password manager visually does the exact same thing, but formkit does pick up these values.

### Environment

• OS: iOS
• Browser: Brave
• Version: Newest

**Comment by justin-schroeder** [comment]
By default FormKit does not put any `autocomplete` attribute on inputs. So some password managers and browsers will still attempt to determine what a given input is asking for and suggest it with their password manger. You can however, add attributes to your inputs to give them (brave) a nudge in the correct direction. For example:

```vue
<FormKit
  type="password"
  autocomplete="password"
/>
```

You can read about the autocomplete attribute from MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete
