### ISSUE TITLE
Select input initialized with null value doesn't have good value

### ISSUE THREAD

**Issue by comhon-project** [formkit/formkit#415]
### Reproduction

[playground](https://formkit.com/playground?fkv=1.0.0-beta.11&fileTab=Playground.vue&files=JTVCJTdCJTIybmFtZSUyMiUzQSUyMlBsYXlncm91bmQudnVlJTIyJTJDJTIyZWRpdG9yJTIyJTNBJTIyJTNDc2NyaXB0JTIwc2V0dXAlM0UlNUNuJTIwJTIwJTIwJTIwaW1wb3J0JTIwJTdCJTIwcmVhY3RpdmUlMjAlN0QlMjBmcm9tJTIwJ3Z1ZSclNUNuJTVDbmNvbnN0JTIwc3RhdGUlMjAlM0QlMjByZWFjdGl2ZSglN0IlNUNuJTIwJTIwdmFsdWUxJTNBJTIwbnVsbCUyQyU1Q24lMjAlMjB2YWx1ZTIlM0ElMjAnJyU1Q24lN0QpJTNCJTVDbmNvbnN0JTIwb3B0aW9ucyUyMCUzRCUyMCU3QiU1Q24lMjAlMjAndGVzdCclM0ElMjAndGVzdCclMkMlNUNuJTdEJTNCJTVDbiU1Q25mdW5jdGlvbiUyMHN1Ym1pdCgpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGFsZXJ0KCdzdWJtaXRlZCcpJTNCJTVDbiU3RCU1Q24lM0MlMkZzY3JpcHQlM0UlNUNuJTVDbiUzQ3RlbXBsYXRlJTNFJTVDbi0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0lMjB3aXRoJTIwbnVsbCUyMC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tJTVDbiUzQ0Zvcm1LaXQlMjB0eXBlJTNEJTVDJTIyZm9ybSU1QyUyMiUyMCU0MHN1Ym1pdCUzRCU1QyUyMnN1Ym1pdCU1QyUyMiUyMCUzQWFjdGlvbnMlM0QlNUMlMjJmYWxzZSU1QyUyMiUzRSU1Q24lMjAlMjAlMjAlMjAlM0NGb3JtS2l0JTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHR5cGUlM0QlNUMlMjJzZWxlY3QlNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwdi1tb2RlbCUzRCU1QyUyMnN0YXRlLnZhbHVlMSU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBsYWJlbCUzRCU1QyUyMnRlc3QlNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwcGxhY2Vob2xkZXIlM0QlNUMlMjJwbGFjZWhvbGRlciU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBuYW1lJTNEJTVDJTIydGVzdCU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0FvcHRpb25zJTNEJTVDJTIyb3B0aW9ucyU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB2YWxpZGF0aW9uJTNEJTVDJTIycmVxdWlyZWQlNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUzQ0Zvcm1LaXQlMjAlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwc3R5bGUlM0QlNUMlMjJ3aWR0aCUzQSUyMDEwMCUyNSUzQiUyMHBhZGRpbmclM0ElMjAxcmVtJTNCJTIwbWFyZ2luJTNBJTIwMXJlbSUyMDAlM0IlNUMlMjIlMjB0eXBlJTNEJTVDJTIyc3VibWl0JTVDJTIyJTIwJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGxhYmVsJTNEJTVDJTIyc3VibWl0JTVDJTIyJTVDbiUyMCUyMCUyMCUyMCUyRiUzRSU1Q24lM0MlMkZGb3JtS2l0JTNFJTVDbi0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0lMjB3aXRoJTIwJyclMjAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSU1Q24lM0NGb3JtS2l0JTIwdHlwZSUzRCU1QyUyMmZvcm0lNUMlMjIlMjAlNDBzdWJtaXQlM0QlNUMlMjJzdWJtaXQlNUMlMjIlMjAlM0FhY3Rpb25zJTNEJTVDJTIyZmFsc2UlNUMlMjIlM0UlNUNuJTIwJTIwJTIwJTIwJTNDRm9ybUtpdCU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB0eXBlJTNEJTVDJTIyc2VsZWN0JTVDJTIyJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHYtbW9kZWwlM0QlNUMlMjJzdGF0ZS52YWx1ZTIlNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwbGFiZWwlM0QlNUMlMjJ0ZXN0JTVDJTIyJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHBsYWNlaG9sZGVyJTNEJTVDJTIycGxhY2Vob2xkZXIlNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwbmFtZSUzRCU1QyUyMnRlc3QlNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNBb3B0aW9ucyUzRCU1QyUyMm9wdGlvbnMlNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwdmFsaWRhdGlvbiUzRCU1QyUyMnJlcXVpcmVkJTVDJTIyJTVDbiUyMCUyMCUyMCUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlM0NGb3JtS2l0JTIwJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHN0eWxlJTNEJTVDJTIyd2lkdGglM0ElMjAxMDAlMjUlM0IlMjBwYWRkaW5nJTNBJTIwMXJlbSUzQiUyMG1hcmdpbiUzQSUyMDFyZW0lMjAwJTNCJTVDJTIyJTIwdHlwZSUzRCU1QyUyMnN1Ym1pdCU1QyUyMiUyMCU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBsYWJlbCUzRCU1QyUyMnN1Ym1pdCU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlMkYlM0UlNUNuJTNDJTJGRm9ybUtpdCUzRSU1Q24lM0NwcmUlMjB3cmFwJTNFJTdCJTdCJTIwc3RhdGUlMjAlN0QlN0QlM0MlMkZwcmUlM0UlNUNuJTNDJTJGdGVtcGxhdGUlM0UlNUNuJTVDbiUzQ3N0eWxlJTIwc2NvcGVkJTNFJTVDbiUyRiolNUNudmFuaWxsYSUyMENTUyUyMGNhbiUyMGdvJTIwaGVyZS4lNUNuS2VlcCUyMHN0eWxlcyUyMHNjb3BlZCUyMHRvJTIwYXZvaWQlMjBtdWx0aXBsZSUyMGZpbGVzJTVDbm92ZXJ3cml0aW5nJTIwZWFjaCUyMG90aGVyJTIwaW4lMjB0aGUlMjByZW5kZXIlMjBvdXRwdXQuJTVDbiolMkYlNUNuJTNDJTJGc3R5bGUlM0UlNUNuJTIyJTJDJTIyYWRkZWQlMjIlM0F0cnVlJTdEJTVE&imports=JTdCJTIybmFtZSUyMiUzQSUyMkltcG9ydE1hcCUyMiUyQyUyMmVkaXRvciUyMiUzQSUyMiU3QiU1Q24lMjAlMjAlNUMlMjJ2dWUlNUMlMjIlM0ElMjAlNUMlMjJodHRwcyUzQSUyRiUyRmNkbi5qc2RlbGl2ci5uZXQlMkZucG0lMkZ2dWUlNDAzJTJGZGlzdCUyRnZ1ZS5lc20tYnJvd3Nlci5taW4uanMlNUMlMjIlNUNuJTdEJTVDbiUyMiU3RA)

### Describe the bug

problem :
when initialize select with `null` value there are two problems
* the first option is selected instead of display placeholder
* the model is not updated (if we have only one option and value is required, we are stuck)

expected : 
when value is null, it should display placeholder (like when value is an empty space)

thanks in advance :)

### Environment

beta 11

**Comment by justin-schroeder** [comment]
Thanks for the good reproduction!
