### ISSUE TITLE
File input has no styling when used with tailwind

### ISSUE THREAD

**Issue by 1lander** [formkit/formkit#416]
### Reproduction

https://formkit.com/playground?fkv=1.0.0-beta.11&fileTab=Playground.vue&files=JTVCJTdCJTIybmFtZSUyMiUzQSUyMlBsYXlncm91bmQudnVlJTIyJTJDJTIyZWRpdG9yJTIyJTNBJTIyJTNDc2NyaXB0JTIwc2V0dXAlM0UlNUNuJTJGJTJGJTIwRVNNJTIwaW1wb3J0cyUyMGFyZSUyMHN1cHBvcnRlZCUyMGZyb20lMjBVUkxzJTIwKGh0dHBzJTNBJTJGJTJGY2RuLi4uKSU1Q24lMkYlMkYlMjBhcyUyMHdlbGwlMjBhcyUyMHNlY29uZGFyeSUyMHBsYXlncm91bmQlMjBmaWxlcyUyMCguJTJGT3RoZXJGaWxlLnZ1ZSkuJTVDbiUzQyUyRnNjcmlwdCUzRSU1Q24lNUNuJTNDdGVtcGxhdGUlM0UlNUNuJTIwJTIwJTNDRm9ybUtpdCU1Q24lMjAlMjAlMjAlMjB0eXBlJTNEJTVDJTIyZmlsZSU1QyUyMiU1Q24lMjAlMjAlMjAlMjBsYWJlbCUzRCU1QyUyMkZvcm1LaXQlMjBJbnB1dCU1QyUyMiU1Q24lMjAlMjAlMjAlMjBoZWxwJTNEJTVDJTIyZWRpdCUyMG1lJTIwdG8lMjBnZXQlMjBzdGFydGVkJTVDJTIyJTVDbiUyMCUyMCUyMCUyMGZpbGUtaXRlbS1pY29uJTNEJTVDJTIyZmlsZUltYWdlJTVDJTIyJTVDbiUyMCUyMCUyRiUzRSU1Q24lM0MlMkZ0ZW1wbGF0ZSUzRSU1Q24lMjIlMkMlMjJhZGRlZCUyMiUzQXRydWUlN0QlNUQ&css-framework=tailwind&cssFramework=tailwind&imports=JTdCJTIybmFtZSUyMiUzQSUyMkltcG9ydE1hcCUyMiUyQyUyMmVkaXRvciUyMiUzQSUyMiU3QiU1Q24lMjAlMjAlNUMlMjJ2dWUlNUMlMjIlM0ElMjAlNUMlMjJodHRwcyUzQSUyRiUyRmNkbi5qc2RlbGl2ci5uZXQlMkZucG0lMkZ2dWUlNDAzJTJGZGlzdCUyRnZ1ZS5lc20tYnJvd3Nlci5taW4uanMlNUMlMjIlNUNuJTdEJTVDbiUyMiU3RA

### Describe the bug

When using the file input within a tailwind project there is no default styling to any attributes on the input including icons.

### Environment

• OS: macOS
• Browser: Brave
• Version: 1.44.112 Chromium: 106.0.5249.119

**Comment by justin-schroeder** [comment]
Thats correct! FormKit does not ship default styles if you are using tailwind. It’s a blank canvas for you :)

Feel free to checkout this guide on how to create a tailwind theme for FormKit: https://formkit.com/guides/create-a-tailwind-theme
