### ISSUE TITLE
Prototyping creates misbehaviour - Array.prototype

### ISSUE THREAD

**Issue by ThatDeveloper** [formkit/formkit#419]
### Reproduction

https://formkit.link/3e540ddf729da201015b3286a2f8782a

### Describe the bug

As soon as you have anywhere in your application a prototype, formkit misbehaves. In my particular case it using the Schema with `$formkit: "select"` +  `Array.prototype`, but maybe there could be other prototypes / combinations. This is very unfortunate as, I assume, a lot of people use prototypes like this.

---

I use this code in some of my libraries:
```
if (!Array.prototype.selectMany) {
    Array.prototype.selectMany = function (fn) {
      return this.map(fn).reduce(function (x, y) { return x.concat(y); }, []);
  };
}
```
(NOTE: It does not matter what comes after "Array.prototype.". As soon as it is present, the bug exists.)

---

By using FormKitSchema with the following schema you get **4** entries/options instead of **3** in the select input:
```
<script setup>
import { reactive } from 'vue'

const schema = [
 {
   $formkit: 'select',
    name: 'customerTypeId',
    validation: 'required',
    options: [
        { value: 1, label: "Guest" },
        { value: 2, label: "Customer" },
        { value: 3, label: "Partner" }
    ]
 }
];

const data = reactive({});
</script>

<template>
  <div>
    <FormKitSchema 
      :schema="schema"
      :data="data"
     />
  </div>
</template>
```

Expected Result: "Guest", "Customer", "Partner"
Result: "Guest", "Customer", "Partner", undefined

### Environment

• OS: Windows
• Browser: Chrome
• Version: 106.0.5249.119

**Comment by GustavoFenilli** [comment]
Well changing native prototypes generally is a bad idea, unless you're doing to polyfill.

I would say having a helper function or a helper object is better for these cases.

**Comment by ThatDeveloper** [comment]
@GustavoFenilli While I do understand that it is generally not best-practice, I am sure a lot of people and libraries use it. I already changed it on my end for this project, but I think this is an issue a lot of people would run into & not everybody has a whole day to debug a project to find out from where that issue comes from. Is that something that could be fixed in the library?

**Comment by justin-schroeder** [comment]
Oh yeah — @GustavoFenilli is right — modifying prototypes is a big no-no. Not for FormKit specifically, just any third party code that wants to loop over an array, for example, is going to get screwed by this. To be crystal clear, **is not a FormKit bug** and cannot/will not be "fixed" in FormKit — all we are doing is iterating over an array that you've added a property to globally.

Way back in the day, before even jQuery, us old devs used to use a library called `prototype.js` which explicitly modified prototypes. But it broke so much interoperability it was eventually lost to history as a bad lesson of "what not to do".

I would *highly* recommend not modifying builtin prototypes, FormKit wont be the last issue you find out there! However, if you are going to modify prototype, at least make those properties non-enumerable.

Here's a full reproduction of your bug (again, not a FormKit bug): https://formkit.link/534442088094e78e2a3b1c10282525ed

Again don’t do this, but if you are going to do this, you should at least extend the prototype without making a property enumerable:
https://formkit.link/f58b46ee387e1350b6299f5119bfbf3c

**Comment by justin-schroeder** [comment]
Ok fine @ThatDeveloper hahah, you convinced me to make a small change to "fix" this. But still folks — lets not modify prototype. `@formkit/vue@next` has this patched now.
