### ISSUE TITLE
Repeater: `.formkit-control` needs `position:relative`

### ISSUE THREAD

**Issue by ThatDeveloper** [formkit/formkit#424]
### Reproduction

https://formkit.link/eef9b50248b1e52701debb58cb07afbc

### Describe the bug

`.formkit-control-label` class should have e.x. `z-index: -1` and / or `opactiy: 0`, or another way of hiding as `position: absolute` and `left: -999px` are still on screen if they are in a `position: relative` container.

What exactly are these labels used for if they are not visible? Screen readers? Any "right" solution to that, except for changing the class?

### Environment

• OS: Windows
• Browser: Chrome
• Version: 106.0.5249.119

**Comment by justin-schroeder** [comment]
Are you saying this is a bug with the genesis theme, or your personal theme? The parent `.formkit-controls` has `overflow:hidden` in genesis so all those values are not visible no matter how wide the screen is. The labels are there for accessibility purposes. Can you provide a genesis reproduction of this issue?

**Comment by ThatDeveloper** [comment]
@justin-schroeder Here you go: https://formkit.link/eef9b50248b1e52701debb58cb07afbc
If you size it further to the right, you can see it. At least on my screen it is there without changing the size at all.

![image](https://user-images.githubusercontent.com/12497431/197218553-a4403859-6f7a-4112-8366-b9292dd5984d.png)


I would recommend to use `overflow: hidden` on `.formkit-fieldset`, which seem to fix this, and maybe increase `left: -999px` to more than that?

**Comment by justin-schroeder** [comment]
Should have `position:relative` on `.formkit-controls`. We wouldn't want the fieldset to have overflow hidden or children couldn't overflow their container (like dropdowns). You can add that as a workaround for now:

```css
.formkit-controls {
  position: relative;
}
```

This will eventually make it into the pro package too.

**Comment by sashamilenkovic** [comment]
`position: relative` has been added to `.formkit-controls` in the pro package.
