### ISSUE TITLE
Commit hook not running on last input of form

### ISSUE THREAD

**Issue by DNA** [formkit/formkit#425]
When assigning a commit hook to inputs inside a form with a value object associated, all hooks run except for the last input.

I've made an example about this behavior on playground. On it I've added a plugin that adds a commit hook that changes all inputs to uppercase:
https://formkit.link/f08f72435fde470a1039462718edb06f

The generated form shows that the last input is still in lowercase (but get uppercase'd correctly if you change it's value)

**Comment by justin-schroeder** [comment]
Hi @DNA 👋

Hooks are best registered outside the "created". The reason your first two inputs were run was subsequent node additions re-ran the input hooks, so only the last one wasn't called. If you instead hoist these to the root of the plugin, all should be well:

https://formkit.link/2f7e9be12556fb7087e66101d23b2ba5

Hope that helps!

**Comment by DNA** [comment]
Hi @justin-schroeder, thanks for the fast reply! 😄 

And it makes sense, I've changed it on my code and it worked fine! I think this `created` was a leftover from a previous test… Sorry for the non-bug report 😅
