### ISSUE TITLE
Add support for `optgroup` to `select`

### ISSUE THREAD

**Issue by hacknug** [formkit/formkit#426]
### Describe the feature

Just [like we had with `vue-formulate`](https://vueformulate.com/guide/inputs/types/select/#option-grouping), I think we need a way to specify option groups for select options.

Given `formkit` aims to have a shared API between input types, perhaps we could look into adding a `group` key to each of our options so we don't have to change the `options` prop for `optionGroups`. The value of `group` could be stringified to use as the group label inside the browser's `optgroup` or replaced by the matching `label` from one of the provided `optionGroups`.

This would allow to render those options grouped when using a `select` but at the same time re-use the props if we change that input for a different type that also supports `options` (eg. `checkbox` or `radio`).

Simple config example:
```js
const schema = [
  {
    $formkit: 'select',
    name: 'genre',
    label: 'Genre',
    options: [
      { id: 28, name: 'Action', group: 'movie' },
      // NOTE: More options with movie genres
      { id: 10759, name: 'Action & Adventure', group: 'tv' },
      // NOTE: More options with tv show genres
    ],
  },
]
```

Complex config example:
```js
const schema = [
  {
    $formkit: 'select',
    name: 'genre',
    label: 'Genre',
    options: [
      { id: 28, name: 'Action', group: 'movie' },
      // NOTE: More options with movie genres
      { id: 10759, name: 'Action & Adventure', group: 'tv' },
      // NOTE: More options with tv show genres
    ],
    optionGroups: [
      { label: 'Movie', value: 'movie' },
      { label: 'TV', value: 'tv' },
    ],
  },
]
```

Does this make sense? I can try to explain more but I don't think I care as much about the API as I do about having support for it in some kind of way. You probably know better how we should implement this.

Let me know if there's anything I can do to help 💖

**Comment by GustavoFenilli** [comment]
I think it would be a good idea, but I thinkg a better API would be this, it would be easier to render the group, and there could be options with no groups.
```
options: [
  { group: 'Movie', options: [
    { value: 28, label: 'Action' },
  ] }
]
```

**Comment by justin-schroeder** [comment]
Valid proposal. In the meantime, you can use the default slot (which does come with some drawbacks), but was not an option with Vue Formulate:

https://formkit.link/ba77f3dbd7f6bb6daf970eb814a1fe72

**Comment by ThatDeveloper** [comment]
@justin-schroeder Will this also be implemented in autocomplete?

**Comment by justin-schroeder** [comment]
The big question we have about this is how we implement this with async options. As options load, we dont think they should be added to respective "groups" somewhere higher up the list. That would make for a horrific UX. If we had an outer wrapper as @GustavoFenilli proposed, async wouldn't even be possible. We are planning to implement something but need to play around with the API design a bit.
