### ISSUE TITLE
How to translate field names according to user locale?

### ISSUE THREAD

**Issue by JesterIruka** [formkit/formkit#427]
Even though I'm using the pt i18n locale, I couldn't find a way to translate fields, such as "password", "weight" and "username"

If the user locale is PT, I must translate this fields to "Senha", "Peso" and "Usuário" respectively
Looking at the source code, the `sentence` only apply a upper case first.

Is there a way to translate field names as well?

**Comment by JesterIruka** [comment]
Just to add more context, I'm talking about the form validation, messages like: "Password is required", which in Portuguese actually show "Password é obrigatório"

**Comment by justin-schroeder** [comment]
FormKit doesn't try to solve general i18n, so anything that is prop based (like `label`) should use your own i18n utility. You might want to use something like https://vue-i18n.intlify.dev

**Comment by JesterIruka** [comment]
> FormKit doesn't try to solve general i18n, so anything that is prop based (like `label`) should use your own i18n utility. You might want to use something like https://vue-i18n.intlify.dev

This issue is not about label, it's about the validation message itself.
Since the database is designed using english, the input[name] will always be in English, leading to incorrect translations.

In korean for instance, the validation message would be "Password 필수 값입니다" if the input[name] is "password"

As reference, in Laravel you can specify your attributes translations for each language.
![image](https://user-images.githubusercontent.com/49654905/197441449-fcc61502-bbe7-4f89-be56-7d09667771e1.png)

**Comment by JesterIruka** [comment]
> FormKit doesn't try to solve general i18n, so anything that is prop based (like `label`) should use your own i18n utility. You might want to use something like https://vue-i18n.intlify.dev

Just tested here, I dind't know that the validator was capable of using the label, which was empty in my scenario.
I thought it was limited to the input[name]

Problem solved.

**Comment by justin-schroeder** [comment]
@JesterIruka thanks for the sponsorship too :) If you want early access to FormKit Pro, dm me on discord with your email address and I'll put you on the whitelist.
