### ISSUE TITLE
Select Input - default value behaviour if no initial value is set

### ISSUE THREAD

**Issue by ThatDeveloper** [formkit/formkit#429]
### Describe the feature

As requested, here is an attempt for this feature request, @justin-schroeder. 

Add code to formkit "select" to initially set value without the users need to modify model data. Especially if the options at the start are `const options = ref([]);`, and get populated later e.x. from server, it should be possible that formkit "select" chooses the appropriate option and sets that value to the result model. This of course only if there was no initial value set anyway.

Example options:
```js
const options = ref([]);

//... some code that loads the options
options.value = [
  { value: 1, label: "A" },
  { value: 1, label: "B", selected: true },
  { value: 1, label: "C" },
];
```

This is the code / functionality written in form of a plugin:
```js
export function selectInitialWhenSelectOptionsChanged(node) {
  if (node.type !== "input" || node.context.type !== "select")
    return;

  node.on('prop:options', ({ payload }) => {
    if (payload.length === 0 || node.value !== undefined) //do not execute if payload array is empty or initial value is set
      return;
    
    let toSelect = payload.find((el) => el.selected); //get selected option
    if (toSelect === undefined)
      toSelect = payload[0]; //if no selected option is found, select first one

    node.input(toSelect.__original);
  })
}
```

**Comment by justin-schroeder** [comment]
Its been a long time since we looked into this issue 😂.

I sort of get this but I also sort of dont — why would the `value` prop of the select not be sufficient here?
