### ISSUE TITLE
Add option to debounce the `options` when it is a function.

### ISSUE THREAD

**Issue by ThatDeveloper** [formkit/formkit#430]
### Reproduction

https://formkit.link/6405cfc5177b3fee6bd3721992df7ffb

### Describe the bug

Autocomplete does not respect delay / debounce. This is rather bad, especially when using a function to fetch data from an api.
It would be great to set a debounce time before options func gets called.

### Environment

• OS: Windows
• Browser: Chrome
• Version: 106.0.5249.119

**Comment by justin-schroeder** [comment]
The delay prop is not for debouncing your options api call, but the communication of a new value to the rest of the form. I think what you're suggesting here is valid, but should be a feature enhancement instead. The current assumption is you provide a debounced function for options if you need that.

**Comment by justin-schroeder** [comment]
Ooops, I mispoke — we actually already have a `debounce` prop for this. The default is 200ms — but you can change the value by passing a different number. It’s missing from our props table! So we'll get that added.
