### ISSUE TITLE
Autocomplete options misbehaving / duplicating when being used fast, repeatedly or with pasted content (cache related?)

### ISSUE THREAD

**Issue by ThatDeveloper** [formkit/formkit#431]
### Reproduction

https://formkit.link/c99d6d313aa88c350bff3f71b2a50a67

### Describe the bug

I don't really know how to describe the bug, so I just used the examples & try to explain with them.
While below I use "Lord of the Rings: The Two Towers", which would be rather an edge case that someone uses it like that, this also happens when you use 1 letter, quickly write e.x. "G" and then either copy / select / paste or delete / write, etc. This happens a lot. It is not hard evidence, but I asked a friend to try my form and he discovered this immediately.

1. Open Playground
2. Enter or Paste "Lord of the Rings: The Two Towers"
3. Select the entered text
4. Copy / Paste it again

=> Now you have multiple entries.

![image](https://user-images.githubusercontent.com/12497431/198284686-86325f28-4d94-4e74-bdf4-cd03ad68740e.png)

---

**Why is this even more a problem?**

When writing e.x. "G", the func returns the results, when you delete "G" the result is still there (assume a cached version) when you click on the autocomplete. This + the above combined creates a pretty strange user experience.
If you know have a method that depends on a value like so:

(usually you would use `getCities: async ({ search, page, hasNextPage })`, but you do not have access to the model value at that point)

```js
getCities: async (input) => {
        const search = input.searchValue;
        if (search === "")
            return [];

        const take = 20;
        const gqlPage = input.page - 1;
        const whereClause = "startsWith" //todo: could also be contains
        const countryId = input.node.parent.value.countryId; //<--- watch here

        return Promise.resolve({data:{hasNextPage:true,items:[]}}/*logic to get data*/).then(e => {
            if (e.data.hasNextPage)
                hasNextPage();

            return e.data.items.map(e => {
                return {
                    value: e.id,
                    label: e.name
                }
            });
        })
    }
```

You have the issue that if you get the duplicate "options" entries, that they can have the same label but different value, as there is a cached version from before shown.

I hope it is somehow understandable. I am sorry for not being able to provide more details. I can't debug the pro "autocomplete" code. Willing to show problem live.

### Environment

• OS: Windows
• Browser: Chrome
• Version: 106.0.5249.119

**Comment by justin-schroeder** [comment]
Great find, I'm able to duplicate it so we'll work on fixing this — only question I have is your explanation of the typing `G` and then deleting it and the same options still being visible? That shouldn't be the case — when I go to the movies example and type `G` then delete `G` the results go away. Is your experience different than that?

**Comment by ThatDeveloper** [comment]
The issue with that is the source of the playground example. When you type G it is too much matches. It also duplicated them, you just can't see them. But I was not able to create a different playground example.

**Comment by ThatDeveloper** [comment]
@justin-schroeder Just found out, it might be, that the behaviour is even more strange when using `selectionAppearance: "option"` on the input. 
"G", on my end, is just an example, where 1 result comes back.

1. Write "G"
2. Select result
3. Click cross to remove option
4. Write "G"

=> Duplicated

**Comment by sashamilenkovic** [comment]
@ThatDeveloper Do you want to hard reload your playground https://formkit.link/c99d6d313aa88c350bff3f71b2a50a67 and give it another try? This should be fixed.

**Comment by ThatDeveloper** [comment]
> @ThatDeveloper Do you want to hard reload your playground https://formkit.link/c99d6d313aa88c350bff3f71b2a50a67 and give it another try? This should be fixed.

I hard reloaded it and it did work. How can I use your fix in my project?

**Comment by sashamilenkovic** [comment]
Sweet! @ThatDeveloper update your pro package to the latest version.

**Comment by ThatDeveloper** [comment]
Thank you @sashamilenkovic!

Which command / package version to use? I think I am currently on pro@next.

**Comment by sashamilenkovic** [comment]
@ThatDeveloper Use the latest tag instead. Should be 1.0.0-alpha.21

**Comment by ThatDeveloper** [comment]
@sashamilenkovic Sadly, I still have an issue with this bug.

Setting: autocomplete with options func that return elements from server.
Actions: See Video https://streamable.com/5k9y7b

**Comment by sashamilenkovic** [comment]
@ThatDeveloper Appreciate the video! Unfortunately, I'm having trouble reproducing the issue. Can you make an approximate reproduction in the playground?

**Comment by ThatDeveloper** [comment]
@sashamilenkovic I tried and tried and I can't reproduce it in a way that it always happens. You can try this playground: https://formkit.link/fcd8c2fa9e38b9a5d42781892d37645d

Open the link, before you do anything, press Ctrl + R to reload the page, then, enter "A" in the autocomplete.
![image](https://user-images.githubusercontent.com/12497431/198361999-fb9f5600-2d08-4986-bd7b-7e10317b0b67.png)

**Comment by ThatDeveloper** [comment]
@sashamilenkovic omg yes! This problem is really bugging me but I was not able to do reproduce it reliably.

**Comment by sashamilenkovic** [comment]
@ThatDeveloper Hey, question for you. If you set the multiple prop to true on the autocomplete in your local project, do you still get that issue?

**Comment by ThatDeveloper** [comment]
@sashamilenkovic Could you please show me what you mean in the playground?

**Comment by sashamilenkovic** [comment]
@ThatDeveloper https://formkit.link/f17d2bdd70c6f771151b0a7d2be98729

**Comment by ThatDeveloper** [comment]
> @ThatDeveloper Hey, question for you. If you set the multiple prop to true on the autocomplete in your local project, do you still get that issue?

How the f***. When multiple is true, this does not happen. What a strange find... Does that help you?

**Comment by sashamilenkovic** [comment]
@ThatDeveloper It does! I think I have a path forward for solving this, but I won't be able to deploy a fix today.

**Comment by ThatDeveloper** [comment]
@sashamilenkovic Awesome. Just notify me when it is solved. Don't need it today. :)

**Comment by sashamilenkovic** [comment]
@ThatDeveloper Update your pro package again. The issue should be resolved. You can check the last playground you sent me as well.

**Comment by sashamilenkovic** [comment]
@ThatDeveloper Alright, let's try this again. The last playground example you sent me should now be working. Try updating your pro package to the latest version and let me know how it goes.

**Comment by ThatDeveloper** [comment]
@sashamilenkovic Now the filter function seems to be broken. Enter the automcomplete and write A, it shows the options. Now write AAAAAAAAAA or Ajkashkdhjkahs or Z. (last one is impossible)

**Comment by sashamilenkovic** [comment]
@ThatDeveloper  When the options prop is assigned to a function, you are in charge of your own filtering.

**Comment by ThatDeveloper** [comment]
@sashamilenkovic Got it, thank you! Looks good from the not having duplicate aspect. :)

**Comment by sashamilenkovic** [comment]
@ThatDeveloper Thank you for being so patient :), on to the next one!

**Comment by ThatDeveloper** [comment]
@sashamilenkovic Sorry, I have to reopen this. :( You seem t o have changed logic from alpha.21 to alpha.24 in regards to either events or optionsLoader.

In the version alpha.21, when you enter e.x. "A" the options func gets called with "A". If you now select an option. Perfect.
In the new version alpha.24, when you enter e.x. "A" the options func gets called with "A". If you now select an option, options func gets called with the "label" of selected item. Not good. => This call should not happen.

**Comment by ThatDeveloper** [comment]
@sashamilenkovic It looks like it is working now. Closing the issue, thank you very much. :)

**Comment by kswzr** [comment]
Hey @sashamilenkovic, we need to reopen this issue.

I'm having the same issue with the latest versions. Also could reproduce that bug in [FormKit Playground](https://formkit.com/playground?fkv=1.0.0-beta.12&fileTab=Playground.vue&files=JTVCJTdCJTIybmFtZSUyMiUzQSUyMlBsYXlncm91bmQudnVlJTIyJTJDJTIyZWRpdG9yJTIyJTNBJTIyJTNDc2NyaXB0JTIwc2V0dXAlM0UlNUNuaW1wb3J0JTIwJTdCJTIwcmVhY3RpdmUlMkMlMjB0b1JlZiUyQyUyMHJlZiUyQyUyMHdhdGNoJTIwJTdEJTIwZnJvbSUyMCd2dWUnJTVDbiU1Q24lNUNuJTVDbmNvbnN0JTIwc2NoZW1hRGF0YSUyMCUzRCUyMHJlYWN0aXZlKCU3QiU1Q24lMjAlMjBnZXRDaXRpZXMlM0ElMjBhc3luYyUyMChpbnB1dCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwJTIwJTIwY29uc3QlMjBzZWFyY2glMjAlM0QlMjBpbnB1dC5zZWFyY2hWYWx1ZSUzQiU1Q24lMjAlMjAlMjAlMjBpZiUyMChzZWFyY2glMjAlM0QlM0QlM0QlMjAlNUMlMjIlNUMlMjIpJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHJldHVybiUyMCU1QiU1RCUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTIwUHJvbWlzZS5yZXNvbHZlKG5ldyUyMFByb21pc2UocmVzb2x2ZSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBzZXRUaW1lb3V0KHJlc29sdmUoJTVCJTdCdmFsdWUlM0ElMjAxJTJDJTIwbGFiZWwlM0ElNUMlMjJBJTIwKDEpJTIwJTVCVGVzdCUyMC0lMjBBRyU1RCU1QyUyMiU3RCUyQyUyMCU3QnZhbHVlJTNBJTIwMiUyQyUyMGxhYmVsJTNBJTVDJTIyQiUyMCgyKSUyMCU1QlRlc3QlMjAtJTIwQUclNUQlNUMlMjIlN0QlNUQpJTJDJTIwMjAwMCklM0IlNUNuJTIwJTIwJTIwJTIwJTdEKSklNUNuJTIwJTIwJTdEJTVDbiU3RCklM0IlNUNuY29uc3QlMjByb290Rm9ybSUyMCUzRCUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjRjbXAlM0ElMjAnRm9ybUtpdCclMkMlNUNuJTIwJTIwJTIwJTIwcHJvcHMlM0ElMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwdHlwZSUzQSUyMCdmb3JtJyUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBpZCUzQSUyMCU1QyUyMnRlc3QlNUMlMjIlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwYWN0aW9ucyUzQSUyMGZhbHNlJTVDbiUyMCUyMCUyMCUyMCU3RCUyQyU1Q24lMjAlMjAlMjAlMjBjaGlsZHJlbiUzQSUyMCU1QiU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjRlbCUzQSUyMCdkaXYnJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGNoaWxkcmVuJTNBJTIwJTVCJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyNGZvcm1raXQlM0ElMjAlNUMlMjJyZXBlYXRlciU1QyUyMiUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBuYW1lJTNBJTIwJTVDJTIycmVwZWF0ZXIxJTVDJTIyJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGNoaWxkcmVuJTNBJTIwJTVCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjRmb3Jta2l0JTNBJTIwJTVDJTIycmVwZWF0ZXIlNUMlMjIlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwbmFtZSUzQSUyMCU1QyUyMnJlcGVhdGVyMiU1QyUyMiUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBjaGlsZHJlbiUzQSUyMCU1QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTI0Zm9ybWtpdCUzQSUyMCU1QyUyMmF1dG9jb21wbGV0ZSU1QyUyMiUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBuYW1lJTNBJTIwJTVDJTIya2V5JTVDJTIyJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMG9wdGlvbnMlM0ElMjAlNUMlMjIlMjRnZXRDaXRpZXMlNUMlMjIlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwc2VsZWN0aW9uQXBwZWFyYW5jZSUzQSUyMCU1QyUyMm9wdGlvbiU1QyUyMiUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB2YWxpZGF0aW9uJTNBJTIwJTVDJTIycmVxdWlyZWQlNUMlMjIlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTJGJTJGJTIwcHJvcCUyMGhlcmUlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwbXVsdGlwbGUlM0ElMjB0cnVlJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3RCUyQyU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjRmb3Jta2l0JTNBJTIwJTVDJTIydGV4dCU1QyUyMiUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBuYW1lJTNBJTIwJTVDJTIydmFsdWUlNUMlMjIlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwdmFsaWRhdGlvbiUzQSUyMCU1QyUyMnJlcXVpcmVkJTVDJTIyJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3RCU1RCU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0QlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTVEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3RCU1RCU1Q24lMjAlMjAlMjAlMjAlN0QlNUQlNUNuJTdEJTVDbiUzQyUyRnNjcmlwdCUzRSU1Q24lNUNuJTNDdGVtcGxhdGUlM0UlNUNuJTIwJTIwJTNDRm9ybUtpdFNjaGVtYSUyMCU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0FzY2hlbWElM0QlNUMlMjJyb290Rm9ybSU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0FkYXRhJTNEJTVDJTIyc2NoZW1hRGF0YSU1QyUyMiU1Q24lMjAlMjAlMkYlM0UlNUNuJTNDJTJGdGVtcGxhdGUlM0UlNUNuJTVDbiUzQ3N0eWxlJTIwc2NvcGVkJTNFJTVDbiUyRiolNUNudmFuaWxsYSUyMENTUyUyMGNhbiUyMGdvJTIwaGVyZS4lNUNuS2VlcCUyMHN0eWxlcyUyMHNjb3BlZCUyMHRvJTIwYXZvaWQlMjBtdWx0aXBsZSUyMGZpbGVzJTVDbm92ZXJ3cml0aW5nJTIwZWFjaCUyMG90aGVyJTIwaW4lMjB0aGUlMjByZW5kZXIlMjBvdXRwdXQuJTVDbiolMkYlNUNuJTNDJTJGc3R5bGUlM0UlNUNuJTIyJTJDJTIyYWRkZWQlMjIlM0F0cnVlJTdEJTVE&imports=JTdCJTIybmFtZSUyMiUzQSUyMkltcG9ydE1hcCUyMiUyQyUyMmVkaXRvciUyMiUzQSUyMiU3QiU1Q24lMjAlMjAlNUMlMjJ2dWUlNUMlMjIlM0ElMjAlNUMlMjJodHRwcyUzQSUyRiUyRmNkbi5qc2RlbGl2ci5uZXQlMkZucG0lMkZ2dWUlNDAzJTJGZGlzdCUyRnZ1ZS5lc20tYnJvd3Nlci5taW4uanMlNUMlMjIlNUNuJTdEJTVDbiUyMiU3RA)

Have a look at my loom, to see which error I have, and how to reproduce it:

https://www.loom.com/share/65a742154573490ea26f689e6a8cadaa

**Comment by sashamilenkovic** [comment]
@kswzr Hmmmm, that's unfortunate. I'll take a look at this first thing tomorrow.

**Comment by sashamilenkovic** [comment]
@kswzr If you give that same playground a hard reload, are you still seeing that issue?

**Comment by enzobrigati** [comment]
Hey @sashamilenkovic , we have the same issue locally as described. We saw that it was closed last week, have you find any solution ?

Thanks a lot :)

**Comment by sashamilenkovic** [comment]
@enzobrigati can you tell me what version of FormKit pro you're currently using?

**Comment by enzobrigati** [comment]
> @enzobrigati can you tell me what version of FormKit pro you're currently using?

Yeap, we just updated it to Beta.13, but the issue was the same on Beta.12 :/

**Comment by sashamilenkovic** [comment]
@kswzr @enzobrigati I'm actually going to reopen this for now as I've found a regression myself. I'll be working on this now.

**Comment by sashamilenkovic** [comment]
@enzobrigati The issue should be fixed @latest tag now. I'm going to close this again but of course comment back if you have any issues.
