### ISSUE TITLE
Not properly emitted events (count:blocking) - Multistep - "repeater" elements

### ISSUE THREAD

**Issue by ThatDeveloper** [formkit/formkit#433]
### Reproduction

https://formkit.link/38408b5ac17114a5e397271c23c58333

### Describe the bug

I am creating this issue to keep track of it.
@justin-schroeder already commented on discord: "I’m familiar with this bug. I generally know the direction to track it down. Noted."

---

I have a very strange behaviour when using "repeater" in multistep. I created a playground, please ignore formatting or whatever you see in there, as proper formatting ended up with an error "URI too long". 

Within the playground when you open your console and click the add button & then delete the created add button you see console.logs of "count:blocking" event. When adding it goes up and down and stops at 6. When removing it goes up and down and stops at 2, making this repeater invalid, even though it should not be, as the blocking count should end at 0.
I am sadly not understanding enough of "count:blocking" to truly understand this. Does anyone have an idea? I think it might be that the delete of the repeater item is not properly emitting events.

### Environment

• OS: Windows
• Browser: Chrome
• Version: 106.0.5249.119

**Comment by justin-schroeder** [comment]
Ok — here's an updated *minimal* reproduction showing the count issue when reducing the repeater count:

https://formkit.link/adcfd18ea659d7141cd3922874bc3513

This should be enough for us to develop a backing test and solution. I can’t give a precise time estimate, but this will be our top priority bug for the moment.

**Comment by justin-schroeder** [comment]
Ok, this issue is now fixed — the bug was actually in `@formkit/core` so to receive this patch you'll need to update  `@formkit/vue@next` and `@formkit/pro`.

If you select `beta.12` and do a _hard refresh_ on the playground example above (https://formkit.link/adcfd18ea659d7141cd3922874bc3513) you can see the blocking count correctly gets set back down to zero.
