### ISSUE TITLE
Server rendered FormKit inputs (no js)

### ISSUE THREAD

**Issue by Rigo-m** [formkit/formkit#434]
### Describe the feature

In Nuxt3 it's now possible to deploy a fully-static no js website and also server components has dropped (i.e.: components rendered on the server with no js on the client).

It would be cool to be able to leverage FormKit form building capabilities with these features (we already had a use case where we used formkit+nojs nuxt build to provide some forms to a third party client), although we acknowledge that many FormKit features can't be ported to a no-js environment, it's also true that a form is just a form at the end, and being able to provide native validation/styling would be a great addition as a no-js fallback.

**Comment by justin-schroeder** [comment]
Hi @Rigo-m 👋

You can use "native" validation if you want! Native validation is done via attributes like `pattern`. Now if you're asking if we can make the FormKit validation rules work using no-js, the answer is usually *no* because native validation is very very limited. RegExp only gets you so far with validation — so a few of them could work in theory.

That said I'm certainly interested in looking into additional server component based features for FormKit

**Comment by Rigo-m** [comment]
I actually overlooked the fact that I can pass a pattern attribute directly to the form input. Thanks!

Just a quick question, let's say I pass the pattern attribute, because in one environment I have server rendered forms, but in another environment I do use the whole formkit package with frontend custom validation. Is it useful to automatically infer formkit js validation strategies from the pattern attribute?

This would dedupe some code I think

**Comment by justin-schroeder** [comment]
It’s an interesting question — I'm honestly not sure how a no-js render "knows" it is a no js render (nuxt hook perhaps?). In those instances we could possibly perform some build-time optimizations. For example, there could be a limited set of validation rules that provide "native" fallbacks during a no-js build:

FormKit Rule | Native attribute
--------------|-----------------
required         | `[required]`
email              | `[type="email"]`
matches        |  `[pattern]`

etc...

It would be a very small, limited set, but that seems like the best way to reduce duplicate code. The alternative is to remove the native attributes when similar validation rule exists. This is *ok* but at first glace, to me, has a lower correlation. Also, this would be pretty easy to implement using a quick plugin. The pseudo code would be:

1. Check if the node has any `node.props.attrs` that are in a hard-coded set of native "rules" (like required)
2. Remove those `attrs` from `node.props.attrs` if a matching validation rule is found in `node.props.parsedRules`.

I'll reopen this to carry on a conversation about it. Perhaps there are other interesting ideas in the space for the no-js masochists out there 😂😂😂
