### ISSUE TITLE
Autocomplete validation not working correctly

### ISSUE THREAD

**Issue by ThatDeveloper** [formkit/formkit#437]
### Reproduction

https://formkit.link/affec848939edf8112fa400d3fb33749

### Describe the bug

In the playground you can see a repeater with a autocomplete and a text input.
The validation, as per your docs, should default to "blur" (Errors are shown after a user removes focus from an input.).

If you add repeater item and select "test1" in the autocomplete, then "blur" by changing focus, no validation happens. 
If you add another repeater, do the same, still no validation.

I have also added console logs where the last boolean value shows the validation result & If using `validationVisibility: "live"` you can see that the validator is working.

It looks like autocomplete does not handle events correctly.

### Environment

• OS: Windows
• Browser: Chrome
• Version: 106.0.5249.119

**Comment by luan-nk-nguyen** [comment]
Thanks @ThatDeveloper! Here is a related reproduction where the `autocomplete` blur event is not closing the options list when inside a repeater (causing JS errors). https://formkit.link/40fc34417595a20150268f160a661997

**Comment by justin-schroeder** [comment]
This should be working in `@formkit/pro` from `alpha.27` and on (hard refresh in the playground)

**Comment by ThatDeveloper** [comment]
@justin-schroeder I think the fix has broken something. I did do no changes since yesterday to the code, except updating the version of `@formkit/pro` from `1.0.0-alpha.26` to `latest`.

On every autocomplete, if I select an option, (before the first "blur") the option does not get selected and the "required" validation comes up. Only the next ones work. This is for every autocomplete. I think this could be some form of race condition between blur and click?

1.0.0-alpha.26: https://streamable.com/2zai8o
latest: https://streamable.com/95c43c
