### ISSUE TITLE
Autocomplete options css bug when using selectionAppearance: "option"

### ISSUE THREAD

**Issue by ThatDeveloper** [formkit/formkit#439]
### Reproduction

https://formkit.link/b5c78d3bfee3193c92cb784e95322572

### Describe the bug

When using `autocomplete` with `selectionAppearance: "option"` the text and cross to delete the option are overflowing into the form.

Steps to reproduce:
1. Open playground
2. Select the option in the first repeater
3. Make playground window smaller in width

![image](https://user-images.githubusercontent.com/12497431/198550105-5ab2483f-3a10-434f-92d4-24b96c8b5c04.png)

### Environment

• OS: Windows
• Browser: Chrome
• Version: 106.0.5249.119

**Comment by justin-schroeder** [comment]
Fixed in alpha 28
