### ISSUE TITLE
Custom i18n localization function

### ISSUE THREAD

**Issue by ThatDeveloper** [formkit/formkit#441]
### Describe the feature

It would be great if the docs have a text hook example of the following OR FormKit & FormKitSchema would have a prop that allows to provide a function which receives key, context, and args and returns a string for localization.

If the function is set as prop and the function does not return anything (undefined, null), fallback to regular i18n.

This would be help me a lot!

Example:
```vue
<FormKitSchema 
    :schema="schema"
    :data="schemaData"
    :i18n="customLocalization"
/>
```
```js
function customLocalization(key, ...) {
    return "my custom translated version";
}
```

**Comment by justin-schroeder** [comment]
FormKit has a pretty advanced i18n system already. You can provide custom messages via the locale files, config messages, translation hook, or with props. You can configure your localization mostly via the config — but from the example I'm not quite sure the intent of the translation. Point me in the right direction and I can give you a generic example.
