### ISSUE TITLE
FormKitSchema - sanitize / validate schema input - ref() bug

### ISSUE THREAD

**Issue by ThatDeveloper** [formkit/formkit#442]
### Reproduction

1. https://formkit.link/9bbc3ee5f0202ec99b6c3fd09c5dea4e
2. https://formkit.link/17c9fef20bf4b5816d982880e30c6d90

### Describe the bug

The difference between playground 1 (working) and playground 2 (not working) is that the schema is [] vs ref([]).

This has very unpredictable issues, e.x. in my local example everything works, except for a section that contains only a repeater and I add an item to the repeater (`min: 0`) where suddenly in the `showStepErrors` func the `stepName` parameter is undefined. While reproducing in playground I saw a lot of different issues emerging out of this.

As especially in vue people work with refs or similar, it might make sense to either fix it, not render at all + error message, or something else. What do you think?

### Environment

• OS: Windows
• Browser: Chrome
• Version: 106.0.5249.119

**Comment by justin-schroeder** [comment]
Hmm, there shouldn't be any issues using a ref at all (not expected behavior). I can see the playground version going on the fritz, so this is worth investigating further.

**Comment by justin-schroeder** [comment]
If anyone is able to find a *minimal* reproduction (rather than hundreds of lines) it would greatly help isolate this.

**Comment by ThatDeveloper** [comment]
Yes, very strange. I always try to provide playgrounds with enough context. The ones above was from formkits own examples from the docs, as I though it would help.
Here a new one with less code: https://formkit.link/33e3af6ce36c96b2b679092ce30ea7a1

Best seen that this is probably a vue - formkit bug by opening it with console open, then change something simple, e.x. add a ";" to the e.x. alert of submitApp and then it loads.

**Comment by andrew-boyd** [comment]
@ThatDeveloper Is this behavior also happening in a local project or only in the FormKit playground? 

By changing the import path to Vue from `vue` to `./vue` I've "fixed" both your minimal reproduction and the original provided playground:

minimal: https://formkit.link/97a5a06572e66091110b3122c9a45a33
full: https://formkit.link/3cfd984721a6fe17700b2b097328a11f

So, unless you're seeing this behavior outside of the Playground I think it's an issue with the way the Playground is booting up, compiling, and then rendering the components. I can investigate further but would be happy if this was just an issue with the Playground and not FormKit proper.

**Comment by justin-schroeder** [comment]
Pretty sure this is no longer an issue. If it is, a minimal reproduction will re-open this.
