### ISSUE TITLE
Adding a custom component isn't working with schema

### ISSUE THREAD

**Issue by phillipmohr** [formkit/formkit#443]
- Nuxt 3
- @formkit/nuxt1.0.0-beta.11

I'm having such a headache lol I've been trying to add a multiselect since 3 days and I tried literally everything from the docs. Nothing seems to work.

What I want 

- adding the @vueform/multiselect component to the schema, or even better: creating a component FormkitMultiselect which has @vueform/multiselect as a child component
- adding a label to this component in the same style like all other inputs (native formkit text inputs etc.)
- correct value handling 

What already works
- having the VueMultiselect rendered with my provided options 

Problems
- how to add a label when using a custom component?
- how to handle the data? (v-model) for some reason all values are selected (see screenshot)

I tried everything from the docs... createInput etc., but nothing worked for me.

My Code

@vueform/multiselect is provided globally via Nuxt plugin
```js
import VueMultiselect from '@vueform/multiselect'

export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.vueApp.component("VueMultiselect", VueMultiselect)
})
```

```vue
const schema = ref<FormKitSchemaCondition | FormKitSchemaNode[]>([
    {
        $formkit: 'text',
        name: 'title',
        label: 'Recipe Title',
        validation: 'required',
        value: ''
    },
    {
        $cmp: 'VueMultiselect',
        props: {
            options: useRecipeBadges()
        }
    },
])
```

Passing schema to a wrapper component
```vue

<FormBuilder
    :schema="schema"
/>
```

wrapper passes it to FormKit
```
<FormKit type="form" @submit="handleSubmit" :submit-label="submitLabel">
    <FormKitSchema
        :schema="schema"
    />
</FormKit>
```

All values selected
<img width="1034" alt="Bildschirmfoto 2022-10-28 um 15 13 48" src="https://user-images.githubusercontent.com/30236221/198605225-f02c4257-7a43-4d88-aaae-2c1b676fcbe6.png">

**Comment by phillipmohr** [comment]
@justin-schroeder Hey, thanks for your time. I already tried that. Unfortunately the docs don't show how to use a custom input with schema. And with that attempt I have other problems... 

What's working now
- label is being rendered
- component is being rendered

Problems: 
- (select) options aren't showing (I pass them as a prop)
- Typescript error
- not sure how to handle data yet, but maybe I can figure this out by myself after I see the options etc...

Form.vue
```vue
const FormkitMultiselectWrapper = resolveComponent('FormkitMultiselectWrapper')
const multiselect = createInput(FormkitMultiselectWrapper)

... schema
{
        $formkit: multiselect,
        name: 'badges',
        label: 'Badges',
        value: 'spicy',
        props: {
                options: useRecipeBadges(),
    
        }
    },
```

**Typescript Error**
`No overload matches this call.
  Overload 2 of 3, '(value: FormKitSchemaCondition | FormKitSchemaNode[]): Ref<{ if: string; then: string | ... | { $el: string; attrs?: { [index: string]: FormKitAttributeValue; } | { ...; }; ... 5 more ...; meta?: FormKitSchemaMeta; } | { ...; } | { ...; } | (string | ... 3 more ... | { ...; })[]; else?: string | ... 4 more ... | (string | ... 3 more ... | { ...; })[]; } | (string | ... 3 more ... | { ...; })[]>', gave the following error.
  Overload 2 of 3, '(value: FormKitSchemaCondition | FormKitSchemaNode[]): Ref<{ if: string; then: string | ... | { $el: string; attrs?: { [index: string]: FormKitAttributeValue; } | { ...; }; ... 5 more ...; meta?: FormKitSchemaMeta; } | { ...; } | { ...; } | (string | ... 3 more ... | { ...; })[]; else?: string | ... 4 more ... | (string | ... 3 more ... | { ...; })[]; } | (string | ... 3 more ... | { ...; })[]>', gave the following error.ts(2769)
index.d.ts(986, 5): '$formkit' is declared here.`

Can you see what I'm doing wrong? If you need more information please let me know!

**Comment by justin-schroeder** [comment]
How about you provide a minimal reproduction of in a repository or stackblitz and we can take a look from there.

**Comment by phillipmohr** [comment]
> How about you provide a minimal reproduction of in a repository or stackblitz and we can take a look from there.

I added a [reproduction here](https://stackblitz.com/edit/nuxt-starter-q1gm5m?file=package.json,nuxt.config.ts,formkit.config.ts,components%2FFormkitMultiselectWrapper.vue,plugins%2Fmultiselect.ts,components%2FButton.vue,app.vue,components%2Fadmin%2FForm%2FRecipe.vue)

This is my first reproduction, so let me know if this helps :) 

Unfortunately, the Typescript isn't showing in stackblitz. I'm not sure if I need to configure something in stackblitz or if my editor (VSCode) is showing me the Typescript error by mistake.

**Comment by justin-schroeder** [comment]
Thank you for the reproduction. I saw a number of issues that needed resolving, but rather than list them all out, here’s your reproduction working: https://stackblitz.com/edit/vueform-multiselect-formkit

Best of luck 👍 And if you enjoy FormKit, consider using our Pro inputs next time to help support the project 🙂

**Comment by phillipmohr** [comment]
@justin-schroeder thanks for your time!
