### ISSUE TITLE
Form reset not working when options func / optionsLoader is used

### ISSUE THREAD

**Issue by ThatDeveloper** [formkit/formkit#444]
### Reproduction

https://formkit.link/6373b88451c404594b0954d7d05829f7

### Describe the bug

When resetting the form, the autocomplete does not get cleared. Form data does though as far as I can see.

@justin-schroeder Is that similar to https://github.com/formkit/formkit/issues/432?

### Environment

• OS: Windows
• Browser: Chrome
• Version: 106.0.5249.119

**Comment by justin-schroeder** [comment]
Not sure but it’s a good lead. Thanks for the minimal repro.

**Comment by sashamilenkovic** [comment]
@ThatDeveloper Firstly, I don't think you are referencing the right ID in your reset function call. And then secondly, it appears there is a reference error. 
<img width="463" alt="Screenshot 2022-10-29 at 11 25 19 AM" src="https://user-images.githubusercontent.com/50585039/198839795-09c750e4-4e06-46b0-afb8-d75766f79a72.png">

**Comment by justin-schroeder** [comment]
Well that’s what I get for looking at this on my phone. Good find @sashamilenkovic!

**Comment by ThatDeveloper** [comment]
@sashamilenkovic It is all correct. That does not affect anything. Here it is fixed: https://formkit.link/c65998673ec9e256d309ea8d540388ab

Issue still is there. I am referencing the right. I am resetting the form called form.

**Comment by sashamilenkovic** [comment]
@ThatDeveloper Hahah, I was just in the middle of commenting this issue. It works just fine in my local environment but not the playground. @justin-schroeder I was wondering if you have any insight into this

**Comment by sashamilenkovic** [comment]
@ThatDeveloper Do you have this issue in your local environment?

**Comment by ThatDeveloper** [comment]
> @ThatDeveloper Do you have this issue in your local environment?

It is not working in the playground.

Just select an option and then click reset.

**Comment by sashamilenkovic** [comment]
@ThatDeveloper I've acknowledged that it does not work in the playground. I'm asking if you try this same functionality in your local environment, does it cause any issues?

**Comment by ThatDeveloper** [comment]
> @ThatDeveloper I've acknowledged that it does not work in the playground. I'm asking if you try this same functionality in your local environment, does it cause any issues?

Yes, exactly same behaviour.

**Comment by sashamilenkovic** [comment]
@ThatDeveloper Let me take a look.

**Comment by justin-schroeder** [comment]
Good news, turns out this isn't a bug: https://formkit.link/8c4fd012d6c0eedd1ba9fbe5accdde1b

The issue was just a plain ol' JavaScript bug. The click handler was calling `this.$formkit.reset('form')`, `this` is not a reference to the Vue instance in this context, and also the form’s id was `test` not `form`. So the above example should work great now 👍 🎉

**Comment by ThatDeveloper** [comment]
@justin-schroeder Well, my bad on the `this.$formkit.reset('form')`  as I copied this one from local (and it did work).
But the underlying issue is not resolved. Please do the following in your playground https://formkit.link/8c4fd012d6c0eedd1ba9fbe5accdde1b

1. Select an option
2. click somwhere in the white area
3. press reset

The form value resets, the input stays.

**Comment by justin-schroeder** [comment]
Ok — this is actually fixed now @ThatDeveloper. Need upgrade to alpha.30, but its working in the playground (with a hard reload)!
