### ISSUE TITLE
Custom input with two inputs? prepended inputs?

### ISSUE THREAD

**Issue by SH1R3F** [formkit/formkit#445]
I would like to have an input that have a prepended select. So, it's two inputs. I can't find it in docs so I would make a custom input and have my logic inside it. 
the problem is. how would manage, validate, read two inputs inside my custom input component?

**Comment by justin-schroeder** [comment]
@SH1R3F 👋

The real question here is how do you want your *data* structured. You can have as many inputs as you want be part of a custom input, but they can only contribute 1 value. That value can be any type (object, array, string etc).

For example, this guide shows how to use 4 inputs to produce a single number: https://formkit.com/guides/create-a-custom-input

So perhaps more details on what you are trying to build would be helpful. The most helpful would be if you could take a stab at it in the playground and then share that playground back here — or ideally hop into discord and continue the conversation there.

Thanks!
