### ISSUE TITLE
Some regexes don't work when using "matches" for validation

### ISSUE THREAD

**Issue by emanuelradu** [formkit/formkit#454]
### Reproduction

https://formkit.com/playground?files=JTVCJTdCJTIybmFtZSUyMiUzQSUyMnJ1bGUtbWF0Y2hlcy1pbmxpbmUtcmVnZXgudnVlJTIyJTJDJTIyZWRpdG9yJTIyJTNBJTIyJTNDdGVtcGxhdGUlM0UlNUNuJTIwJTIwJTNDRm9ybUtpdCU1Q24lMjAlMjAlMjAlMjB0eXBlJTNEJTVDJTIyZW1haWwlNUMlMjIlNUNuJTIwJTIwJTIwJTIwbGFiZWwlM0QlNUMlMjJFbWFpbCU1QyUyMiU1Q24lMjAlMjAlMjAlMjB2YWxpZGF0aW9uJTNEJTVDJTIybWF0Y2hlcyUzQSUyRiU1RSU1QyU1Q3clMkIoJTVCJTVDJTVDLi0lNUQlM0YlNUMlNUN3JTJCKSolNDAlNUMlNUN3JTJCKCU1QiU1QyU1Qy4tJTVEJTNGJTVDJTVDdyUyQikqKCU1QyU1Qy4lNUMlNUN3JTdCMiUyQzMlN0QpJTJCJTI0JTJGJTVDJTIyJTVDbiUyMCUyMCUyMCUyMGhlbHAlM0QlNUMlMjJQbGVhc2UlMjBlbnRlciUyMHlvdXIlMjBwYXNzd29yZC4lNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTNBdmFsaWRhdGlvbi1tZXNzYWdlcyUzRCU1QyUyMiU3QiUyMG1hdGNoZXMlM0ElMjAnRW1haWwlMjBub3QlMjB2YWxpZCclMjAlN0QlNUMlMjIlNUNuJTIwJTIwJTJGJTNFJTVDbiUzQyUyRnRlbXBsYXRlJTNFJTVDbiUyMiUyQyUyMnN5bnRheCUyMiUzQSUyMmh0bWwlMjIlMkMlMjJhZGRlZCUyMiUzQXRydWUlN0QlNUQ&css-framework=genesis&fkv=1.0.0-beta.11&fileTab=rule-matches-inline-regex.vue&imports=JTdCJTIybmFtZSUyMiUzQSUyMkltcG9ydE1hcCUyMiUyQyUyMmVkaXRvciUyMiUzQSUyMiU3QiU1Q24lMjAlMjAlNUMlMjJ2dWUlNUMlMjIlM0ElMjAlNUMlMjJodHRwcyUzQSUyRiUyRmNkbi5qc2RlbGl2ci5uZXQlMkZucG0lMkZ2dWUlNDAzJTJGZGlzdCUyRnZ1ZS5lc20tYnJvd3Nlci5taW4uanMlNUMlMjIlNUNuJTdEJTVDbiUyMiU3RA

### Describe the bug

I'm trying to add custom regex to validate email addresses. I tried several regexes and formkit doesn't validate them correctly.

You can try the following regexes with a valid email address such as: test@gmail.com:
```
1. /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/
2. /(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])/
```

I mention that I tried to use the built in validation from formkit but it misses some rules. It lets you add an email with no "." after @.

You can use the link I provided from playground to test it

### Environment

• OS: Windows 10
• Browser Chrome 
• Version:
  107.0.5304.87

**Comment by justin-schroeder** [comment]
Seems like there are 2 different things here.

1. You think the email validation rule isn't sufficient
2. Not all regex patterns work

Let me address the second point first — you are correct! Not all strings work, there's a section about this in the matches rule documentation:

![Documentation describing array syntax for validation](https://user-images.githubusercontent.com/1950463/199491846-d0d7a69b-c34c-4f69-906e-1df2da7ecd99.png)

Here's your playground with the array syntax that allows full regex patterns: https://formkit.link/cbf4103197e98f698697f472b932cca3

As for the email validation rule not validating the way you expect. I would be happy to look at a reproduction of that in a separate issue.

**Comment by emanuelradu** [comment]
Thank you very much for the reply. I omitted that section.
