### ISSUE TITLE
Repeater input (FormKit Pro) - reactivity issue

### ISSUE THREAD

**Issue by tno2007** [formkit/formkit#455]
### Description
When using the repeater (FormKit Pro input), reactivity does not trigger immediately, when you try to input data into an repeating item you just added.

### FormKit Vue Playground link:
https://formkit.link/a17b389dce00350cbf8414e1ea4bd22a

### How to reproduce:
- Visit the playground link above
- Fill in something in the the dependant name field (Just to test initial reactivity... the model ref JSON on top updates as you type)
- Click the "Add another dependant" button 
- Fill in something in the second dependant field (result: The model **\*\*does not\*\*** update as you type!)
- Fill in something in any of the other 2 fields on the form (The model now updates, with the data you filled in previously) 

### Expected behavior

The model data should be in-sync and reactive with what you type into the repeating item fields

**Comment by justin-schroeder** [comment]
Thanks for the reproduction. We'll definitely look into this further.
