### ISSUE TITLE
input event triggered when render formkit element for the first time

### ISSUE THREAD

**Issue by comhon-project** [formkit/formkit#464]
### Reproduction

[playground](https://formkit.com/playground?fkv=1.0.0-beta.11&fileTab=Playground.vue&files=JTVCJTdCJTIybmFtZSUyMiUzQSUyMlBsYXlncm91bmQudnVlJTIyJTJDJTIyZWRpdG9yJTIyJTNBJTIyJTNDc2NyaXB0JTIwc2V0dXAlM0UlNUNuaW1wb3J0JTIwJTdCJTIwcmVmJTIwJTdEJTIwZnJvbSUyMCd2dWUnJTVDbiUyRiUyRiUyMEVTTSUyMGltcG9ydHMlMjBhcmUlMjBzdXBwb3J0ZWQlMjBmcm9tJTIwVVJMcyUyMChodHRwcyUzQSUyRiUyRmNkbi4uLiklNUNuJTJGJTJGJTIwYXMlMjB3ZWxsJTIwYXMlMjBzZWNvbmRhcnklMjBwbGF5Z3JvdW5kJTIwZmlsZXMlMjAoLiUyRk90aGVyRmlsZS52dWUpLiU1Q24lNUNuY29uc3QlMjB0ZXN0JTIwJTNEJTIwcmVmKCU3QiU1Q24lMjAlMjB0ZXN0XzElM0ElMjAndmFsdWVfMSclMkMlNUNuJTIwJTIwdGVzdF8yJTNBJTIwJ3ZhbHVlXzInJTJDJTVDbiUyMCUyMHRlc3RfMyUzQSUyMCd2YWx1ZV8zJyUyQyU1Q24lMjAlMjB0ZXN0XzQlM0ElMjAndmFsdWVfNCclMkMlMjAlNUNuJTdEKSUzQiU1Q24lNUNuZnVuY3Rpb24lMjBpbnB1dChuYW1lKSUyMCU3QiU1Q24lMjAlMjBjb25zb2xlLmxvZygndXBkYXRlJyUyQyUyMG5hbWUpJTNCJTVDbiU3RCU1Q24lM0MlMkZzY3JpcHQlM0UlNUNuJTVDbiUzQ3RlbXBsYXRlJTNFJTVDbiUzQ0Zvcm1LaXQlMjB2LW1vZGVsJTNEJTVDJTIydGVzdCU1QyUyMiUyMHR5cGUlM0QlNUMlMjJmb3JtJTVDJTIyJTNFJTVDbiUyMCUyMCUzQ0Zvcm1LaXQlNUNuJTIwJTIwJTIwJTIwdHlwZSUzRCU1QyUyMnRleHQlNUMlMjIlNUNuJTIwJTIwJTIwJTIwbmFtZSUzRCU1QyUyMnRlc3RfMSU1QyUyMiU1Q24lMjAlMjAlMjAlMjBsYWJlbCUzRCU1QyUyMkZvcm1LaXQlMjBJbnB1dCU1QyUyMiU1Q24lMjAlMjAlMjAlMjBoZWxwJTNEJTVDJTIyZWRpdCUyMG1lJTIwdG8lMjBnZXQlMjBzdGFydGVkJTVDJTIyJTVDbiUyMCUyMCUyMCUyMCU0MGlucHV0JTNEJTVDJTIyKCklMjAlM0QlM0UlMjBpbnB1dCgndGVzdF8xJyklNUMlMjIlNUNuJTIwJTIwJTJGJTNFJTVDbiUyMCUyMCUzQ0Zvcm1LaXQlNUNuJTIwJTIwJTIwJTIwdHlwZSUzRCU1QyUyMnRleHQlNUMlMjIlNUNuJTIwJTIwJTIwJTIwbmFtZSUzRCU1QyUyMnRlc3RfMiU1QyUyMiU1Q24lMjAlMjAlMjAlMjBsYWJlbCUzRCU1QyUyMkZvcm1LaXQlMjBJbnB1dCU1QyUyMiU1Q24lMjAlMjAlMjAlMjBoZWxwJTNEJTVDJTIyZWRpdCUyMG1lJTIwdG8lMjBnZXQlMjBzdGFydGVkJTVDJTIyJTVDbiUyMCUyMCUyMCUyMCU0MGlucHV0JTNEJTVDJTIyKCklMjAlM0QlM0UlMjBpbnB1dCgndGVzdF8yJyklNUMlMjIlNUNuJTIwJTIwJTJGJTNFJTVDbiUyMCUyMCUzQ0Zvcm1LaXQlNUNuJTIwJTIwJTIwJTIwdHlwZSUzRCU1QyUyMnRleHQlNUMlMjIlNUNuJTIwJTIwJTIwJTIwbmFtZSUzRCU1QyUyMnRlc3RfMyU1QyUyMiU1Q24lMjAlMjAlMjAlMjBsYWJlbCUzRCU1QyUyMkZvcm1LaXQlMjBJbnB1dCU1QyUyMiU1Q24lMjAlMjAlMjAlMjBoZWxwJTNEJTVDJTIyZWRpdCUyMG1lJTIwdG8lMjBnZXQlMjBzdGFydGVkJTVDJTIyJTVDbiUyMCUyMCUyMCUyMCU0MGlucHV0JTNEJTVDJTIyKCklMjAlM0QlM0UlMjBpbnB1dCgndGVzdF8zJyklNUMlMjIlNUNuJTIwJTIwJTJGJTNFJTVDbiUyMCUyMCUzQ0Zvcm1LaXQlNUNuJTIwJTIwJTIwJTIwdHlwZSUzRCU1QyUyMnRleHQlNUMlMjIlNUNuJTIwJTIwJTIwJTIwbmFtZSUzRCU1QyUyMnRlc3RfNCU1QyUyMiU1Q24lMjAlMjAlMjAlMjBsYWJlbCUzRCU1QyUyMkZvcm1LaXQlMjBJbnB1dCU1QyUyMiU1Q24lMjAlMjAlMjAlMjBoZWxwJTNEJTVDJTIyZWRpdCUyMG1lJTIwdG8lMjBnZXQlMjBzdGFydGVkJTVDJTIyJTVDbiUyMCUyMCUyMCUyMCU0MGlucHV0JTNEJTVDJTIyKCklMjAlM0QlM0UlMjBpbnB1dCgndGVzdF80JyklNUMlMjIlNUNuJTIwJTIwJTJGJTNFJTVDbiUyMCUyMCUzQyUyRkZvcm1LaXQlM0UlNUNuJTNDJTJGdGVtcGxhdGUlM0UlNUNuJTVDbiUzQ3N0eWxlJTIwc2NvcGVkJTNFJTVDbiUyRiolNUNudmFuaWxsYSUyMENTUyUyMGNhbiUyMGdvJTIwaGVyZS4lNUNuS2VlcCUyMHN0eWxlcyUyMHNjb3BlZCUyMHRvJTIwYXZvaWQlMjBtdWx0aXBsZSUyMGZpbGVzJTVDbm92ZXJ3cml0aW5nJTIwZWFjaCUyMG90aGVyJTIwaW4lMjB0aGUlMjByZW5kZXIlMjBvdXRwdXQuJTVDbiolMkYlNUNuJTNDJTJGc3R5bGUlM0UlNUNuJTIyJTJDJTIyYWRkZWQlMjIlM0F0cnVlJTdEJTVE&imports=JTdCJTIybmFtZSUyMiUzQSUyMkltcG9ydE1hcCUyMiUyQyUyMmVkaXRvciUyMiUzQSUyMiU3QiU1Q24lMjAlMjAlNUMlMjJ2dWUlNUMlMjIlM0ElMjAlNUMlMjJodHRwcyUzQSUyRiUyRmNkbi5qc2RlbGl2ci5uZXQlMkZucG0lMkZ2dWUlNDAzJTJGZGlzdCUyRnZ1ZS5lc20tYnJvd3Nlci5taW4uanMlNUMlMjIlNUNuJTdEJTVDbiUyMiU3RA)

### Describe the bug

bug: 
input event triggered when render formkit element for the first time (open dev console to see logs)

expected: 
should not trigger input event

### Environment

• Formkit beta 11

thanks in advance :)

**Comment by comhon-project** [comment]
thanks for quick answer!
1) you mean i'ts not recommended to use both `v-model` and `@input` in same time ?
or neither should be used ?
2) what is `node` object and how I access it ?
3) now I understand why @input are triggered but I guess it should not. it's an initialization, it's not a user input.
4) I just see there is something weird, the input event for the last element in my example (test_4) is not triggered.

**Comment by GustavoFenilli** [comment]
1. I would nor recommend using either, only v-model can be useful for some cases.
2. node is the core formkit node https://formkit.com/advanced/core#node, you can access it using `getNode` or `$formkit.get` https://formkit.com/advanced/core#getting-a-components-node#getting-a-components-node
3. `@input` from formkit is not a native `@input` it is an event that happens when a value is commited to that node, it is not an even for user input.
4. That is weird and i'm not sure why ( v-model and @input does give some weird behaviour sometimes )

**Comment by comhon-project** [comment]
okay i thought it was the native @input, that's why I was confused.
thanks for help!
