### ISSUE TITLE
prop classes on form type don't add class to submit button

### ISSUE THREAD

**Issue by DNA** [formkit/formkit#466]
### Reproduction

https://formkit.link/cfd5731b2d1e16b53d1f0e641a8c58e6

### Describe the bug

In [the `form` docs](https://formkit.com/essentials/forms#sections) it states that there are 3 sections: `form`, `actions` and `submit`

However, when we edit it's `classes` prop it won't add the class to the submit button:

```vue
  <FormKit
    type="form"
    :classes="{
      form: 'form-css',
      actions: 'action-css',
      submit: 'submit-css' // <= This one
    }"
  ></Formkit>
```

The generate code:

```html


<form class="formkit-form form-css" id="input_0" name="form_1">
  <div class="formkit-actions action-css">
    <div class="formkit-outer" data-family="button" data-type="submit">
      <div class="formkit-wrapper">
        <button class="formkit-input" type="submit" name="submit_2" id="input_1">Submit</button>
        <!-- class `submit-css` should've appeared on this button class, right? -->
      </div>
    </div>
  </div>
</form>
```

### Environment

• OS: MacOS BigSur (11.7)
• Browser Chrome
• Version 107.0.5304.87 (Official Build) (x86_64)

**Comment by GustavoFenilli** [comment]
To change the submit you actually have to use `submit-attrs` prop because it is another node and not really a section at the form, we may need to improve the documentation about this.

https://formkit.com/essentials/forms#provided-submit-button

```html
:submit-attrs={
    inputClass: 'submit-css'
}
```

**Comment by DNA** [comment]
Yes, the docs was a bit vague on this part. I'll look into opening a PR to improve it, thanks for the response! :)

**Comment by luan-nk-nguyen** [comment]
Hi @DNA -- love that you were willing to pitch in on the docs! We already added a section before seeing your comment. Hopefully this will help the next developer:https://formkit.com/essentials/forms#provided-submit-button
