### ISSUE TITLE
Is there a list of listenable events for each component?

### ISSUE THREAD

**Issue by ehainer** [formkit/formkit#467]
Hopefully okay to ask this here. I assume Discord would be better for questions, but a) I'm old enough to not know what the hell Discord is, and b) couldn't sign up for whatever reason, just got stuck in an auth loop 🤷🏼 

Regarding the ability to listen to events/props using `node.on()`, is there a list anywhere of what events are dispatched from each component? Been up and down the docs and can't seem to find anything, not sure if I missed it or it doesn't exist, and it's difficult to track it back to the source code.

What prompted this is a need to know when the state of the select (or dropdown) component switches between "open" and "closed." It would be great to be able to do something along the lines of `node.on('toggle', ({ payload }) => console.log('Select is', payload.open ? 'open' : 'closed'))` so that I could react accordingly.

Much appreciated, and thanks for all the great work!

**Comment by justin-schroeder** [comment]
Yes — the core node event list is here: https://formkit.com/advanced/core#core-events

This list isn't necessarily comprehensive, but if the event is not published on this list it is not recommended for user land use.
