### ISSUE TITLE
Race condition with v-model and watchers

### ISSUE THREAD

**Issue by Tragio** [formkit/formkit#470]
### Reproduction

https://formkit.link/125f6fb5918637303d5ccc37f0cb0095

### Describe the bug

As discussed in Discord with @justin-schroeder and @GustavoFenilli here is the issue for the race condition.

> Hmm yeah — I don't see anything wrong with that playground @tragio — it should work, something about the form wrapper isn't working there with the v-models.

> it is working, but probably being overwritten by v-if creating and removing the input.
> so when it removes, it removes the value from the v-model.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
I think this is fixed in beta.17 — can you confirm?

**Comment by Tragio** [comment]
> I think this is fixed in beta.17 — can you confirm?

At first, it seems fixed. I'll test it further. Thank you for the awesome work 🚀
