### ISSUE TITLE
Add value diffing for scalar value nodes.

### ISSUE THREAD

**Issue by dominikklein** [formkit/formkit#473]
### Reproduction

https://formkit.link/f9d392b14d0680c0a7ead6a46da02fa8

### Describe the bug

Very fast rendering from FormKitSchema when it's used without a FormKit-Form around the FormKitSchema. When a FormKit-Form is used around the FormKitSchema it will be slower and slower for every field. I tested it also in the playground and saw the same result in the Vue-Dev-Console.

### Environment

• OS: macOS
• Browser: Chrome + Firefox

**Comment by justin-schroeder** [comment]
An experimental fix for constant-time settlement inside groups/lists is deployed at `@formkit/vue@perf`.

**Comment by dominikklein** [comment]
@justin-schroeder Thanks for the fast feedback ⭐  The result looks really nice (like already mention in discord).

Will also play a little bit around during the day.

**Comment by dominikklein** [comment]
Ok, I saw that a lot of our tests are failing after the switch to this branch.

The `getNode` returns undefined in this situation:

```
describe('Form - Field - Hidden (Formkit-BuildIn)', () => {
  it('can render a input', () => {
    const wrapper = renderComponent(FormKit, {
      ...wrapperParameters,
      props: {
        name: 'hidden',
        type: 'hidden',
        id: 'hidden',
        value: 'example-value',
      },
    })

    const input = wrapper.getByDisplayValue('example-value')

    expect(input).toBeInTheDocument()
    expect(input).toHaveAttribute('id', 'hidden')
    expect(input).toHaveAttribute('type', 'hidden')

    const node = getNode('hidden')
    console.log('NODE', node) -> undefined
    expect(node?.value).toBe('example-value')
  })
})
```

**Comment by dominikklein** [comment]
Ok, I saw also that in our "real" code the getNode is not working as expected. E.g. I'm using this multi-step approach from the example with the "visitedSteps" and here the group node is now also `undefined`.

**Comment by dominikklein** [comment]
It's also happening when I try to reproduce it with this playground code and the new `perf` branch: https://formkit.link/9fc88976fc72d4d09f5deb2b1891abce

**Comment by justin-schroeder** [comment]
@dominikklein I'm guessing your tests are failing because you have multiple instances of FormKit in your app now. `getNode` uses the module scope for its store, so if there are multiple instances of `@formkit/core` (which could happen easily with a new tagged version).

**Comment by dominikklein** [comment]
Ah yes make sense, thanks. Will test it :-)

**Comment by dominikklein** [comment]
@justin-schroeder Yes looks good, when I did a clean package installation. I'm only wondering that I see a range from 500ms - 2,5 seconds for the rendering. But maybe it's a little bit related to my other issues (#475 + #478).

**Comment by dominikklein** [comment]
Anything I can do from my side that the changes can be merged for the next release?

**Comment by justin-schroeder** [comment]
We have a big "stability/performance" sprint brewing that this is sloted for, in addition to a number of other core stability improvements. This is planned for that sprint, so it should be in the next release or shortly after.

**Comment by justin-schroeder** [comment]
Good reproduction: https://formkit.link/ca42c015bacecbf838ead1f4f674ef7a

**Comment by justin-schroeder** [comment]
@azertyalex and @dominikklein new performance PR is now open (published as `@dev` tag). Hopefully this moves the needle a bit, although there is still more that could be done here: #659

**Comment by justin-schroeder** [comment]
These performance improvements are now in the `@next` tag 👍 Still room to iterate but there is now a 3-5x performance improvement on large forms.
