### ISSUE TITLE
Add support for single root nodes in `FormKitSchema`

### ISSUE THREAD

**Issue by dominikklein** [formkit/formkit#474]
### Reproduction

https://formkit.link/57d42f8af4fb03149fce4f486a3d98fa

### Describe the bug

When I tested it correctly it's currently not possible to use the `v-show` directly on the FormKit-Component.

### Environment

• OS: macOS

**Comment by justin-schroeder** [comment]
This is now solved in beta 17! Finally root nodes are supported for all built in inputs as well as FormKitSchema proper.

https://formkit.link/ebe87ae17079c89ac5ab0ea078bce5e5
