### ISSUE TITLE
Add `data-is-checked` to checkbox and radio wrappers.

### ISSUE THREAD

**Issue by silveltman** [formkit/formkit#477]
### Describe the feature

Currently, I can't add regular/static classes + conditional classes. 

Simplified example:
```
    <FormKit  :wrapper-class="myVar && 'test-class'"  wrapper-class="flex items-centercursor-pointer" type="radio"
        :options="options">
    </FormKit>
```

I know I can probably do something like `:class="true && 'flex items-centercursor-pointer'; myVar && 'test-class'" ` But this is kinda ugly.

I'm building a custom radio input, for which I want to add a border to the active/selected option

**Comment by justin-schroeder** [comment]
is something like this what you’re thinking? https://formkit.link/9f2e14de67871afd1200ec4460841054

**Comment by luan-nk-nguyen** [comment]
@silveltman Here's an example of adding a data-attribute to any selected option using the [`sections-schema` functionality](https://formkit.com/essentials/inputs#sections-schema) along with a builtin `isChecked` function, which is not really documented at the moment:

https://formkit.link/5adc96378b9430d11706c9e5ae5f9892

You can use it with a `radio` or `checkbox`. I do think that we should probably make conditional classes on options easier.

**Comment by luan-nk-nguyen** [comment]
Here's another example with the tailwind FormKitPlugin: https://formkit.link/553c124d54ddaafa085016a0e2f9623e if it helps.

**Comment by silveltman** [comment]
Thanks! Both solutions work.

However, I find this part quiet robust for simply adding a checked state: 
```
:sections-schema="{
      option: {
        attrs: {
          'data-is-checked': '$fns.isChecked($option.value)'
        }
      }
    }"
```
Isn't there a simpler way? And if not, can you please elaborate on what's happening here? I can't make it up from the docs

**Comment by andrew-boyd** [comment]
This should probably be combined with https://github.com/formkit/formkit/issues/350 yeah?

**Comment by justin-schroeder** [comment]
This is being added in beta.13. See: https://formkit.link/dab5b4e144a12fac26f6073f3dd1f358 (do a hard refresh)
