### ISSUE TITLE
FormKit-Schema (and Form-Settlement) rendering postpones other async code (e.g. setTimeout)

### ISSUE THREAD

**Issue by dominikklein** [formkit/formkit#478]
### Reproduction

https://formkit.link/b38979bb0807aeb9d4e5b42e033d3689

### Describe the bug

For me, it seems that the formkit schema rendering (and settlement) postpones other async code, e.g. the set timeout in the playground.
The timeout callback should be executed after 300ms, but it is only executed when the settlement (schema rendering) is finished (locally I saw the same for other things, e.g. debounce).

(In the playground I added some "v-if"/"v-show",  because this is the situation from our project, but it's the same without this stuff when I saw it correctly.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
This is expected JavaScript behavior. In JavaScript the primary call stack completes before any async code can be run (which is why timeouts can be really imprecise, especially on load). The key is to reduce the size of the primary call stack.

**Comment by dominikklein** [comment]
Ok make sense on one perspective, but really confusing in this context. But I think I'm not that deep inside this stuff.
At the end there is also not really a possible to reduce here something from the outside, because I'm using only the schema with some more fields. Do you have any general idea about this topic?

**Comment by justin-schroeder** [comment]
I don’t have any specifics other than what we've discussed on discord. For FormKit you want to optimize for the number of shared schemas. This happens for most inputs automatically, but if you use plugins to directly modify the schema you could cause re-parsing on a per-input basis which would dramatically slow down a form with lots of inputs.

**Comment by justin-schroeder** [comment]
Perhaps if you provide a reproduction of an instance of slow mounting we could take a look at it on our end too.

**Comment by dominikklein** [comment]
I think in the end we do not have many schema modifications with plugins. We are only adding some data attributes to the outer level (and maybe also for some single fields) and we defined our general "base" schema.
With the improvements from the other issue, it's now also no longer slow (only sometimes it's confusing that it takes some more time, which I already mentioned in the other issue).

In the end, the reproduction of the async stuff is already present in the playground with these 150 fields (but for sure this has not the performance improvements package).

**Comment by dominikklein** [comment]
Do you need anything else from my side or is it ok with the current playground?

In the end, I can say, that with the improvement from the other stuff it's not that slow anymore for many fields. But what I see in the Vue-Dev-Console is, that our custom fields which are using a Vue-Component for the inner part, have a loading time greater than 10ms. It's no longer increasing for every additional field but looks not that fast, but maybe it's normal for such kind of stuff.

**Comment by justin-schroeder** [comment]
> Do you need anything else from my side or is it ok with the current playground?
> 
> In the end, I can say, that with the improvement from the other stuff it's not that slow anymore for many fields. But what I see in the Vue-Dev-Console is, that our custom fields which are using a Vue-Component for the inner part, have a loading time greater than 10ms. It's no longer increasing for every additional field but looks not that fast, but maybe it's normal for such kind of stuff.

Yeah, not sure there is anything else we can do about that specifically. The schema portion of that would still be memoized but the Vue portion of that is left in Evan’s hands :)

**Comment by dominikklein** [comment]
My problem is at the moment I want to show a loading animation when the form settlement is slower then 300ms (so that the animation is not directly visible to avoid some flicker effect when it's faster).
Because of that, I'm setting a timeout at the beginning of the initialization phase (=building static schema). When the static schema is ready the FormKit-Component will be rendered (v-show), but then I have the problem that the timeout is "stacked" because of the mention "primary call stack".

**Comment by justin-schroeder** [comment]
Annoying — but I would recommend you move your timeout setting to the parent of the FormKit form — in theory that should allow your timeout to start before any intensive compute takes place.

**Comment by dominikklein** [comment]
Do you mean the parent from the component where the "FormKit-Form"-Component is used?
I can try it, but in the end, it will be a little bit ugly because the usage of our Form-Wrapper will be more special.

**Comment by justin-schroeder** [comment]
yeah I agree. not sure there is a good path forward here except to make FormKit more efficient. Or, perhaps we offer some kind of optional async boot procedure for people who dont need SSR.

**Comment by justin-schroeder** [comment]
Nothing specifically we can do here other than make formkit faster — which we are doing, so I'll close this in favor of #473
