### ISSUE TITLE
Abbreviation `url` is lowercase in the URL validation message

### ISSUE THREAD

**Issue by DamianGlowala** [formkit/formkit#480]
### Reproduction

n/a

### Describe the bug

URL is an abbreviation of the Uniform Resource Locator, and therefore the validation messages should respect this. Currently, it is lowercase (checked only for the `en` locale):

![image](https://user-images.githubusercontent.com/48835293/202846642-f49df4e7-5dd6-44af-ba21-5385e98ba2ec.png)

On contrary, the documentation uses the correct casing:

![image](https://user-images.githubusercontent.com/48835293/202846609-8687d3a7-5661-49d0-bb95-4db1423aa746.png)

https://en.wikipedia.org/wiki/URL

### Environment

n/a

**Comment by sashamilenkovic** [comment]
@DamianGlowala Fair point! This has been updating at the @next tag. https://formkit.link/1914f081be3f8502ff0023a09ed19d8b
