### ISSUE TITLE
Repeater throws errors when unmounting while still containing items.

### ISSUE THREAD

**Issue by hassanbhattignomen** [formkit/formkit#485]
### Reproduction

https://formkit.link/8496bc2dc2a1754b7b8af4cc2fe3a780

### Describe the bug

I am using repeater inside modal when i try to close modal ,sort error appears and nothing works i need to refresh the page So in production link click on open modal button and try to close it then you can see error inside repeater.

index.mjs:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'sort')
    at R (index.mjs:1:19697)
    at index.mjs:1:50793
    at Function.n [as dispatch] (index.mjs:15:20)
    at commit (index.mjs:1105:55)
    at calm (index.mjs:1214:16)
    at Proxy.<anonymous> (index.mjs:973:32)
    at removeChild (index.mjs:1429:18)
    at Proxy.<anonymous> (index.mjs:973:32)
    at destroy (index.mjs:1237:21)
    at Proxy.<anonymous> (index.mjs:973:32)

### Environment

• OS: mac os
• Browser chrome, safari and firefox

**Comment by justin-schroeder** [comment]
I was able to further isolate this — this error is thrown anytime the repeater is unmounted while still containing items: https://formkit.link/44254f31ffa0ee685d9d5c53f07521bd

**Comment by anjil-fastlane** [comment]
Has there been any update on this bug? I am facing similar issue with repeater input .

**Comment by mingyangshih** [comment]
I also met this issue with repeater input.

**Comment by anjil-fastlane** [comment]
@mingyangshih  Resting the repeater form during the component unmount will avoid getting this error.

**Comment by mingyangshih** [comment]
Thanks a lot. I will try it on my end.

**Comment by hassanbhattignomen** [comment]
@mingyangshih can you share your code how you solved it please explain it will help me thanks

**Comment by anjil-fastlane** [comment]
> @mingyangshih @anjil-fastlane can you guys share your code how you solved it please explain it will help me thanks

`<script setup lang='ts'>
import { reset } from '@formkit/core'

onBeforeUnmount(() => {
// reset the repeater form 
reset('repeater')
})
</script>
<template>
         <FormKit
              id="repeater"
              type="repeater"
              label="something"
              name="something"
            >
        ..........................."formkit components"
       </FormKit>
</template>
`

**Comment by mingyangshih** [comment]
My code is the same as @anjil-fastlane

**Comment by agenordebriat** [comment]
> 

Same thing here.

**Comment by agenordebriat** [comment]
> My code is the same as @anjil-fastlane

Same thing here.

**Comment by perkovandrey** [comment]
Any progress here?

I'm creating a multi-step form on a website and getting exactly the same error when switching between steps. @anjil-fastlane solution works, but when returning to the previous form step after reset('repeater'), all input fields stop working altogether. https://tppr.me/2clg2

**Comment by justin-schroeder** [comment]
Good news! This issue is now fixed in `@formkit/pro >= 1.0.0-alpha.41`. Unmount to your hearts content.

**Comment by perkovandrey** [comment]
> Good news! This issue is now fixed in `@formkit/pro >= 1.0.0-alpha.41`. Unmount to your hearts content.

Unfortunately it doesn't work. My repeater works with v-model and after unmount the value of the model becomes undefined.

Before unmount: https://tppr.me/BxSMF
After unmount: https://tppr.me/mHlig

**Comment by justin-schroeder** [comment]
That is intentional. All inputs un-mounting clear their data in FormKit. In most cases this is the desired behavior but you can preserve your data with the `preserve` prop if needed.

https://formkit.com/inputs/form#unmounting-inputs

**Comment by perkovandrey** [comment]
> That is intentional. All inputs un-mounting clear their data in FormKit. In most cases this is the desired behavior but you can preserve your data with the `preserve` prop if needed.
> 
> https://formkit.com/inputs/form#unmounting-inputs


I use all formKit fields with v-model. But the value of v-model becomes undefined on unmount only now in repeater

**Comment by perkovandrey** [comment]
> That is intentional. All inputs un-mounting clear their data in FormKit. In most cases this is the desired behavior but you can preserve your data with the `preserve` prop if needed.
> 
> https://formkit.com/inputs/form#unmounting-inputs

With `preserve ` it works. Thanks!
