### ISSUE TITLE
`show` in FormKit schema

### ISSUE THREAD

**Issue by aresofficial** [formkit/formkit#487]
### Describe the feature

Hi guys,

We are using FormKit schema to dynamically build form. It works perfect.

We implemented `Steps` functionality, but the problem that we can not use `if` (`v-if`) in our schema because it forces component re-rendering.
Is any way to **hide** (`v-show`) the component base on some data value, or add this functionality?

P.S. I can create helper method, pass it to data and use it, but we would like to use some kind of `show` in our definition.

Many thanks for the answer.

**Comment by sashamilenkovic** [comment]
@aresofficial All v-show does behind the scene is toggle the display property. Here's how you could replicate something like this: https://formkit.link/7a8e870498605f8da37c01728ac6b905

**Comment by justin-schroeder** [comment]
This is a good question. We could add syntactic sugar like a top level `show` property (like the top level `if` property) — although I'm not sure this amount of sugar would be generally beneficial or not. It's more code shipped to more browsers, on the other hand it does provide a nice API. Perhaps we need to expose a more robust mechanism for adding your own "sugar" to the schema.

**Comment by aresofficial** [comment]
> This is a good question. We could add syntactic sugar like a top level `show` property (like the top level `if` property) — although I'm not sure this amount of sugar would be generally beneficial or not. It's more code shipped to more browsers, on the other hand it does provide a nice API. Perhaps we need to expose a more robust mechanism for adding your own "sugar" to the schema.

Yep, that would be great if we could extend basic schema definition with own "sugar". It will allow users to build their flexible components and use it via FormKit Schema. Our case with `Steps`:  `stepName` property that we can bind to `data.activeStep`.

For now we can use `attrs.style.` for our purposes.

**Comment by comhon-project** [comment]
+1
this feature would be very help full!
in my case I can't just use `attrs.style` because when I wrap it in a `TransitionGroup`, the transition is not triggered.

**Comment by justin-schroeder** [comment]
@comhon-project — FWIW this wouldn't fix the `TransitionGroup`. That’s not FormKit related, Vue’s transition group is for adding/removing and reordering DOM elements. Not for `v-show`.

**Comment by justin-schroeder** [comment]
Closing this in favor of #474
