### ISSUE TITLE
date validation for today or future

### ISSUE THREAD

**Issue by paulrosen** [formkit/formkit#488]
### Describe the feature

This is really convenient:
```
<FormKit type="date" validation="date_after" etc...
```
But I want my users to "pick a date in the future" - the future also includes the rest of today and that validation doesn't allow today.

I can work around this by getting today's date and parsing it and using `date_after:YYYY-MM-DD` but that is such a common use case (I would think) that I'd love for that to be built in.

**Comment by GustavoFenilli** [comment]
`date_after` has by default today as the day to compare, you can pass a date that it will compare as bigger than that, here is the code:

```js
const date_after: FormKitValidationRule = function (
  { value },
  compare = false
) {
  const timestamp = Date.parse(compare || new Date())
  const fieldValue = Date.parse(String(value))
  return isNaN(fieldValue) ? false : fieldValue > timestamp
}
```

you can easily create a new rule and add to `validation-rules` globally or locally.

```js
const date_future: FormKitValidationRule = function (
  { value },
  compare = false
) {
  const timestamp = Date.parse(compare || new Date())
  const fieldValue = Date.parse(String(value))
  return isNaN(fieldValue) ? false : fieldValue >= timestamp
}

createApp(App).use(plugin, defaultConfig({
  rules: { date_future },
})).mount('#app')
```

**Comment by GustavoFenilli** [comment]
> This might be a bug, also. I put in `required|date_after:2022-11-23` as the validation and selected a date in the past and clicked "save". I got the message "Due Date must be after Nov 22, 2022." Shouldn't it have said "Nov 23"?

do you have a reproduction of this behaviour so we can check?

**Comment by paulrosen** [comment]
https://formkit.com/playground?fkv=1.0.0-beta.12&fileTab=Playground.vue&files=JTVCJTdCJTIybmFtZSUyMiUzQSUyMlBsYXlncm91bmQudnVlJTIyJTJDJTIyZWRpdG9yJTIyJTNBJTIyJTNDc2NyaXB0JTIwc2V0dXAlM0UlNUNuJTJGJTJGJTIwRVNNJTIwaW1wb3J0cyUyMGFyZSUyMHN1cHBvcnRlZCUyMGZyb20lMjBVUkxzJTIwKGh0dHBzJTNBJTJGJTJGY2RuLi4uKSU1Q24lMkYlMkYlMjBhcyUyMHdlbGwlMjBhcyUyMHNlY29uZGFyeSUyMHBsYXlncm91bmQlMjBmaWxlcyUyMCguJTJGT3RoZXJGaWxlLnZ1ZSkuJTVDbiUzQyUyRnNjcmlwdCUzRSU1Q24lNUNuJTNDdGVtcGxhdGUlM0UlNUNuJTIwJTIwJTNDRm9ybUtpdCU1Q24lMjAlMjAlMjAlMjB0eXBlJTNEJTVDJTIyZGF0ZSU1QyUyMiU1Q24lMjAlMjAlMjAlMjBuYW1lJTNEJTVDJTIyZHVlRGF0ZSU1QyUyMiU1Q24lMjAlMjAlMjAlMjBsYWJlbCUzRCU1QyUyMkR1ZSUyMERhdGUlNUMlMjIlNUNuJTIwJTIwJTIwJTIwdmFsaWRhdGlvbiUzRCU1QyUyMnJlcXVpcmVkJTdDZGF0ZV9hZnRlciUzQTIwMjItMTEtMjMlNUMlMjIlNUNuJTIwJTIwJTJGJTNFJTVDbiUzQyUyRnRlbXBsYXRlJTNFJTVDbiU1Q24lM0NzdHlsZSUyMHNjb3BlZCUzRSU1Q24lMkYqJTVDbnZhbmlsbGElMjBDU1MlMjBjYW4lMjBnbyUyMGhlcmUuJTVDbktlZXAlMjBzdHlsZXMlMjBzY29wZWQlMjB0byUyMGF2b2lkJTIwbXVsdGlwbGUlMjBmaWxlcyU1Q25vdmVyd3JpdGluZyUyMGVhY2glMjBvdGhlciUyMGluJTIwdGhlJTIwcmVuZGVyJTIwb3V0cHV0LiU1Q24qJTJGJTVDbiUzQyUyRnN0eWxlJTNFJTVDbiUyMiUyQyUyMmFkZGVkJTIyJTNBdHJ1ZSU3RCU1RA

**Comment by paulrosen** [comment]
I made the custom rule similar to what you pasted and it worked. I had to put this on the `<FormKit>` element itself: `:validation-messages="{ date_future: t('Pick a date on or after today')}"`. I would have liked to make that message global, too, but that's not a big deal.

**Comment by GustavoFenilli** [comment]
> I made the custom rule similar to what you pasted and it worked. I had to put this on the `<FormKit>` element itself: `:validation-messages="{ date_future: t('Pick a date on or after today')}"`. I would have liked to make that message global, too, but that's not a big deal.

you can add global validation messages here by following this https://formkit.com/essentials/validation#global-validation-message

**Comment by GustavoFenilli** [comment]
It seens like a bug to me too, for the validation messages.
