### ISSUE TITLE
scoped slot label doesn't update

### ISSUE THREAD

**Issue by comhon-project** [formkit/formkit#489]
### Reproduction

[playground](https://formkit.com/playground?fkv=1.0.0-beta.12&fileTab=Playground.vue&files=JTVCJTdCJTIybmFtZSUyMiUzQSUyMlBsYXlncm91bmQudnVlJTIyJTJDJTIyZWRpdG9yJTIyJTNBJTIyJTNDc2NyaXB0JTIwc2V0dXAlM0UlNUNuJTJGJTJGJTIwRVNNJTIwaW1wb3J0cyUyMGFyZSUyMHN1cHBvcnRlZCUyMGZyb20lMjBVUkxzJTIwKGh0dHBzJTNBJTJGJTJGY2RuLi4uKSU1Q24lMkYlMkYlMjBhcyUyMHdlbGwlMjBhcyUyMHNlY29uZGFyeSUyMHBsYXlncm91bmQlMjBmaWxlcyUyMCguJTJGT3RoZXJGaWxlLnZ1ZSkuJTVDbmltcG9ydCUyMCU3QiUyMHJlZiUyMCU3RCUyMGZyb20lMjAndnVlJyU1Q25pbXBvcnQlMjBNeUlucHV0JTIwZnJvbSUyMCcuJTJGTXlJbnB1dC52dWUnJTVDbiU1Q25jb25zdCUyMGFjdGl2YXRlU3VmZml4JTIwJTNEJTIwcmVmKGZhbHNlKSUzQiU1Q25jb25zdCUyMGtleSUyMCUzRCUyMHJlZigxKSUzQiU1Q25jb25zdCUyMGxvb3AlMjAlM0QlMjB0cnVlJTNCJTVDbiU1Q25mdW5jdGlvbiUyMHVwZGF0ZSgpJTIwJTdCJTVDbiUyMCUyMGFjdGl2YXRlU3VmZml4LnZhbHVlJTIwJTNEJTIwIWFjdGl2YXRlU3VmZml4LnZhbHVlJTNCJTVDbiUyMCUyMGtleS52YWx1ZSUyQiUyQiUzQiU1Q24lMjAlMjBzZXRUaW1lb3V0KCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMGlmJTIwKGxvb3ApJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHVwZGF0ZSgpJTNCJTVDbiUyMCUyMCU3RCU1Q24lMjAlMjAlN0QlMkMlMjAyMDAwKSUzQiU1Q24lN0QlNUNuJTVDbnNldFRpbWVvdXQodXBkYXRlJTJDJTIwMTAwMCklM0IlMjAlNUNuJTNDJTJGc2NyaXB0JTNFJTVDbiU1Q24lM0N0ZW1wbGF0ZSUzRSU1Q24lMjAlMjAlM0NkaXYlM0UlNUNuJTIwJTIwJTIwJTIwJTNDZGl2JTNFJTdCJTdCJTIwYWN0aXZhdGVTdWZmaXglMjAlN0QlN0QlMjAlM0MlMkZkaXYlM0UlNUNuJTIwJTIwLS0tLS0tLS0tLS0tJTIwRm9ybUtpdCUyMGRvZXNuJ3QlMjBhcHBseSUyMHVwZGF0ZSUyMC0tLS0tLS0tLS0tLS0lNUNuJTIwJTIwJTIwJTIwJTNDRm9ybUtpdCUyMHR5cGUlM0QlNUMlMjJ0ZXh0JTVDJTIyJTIwbGFiZWwlM0QlNUMlMjJteSUyMGxhYmVsJTVDJTIyJTIwbmFtZSUzRCU1QyUyMnN0YXR1cyU1QyUyMiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0N0ZW1wbGF0ZSUyMHYtaWYlM0QlNUMlMjJhY3RpdmF0ZVN1ZmZpeCU1QyUyMiUyMCUyM2xhYmVsJTNEJTVDJTIyY29udGV4dCU1QyUyMiUzRSUzQ2xhYmVsJTIwY2xhc3MlM0QlNUMlMjJleHBvLWxhYmVsJTVDJTIyJTNFbXklMjBsYWJlbCUyMCUzQ3NwYW4lMjBzdHlsZSUzRCU1QyUyMmNvbG9yJTNBJTIwYmx1ZSU1QyUyMiUzRXdpdGglMjBibHVlJTIwc3VmZml4JTNDJTJGc3BhbiUzRSUzQyUyRmxhYmVsJTNFJTNDJTJGdGVtcGxhdGUlM0UlNUNuJTIwJTIwJTIwJTIwJTNDJTJGRm9ybUtpdCUzRSU1Q24lMjAlMjAtLS0tLS0tLS0tLS0tLS0tLSUyMEN1c3RvbSUyMGFwcGxpZXMlMjB1cGRhdGUlMjAtLS0tLS0tLS0tLS0tLS0tLS0lNUNuJTIwJTIwJTIwJTIwJTNDTXlJbnB1dCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0N0ZW1wbGF0ZSUyMHYtaWYlM0QlNUMlMjJhY3RpdmF0ZVN1ZmZpeCU1QyUyMiUyMCUyM2xhYmVsJTNFJTNDbGFiZWwlMjBjbGFzcyUzRCU1QyUyMmV4cG8tbGFiZWwlNUMlMjIlM0VteSUyMGxhYmVsJTIwJTNDc3BhbiUyMHN0eWxlJTNEJTVDJTIyY29sb3IlM0ElMjBibHVlJTVDJTIyJTNFd2l0aCUyMGJsdWUlMjBzdWZmaXglM0MlMkZzcGFuJTNFJTNDJTJGbGFiZWwlM0UlM0MlMkZ0ZW1wbGF0ZSUzRSU1Q24lMjAlMjAlMjAlMjAlM0MlMkZNeUlucHV0JTNFJTVDbiUyMCUyMCUzQyUyRmRpdiUzRSU1Q24lM0MlMkZ0ZW1wbGF0ZSUzRSU1Q24lNUNuJTNDc3R5bGUlMjBzY29wZWQlM0UlNUNuJTJGKiU1Q252YW5pbGxhJTIwQ1NTJTIwY2FuJTIwZ28lMjBoZXJlLiU1Q25LZWVwJTIwc3R5bGVzJTIwc2NvcGVkJTIwdG8lMjBhdm9pZCUyMG11bHRpcGxlJTIwZmlsZXMlNUNub3ZlcndyaXRpbmclMjBlYWNoJTIwb3RoZXIlMjBpbiUyMHRoZSUyMHJlbmRlciUyMG91dHB1dC4lNUNuKiUyRiU1Q24lM0MlMkZzdHlsZSUzRSU1Q24lMjIlMkMlMjJhZGRlZCUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyTXlJbnB1dC52dWUlMjIlMkMlMjJlZGl0b3IlMjIlM0ElMjIlM0NzY3JpcHQlMjBzZXR1cCUzRSU1Q24lNUNuJTNDJTJGc2NyaXB0JTNFJTVDbiU1Q24lM0N0ZW1wbGF0ZSUzRSU1Q24lMjAlMjAlM0NkaXYlM0UlNUNuJTIwJTIwJTIwJTIwJTNDZGl2JTNFJTNDc2xvdCUyMG5hbWUlM0QlNUMlMjJsYWJlbCU1QyUyMiUzRSUzQyUyRnNsb3QlM0UlM0MlMkZkaXYlM0UlNUNuJTIwJTIwJTIwJTIwJTNDaW5wdXQlMjB0eXBlJTNEJTVDJTIydGV4dCU1QyUyMiUyRiUzRSU1Q24lMjAlMjAlM0MlMkZkaXYlM0UlNUNuJTNDJTJGdGVtcGxhdGUlM0UlNUNuJTVDbiUzQ3N0eWxlJTIwc2NvcGVkJTNFJTVDbiU1Q24lM0MlMkZzdHlsZSUzRSU1Q24lMjIlMkMlMjJyZW1vdmFibGUlMjIlM0F0cnVlJTJDJTIyYWRkZWQlMjIlM0F0cnVlJTdEJTVE)

### Describe the bug

bug :
scoped slot label doesn't update

expected :
scoped slot label should update

(the only workaround i found is to add a `key` to formkit component and update it to reload completely the component)

thanks in advance :)

### Environment

beta 12

**Comment by justin-schroeder** [comment]
This is fixed in `beta.13` 👍 Thanks for the report.
