### ISSUE TITLE
Extend docs with Tailwind examples (PRO inputs)

### ISSUE THREAD

**Issue by maartenvanhunsel** [formkit/formkit#490]
### Describe the feature

While developing I've experienced it's quite hard and time consuming to theme PRO inputs with tailwind. Especially for the dropdowns like: Taglist, Autocomplete and dropdown because you can't force the dropdown in a particular state.

It would be nice if we can (1) extend the Create a Tailwind CSS theme guide or maybe better (2) add per input a theming section with predefined styles so it's easier to customize inputs.

**Comment by sashamilenkovic** [comment]
@maartenvanhunsel This is definitely something we want to make easier. At some point within the next few weeks we'll "add per input a theming section with predefined styles." In the meantime, if you update your pro package to the `@latest` tag, you should be able to use the `force-expanded` prop that forces the listbox open (for Taglist, Autocomplete, and Dropdown pro inputs), https://formkit.link/e06bfdbd389a3a8d5af999eec720b49a Make sure you hard reload the docs site to get the latest pro dependency.

**Comment by luan-nk-nguyen** [comment]
Hi @maartenvanhunsel! We have created a complete 1-to-1 reproduction of our Genesis CSS theme in Tailwind. Hopefully, this gives you a great starting point and makes theming Pro inputs with Tailwind easier! 

Here's the link: https://formkit.com/guides/create-a-tailwind-theme#a-complete-tailwind-theme--recreating-genesis-css
