### ISSUE TITLE
Pro - Repeater - Objects created by repeater not honoring type of objects 

### ISSUE THREAD

**Issue by patpicos** [formkit/formkit#493]
### Reproduction

https://formkit.link/7a6a8c54bfe7a8fa10a2f0cf11fa97bf

### Describe the bug

Create a repeater object, in the list of repeated fields, create 4 files of type number.
When you add objects to the repeater, the data type of the data input of type number turns into string values in the array

Result:
```javascript
{
  "repeater_2": [
    {
      "min_year": "1900",
      "max_year": "1905",
      "min_votes": "50",
      "min_rating": "5.0"
    }
  ]
}
```
Expected: 
```javascript
{
  "repeater_2": [
    {
      "min_year": 1900,
      "max_year": 1905,
      "min_votes": 50,
      "min_rating": 5.0,
    }
  ]
}
```

### Environment

• OS: MacOS
• Browser Edge
• Version: Version 107.0.1418.56 (Official build) (x86_64)

    "@formkit/pro": "^1.0.0-alpha.29",
    "@formkit/vue": "^1.0.0-beta.11",

**Comment by patpicos** [comment]
I think the bug is from the number input rather than the repeater

**Comment by justin-schroeder** [comment]
This is actually working as expected. HTML does not support numeric values (you can ask for the value as a number in HTML but the actual value of all inputs is always a string). You can, however, easily use a FormKit plugin if you'd like a different type of casting. Here's an example plugin:

https://formkit.link/631ba980869cd7337e55a9636c8709a5

Good luck 👍

**Comment by patpicos** [comment]
Did the trick.
