### ISSUE TITLE
PRO: Taglist shows duplicate value when 'multiple' is set to false

### ISSUE THREAD

**Issue by jerrebm** [formkit/formkit#494]
### Reproduction

https://formkit.link/2f5a5f4861f32868d591c281f8e65b3a

### Describe the bug

When setting `multiple` to `false` on the taglist input, the selected value will render both as the option and in the input text field. The expected behavior would be to only show the selected option and clear the input field.

### Environment

• OS: Mac OS Ventura
• Browser Chrome
• Version [e.g. 22]

**Comment by sashamilenkovic** [comment]
@jerrebm Thanks for this! As we discussed in discord, the `multiple` prop was not intended to be used for the taglist and was erroneously added to its docs. I've fixed the issue anyways by nullifying the `multiple` prop even if it is passed. I will open a separate issue for an enhancement to add a `max` prop to the taglist.

**Comment by jerrebm** [comment]
Sweet! I agree, `max` prop is a better solution :)
