### ISSUE TITLE
Add the ability to have an empty message for an `autocomplete` that returns no results.

### ISSUE THREAD

**Issue by justin-schroeder** [formkit/formkit#502]
### Describe the feature

It would be great if we had a way to display a message to the user when the autocomplete returns no results (empty array). In most cases, I think our default behavior of not showing the listbox at all is correct, but in some cases it may be desirable to show a message like "No results found".

This could be the `empty-message` prop.

**Comment by sashamilenkovic** [comment]
This can now be done @latest tag, @justin-schroeder. https://formkit.link/9eb7fa5c48cedfaab36e0cb4c5c4fedd
