### ISSUE TITLE
Form submitted state not correct in different situtations

### ISSUE THREAD

**Issue by dominikklein** [formkit/formkit#503]
### Reproduction

https://formkit.link/9fc88976fc72d4d09f5deb2b1891abce

### Describe the bug

In the Multi-Step form from the documentation examples, I saw that the submitted state on the main form is not updated when I click on the submit button at the end (I mean not the "next Step"-Button).

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by devoidofgenius** [comment]
I could very well be misunderstanding your issue or completely missing something, but I'm unable to reproduce any issues given your reproduction link. Could you please provide a little more information regarding the expected behavior and what you're seeing on your end?

**Comment by dominikklein** [comment]
I'm talking about the `submitted` flag inside the state object in the node context. For example when you take a look in the Vue Dev-Console or when you want to use the node to check if the form was submitted in one place.

**Comment by justin-schroeder** [comment]
Ok — this is resolved in beta 16
