### ISSUE TITLE
Default value for Autocomplete and Taglist components cannot be removed when value is an object

### ISSUE THREAD

**Issue by jerrebm** [formkit/formkit#505]
### Reproduction

https://formkit.com/playground?files=JTVCJTdCJTIybmFtZSUyMiUzQSUyMmF1dG9jb21wbGV0ZS1zZWxlY3Rpb24tYXBwZWFyYW5jZS1vcHRpb24tbXVsdGlwbGUudnVlJTIyJTJDJTIyZWRpdG9yJTIyJTNBJTIyJTNDc2NyaXB0JTIwc2V0dXAlM0UlNUNuY29uc3QlMjBjb3VudHJpZXMlMjAlM0QlMjAlNUIlN0IlMjBsYWJlbCUzQSUyMCdBZmdoYW5pc3RhbiclMkMlMjB2YWx1ZSUzQSUyMCU3QmxhYmVsJTNBJTIwJ0FGJyUyQyUyMGlkJTNBJTIwMTIzJTdEJTIwJTdEJTJDJTdCJTIwbGFiZWwlM0ElMjAnWmltYmFid2UnJTJDJTIwdmFsdWUlM0ElMjAlN0JsYWJlbCUzQSUyMCdaVyclMkMlMjBpZCUzQSUyMDQ1NiU3RCUyMCU3RCU1RCU1Q24lM0MlMkZzY3JpcHQlM0UlNUNuJTVDbiUzQ3RlbXBsYXRlJTNFJTVDbiUyMCUyMCUzQ0Zvcm1LaXQlNUNuJTIwJTIwJTIwJTIwdHlwZSUzRCU1QyUyMmZvcm0lNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTIzZGVmYXVsdCUzRCU1QyUyMiU3QiUyMHZhbHVlJTIwJTdEJTVDJTIyJTVDbiUyMCUyMCUyMCUyMCUzQWFjdGlvbnMlM0QlNUMlMjJmYWxzZSU1QyUyMiU1Q24lMjAlMjAlM0UlNUNuJTIwJTIwJTIwJTIwJTNDRm9ybUtpdCU1Q24lMjAlMjAlMjAlMjAlMjAlMjB0eXBlJTNEJTVDJTIyYXV0b2NvbXBsZXRlJTVDJTIyJTVDbiUyMCUyMCUyMCUyMCUyMCUyMG5hbWUlM0QlNUMlMjJhdXRvY29tcGxldGUlNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwbGFiZWwlM0QlNUMlMjJTZWFyY2glMjBhbmQlMjBzZWxlY3QlMjBtdWx0aXBsZSUyMGNvdW50cmllcyU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0FvcHRpb25zJTNEJTVDJTIyY291bnRyaWVzJTVDJTIyJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQXZhbHVlJTNEJTVDJTIyJTVCJTdCbGFiZWwlM0ElMjAnQUYnJTJDJTIwaWQlM0ElMjAxMjMlN0QlNUQlNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwc2VsZWN0aW9uLWFwcGVhcmFuY2UlM0QlNUMlMjJvcHRpb24lNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwbXVsdGlwbGUlNUNuJTIwJTIwJTIwJTIwJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCU1Q24lMjAlMjAlMjAlMjAlM0NGb3JtS2l0JTVDbiUyMCUyMCUyMCUyMCUyMCUyMHR5cGUlM0QlNUMlMjJ0YWdsaXN0JTVDJTIyJTVDbiUyMCUyMCUyMCUyMCUyMCUyMG5hbWUlM0QlNUMlMjJ0YWdsaXN0JTVDJTIyJTVDbiUyMCUyMCUyMCUyMCUyMCUyMGxhYmVsJTNEJTVDJTIyU2VhcmNoJTIwYW5kJTIwc2VsZWN0JTIwbXVsdGlwbGUlMjBjb3VudHJpZXMlNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNBb3B0aW9ucyUzRCU1QyUyMmNvdW50cmllcyU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0F2YWx1ZSUzRCU1QyUyMiU1QiU3QmxhYmVsJTNBJTIwJ0FGJyUyQyUyMGlkJTNBJTIwMTIzJTdEJTVEJTVDJTIyJTVDbiUyMCUyMCUyMCUyMCUyMCUyMG11bHRpcGxlJTVDbiUyMCUyMCUyMCUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlM0NwcmUlMjB3cmFwJTNFJTdCJTdCJTIwdmFsdWUlMjAlN0QlN0QlM0MlMkZwcmUlM0UlNUNuJTIwJTIwJTNDJTJGRm9ybUtpdCUzRSU1Q24lM0MlMkZ0ZW1wbGF0ZSUzRSU1Q24lNUNuJTIyJTJDJTIyYWRkZWQlMjIlM0F0cnVlJTdEJTVE&css-framework=genesis&fkv=1.0.0-beta.13&fileTab=autocomplete-selection-appearance-option-multiple.vue&imports=JTdCJTIybmFtZSUyMiUzQSUyMkltcG9ydE1hcCUyMiUyQyUyMmVkaXRvciUyMiUzQSUyMiU3QiU1Q24lMjAlMjAlNUMlMjJ2dWUlNUMlMjIlM0ElMjAlNUMlMjJodHRwcyUzQSUyRiUyRmNkbi5qc2RlbGl2ci5uZXQlMkZucG0lMkZ2dWUlNDAzJTJGZGlzdCUyRnZ1ZS5lc20tYnJvd3Nlci5taW4uanMlNUMlMjIlNUNuJTdEJTVDbiUyMiU3RA

### Describe the bug

I ran into an issue with the `autocomplete` and `taglist` components, where the pre-populated value cannot be removed when the value is an object. It is still possible to add and remove other values that have not been pre-populated.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by sashamilenkovic** [comment]
@jerrebm Hey! On the @latest tag, you can now remove options even when their value is an object or array.
