### ISSUE TITLE
Property is removed from object when the attached input is removed from the DOM

### ISSUE THREAD

**Issue by jith51** [formkit/formkit#509]
### Reproduction

https://formkit.link/a83b241dc9f7cf240419d816bd908a35

### Describe the bug

Hi,
I have a list of objects in which i want to delete and add objects.
In the purpose to tell my api that an object must be deleted, i mark this object with new property _destroy set to '1'.
When I delete an object i remove it from the DOM.
Then I always have my object with the property id and the property _destroy mark but the other property are deleted.

It seems strange that when you remove an input from the DOM, the attached property is remove from the object.

Best regards 

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
This is the default behavior, most of the time it makes sense for the value to be removed. If you want to preserve the value you can use the `preserve` prop. Docs for that are here: https://formkit.com/inputs/form#clearing-errors#unmounting-inputs

**Comment by jith51** [comment]
Hi, thanks for this answer
