### ISSUE TITLE
Reactivity issue with loop when reset form

### ISSUE THREAD

**Issue by jith51** [formkit/formkit#512]
### Reproduction

https://formkit.link/964e8178027f98c9d392201a313d6534

### Describe the bug

Hi,

When i reset my form with  a second argument (reset(formId, initialState)) in order to change the reset state, the loop reactivity don't work.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
Thanks for the reproduction — we’ll look into this.

**Comment by justin-schroeder** [comment]
This is related to list index stability, which we are addressing in our stability sprint — closing this in favor of #293
