### ISSUE TITLE
v-if directive is not working for groups that are inside other component

### ISSUE THREAD

**Issue by Nks** [formkit/formkit#513]
### Reproduction

Inside the component: https://formkit.link/82dde7ae2c35b2dcebd74561e03d0b9a

Outside the component: https://formkit.link/4ffdb347be0009da7510ab9b34c83b72

### Describe the bug

When a developer is trying to set up dynamic components with the groups inside the component, it works only once and then stops showing any forms;

FormKit group outside the component with the "v-if" directive also doesn't work.

I'm aware of [Multi step](https://formkit.com/guides/build-a-multi-step-form) that uses the `v-show` directive. Still, the problem is more than this: the `v-show` directive couldn't remove parasitic elements created by custom fields and attached to the dom (such as TinyMCE editor that creates a dropdown for the editor), and when the user switched between the tabs these elements still visible. Also, forms with many inputs on different tabs will create unnecessary memory usage.

![screenshot 2022-12-21 at 03 48 15](https://user-images.githubusercontent.com/349293/208817211-bc7e962a-0904-410a-affa-ede164bb2f0c.gif)

### Environment

• OS: macOS
• Browser Chome
• Version Version 108.0.5359.124 (Official Build) (arm64)

**Comment by sashamilenkovic** [comment]
@Nks https://formkit.link/f6a29cb53f9337b8a8bcd92e3caac460. If you throw on the `preserve` attribute I think this should solve your issue.

**Comment by Nks** [comment]
@sashamilenkovic thanks! Very implicit behavior, if you ask me.

**Comment by sashamilenkovic** [comment]
@Nks Agreed. Should at least be more explicitly mentioned in the docs.

**Comment by justin-schroeder** [comment]
Perhaps in the case of tabs it is implicit that you want to preserve the data, but usually fields are added/removed as conditionals, and in those cases you generally do not want the removed values to be preserved. So a bit of give and take for different use cases is at play here — for more on that here is the documentation on the preserve prop: https://formkit.com/inputs/form#unmounting-inputs#unmounting-inputs
