### ISSUE TITLE
FormKitIcon doesn't work in schema

### ISSUE THREAD

**Issue by jith51** [formkit/formkit#515]
### Reproduction

https://formkit.link/b95181fddf060b251a15ccbe9b0a2e7c

### Describe the bug

{
    $cmp: 'FormKitIcon',
    props: {
      icon: 'heart'
    }
render <formkiticon icon="heart"></formkiticon>
instead the icon 

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
`FormKitIcon` was imported in your local component, but never passed to the schema. Schema needs to reference either globally registered components, or it needs to have the components passed to it via the library prop. Here's an updated example: https://formkit.link/70c27314c1a608e67178eb9c66b79553

You can read more about how to render components via schema here: https://formkit.com/essentials/schema#components-cmp

**Comment by jith51** [comment]
Thans,
So you can't use component in custom Input or there is a way for that ?

{
  // Node type: input, group, or list.
  type: 'input',
  // Schema to render (schema object or function that returns an object)
  schema: [],
  // A Vue component to render (use schema _OR_ component, but not both)
  component: YourComponent,
  // (optional) Input specific props the <FormKit> component should accept.
  // should be an array of camelCase strings
  props: ['fooBar'],
  // (optional) Array of functions that receive the node.
  features: []
}

**Comment by justin-schroeder** [comment]
You can. That is an input definition, not schema. Not sure im following your question here.
