### ISSUE TITLE
Autocomplete on Mobile

### ISSUE THREAD

**Issue by aljabr** [formkit/formkit#516]
### Reproduction

https://formkit.com/inputs/autocomplete

### Describe the bug

When dismissing the keyboard on the ios, the list keeps appearing

It should be dismissed when the input not blurred

![C517F873-D596-49E3-A60F-58FFB595A82B](https://user-images.githubusercontent.com/15986585/209588425-cde05edc-348e-402e-b4c1-4b361619728a.png)

### Environment

• OS: [iOS]
• Browser [safari]

**Comment by sashamilenkovic** [comment]
@aljabr This has been fixed at @latest tag.
