### ISSUE TITLE
Dirty state don't switch to false after value is the same like the initial value

### ISSUE THREAD

**Issue by dominikklein** [formkit/formkit#520]
### Reproduction

https://formkit.link/b777a6e964e28f8297fd4af668533f06

### Describe the bug

Currently, the dirty flag will not switch to `false` again, when the value is switched back to the initial value.

I would expect that the dirty flag will be switched again because the field has no longer a changed value compared to the initial state.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by GustavoFenilli** [comment]
I would say that even if you switched back to the initial value, the input is still dirty ( as it was modified at some point ) but not sure about that, if dirty would mean ( value that is not the initial value ).

What do you think @justin-schroeder?

**Comment by justin-schroeder** [comment]
It depends probably. If we're talking about performing a `reset` — I think it should be clean again, but when the values are simply changed back to a matching value I'm less sure. Mostly this would require a relatively expensive comparison on large forms that I'm not sure we should. That said it would be super easy to do a JSON comparison with a hook on the form node.

**Comment by dominikklein** [comment]
Yes I understand the different views. I think as a developer it's often like you both describe, but when I asked more non technical persons they are always saying that the field is no longer dirty because the value is again equal the initial value.

**Comment by andrew-boyd** [comment]
"Dirty" means it's been touched — even if you put the value back it's still "dirty" because it was touched. A form reset does set things back to a pristine state. I'm in favor of keeping this behavior as-is because it's consistent with other libraries that track `dirty` state and deviating from that behavior would cause more issues than it would solve.

**Comment by dominikklein** [comment]
I think when we only talking about technical stuff, I fully agree. But I think the understanding of such information is also related to the placement of a form and usage of a form.
And your description sounds to me, that this is more like a `touched` state instead of a `dirty` state. I saw also products where such a flag is not like it's currently implemented in FormKit. 
Maybe the behavior can/should be configurable or there should be an additional state?

In the end, I know that I have possibilities to make it work as we need it in our product, but it's currently a little bit frustrating that we need a lot of these modifications.

**Comment by GustavoFenilli** [comment]
Well a touched state, is when a input was touched, not changed per say, dirty is a touched + changed state.

**Comment by anabatel1** [comment]
What prop should be used to determine the case when _the form after changes_ is equal to the _initial form_?

**Comment by justin-schroeder** [comment]
@anabatel1 currently there is no prop to do that, but it could be done with a simple plugin. The reason this isnt in FormKit core is it is a relatively expensive operation (performance wise) to be doing on every keystroke). Here’s an example:

https://formkit.link/faefe301e91b914bfb68d982c2a71587

**Comment by dominikklein** [comment]
@justin-schroeder Any thoughts about the future of a topic? Otherwise, I will try it on my own with a small plugin for now.

**Comment by justin-schroeder** [comment]
Good news! We’ve decided to include this feature as an optional opt-in. You can enable *actual* comparisons on a given input by specifying `dirty-behavior="compare"`.

https://formkit.link/888da1366684c92f3afdf368417985e4
(might need a hard refresh)
