### ISSUE TITLE
Focus class on outer wrapper

### ISSUE THREAD

**Issue by MortenHe** [formkit/formkit#524]
### Describe the feature

It would be great if FormKit would set an focus class on the outer wrapper of a FormKit input, so I could style the whole block.

I often have forms with a lot of text inputs where you TAB from one input to the next. It would be helpful to see which input block is focused at the moment.

If there was a focus class on the outer wrapper, it would be easy to style the form like this:

![focus](https://user-images.githubusercontent.com/2443839/210737190-ad3bad1a-1d19-47ae-a87d-123315f7e1ff.jpg)

Many greetings and happy New Year (a little bit late ;-))

**Comment by GustavoFenilli** [comment]
You can easily do it using the `has`css selector
```css
.formkit-outer:has(input:focus) {
  background-color: red;
}
```

**Comment by MortenHe** [comment]
Wow, I didn't know that has:() is already ready to use. Just waiting for firefox ;-)

But I realized that I can achieve the same effect with :focus-within which is supported in firefox:

.formkit-outer:focus-within {
  background-color: red;
}

Thank you for pushing me in the right direction.
