### ISSUE TITLE
Tailwind Theme Icons not sizing correctly

### ISSUE THREAD

**Issue by HydraCOREY** [formkit/formkit#526]
### Reproduction

https://formkit.com/playground?fkv=1.0.0-beta.12&fileTab=Playground.vue&files=JTVCJTdCJTIybmFtZSUyMiUzQSUyMlBsYXlncm91bmQudnVlJTIyJTJDJTIyZWRpdG9yJTIyJTNBJTIyJTNDc2NyaXB0JTIwc2V0dXAlM0UlNUNuJTJGJTJGJTIwRVNNJTIwaW1wb3J0cyUyMGFyZSUyMHN1cHBvcnRlZCUyMGZyb20lMjBVUkxzJTIwKGh0dHBzJTNBJTJGJTJGY2RuLi4uKSU1Q24lMkYlMkYlMjBhcyUyMHdlbGwlMjBhcyUyMHNlY29uZGFyeSUyMHBsYXlncm91bmQlMjBmaWxlcyUyMCguJTJGT3RoZXJGaWxlLnZ1ZSkuJTVDbiUzQyUyRnNjcmlwdCUzRSU1Q24lNUNuJTNDdGVtcGxhdGUlM0UlNUNuJTIwJTIwJTNDRm9ybUtpdCU1Q24lMjAlMjAlMjAlMjB0eXBlJTNEJTVDJTIydGV4dCU1QyUyMiU1Q24lMjAlMjAlMjAlMjBwcmVmaXgtaWNvbiUzRCU1QyUyMmNsb3NlJTVDJTIyJTVDbiUyMCUyMCUyMCUyMHByZWZpeC1pY29uLWNsYXNzJTNEJTVDJTIyaC00JTIwdy00JTVDJTIyJTVDbiUyMCUyMCUyMCUyMHN1ZmZpeC1pY29uJTNEJTVDJTIyY2xvc2UlNUMlMjIlNUNuJTIwJTIwJTIwJTIwc3VmZml4LWljb24tY2xhc3MlM0QlNUMlMjJoLTQlMjB3LTQlNUMlMjIlNUNuJTIwJTIwJTIwJTIwbGFiZWwlM0QlNUMlMjJGb3JtS2l0JTIwSW5wdXQlNUMlMjIlNUNuJTIwJTIwJTIwJTIwaGVscCUzRCU1QyUyMmVkaXQlMjBtZSUyMHRvJTIwZ2V0JTIwc3RhcnRlZCU1QyUyMiU1Q24lMjAlMjAlMkYlM0UlNUNuJTNDJTJGdGVtcGxhdGUlM0UlNUNuJTVDbiUzQ3N0eWxlJTIwc2NvcGVkJTNFJTVDbiUyRiolNUNudmFuaWxsYSUyMENTUyUyMGNhbiUyMGdvJTIwaGVyZS4lNUNuS2VlcCUyMHN0eWxlcyUyMHNjb3BlZCUyMHRvJTIwYXZvaWQlMjBtdWx0aXBsZSUyMGZpbGVzJTVDbm92ZXJ3cml0aW5nJTIwZWFjaCUyMG90aGVyJTIwaW4lMjB0aGUlMjByZW5kZXIlMjBvdXRwdXQuJTVDbiolMkYlNUNuJTNDJTJGc3R5bGUlM0UlNUNuJTIyJTJDJTIyYWRkZWQlMjIlM0F0cnVlJTdEJTVE&css-framework=tailwind&cssFramework=tailwind

### Describe the bug

When adding any icons, they aren't scaled properly to the tailwind classes. Even the default seems to be presented max width and height.

### Environment

• OS: Window 11
• Browser: Any
• Version: 
    "@formkit/themes": "^1.0.0-beta.12",
    "@formkit/vue": "^1.0.0-beta.12",

**Comment by justin-schroeder** [comment]
Just the joys of styling at play here. I believe you just needed those wrappers to have block styling. There is no "default" styles since you're writing your own in this case with tailwind. Here's a working example: https://formkit.link/6b0eab33fe725bc23add876aae55ac3c

Good luck!

**Comment by CoreyVincent** [comment]
@justin-schroeder Thank you.
