### ISSUE TITLE
Add an option for schema’s to use a root node.

### ISSUE THREAD

**Issue by comhon-project** [formkit/formkit#528]
### Reproduction

https://formkit.link/86188930334078cf5d518641afe800a6

### Bug: 
when render `$formkit` children in a `TransitionGroup` the following error is raised: 
```
t.el.getBoundingClientRect is not a function
```
### Workaround:
wrap `$formkit` child with a `$cmp: div` (on playground example: click on toggle button to see the schema with wrapper)

### Expected:
should works without a wrapper

### Environment

• OS: Ubuntu
• Browser firefox and chrome
• Version FormKit beta.12

**Comment by justin-schroeder** [comment]
This is because FormKit inputs do not have a root node. This allows modification to each input to allow adjacent dom structure. Unlikely to change, but maybe we can have some sort of option for this in the future. I'll tag it as an enhancement.

**Comment by comhon-project** [comment]
okay thanks for the quick answer.
