### ISSUE TITLE
Dirty flag for existing groups are switched to "true" when additional group is added in schema

### ISSUE THREAD

**Issue by dominikklein** [formkit/formkit#529]
### Reproduction

https://formkit.link/3e1450969b7d8401ea94c52421db6598

### Describe the bug

When a schema has multiple groups and one is hidden with an `if` condition, only the change for this hidden group to a visible state will switch the dirty flag for all existing groups to `true`.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
I think this one is resolved in the upcoming beta 16
