### ISSUE TITLE
Preserve all keys/values when placing "preserve" attribute on overarching inputs or schema

### ISSUE THREAD

**Issue by arjendejong12** [formkit/formkit#53]
**Describe the bug**
Placing the `preserve` attribute on `<FormKit type="form" />` or `<FormKitSchema />` does not result in keeping all keys/values when a pair gets unmounted.

**Reproduction**
[FormKit playground](https://formkit.link/08fff231e95c83d4fe55c0cf2bb04294)

**Comment by justin-schroeder** [comment]
This is now included in beta.2
