### ISSUE TITLE
Formkit TailwindCSS variants "formkit-has-prefix-icon"/"formkit-has-suffix-icon" not working

### ISSUE THREAD

**Issue by fabiangfd** [formkit/formkit#530]
### Reproduction

https://formkit.link/9e61f0e1e2afc1dabb9a7739a6cdb3d3

### Describe the bug

Conditional formating via [TailwindCSS variants](https://formkit.com/guides/create-a-tailwind-theme#using-variants) works fine in general, but the icon related variants "formkit-has-prefix-icon" and "formkit-has-suffixicon" are not working for me. (See [playground](https://formkit.link/9e61f0e1e2afc1dabb9a7739a6cdb3d3))

### Environment

Version: 1.0.0 beta 12 (latest)
TailwindCSS

**Comment by GustavoFenilli** [comment]
This is a known bug and it will be fixed at `beta.13`
