### ISSUE TITLE
Conditionally defined fields works incorrect with different fields

### ISSUE THREAD

**Issue by Nks** [formkit/formkit#538]
### Reproduction

https://formkit.link/ab126c0526bc084ea49a1eb82395a6eb

### Describe the bug

When defining the conditional logic to show different fields based on another field, the FormKit doesn't get actual value from the `data` but instead shows the value from another field and stores the data in an incorrect field.

Video:

https://user-images.githubusercontent.com/349293/212415126-ea7ebd59-13df-40ce-9062-eb2b00b9f4ed.mp4

### Environment

• OS: any
• Browser chrome
• Version latest

**Comment by GustavoFenilli** [comment]
This is not a bug, when using schema you need to specify the `:key` prop so Vue does not reuse the same input when changing the inputs: https://formkit.link/3dd0691804f063389371819c20f3a232
