### ISSUE TITLE
checkbox label not modified by :sections-schema prop

### ISSUE THREAD

**Issue by agenordebriat** [formkit/formkit#541]
### Reproduction

https://formkit.link/1e3a8f354435dbbf99e0eaba00c5677b

### Describe the bug

Following an issue brought by user "Nonchalant" on Discord, @GustavoFenilli  and I noticed that the `label` section of a `checkbox` input is not modified by the `:sections-schema` prop, see reproduction playground.

Every other section seems to be fine.

### Environment

- Playground environment

**Comment by GustavoFenilli** [comment]
It works at `@next` on `beta.13`

**Comment by agenordebriat** [comment]
Nice to know! Thanks.
