### ISSUE TITLE
Add AutoAnimate plugin to the repeater.

### ISSUE THREAD

**Issue by justin-schroeder** [formkit/formkit#555]
### Reproduction

https://formkit.link/455311c11055c775cfbccf5e3196873a

### Describe the bug

The AutoAnimate plugin should be applied on the inner `fieldset` as well. Ideally we would do this by using schema meta to indicate AutoAnimate should be applied on that item.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by andrew-boyd** [comment]
Love the idea of having meta in the schema to control how the animations should be applied.
