### ISSUE TITLE
FormKit clearErrors not working

### ISSUE THREAD

**Issue by azertyalex** [formkit/formkit#559]
### Reproduction

https://formkit.link/4a692575171a6b9e02511a5c98801938

### Describe the bug

`clearErrors` should clear all form errors, also, using parameter `clearChildren` does not help.
Neither does walking over all children and calling `clearErrors` respectively.

https://formkit.com/api-reference/formkit-core#clearerrors#clearerrors

### Environment

• OS: Ubuntu
• Browser chrome
• Version 1.4 Beta

**Comment by sashamilenkovic** [comment]
@azertyalex I think there's a little bit of confusion here between errors and validation messages. Errors are set explicitly (think server-side validation). Here is an example of setting an error on submit and then using clearErrors to remove them: https://formkit.link/652b964887f6e35599f8aec535a10ecd. Validation messages on the other hand are rendered according to the validation-visibility prop.

**Comment by justin-schroeder** [comment]
If you have further questions about the distinction, join us on the discord server and we can hash it out further 👍
