### ISSUE TITLE
Cannot find module '@formkit/themes/tailwindcss/genesis'

### ISSUE THREAD

**Issue by sashamilenkovic** [formkit/formkit#560]
### Reproduction

https://formkit.com/getting-started/installation

### Describe the bug

The genesis theme is not found `import genesis from '@formkit/themes/tailwindcss/genesis'`, per instructions for importing the Tailwind version of genesis theme https://formkit.com/getting-started/installation

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by andrew-boyd** [comment]
Looks like the genesis export alias didn't make it to the `package.json` for the `@formkit/themes` package. Changing the import to include the `/dist/` directory in the path will work for the time being. 

so this: 
`import genesis from '@formkit/themes/tailwindcss/genesis'`

becomes: 
`import genesis from '@formkit/themes/dist/tailwindcss/genesis'`

**Comment by Namianya** [comment]
am still having the issue with nuxt
this is the error

[vite] Internal server error: Missing "./dist/tailwindcss/genesis" export in "@formkit/themes" package

**Comment by aerophobic** [comment]
experiencing the same issue as @michelveloso

**Comment by GustavoFenilli** [comment]
Are you all at `beta.15`?

**Comment by aerophobic** [comment]
thx for your superfast answer! I'm on `1.0.0-beta.14` this was the latest, half an hour ago 😄

**Comment by GustavoFenilli** [comment]
yes `beta.14` is the current one, just make sure you're at `beta.15` and see if you can still experience the problem.

**Comment by aerophobic** [comment]
my bad, I didnt see this issue was added to the milestone of `beta.15` - I just updated `@formkit/nuxt`, `@formkit/icons`, `@formkit/themes` to `1.0.0-beta.15-3995886`. unfortunately this does not change the import issue

**Comment by GustavoFenilli** [comment]
I will take a look thank you.

**Comment by andrew-boyd** [comment]
This has been published under the `@next` tag

**Comment by vctrtvfrrr** [comment]
Still with error on Nuxt 3:

package.json
```json
  "devDependencies": {
    "@formkit/icons": "^1.0.0-beta.15-6f87a41",
    "@formkit/nuxt": "^1.0.0-beta.15-6f87a41",
    "@formkit/themes": "^1.0.0-beta.15-6f87a41",
  }
```

formkit.config.ts
```typescript
import { DefaultConfigOptions } from "@formkit/vue";
import { genesisIcons } from "@formkit/icons";
import { generateClasses } from "@formkit/themes";
import genesis from "@formkit/themes/dist/tailwindcss/genesis";

const config: DefaultConfigOptions = {
  icons: { ...genesisIcons },
  config: {
    classes: generateClasses(genesis),
  },
};

export default config;
```

![image](https://user-images.githubusercontent.com/1169416/215533047-a479337d-ccc1-43f1-9141-349d91990ae2.png)

**Comment by andrew-boyd** [comment]
@vctrtvfrrr `/dist/` no longer required in the path for the `@next` tag. try `import genesis from "@formkit/themes/tailwindcss/genesis";`

**Comment by vctrtvfrrr** [comment]
![image](https://user-images.githubusercontent.com/1169416/215538739-f10e9e37-cdbe-4256-836c-e5acb2550423.png)

Despite the TypeScript warning, worked just fine. Thanks for the great job.

**Comment by aerophobic** [comment]
works like a charm, thank you so much @andrew-boyd 🙏🏼

**Comment by andrew-boyd** [comment]
> ![image](https://user-images.githubusercontent.com/1169416/215538739-f10e9e37-cdbe-4256-836c-e5acb2550423.png)
> 
> Despite the TypeScript warning, worked just fine. Thanks for the great job.

Does this error persist if you restart VSCode's typescript server?

**Comment by aerophobic** [comment]
on my end the ts error issue is gone as soon as I start the server

**Comment by vctrtvfrrr** [comment]
> > ![image](https://user-images.githubusercontent.com/1169416/215538739-f10e9e37-cdbe-4256-836c-e5acb2550423.png)
> > Despite the TypeScript warning, worked just fine. Thanks for the great job.
> 
> Does this error persist if you restart VSCode's typescript server?

Everything working fine.

**Comment by PsclDev** [comment]
Can also confirm on my side the latest @next tag fixed the issue and its working including typescrpt after restarting ts server

**Comment by Ragura** [comment]
You can fix the issue by importing the config type as mention here: https://github.com/formkit/formkit/issues/577#issuecomment-1434718636

**Comment by sr-skillmore** [comment]
Still getting this error.

**Comment by sashamilenkovic** [comment]
@sr-skillmore Any chance you can make a reproduction I could take a look at?

**Comment by sr-skillmore** [comment]
> @sr-skillmore Any chance you can make a reproduction I could take a look at?

This the reproduction, the red squiggly like still shows up in the `formkit.config.ts` file.

https://stackblitz.com/edit/nuxt-starter-xv4bnr?file=package.json,nuxt.config.ts,formkit.config.ts,app.vue,tailwind.config.js

**Comment by sashamilenkovic** [comment]
@sr-skillmore I am also running into an issue with this. Not sure if it's due to instructions or an internal issue. We'll look into this more tomorrow.

**Comment by sashamilenkovic** [comment]
@sr-skillmore Spoke to the team, and it seems like the installation instructions are wrong. I will look into updating those. The import path should be: `import genesis from '@formkit/themes/dist/tailwindcss/genesis'`

**Comment by sr-skillmore** [comment]
> @sr-skillmore Spoke to the team, and it seems like the installation instructions are wrong. I will look into updating those. The import path should be: `import genesis from '@formkit/themes/dist/tailwindcss/genesis'`

Thank you for the response, but adding the `dist` path also does not work for me. Please see the recreation on stackblitz here: https://stackblitz.com/edit/nuxt-starter-xv4bnr?file=package.json,nuxt.config.ts,formkit.config.ts,app.vue,tailwind.config.js 

The error in the image is what shows up for me.

![Screenshot 2023-06-23 at 10 13 34 AM](https://github.com/formkit/formkit/assets/123024042/56b57c1e-4eba-4573-a239-2367608a0943)

**Comment by duyn-stanford** [comment]
Seeing same error for a Laravel/Inertia/Vue/Tailwind project:

```
// app.js

import './bootstrap';
import '../css/app.css';

import { createApp, h } from 'vue';
import { createInertiaApp } from '@inertiajs/vue3';
import { resolvePageComponent } from 'laravel-vite-plugin/inertia-helpers';
import { ZiggyVue } from './vendor/tightenco/ziggy/dist/vue.m';
import { plugin as formkitPlugin, defaultConfig } from '@formkit/vue';
import { generateClasses } from '@formkit/themes';
import { genesisIcons } from '@formkit/icons';
import genesis from '@formkit/themes/dist/tailwindcss/genesis';

const appName = window.document.getElementsByTagName('title')[0]?.innerText || 'Laravel';

createInertiaApp({
    title: (title) => `${appName} ${title ? '- ' + title : ''}`,
    resolve: (name) => resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob('./Pages/**/*.vue')),
    setup({ el, App, props, plugin }) {
        return createApp({ render: () => h(App, props) })
            .use(plugin)
            .use(ZiggyVue, Ziggy)
            .use(
                formkitPlugin,
                defaultConfig({
                    icons: {
                        ...genesisIcons,
                    },
                    config: {
                        classes: generateClasses(genesis),
                    },
                })
            )
            .mount(el);
    },
    progress: {
        color: '#8c1515',
        showSpinner: true,
    },
});
```

```
// tailwind.config.js
/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './node_modules/@formkit/themes/dist/tailwindcss/genesis/index.cjs',
        './resources/js/**/*.vue',
    ],
    plugins: [
        require('@tailwindcss/forms'),
        require('tailwindcss-debug-screens'),
        require('@formkit/themes/tailwindcss'),
    ],
};
```

![Screenshot 2023-06-27 at 3 04 11 PM](https://github.com/formkit/formkit/assets/89502875/6b40f0bb-59be-4b58-9abb-a05e099337e5)

**Comment by GustavoFenilli** [comment]
The correct import is without `dist` like so: `import genesis from '@formkit/themes/tailwindcss/genesis';` but it looks like some module resolutions do not correctly get this, so in those cases you may need to change the module resolution of your application.

With that in mind, we are recommending people to create a `themes.js` file and copy the contents of the ts export there instead https://formkit.com/guides/create-a-tailwind-theme#a-complete-tailwind-theme-recreating-genesis-css

**Comment by duyn-stanford** [comment]
> The correct import is without `dist` like so: `import genesis from '@formkit/themes/tailwindcss/genesis';` but it looks like some module resolutions do not correctly get this, so in those cases you may need to change the module resolution of your application.
> 
> With that in mind, we are recommending people to create a `themes.js` file and copy the contents of the ts export there instead [formkit.com/guides/create-a-tailwind-theme#a-complete-tailwind-theme-recreating-genesis-css](https://formkit.com/guides/create-a-tailwind-theme#a-complete-tailwind-theme-recreating-genesis-css)

Thank you. This fixed my issue.
