### ISSUE TITLE
V-model data being cleared when hiding forms without any user action on the form itself

### ISSUE THREAD

**Issue by angelblanco** [formkit/formkit#562]
### Reproduction

https://formkit.link/f60ab208ff332707fffd65bb4f4a5f70

### Describe the bug

Hello and Thank you for creating this library!

I have found a bug. If you conditionally render a form, the data passed through v-model is being cleared when unmouting the component.

I think this is not intendeed and I thinks theres no easy way to "hack" this behaviour as  v-model is not throwing `update:model-value` events.

I've created a simple reproduction link.

Thanks!

### Environment

• OS: Linux
• Browser: Chrome
• Version beta.14

**Comment by angelblanco** [comment]
Ok!!! Thank you, sorry!

**Comment by sashamilenkovic** [comment]
@angelblanco No problem! It isn't easy to find in the docs unless you know what you're looking for.
