### ISSUE TITLE
Autocomplete bug after manually changing input

### ISSUE THREAD

**Issue by huzaifahj** [formkit/formkit#564]
### Reproduction

https://formkit.link/7b3f530255f8bf96086634b38826a668

### Describe the bug

1. Select an option e.g. "Afghanistan"
2. Add a letter on the end to make it e.g. "AfghanistanX"
3. Click dropdown button
4. Dropdown button doesn't work

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by sashamilenkovic** [comment]
@huzaifahj The listbox is not reopening because there are no options found when you search for "AfghanistanX". If you'd like, you can add an `empty-message` prop that will render when no options are found: https://formkit.link/087461efd62e45a2fa452b7390fb740e.

**Comment by sashamilenkovic** [comment]
@huzaifahj I'm going to close this for now, but let me know if you have any further questions.
