### ISSUE TITLE
phone mask fails to compile

### ISSUE THREAD

**Issue by drev74** [formkit/formkit#568]
### Reproduction

https://formkit.link/0cad60aade1dd7da188fce2d5022ea63

### Describe the bug

Related to #296

I tried to pick an example from docs, but it fails to compile on my lap.

Chromium: Version 109.0.5414.119 (Official Build) snap (64-bit)
FireFox: Version 109.0 (64-bit)
NodeJS: 18.13.0

```bash
Uncaught (in promise) Error: Unknown input type "mask" ("phone")
    error index.mjs:273
    useInput index.mjs:1157
    setup index.mjs:732
    callWithErrorHandling runtime-core.esm-bundler.js:173
    setupStatefulComponent runtime-core.esm-bundler.js:7265
    setupComponent runtime-core.esm-bundler.js:7220
```

### Environment

• OS: Ubuntu 21
• Browser Chromium, Firefox

Chromium: Version 109.0.5414.119 (Official Build) snap (64-bit)
FireFox: Version 109.0 (64-bit)
NodeJS: 18.13.0

```json
"@formkit/vue": "^1.0.0-beta.15-6f87a41",
"vue": "^3.2.47"
```

**Comment by andrew-boyd** [comment]
Hey @drev74 you'll need to install the `@formkit/pro` package since the mask is in the pro set of inputs.

https://formkit.com/getting-started/installation#adding-pro-inputs

**Comment by andrew-boyd** [comment]
I'm going to close this issue for now, please feel free to reach back out if you have any issues getting `@formkit/pro` added to your project.
