### ISSUE TITLE
Bundle Size Increases

### ISSUE THREAD

**Issue by totalhack** [formkit/formkit#569]
### Reproduction

N/A

### Describe the bug

I have been pinned to 1.0.0-beta.11, but during another change today I figured I'd try 1.0.0-beta.14. In doing so all of my output bundle sizes increased by 20%. Reverted back to 1.0.0-beta.11 and it immediately resolved the issue.

I did see this in the log when building with vite:

```
transforming (80) node_modules/core-js/internals/dom-token-list-prototype.js[BABEL] Note: The code generator has deoptimised the styling of /node_modules/@formkit/i18n/dist/index.mjs as it exceeds the max of 500KB.
```

I'm fine with sticking with beta.11 for now but figured I'd give you guys a heads up.

### Environment

• OS: Linux
• Browser: N/A
• Version: 1.0.0-beta.14

**Comment by justin-schroeder** [comment]
What build tool are you using? Does it tree shake? You shouldn't need to import any languages other than those you want to use.

**Comment by totalhack** [comment]
I'm not explicitly importing or trying to use any languages, though English is all I need. Maybe something I'm doing is accidentally pulling in il8n code I don't need (apologies if that ends up being the case!). I just reinstalled beta.14 again to get more info for you and I'm now seeing slightly different results -- an increase in the 5% range -- which is also odd.

This project is using Vite 2.9.4 and building multiple targets, and each outputting es, umd, and iife formats. 

For the baseline build target the babel plugin is not used and so the core-js warning above is not seen, though the bundle size for that also increases with 1.0.0-beta.14. The target that utilizes babel/core-js produces that warning above but increases by roughly the same net number of bytes as the baseline bundle comparing beta.11 to beta.14.

**Comment by justin-schroeder** [comment]
A small increase in bundle is inevitable as features get added occasionally (most should tree shake), but i18n shouldn't contribute very much at all to your overall bundle size — if it is, then something must not be tree shaking properly. That can be on the bundler, our export structure, or the implementation. That said, I dont think anything changed significantly between 11 and 14 that would cause a significant bundle bloat.

Perhaps core-js doesn't tree shake? I dont know enough about it.

**Comment by totalhack** [comment]
That core-js message could be a red herring, and maybe what it does is transform all of the things it finds in node modules even if they dont end up getting used (I'm also clearly no expert). Considering the net bundle size increase for that build target wasn't much different than the base target that doesn't use it, I'll just ignore the core-js stuff. 

It is quite odd to me that the first time I tried updating it showed 20% and now it doesn't, which almost certainly has nothing to do with formkit. 

These are the only imports from formkit I'm doing in the project, FYI. Not sure if that changes the expectation around whether new features between beta.11 and beta.14 would increase my output size by ~30kb in the es output (15kb in the iife/umd minified output).

```
import { createMessage, getNode } from '@formkit/core'

// another file

import { plugin, defaultConfig, createInput } from '@formkit/vue'
import { generateClasses } from '@formkit/tailwindcss'
```

If you think this is just expected behavior we can go ahead and close this.

**Comment by justin-schroeder** [comment]
Hmmm. 30Kb increase is definitely waaay more than I would expect. Something is definitely being included in your bundle that shouldn't be. Unfortunately I have no idea without analyzing it myself — any chance you can do a package analysis to see where the weight is coming from?

**Comment by totalhack** [comment]
Bundle analysis differences between beta.11 and beta.14 for the top 10 size contributors in my build output:

beta.11:

```
/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js
█████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 19.64 % (157.74 KB)
/node_modules/@formkit/core/dist/index.mjs
█████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 10.55 % (84.739 KB)
/node_modules/@formkit/vue/dist/index.mjs
███░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 7.76 % (62.315 KB)
/node_modules/@formkit/inputs/dist/index.mjs
██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 5.54 % (44.505 KB)
/node_modules/date-fns/esm/parse/_lib/parsers/index.js
██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 5.36 % (43.054 KB)
/node_modules/vue3-datepicker/dist/vue3-datepicker.esm.js
██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 5.16 % (41.403 KB)
/node_modules/formkit-multistep/dist/formkit-multistep.es.js
██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 4.96 % (39.819 KB)
/node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js
██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 4.06 % (32.602 KB)
/node_modules/date-fns/esm/parse/index.js
█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 3.88 % (31.165 KB)
/node_modules/date-fns/esm/format/index.js
█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 3.29 % (26.42 KB)
```

beta.14

```
/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js
███████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 14.39 % (157.74 KB)
/node_modules/@formkit/vue/node_modules/@formkit/core/dist/index.mjs
████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 8.56 % (93.761 KB)
/node_modules/@formkit/vue/dist/index.mjs
███░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 6.06 % (66.394 KB)
/node_modules/@formkit/inputs/dist/index.mjs
██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 4.51 % (49.444 KB)
/node_modules/@formkit/inputs/node_modules/@formkit/core/dist/index.mjs
██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 4.33 % (47.426 KB)
/node_modules/@formkit/validation/node_modules/@formkit/core/dist/index.mjs
██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 4.27 % (46.763 KB)
/node_modules/@formkit/observer/node_modules/@formkit/core/dist/index.mjs
██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 4.27 % (46.763 KB)
/node_modules/@formkit/dev/node_modules/@formkit/core/dist/index.mjs
██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 4.27 % (46.763 KB)
/node_modules/@formkit/core/dist/index.mjs
██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 4.23 % (46.363 KB)
/node_modules/date-fns/esm/parse/_lib/parsers/index.js
█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 3.93 % (43.054 KB)
```

So maybe just additional size in formkit from features as you noted? Surprised to see a node_modules directory *within* the formkit node_modules directory, i.e. `/node_modules/@formkit/vue/node_modules/@formkit/core/dist/index.mjs` but maybe that's something you guys did intentionally.

For the heck of it I tried beta.12 and beta.13 as well. Beta.12 is basically the exact same size as beta.11, beta.13 shows a small increase, but most of the increase is in beta.14 it seems. Here is the beta.13 top 10 for reference:

```
/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js
█████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 19.1 % (157.74 KB)
/node_modules/@formkit/core/dist/index.mjs
█████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 11.29 % (93.23 KB)
/node_modules/@formkit/vue/dist/index.mjs
████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 8.02 % (66.279 KB)
/node_modules/@formkit/inputs/dist/index.mjs
██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 5.98 % (49.364 KB)
/node_modules/date-fns/esm/parse/_lib/parsers/index.js
██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 5.21 % (43.054 KB)
/node_modules/vue3-datepicker/dist/vue3-datepicker.esm.js
██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 5.01 % (41.403 KB)
/node_modules/formkit-multistep/dist/formkit-multistep.es.js
██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 4.82 % (39.819 KB)
/node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js
█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 3.95 % (32.602 KB)
/node_modules/date-fns/esm/parse/index.js
█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 3.77 % (31.165 KB)
/node_modules/date-fns/esm/format/index.js
█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 3.2 % (26.42 KB)
```

**Comment by justin-schroeder** [comment]
ahh yes, the nested `node_modules` this happens (not formkit specific, but super annoying) when you get dependency version mismatches. Im guessing some of your formkit dependencies are mismatched versions. If the package.json looks right you can probably just delete your node modules and lock file re-install to clean it up.

One other thing to note, the sizes you are seeing there are definitely not the built sizes. Vue, for example, even when not gzipped is only 157kb when it includes all the comments and what not. The same is true for FormKit, we added a lot of additional comments to our source code between beta.11 and beta.14 since we how have an auto-generated API reference (https://formkit.com/api-reference) so those are also being included in your bundle breakdown there. However, hopefully when actually built for production many of those kb "melt" away as they are stripped out, and likely the overall distribution of kb would change too.

**Comment by totalhack** [comment]
Thanks I'll give that a shot. This is just what `rollup-plugin-analyzer` spits out as a plugin for vite. It definitely is including stuff that doesnt make it into the final dist files unfortunately.

**Comment by totalhack** [comment]
Confirmed that if I nuke node_modules and reinstall with beta.14 my output bundle sizes only end up about 1% bigger now. Thanks for your help.
