### ISSUE TITLE
OptionLoader gets triggered by every value change

### ISSUE THREAD

**Issue by pitcher-maarten** [formkit/formkit#571]
### Reproduction

https://formkit.com/inputs/autocomplete#option-loader

### Describe the bug

As you can also see in the docs (open network tab) the option loader is not only getting triggered during initial load but also on every value change.

**Reproduction:**
1. Go to the attached link
2. Open network tab
3. Click another movie

### Environment

• OS: Mac OS
• Browser Chrome
• Version Beta 14

**Comment by justin-schroeder** [comment]
The option loader gets passed 2 arguments — the lookup value (value of the input) and the second argument is the cached option if it already has one. The implementation is left to the user, but if you return the second argument (if it is not `false`) then you are just returning the memoized option.

This gives you the ultimate freedom to decide how to you want to implement your loader.

For example:

https://formkit.link/c5d42015afeee8899e47dadec748c553

Now when you select a result — the `options-loader` (search api) will run again as it is narrowing the results to your current search selection, but in the above example your `optionLoader` will only be called on initial load.

**Comment by pitcher-maarten** [comment]
Thanks for clarification, however we do not really have use cases (at this point) where we also need to get the entire single selection by api.

What you think about a global configuration option to enable the cachedOption as default? So we don't have to take care of the `if (cachedOption) return cachedOption` option every time.

**Comment by justin-schroeder** [comment]
Just don't provide an option-loader and you should be fine in that case.

**Comment by sashamilenkovic** [comment]
I've gone ahead and added more documentation to the use of the option loader for the dropdown family pro inputs. I'm going to close for this now, but please let us know if you have any further questions @pitcher-maarten
