### ISSUE TITLE
Not able to use multiple 'matches' rules

### ISSUE THREAD

**Issue by rikzwarthoff** [formkit/formkit#575]
### Reproduction

https://formkit.link/1f52454611d3047e653b34198c9e533e

### Describe the bug

My idea was to have different 'matches' rules for requirements of a password, also having a separate error message per rule. To give a more specific error message.

For example:
- ["matches", "/[A-Z]/"]: Must include one uppercase character
- ["matches", "/[a-z]/"]: Must include one lowercase character
- etc etc

However I can only use 'matches' once, as it is keyed by the name, so it uses the last one.  Think there should be a way to alias them, so you can attach specific error messages to them. 

Solution for now is custom rules.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by GustavoFenilli** [comment]
Yeh that is not something I would say is needed, as you can create custom rules for each case with a name, so you're aliasing those.

But would like to hear from @justin-schroeder.

**Comment by andrew-boyd** [comment]
also agree that multiple custom rules would be ideal here so that you can adjust the display of validation messages independently as requirements are met. Otherwise they'd still all need to share a single message and might as well be a single rule.
