### ISSUE TITLE
Improve missing pro package error message.

### ISSUE THREAD

**Issue by hyperupcall** [formkit/formkit#580]
### Reproduction

https://github.com/hyperupcall/repro-formkit-unknown-input-type

### Describe the bug

~~Using the [Dropdown basic example](https://formkit.com/inputs/dropdown#basic-example) results in console errors. I could not reproduce this on the Playground, so the repo link is to a [repository with a repo](https://github.com/hyperupcall/repro-formkit-unknown-input-type):~~

I now realize that Dropdown requires Pro... Maybe the error message can be improved?

### Environment

• OS: Linux
• Browser Brave
• Version 1.0.0-beta.15

**Comment by justin-schroeder** [comment]
Yes — I think it can 👍
