### ISSUE TITLE
The shouldSelect function in options.ts, used to compare options, doesn't differentiate between null and undefined.

### ISSUE THREAD

**Issue by js-modernary** [formkit/formkit#582]
### Reproduction

https://formkit.link/cdf6a0d8281905534b3d8aa7fa1175b1

### Describe the bug

I'd expect to be able to differentiate between an uninitialized (`undefined`) state and a state where the user has explicitly selected `null`. The attached example shows the simplest of my use cases, where the user themselves **must** make a selection and I cannot default to something without implying that the user made that choice themselves. Obviously this is being stored in the backend as a nullable boolean, so it makes sense for the frontend to be able to provide a control that uses `true`/`false`/`null` as its options' values.

### Environment

• OS: All
• Browser: All
• Version: 1.0.0-beta.15

**Comment by andrew-boyd** [comment]
Agree that this could be improved. For the time being you could use a plugin to cast `undefined` to whatever interim value you would deem appropriate so that you can use `null` as an actual value in your radio.

https://formkit.link/f4ca107dc4d4509e2e43012dafdfdb6f

You would then want to also prune out your interim value in your submit handler if you don't want it hitting your back-end.

**Comment by js-modernary** [comment]
I really appreciate your work on this! 

Unfortunately it looks like perhaps something in the build has prevented the fix from being completely applied. I'm still seeing the old version within `...\node_modules\@formkit\inputs\dist\index.mjs` (Same for the index.cjs file at that location). I'm seeing the new version within `...\node_modules\@formkit\vue\dist\formkit-vue.js`. 

I'm importing from @formkit/inputs for my custom component, so I end up with the old code. I confirmed in my browser that the old code runs when using my custom component but I saw FormKit native select controls using the new logic.

**Comment by js-modernary** [comment]
@sashamilenkovic I previously tried deleting my node_modules entirely and reinstalling. I did not remove my package-lock file, although I can try that now.

**Comment by sashamilenkovic** [comment]
@js-modernary Let me know how that goes.

**Comment by sashamilenkovic** [comment]
@js-modernary Sweet! No worries. Glad it's working now.
