### ISSUE TITLE
Genesis Tailwind theme - unexpected grey zone on disabled checkbox

### ISSUE THREAD

**Issue by LLCampos** [formkit/formkit#584]
### Reproduction

https://formkit.link/3323ad3081d7da1615610c0ae36e6b26

### Describe the bug

As seen in the Playground, if we're using the Genesis Tailwind theme and have a disabled checkbox, a unexpected grey bit will appear between the checkbox and the label.

This is due to the `formkit-disabled:bg-gray-200` property in [here](https://github.com/formkit/formkit/blob/master/packages/themes/src/tailwindcss/genesis/index.ts#L6).

Right now, I'm working around it with the following:

```js
import { generateClasses } from '@formkit/themes'
import genesis from '@formkit/themes/tailwindcss/genesis'

export default {
  config: {
    classes: generateClasses({
      ...genesis,
      'family:box': {
        ...genesis['family:box'],
        inner: 'formkit-disabled:bg-transparent',
      },
    }),
  },
}
```

### Environment

• OS: iOS Ventura 13.0.1
• Browser: Chrome 110

**Comment by andrew-boyd** [comment]
Thank you for the report @LLCampos, we'll address this in the next release.

**Comment by parsajabbari** [comment]
I noticed something similar happening when using the options prop to have multiple checkboxes. Interestingly, in this case, in addition to the gray bit, seems that the opacity effect for the disabled state isn't being applied at all for multi-checkbox inputs.

I see it happening in one of the official FormKit examples:

[Playground](https://formkit.com/playground?css-framework=tailwind&fkv=1.0.0-beta.15&fileTab=checkbox-objects.vue&files=jc%5B%26checkbox-objects.vue%27%7EeditQ%21%27%3CscripAsetup%3E_ref%3BcomputeY%29Z%22vue%223XsAzW+ref%7B%5B%5D%7D3XsAsumW+computed%7B%7B%7C%2831return+new+Intl.NumberFQmat%7B%22en-US%22%7DM.fQmat%7Bz.z.reduce%7B%7Bsum%3Bprice%7CNumber%7Bprice%7D+%2B+sum%3B0%7D%7D3%29%7D3%3C%2Fscript%3E33%3C%5E1%3CFQmKitMv-model%3DGzGMtype%3DGcheckboxGMlabel%3DGIndianEoodGM%3Aoptions%3DG%5B92RBhajjiqFrieYchickpea+batter+%E2%80%94+spicy.6%29%2C955RVada+Pav+%7BouAof+stock%7DqFrieYvegetarian+dumplings.61attrsJ%28+disabledJtrue+%29M1%29%2C922RParathaqFlatbreaYlayereYanYpanEriend.6%29%2C944RHalwaqPudding+made+withElour.6%29M%5DGMhelp%3DGSelecAyourEavQite+Indian+dishes.G31%2F%3E3%3C%2F%5E%27%7Esyntax%21%27html%27%60%2C%26fQmkit%23%2F*+In+thisEile%3BexpQAyourEinal+Xfig.3IAwill+automatically+be+injecteYinto+the%25Q+you.3ImpQtsZother%25iles+are+suppQted.+*%2F3_%24+%298%22_OIXs+%29ZG%3FiXsG3impQAO8%2Fdist%2FtLcss%2FO%2233expQAdefaulA%2831iXsJ%28M...OIXs31%29%2C31XfigJ%28MclassesJ%24%7BO%7D31%293%293D%2C%26tL%23impQAFQmKitTL8%2FtLcss%2233window.tL.XfigW+%2831pluginsJ%5BMFQmKitTL31%5D3%29D%5D1++3%5Cn6%22%2CM17J%228Z%22%3Fthemes9M1%28M11z7item-At+D%27%7Eremovable%21true%7Esilent%21true%60E+fG%5C%27J%3A+LailwindM311OgenesisQorR61label7W+%3DXconYd+ZErom+_3impQA%28+q61help7zvalue%23.Xfig.js%27%7EeditQ%21%27%24generateClasses%25+playgroundE%26%28%27name%21%27%3B%2C+%3F%40fQmkit%2F%5Etemplate%3E3%60%7Eadded%21true%29%7C%7DW%3E+%01%7C%60%5E%3F%3B%26%25%24%23zq_ZYXWRQOMLJGEDA987631_&imports=jc%28%27name%21%27ImportMap%27%7Eeditor%21%27%28*+1vue%5C%211https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fvue%403%2Fdist%2Fvue.esm-browser.min.js0*%29*%27%29*%5Cn0%5C%271+0%0110*_)
