### ISSUE TITLE
Initial value doesn't fire option loader

### ISSUE THREAD

**Issue by pitcher-maarten** [formkit/formkit#585]
### Reproduction

https://formkit.com/inputs/taglist#paint0_206889#option-loader

### Describe the bug

As you can see in the docs the initial value is not getting loaded by the option loader.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version beta 15

**Comment by sashamilenkovic** [comment]
@pitcher-maarten This has been fixed @next tag: https://formkit.link/c51b88e5916d0cdf751007d94f5bd90c. This will get merged into @latest soon.

**Comment by sashamilenkovic** [comment]
@pitcher-maarten This is now on the @latest tag.
