### ISSUE TITLE
Input with same name not synchronized in every input

### ISSUE THREAD

**Issue by mathsgod** [formkit/formkit#587]
### Reproduction

https://formkit.link/d1a3c4cf1a091639169e05697fef3258

### Describe the bug

I have two Input with same name, Input A and Input B. When input some value on Input A, Input B not update on every input keypress at Input A

https://formkit.link/d1a3c4cf1a091639169e05697fef3258

### Environment

• OS: Window
• Browser : Chrome
• Version 1.0.0-beta-15

**Comment by justin-schroeder** [comment]
having 2 inputs with the same name in the same namespace (the same group/list depth) is not supported in FormKit. However if you want to force the issue, you can directly v-model them to the same value. https://formkit.link/2b1df977bc67ae6d576497c34322a267
