### ISSUE TITLE
Multiple uses of a condition break the display of radio buttons

### ISSUE THREAD

**Issue by addidesign** [formkit/formkit#588]
### Reproduction

https://formkit.link/2e71f739b570c5e5f32ec2a59abdcb0d

### Describe the bug

I have come across a strange bug, which appears when I use the same conditional multiple times when there's a radio input present. 

In the example, you can see that if you select 'test 1' in the dropdown the radio buttons do not render.

If you uncomment out line 31 it all works - it's worth noting this is nothing to do with the comment, if you remove line 31 all together the issue still occurs. I have just left it there to demonstrate when it is present it seems to work.

### Environment

• OS: OSX
• Browser chrome

**Comment by justin-schroeder** [comment]
I believe in this case you just need to add some keys to those conditional inputs:

https://formkit.link/9eab1686c0c4f2d89199a550ff75cb64

**Comment by addidesign** [comment]
Thanks for this!

Just so I'm clear - do you have anywhere in the docs with info about the usage of `id` , `name` and `key` as I'm a bit unsure of the purpose of each of them? We've been using `name` for all other conditionals, which still works as expected. Is the `key` only required in these situations where conditions exist in repeaters?

**Comment by justin-schroeder** [comment]
The props table which includes `id` and `name` are included on every input’s documentation page:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/1950463/219420901-c998d96b-25bb-4f62-b02a-b74ecb648434.png">

The `key` thing is not related to FormKit, this is actually a Vue primitive, but you can read more about it here: https://vuejs.org/api/built-in-special-attributes.html#key

We'd like to add better root node support for the inputs which should make the key necessary in fewer circumstances, but for now it is often required when conditionally swapping between two structures (see #528).

Good luck! 👍

**Comment by AbdallahAlhaddad** [comment]
Hello @justin-schroeder 
I've faced a similar problem and fixed it by adding keys, thanks.
Would it be nice to let formkit generate the keys automatically?

**Reproduction:**
https://formkit.link/0c24f3580753ffc9f29dd6ae60d48dc2

**Comment by justin-schroeder** [comment]
Yes, that would be nice, we have an issue open to track that. Unfortunately it requires some changes to how schema is parsed. You can track: #407

**Comment by AbdallahAlhaddad** [comment]
Ok, thanks @justin-schroeder
