### ISSUE TITLE
taglist : it is possible to remove tag with property disabled: true

### ISSUE THREAD

**Issue by aousadou** [formkit/formkit#590]
### Reproduction

https://formkit.link/ed7ac04d463a7de37e9193983bfebe6a

### Describe the bug

It is possible to remove tag when disabled: true property setted. It must be not possible to remove tag when option disabled = true

### Environment

- Linux
- Chromium 110.0.5481.104 and Firefox 110.0

**Comment by sashamilenkovic** [comment]
@aousadou This has been fixed at the @next and @latest tags. Make sure to give the playground a hard reload. I'll close this for now but let me know if you have any other issues.

**Comment by aousadou** [comment]
@sashamilenkovic it seems fixed on latest but not on next tag

**Comment by sashamilenkovic** [comment]
@aousadou Hmm, it seems fixed for me on both. Maybe try hard reloading again or try in a different browser. It can be quite sticky at times.

**Comment by aousadou** [comment]
@sashamilenkovic After navigator restart it works. How i can install @next or @latest tag with pnpm ?

**Comment by aousadou** [comment]
@sashamilenkovic fixed by pnpm install @formkit/pro@1.0.0-alpha.67
