### ISSUE TITLE
Cannot change the element of addButton section on a repeater input

### ISSUE THREAD

**Issue by agenordebriat** [formkit/formkit#594]
### Reproduction

https://formkit.link/9b1586934b8520e3a8e927e721fdbc41

### Describe the bug

The element holding the addButton section on the repeater input cannot be changed.
I had a discussion with @GustavoFenilli on Discord more than a week ago about it, and he thought that maybe this section isn't actually "sectioned".

You can actually notice that the sections for the input don't include the addButton. Everything else works fine.

As you can see in the reproduction, you can update the text.
Locally I did replace the insert and remove controls with custom button components, but the addButton wouldn't work.

If the bug is fixed, I'd expect the addButton section to behave exactly like the other sections.

### Environment

• Version: beta-15 or beta-16, same issue

**Comment by GustavoFenilli** [comment]
This is fixed at @next https://formkit.link/e1e12bdaf53fb16b6b1bfbc5dc720f4b

**Comment by GustavoFenilli** [comment]
Nvm not the same problem that was fixed! haha

**Comment by GustavoFenilli** [comment]
As a workaround you can use `<template>` with `section-schema` https://formkit.link/156cb832a7d1d9dc6e9ce52f0b95cffb

**Comment by agenordebriat** [comment]
> As a workaround you can use `<template>` with `section-schema` https://formkit.link/156cb832a7d1d9dc6e9ce52f0b95cffb

Any pointer on how to do this on a schema?

**Comment by justin-schroeder** [comment]
@agenordebriat Here’s an example using schema: https://formkit.link/86584728067750c845611ced96d658ea

**Comment by sashamilenkovic** [comment]
This has been fixed at 0.112.6.
