### ISSUE TITLE
Drag and drop doesn't work when a taglist input is present

### ISSUE THREAD

**Issue by Pondake** [formkit/formkit#598]
### Reproduction

https://formkit.com/playground?css-framework=genesis&fkv=1.0.0-beta.15&fileTab=taglist-base.vue&files=jc%5B%28%27name%21%27taglist-base.vue%27%7EeditX%21%27%3Cscript+setup8const+cQBrands%3D%5B%28G%3A2Audi0audi*BMW0bmw*Citroen0citroen*Dacia0Ycia*Fiat0fiat*FXd0fXd*FerrQi0ferrQi*HonY0honY*HyunYi0hyunYi*JaguQ0jaguQ*Jeep0jeep*Kia0kia*Land+Rover0land+rover*MazY0mazY*Mercedes0mercedes*Mini0mini*Mitsubishi0mitsubishi*Nissan0nissan*Opel0opel*Peugeot0peugeot*PXsche0pXsche*Renault0renault*Saab0saab*SkoY0skoY*SubQu0subQu*Suzuki0suzuki*TZ0tZ*Volkswagen0volkswagen*Volvo0volvo2%29%5D57script85%3Ctemplate836qfXmU%23default4%28+I+%29U%3Aactions4false253%3E16qfileUG4DocumentsUaccept4.pdfEdocEdocxExmlEmdEcsvUhelp4Select+as+many+documents+as+you+would+like.Umultiple4true253%2F%3E163qtaglistU3name4cQ_b9G4SeQch+fX+your+favXite+cQ+b9%3Aoptions4cQB9%3AI4%5B%22honY%22%2C+%22tZ%22%5DU%2F%3E1%3Cpre+wrap%3E%28%28+I+%29%297pre837FXmKit87template8%27%7Eadded%21true%29%5D*2%29%2C%28G%3A202%2CI%3AU5332%5C%273++4%3D25%5Cn6%3CFXmKit17%3C%2F8%3E59randsU3E%2C.GlabelIvalueQarU21XorYdaZoyotaqtype4%01qZYXUQIGE9876543210*_&imports=jc%28%27name%21%27ImportMap%27%7Eeditor%21%27%28*+1vue%5C%211https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fvue%403%2Fdist%2Fvue.esm-browser.min.js0*%29*%27%29*%5Cn0%5C%271+0%0110*_

### Describe the bug

Drag and drop images/files doesn't work when you also have a taglist input inside the form. 

Only drag and drop: 
https://formkit.com/playground?css-framework=genesis&fkv=1.0.0-beta.15&fileTab=file.vue&files=jc%5B%28%27name%21%27file.vue%27%7E1%21%27%3C17%25target%25%3C%2F17%27%7Eeditor%21%270%3CFormKit*type4file9label4D69accept4.pdf88x3xml3md3csv9help4Select5many+d65you+would+like.9multiple4true-20%2F7%27%7Esyntax%21%27%27%7Eadded%21true%29%5D*200-%5C%270++1template2%5Cn3%2C.4%3D-5+as+6ocuments7%3E283doc9-*%019876543210-*_&imports=jc%28%27name%21%27ImportMap%27%7Eeditor%21%27%28*+1vue%5C%211https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fvue%403%2Fdist%2Fvue.esm-browser.min.js0*%29*%27%29*%5Cn0%5C%271+0%0110*_

### Environment

• OS: Windows 11
• Browser chrome
• Version 110.0.5481.178

**Comment by sashamilenkovic** [comment]
@Pondake Thanks for the filing the issue. I'll be sure to take a look at this.

**Comment by sashamilenkovic** [comment]
@Pondake Can you give your a playground example a hard reload and see if it's working for you now?

**Comment by Pondake** [comment]
Seems to work 👍 @sashamilenkovic Thanks for the fast fix.

**Comment by sashamilenkovic** [comment]
@Pondake Great! This fix has been published to both the @latest and the @next tag of @formkit/pro

**Comment by sashamilenkovic** [comment]
@Pondake I'm going to close this for now, but let me know if you have any issues getting that working locally.
