### ISSUE TITLE
Data binding on $formkit schema is not reactive 

### ISSUE THREAD

**Issue by qstarx** [formkit/formkit#599]
### Reproduction

https://formkit.link/87a4e9feebd7ebb6888dc13666506de0

### Describe the bug

Using FormKitSchema `<FormKitSchema :schema="schema" :data="data"/>`I would expect to have data binding using the key "bind" on the schema.
```javascript
const data = reactive({
  sel2:{
    value:'ship'
  }
})

const schema = [
  {
    $formkit: 'select',
    bind: '$sel2',
    options: ["plane","ship"]
  }
]
```
In my example the reactivity for the `$el `definition works, whereas using the `$formkit` definition the binding fails.
Using `$formkit` the initial value of the reactive `data` variable is read, but it's not updated.
Neither there is a two way binding. For two way binding I would expect the behaviour I get if I change the code to
```javascript
 sel:{
    value:'bike',
    onChange: (el) => {
      data.sel.value = el.target.value
    }
 } 
```
Then `data` is also updated when the select option changes

### Environment

• OS: ubuntu linux
• Browser: Firefox
• Version: 110

**Comment by mathsgod** [comment]
Use "modelValue" to do two way binding in schema
```js
 {
    $formkit: 'select',
    modelValue: '$sel2.value',
    options: ["plane","ship"]
  },
```
https://formkit.link/d5c793273bb851caf2c92369db5cae0e

**Comment by jefffairson** [comment]
Hello there,
Quick question about that, there is probably something I miss about the reactivity.
In this example :
[https://formkit.link/24524a4df5793da613401ac8e53f9a31](https://formkit.link/24524a4df5793da613401ac8e53f9a31)

If I force the ```questionanswer``` value to ```oui```, the conditional is working and displaying the other field, but if I set it up as a blank value and click on 'oui' nothing happens as if the reactivity is totally lost.
The data are not updated as well.

The question is simple, what did I miss ?

PS : thank for your great work, this library is saving my life ! any news about the pro version yet ?
