### ISSUE TITLE
Suggestion: Wrapper classes for errors and messages

### ISSUE THREAD

**Issue by antemarkic** [formkit/formkit#60]
Hi, I have a suggestion regarding the styling of fields -> to add additional classes to _.formkit-outer_ if there's a validation error or some other message displayed. Something like ".has-messages.has-messages--error".

This is currently not a case, but it would make it easier for developers to additionally point out which forms are invalid by outlining inputs or some other css property...

![image](https://user-images.githubusercontent.com/76186792/152679767-eb118473-b4b9-4a1d-842e-55c2c90b69d6.png)

**Comment by justin-schroeder** [comment]
@antemarkic Thanks for the suggestion. We did this in vue formulate by adding a data attribute `data-is-valid`, and `data-has-error` this is nice because it leaves the class system free/clear for people who want to write their own class solutions. We could pretty easily re-create that same tooling here in FormKit.

Let’s add it to the roadmap.

**Comment by justin-schroeder** [comment]
@antemarkic this is release-ready and will be published with `1.0.0-beta.3`. Here's an example of it running on beta.3:

https://formkit.link/cb85162e120c9de18e0298dbd8ca849e

Basic rules:

## `data-complete`


True when these conditions are met:

**Either:**
- The input has validation rules
- The validation rules are all passing
- There are no errors on the input
**Or:**
- The input has no validation rules
- The input has no errors
- The input is dirty and has a value

This is not intended to be used on forms/groups/lists but instead on individual inputs. Imagine placing a green checkbox next to each input when the user filled it out correctly — thats what these are for.

## `data-invalid`

Added when the input has failing validation messages and those messages are being displayed `!context.state.valid && context.state.validationVisible`

## `data-errors`

Added whenever explicitly set errors are on the input, either via a parent (like `setErrors()` from the form), or directly via the `:errors` prop.

**Comment by aegorx** [comment]
Hi, @justin-schroeder.
While adding built-in attributes is a nice feature, If message uses the transition tag, the style changes ugly, is there any way to add a custom class?

I'm sorry, that's what I wanted to say yesterday. Now that I've handled the transition hook manually, it would be nice to have a built-in API

**Comment by justin-schroeder** [comment]
You _can_ modify this behavior on your own — although I'm still not exactly sure what behavior you're looking to modify. Perhaps you could make a playground at https://formkit.com/playground with an example of the transition you are attempting and what you are wanting to achieve and then I can assist from there. Thanks @aegorx!
