### ISSUE TITLE
No more coffee

### ISSUE THREAD

**Issue by sashamilenkovic** [formkit/formkit#600]
### Reproduction

Go to the office, there is no coffee

### Describe the bug

Coffee, none.

### Environment

FormKit HQ

**Comment by luan-nk-nguyen** [comment]
Is this a joke, @sashamilenkovic? 😂. Catastrophic mistake on my part. Will get this resolved asap.

**Comment by andrew-boyd** [comment]
![IMG_0228](https://user-images.githubusercontent.com/2946356/222826393-72962883-8e71-4d19-af5b-07b524d0fde2.jpeg)

This has been patched, closing. Please feel free to re-open in the future if the issue comes back.
