### ISSUE TITLE
Changing schema with reactive object breaks form

### ISSUE THREAD

**Issue by qstarx** [formkit/formkit#608]
### Reproduction

https://formkit.link/82a863434fc06d4ba8f935ca26b878e4

### Describe the bug

Setting up a form with a schema from a reactive object using `ref()`, the form is updating nicely as long the input types stay the same (e.g. types: select, radio). But if the input type changes from "radio" to "select" or vice versa the form components get broken (wrong markup). 

I would assume that as soon as the schema changes,  the component is rendered completely, so that it is possible to change the entire form and replace every input to whatever I want.

### Environment

• OS: Linux, Ubuntu
• Browser Firefox
• Version 110

**Comment by justin-schroeder** [comment]
Well there’s a few issues I see here:

1. You really shouldn't update the schema. Think of schema like the `<template>` tag of a component. You can bake a lot of logic into each template, but fundamentally you cannot change the actual `<template>` itself. FormKit does allow this, but its not ideal for performance. Instead checkout the [expressions section of the schema docs](https://formkit.com/essentials/schema#expressions) to learn how to bake that logic into the structure itself.
2. Conditionals and loops need `key`s. I've added them to your example — in the future we hope to remove this. See #528 .
3. You've got duplicate `name`s in your schema. This isn't strictly prohibited, but does lead to unexpected bindings.

Here’s a working example: https://formkit.link/1676bb5f169f4065a2c958acce96458a
