### ISSUE TITLE
Autocomplete open-on-click isn't working properly 

### ISSUE THREAD

**Issue by mweghorst** [formkit/formkit#609]
### Reproduction

https://formkit.link/4256ee63039a445616bad1ca6579a150

### Describe the bug

I'm trying to extend FormKits autocomplete to a custom 'product' input. We have a product selector that we use throughout our application. We want to be able to use <FormKit type="product" /> and not needing to define :options and :optionsLoader each time. This is almost working, except that the autocomplete options immediately blur after the first click/focus. When I click on the label or when I click on the input twice it's working fine. Extending the dropdown input is also working fine.

Edit: closeOnSelect also isn't working properly, probably related

### Environment

- OS: macOS
- Browser: Google Chrome 110.0.5481.177
- FormKit: 1.0.0-beta.16-18186fe
- FormKit Pro: 1.0.0-alpha.96-cba4df4

**Comment by sashamilenkovic** [comment]
@mweghorst Open-on-click should be working properly now. Can you give your playground link a hard reload and confirm that it's working for you?

**Comment by mweghorst** [comment]
No it's not yet working properly: https://www.loom.com/share/6db2b6a9c82d431b82d9591b1c24993b

**Comment by mweghorst** [comment]
Yes, this seems to be working! I do have 2 other issues, although I'm not sure they're related. I have updated my Playground and recorded a video. What happens is that on select the optionLoader method gets called without hitting its cache. When clearing the selection (I've set selectionAppearance option) two calls to the options are made: one with the last known page, and one with page=1.

https://formkit.link/eadb662e5440e58430596c6529c367a1
https://www.loom.com/share/6934c724b89e43208bf30ac01015e775

I can also create a new ticket if you want.

**Comment by sashamilenkovic** [comment]
@mweghorst Hmmm, yeah. That seems to be related to the open-on-click prop as well. I'll take a look at that. No need to create a new ticket.

**Comment by sashamilenkovic** [comment]
@mweghorst Okay, on the @next tag, if you hard reload (you should be pulling down 1.0.0-alpha.102-6029341), the option loader will correctly use the cached option. Also, when you clear the selection, it shouldn't make a request to the last known page, only page=1.

**Comment by mweghorst** [comment]
Yes, working perfectly now! Thanks Sasha
