### ISSUE TITLE
Schema class strings fail if using $reset as the first item due to schema parser.

### ISSUE THREAD

**Issue by andrew-boyd** [formkit/formkit#61]
When supplying custom classes and using the `$reset` token, the schema attempts to parse the string resulting in the default classes persisting and the custom classes not being applied. 

We probably need a different token for `$reset` unless it's acceptable to prevent `-class` schema items from being dynamically processed.

FormKit Vue Playground link:
https://formkit.link/5e27eb29b8894ccfb4431fe63238b92c

**Update — CURRENT SOLUTION:**

Prefix your `$reset` calls in schema [with __raw__ per the docs](https://formkit-com-1gkwrk32m-formkit.vercel.app/advanced/schema#raw-values).
https://formkit.link/0f8d83e4f7b51791eef9aa544383fa81

**Comment by andrew-boyd** [comment]
Honestly, 3 seems like the most sensible thing, and now's the time to do it. some options:

`%reset`
`_reset`
`!reset`
`@reset` <-- this one feels sass / tailwind like.

**Comment by justin-schroeder** [comment]
One small sticking point with those is only `_reset` is a valid quoted object key in JS:

```js
{
  $reset: true, // ✅ valid
  _reset: true,  // ✅ valid
  !reset: true,  // 🚫 not valid
  %reset: true,  // 🚫 not valid
  @reset: true  // 🚫 not valid
}
```

Of course you could quote any of the above invalid ones, but it takes something away from the fluidity and legibility when you have to do that.

**Comment by justin-schroeder** [comment]
Wondering if it might be best to just call `$reset` a reserved word.

**Comment by andrew-boyd** [comment]
Reserving `$reset` feels reasonable in light of the above. I’m in favor.

**Comment by luan-nk-nguyen** [comment]
As long as it's consistent between the Vue component and the schema, I think this will be ok. `$reset` seems like it could be a relatively common collision within schema — I could see people using it for functions or other things — so we might consider ways to make it clear that it is a reserved word.

**Comment by justin-schroeder** [comment]
Ok, this is implemented for all `-class` and `fooClass` attributes. Caveat, it does not work for the `classes` prop which will require the prefix: `__raw__classes`
