### ISSUE TITLE
Floating label is set to top when using validation other than required

### ISSUE THREAD

**Issue by enzo-mandine** [formkit/formkit#611]
### Reproduction

https://formkit.link/0df7be236efff139ba8bbfa9eca29349

### Describe the bug

When using a rule with floating label, if the rule does not start with "required" the label is directly set to top.
Adding + in front of any rule restore the desired behavior.

I fixed it with the following : setAttribute('data-complete', 'false'), but i guess it's not the best practice.

### Environment

• OS: Linux Mint
• Browser Firefox
• Version Mint-001 - 1.0

**Comment by GustavoFenilli** [comment]
It looks like a problem with `data-complete="true"` being set for those rules as the rules is being computed, and it might have something to do with the css of floating it or not.

**Comment by andrew-boyd** [comment]
This will be addressed in beta.16 (`0.16.0`) — it's styling that's not needed since completed elements also have values, we can rely on only `data-has-value`.
