### ISSUE TITLE
Disable form submit on enter in text input

### ISSUE THREAD

**Issue by MortenHe** [formkit/formkit#617]
### Reproduction

https://formkit.link/6ae80466414a8f2f30c880d601869a78

### Describe the bug

Is it possible to disable a form from being submitted when ENTER is hit inside a text input?

In the example I have 3 inputs. There first two inputs will submit the form on enter. The 3rd input has @keypress.enter.prevent="" to disable form submission on enter.

I could add this for every input in my form (~12 inputs). But I would also be glad if there would be a more elegant solution.

(Some inputs in my form are filled by scanning a code. The hand scanner sends the value and ENTER, so I want to stop the form from submitting)

### Environment

• OS: Win
• Browser Chrome current version
• FormKit Beta 15

**Comment by mathsgod** [comment]
You can add ```actions="false"``` attributes at ```<FormKit type="form">```
And add ```<FormKit type="button" label="Submit" />``` manually at form below


https://formkit.link/61c449ead89f3edb32ff069ae0f0d98d

**Comment by MortenHe** [comment]
Thanks for your working exmaple.

Do you have an idea what to todo to prevent a button inside the form from being clicked, when hitting enter in a text input?

I have a button that sets the text of one input. Button the click function gets also called, when I hit enter in a text input. That's what I would like to prevent.

https://formkit.com/playground?fkv=1.0.0-beta.15&fileTab=Playground.vue&css-framework=genesis&files=jc%5B%28%27name%21%27Playground.vue%27%7EeditQ%21%27%3Cscrip9jup7impQ9RWT+from+%22%40fQmkit%2FcQe%22%3B00cons9jVC+%3D+%7B%7D+%3D%3E+%280*zertEwG0*WEfirstG%3F.inputEhelloG%3B0%2900Ascript70%3CO8X9MfQmU%3Aactions6fzse_id6myFQm_%40sJ6handleSJ40*8%23default6Rstate%3A+RL%2C+loadingT%2C+vCT_-*id6first4DYLation6required4D*514%2F%3E+DY%3CH+%40click%3D%22jVC%22%3EwAH-524%2F-534D8%2F7Y8X9%3Adisabled%3D%22%27%3AL%22D8MHUZSJU%2F78ABt7AO0%3Cstyle+scoped7Astyle7%27%7Eadded%21true%29%5D8+-7Y*XtDYMtext4D*0%5Cn4%5C%275*ZB9Inpu96%3D47%3E08*+9t+A%3C%2FBFQmKiCzueD0YE%7B%22G%22%7DHbuttonJubmitLvzidMtype6Otemplate7QorR%28+T+%29U4+WgetNodeX%3CBY**Zlabel6_408jsetwse9vCzal%01zwj_ZYXWUTRQOMLJHGEDCBA9876540-*_&imports=jc%28%27name%21%27ImportMap%27%7Eeditor%21%27%28*+1vue%5C%211https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fvue%403%2Fdist%2Fvue.esm-browser.min.js0*%29*%27%29*%5Cn0%5C%271+0%0110*_

**Comment by mathsgod** [comment]
Because the default type of button is `submit` if you haven't set. You can add attribute `type="button"` in button tag to prevent  keyboard `enter` event.

https://formkit.link/beb1b78eafd9440a4f1334d686c27ce0

**Comment by MortenHe** [comment]
Perfect, that was the missing piece.

Thank you very much and have a nice day!
