### ISSUE TITLE
After selecting an option on autocomplete, the down caret does not trigger a search

### ISSUE THREAD

**Issue by charliepy** [formkit/formkit#620]
### Reproduction

https://formkit.link/2f906c8411c3128fa5c0773d11ac4df7

### Describe the bug

If I select Shawshank Redemption and then hit the down caret again, nothing happens. formkit-outer class shows data-expanded="true" but there are no results. Only when I unfocus and then reclick the down caret do results show. 

### Environment

• OS: Windows 10
• Browser: Brave 
Version 1.49.120 Chromium: 111.0.5563.64 (Official Build) (64-bit)
• Version: latest

**Comment by sashamilenkovic** [comment]
@charliepy Hey! If you hard reload your example so that pro is pulling down version [0.111.2](https://www.npmjs.com/package/@formkit/pro/v/0.111.2), is this issue resolved for you now?

**Comment by charliepy** [comment]
@sashamilenkovic yes it is very responsive now. Thanks!
