### ISSUE TITLE
Manually passing reset values inside the reset function updates not the initial value of the form fields

### ISSUE THREAD

**Issue by dominikklein** [formkit/formkit#621]
### Reproduction

https://formkit.link/1d28ea92f1926ca1a2e42d2d6bc4b6d8

### Describe the bug

Currently, the initial values of the form fields are not changed, when I use the `reset` function with a new set of data.

I would expect that the initial values from the fields are changed after a reset to these "new" initial values.

The use case is that I'm in an edit form and an other user changed the entity in the meanwhile and I receive a subscription for the new data. In this case, I would reset the form with the newly received data (and this should also change the "initial" data from the fields).

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by anjil-fastlane** [comment]
@dominikklein @justin-schroeder  I am facing the similar situation with the reset function. Supplied the formid and the formfield names but all I can she a warning in the console as "W152".

**Comment by oawebdev** [comment]
I have a similar issue, but in my case it's slitly different.
I edit the form value, submit it to server, refresh data, set new value to fields, and after click reset I receive the initial date from first load, not from new fetch.

**Comment by oawebdev** [comment]
> Can you provide a reproduction @oawebdev?

Hello!
https://stackblitz.com/edit/nuxt-starter-tqekb8?file=app.vue

I have found that in my case fields didn't update value from prop, so reset works well. 
How can I update values for the fields after I refresh data?
