### ISSUE TITLE
Autocomplete is not re-enabled when an options change dynamically from empty to populated.

### ISSUE THREAD

**Issue by justin-schroeder** [formkit/formkit#622]
### Reproduction

https://formkit.link/d22cf54449eca22d53a1ee9377ca7301

### Describe the bug

In the above example a `ref` with an empty array of options is bound to the options prop. When that ref is updated with options the input is still disabled.

### Environment

• OS: MacOS
• Browser Brave
• Version 1.49.120

**Comment by sashamilenkovic** [comment]
Fixed now also on @latest tag.
