### ISSUE TITLE
Icon not working

### ISSUE THREAD

**Issue by muhammedfayaz** [formkit/formkit#626]
### Reproduction

https://formkit.com/essentials/icons

### Describe the bug

prefix icon is not working in file type

able to remove no file chosen image

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by muhammedfayaz** [comment]
![image](https://user-images.githubusercontent.com/105773169/226869938-359953c7-28a4-44de-9005-6343f07db29b.png)

**Comment by justin-schroeder** [comment]
Please provide a playground reproduction of the specific issue. they seem to be working to me, but I'm not sure what your exact issue is: https://formkit.link/6050c83b2bfe2459777ed404ddde7055
