### ISSUE TITLE
Transferlist, repeater and formkit form bug

### ISSUE THREAD

**Issue by kohlzz** [formkit/formkit#628]
### Reproduction

https://formkit.link/8fd36dd99e2fc329f81fadab7eb762c7

### Describe the bug

The items won't transfer to the right side, nor do the buttons work.  If I remove the repeater, it works again, or if I remove the type form and leave the transfer list and repeater then it also works.

If I did overlook something, then I apologize.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by luan-nk-nguyen** [comment]
Thanks for your example, @kohlzz! It works for me. You may need to clear cache within the playground? 

https://user-images.githubusercontent.com/11545316/227264005-81134589-f88a-432a-b467-7ef4199569ce.mov

**Comment by kohlzz** [comment]
Hi @luan-nk-nguyen, I did clear my cache but there is no difference. On a sidenote, I use this on my local Nuxt 3 project. Did a cleanup too but no effect.

**Comment by kohlzz** [comment]
https://user-images.githubusercontent.com/20999775/227272461-402c44b7-3a82-4f86-9ace-0cb59b7a8168.mp4

This i tried on IE but same results

**Comment by sashamilenkovic** [comment]
@kohlzz If you switch to the next tag in the playground to where you are pulling down [0.111.3-2e9ec91](https://www.npmjs.com/package/@formkit/pro/v/0.111.3-2e9ec91) on @formkit/pro are you seeing the transfer list work now?

**Comment by kohlzz** [comment]
I can confirm that this is working for me as of now. Tested now on local project and this also works.

**Comment by sashamilenkovic** [comment]
@kohlzz This fix has been published to the latest tag as well. I'll close this for now, but let me know if there are any further issues and we can reopen this.
