### ISSUE TITLE
Using `:model-value` and `@update:model-value` directly does not trigger updates

### ISSUE THREAD

**Issue by NielsJanssen** [formkit/formkit#629]
### Reproduction

https://formkit.link/fe2ea13d7e65ab156b0a9f975a7421e4

### Describe the bug

When using using `:model-value` and `@update:model-value` directly instead of `v-model` updates are not triggered on the field. Using `:modelValue` instead does cause the updates to trigger. I would expect `:model-value` to work.

I suspect this check is the cause: https://github.com/formkit/formkit/blob/master/packages/vue/src/composables/useInput.ts#L169

### Environment

• OS: MacOS 13.1
• Browser: Chrome 110, Safari 16.2 & Firefox 110
• Version: 0.16.4

**Comment by dominikklein** [comment]
Saw the same today after we updated to the current version: https://formkit.link/0b998ab757851519d7749b6333da9ec9

**Comment by justin-schroeder** [comment]
This was fixed in beta 17 but wasn’t ever closed.
