### ISSUE TITLE
Multi-step Form Support/Docs

### ISSUE THREAD

**Issue by totalhack** [formkit/formkit#63]
The readme lists multi-step forms as supported, but I've read through the docs and can't find an example of how this would be done. In particular I'm interested in using the schema generator to go from JSON to a multi-step form. Apologies if I've just missed it.

Just to clarify, when I say multi-step form I mean the ability to have one or more inputs per step, some sort of "next" or "submit" button that goes to the next step (next set of inputs become visible, previous ones hidden) until you get to a final step and do a full form submission. Some nice-to-haves would be the ability to go back to a previous step, as well as the ability to do partial submissions to the backend between steps.

I suppose one hacky way to do this would be with the conditional visibility feature, but hoping there is something better I missed, like just grouping the inputs in a list or something.

Thanks for putting this library together, been looking forward to seeing what the Vue 3 version looks like.

**Comment by andrew-boyd** [comment]
@totalhack It's on our list to do a guide for this exact topic and have it on the site. I'll keep in mind your request to see a schema-only version. It should be doable since the schema lets you use arbitrary components as well, so you'd register something like a `form-step` component that has a default slot for the content and then pass in the `children` with the schema.

FormKit will be compatible with multistep form setups, but it will require some configuration and custom components within your own project at this time. We may tackle some pre-baked multistep form solutions as part of the pro package as well.

**Comment by totalhack** [comment]
Hey @andrew-boyd, just curious if this has made it onto the roadmap with an ETA for either documentation or some built-in support. I'm about to run into needing this to use FormKit...

**Comment by andrew-boyd** [comment]
The guide for creating a multi-step form has been published! https://formkit.com/guides/build-a-multi-step-form

**Comment by totalhack** [comment]
Thanks @andrew-boyd, that's a helpful starting point! Based on the example code I assume there can is no easy way to do this same thing from a JSON schema?

**Comment by oivvio** [comment]
+1 on what @totalhack said. This is a great starting point but we want that sweet sweet JSON schema :)

**Comment by andrew-boyd** [comment]
@totalhack @oivvio Here's my take on a schema-version: https://formkit.link/7b74e4469f5c6eb1820cea4423a3ccbe

**Comment by totalhack** [comment]
Thanks @andrew-boyd, appreciate the quick turnaround on that. This a really helpful working example. 

One last item I wanted to address from my original question is around taking actions between steps. Specifically, is it possible to do either of the following:

1. Submit partial results to the backend between steps -- would just require accessing the current state of the overall form which should be simple I think.
2. Alter the behavior between steps, such as deciding to redirect a user or skip steps. Skipping steps seems trivial though you'd have to remove a step from requiring validation too. Redirecting a user based on some previous answers also seems trivial.

I think the answer to both of those is yes, you'd just handle it in the onClick events of the step navigation, but wanted to get your thoughts and see if you could think of any gotchas.

**Comment by andrew-boyd** [comment]
Yes to both, I believe. Probably several ways to skin that cat but nothing comes to mind that would prevent you from achieving both of those goals.

**Comment by totalhack** [comment]
Hey @andrew-boyd, I'm trying to modify your JSON-based example to not allow moving to the next step if the current step fails validation (rather than just showing validation errors but letting users move on, which would be a bit unusual). 

I see the `useSteps` plugin has a `watch` method that triggers validation apparently by calling `n.store.set` on all underlying nodes. So I think instead of that I just need to call `getNode(oldStep)` and detect if validation fails when calling `set` on that step, and if so set `activeStep=oldStep`...but how can you detect whether validation failed when setting a node value with formkit core? It doesn't appear that `someNode.store.set` returns whether there were validation errors.

Thanks for your help.

**Comment by andrew-boyd** [comment]
Yes, the context object is the correct place to be looking for those values. https://formkit.com/advanced/context. 👍 

> FormKit inputs use a reactive object to expose data to template slots, rules, and the [schema](https://formkit.com/advanced/schema) that defines each input. This is called the `context` object and is found in the each input's [core node object](https://formkit.com/advanced/core#node) at `node.context`.

Glad you were able to figure it out!

**Comment by totalhack** [comment]
This may be getting a little off-topic but I'm trying to implement the redirect functionality I mentioned above and running into some surprising behavior when trying to use functions in the schema. I think I've narrowed it down to being a problem with passing a url as a string argument to a function in `onClick`. I replaced my attempt at a redirect with a simple log function to show an example of the issue...

In App.vue's `data`:

```javascript
const data = reactive({
  log: target => () => {
    console.log('target:', target)
  },
}
```

In the schema:

```javascript
    //  added to the navigation buttons to test 
    {
      $formkit: 'button',
      onClick: '$log("https://www.google.com")',
      children: 'Log'
    }
```

In the console this comes through as `target: NaN` when clicked. If I switch that URL to an integer or a non-url string it prints it correctly. If I removed the slashes it prints the string. If you want me to open a separate issue for this I can.

**Comment by totalhack** [comment]
Hey @andrew-boyd, another question more on topic here...

I am trying to add the ability to skip steps or have hidden steps that may or may not be in the path of the form flow based on some logic (perhaps based on answers to earlier questions, etc.). The issue is it seems the submit action always tries to validate all of the steps, whether that step was shown or not. Is there some way to disable this behavior, or maybe just something I'm missing?

**Comment by totalhack** [comment]
I'm going to separate the questions above into their own issues to better organize this.
