### ISSUE TITLE
Validation in Formkit-Schema

### ISSUE THREAD

**Issue by joshbrooks** [formkit/formkit#633]
### Reproduction

schema

### Describe the bug

Two questions: 
 1. Is it possible to **have a validator which acts on multiple fields**?
 2. If so, is it possible to **include that in a FormKit schema**?

I have read the docs but cannot work out how to add a validation which depends on a different field in a schema. Our use case is for meetings where the **total** partisipant number must be less than the **sum** of different partisipant types. What I'm trying to do is assigning a function as a validator

## First Attempt

`it.validation = 'max:$getMax(node)'`

However, it's treated as a string - and I get the validation message`Numeru Total Partisipantes (mane): must be less than or equal to $getMax(node).`

## Second Attempt

Adding a validation rule 
```
const myRule: FormKitValidationRule = function (
  { value }
) {
  debugger
  return true
}
```

and then applying this as `validationRules` on the items
```
(partisipants.formkitschema[0]?.children as FormKitSchemaFormKit[]).forEach((it) => { it.validationRules = { myRule } })
```

The debugger is never hit

Is this supported with FormKit schema - or, should I be thinking about creating a separate component with the logic and a validation message?

### Environment

Vue with Typescript

**Comment by keithmifsud** [comment]
I'd also like to either be able to create such a rule or have the rule available.

I need to have a rule `required_if:another-field,value` and `prohibited_if:another-field,value`.

At the moment I cannot see how I can access the form schema/node from a custom validation rule.

**Comment by justin-schroeder** [comment]
Yes, it’s definitely possible to create dependencies in your validation rules. To do so you want to use [core node traversal](https://formkit.com/essentials/architecture#traversal). Here’s an example of a custom `require_one` rule:

https://formkit.link/cfae44ab9e3a91d069d584e6642f2663
