### ISSUE TITLE
Schema for loop on array with single number value

### ISSUE THREAD

**Issue by JustinProbyn** [formkit/formkit#635]
### Reproduction

https://formkit.link/f4e02e0d6bbcf02824dc0b1bf59e52f8

### Describe the bug

When using an array with only one value - that's either a number or a string that can be converted to a number - the schema for loop iterates the value that many times.

In the playground, you can change the number to a string of the number, e.g .10 to '10' and the same thing happens.

Is this intentional?

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by JustinProbyn** [comment]
Great, thanks for the quick response!

**Comment by justin-schroeder** [comment]
Wow. You only make a mistake like this once:

```js
isNaN([1])    // false
isNaN([1,2]) // true
```

JavaScript....
