### ISSUE TITLE
Add Tetum language

### ISSUE THREAD

**Issue by joshbrooks** [formkit/formkit#637]
### Reproduction

-

### Describe the bug

Adds initial translations for the "Tetum" language.
Tetum is one of the languages spoken in East Timor (Timor Leste) and will be the primary language for our site "Partisipa" https://partisipa-staging.catalpa.build

[tet.ts.txt](https://github.com/formkit/formkit/files/11086696/tet.ts.txt)

### Environment

-

**Comment by joshbrooks** [comment]
@sashamilenkovic Is there any further action required on our part for this?

**Comment by sashamilenkovic** [comment]
@joshbrooks Sorry, I haven't had a chance to look into this yet. Your txt file looks good, I'll add this to my queue.
