### ISSUE TITLE
Pressing enter inside an input on a multi-step form with a submit handler will submit the form, rather than advancing it

### ISSUE THREAD

**Issue by 5HT2** [formkit/formkit#641]
### Reproduction

https://formkit.link/980e8770e49ab3e4adc6997272e76cda

### Describe the bug

Pressing enter inside an input on a multi-step form with a submit handler will submit the form, rather than advancing it.
This happens on any of the steps.

A hacky workaround to intercept this in your submit handler can be done like so (assuming you have two steps, modify it if you have more than that):
```js
const submitForm = async (fields, handlers) => {
  console.log("submitForm", fields)

  let lastPage = true;

  handlers.children[0].walk(child => {
    if (child.name === "account_info") {
      // Increment to the next page if the user pressed enter on the first page.
      if (child.context.isActiveStep) {
        lastPage = false
        child.context.handlers.next()
      }
      console.log("account_info", lastPage, child.context)
    }
  })

  if (lastPage) {
    // rest of your submit handler
  }
}
```

Do note that this workaround does not focus the first input inside your next page, and when fixing this bug I think that will also need to be fixed explicitly, code-wise.

### Environment

• OS: Linux
• Browser Firefox, Chrome
• Version: 0.16.x any, 0.17.x beta

**Comment by 5HT2** [comment]
I am also not able to reproduce #601 on 1.16.4 or 1.17.x, but it seems somewhat related.

**Comment by 5HT2** [comment]
Slightly more hacky workaround that actually focuses the input.

```js
  handlers.children[0].walk(child => {
    if (child.name === "account_info") {
      // child.context.handlers.incrementStep(1, child.context)()
      // Increment to the next page if the user pressed enter on the first page.
      // This is necessary because
      if (child.context.isActiveStep) {
        lastPage = false
        makeUserInputActive = true
        child.context.handlers.next()
      }
    }

    // Focus the next text input if the user presses enter
    if (child.name === "user_info" && makeUserInputActive) {
      setTimeout(function () {
        const el = document.getElementById(child.context.node.children[0].props.id)
        el.focus()
        el.click()
      }, 20)
    }
  })
```

**Comment by GustavoFenilli** [comment]
The reason why it does submit, is because your submit at the step 3 is in the DOM when you click, even tho you're only looking at the first step visually.

So instead of using a `submit` use a `button` and programatically call `submit` on the form node https://formkit.link/2eaa3e5ea4d5bee480a3b905fe67ddb4

**Comment by 5HT2** [comment]
Thank you! That solves the actual "bug", it would probably be good to make it more explicit in the plugin's docs.

It would be nice to have advancing form steps when the user hits enter implemented properly, rather than the hacky workaround, but that would be more of a feature request on it's own.
