### ISSUE TITLE
Cannot use custom components in sectionsSchema

### ISSUE THREAD

**Issue by bringmethedeathstar** [formkit/formkit#643]
### Reproduction

https://formkit.link/0e7bff55345fa2dd1ae5c42daebd3b5b

### Describe the bug

Custom component isn't rendered inside `schema` when using `sectionsSchema`. I can't seem to find any examples of anyone using `$cmp` inside of `sections-schema` anywhere, so I may just be using this incorrectly? 😅 

```JavaScript
{
  $formkit: 'textarea',
  name: 'test',
  key: 'test',
  label: 'Enter some very important information',
  sectionsSchema: {
    label: {
      children: [
        '$label',
        {
          $cmp: 'Badge',
          props: { label: `This doesn't work` },
        },
      ],
    },
  },
},
```

### Environment

• OS: [MacOS Montery]
• Browser [Chrome]
• Version [111.0.5563.146]

**Comment by justin-schroeder** [comment]
Unfortunately I think the only way to resolve this (at the moment) is to globally register your `Badge` component so it is able to resolve it in the nested context.

**Comment by bringmethedeathstar** [comment]
@justin-schroeder that works perfectly for me, thanks!

**Comment by markusgeert** [comment]
> Unfortunately I think the only way to resolve this (at the moment) is to globally register your `Badge` component so it is able to resolve it in the nested context.

Is this registering the component globally with Vue? Or with FormKit? Registering with Vue doesn't seem to work..

**Comment by justin-schroeder** [comment]
Globally registering with Vue will still work just fine. However in > 1.6 there is also a `library` prop you can use to pass components to `sections-schema`
