### ISSUE TITLE
`node.walk` does not stop when passing `stopOnFalse: true` and returning `false` from callback.

### ISSUE THREAD

**Issue by AhmadJavaidWork** [formkit/formkit#644]
### Reproduction

https://formkit.link/30e3bf77c76f4610c0e7c34541a851e9

### Describe the bug

In the reproduction link I have edited the example provided in formkit's documentation for making a "scroll to error" plugin. I have added multiple validation rules in the form and when I submit the form without adding anything in the form, the `scrollToErrors` plugin runs and the `node.walk` function walks to every child of the form. And in the plugin I have specified that `node.walk` should stop when we find a child that has a validation error by passing `stopOnFalse: true` and returning `false` from the callback of `node.walk`.

But as you can see when you submit the form it scrolls to first node (that has validation errors) then second and then so on because `node.walk` does not stop when passing `stopOnFalse: true` and returning `false` from callback.

### Environment

• All

**Comment by justin-schroeder** [comment]
Thanks for the report. I’ve published a fix on the `@next` tag.
