### ISSUE TITLE
Dropdown multi-select

### ISSUE THREAD

**Issue by CallumAtCarter** [formkit/formkit#647]
### Reproduction

N/A

### Describe the bug

Feature request:
The Dropdown input should support the `multiple` attribute, similar to the implementation in the Autocomplete input.

### Environment

N/A

**Comment by jjjrmy** [comment]
my expected behavior would be the current selections are shown as active when you open the options dropdown, and the text of the input would be the selected option or "2 options selected" for more than one selection.
