### ISSUE TITLE
Formkit bad performance with lots? of data

### ISSUE THREAD

**Issue by azertyalex** [formkit/formkit#654]
### Reproduction

https://formkit.link/ca42c015bacecbf838ead1f4f674ef7a

### Describe the bug

I don't really think this is too much data. Creating similar UI with native html elements renders the page almost instantly while formkit takes many seconds to load.

Maybe it has to do with validation, maybe something else. I tried recording the performance but that didn't give me any clear info.

### Environment

• OS: Ubuntu
• Browser chrome
• Version 112

**Comment by dominikklein** [comment]
Maybe similar problem like this here: https://github.com/formkit/formkit/issues/473

You could check it against the performance release branch (but it's a little bit outdated, around beta 12).

**Comment by justin-schroeder** [comment]
Yes — this is the same as #473 — but I like the reproduction so I'll cross post it over there @azertyalex 👍

Closing in favor of #473.
