### ISSUE TITLE
autocompletion is not working after import formKitTailwind from '@formkit/themes/tailwindcss'

### ISSUE THREAD

**Issue by ericlaaper** [formkit/formkit#661]
### Reproduction

http

### Describe the bug

HI by using the formkittailwind plugin the autocompletion of webstorm tailwind does not work anymore. 
When I open the project in Visual Studio everything works fine.

Hope you can help me out. 

Cheers,

Eric

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by sashamilenkovic** [comment]
@ericlaaper Is there a reproduction you can make/any more information you can give?
