### ISSUE TITLE
Mask input timing issue with passing data to custom component

### ISSUE THREAD

**Issue by addidesign** [formkit/formkit#667]
### Reproduction

https://formkit.link/66a99b61d8c7ee62eec910068ec60ffa

### Describe the bug

You can see in the example, the first 2 inputs are passing values as mask inputs to a custom component and the output seems to drop in and out.

The 3 & 4th are number inputs passing the values to the same component and it seems to work fine.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
The reason for this is your masks on the top are often "incomplete" in otherwords not fully satisfying all portions of the mask. In the case of currency this is acceptable, so you can add the `allowIncomplete` prop:

https://formkit.link/67a9f87ef1e47ef836bff06a4a27df43

And all good! 👍
