### ISSUE TITLE
Validationkey matches doesn't work with certain pattern

### ISSUE THREAD

**Issue by azertyalex** [formkit/formkit#673]
### Reproduction

https://formkit.link/3091b647d7fc3a9787ec748ae8e50329

### Describe the bug

It seems that following pattern causes some issues.
```js
/^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}$/g
```

It is valid and working pattern in JS. When I submit the form it says `Please fill in a valid IP address`. I can circumvent this by typing an extra char, deleting it and submit it again.

### Environment

• OS: ubuntu
• Browser chrome
• Version 111

**Comment by justin-schroeder** [comment]
It does seem that removing the global flag solves it, but I'm not sure i understand *why* that is the case? Do you? The rule is quite simple:

```ts
const matches: FormKitValidationRule = function matches({ value }, ...stack) {
  return stack.some((pattern) => {
    if (
      typeof pattern === 'string' &&
      pattern.substr(0, 1) === '/' &&
      pattern.substr(-1) === '/'
    ) {
      pattern = new RegExp(pattern.substr(1, pattern.length - 2))
    }
    if (pattern instanceof RegExp) {
      return pattern.test(String(value))
    }
    return pattern === value
  })
}
```

So in this case it should just be running:

```ts
pattern.test(String(value))
```

Which seems to work fine when I repl it.

**Comment by GustavoFenilli** [comment]
I remember that I got a similar question in the discord and removing the `/g` worked as well, I'm not sure why tho.

**Comment by azertyalex** [comment]
The function looks fine, seems like the problem is somewhere else.

**Comment by justin-schroeder** [comment]
I believe this is all working in beta 18.
