### ISSUE TITLE
Non ISO 8601 complient date when extra precision is given to datepicker PRO

### ISSUE THREAD

**Issue by JesterIruka** [formkit/formkit#675]
### Reproduction

https://formkit.link/6205646c34e633fa4d9888f328850c91

### Describe the bug

When extra precision is given, the input[type=datepicker] throws **Error: Non ISO 8601 compliant date**

### Expected behavior:
✅ 2023-01-31T21:46:21Z
✅ 2023-01-31T21:46:21.000Z
✅ 2023-01-31T21:46:21.000000Z

### Current behavior:
✅ 2023-01-31T21:46:21Z
✅ 2023-01-31T21:46:21.000Z
❌ 2023-01-31T21:46:21.000000Z
>  **Non ISO 8601 compliant date (2023-01-31T21:46:21.000000Z)**

### Environment

Environment is not relevant to the issue.

**Comment by justin-schroeder** [comment]
This is now fixed in `@formkit/pro@0.111.12` — thanks for sponsoring us @JesterIruka!
