### ISSUE TITLE
DOM element of formkit list not deleted when remove an element from list value

### ISSUE THREAD

**Issue by comhon-project** [formkit/formkit#676]
### Reproduction

https://formkit.link/5ba35b224a750b8d2167a5a847e11eea

### Describe the bug

bug:
element of formkit list not deleted when remove an element from list value

expected: 
element should be remove from DOM

(if it's not a bug what is wrong in the playground example ?)

### Environment

• OS: Ubuntu 22.04
• Browser firefox
• Version formkit 0.16

**Comment by devoidofgenius** [comment]
Thank you for filing this issue. This is a known bug that is being worked on.

As long as you're iterating over something other than the value, you should be able to successfully accomplish what you're attempting to do. [Here is an example](https://formkit.link/57c5566acbc6fe1b128c9631057ab990)

**Comment by comhon-project** [comment]
yes but I can't use pro inputs, is there a free workaround ?

**Comment by GustavoFenilli** [comment]
You can still use the same example @devoidofgenius showed, just use a group instead, the example still stands, the bug is for iterating over the values instead of items, meaning you just need to iterate the group and not the values.

**Comment by andrew-boyd** [comment]
> yes but I can't use pro inputs, is there a free workaround ?

FWIW the repeater is free — it requires a pro licenses key but if you choose a pay-as-you-go license the repeater and toggle are both $0/month.

**Comment by justin-schroeder** [comment]
As of `0.17.2` there are now dynamic lists which solve these issues. 🎉
