### ISSUE TITLE
v-model.lazy does not seem to work correctly

### ISSUE THREAD

**Issue by wessel-techtribe-nl** [formkit/formkit#678]
### Reproduction

https://formkit.link/cf9ebac189721b7d32200178479047ea

### Describe the bug

v-model.lazy does not seem to work correctly in FormKit . 

If I use `v-if="!prop` with a `v-model.lazy="prop"` on a regular input the only disappears after focus is lost from the input.

If I do this on a FormKit input the input disappears after typing the first letter.

Maybe it's a strange usecase, for me it's for complementing missing data which was party retrieved somewhere else.

### Environment

• OS: macOS 13.3.1
• Browser Firefox
• Version 112.0.2 (64-bit)

**Comment by justin-schroeder** [comment]
That is correct, FormKit exclusively uses the input event, however inputs are debounced automatically. I'm not sure if we’ll change this behavior, but we'll keep this open as a reminder to investigate.

**Comment by wessel-techtribe-nl** [comment]
Ok, thanks for the quick reply! I will try a workaround
