### ISSUE TITLE
Input errors on not working in conjunction with multi step

### ISSUE THREAD

**Issue by darthf1** [formkit/formkit#679]
### Reproduction

https://formkit.link/d6f465d5ae8dab78ec6f0f76c7ba30fc

### Describe the bug

Hi!

When form components are inside a [multi-step](https://formkit.com/plugins/multi-step) flow, the [input-errors](https://formkit.com/inputs/form#using-input-errors-prop) prop does not work anymore as expected.

From the reproduction, if you would remove the  `multi-step` and the `step` components, you can see the error appearing again.

### Environment

• OS: Ubuntu 22.04
• Browser Firefox
• Version 122

**Comment by justin-schroeder** [comment]
You just need to give the full address of the input you are adding errors to (there can be items named the same things at different depths in your form). For example:

![image](https://user-images.githubusercontent.com/1950463/235189289-78452c93-27a5-4cc9-89da-919fca33f075.png)

https://formkit.link/607191cdb9f3ef172fdd5ed57ad31a10

Happy coding 👍

**Comment by darthf1** [comment]
@justin-schroeder ah yes that makes total sense!

However, is it possible (be it via a custom one) to make it so the errors can be mapped without the steps name? My API returns a perfect response, with the key as the field name and the value as an array of strings. However, the API is not aware of the steps used to display the different form elements. It would be great if the input-errors field mapping can be done on form field name alone.

**Comment by justin-schroeder** [comment]
There is sort of a work around here. Any node "address" works for the keys of your error object including any traversal (more here: https://formkit.com/essentials/architecture#traversal) So, if you know your data structure and you can be sure that there are no duplicate names in your form — you can use `find()` traversal which performs a breadth-first-search on your form tree for the specified name, that allows you to simply wrap your keys in a find() string:

https://formkit.link/998aa78221154eee81fad9cc4aa57373
