### ISSUE TITLE
`console.trace` logs in console instead of errors

### ISSUE THREAD

**Issue by huzaifahj** [formkit/formkit#686]
### Reproduction

https://formkit.link

### Describe the bug

![image](https://user-images.githubusercontent.com/52999758/236133278-7625690f-860c-42ac-94e7-c8d614186e67.png)

Errors like this in the console are appearing when I open/close a taglist/autocomplete input. I'm getting issues with the popover for those inputs not closing after clicking the down arrow again. The errors may be linked to that but I have no way to investigate further. A new log appears each time I click the down arrow to show the popover.

It should display the error instead of the trace. I've tried it without Sentry installed too.

### Environment

```
    "@formkit/icons": "^0.17.0-e457a82",
    "@formkit/nuxt": "^0.16.5",
    "@formkit/pro": "^0.111.15",
    "@formkit/themes": "^0.17.0-e457a82",
```

**Comment by sashamilenkovic** [comment]
@huzaifahj Your playground link gives me a 404. Was there a reproduction you were trying to share?

**Comment by huzaifahj** [comment]
No able to reproduce this in the playground

**Comment by justin-schroeder** [comment]
@formkit/nuxt@next is not compatible for @formkit/pro at the moment.

**Comment by huzaifahj** [comment]
`0.16.5` is `@latest` not `@next`?

![image](https://github.com/formkit/formkit/assets/52999758/8ed8f687-9d44-4597-a7cd-1b87b4714961)

**Comment by sashamilenkovic** [comment]
@huzaifahj Can you try the latest version of pro? [0.111.19](https://www.npmjs.com/package/@formkit/pro/v/0.111.19)
