### ISSUE TITLE
Using FormKit Pro Key From .env in Nuxt

### ISSUE THREAD

**Issue by Buffalom** [formkit/formkit#687]
### Reproduction

https://github.com/TitusKirch/example-nuxt3-formkit-app

### Describe the bug

This is a follow-up to #595.

I understand, that using useRuntimeConfig() in formkit.config is not possible. However, I am unable to find a workaround to using the FormKit Pro key from .env. `process.env.FORMKIT_KEY` works server-side but client-side I keep failing. [When my formkit.config is imported](https://github.com/formkit/formkit/blob/master/packages/nuxt/src/module.ts#L35-L41), the config is available (through the `nuxt` argument of the module's setup function). How do I access it from inside the fomkit config?

The way I see it, I should be able to export a function accepting the nuxt module's arguments instead of exporting the config directly.

The only alternative I see currently, is to commit the key to my repo since Vercel eventually builds it from there. This feels very dirty.

### Environment

• OS: macOS
• Browser: Arc (Chromium)
• Version: @formkit/nuxt@0.16.4

**Comment by andrew-boyd** [comment]
`useRuntimeConfig()` is now possible in `0.17.4`.

Update your `formkit.config.ts` to look like this excerpt from the updated docs

---

There may be instances where you want to use Nuxt's `runtimeConfig` variables inside of your `formkit.config.ts` file — such as keeping a FormKit Pro API key from being published in your codebase. To achieve this you can provie a function to `defineFormKitConfig` which returns a configuration object. Your function will be called by Nuxt and have access to `runtimeConfig`.

```js
import { fr } from '@formkit/i18n'
import { defineFormKitConfig } from '@formkit/vue'
import { createProPlugin, inputs } from '@formkit/pro'

export default defineFormKitConfig(() => {
  // here we can access `useRuntimeConfig` because
  // our function will be called by Nuxt.
  const config = useRuntimeConfig()

  // and we can use the variables to import secrets
  const pro = createProPlugin(config.FORMKIT_PRO_KEY, inputs)

  return {
    plugins: [pro],
    locales: { fr },
    locale: 'fr',
  }
})
```

**Comment by Buffalom** [comment]
Finally got around to test it. Seems to work perfectly. Thanks a lot.

**Comment by manniL** [comment]
Little add-on here: The key must be part of `public` in `runtimeConfig`

**Comment by DanjBethel** [comment]
Seems to be broken again maybe? Getting the error message "A composable that requires access to the Nuxt instance was called outside of a plugin..."

**Comment by manniL** [comment]
@DanjBethel works fine for me if you use `defineFormKitConfig` and a *function*

**Comment by enoch2110** [comment]
> @DanjBethel works fine for me if you use `defineFormKitConfig` and a _function_

It seems to produce the problem that @DanjBethel mentioned when `autoImport` option is set to `true`

**Comment by enoch2110** [comment]
> Seems to be broken again maybe? Getting the error message "A composable that requires access to the Nuxt instance was called outside of a plugin..."

The current workaround is to set `autoImport` to `false`. Then some auto imports such as `FormKitProvider`, `FormKitMessages`, `FormKitSummary` would not auto import.

If you want those to auto import as well, you can put the following code in `modules/formkit.ts` to set auto import for third party components.


```typescript
import { addComponent, defineNuxtModule } from '@nuxt/kit'

export default defineNuxtModule({
  setup() {
    addComponent({
      name: 'FormKitProvider',
      export: 'FormKitProvider',
      filePath: '@formkit/vue',
      chunkName: '@formkit/vue'
    })

    addComponent({
      name: 'FormKitMessages',
      export: 'FormKitMessages',
      filePath: '@formkit/vue',
      chunkName: '@formkit/vue'
    })

    addComponent({
      name: 'FormKitSummary',
      export: 'FormKitSummary',
      filePath: '@formkit/vue',
      chunkName: '@formkit/vue'
    })
  }
})

```

**Comment by manniL** [comment]
@enoch2110 Could you raise a new issue then here? I think that'd help ☺️

**Comment by jpcarpenter** [comment]
Any update on this? It'd be really nice to use `autoImport: true` feature and have things work properly 😅

**Comment by jessekahner** [comment]
Any news on this front?
I'm "scared" of what I'd have to import manually. 😬
