### ISSUE TITLE
Node is not being created when using FormKit with HeadlessUI Dialog

### ISSUE THREAD

**Issue by MattFromGer** [formkit/formkit#689]
### Reproduction

https://stackblitz.com/edit/bug-formkit-with-headless-ui-dialog?file=src%2Fcomponents%2FHelloWorld.vue&terminal=dev

### Describe the bug

I'm using a form in a dialog provided by the [HeadlessUI lib](https://headlessui.com/vue/dialog) of TailwindLabs. For a specific functionality ([multistep form with custom located action buttons](https://github.com/orgs/formkit/discussions/685)) I need to access the node of a FormKit component. But `getNode()` would always return undefined.

While preparing the reproduction example I realised that the problem might have something to do with the FormKit component not getting registered internally? The first input gets `text_1` as a name, the third one is `text_2`. Maybe `createNode()` doesn't get called?

As you can see in the reproduction example I even tried the `Teleport` component, which FormKit handles perfectly. So I don't know if the Dialog is doing anything shady ([code here](https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-vue/src/components/dialog/dialog.ts)) or if it's a bug in the FormKit code?

### Environment

• Version [0.16]

**Comment by sashamilenkovic** [comment]
@MattFromGer Hey! I took a look at this. So I'm not familiar with HeadlessUI, but I would guess that the Dialog component that you have wrapping your FormKit component with "my-id-2" is not rendering immediately on mount. If you wrap that assignment in a setTimeout: https://stackblitz.com/edit/bug-formkit-with-headless-ui-dialog-us8nuk?file=src%2Fcomponents%2FHelloWorld.vue&terminal=dev, you'll see that it works.

**Comment by sashamilenkovic** [comment]
@MattFromGer As a workaround, you can just use the @node directive and assign it to a function like this: https://stackblitz.com/edit/bug-formkit-with-headless-ui-dialog-gxtrmu?file=src/components/HelloWorld.vue

**Comment by MattFromGer** [comment]
Thank you for your help! I can live with the solution, but I guess it's not something that is going to be handled by the library? Async initialisation...
