### ISSUE TITLE
Type Error to adding formKit option to nuxt config file

### ISSUE THREAD

**Issue by OrhanOzkercin** [formkit/formkit#69]
**Describe the bug**

I was following the documentation and making configurations for my Nuxt3 project. When I wanted to add formKit property to defineNuxtConfig function parameter. It throws an error like below.

![image](https://user-images.githubusercontent.com/25130814/153268896-aa4d0efc-7ba5-4142-bc1e-37aa6c703ea3.png)

Here is the all nuxt config file: 
```
export default defineNuxtConfig({
  buildModules: ["@pinia/nuxt"],
  modules: ["@formkit/nuxt"],
  formkit: {
    configFile: "./my/custom/location/formkit.config.ts",
  },
  build: {
    postcss: {
      postcssOptions: require("./postcss.config.js"),
    },
  },
  css: ["~/assets/css/tailwind.scss", "~/assets/css/global.scss"],
});
```

**Comment by andrew-boyd** [comment]
@OrhanOzkercin Thank you for the report, we will look into it. In the mean time, can you try doing the option inline with the module like so and see if gets you past this particular hurdle?

```
export default defineNuxtConfig({
  buildModules: ["@pinia/nuxt"],
  modules: [
    ["@formkit/nuxt", {configFile: "./my/custom/location/formkit.config.ts"}]
  ],
  build: {
    postcss: {
      postcssOptions: require("./postcss.config.js"),
    },
  },
  css: ["~/assets/css/tailwind.scss", "~/assets/css/global.scss"],
});
```

**Comment by justin-schroeder** [comment]
@OrhanOzkercin I wonder if this is a version mismatch of Nuxt 3 — there have been a lot of updates going on in the Nuxt 3 community so its hard to know for sure which is causing issues, but I'm unable to duplicate this issue with a fresh install of Nuxt 3.
