### ISSUE TITLE
Make note in docs that `type` prop is not intended to be changed dynamically.

### ISSUE THREAD

**Issue by bielfrontera** [formkit/formkit#693]
### Reproduction

https://formkit.link/9451e663a0a2fbbfda278507f6fd2192

### Describe the bug

I've created a custom input for passwords with the `forceTypeProp` property `password`. It generates an input with type password, as expected. 

However If the type prop of the Formkit component is reactive, it is rendered with the type password the first time, and when the type is set again to the custom input, it is rendered with the name of the custom input as type instead of `password` (the value of forceTypeProp`).

### Environment

• OS: any
• Browser: chrome
• Version: 0.16.1

**Comment by GustavoFenilli** [comment]
I think this has to do with vue reusing dom nodes to save performance, so just add a unique key and it should work fine https://formkit.link/1e72eaf1bdcd8de6646e210a55112f10

**Comment by bielfrontera** [comment]
Many thanks @GustavoFenilli !

With this solution, I also have to add a v-model prop to preserve the data that the user has already filled in the input. But it works fine for me. https://formkit.link/778b7b3b5543fbc99ea5025ce2c7ea0b

**Comment by GustavoFenilli** [comment]
No need for v-model you can use the `preserver` prop like so https://formkit.link/070c9529972bb5f80fcec480106e01fe
