### ISSUE TITLE
List flattens complex object 

### ISSUE THREAD

**Issue by csakis** [formkit/formkit#697]
### Reproduction

https://formkit.link/036e72e7f1268061a82f9803438c168b

### Describe the bug

I need to create a form that contains a dynamic list of subforms. This requires to use the type 'list'.
I could not find a way of looping through the list (array) of objects and bind the appropriate fields to the form fields. The list flattened my objects into a one dimensional array. 

### Environment

• OS: Windows 10
• Browser MS Edge
• Version  112.0.1722.68

**Comment by justin-schroeder** [comment]
Lists always produce simple arrays. If you want more depth, you can use more lists or groups. For example:

https://formkit.link/517046ed94a622dd55140ca301b53a4d

Good luck 👍
