### ISSUE TITLE
Certain mask combinations wiping input

### ISSUE THREAD

**Issue by SDRACK** [formkit/formkit#699]
### Reproduction

https://formkit.link/eda391a3d61e193639a7ed4b214de767

### Describe the bug

Hey again :)

This is a follow on from: https://github.com/formkit/formkit/issues/677.

The fix there overcame the issue at hand, but since updating there's another problem: entering more than three digits sees the field wipe itself.

Replicated nicely in the attached playground - only seems to happen using a schema rather than on page components.

Any ideas?

### Environment

• OS: Mac Ventura 13.3.1
• Browser: Chrome
• Chrome version: 113
• Formkit version: 0.16.5

**Comment by justin-schroeder** [comment]
Thanks! This is fixed in `@next` 👍
