### ISSUE TITLE
Time input not opening in Firefox

### ISSUE THREAD

**Issue by dpankratz96** [formkit/formkit#702]
### Reproduction

https://formkit.link/30d4bd9718aeb32fa016c0ca9aab50fd

### Describe the bug

The popup to select a time on the time input ist not opening on Firefox. Even the clock icon is missing.

### Environment

• OS: Win 10
• Browser Firefox
• Version 113.0

**Comment by sashamilenkovic** [comment]
@dpankratz96 It appears that's just how Firefox renders its native time input: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time
