### ISSUE TITLE
Datepicker not working properly in Portuguese 

### ISSUE THREAD

**Issue by Tragio** [formkit/formkit#705]
### Reproduction

https://formkit.link/72514a2a2b3244d0c21cb6ace5342d00

### Describe the bug

Hi there 👋 

The `datepicker` component is not working properly in Portuguese 🇵🇹, not sure if the same is happening in other languages.

The date appears with backslashes `\` and if after the date selection, you try to change for example the year, it shows a validation error.

![CleanShot 2023-05-13 at 09 44 37](https://github.com/formkit/formkit/assets/5109593/e1a93451-dc3d-4151-931a-7c8b0314098b)

Thank you for the amazing work 🚀 

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
Looking into this now 👍

**Comment by justin-schroeder** [comment]
Thanks for the report — this is fixed in `@formkit/pro@0.112.1` 👍
