### ISSUE TITLE
Destructured form value from default slot not reflecting updates when passed as prop to child component

### ISSUE THREAD

**Issue by andrew-boyd** [formkit/formkit#717]
### Reproduction

https://formkit.link/4223c27a99b215640ebe6cefacf75dae

### Describe the bug

If you desctructure the `value` from the default slot of a `form` in FormKit and pass it as a prop to a nested child component, the `value` prop will not receive any updated values from the fields inside the child component. This is a regression from Beta 16.

### Environment

• OS: MacOS
• Browser: Brave
• Version: 1.151

**Comment by justin-schroeder** [comment]
Fixed in 0.17.1
