### ISSUE TITLE
Different event `prop:{propName}` behaviour for default props and custom props.

### ISSUE THREAD

**Issue by dominikklein** [formkit/formkit#73]
**Describe the bug**
At the moment the core event for set/updated props (`prop:{propName}`) has a different beahviour for the default props and the added custom props.

I think the behaviour should be aligned:

1. Trigger also for the "initial value" the event for the default props (e.g. label).
2. Don't trigger the event for custom props, when the "initial value" was filled.

The question is maybe, for what kind of default props we ware talking and has it some downsides to trigger for all the default props the event?
If i understand it correctly the placeholder is normally not a real prop, so for this the event can not be used? Are there other possibilities?

**Reproduction**
[Playground](https://formkit.link/bdb4e199a17b42b46bb6fb4bf292233b)
See log messages.

**Comment by justin-schroeder** [comment]
@dominikklein So looking this over a bit now that I'm ready to work on it — I think the change that needs to be made is we should *not* trigger a `prop:{name}` event for custom props for the initial value. Since they are the initial values, I'm not sure they count as change events, and the only alternative to align them is to trigger prop event emissions for every single prop which would just be a big fat unnecessary call stack.

Any opposition to this?

**Comment by dominikklein** [comment]
Yes sounds so for me as the best solution :-)

**Comment by dominikklein** [comment]
Hi @justin-schroeder 

I think this is still not consistent and I think also the doc is saying it correct (`Emitted any time a prop is set or changed.`).

And also the prop-event is different from the hook when I see it correctly:

```
---NODE--- login
HOOK formId 653440109
HOOK initial undefined
HOOK attrs {placeholder: 'Username / Email'}
PROP-EVENT attrs {placeholder: 'Username / Email'}
HOOK parsedRules [{…}]0: {args: Array(0), timer: 0, state: false, queued: false, rule: ƒ, …}length: 1[[Prototype]]: Array(0)
PROP-EVENT parsedRules [{…}]
HOOK definition {type: 'input', props: Array(4), features: Array(1), schema: ƒ}
PROP-EVENT definition {type: 'input', props: Array(4), features: Array(1), schema: ƒ}
HOOK id input_0
PROP-EVENT id input_0
HOOK attrs {placeholder: 'Username / Email'}
PROP-EVENT attrs {placeholder: 'Username / Email'}
```

```
---NODE--- password
HOOK initial undefined
HOOK attrs {placeholder: 'Password', formId: '653440109'}
PROP-EVENT attrs {placeholder: 'Password', formId: '653440109'}
HOOK passwordVisibilityIcon eye
PROP-EVENT passwordVisibilityIcon eye
HOOK definition {type: 'input', props: Array(3), features: Array(2), schema: ƒ}
PROP-EVENT definition {type: 'input', props: Array(3), features: Array(2), schema: ƒ}
HOOK formId 653440109
HOOK initial undefined
HOOK attrs {placeholder: 'Password'}
PROP-EVENT attrs {placeholder: 'Password'}
HOOK parsedRules [{…}]
PROP-EVENT parsedRules [{…}]
HOOK definition {type: 'input', props: Array(5), features: Array(2), schema: ƒ}
PROP-EVENT definition {type: 'input', props: Array(5), features: Array(2), schema: ƒ}
HOOK id input_1
PROP-EVENT id input_1
HOOK attrs {placeholder: 'Password'}
PROP-EVENT attrs {placeholder: 'Password'}
```

Here you can for example see, that some props are triggered with the hook and event, but some are not. And the `attrs` is triggered twice during the initial creation.

Maybe this can be checked or can you explain this a little bit more.
