### ISSUE TITLE
Taglist, Autocomplete inputs: cachedOption always return false

### ISSUE THREAD

**Issue by Dartsya-Zelo** [formkit/formkit#730]
### Reproduction

https://formkit.link/a89c2650cf3655e303034a014c02a5af
### Describe the bug

cachedOption always return false. Error not reproducible in playground. Using @formkit/nuxt, inputs Autocomplete, taglist send requests many times, the response is not cached. 
```
export function useAutocompleteOptionLoader<DataT extends ExtendedBaseType>(
  viewFunction: (id: number) => Promise<SingleRecordResponse<DataT>>,
  mapFunction?: (data: DataT) => Option
): (id: number, Option: Option) => Promise<Option | undefined> {
  return async (id, cachedOption) => {
    if (cachedOption) return cachedOption;
    console.debug('cachedOption', cachedOption);
    const { data } = await viewFunction(id);
    if (data) {
      if (mapFunction) {
        return mapFunction(data);
      }
      return {
        label: data?.name || '',
        value: data?.id,
      };
    }
    return { label: 'Error loading' };
  };
}
```

### Environment

- Nuxt 3.4.2
- Formkit/nuxt 0.16.5
- Formkit/pro 0.111.21

**Comment by justin-schroeder** [comment]
Can you provide a reproduction of this issue in nuxt? Maybe on stackblitz? We’re not seeing the same issue.
