### ISSUE TITLE
Taglist not rendering correctly when options are empty

### ISSUE THREAD

**Issue by subtubes-io** [formkit/formkit#732]
### Reproduction

https://formkit.link/fa78befdbb6401ef78653427d70cf567

### Describe the bug

. 
There are two issues when I render a taglist with an empty options list:
- The taglist breaks and does not allow users to create new tags
- Instead of being two distinct values as tags, I get one tag "honda,toyota" vs "honda", "toyota"

[I posted this in the discord chat originally but now was asked to make a ticket.](https://discord.com/channels/793529058377072650/1025447518617735210/1109200646978146475)

[Please see the reproduction in the playground](https://formkit.link/fa78befdbb6401ef78653427d70cf567). 

<img width="466" alt="broken-taglist" src="https://github.com/formkit/formkit/assets/1854719/8e035d6e-b3f5-4821-8cc1-dd46c4fee509">

### Environment

Chrome Version 113.0.5672.126 (Official Build) (arm64)

**Comment by shurth** [comment]
+1 to not disable the taglist when the options are empty. I was hoping to use it as a taglist for arbitrary (new) tags.

**Comment by sashamilenkovic** [comment]
@subtubes-io @shurth Closing this in favor of #586.
