### ISSUE TITLE
Datepicker Pro input throws error when using keyboard with `picker-only` option

### ISSUE THREAD

**Issue by lukepeel** [formkit/formkit#736]
### Reproduction

https://formkit.link/26abe9131c18c7dc46f05b6233934960

### Describe the bug

I have this setup:
```
<FormKit
    type="datepicker"
    name="dob"
    label="Date of birth"
    format="DD MMMM YYYY"
    value-format="YYYY-MM-DD"
    :sequence="['year', 'month', 'day']"
    picker-only
    validation="required"
/>
```

And clicking through the options works fine, but if you press any key on the keyboard, it throws a RangeError. 

`RangeError: Invalid time value`

### Environment

• OS: MacOS
• Browser Chrome
• Version latest

**Comment by justin-schroeder** [comment]
This bug is now fixed on the @next tag, thanks for the report 👍
