### ISSUE TITLE
`{section}Class` is compiled before and can not use the node.context in schema

### ISSUE THREAD

**Issue by rexpan** [formkit/formkit#737]
### Reproduction

[PlayGround](https://formkit.com/playground?fkv=latest&fileTab=Playground.vue&css-framework=genesis&files=jc%5B%28%276%21%27Playground.vue%27%7EeditN%21%27%3CscripOsetup2GdataH%2801f64xxx*0%290Gs8H%5B0%28%24fNmkit47364f6M4I+if+helloMClass%3A%28if4%246B%3D+%22f6%223then4TI3else4TD*%29+%29%2C0%5D05script20%3CE11U+typeJfNmRv-modelJdata*21QUS8+%3As8Js8R%2F2115925E%3CL.TIAI%29+0.TDAD%2905L%27%7Eadded%21true%29%5D*%5C%270%5CnQ+2%3E03*%2C+4%3A*5%3C%2F6name7text8chema9FNmKitA%28+colN%3AH%3DDgreenEtemplate2GconsOHB+IredJ%3D*Lstyle2M3labelNorOt+Q1+R*+T7-U%3C9%01UTRQONMLJIHGEDBA9876543210*_&imports=jc%28%27name%21%27ImportMap%27%7Eeditor%21%27%28*+1vue%5C%211https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fvue%403%2Fdist%2Fvue.esm-browser.min.js0*%29*%27%29*%5Cn0%5C%271+0%0110*_)

### Describe the bug

The `labelClass` will be resolved to `text-green` instead of `text-red`. The `$name` not available since it was resolved upfront.
```
<script setup>
const data = {
  fname:"xxx"
}
const schema = [
{$formkit:"text", name:"fname", label:"red if hello", labelClass:{if:"$name == 'fname'", then:"text-red", else:"text-green"} },
]
</script>

<template>
    <FormKit type="form" v-model="data">
     <FormKitSchema :schema="schema" />
    </FormKit>
</template>
<style>
.text-red{ color:red} 
.text-green{ color:green}
</style>
```

### Environment

• OS: Windows
• Browser: Chrome
• Version: 116

**Comment by andrew-boyd** [comment]
There are some issues with your example code. I've modified your example at it appears to be working as expected. Can you confirm? https://formkit.link/a5ee7ae7650e5b74a24a3663151b81ba

**Comment by rexpan** [comment]
Hi @andrew-boyd
Thank for replied. But actually the condition should be applied more generic. The example above is just for the minimum reproduce.
The question is why `{section}Class` cannot access the node context like `$type`, `$id`...
For use case, I need to applied the logic to many nodes based on their context so the `$get(id)` is not straightforward. For example: [to apply the class if the input is type **text](https://formkit.com/playground?fkv=latest&fileTab=Playground.vue&css-framework=genesis&files=jc%5B%28%27B%21%27Playground.vue%27%7Eeditz%21%27%3CscripHsetup7consHdataV%281*fB3Alex09*W%3A421%2911consHs8V%5B1GIZB3fBZQ3firsHBRfBN%299Gnumber0%2C*B3WZQ3WRWN%299%5D.map%7BMD%3E+Object.assign%7BM5%281*QU+%281Y*%2F%2F+if3%24609Y*if+%3A%60%24get%7B%22%24%28M.id%29%22%7D.6%609Y*then3I-redZ1Y*else3q1Y%299YouterU0q9%29%7D%7D11Escript71%3CT*%3CLHtypeXfzmNv-modelXdata07Y%3CLtS8+%3As8Xs8N%2F7*ELt7ET1%3Cw.I-redJred%29+1.I-greenJgreen%291Ew%27%7Eadded%21true%29%5D*++0%5C%271%5Cn3%3A+Z%2C+6typeD%3D+%22I%227%3E18chema9%2C1BnameV%3DE%3C%2FG*%28+%24fzmkit3Ht+ItextJ%28+colz%3ALFzmKiMnodeS8N0+QlabelRZid%3A0_Ttemplate7UClass%3AVD+WageX%3D0Y**Z05q%24id0wstyle7zor%01zwqZYXWVUTRQNMLJIHGEDB98765310*_&imports=jc%28%27name%21%27ImportMap%27%7Eeditor%21%27%28*+1vue%5C%211https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fvue%403%2Fdist%2Fvue.esm-browser.min.js0*%29*%27%29*%5Cn0%5C%271+0%0110*_), the condition should be `if: "$type == 'text'"` but for workaround it is 
```
if :`$get('${nodeSchema.id}').type == 'text'`
```
Again, the condition is not important. The idea is to use node context in `{section}Class` instead of workaround by `$get(id)`.

**Comment by dominikklein** [comment]
I think in general the classes are not reactive inside the schema data? I tried this here and it's not working:

https://formkit.link/1426dad27582d507db7df5380194c049

**Comment by justin-schroeder** [comment]
I think there are 2 different things here. @rexpan — in your situation you are asking for the `node.type` which is *always* either `input` `group` or `list`. The type prop is available at: `node.props.type` (https://formkit.link/5093597a6c7bed5975e9e0babed329dd).

A separate issue worth exploring further is @dominikklein’s issue — classes don’t appear to work when dynamically changed using `bind` in schema.
