### ISSUE TITLE
Repeater Input #addButton Slot Not Working

### ISSUE THREAD

**Issue by jjjrmy** [formkit/formkit#750]
### Reproduction

https://formkit.link/b5bdc49d803df5923007bd36e4123203

### Describe the bug

Repeater Input #addBytton Slot Not Working

### Environment

Latest

**Comment by andrew-boyd** [comment]
Not entirely sure _why_ this works — but if you use the `sections-schema` prop to set the `addButton` element to `null` and _then_ use the slot it'll work. You can use this as a workaround until we get the schema updated in the next Pro release. https://formkit.link/452626c7bc0a25b4f89643ed6487c493
