### ISSUE TITLE
Nuxt custom config not working `Unknown input type "form" ("form_1")`

### ISSUE THREAD

**Issue by jclaessens97** [formkit/formkit#754]
### Reproduction

https://stackblitz.com/edit/nuxt-starter-vyfylt?file=package.json,formkit.config.ts,app.vue,nuxt.config.ts

### Describe the bug

I'm trying to setup FormKit on Nuxt with custom tailwind classes configured, however as soon as I try to use a custom config, FormKit gives the error `Unknown input type "form" ("form_1")` on my form.

Even with an empty custom config, it doesn't work.

### Environment

• OS: [e.g. iOS]: `MacOS`
• Browser [e.g. chrome, safari]: `Chrome`
• Version [e.g. 22]: `144`

**Comment by GustavoFenilli** [comment]
You're passing a custom config, meaning that you're opt-out of the default configuration components/rules and all automatically added things FormKit add, so if you want to keep your bundle small this is the recommended way, and adding anything you want manually by importing it.

But you can also import `defaultConfig` and use it to get all configurations and if you pass your configuration object inside of it, it will be merged with the default configuration that exists.

**Comment by jclaessens97** [comment]
Okay, so the thing is I already tried importing the `defaultConfig` and merge it with my config... Except I overlooked the part where defaultConfig is not an object but a function 🤦‍♂️

Thanks!
