### ISSUE TITLE
File input not resetting correctly

### ISSUE THREAD

**Issue by morgan-retex** [formkit/formkit#762]
### Reproduction

https://formkit.link/24b3c799ffb7ca74fe6d3c398476a90a

### Describe the bug

Issue: Resetting a file input prevents re-selecting the previous file

Reproduction steps:
- select a file for the file input
- Press "reset" (thus calling node.value.reset() )
- Notice how the input is cleared
- Try selecting the same file as before for the input
- Notice how  the input is still empty

**Observed outcome:** The file input is not populated when re-selecting the same file from before the reset. It appears that the node.value doesn't get reset properly and still holds the value after the reset. This happens only when re-selecting the same file as before the reset.
**Desired outcome:** Selecting the same file after resetting the input should repopulate the input

### Environment

• OS: MacOS Ventura
• Browser: Chrome 114
• Version: Formkit 0.17+

**Comment by justin-schroeder** [comment]
Ah yeah, thank you for the good reproduction. We can resolve this for sure 👍

**Comment by justin-schroeder** [comment]
@GustavoFenilli I'm pretty sure we need to listen to the `reset` event in the file input’s feature and manually reset the dom element.
