### ISSUE TITLE
Improve docs for conditional elements needing `:key` prop.

### ISSUE THREAD

**Issue by CountKyle** [formkit/formkit#764]
### Reproduction

https://formkit.link/e93bc0e5826b2e21afb6e502eb34ed48

### Describe the bug

When using conditions that show or hide more than one field, the name of the field appears to be wrong. 

In the example playground attached, if you select "Qualification" as the type, then change it back to "Unit", the field with the id "unit_id" has the name "awarding_body_id", which is wrong. 

The name always seems to go by the order the field is set in the dict.

Steps to recreate:

![formkit-conditional-bug](https://github.com/formkit/formkit/assets/297354/20faebe0-d003-4c59-b83d-bf8be1031630)

Incorrect name:

<img width="503" alt="Screenshot 2023-06-14 at 12 20 58" src="https://github.com/formkit/formkit/assets/297354/4046884e-24b8-48e6-b6e7-b331a1d9ff8e">

I've tried using the `$cmp` method  and also dropping the id prop, but it doesn't seem to make any difference.

### Environment

• OS: macOS Big Sur
• Browser: Chrome 113

**Comment by justin-schroeder** [comment]
You need to include a `key` when using conditional fields in a schema array. https://formkit.link/33f93d5196d961f3c1be7280a3f25b34

This is actually a Vue thing, not a FormKit thing, but I think we need to do a better job of calling this out in the docs.

**Comment by justin-schroeder** [comment]
We added this to more places in the docs.
