### ISSUE TITLE
Schema: Changing the type of a FormKit field not working

### ISSUE THREAD

**Issue by volkerjaenisch** [formkit/formkit#767]
### Reproduction

https://formkit.link/e455836aa0a711578269011d656eef48

### Describe the bug

Sorry to bother you.

Formkit is an astonishing tool! I have not once seen a tool, so new, that can be included in your code so unobtrusive.

I have programed a quite simple WSIWYG JSON editor to generate Formkit forms and I am stuck.

**If you have a formkit schema form in your Vue <template> and you change the type of a form element e.g. from "text" to "select" then formkit crashes.**

I have tried to catch this problem in the linked playground.

![image](https://github.com/formkit/formkit/assets/2539336/14434f7d-b9f8-4bea-bc0d-423ff4ee8f08)

I am not sure if this is a bug in formkit or me using formkit in a weird way.

Any help appreciated

Cheers,
Volker

### Environment

• OS: Linux
• Browser all

**Comment by GustavoFenilli** [comment]
Changing the schema dynamically is not recommended, but in your case as you need to change it, you also need to tell vue that it is being changed with a unique `key` property like so: https://formkit.link/2ceba80dd1a58e08f9d521a20e96eb33

**Comment by volkerjaenisch** [comment]
@GustavoFenilli 
Thank you so much! You saved my night.
Cheers,
Volker
