### ISSUE TITLE
Checkbox label slot will be ignored, if Radio-Button exists and no label prop isset

### ISSUE THREAD

**Issue by TitusKirch** [formkit/formkit#778]
### Reproduction

https://formkit.link/5f7c0e5bd469bc64fdb8fbe6f01ac353

### Describe the bug

In my form I have a checkbox whose label is set with `<template #label>...</template>' instead of via. Props (this works). When I add radio buttons, no label is displayed for the checkbox unless I add the label prop to the checkbox. Then the content of the label slot is displayed.

If you are using Nuxt and SSR is enabled, you can actually see it being rendered correctly for a moment, but then it disappears and the hydration is mismatched.

Works:
```VUE
<FormKit type="checkbox" name="bar">
  <template #label>This is shown</template>
</FormKit>
```

Works not:
```VUE
<FormKit
   type="radio"
  name="foo"
  :options="[
    { label: 'abc', value: true },
    { label: 'xyz', value: false },
  ]"
  validation="required"
/>
<FormKit type="checkbox" name="bar">
  <template #label>This is not shown</template>
</FormKit>
```

Works:
```VUE
<FormKit
   type="radio"
  name="foo"
  :options="[
    { label: 'abc', value: true },
    { label: 'xyz', value: false },
  ]"
  validation="required"
/>
<FormKit type="checkbox" name="bar" label="this will be ignored">
  <template #label>This is shown</template>
</FormKit>
```

### Environment

• OS: Windows 11
• Browser: Chrome 114
• Formkit-Version: next

**Comment by justin-schroeder** [comment]
Great reproduction, thank you @TitusKirch. Will be fixed in beta.18
