### ISSUE TITLE
Error thrown by createIconHandler when `iconName` is null / undefined

### ISSUE THREAD

**Issue by SDRACK** [formkit/formkit#780]
### Reproduction

https://formkit.link/092d9e5b547708e1b0bd2a33a199c58c

### Describe the bug

We're seeing a console error from the `createIconHandler` function:

> errorhandler.js:44 [Vue warn]: Error in watcher callback: "TypeError: Cannot read properties of undefined (reading 'startsWith')"

```
function createIconHandler(iconLoader, iconLoaderUrl) {
    return (iconName) => {
        if (typeof iconName === 'boolean') {
            return; // do nothing if we're dealing with a boolean
        }
        // if we're dealing with an inline SVG, just use it as-is
        if (iconName.startsWith('<svg')) {
            return iconName;
        }
        if (typeof iconName !== 'string')
            return; // bail if we got something that wasn't a boolean or string
```

This seems to be fixed by moving the `typeof iconName !== 'string'` check _before_ the `startsWith` check, e.g.

```
function createIconHandler(iconLoader, iconLoaderUrl) {
    return (iconName) => {
        if (typeof iconName === 'boolean') {
            return; // do nothing if we're dealing with a boolean
        }
        if (typeof iconName !== 'string') {
            return; // bail if we got something that wasn't a boolean or string
        }
        // if we're dealing with an inline SVG, just use it as-is
        if (iconName.startsWith('<svg')) {
            return iconName;
        }
```

I've not been able to isolate what's causing this in our schema (our form is pretty complex), so can't strictly ascertain the cause and why `iconName` is undefined at this stage - all our `prefixIcon` / `suffixIcon` / etc. options use string values. 

My gut says the check coming first is logical to defend against this issue, but happy to hear feedback / advice on this :)

### Environment

• OS: Ventura 13.3.1 (a) 
• Browser Chrome 114.0.5735.133
• Version     
    "@formkit/icons": "^0.17.2",
    "@formkit/pro": "^0.112.6",
    "@formkit/themes": "^0.17.2",
    "@formkit/vue": "^0.17.2",

**Comment by justin-schroeder** [comment]
Seems worth resolving. Lots of times people initialize a ref with a null value and then swap it out for a true value once some async operation is complete, so it seems reasonable that we should handle this more gracefully.
