### ISSUE TITLE
Issue with importing genesis

### ISSUE THREAD

**Issue by Isidorev215** [formkit/formkit#787]
### Reproduction

https://github.com/Isidorev215/MinutesHub/tree/982dfa14cb5dab4cce30c289e94372562a6f2f19

### Describe the bug

In the documentation for installation and use of genesis, the instructions say to import genesis in this manner,
```
// formkit.config.js
import { generateClasses } from '@formkit/themes'
import { genesisIcons } from '@formkit/icons'
import genesis from '@formkit/themes/dist/tailwindcss/genesis'

export default {
  icons: {
    ...genesisIcons,
  },
  config: {
    classes: generateClasses(genesis),
  },
}
```
![image](https://github.com/formkit/formkit/assets/72921554/8d181a3c-8bd5-482d-ba13-6f49f315c370)

The import statement for genesis above 
`import genesis from '@formkit/themes/dist/tailwindcss/genesis` gave me the following error which prevented Formkit from mounting;

![image](https://github.com/formkit/formkit/assets/72921554/bd989b23-0c9f-4ba5-add8-03223581eddc)

However, when I appended `./node_modules/@formkit...` to the import path like so the error is resolved

`import genesis from './node_modules/@formkit/themes/dist/tailwindcss/genesis'`

This is quite different from the documentation

### Environment

• OS: Windows 10
• Browser: Chrome Version 114.0.5735.134 (Official Build) (64-bit)
• Node: 18.15.0
• npm: 9.6.6
• vite: ^4.3.9
• "@formkit/addons": "^0.17.3",
• "@formkit/icons": "^0.17.3",
•  "@formkit/themes": "^0.17.3",
•  "@formkit/vue": "^0.17.3",

**Comment by GustavoFenilli** [comment]
The import is wrong in the documentation, we will be fixing that, it should be `import genesis from '@formkit/themes/tailwindcss/genesis'`, it should work as long as you're using vite without a problem.

If you're using Nuxt there might be a TS error because of module resolution doesn't work well with the exports property, so for that case you need to change the `moduleResolution` from the `compilerOptions` at your `tsconfig.json` file.

**Comment by andrew-boyd** [comment]
The FormKit docs have been updated and the recommended way to install the Genesis theme is now to copy/paste the theme object into your own project as a starting point. In future releases the import object will no longer receive updates.
