### ISSUE TITLE
`state.valid` one step behind the form

### ISSUE THREAD

**Issue by SDRACK** [formkit/formkit#788]
### Reproduction

https://formkit.link/e49d3af4e95be83ed376cb90fe918d45

### Describe the bug

Hey all,

To demo in the playground example:

1) enter 1 char in the required field
2) the form should be valid, it's not
3) enter another char, it then becomes valid
4) clear the field with backspace - it should become invalid, but doesn't
5) add another char somewhere (either field), it becomes invalid 
(Or, to double the effect of step 5, re-add a char to the required field and the form will _then_ become invalid despite being valid again.)

We've also seen this using `#default="{ state }"` on the form node when plugging into our schema using `$state.valid`, but I'm not sure how to reproduce that in the playground.

I might be misunderstanding something, so please correct me if I'm using this wrong :) If not, do you know if there's a fix for this?

Thanks,

Steve.

### Environment

• OS: Ventura 13.3.1 (a)
• Browser Chrome 114.0.5735.133
• Version
"@formkit/icons": "^0.17.2",
"@formkit/pro": "^0.112.6",
"@formkit/themes": "^0.17.2",
"@formkit/vue": "^0.17.2",

**Comment by GustavoFenilli** [comment]
Well not sure why, but settled might be being called before the state is being changed, I would recommend instead to toRef + watch the state directly like so for now: https://formkit.link/e940e20c475f212a79e5bc0218da93d6

**Comment by justin-schroeder** [comment]
The issue you are experiencing here is that v-model is updated before the `state` and your v-model handler is being run synchronously before the validation rules have finished updating. The good news is validate state is already tracked for you. There are a number of ways to get that state out. If you want it as a stand alone ref, that’s easy enough to arrange:

Here we observe the `state.valid` reactive value: https://formkit.link/ea13a6cda4105ca551fa852366db3559

Here we listen directly to the settled and unsettled state of the ledger: https://formkit.link/83efec03dbe0c455a62486a59683f762

Here we use a ref on the form: https://formkit.link/e124bbd9e584ae598d86f47e5ab0dd3a

Good luck!

**Comment by SDRACK** [comment]
Great, thanks @justin-schroeder
