### ISSUE TITLE
DataPicker in schema dosen't have placeholder

### ISSUE THREAD

**Issue by zgurea1** [formkit/formkit#792]
### Reproduction

https://formkit.link/86bad6bdc1b9eb12dc3b9f41face9d07

### Describe the bug

Hi guys, when i am trying to generate a schema with datepicker, placeholder is missing.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
Placeholder requires the `overlay` prop: https://formkit.link/45513232aaba7468830116e84623da1b

Good luck 👍
