### ISSUE TITLE
How do you update the value of taglist? possible bug?

### ISSUE THREAD

**Issue by Youhan** [formkit/formkit#800]
### Reproduction

https://formkit.link/474a6a9cdd944dc394e579f03ef2252c

### Describe the bug

I tried to use `v-model` to to pass the value to taglist but also be able to change it later externally. As you can see in the playground example, setting an array of strings for the value joins them with comma as one tag.

I might be doing it wrong and not actually a bug. Please advise.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by sashamilenkovic** [comment]
@Youhan I'm currently working on a rewrite of all the dropdown family inputs (dropdown, autocomplete, and taglist). Early next week I'll have a release out (which I'll notify here), for a fix for this.

**Comment by J-tt** [comment]
@sashamilenkovic any update on this? Was excited to see taglist fits our use case perfectly but unable to use it because of this bug.

**Comment by sashamilenkovic** [comment]
@J-tt Fair question! Haha. We've been working on this for quite a while now. We are hoping to have this fix included with the release of Beta 18 which we are hoping to get out early next week.

**Comment by sashamilenkovic** [comment]
Closing in favor of https://github.com/formkit/formkit/issues/586
