### ISSUE TITLE
Transfer list drag-and-drop bugs

### ISSUE THREAD

**Issue by binaryfire** [formkit/formkit#801]
### Reproduction

https://formkit.com/inputs/transfer-list

### Describe the bug

Hi guys

The drag-and-drop functionality of the transfer list feels quite laggy on Chrome and Firefox. 

And if you drag too quickly or move up and down a few times while dragging, the dropzone doesn't always appear in the right place.

### Environment

Windows 11. Reproducible in both Chrome and Firefox.

**Comment by justin-schroeder** [comment]
Hmm, we’re using the browser’s native drag and drop functionality. It’s smooth in our test environments, but perhaps you can provide some information about your specs and a video of the behavior?

**Comment by binaryfire** [comment]
Hey @justin-schroeder. I’m seeing the issue on your demo page (https://formkit.com/inputs/transfer-list).

Can you reproduce it there? If not, I can record a vid.

**Comment by sashamilenkovic** [comment]
@binaryfire A vid would be great actually. That being said, sometime this month (hopefully), we'll be pushing out a rewrite of all drag and drop functionality for the transfer list and other pro inputs.

**Comment by justin-schroeder** [comment]
@binaryfire also would be interested if your drag and drop feels laggy here: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/drop_event#result

**Comment by binaryfire** [comment]
@justin-schroeder Feels fine on that page but there's only one element. 

This is a better test: [https://sortablejs.github.io/Sortable/](https://sortablejs.github.io/Sortable/). Everything works fine for me here. Buttery smooth, no lag. Touch works too.

**Comment by justin-schroeder** [comment]
Yea, the underlying API of sortable is different than what FormKit is using — sortable does not use the native drag/drop API. If youre able to provide a screencapture of what you are describing it would be super helpful 👍

**Comment by binaryfire** [comment]
@justin-schroeder They definitely use the native drag/drop api. The author breaks it down here, including how he added touch support: [https://github.com/SortableJS/Sortable/wiki/Sorting-with-the-help-of-HTML5-Drag'n'Drop-API/](https://github.com/SortableJS/Sortable/wiki/Sorting-with-the-help-of-HTML5-Drag'n'Drop-API/)

Would it be better to integrate Sortable for drag and drop? I'm guessing a custom solution would end up reinventing the same things they've done. Just a thought :)

Here's the video: https://www.youtube.com/watch?v=IDbbgpy-L1g

**Comment by justin-schroeder** [comment]
Oh sweet! My mistake. I thought they were one of the libraries that did `transformXY` — I stand corrected. We’re unlikely to use sortable as a direct dependency as we’re trying to keep our dependency supply chain completely clean (FormKit has no runtime dependencies) — but we may take a look at what they are doing. Thanks for the pointer.

**Comment by sashamilenkovic** [comment]
@binaryfire Thanks for the video
