### ISSUE TITLE
Touch support for drag and drop

### ISSUE THREAD

**Issue by binaryfire** [formkit/formkit#802]
### Reproduction

https://formkit.com/inputs/transfer-list

### Describe the bug

Hi guys

Drag and drop doesn't work on mobile / touch devices. You can reproduce this by visiting [https://formkit.com/inputs/transfer-list](https://formkit.com/inputs/transfer-list) on a phone and trying to drag transferred items.

It's a known issue with the HTML 5 Drag and Drop API. Some useful references:

- [https://docs.dndkit.com/#architecture](https://docs.dndkit.com/#architecture)
- [https://www.horuskol.net/blog/2020-08-15/drag-and-drop-elements-on-touch-devices/](https://www.horuskol.net/blog/2020-08-15/drag-and-drop-elements-on-touch-devices/)
- [https://github.com/rlemaigre/Easy-DnD](https://github.com/rlemaigre/Easy-DnD)

Is this something that will be fixed in an upcoming release? I'm interested in an Enterprise license but I build with a mobile-first approach and turn my apps in PWAs. So touch support is essential for me.

### Environment

iOS. Tested in both Safari and Chrome

**Comment by sashamilenkovic** [comment]
@binaryfire Sometime this month (hopefully), we'll be pushing out a rewrite of all drag and drop functionality for the transfer list and other pro inputs. This rewrite should include support for touch events.

**Comment by binaryfire** [comment]
@sashamilenkovic Nice, thanks!

**Comment by binaryfire** [comment]
Hi guys. Any news on this and https://github.com/formkit/formkit/issues/801? Need this for a mobile project

**Comment by sashamilenkovic** [comment]
@binaryfire Hey there. Unfortunately, we have not started working on this. Most of our effort the past couple of months has gone to Beta 18/RC-1 as well as a rewrite of the dropdown, autocomplete, and taglist inputs. Hopefully I'll have time to start working on it this week. As for a timeline, I'm not sure. Hopefully it's something that we can get out there in 2-3 weeks, but it's hard to say.

**Comment by binaryfire** [comment]
Hi guys, just pinging you again on this and https://github.com/formkit/formkit/issues/801.

I mentioned to @luan-nk-nguyen prior to buying an Enterprise license that I’m building for mobile and needed to know these issues would be addressed soon. He assured me it would be. That was in June.

As an Enterprise customer, it’s frustrating to see new features being released over the last 5 months while these problems still remain unaddressed.

**Comment by justin-schroeder** [comment]
@binaryfire we are also frustrated that these updates have not yet been released — but trust me when I say this is not due to inaction. We have multiple team members and the work is parallelized so when you see new features released it doesn’t necessarily mean there hasn’t been progress. In fact, this issue has been in progress for multiple months now. Not just the drag and drop, but an internal refactor of how drag/drop works on all our inputs that specifically spawned from your issue. The good news? Its getting very close to being released — we’ll follow up here as soon with good news.

**Comment by sashamilenkovic** [comment]
@binaryfire Hi Raj. Completely understand why you'd be frustrated. I have been working on fixing these transferlist bugs and touch support for drag and drop. In hindsight, I should have reached out to you at some point over the last few months to provide an update so you didn't feel left in the dark. Anyways, the good news is, touch support for drag and drop has been implemented as well as a fixes for critical bugs. I have a bit more QA to go through before publishing. Fingers crossed that we get this out by the end of the week.

**Comment by binaryfire** [comment]
@justin-schroeder @sashamilenkovic Thanks for the update. I don't like being the guy who nags about stuff like this but I hope you can appreciate how it's created a lot of unexpected delays for us internally. Look forward to the update and keep up the good work.

**Comment by sashamilenkovic** [comment]
@binaryfire Hey! Just wanted to keep you posted, we are now shooting to publish tomorrow.

**Comment by binaryfire** [comment]
@sashamilenkovic Awesome, thank you!

**Comment by sashamilenkovic** [comment]
@binaryfire We're working hard here. Not going to be able to get it out today. Looking good for tomorrow (I know I've said that before, forgive me, haha).

**Comment by sashamilenkovic** [comment]
@binaryfire Hey man! Unfortunately we ran into some issues with getting the transferlist out there with the newly published styles from https://themes.formkit.com/. It's going to take us a little more time to reconcile these styles. Shooting to get this sorted out early next week. Hope you have a good weekend.

**Comment by sashamilenkovic** [comment]
@binaryfire Hey! We just released the transferlist with touch support on [0.119.0](https://www.npmjs.com/package/@formkit/pro/v/0.119.0). Be sure to check it out. Please get back to me with any feedback and I'll be sure to address it.
