### ISSUE TITLE
Initial values are overriding with the initial values plugin

### ISSUE THREAD

**Issue by Nks** [formkit/formkit#808]
### Reproduction

https://formkit.link/b5741ced5019569440209fbae4807ef7

### Describe the bug

Using an example for the [initial values](https://formkit.com/essentials/examples#plugins) has unexpected behavior when data is already passed to the form.

For example, if the form already has the initial values, it should not clear the username field but has the password field predefined in the result value.

It also not affects the autocomplete field when the user clicks on the delete option the option is fully deleted from the result object instead of set to null

### Environment

• OS: MacOS
• Browser chrome
• Version: 114.0.5735.198 (Official Build) (arm64)

**Comment by justin-schroeder** [comment]
Sure, here’s a more appropriate plugin: https://formkit.link/d5c3d554d55dbe94984c48f826ae84f7

I’ll update the docs too.
