### ISSUE TITLE
Hydration issue on Nuxt3

### ISSUE THREAD

**Issue by paulvonber** [formkit/formkit#81]
**Describe the bug**
If textarea contains predefined value, on the first (SSR) load hydration fails, it's all good if the textarea initially is empty.
<img width="916" alt="image" src="https://user-images.githubusercontent.com/37245111/153730501-b8f0bb04-d3d2-40ca-b26e-6a11d94de320.png">

**Reproduction**
Please try to reproduce the issue using the FormKit playground. https://docs.formkit.com/playground
**Desktop (please complete the following information):**
 - OS: [macOS Monterey 12.1]
 - Browser [Chrome]
 - Version [98.0.4758.80 (Official Build) (arm64)]

**Comment by justin-schroeder** [comment]
Thanks for the report — I can duplicate the issue and will look to get this fixed in beta.3

**Comment by justin-schroeder** [comment]
FWIW — short term fix on this is to wrap offending inputs (or the form) in `<ClientOnly>` tags.

**Comment by silvio-e** [comment]
This is happening for me with a checkbox on Nuxt 3.0.0-rc.9.

**Comment by madsh93** [comment]
I am also getting hydration errors with Select in latest Nuxt rc.10 and @formkit/nuxt@next

**Comment by justin-schroeder** [comment]
If you guys can provide reproductions that would be helpful

**Comment by madsh93** [comment]
@justin-schroeder 

https://stackblitz.com/edit/github-dijrla-kavuiw?file=package.json

Heres a repro link.

The issue seems to come from importing the genesis theme in app.vue

`import '@formkit/themes/genesis'`

**Comment by justin-schroeder** [comment]
@madsh93 thank you for that reproduction! We can definitely work to get that fixed. Would you mind creating a new issue for this so it gets surfaced for an upcoming sprint? 🙏
