### ISSUE TITLE
Allow datepicker formats in date validation rules

### ISSUE THREAD

**Issue by zgurea1** [formkit/formkit#810]
### Reproduction

https://formkit.com/playground?css-framework=genesis&fkv=latest&fileTab=schema-formkit.vue&files=jc%5B%28%27name%21%27g-R.vue%27%7Eeditor%21%27%3CscripWsetup944consWg+%3D+%5B4*%28*1%24RPdOpickerVtimezone%3A1Europe%2FAmsIrdam7Que-fGatX1DD.MM.YYYY7labelPDO7namePdO7QidationPrequired%7CdO_afIr%3A2023-06-227placeholderPSelecIaz%C4%83+o+dat%C4%837overlay5true48%2944%5D4Cscript94%3CUL+typeJfGN%23defaultJHN%3AactionsJfalse1LSB+%3AgJgN%2F%3E*%3CprZwrap%3E%28H%29Cpre9CT9CU9%27%7Eadded%21true%29%5D*4881%5C%274%5Cn5X+7V18++9%3E4BchemaC%3C%2FGormH%28+QuZ%29IteJ%3D1L98%3CTN1+OaIP51QvalRfGkitTFGKitUImplOV1%2C*Wt+X%5C%21Ze+gsB%01gZXWVUTRQPONLJIHGCB987541*_&imports=jc%28%27name%21%27ImportMap%27%7Eeditor%21%27%28*+1vue%5C%211https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fvue%403%2Fdist%2Fvue.esm-browser.min.js0*%29*%27%29*%5Cn0%5C%271+0%0110*_

### Describe the bug

Hello, when I change the value format, the validation rule does not work.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
The date validation rules only handles ISO8601 dates — but it sorta does seem like it should also integrate better with value-format. Definitely worth looking into further.

**Comment by zgurea1** [comment]
Hi, i was playing with datapicker input and i was able to achieve the validation rule with min-date, but how can i add min-date attribute to schema?

https://formkit.link/381288b9e3fce158ce46db7b89569ec0
