### ISSUE TITLE
Autocomplete input: `data-complete` not set after refresh or first load with initial value

### ISSUE THREAD

**Issue by KoenCa** [formkit/formkit#816]
### Reproduction

https://formkit.com/playground?fkv=latest&fileTab=Playground.vue&css-framework=genesis&files=jc%5B%28%27name%21%27PWd.vk%27%7Eqitor%21%27%3Cscript9etupAG+ESM+importJare9upporteNfrom+URLJ%7Bhttps%3AGcdn...%7D5GXJwellXs9econdary+pWNfiTJ%7B.%2FOtherFiT.vk%7D.5HscriptA5%3CV8%3CY0typeBautocompTte_seTcQ-appearanceBopQ_jbelBY+Input_helpBqit+mzto+get9tartq_%3AopQsB%5B4161D4262D4363D0%5D_%3AvalkB3758%2FAHV5%3Csx9copqA%2F*5vanilj+CSS+can+go+here.5Keep9xs9copeNtoXvoiNmultipT+fiTs5overwriting+each+other+in+thzrender+output.5*%2F5HsxA%27%7Eaddq%21trk%29%5D0588408%28+jbelZ%22OpQ+5%5Cn6%22%2C+valkZ7%5C%278++9+sA%3E5B%3D7D+%29%2CG%2F%2FH%3C%2FJs+Nd+QtionTleVtempjteAWjygrounX+aYFormKitZ%3A+_70jlakueqedxtyTze+%01zxqkj_ZYXWVTQNJHGDBA9876540_&imports=jc%28%27name%21%27ImportMap%27%7Eeditor%21%27%28*+1vue%5C%211https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fvue%403%2Fdist%2Fvue.esm-browser.min.js0*%29*%27%29*%5Cn0%5C%271+0%0110*_

### Describe the bug

In the reproduction link you see that the `data-complete` attribute is not set on first load which I think it should, because it has an initial value? When you clear the selected option and select another one it is set correctly.

### Environment

• OS: [e.g. iOS]
• Browser: Arc (Chromium)
• Version: 0.17.4

**Comment by justin-schroeder** [comment]
Hi @KoenCa. This is actually working as intended. If your input has a validation rule it will be considered "complete". The specific rules of completeness are found here under the `context.state.complete` property:

https://formkit.com/api-reference/context#state
