### ISSUE TITLE
Autocomplete input: `:open-on-click="true"` together with `selection-appearance="option"` causes unintended behavior?

### ISSUE THREAD

**Issue by KoenCa** [formkit/formkit#817]
### Reproduction

https://formkit.com/playground?fkv=latest&fileTab=Playground.vue&css-framework=genesis&files=jc%5B%28%27name%21%27PlaygY.vj%27%7EeditX%21%27%3Cscrip9setupAH+ESM+impXtDarQsuppXTd+from+URLD%7Bhttps%3AHcdn...%7D5H+aDwell+aDsecondary+playgY+fiqD%7B.%2FOtherFiq.vj%7D.5JscriptA5%3CTmplaTA8%3CFXmKit0typeBautocompqT60seqcV-appearanceBopV60labelBFXmKi9Input60helpBedi9mQtxge9starTdZopen-on-clickBtrjZopVsB%5B4171G4272G4373G0%5DZvaljB3658%2FAJTmplaTA5%3CstyqA%2F*5WXkaY+sxtha9clicking+onzdoesn%229open+thQdropdown+%7Buncommen9txseQi9wXk%7D5*%2F5%2F*+5_ouTr%5Bdata-compqT%3D%22trj%22%5D+_wrapperz%2858poinTr-eventsNnone%3B5%295*%2F5JstyqA%27%7Eadded%21trj%29%5D0588408%28CN%22OpV+5%5Cn6%5C%277%22%2C+valjN8++9t+A%3E5B%3D6zlabelDs+G+%29%2CH%2F%2FJ%3C%2FN%3A+Qe+TteVtionXorYroundZ60%3A_.fXmkit-jueqlexo+zC+%01zxqj_ZYXVTQNJHGDCBA9876540_&imports=jc%28%27name%21%27ImportMap%27%7Eeditor%21%27%28*+1vue%5C%211https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fvue%403%2Fdist%2Fvue.esm-browser.min.js0*%29*%27%29*%5Cn0%5C%271+0%0110*_

### Describe the bug

On the autocomplete input when `open-on-click` is set to `true` and `selection-appearance` is set to `option` you can still open the dropdown by clicking on the label.

The workaround for this is to disabled pointer events on the label by using the `data-complete` attribute of the wrapper of the component which I do like this in my Tailwind theme:

```javascript
'autocomplete': {
    label: 'formkit-complete:pointer-events-none',
}
```

But my workaround only works partially because of the other bug I reported: https://github.com/formkit/formkit/issues/816

### Environment

• OS: MacOS
• Browser: Arc (Chromium)
• Version: 0.17.4

**Comment by justin-schroeder** [comment]
Thanks for the report 👍
