### ISSUE TITLE
Autocomplete input: options with labels that are numbers don't work

### ISSUE THREAD

**Issue by KoenCa** [formkit/formkit#818]
### Reproduction

https://formkit.com/playground?fkv=latest&fileTab=Playground.vue&css-framework=genesis&files=jc%5B%28%27name%21%27PH.vW%27%7Eeditor%21%27%3CscripGsetup8C+ESM+importAare+supporXd+from+URLjhttps%3ACcdn...%7D4CZwYlZsecondary+pH+filej.%2FOtherFile.vW%7D.4Dscript8qJ7%3CFormKit*type9autocompleXxsYecN-appearance9opNx_bY9FormKiGInputxhYp9ediGme+to+geGstarXdQen-on-click9trWQNs9%5B0161B0262B0363B*%5D547%2F8DJqV4DV%27%7Eadded%21trW%29%5D*4770*7%28+_bYT4%5Cn5%5C%276%2C+valWT7++8%3E49%3D5As+B+%29%2CC%2F%2FD%3C%2FGt+H_ygroundJXmp_X8NtionQx%3AopT%3A+Vstyle8WueXteYelZ+aA_lajA%7Bq4%3Cx5*%01xqj_ZYXWVTQNJHGDCBA9876540*_&imports=jc%28%27name%21%27ImportMap%27%7Eeditor%21%27%28*+1vue%5C%211https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fvue%403%2Fdist%2Fvue.esm-browser.min.js0*%29*%27%29*%5Cn0%5C%271+0%0110*_

### Describe the bug

In the autocomplete input providing options were the labels are numbers breaks it. I think the logic in FormKit expects it to be strings, because errors about `toLowerCase` are thrown in the console:

![CleanShot 2023-07-07 at 17 47 06](https://github.com/formkit/formkit/assets/17332418/f33f187e-bf6e-4351-861f-0a3027ac29d6)

My workaround is to convert my labels to strings before providing them to the autocomplete input. 

### Environment

• OS: MacOS
• Browser: Arc (Chromium)
• Version: 0.17.4

**Comment by justin-schroeder** [comment]
Yes, the labels need to be strings. That is part of of the type definition for the prop too.
