### ISSUE TITLE
@formkit/utils eq does not support regexp comparison

### ISSUE THREAD

**Issue by aegorx** [formkit/formkit#819]
### Reproduction

https://formkit.link/99095cd62c3a46b438f0136c67247a1e

### Describe the bug

The eq method is incorrect for RegExp results

This causes the validation property to fail to update under rules that contain RegExp

https://github.com/formkit/formkit/blob/4a2964e40496832ad9adf7182dd04f80f99a786f/packages/validation/src/validation.ts#L207

### Environment

• OS: MacOs ventura 13.2.1 (22D68)
• Browser chrome version 114.0.5735.198 (arm64)
• Version 0.17.x

**Comment by aegorx** [comment]
@GustavoFenilli can you pay attention to this issue?

**Comment by justin-schroeder** [comment]
Ok, pretty cheap/concise way to do a RegExp comparison, I’m adding this to the utils package, and calling it in eq in beta.18

```js
export function eqRegExp(x: RegExp, y: RegExp): boolean {
  return (
    x.source === y.source &&
    x.flags.split('').sort().join('') === y.flags.split('').sort().join('')
  )
}
```

**Comment by aegorx** [comment]
@justin-schroeder 

Thank you very much. I can understand what you mean. As a library, it should be the fastest and smallest. Since the validation of formKit supports array format, when I use matches in array format, the current eq will cause the rule to remain unchanged when the rule changes.

Ps: Originally used string matches, but string matches don't support flags.

https://github.com/formkit/formkit/blob/0d8eae96b5f9c82c977d9da97f954b732c971d11/packages/rules/src/matches.ts
