### ISSUE TITLE
Submit form programatically

### ISSUE THREAD

**Issue by paulvonber** [formkit/formkit#82]
Would be very beneficial if there was an option to submit form with external button (or just programatically), as in certain UI's buttons can be away from the form.
I tried the native HTML way (as in the example just to use id on the form and form attr on the button) but seems it doesn't work either.

FormKit Vue Playground link:
https://formkit.link/134e8d2be15b408633a66e2536d91c21

**Comment by justin-schroeder** [comment]
Great feature request. I think the goal here will be to do this via the FormKit plugin. In the context of a component instance (with reference to `$this`):

```vue
<template>
<FormKit
  type="form"
  id="myForm"
>
  <!-- ... -->
</FormKit>
</template>

<script>
export default {
  methods: {
    customSubmit () {
      this.$formkit.submit('myForm')
    }
  }
}
</script>
```

Or via composition api:


```vue
<template>
<FormKit
  type="form"
  id="myForm"
>
  <!-- ... -->
</FormKit>
</template>

<script setup>
import { getNode } from '@formkit/core'

getNode('myForm').submit() //
</script>
```

Open to suggestions/opinions on this API.

**Comment by madsh93** [comment]
@justin-schroeder That method seems very DX friendly. I have a quick question though.
Would this still be possible if the setup was like this?

-- Parent
  -- Component 1 (with Formkit)
  -- Component 2 (with submit button)

**Comment by justin-schroeder** [comment]
@madsh93 yes it would. Also there is a "native" HTML way to do this too. You give a form an `id`, then any button on your site can include the native `form` attribute and submit that form no matter where it is on the site. This would be how I would recommend doing it, but there is a bug in `<FormKit type="form">` that was preventing the `id` from being applied to the DOM — this is fixed already in beta.3 branch and you can see it working in this example (notice the version is set to "1.0.0-beta.3 (next)" in the version selector at the top of the page:

https://formkit.link/24f4a29dae91a28cf2c5c7c2170c3f2e

If you flip back to the 1.0.0-beta.2 you'll notice the id is not there in the rendered DOM:

Beta 3:
<img width="417" alt="image" src="https://user-images.githubusercontent.com/1950463/154336980-bb3375cb-5a41-453d-8b3b-e46ec349952d.png">

Beta 2:
<img width="380" alt="image" src="https://user-images.githubusercontent.com/1950463/154337031-22006b75-e1d3-4e4f-bb25-0c52b0bc60e1.png">

Anyway – still a work in progress on the other methods of submitting.

**Comment by dominikklein** [comment]
Will the `getNode('myForm').submit()` call return the same like the submit event on the form itself (so i think currently the form data)?

**Comment by jonathansousa** [comment]
In addition to `this.$formkit.submit('myForm')` could we get `this.$formkit.reset('myForm')` to put the form back to its initial state? I actually encounter that situation more often than the programmatic `submit`, although both crop up pretty frequently.

**Comment by justin-schroeder** [comment]
@jonathansousa, Yes (probably) lets open up a new issue about that. Determining what qualifies as an "initial state" is actually more tricky than it seems.

**Comment by nosizejosh** [comment]
@justin-schroeder `this.$formkit.submit('form')` always return undefined whether form submits successfully or validation errors prevents a successful submission. how can one retrieve submission status?

> Will the `getNode('myForm').submit()` call return the same like the submit event on the form itself (so i think currently the form data)?

**Comment by nosizejosh** [comment]
@justin-schroeder  do you have a working example especially of getNode with composition api? I have tried everything to make it work but keep getting undefined.  I have a case where the form is in a component and the submission happens in another component, so I need to get return value and i also need to be able to submit in a composition setup. Nuxt 3 and "@formkit/nuxt": "^1.0.0-beta.6",

> Great feature request. I think the goal here will be to do this via the FormKit plugin. In the context of a component instance (with reference to `$this`):
> 
> ```
> <template>
> <FormKit
>   type="form"
>   id="myForm"
> >
>   
> </FormKit>
> </template>
> 
> <script>
> export default {
>   methods: {
>     customSubmit () {
>       this.$formkit.submit('myForm')
>     }
>   }
> }
> </script>
> ```
> 
> Or via composition api:
> 
> ```
> <template>
> <FormKit
>   type="form"
>   id="myForm"
> >
>   
> </FormKit>
> </template>
> 
> <script setup>
> import { getNode } from '@formkit/core'
> 
> getNode('myForm').submit() //
> </script>
> ```
> 
> Open to suggestions/opinions on this API.

**Comment by justin-schroeder** [comment]
@nosizejosh https://formkit.link/325e75d8799123446193ebd4f070bc16

Calling submit() does not return anything. Its return signature is `void`. This only triggers the submit. If there are validation rules not yet complete only `@submit-raw` will be triggered but not the `@submit` handler. Inside the submit handler it is up to a developer to determine what a "successful" submission is. You are passed the data to do with what you please. Hope that makes sense!

**Comment by nosizejosh** [comment]
@justin-schroeder Thank you!

**Comment by nosizejosh** [comment]
@justin-schroeder I have a form in a modal and only the first submission saves to supabase. All other subsequent submissions don't save even though they show as successfully created. Please help me debug, I have tried everything and cant figure out why it doesn't submit other subsequent submissions unless the entire page is refreshed. 

Form resets just fine, so I can't figure out why subsequent submissions don't save unless the entire page is refreshed and then 
only the first submission will go through. 

```
const submitHandler = async () => {
    try {
        newTicketSuccess.value = false
        const loader = $loading.show();
        const { data: { value: { data: newTicket } }, error: { value: error } } = await useAsyncData('newTicket', async () => {
            return await client.from('Tickets').insert([newTicketFormData.value])
        })
        loader.hide();
        if (newTicket) {
            toast.success("Ticket Created");
            // set form submitt success to true
            newTicketSuccess.value = true
            // reset form
            getNode('create-ticket-form').reset()
            // hide modal if no createAnotherTicket
            if (!createAnotherTicket.value && newTicketSuccess.value) {
                $vfm.hide("newTicketModal")
            }
            // reset form submitt success to fale
            newTicketSuccess.value = false
        }
    } catch (error) {
        toast.error("Ticket Error: " + error.message);
    }
}
```
