### ISSUE TITLE
The sectionsSchema attribute is not reactive

### ISSUE THREAD

**Issue by aegorx** [formkit/formkit#820]
### Reproduction

https://formkit.link/143b8b3975a0c1cefec943cf1157b971 

### Describe the bug

The sectionsSchema attribute is not reactive

### Environment

• OS: MacOs ventura 13.2.1 (22D68)
• Browser chrome version 114.0.5735.198 (arm64)
• Version 0.17.x

**Comment by justin-schroeder** [comment]
@zgurea1 is correct. Section schema is intentionally non-reactive. We’d like to discourage people from changing the schema , but you can work around this by changing the key.
