### ISSUE TITLE
The data-invalid attribute value is incorrect

### ISSUE THREAD

**Issue by aegorx** [formkit/formkit#821]
### Reproduction

https://formkit.link/fc1bc0af19f36853a20b24c49729ca83

### Describe the bug

When a method in validationRules returns a Promise, the data-invalid attribute is always true while the input box is being typed

### Environment

• OS: MacOs ventura 13.2.1 (22D68)
• Browser chrome version 114.0.5735.198 (arm64)
• Version 0.17.x

**Comment by GustavoFenilli** [comment]
You mean for the first time that the input is created, before running the validation any change to that makes that input into a invalid state before running the validation rule?

**Comment by aegorx** [comment]
@GustavoFenilli 
Yes, I think this state and message should be consistent, otherwise use it to control the check style, the phenomenon is inconsistent.

**Comment by GustavoFenilli** [comment]
When you make any input change the input is considered invalid before being valid, as to not trigger submit behaviour before the validation runs, not sure if the `data` attributes could be treated different as to make styling UX better @justin-schroeder what do you think of this one?
