### ISSUE TITLE
Multi-step: Inline validation rules causes "Maximum recursive updates exceeded" warnings and slow rendering

### ISSUE THREAD

**Issue by benlind** [formkit/formkit#829]
### Reproduction

https://github.com/benlind/formkit-repro-max-recursive-updates

### Describe the bug

(This sounds related to #514 and #542.)

When using the multi-step plugin and inline validation rules, Vue emits a bunch of warnings like this:

> [Vue warn]: Maximum recursive updates exceeded in component <FormKitSchema>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.

And when there are many such validation rules on one form, rendering the form is slow.

Example code:

```vue
<template>
  <FormKit
    type="form"
  >
    <FormKit
      type="multi-step"
    >
      <FormKit
        type="step"
        name="personalInfo"
      >
        <!-- To "fix" the bug, replace `{ validPhone }` with `rules` -->
        <FormKit
          type="tel"
          name="phone"
          label="Phone"
          :validation="[
            ['validPhone'],
          ]"
          :validation-rules="{ validPhone }"
          :validation-messages="{
            validPhone: 'invalid phone',
          }"
        />
      </FormKit>
    </FormKit>
  </FormKit>
</template>

<script lang="ts" setup>
function validPhone (node) {
  return true
}

const rules = { validPhone }
</script>
```

While using the `rules` proxy does solve the issue, I'd rather not have to instruct all future devs to beware of this specific situation.

Note, I cannot reproduce this [on the playground](https://formkit.link/6eac771454b983809658555411af263f). But I created a [repro repository](https://github.com/benlind/formkit-repro-max-recursive-updates) that demonstrates this with 0.17.3.

### Environment

• OS: MacOS
• Browser: Chrome
• Version: 0.17.3

**Comment by benlind** [comment]
Also, if I use the object proxy method (`rules`), TypeScript complains:
<img width="537" alt="Screenshot 2023-07-11 at 7 30 03 PM" src="https://github.com/formkit/formkit/assets/180348/8e597759-ce88-45ce-94a8-334e1358c73b">

**Comment by GustavoFenilli** [comment]
If you update to the latest `0.17.4` does the problem persist?

**Comment by benlind** [comment]
@GustavoFenilli , unfortunately yes. I updated the repo to use 0.17.4 and still get the warning.

**Comment by justin-schroeder** [comment]
This is fixed in beta 18 👍 Thanks for the report.
