### ISSUE TITLE
Enhancement: Add alpha_spaces as available validation function

### ISSUE THREAD

**Issue by madsh93** [formkit/formkit#83]
It would be nice if support for alpha spaces was added, similar to what vee-validate provides.
https://vee-validate.logaretm.com/v2/guide/rules.html#alpha-spaces

In my case I need it to validate first names, as it is common to have a multiple first names in my country.

**Comment by justin-schroeder** [comment]
Seems like a reasonable request. For now I would suggest the `matches`. For example:

https://formkit.link/eb4f5f1ff5eda062bb9e92f640fa77cc
