### ISSUE TITLE
Zod plugin - transform method not applied

### ISSUE THREAD

**Issue by damorjuancruz** [formkit/formkit#833]
### Reproduction

[FormKit Playground](https://formkit.com/playground?fkv=latest&fileTab=Playground.vue&css-framework=genesis&imports=jc%28%27name%21%27ImportMap%27%7Eeditor%21%27%280vue*vue%403%2Fdis7vue.esm-browser.mi95%2C0zod*zod%403.21.4%2F%2Besm56%296%27%29*%5C%218https%3A%2F%2Fcd9delivr.ne7npm%2F06+85%5C%276%5Cn7t%2F8+59n.js%01987650*_&files=jc%5B%28%27name%21%27Playground.vue%27%7Eeditor%21%27%3Cscrip4setup%3EDref%29+G%22vue%22Dz%29G%22zod%22DU+%29+G1%40f_kit%2Fzod1%3B00cons4L4%3D+refVE0cons4%5Bz59M%5D8U%7Bz.objectV*iWQz.string%7B%7D.min%7B3%7D%2C0E.transf_%7BViWEqVfooQ%22bar%22E%7D9%7BXs%7Dq%28*Lt.X8+Xs0E0Bscript%3E00%3CT*%3CCt*-type7f_R%3Aplugins7%5Bz5%5DR%40submit7M1*w-%3CCt*--name7iWR-type7textR-label7C4IWR-help7edi4me+to+ge4startedR%2FwBCtw*Should+be%3A6%28*fooQbar0%29*BprY0Actual+Lt%3A6%28%28+JSON.stringify%7BLt9null92%7D+%29%296BT00%27%7Eadded%21true%29%5D*0--++0%5Cn1%5C%274t+5odPlugin6*%3CprY07%3D18+%3D9%2C+B%3C%2FCF_KiD0impor4%28E%29%7DGfrom+LresulMsubmitHandlerQ%3A+R1*-TtemplatYU+createZ5V%7B%28WnputXvalueYe%3E_ormq8%3E+w%3E*%01wq_YXWVUTRQMLGEDCB98765410-*_)

### Describe the bug

When using the zod plugin, the `transform` is not applied. If used with typescript though, the type does get applied, so the values received in the submit handler are not correctly typed.

### Environment

• OS: Windows 10
• Browser: Chrome
• Version: 114

**Comment by GustavoFenilli** [comment]
I'm not sure about the syntax you're using there, but looks fine like this for me https://formkit.link/30760487955eeac09fd881977d9c855f

**Comment by damorjuancruz** [comment]
Your example shows that the `transform` method is executed but, if you pass a handler to the `createZodPlugin` function, the values received there are not the transformed values:

**Comment by GustavoFenilli** [comment]
Oh now I see what you mean, the transformation is done but not applied at the submit. @andrew-boyd what do you think?

As a workaround while we take a look at it, you can use the `submit` hook for transformations.

**Comment by andrew-boyd** [comment]
@damorjuancruz — Spot on with your analysis of the issue. This will be fixed in the next release:

https://formkit.link/2c8286fbd70713b8eaf1c3c0921c97b0

**Comment by damorjuancruz** [comment]
Thanks!
