### ISSUE TITLE
Cannot use v-for with multi-step steps

### ISSUE THREAD

**Issue by shurth** [formkit/formkit#835]
### Reproduction

https://formkit.link/d6338e5efe22e9e4c46553eb475cdec0

### Describe the bug

Using v-for to create a dynamic number of steps in a multi-step results in the following error:

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'label')
    at index.mjs:635:33
    at Array.map (<anonymous>)
    at createSSRStepsFromTabs (index.mjs:632:34)

Looking at the debugger, the tab props are null, and the actual steps are listed in its children property.

Note - the reproduction link has the appropriate code but doesn't render properly. Same issue as on the marketing site demos.

### Environment

Nuxt 3.x (SSR)

**Comment by andrew-boyd** [comment]
This will be fixed in beta.18 

https://formkit.link/dfe585f9e95e71329df90c0652696dd4
