### ISSUE TITLE
HTML in help text

### ISSUE THREAD

**Issue by ancaverniceanu** [formkit/formkit#836]
### Reproduction

https://formkit.link/e2a74dacce0a240dd09c3fb94d802cb1

### Describe the bug

Hi, is there a proper way to include HTML in the help, when using FormKitSchema? Thank you!

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by ancaverniceanu** [comment]
All the forms are customized by editors. For the help field, editors have access to a WYSIWYG editor in our system so they can add whatever they want. The HTML should not replace the help. The entire help is HTML.

**Comment by GustavoFenilli** [comment]
@justin-schroeder any idea on how to make the help accept a pure html string? was thinking about it but not sure ( I was thinking of a helper component that renders html using v-html and using that in place of the help schema )

**Comment by justin-schroeder** [comment]
Sure — with a big caveat that *it is a huge security risk to provide unsanitized user data as HTML* you can do this:

https://formkit.link/29015274b0b8c8978b6f34e4ee20b069
