### ISSUE TITLE
Provide API for date utility functions

### ISSUE THREAD

**Issue by justin-schroeder** [formkit/formkit#845]
### Reproduction

https://formkit.link/ba56ab8e550cd5204bbb36660d27c908

### Describe the bug

Issues like #844 are helpful to highlight the difficulties of working with dates. It’s very easy, as that example shows, to provide a date to a datepicker that is immediately mutated. It would be helpful if we exported and open-sourced the date utility functions that are at work behind the scenes of the datepicker so users can provide well formatted dates and generally make date work easier.

### Environment

• OS: macOS
• Browser: All
• Version: 0.17.5

**Comment by andrew-boyd** [comment]
This is resolved with the release of [Tempo](https://tempo.formkit.com) — an open-source date library that powers the internals of the FormKit `datepicker` input.
