### ISSUE TITLE
Sections-schema button onClick within custom label triggers as submit button

### ISSUE THREAD

**Issue by the14thsky** [formkit/formkit#846]
### Reproduction

https://formkit.link/c3380510828980e4c17fe0dfdfdadb65

### Describe the bug

While this issue is similar to the solved issue [https://github.com/formkit/formkit/issues/541], I am unable to find ways to use button or NuxtLink in the `sections-schema` for `label` that supposes to trigger a function but instead, it triggers a form submit. Even if `$el` is `div`, nothing triggered.  Or did I miss out anything else from documentation..? Please check the reproduction.

### Environment

- Beta 17 with Tailwind CSS
- Playground environment on Safari browser

**Comment by GustavoFenilli** [comment]
This is the default behaviour of `button` from HTML5 inside any form will trigger a submit, unless you add `type: 'button'`.

**Comment by justin-schroeder** [comment]
@the14thsky in HTML (this is not specific to FormKit) a `<button>` has a default `type` of `submit`. You can avoid this by just changing the `type` attribute to `button`:

https://formkit.link/2a4aceda9a8c13f8741ad713237513c0

**Comment by justin-schroeder** [comment]
dang it...haha fenilli beat me to it

**Comment by the14thsky** [comment]
Thanks! How about `<NuxtLink>` or `<RouterLink>` within sections-schema for Vue/Nuxt? Is there another way without needing a separate function in the script section?

**Comment by the14thsky** [comment]
@GustavoFenilli I tried this below to use NuxtLink based on Nuxt 3 and FormKit documentation which explains about $cmp but nothing works when I click "Terms of Service" link. Is there something amiss?

`<FormKit 
  type="checkbox" 
  label="I accept the " 
  name="terms_acceptance" 
  :value="false" 
  validation="required" 
  :sections-schema="{
    label: {
      children: [
        '$label',
        {
          $cmp: 'NuxtLink',
          props: {
            to: '/auth/login',
            class: 'text-green-500 underline-offset-4 hover:underline',
          },
          children: ' Terms of Service'
        },
      ],
    },
  }"
/>`

**Comment by the14thsky** [comment]
> @the14thsky in HTML (this is not specific to FormKit) a `<button>` has a default `type` of `submit`. You can avoid this by just changing the `type` attribute to `button`:
> 
> https://formkit.link/2a4aceda9a8c13f8741ad713237513c0

@justin-schroeder I reproduced your exact codes in my local using Visual Studio Code and it works perfectly except one declaration issue which I just found at this `sections-schema` with `$el: 'button'` and the callable function for `onClick`.

Type '{ $el: string; attrs: { type: string; onClick: () => void; class: string; }; children: string; }' is not assignable to type 'FormKitSchemaNode'.
Type '{ $el: string; attrs: { type: string; onClick: () => void; class: string; }; children: string; }' is not assignable to type 'FormKitSchemaFormKit'.ts(2322)
index.d.ts(1790, 5): '$formkit' is declared here.

**Comment by GustavoFenilli** [comment]
> 

looks fine to me, can you create a reproduction?

**Comment by the14thsky** [comment]
@GustavoFenilli I finally created a reproduction with simple installation of Nuxt 3, Tailwind CSS and FormKit. It is still not working for `NuxtLink` within `sections-schema` for label. Please check the link below.

[https://stackblitz.com/edit/nuxt-starter-9rqjga?file=pages%2Fabout.vue](https://stackblitz.com/edit/nuxt-starter-9rqjga?file=pages%2Fabout.vue)

**Comment by GustavoFenilli** [comment]
Firstly the `$cmp: 'button'` is not valid, it should be `$el` and use `attrs` and not `props`.
About the NuxtLink it looks like it is not a global component? `Failed to resolve component: NuxtLink`. @andrew-boyd you understand nuxt better than I do.

Maybe nuxt do some magic to not have globally available but available when you use it, might be worth adding as global component, otherwise you can use the raw to pass as a library in this case.

**Comment by the14thsky** [comment]
@GustavoFenilli well, I have tried `$el` and `attrs` for button but upon using `onClick: handleClick`, there is declaration issue despite that it is working. It said this type is not assignable to `FormKitSchemaNode` and `FormKitSchemaFormKit` as I have mentioned earlier.

```
Type '{ $el: string; attrs: { type: string; onClick: () => void; class: string; }; children: string; }' is not assignable to type 'FormKitSchemaNode'.
Type '{ $el: string; attrs: { type: string; onClick: () => void; class: string; }; children: string; }' is not assignable to type 'FormKitSchemaFormKit'.ts(2322)
index.d.ts(1790, 5): '$formkit' is declared here.
```

However, `$cmp: 'button'` apparently seems fine and functioning. No declaration issue. Otherwise you might want to fix the declaration issue for using `$el: 'button'` with `onClick` under `attrs`.

Regarding the `NuxtLink`, this component is part of Nuxt's built-in routing system. Similarly, `RouterLink` is for Vue and `Link` is for React. I think `NuxtLink` is already globally available to all pages or components but seemingly not to FormKit's Schema. Could you or @andrew-boyd kindly take a look into this?

**Comment by GustavoFenilli** [comment]
For the case of `$el` and declaration issue I couldn't reproduce in the nuxt stackblitz you send, are you only having that problem in your local build? if so what version you have?

For the next case can you open a new issue se we can track it better?

**Comment by the14thsky** [comment]
I don't think Stackblitz for Nuxt has code highlighting ability as it looks no issue to me too unlike my Visual Studio Code v1.80.2 which has detected this declaration issue. Ok going to open this as a new issue.
