### ISSUE TITLE
getNode doesn't work when the node id is auto generated

### ISSUE THREAD

**Issue by comhon-project** [formkit/formkit#848]
### Reproduction

https://formkit.link/5d4245f4ea01f21ecf5337cba1b20aca

### Describe the bug

when using getNode() on a node that has a custom defined id, the node is found but 
when using getNode() on a node that has a auto generated id, the node is not found.

### Environment

• Ubuntu
• firefox
• formkit v0.17

**Comment by GustavoFenilli** [comment]
Even tho it is a bug and I think auto generated IDs should be placed in the map for lookup ( am I correct @justin-schroeder ?), what would be your use case where you need to get a node with an auto generated id?

It is not the most used case as its most likelly that you need to specify the ID for a case where you need it to be unique identifiable to get the correct node.

**Comment by comhon-project** [comment]
in my case I can specify an id so it's not a big deal, but it looked like a bug so I reported it :)

**Comment by justin-schroeder** [comment]
Yeah sorry, this is intentional so we dont fill the registry with nodes. Only explicitly named ids end up in the registry.

![image](https://github.com/formkit/formkit/assets/1950463/9ecddacf-4ffd-4c77-9fb6-61c9deb4d1e1)
