### ISSUE TITLE
Radio does not accept null values (similar for checkbox & select)

### ISSUE THREAD

**Issue by tosling** [formkit/formkit#85]
**Describe the bug**
When using `null` values in `options`-prop, the inputs fallback to HTML default behavior as if no value was set. 

I would actually expect, that `null` can be used as value if explicit defined.

Maybe I'm expecting too much here, since `null` is not a typical value for HTML elements, but from the JS perspective I'd rather expect `null` than "on".

**Reproduction**
https://formkit.link/b6a5c9100aff1f93c43b99a50962fefe

**Desktop (please complete the following information):**
- OS: Mac 11.6.2
- Browser: Chrome 98.0.4758.80

**Comment by justin-schroeder** [comment]
Fair question. Vue is actually the thing making this work the way it does since it sees the `null` (and `undefined`) as a no op attribute value.

I dont think it is asking too much however — one of the goals of this project is to smooth out some of those inconsistencies and make things "just work".

**Comment by lavolpecheprogramma** [comment]
Hi,
i've noticed that the list field doesn't accept null or undefined live value.
there is any chance to fix it?

Thanks in advice!

**Comment by justin-schroeder** [comment]
@lavolpecheprogramma try the upcoming beta.7 (install `@next` tag) if that doesn’t work make a playground showing the issue and I’ll take a look

**Comment by lavolpecheprogramma** [comment]
hi @justin-schroeder,
here is a playground with the issue: https://formkit.link/c908fd82f86f78032d7aa8629ac5ed73
A use case can be an edit page with data received from an API, and this data can contain null or undefined values (all types of input can receive this initial data in my opinion).

Thanks a lot for your hard work, formkit rocks!

**Comment by justin-schroeder** [comment]
> A use case can be an edit page with data received from an API, and this data can contain null or undefined values (all types of input can receive this initial data in my opinion).

Yes they should all be able to receive undefined as a value, but the options have to be a valid type or it will throw an exception (array of strings, pojo, or array of objects with label/value pairs).

The good news is I just published the `@next` tag with a fix for this bug. You can now specify *any* option value type for a list, checkbox, or radio.

```js
const options = [
  { label: 'Nothing', value: null },
  { label: 'Object' , value: { my: 'object' }},
  { label: 'Number', value: 123 }
]
```

These are all now valid 🎉

**Comment by justin-schroeder** [comment]
Here's a playground example (might need a hard-refresh to get the latest `@next`): https://formkit.link/f445b27441d6eb6850fa17436de8421f

**Comment by andrew-boyd** [comment]
Because we had to deprecate beta.7 use this playground to view it using beta.8: https://formkit.link/02a4894b916eef2aadfd3529022f06c9

**Comment by lavolpecheprogramma** [comment]
> https://formkit.link/c908fd82f86f78032d7aa8629ac5ed73

Hi @andrew-boyd and @justin-schroeder ,
i don't know if you have a look at this playground, it's a related issue on text field with undefined or null value.
Do you prefer to open a new issue to track this issue?

Thanks you very much for your hard work!
