### ISSUE TITLE
regression from 17.4 -> 17.5 "Cannot perform 'get' on a proxy that has been revoked"

### ISSUE THREAD

**Issue by davidAtInleague** [formkit/formkit#852]
### Reproduction

https://stackblitz.com/edit/vitejs-vite-lmt7q8?file=src%2FApp.vue

### Describe the bug

typing into a form element throws the following error:
```
@formkit_vue.js?v=1a29f680:3773 Uncaught TypeError: Cannot perform 'get' on a proxy that has been revoked
    at Object.listener (@formkit_vue.js?v=1a29f680:3773:12)
    at @formkit_vue.js?v=1a29f680:396:20
    at Array.forEach (<anonymous>)
    at Object.emitter [as _e] (@formkit_vue.js?v=1a29f680:394:33)
    at emit$1 (@formkit_vue.js?v=1a29f680:454:11)
    at Proxy.<anonymous> (@formkit_vue.js?v=1a29f680:952:65)
    at commit (@formkit_vue.js?v=1a29f680:1025:8)
```

This appears to be a regression between 17.4 -> 17.5. Changing the stackblitz's deps to exactly 0.17.4 reverts to the non-erroring behavior.

### Environment

• OS: ubuntu
• Browser chrome
• Version 114

**Comment by justin-schroeder** [comment]
Thanks for the reproduction. I can duplicate the issue — in the meantime workarounds:

- Use string syntax
- OR use array syntax but dont declare it inline (create a variable in your script block and use that)
