### ISSUE TITLE
`formkit-icon` class doesn't respect `config.rootClasses`

### ISSUE THREAD

**Issue by DamianGlowala** [formkit/formkit#859]
### Reproduction

n/a

### Describe the bug

1. Set the `config.rootClasses` to `() => ({})`
2. Add `<Formkit type='checkbox' icon='...' />` component with an icon of your choice.
3. Observe how the `formkit-icon` class is present in the HTML markup.

### Environment

n/a

**Comment by justin-schroeder** [comment]
Thanks! This is fixed in beta.18
