### ISSUE TITLE
Datepicker loses active state briefly when clicking calendar button (Safari only)

### ISSUE THREAD

**Issue by sashamilenkovic** [formkit/formkit#864]
### Reproduction

https://formkit.com/playground?css-framework=genesis&fkv=latest&fileTab=datepicker-basic.vue&files=jc%5B%28%27name%21%27C-basic.vue%27%7Eeditor%21%27%3CE9%3C5+HformN%23default26N%3Aactions2false0I51**HC7name2d47label2ABG7placeholder37help3+to+book+yourLB.7overlay1*%2FIprJwrap%3E%286%298pre985M8EM%27%7Eadded%21true%29%5D*++0%5C%271D*2%3D032SelectLG4ate5FormKit6%28+valuJ%29701**8%3C%2F9%3E1BppointmentCd4pickerD%5CnEtempl4G+d4Htype2I9*%3CJe+L+aM%3EDN0+%01NMLJIHGEDCB9876543210*_&imports=jc%28%27name%21%27ImportMap%27%7Eeditor%21%27%28*+1vue%5C%211https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fvue%403%2Fdist%2Fvue.esm-browser.min.js0*%29*%27%29*%5Cn0%5C%271+0%0110*_

### Describe the bug

When the datepicker is focused, and the user clicks the "calendar" button , the input loses its active state briefly.

### Environment

• OS: [e.g. iOS]
• Browser [safari]
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
This is fixed in the `@next` tag of `@formkit/pro`.
