### ISSUE TITLE
Initial Form state is `dirty` when FormKit input is created by nested component

### ISSUE THREAD

**Issue by andrew-boyd** [formkit/formkit#870]
Including an input via an imported component results in the form state being `dirty`. If you move the input inline rather than being included via a custom component then the form state is clean as expected.

FormKit Vue Playground link:
https://formkit.link/a6ee4c75baa7eeeb92ec1c7a18d08488

**Comment by justin-schroeder** [comment]
So I think it *might* be related to the playground’s mechanism of importing? When using vite I cannot duplicate the issue:

https://stackblitz.com/edit/vitejs-vite-zdzosl?file=src%2FApp.vue,src%2FNestedComponent.vue

**Comment by unr** [comment]
I see this got marked as closed -- is there a fix somewhere?

I'd love to try this fix locally on our Nuxt project where this issue is occuring.

**Comment by chasegiunta** [comment]
@andrew-boyd @justin-schroeder can this be reopened?
