### ISSUE TITLE
File remove message

### ISSUE THREAD

**Issue by sungeunl** [formkit/formkit#874]
### Reproduction

,

### Describe the bug

!(https://github.com/formkit/formkit/assets/114973152/ad6357a3-4679-4020-8844-3cfd20572455)

Thank you for making a great app.

The file removal button message always says remove and I want to customize it. 
( to replace the icon , something else... )

Is there any solution for this problem ?

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome]
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
These strings are automatically translated for you based on the selected locale. for example: https://formkit.link/ddd11d774d95586ddf62d1fd27c230ab

If you want to explicitly replace a given string, you can do so by customizing the `ui` message for the relevant key:

https://formkit.link/f9d1372e7cd0396334229714b0ef2080

**Comment by sungeunl** [comment]
Thank you so much.
