### ISSUE TITLE
Generic type 'DefineComponent' requires between 0 and 12 type arguments.

### ISSUE THREAD

**Issue by aegorx** [formkit/formkit#876]
### Reproduction

https://formkit.com/

### Describe the bug

Generic type 'DefineComponent' requires between 0 and 12 type arguments.

../../node_modules/.pnpm/@formkit+vue@0.18.0-94f33ac/node_modules/@formkit/vue/dist/index.d.ts:145:36 - error TS2707: Generic type 'DefineComponent' requires between 0 and 12 type arguments.

145  export declare const FormKitIcon: DefineComponent<    {
                                       ~~~~~~~~~~~~~~~~~~~~~
146  icon: {
    ~~~~~~~~
...
176  iconLoaderUrl: (iconName: string) => string;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
177  }, {}>;
    ~~~~~~~


    "@formkit/core": "0.18.0-94f33ac",
    "@formkit/vue": "0.18.0-94f33ac",
    "vite": "^3.2.7",
    "vue": "^3.3.4",
    "typescript": "^5.1.6"

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
Please provide a reproduction.

**Comment by aegorx** [comment]
@justin-schroeder Sorry, this may be caused by a mismatch of my local vue version.

**Comment by andrew-boyd** [comment]
Thanks for the follow-up! Closing this one for now.
