### ISSUE TITLE
Enhancement: Allow appending classes to form submit button

### ISSUE THREAD

**Issue by olivervorasai** [formkit/formkit#88]
**Describe the bug**
Allow the addition of a user defined class on the auto-generated submit button when using `<FormKit type="form">`.

**Reason**
In my case, I have a pre-existing global css class that defines the style of a button for the entire site. This button could be for forms or for general use cases. But, in general, all buttons should look the same.

**Suggested Solution**
Add an `action-class` prop on `<FormKit>`. Like so:

```vue
<template>
    <FormKit
        type="form"
        action-class="my-already-existing-class"
    >
        <FormKit type="text" name="name" label="Name" validation="required" />
    </FormKit>
</template>
```

**Current Workaround**
I can work around this by doing the following:

```vue
<template>
    <FormKit
        type="form"
        :actions="false"
    >
        <FormKit type="text" name="name" label="Name" validation="required" />
        <FormKit
            type="submit"
            label="Submit"
            input-class="$reset my-already-existing-class"
        />
    </FormKit>
<template>
```

However, error messages from the form validation will appear below the submit button instead of above it.

Please let me know if there are better solutions to this or if I missed anything. Thank you!

**Comment by olivervorasai** [comment]
I have just realized that there is a `submit-attrs` prop that is intended for this this use case. But I am unsure how to use this to add a class to the submit button.

**Comment by justin-schroeder** [comment]
Hi @olivervorasai — good work digging up the `submit-attrs`. here's an example of how you could use it:

https://formkit.link/49a96aa657d3e84a846782d9e87560c9

Good luck!
