### ISSUE TITLE
Genesis Pro 0.114 - `unexpected identifier`

### ISSUE THREAD

**Issue by Tragio** [formkit/formkit#884]
### Reproduction

n/a

### Describe the bug

I'm using SASS on my project and importing the Formkit Genesis and Formkit Genesis Pro CSS.

On the 0.114 version, I get a critical error on building. 0.113 is working fine. I beautified the code to see what was happening and is using an `unexpected identifier` `&[data-disabled]`.

![CleanShot 2023-08-13 at 12 02 16](https://github.com/formkit/formkit/assets/5109593/2a03b949-0ace-4931-a677-0fdf6843c27b)

![CleanShot 2023-08-13 at 12 08 57](https://github.com/formkit/formkit/assets/5109593/5e72bec8-6f91-44f8-a4cf-fc8d7295ce67)

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by andrew-boyd** [comment]
@Tragio We just published `0.114.1` which fixes this. Thank you for the report!
