### ISSUE TITLE
Cannot import language code 'tet'

### ISSUE THREAD

**Issue by joshbrooks** [formkit/formkit#885]
### Reproduction

N/A

### Describe the bug

We've got translations for the [Tetum](https://github.com/formkit/formkit/blob/master/packages/i18n/src/locales/tet.ts) language in main

But the code does not show up in the `dist`
The same occurs with `lv` which was added around the same time. 

They are not listed in the index file: packages/i18n/src/index.ts, maybe this was overlooked when they were added

### Environment

FormKit 0.18.0

**Comment by justin-schroeder** [comment]
This is now published in 0.18.1 — thank you!
