### ISSUE TITLE
How can you render the actual html from <formkit> in vitest? 

### ISSUE THREAD

**Issue by glennovische** [formkit/formkit#887]
### Reproduction

-

### Describe the bug

In using nuxt 3 and vitest to test my components.

```
    test('calls pincodeSubmit on form submission', async () => {
      const pincodeSubmitSpy = vi.spyOn(wrapper.vm, 'pincodeSubmit');
      await wrapper.find('input').trigger('submit.prevent');
      expect(pincodeSubmitSpy).toHaveBeenCalled();
    });
```

searching for the input is not possible because the formkit component is just rendered as <formkit> instead of the actual html?

How to get this working in my tests?

### Environment

Nuxt 3 
Vitest

**Comment by justin-schroeder** [comment]
We use vitest ourselves, checkout any of our tests for examples on how to do this: https://github.com/formkit/formkit/tree/master/packages/vue/__tests__/inputs

**Comment by glennovische** [comment]
@justin-schroeder Thanks for the response, I have looked into the tests as an example and I don't get it get it working. 

I used the  `import { FormKit } from '@formkit/vue';`

this imports the definition:
`/**
 * The root FormKit component.
 * @public
 */
export declare const FormKit: DefineComponent<    { ..... etc`

 In the formkit test the formkit definition is:
    
    `/**
 * The root FormKit component. Use it to craft all inputs and structure of your
 * forms. For example:
 *
 * ```vue
 * <FormKit
 *  type="text"
 *  label="Name"
 *  help="Please enter your name"
 *  validation="required|length:2"
 * />
 * ```
 *
 * @public
 */
export const formkitComponent = defineComponent(setup as any, {
  props: runtimeProps as any,
  inheritAttrs: false,
}) as FormKitComponent
....`
    
    
  In my vitest I want to create a wrapper like:
  
  `wrapper = mount(Pincode, {
      global: {
        components: {
          PrevNextButtons: PrevNextButtons,
          FormKit,
        },
        plugins: [
          createTestingPinia({
            createSpy: vitest.fn,
          }),
        ],
      },
    });

    console.log(wrapper.html());`
    
    I cant defineProps or assign props to Formkit
    
    Any Ideas?

**Comment by justin-schroeder** [comment]
You need to register the FormKit plugin in your test. For example:

```ts
import { plugin, defaultConfig } from '@formkit/vue'
describe('some formkit inputs', () => {
  it('can render a text input', () => {
    const wrapper = mount(FormKit, {
      props: {
        type: 'text',
        value: 133,
      },
      {
        global: {
         plugins: [[plugin, defaultConfig]],
        }
      },
    })
    expect(wrapper.find('input').exists()).toBe(true)
  })
})
```

Of course you could render at template component with pinia or other plugins too.
