### ISSUE TITLE
Support array of objects class definition syntax

### ISSUE THREAD

**Issue by innocenzi** [formkit/formkit#89]
Vue supports [defining classes with an array that contains both strings and objects](https://vuejs.org/guide/essentials/class-and-style.html#binding-html-classes): 

```vue
<input
	type="submit"
	:class="[
		'flex justify-center w-full px-4 py-2 text-sm font-medium text-white transition-colors border border-transparent rounded-md shadow-sm',
		{
			'bg-brand-600 hover:bg-brand-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-brand-500': !form.processing,
			'bg-brand-500 cursor-not-allowed': form.processing
		}
	]"
	v-text="$t('auth.login.attempt_sign_in')"
/>
```

It seems that FormKit doesn't support this syntax: [see an example on the playground](https://formkit.com/playground?fkv=1.0.0-beta.2&fileTab=Playground.vue&files=JTVCJTdCJTIybmFtZSUyMiUzQSUyMlBsYXlncm91bmQudnVlJTIyJTJDJTIyZWRpdG9yJTIyJTNBJTIyJTNDdGVtcGxhdGUlM0UlNUNuJTIwJTIwJTNDRm9ybUtpdCU1Q24lMjAlMjAlMjAlMjB0eXBlJTNEJTVDJTIydGV4dCU1QyUyMiU1Q24lMjAlMjAlMjAlMjBsYWJlbCUzRCU1QyUyMkZvcm1LaXQlMjBJbnB1dCU1QyUyMiU1Q24lMjAlMjAlMjAlMjBoZWxwJTNEJTVDJTIyZWRpdCUyMG1lJTIwdG8lMjBnZXQlMjBzdGFydGVkJTVDJTIyJTVDbiUyMCUyMCUyMCUyMCUzQWhlbHAtY2xhc3MlM0QlNUMlMjIlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwcmVkJTNBJTIwdHJ1ZSU1Q24lMjAlMjAlMjAlMjAlN0QlNUMlMjIlNUNuJTIwJTIwJTJGJTNFJTVDbiUyMCUyMCUzQ0Zvcm1LaXQlNUNuJTIwJTIwJTIwJTIwdHlwZSUzRCU1QyUyMnRleHQlNUMlMjIlNUNuJTIwJTIwJTIwJTIwbGFiZWwlM0QlNUMlMjJGb3JtS2l0JTIwSW5wdXQlNUMlMjIlNUNuJTIwJTIwJTIwJTIwaGVscCUzRCU1QyUyMmVkaXQlMjBtZSUyMHRvJTIwZ2V0JTIwc3RhcnRlZCU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlM0FoZWxwLWNsYXNzJTNEJTVDJTIyJTVCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCd1bmRlcmxpbmUnJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjByZWQlM0ElMjB0cnVlJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlNUQlNUMlMjIlNUNuJTIwJTIwJTJGJTNFJTVDbiUzQyUyRnRlbXBsYXRlJTNFJTVDbiU1Q24lM0NzdHlsZSUzRSU1Q24udW5kZXJsaW5lJTIwJTdCJTVDbiUyMCUyMHRleHQtZGVjb3JhdGlvbiUzQSUyMHVuZGVybGluZSU1Q24lN0QlNUNuLnJlZCUyMCU3QiU1Q24lMjAlMjBjb2xvciUzQSUyMHJlZCU1Q24lN0QlNUNuJTNDJTJGc3R5bGUlM0UlNUNuJTIyJTdEJTVE).

**Comment by justin-schroeder** [comment]
Thats correct, formkit does not support that syntax.

**Comment by justin-schroeder** [comment]
I suppose the follow up is — should it be? We already support lots of class sytaxes that are not supported by vue, like functions, so im not sure parity is what we are going for, but if this is a common use case or something that has really important edge cases im not opposed to it I suppose.

**Comment by innocenzi** [comment]
I think it should be supported, it's a very handy syntax which I think improves DX quite a bit. Without this syntax, it's a bit verbose when there are a few conditional classes and a few non-conditionals (which happens frequently with Tailwind).

**Comment by innocenzi** [comment]
This is really a convenient way of styling with class-based frameworks such as Tailwind. I guess the next time I try FormKit and stumble upon this, I'll PR it, would that be okay?

**Comment by justin-schroeder** [comment]
Yes, I think we would be happy to accept a PR for that.

**Comment by innocenzi** [comment]
Perfect then!
