### ISSUE TITLE
Add prop to datepicker to clear the input

### ISSUE THREAD

**Issue by justin-schroeder** [formkit/formkit#893]
### Discussed in https://github.com/orgs/formkit/discussions/890

<div type='discussions-op-text'>

<sup>Originally posted by **AtousaDarabi** August 16, 2023</sup>
Need to delete date in datepicker in a way  which is not backspace in three steps (delete day, delete month, delete year)
For example adding an X  beside calendar icon in field and by clicking it remove the date or have a "Clear" button in datepicker's dialogue box or any other way... 
</div>

**Comment by sashamilenkovic** [comment]
This can now be done with the `clearable` prop https://formkit.com/inputs/datepicker#page-container#clearable
