### ISSUE TITLE
Wrong FormKitButtonSlots type

### ISSUE THREAD

**Issue by KamilBeda** [formkit/formkit#895]
### Reproduction

https://formkit.link/5bd856812ec78cfc153343a3d320a9bf

### Describe the bug

I've noticed there is a problem with FormKitButtonSlots type. When I use input slot I get `TypeScript error Property 'input' does not exist on type FormKitButtonSlots.` That's clearly not true because I see it's switching button input to anything i put inside slot. 
I think the source of this issue is in type declaration:
```javascript
export declare type FormKitButtonSlots<Props extends FormKitInputs<Props>> = Omit<FormKitBaseSlots<Props>, 'input' | 'help'> & {
           default: FormKitSlotData<Props>;
       };
```
I don't rly get why `input` and `help` slots are omited, docs marks them as valid button sections -> https://formkit.com/inputs/button#sections

### Environment

• OS: N/A
• Browser: N/A
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
Yep, this is just wrong. Should only omit `inner`. This is fixed in the `release/0.18.3` branch.
