### ISSUE TITLE
Plugin usage throws "Maximum recursive updates exceeded in component"

### ISSUE THREAD

**Issue by datenfalke** [formkit/formkit#898]
### Reproduction

https://formkit.link/b1dc4539bfb84c25ea3702d75af5dc3e

### Describe the bug

I want to use the proposed Formkit plugin for "Make number inputs return number values" as proposed at https://formkit.com/essentials/examples#plugins and https://formkit.link/b1dc4539bfb84c25ea3702d75af5dc3e

The example throws the following error/warning from version 0.17.x on up to latest 0.19.x:

`[Vue warn]: Maximum recursive updates exceeded. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.`

![image](https://github.com/formkit/formkit/assets/754335/2c64c243-f9c5-4ce7-bc7f-7d5edad33064)

### Environment

• OS: Ubuntu
• Browser Firefox + Chrome
• Version 0.17.x, 0.18.x, 0.19.x

**Comment by GustavoFenilli** [comment]
You just need to add the hook inside the created event otherwise at first load it will try to mutate the value at the same time as the v-model does I believe. https://formkit.link/9fb566f6fc9a692452d478a6f25feb7c

**Comment by andrew-boyd** [comment]
@GustavoFenilli is correct, this is an interplay between FormKit and the `v-model`. I'm going to update the example to use `#default` slot restructuring to check the value which is what we recommend anyways — but wrapping in a created event works if your use-case requires `v-model` for some reason. 

https://formkit.link/9d5ee95835fc654a2887b7c391f3e8e7
