### ISSUE TITLE
File input doesn't fire 'change' event

### ISSUE THREAD

**Issue by mihqusta** [formkit/formkit#90]
**Describe the bug**

FormKit component of type 'file' doesn't fire the 'change' event on file selection. Means one can't hide the button once a file has been selected.

**Reproduction**

https://formkit.link/fb0dd0499a4dd8277a10404f95217ccb

Steps: 
1. Create a FormKit with type 'file'.
2. Add @change handler. 
3. Select a file. 
4. Watch it not fire.

**Desktop (please complete the following information):**
 - OS: linux
 - Browser: chrome
 - Version: 1.0.0-beta.2

**Comment by justin-schroeder** [comment]
@mihqusta this is now fixed in the beta.3 branch (to be released next week). If you go back to your playground, you can see the fix in action by changing the version to `1.0.0-beta.3 (next)`. Thanks for the report 👍
