### ISSUE TITLE
Testing nested components with FormKit & Vitest

### ISSUE THREAD

**Issue by glennovische** [formkit/formkit#904]
### Reproduction

-

### Describe the bug

A few days ago I openend a ticket asking on how to render Formkits actual HTML in my tests. The answer was 

```
import { plugin, defaultConfig } from '@formkit/vue'
describe('some formkit inputs', () => {
  it('can render a text input', () => {
    const wrapper = mount(FormKit, {
      props: {
        type: 'text',
        value: 133,
      },
      global: {
        plugins: [[plugin, defaultConfig]],
      },
    })
    expect(wrapper.find('input').exists()).toBe(true)
  })
})

or something like this:
import { plugin, defaultConfig } from '@formkit/vue';
const global: Record<string, Record<string, any>> = {
  global: {
    plugins: [[plugin, defaultConfig]],
  },
};

const formkitTestMount = mount(
  {
    setup() {
      const values = reactive<{ form: Record<string, any> }>({
        form: { abc: '123' },
      });
      const changeValues = async () => {
        values.form.foo = 'bar bar';
      };
      return { values, changeValues };
    },
    template: `<FormKit type="form" v-model="values.form">
    <FormKit type="text" name="foo" value="foo" />
    <button type="button" @click="changeValues">Change</button>
  </FormKit>`,
  },
  {
    ...global,
  }
);
```

this works fine for just testing and rendering out the formkit component self but in my case I have a component named pincode. In the component I am using 3 types "form", "otp" and "sumbit" within the FormKit wrapper. Plus a custom component with buttons PrevNextButtons.

Now in my test I want to render all the actual html for my custom PrevNextButtons and for the FormKit stuff. In my wrapper I mount the Pincode component and its childs like so

```
wrapper = mount(Pincode, {
      global: {
        components: {
          PrevNextButtons: PrevNextButtons,
          **FormKit how to get the template html rendered here?? **
        },
        plugins: [
          createTestingPinia({
            createSpy: vitest.fn,
          }),
        ],
      },
    });
```
How to render the HTML of FormKit within nested components?

### Environment

- Operating System: `Darwin`
- Node Version:     `v18.14.2`
- Nuxt Version:     `3.5.3`
- Nitro Version:    `2.4.1`
- Package Manager:  `npm@9.5.0`
- Builder:          `vite`
- User Config:      `app`, `build`, `runtimeConfig`, `modules`, `css`, `plugins`, `postcss`, `vite`, `auth`, `experimental`
- Runtime Modules:  `@sidebase/nuxt-auth@0.5.0`, `nuxt-vitest@0.6.12`, `nuxt-lodash@2.5.0`, `@formkit/nuxt@1.0.0-beta.9-f64c966`, `@vueuse/nuxt@9.13.0`, `@pinia/nuxt@0.4.11`
- Build Modules:    `-`

**Comment by justin-schroeder** [comment]
You just need to add the plugin to your `mount()` call like you did in your other examples.

```
{
  plugins: [[plugin, defaultConfig]],
}
```
