### ISSUE TITLE
Missing types for slots in the Autocomplete input

### ISSUE THREAD

**Issue by lud-hu** [formkit/formkit#905]
### Reproduction

https://formkit.link/a8bc993b26501fd8a261d6d085faf48c

### Describe the bug

Since 0.18.x the typings for the v-model seem to not match properly, even though the type is "number". In the source code it looks like the v-model type is derived from the value (which we don't want to set here) - but if I pass a number as value it does not work as well.
![image](https://github.com/formkit/formkit/assets/26108368/99587b82-a851-416b-b1fb-6afe3eb11f44)

```ts
<FormKit
  v-model="finalPostalCode"
  name="zipCode"
  type="number"
  validation="required|number|length:5,5"
  :validation-messages="{
    length: zipCodeValidationMessage,
    number: zipCodeValidationMessage,
    required: zipCodeValidationMessage,
  }"
/>
```

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by GustavoFenilli** [comment]
With the new typings, the type got stricter, basically the native html number only accepts strings, and the input number follows that, that is why it only accepts strings, meaning your `finalPostalCode` should be a string ref `const finalPostalCode: Ref<string> = ref('1');`

**Comment by GustavoFenilli** [comment]
What version of FormKit and FormKit Pro you're using?

**Comment by lud-hu** [comment]
> With the new typings, the type got stricter, basically the native html number only accepts strings

Ah, I understand! Thanks for clarification.

> What version of FormKit and FormKit Pro you're using?

```
"@formkit/addons": "0.18.3",
"@formkit/icons": "0.18.3",
"@formkit/nuxt": "0.18.3",
"@formkit/pro": "0.114.2",
```

**Comment by justin-schroeder** [comment]
@lud-hu you’re right — `closeIcon` is missing — we’ll get it added 👍
