### ISSUE TITLE
created not emit

### ISSUE THREAD

**Issue by vxow** [formkit/formkit#909]
### Reproduction

https://formkit.link/963af6b253d0c8e7bf597617b0c07703

### Describe the bug

group.on('created.deep', ({ payload: child }) => {
  console.log('child node created:', child.name)
})

created not emit

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by sashamilenkovic** [comment]
@aegorx Hey! So I think that's correct. The node has already been created by the time you call `createNode` so it makes sense that by the time you set `created` event listener it doesn't fire. You could get around this by passing a plugin to the `createNode` call like so: https://formkit.link/c4abc854c0b1d956b2429db5465d6c06.

**Comment by justin-schroeder** [comment]
@sashamilenkovic nailed it — the node is created by the time you run that, if you want to catch its own `created` event the plugin needs to be on there at instantiation (`createNode()`).
