### ISSUE TITLE
Loop scope is lost inside nested FormKit components

### ISSUE THREAD

**Issue by justin-schroeder** [formkit/formkit#91]
The scope of a nested loop is lost inside the default slot of a group component. It should not be. In this example, `$input` appears to be out of scope inside a nested loop, but only if the parent of that nested loop is a FormKit input (group in this case) when it's an `$el` it does not loose scope.

https://formkit.link/47a7293ea048b2a16b40677eba6b58d4

This could have something to do with the memoization. Thanks to @dominikklein for the report.

**Comment by justin-schroeder** [comment]
@dominikklein Remember this one? It was a seriously hard bug to track down, but its working now in the beta.6 on the `@next` tag.

**Comment by dominikklein** [comment]
Ah nice:-) then i can maybe change some code for the usage of FormGroups.
