### ISSUE TITLE
datepicker events don't include event object

### ISSUE THREAD

**Issue by kswedberg** [formkit/formkit#912]
### Reproduction

https://formkit.link/af6e189d19f63885d824463cff852734

### Describe the bug

When I set an `onBlur` handler (using schema) on a datepicker input, the `event` object is not being passed to that function. Also, the datepicker's input doesn't have the name attribute assigned to it. 
Confirmed by @GustavoFenilli in Discord. He also noted that blur isn't triggered at all if you click the datepicker button and then click away from the input.

### Environment

• OS: MacOS
• Browser:chrome, safari
• Version: latest

**Comment by kswedberg** [comment]
Oh wait, I see the issue now isn't the event handler. The `name` property isn't being set as the `name` attribute of the input. 
Should I create another issue for that?

**Comment by justin-schroeder** [comment]
Yeah lets make a new issue for that 👍
