### ISSUE TITLE
Dropdown Input with Dynamic Options and `#option` Slot

### ISSUE THREAD

**Issue by jjjrmy** [formkit/formkit#914]
### Reproduction

https://formkit.link/924ab2f4c1cf31f1820ec4cbf7f33520

### Describe the bug

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'label')`
The `option` is returning undefined from the slot when using dynamic options functionality.

### Environment

latest

**Comment by GustavoFenilli** [comment]
Might not be a bug?, #option shows whenever you start loading, at that point your `await new Promise((resolve) => setTimeout(resolve, 500))` didn't finish yet, so its `[]`, meaning that when you do `option.label` it is undefined, if you do `option?.label` to make sure it is not undefined it works.

**Comment by jjjrmy** [comment]
This issue happens to me even when not using a `setTimeout` before my requests.
If the return is any empty array or a promise then shouldn't it not loop through the options anyways and it not be a problem?

Maybe the error is actually being thrown from the selected option being empty, not from the dropdown.

**Comment by GustavoFenilli** [comment]
Might be better for DX if the option slot only renders if there are options.
