### ISSUE TITLE
Checkbox: Invalid markup (div within label)

### ISSUE THREAD

**Issue by betabong** [formkit/formkit#915]
### Reproduction

https://formkit.link/90a129004a49b2a844962062965ca7ca

### Describe the bug

Checkboxes and Radios are wrapped via label (which is fine, slightly surprising to oldschool accessibility me). But a div within a label is not valid markup (and therefore not 100% valid in accessibility audits).

### Environment

Formkit: <= 0.19
Browser: any

**Comment by justin-schroeder** [comment]
Thank you for pointing this out, we’ll address this.
