### ISSUE TITLE
Add new core event for any mutation to children array.

### ISSUE THREAD

**Issue by aegorx** [formkit/formkit#919]
### Reproduction

https://formkit.com/essentials/architecture

### Describe the bug

https://github.com/formkit/formkit/blob/c781b3995d3873cdf8ffd0cc30008aa8072a6935/packages/core/src/node.ts#L2257

https://github.com/formkit/formkit/blob/c781b3995d3873cdf8ffd0cc30008aa8072a6935/packages/core/src/node.ts#L2334

Can I have the remove method trigger as well.
Or is there a way to deeply sense changes in a group node's data.input.deep cannot sense add or remove child.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
@aegorx I think this is the information you need correct? https://formkit.link/bf634f8351579aaf88cb1b28269e20b7

**Comment by aegorx** [comment]
@justin-schroeder  THX.

It would really solve my problem.

But I want an event that notifies node.value of the change after executing 'node.add' 'node.remove' 'node.destroy'. It would be cool if there were such an event.

**Comment by justin-schroeder** [comment]
I think we can do that. Would also be nice to add that to the `@formkit/observer` since `node.children` is not reactive in the observer at the moment and this event would enable that. FWIW — the event would also need to trigger on child sorting.

**Comment by justin-schroeder** [comment]
In `@next` this is now more clear. There are `child` and `childRemoved` events — these both emit the child as the payload. Additionally `node.children` is now observable by the node observer:

```ts
import { createNode } from '@formkit/core'
import { createObserver } from '@formkit/observer'

const parent = createNode({ type: 'group' })
const observed = createObserver(parent)
// This works like `watchEffect` in Vue:
observed.watch((node) => {
  console.log(node.children.length)
})
// console.log: 0
const childA = createNode()
node.add(childA) // console.log: 1
node.add(createNode()) // console.log: 2
node.remove(childA) // console.log: 1
```
