### ISSUE TITLE
Autocomplete: faulty behaviour with many items

### ISSUE THREAD

**Issue by betabong** [formkit/formkit#926]
### Reproduction

https://formkit.link/98cdc0489eed32ee69fcf0dc90a01813

### Describe the bug

If an autocomplete has many (around 400) options, filtering behaves erratic: options are included that should not be included. 

As soon as I options are removed (like reduced to 50), everything works as expected. But I'm not sure wether it's got to do with deleted values or the number of values or the number of found items. The only thing I know is that the behaviour is definitely erratic. 

### Environment

• OS: Mac
• Browser Chrome
• Version 116
(but it affects all browsers AFAIK)

**Comment by sashamilenkovic** [comment]
@betabong Hey! I looked into this. It looks like your flights array has a lot of duplicate values causing the key of the listitem section schema to not update accordingly. Can you provide a reproduction where all values of options are unique and see this occur as well?
