### ISSUE TITLE
Font descenders cut off

### ISSUE THREAD

**Issue by meixger** [formkit/formkit#930]
### Reproduction

https://formkit.link/3792a492459107ea63f9d2a8bcc7418b

### Describe the bug

The font descenders are cut off. e.g.: 'j' and 'g'.

![image](https://github.com/formkit/formkit/assets/600424/64cd1119-7aa6-4dfa-9eca-f3ead5840c58)

I tested also on BrowserStack.com.
Chrome 116 on OSX works fine.

[edit] Occurs only with Genesis theme

### Environment

• Windows 11
• Chrome 116

**Comment by sa8ab** [comment]
This can be fixed by increasing `--fk-line-height-input` and decreasing `--fk-padding-input-x` css variables. I have not tested other input types to see if it causes different height elements but makes descenders visible.

**Comment by meixger** [comment]
Resolved with the regenesis theme from https://themes.formkit.com/
