### ISSUE TITLE
Name attribute not set on datepicker input

### ISSUE THREAD

**Issue by kswedberg** [formkit/formkit#932]
### Reproduction

https://formkit.link/5cc99b08362928800867e6e991809543

### Describe the bug

Given a datepicker input:

```html
<FormKit name="cant_see_me" data-name="hello" type="datepicker" />
```
The html output will be (for example): 

```html
<input data-name="hello" class="formkit-input" id="input_0">
```
Note the `name` attribute is missing.

### Environment

• OS: any
• Browser any
• Version any

**Comment by justin-schroeder** [comment]
This has been resolved 👍

**Comment by kswedberg** [comment]
Thank you! 🎉
