### ISSUE TITLE
Slider input does not react to changes in max property

### ISSUE THREAD

**Issue by radusuciu** [formkit/formkit#935]
### Reproduction

https://formkit.link/2b7431dae74e110c00578c8b48ef4cd6

### Describe the bug

When the `max` attribute is reactive, the slider does not re-render to account for these changes.

![GIF 2023-09-07 5-38-15 PM](https://github.com/formkit/formkit/assets/1108600/118b7f9b-e861-4ef1-bc24-3e6979ae2459)

### Environment

• OS: Windows
• Browser: Edge
• Version: 116.0.1938.69 (Official build) (64-bit)

**Comment by justin-schroeder** [comment]
I think what you are saying is you want the slider to reduce its stored value based on the max changing. I can understand why you would expect this behavior, however this is contrary to one of FormKit’s underlying principles of not changing user-input values automatically.

On all first-party inputs we try very hard to respect the value that has been assigned to the input unless a user explicitly changes the value. For example, if someone’s value was 255, and the input’s max was determined by an async call so the initial value was `0` it would, confusingly, reset the value down. These kinds of bugs are very hard to track down, and they fundamentally *lose* information about the users intention.

Now that said, the behavior you’re looking for can be implemented relatively easily in user-land using a hook:

https://formkit.link/2686fc2e66a71e4bd5a9456ecb270cc7

**Comment by justin-schroeder** [comment]
Was pointed out to me by @sashamilenkovic that our UI needs to update to reflect the new positioning when the max changes — this is true!

**Comment by radusuciu** [comment]
> I think what you are saying is you want the slider to reduce its stored value based on the max changing. I can understand why you would expect this behavior, however this is contrary to one of FormKit’s underlying principles of not changing user-input values automatically.
> 
> On all first-party inputs we try very hard to respect the value that has been assigned to the input unless a user explicitly changes the value. For example, if someone’s value was 255, and the input’s max was determined by an async call so the initial value was `0` it would, confusingly, reset the value down. These kinds of bugs are very hard to track down, and they fundamentally _lose_ information about the users intention.
> 
> Now that said, the behavior you’re looking for can be implemented relatively easily in user-land using a hook:
> 
> https://formkit.link/2686fc2e66a71e4bd5a9456ecb270cc7

Thanks for the reply!

Not quite what I'm saying though, let me clarify - I would not expect that the value changes, but rather that the slider fill changes to account for the new max.

Starting state:
![image](https://github.com/formkit/formkit/assets/1108600/aa2519f1-cd20-4347-8706-10dcad212c50)

Current state after max ref is changed to 125:
![image](https://github.com/formkit/formkit/assets/1108600/45c52541-f4ac-4f9b-9024-b53952c7a1e7)

Desired state after max ref is changed to 125:
![image](https://github.com/formkit/formkit/assets/1108600/0b29b0a1-d165-4b0c-8e54-7c39a60fd5fa)

**Comment by radusuciu** [comment]
> Was pointed out to me by @sashamilenkovic that our UI needs to update to reflect the new positioning when the max changes — this is true!

Yes!
