### ISSUE TITLE
Slider handle won't update after binded value updates

### ISSUE THREAD

**Issue by phoenixbart** [formkit/formkit#936]
### Reproduction

https://formkit.link/5cb15c27e3ac4ddc388ffc36f0ac8af1

### Describe the bug

The binded value is updating but the slider itself isn't. I would expect that the handle and track is updating according to the updated value

### Environment

• Mac OS
• Browser chrome

**Comment by radusuciu** [comment]
Not sure I can replicate in Edge on Windows:

![GIF 2023-09-08 7-46-51 AM](https://github.com/formkit/formkit/assets/1108600/a1b95b55-1bce-4247-a637-cf3eeba2f526)

**Comment by phoenixbart** [comment]
If you edit the value with the slider, the value will updated as it should indeed. But not the other way around: If some other component changed the value it should update the slider, but it doesn't
