### ISSUE TITLE
The clearErrors method cannot be used on a node 

### ISSUE THREAD

**Issue by aegorx** [formkit/formkit#941]
### Reproduction

https://formkit.link/b26a46fe8a9ccdd47bad63dbc281dab4

### Describe the bug

Does this method only work on 'form'.

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by justin-schroeder** [comment]
We can improve the DX here.

For context the intent of setErrors/clearErrors (when used deeply) — is for FormKit to automatically know which errors were applied via setErrors and only remove those ones when calling `clearErrors`. To do this errors are "signed" by the node that initially applied the error — in your case you are applying errors via the form, so the only node that can `clearErrors` is the form node.

If you use the form node to clear the errors on `second_input` you can do so (https://formkit.link/6679c9f9cec9e49a7d89a0166ce88c9e).

Alternatively — you can directly access the node store and filter out any `error` type messages: 
https://formkit.link/fe8804af475ee1632c484d66786ffc01

**Comment by justin-schroeder** [comment]
ok @aegorx `node.clearErrors()` will always clear it’s own local errors even if they were set by a different node (in `@next`).
