### ISSUE TITLE
Datepicker with picker only is closing immediately after opening it

### ISSUE THREAD

**Issue by CavalcanteLeo** [formkit/formkit#942]
### Reproduction

https://formkit.link/33b85f9b2598ab352141a92799a7586c

### Describe the bug

The picker dropdown closes immediately after we click on the input to open it. It only remains open if we click on the calendar icon. Also if we click and hold the click, it remains opened

https://github.com/formkit/formkit/assets/1735944/674e3c5c-9f38-4498-ab99-eb6dbc38525e

### Environment

• OS: macOS
• Browser chrome
• Version 1.0.0

**Comment by JoaoPedroAS51** [comment]
I'm still facing this issue.

Environment
• OS: macOS
• Browser: Chrome
• FormKit: v1.0.0
• FormKit Pro: v0.115.8

**Comment by CavalcanteLeo** [comment]
Yep, even on the link I sent previously it's still closing

**Comment by justin-schroeder** [comment]
Hmm, not sure what happened here — had it fixed locally and published, but perhaps it didn’t make it out. I’ll get this sorted...

**Comment by justin-schroeder** [comment]
This is now fixed in 0.115.9 👍
