### ISSUE TITLE
zod plugin - setZodErrors() should look for a 'issues' array

### ISSUE THREAD

**Issue by davbtmx** [formkit/formkit#945]
### Reproduction

https://formkit.link/3dd52f5f944a7bf55051dbcdeff6265b

### Describe the bug

A **ZodError** contains an array of errors called **_issues._**

```js
const zodError = {
  name: 'ZodError'
  issues: [],
}
```

Documentation:
https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md#zoderror

Code:
https://github.com/colinhacks/zod/blob/master/src/ZodError.ts#L210

FormKit's **setZodErrors()** looks for an array called **_errors_** within the ZodError object. It should look for an array called **_issues_** instead.

Code:
https://github.com/formkit/formkit/blob/master/packages/zod/src/zod.ts#L199

In the [official example playground](https://formkit.com/plugins/zod#for-setting-form-errors) it works because the ZodError is a plain object which not only contains the **_issues_** array but also a getter called **_errors()_** which returns the **_issues_** array.

Code :
https://github.com/colinhacks/zod/blob/master/src/ZodError.ts#L195-L197

But in a real app where the server **converts the ZodError object to JSON** in order to send it to the client, this getter is therefore lost. In the end, the client receives a **ZodError** that only contains the **_name_** string and the original **_issues_** array.

So I guess that replacing `zodError.errors.forEach(...)` with `zodError.issues.forEach()` in `zod.ts` should make it work for all cases.

### Environment

• OS: any
• Browser: any
• Version: any

**Comment by andrew-boyd** [comment]
Thanks for the great report @davbtmx — this will go out in the next release (hopefully today).
