### ISSUE TITLE
Autocomplete option dropdown no longer opens after invalid input

### ISSUE THREAD

**Issue by radusuciu** [formkit/formkit#949]
### Reproduction

https://formkit.link/358dd9b835e497dc78e58fb662f453bc

### Describe the bug

After selecting an option, then providing some invalid input, the dropdown no longer opens.

![GIF 2023-09-14 11-56-20 AM](https://github.com/formkit/formkit/assets/1108600/98668084-c1ed-4278-a791-e3a63f2c4644)

Sorry for the bug report barrage. Everything I've submitted has been pretty minor, but I very much appreciate your work and am loving FormKit!

### Environment

• OS: Windows 10
• Browser: Edge
• Version: 116.0.1938.81

**Comment by sashamilenkovic** [comment]
@radusuciu No! We appreciate the feedback. I'll take a look into this.

**Comment by sashamilenkovic** [comment]
@radusuciu I published a fix for this on `0.115.7` if you could take a look.

**Comment by radusuciu** [comment]
I can confirm that this is fixed, thank you!

For some reason it did require me to blow away my node_modules but that's probably just my setup.
