### ISSUE TITLE
transferlist options not reactive in combination with v-model

### ISSUE THREAD

**Issue by smakinson** [formkit/formkit#951]
### Reproduction

https://formkit.link/29ae92c7e645174561d0df4b702a5f80

### Describe the bug

After posting on discord support @sashamilenkovic requested a bug be filed.

This playground link moves an item to the target side as expected from `v-model`: https://formkit.link/44081db6788687669e8fc5726600b9d9

And this one, with a delay in loading an array of data into a `ref` provided to `options` does not show the item on the target side: https://formkit.link/29ae92c7e645174561d0df4b702a5f80

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by sashamilenkovic** [comment]
@smakinson I published an update for @formkit/pro `0.115.8` if you could take a look when you have a chance. The playground should reflect the fix as well on the latest tag but you may need to clear you cache/hard reload to make sure you're pulling the right version of FormKit Pro from the CDN.

**Comment by smakinson** [comment]
@sashamilenkovic That looks like it fixes the issue.  Thank you!
