### ISSUE TITLE
Keyboard navigation issues when using Datepicker

### ISSUE THREAD

**Issue by js-modernary** [formkit/formkit#952]
### Reproduction

https://formkit.link/b007a9eb98ae2fdc838dd02a1c988fcc

### Describe the bug

Open the picker dialog by either selecting the picker icon or hitting "enter" while the control has focus. Then -

Keyboard behavior - Hit "enter" to select a date. This opens the month selection dialog. Selecting a month using "enter" appears to do nothing. Using "tab" jumps between the year and the months. If you use "shift-tab" it'll take you back into the input control, but you're in a very weird state at that point. You can use the arrow keys to change the date, but those changes aren't reflected in the picker. Hitting "enter" after making those changes just causes the picker to go into year selection mode.

Mouse behavior - Click on a date date with your mouse, this causes it to jump to the time selection control.  

I would expect the keyboard to behave like the mouse - You can select a day from the default month/year followed by the time or you can select a year, followed by a month, followed by a day, followed by the time. 

Somewhat related - Once you've entered the time, the timepicker feels like a dead end when using the mouse. Using the keyboard it's great - you hit enter and the picker collapses. Clicking off of the picker at the conclusion of setting the time feels somewhat strange by comparison. I recognize that some kind of "done" or "x" button is entirely redundant as the time is synced as you're changing it, but you end up searching for one anyway (but maybe that's just me).

### Environment

• OS: Windows
• Browser: Any (replicated in Chrome, Firefox, Brave)
• Version: 1.0.0

**Comment by justin-schroeder** [comment]
I also would expect the keyboard to behave like the mouse. Thanks for the report 👍

**Comment by justin-schroeder** [comment]
I believe this behavior has been fixed.
