### ISSUE TITLE
Datepicker `invalidDate` validation rule key can't set custom validation message

### ISSUE THREAD

**Issue by KoenCa** [formkit/formkit#953]
### Reproduction

https://formkit.com/playground?fkv=latest&fileTab=Playground.vue&css-framework=genesis&files=jc%5B('name!'PQd.vue'~_itx!'%3Cscrip6setup4B+ESMVmpxt5ar8suppxteHfrom+URL5%7Bhttps:Bcdn...%7D1BW5wellW5secondary+pQHfile5%7B./OthXFile.vue%7D.19script41%3CZ0%3CA6type7fxm2400%3CAt3type7dGpickXjlabel7A6Inputjhelp7_i6m8to+ge6start_jN7Tj:min-dG7new+DG%7B%7Dj:N-messages7(30TJi6i5vXplicht.%22,30invalidDGJez8datumV5nie6geldig.%223)2100/409At49Z1%3CY8scop_4/*1vanilla+CSS+can+go+hXe.1Keep+Ye5scopeHtoWvoiHmultipl8files1ovXwriting+each+othXVn+th8rendX+output.1*/19Ye4'~add_!true)%5D0++1%5Cn2%5C'310004%3E15s+6t+7%3D28e+9%3C/AFxmKiB//GateHd+J:+%22DNvalidationQlaygrounTrequir_V+iW+aXerYstylZtemplG4_edj23xor%01xj_ZYXWVTQNJHGBA9876543210_

### Describe the bug

According to the datepicker docs the validation key is `invalidDate` when `min-date`, `max-date` or `disabled-days` are set. But when I use this key to set a custom validation message, then the custom message is not used. This is reproduced in the provided link.

### Environment

• OS: MacOS
• Browser: Arc (Chrome)
• Version: `1.0.0` + `1.1.0 (next)`

**Comment by KoenCa** [comment]
I wanted to do this, because this validation message is not translated in my message, but when I take a look at the `nl.ts` translation file, then I see that is translated: https://github.com/formkit/formkit/blob/0adcf3f5c8e8630607ab71a3f0938aa9711dfd1f/packages/i18n/src/locales/nl.ts#L91

So it looks like the translation is also not picked up for this key?

**Comment by justin-schroeder** [comment]
Ah, `invalidDate` is under the `ui` key not the `validation` key in our i18n files, but the message `type` is validation. This is my fault and will be fixed in `1.3.3`.

**Comment by justin-schroeder** [comment]
Resolved in 1.4.0 👍
