### ISSUE TITLE
Floating label of dropdown input misplaced

### ISSUE THREAD

**Issue by meixger** [formkit/formkit#955]
### Reproduction

https://formkit.link/07712b8e9e321839f4af7a95a6bbe3dc

### Describe the bug

The dropdown (pro) input has the label misplaced when using `createFloatingLabelsPlugin ` from `@formkit/addons`

![image](https://github.com/formkit/formkit/assets/600424/85e5ebd4-eff0-44e8-84b4-0c26c521b7ab)

### Environment

• OS: Windows 11
• Browser: chrome 117, firefox 117

**Comment by andrew-boyd** [comment]
This was fixed in 1.5.0

https://formkit.link/9d311485550b0ee337a6dfdf13ee73c9
