### ISSUE TITLE
Custom inputs cause Typescript errors in v-model and named slots

### ISSUE THREAD

**Issue by ymansurozer** [formkit/formkit#956]
### Reproduction

https://github.com/ymansurozer/formkitTypeError

### Describe the bug

My custom inputs I create with `createInput` and register globally are getting type errors.

1. Whenever I use named slots to customize help, label, etc., I get `Property 'label' does not exist on type '{}'.ts(2339)
` error. See `pages>error12` in the repo.
2. My custom inputs do not appear in `FormKit`'s `type` attribute. Is that normal? This can also be seen in the initial state of the reproduction repo. See `pages>error12` in the repo.

3. Also, whenever I try to do v-model or provide props or a value, I get this error: 
```
Argument of type '{ modelValue: {}; type: "myCustomInput"; }' is not assignable to parameter of type 'FormKitInputs<{ modelValue: {}; type: "myCustomInput"; }> & VNodeProps & AllowedComponentProps & ComponentCustomProps'.
  Type '{ modelValue: {}; type: "myCustomInput"; }' is not assignable to type 'Omit<Partial<FormKitBaseProps>, "type" | "value"> & Omit<Partial<FormKitRuntimeProps<{ modelValue: {}; type: "myCustomInput"; }>>, "type" | "value"> & ... 5 more ... & ComponentCustomProps'.ts(2345)
```

See `pages>error3` in the repo.

Is there a solution to this or do I simply ignore the type errors with `vue-ignore`? The code works great, the only issue is the type errors.

### Environment

• OS: Windows 11
• Browser: Edge@latest

**Comment by justin-schroeder** [comment]
@ymansurozer Have you added an appropriate declaration block as described in the "typescript support" section of the custom inputs docs?

https://formkit.com/essentials/custom-inputs#typescript-support

**Comment by ymansurozer** [comment]
Thanks Justin. I'm using Nuxt 3.7.3, which uses Vue 3.3. I'm in takeover mode and tried restarting Vue Server. Still the same.

By defining the value, I think you mean in the type declaration? I've done it now but did not help.

I already have a reproduction here (along with last edits): https://github.com/ymansurozer/formkitTypeError

**Comment by justin-schroeder** [comment]
Hmm. This all seems to be working just fine for me. Other than your example being a type `<input>` — when I swap that out for a `<FormKit>` component all is well — and typing is working on the value prop as well (if it give it a number it warns me of the issue).

![Screenshot 2023-09-20 at 11 51 02 AM](https://github.com/formkit/formkit/assets/1950463/42f21caa-69a8-47b9-af3f-59b72df0b891)
![Screenshot 2023-09-20 at 11 50 55 AM](https://github.com/formkit/formkit/assets/1950463/a6fbec9a-eb6e-4630-b78f-0f9f900864c9)

**Comment by ymansurozer** [comment]
Thanks for bearing with my Justin. That is very weird. Two questions:
1. I assume I don't have to use `<FormKit>` in custom inputs? I am asking because I want to simply create my own custom input and wrap that with FormKit defaults.
2. You can see `myCustomInput` inside `type` options in autocomplete in my repo? I've just upgraded my Node version to 18.8. Now the error on the named slots and v-model disappeared. But the custom input type is still not recognized.
```
**Argument of type '{ modelValue: string; type: "myCustomInput"; myProp: number; }' is not assignable** to parameter of type 'NonNullable<(Omit<Partial<FormKitBaseProps>, "number" | "type" | "value"> & Omit<Partial<FormKitRuntimeProps<{ modelValue: string; type: "myCustomInput"; myProp: number; }>>, "number" | ... 1 more ... | "value"> & Omit<...> & Partial<...> & { ...; }) | ... 26 more ... | (Omit<...> & ... 3 more ... & { ...; })> & Rec...'.
```

![image](https://github.com/formkit/formkit/assets/40335724/a4ec890b-3317-4ea7-a0c8-35e6b7d8dbd9)

I tried `my-custom-input` too but still the same. I tried a clean install (removed `package.json` and `node_modules` and `.nuxt` folders) but to no avail. And the weird thing is if I change the `ref` to number, the type checking works for the `value` and the error goes there. But if I make the `ref` of correct type, then the error goes to the whole component custom type. Do you have any ideas why this might be happening?

![image](https://github.com/formkit/formkit/assets/40335724/8d6bb9c1-7761-4bd6-bffe-6b7ef6b053e2)


Sorry for taking your time with this. Much much appreciated.

**Comment by ymansurozer** [comment]
Thanks Justin! I can definitely understand, the Vue space overall is developing quite fast (and I love it). :) 

So, I've upgraded to FormKit `1.1.0` and am using Volar `1.8.13`. I checked that the casing match between `type` prop, input definition in `formkit.config.ts`, and the Typescript definition. I tried disabling all my extensions and also changing Volar version down to `1.8.6` but none of this helped.

I am pretty sure the component is actually recognizing the custom type but still gives this error because if I mistype the `type` prop, then the error changes to `cannot assign to undefined`. And I also do not get any type errors if I do a type check via `vue-tsc --noEmit`. So it makes sense that it derives from Volar.

**Comment by justin-schroeder** [comment]
Maybe an updated reproduction is the next step here?

**Comment by ymansurozer** [comment]
Sure, I've already updated the reproduction repo above. Does that still work fine on your system?

**Comment by justin-schroeder** [comment]
When I pulled initially i was getting the error you described, but after doing an update and restarting the vue server all is well and working as intended.

**Comment by ymansurozer** [comment]
Ah, finally found the issue. In my `FormKit` type definitions, I had `value: string`, thinking a form should always have a value. I turned `value` into nullable with `value?: string` and now it works like a charm. So `FormKit` was simply expecting the `value`.

Thank you very much with your help Justin!

**Comment by maxjayne98** [comment]
@justin-schroeder @ymansurozer 
Hi guys, 
I guessed you can help me to fix my problem so I didn't create a new issue.

1. where should I put my custom input interfaces in the project, I created formkit.config.d.ts and formkit.d.ts (next to my formkit config file) but it didn't work , should I name it differently ?

2. How can I specify my props in the custom input component itself ? it didn't mention here https://formkit.com/essentials/custom-inputs#typescript-support.

**Comment by maxjayne98** [comment]
@justin-schroeder @ymansurozer
Hi guys,
I guessed you can help me to fix my problem so I didn't create a new issue.

where should I put my custom input interfaces in the project, I created formkit.config.d.ts and formkit.d.ts (next to my formkit config file) but it didn't work , should I name it differently ?

How can I specify my props in the custom input component itself ? it didn't mention here https://formkit.com/essentials/custom-inputs#typescript-support.

**Comment by ymansurozer** [comment]
Hi @maxjayne98. I simply created a `types/formkit.ts` file and declared a module as follows. Hope this helps.
```
import type { FormKitInputs } from "@formkit/inputs";
import type { UploadFileInfo } from "naive-ui";
import type { RadioButtonOption, RadioCardOption } from "@/types/radio";
import type { TransferOption } from "@/types/transfer";

declare module "@formkit/inputs" {
  interface FormKitInputProps<Props extends FormKitInputs<Props>> {
    "dcFileImage": {
      type: "dcFileImage";
      value?: UploadFileInfo[];
    };
    "dcFile": {
      type: "dcFile";
      accept?: string;
      maxFiles?: number;
      value?: UploadFileInfo[];
    };
    "dcRadioCard": {
      type: "dcRadioCard";
      dcOptions: RadioCardOption[];
      value?: string;
    };
    "dcRadioButton": {
      type: "dcRadioButton";
      dcOptions: RadioButtonOption[];
      value?: string;
    };
    "dcRadioButtonColor": {
      type: "dcRadioButtonColor";
      dcOptions: RadioButtonOption[];
      value?: string;
    };
    "dcTransfer": {
      type: "dcTransfer";
      dcOptions: TransferOption[];
      sourceTitle: string;
      targetTitle: string;
      value?: string[];
    };
    "dcToggle": {
      type: "dcToggle";
      value?: boolean;
    };
  }

  interface FormKitInputSlots<Props extends FormKitInputs<Props>> {
    "dcFileImage": FormKitBaseSlots<Props>;
    "dcFile": FormKitBaseSlots<Props>;
    "dcRadioCard": FormKitBaseSlots<Props>;
    "dcRadioButton": FormKitBaseSlots<Props>;
    "dcRadioButtonColor": FormKitBaseSlots<Props>;
    "dcTransfer": FormKitBaseSlots<Props>;
    "dcToggle": FormKitBaseSlots<Props>;
  }
}
```

`dc` is just a shorthand I use to distinguish my own custom inputs I imported from Naive UI.
