### ISSUE TITLE
Enhancement: Add programmatic form reset

### ISSUE THREAD

**Issue by jonathansousa** [formkit/formkit#96]
### Describe the feature

It would be very helpful to have the ability to reset a form programmatically to its initial state using something like `this.$formkit.reset('myForm')`. That call would remove current field values and set any initially specified defaults, clear and reset the validation status for the form and all nested fields, and set field states to their initial values (so `blurred`, `dirty`, and `submitted` all return to `false`).

I'm thinking about situations like a comment form where, after a successful XHR request, the form needs to be cleared for fresh input. Being able to call a `reset` function when the server finished responding would simplify things a lot.

If you want to get really flexible, have `reset` accept an object that modifies the initial schema so a label like "submit a comment" could be updated to "submit another comment".

**Comment by justin-schroeder** [comment]
Great idea! Thanks for the suggestion.

**Comment by justin-schroeder** [comment]
Ok reset functionality is now in the beta.5 branch. You can use it today by installing `@formkit/vue@next`. Documenation still to come but in general you can perform a `node.reset()` or a `import { reset } from '@formkit/core'` and then reset by id. It determines the initial state of the form based on values set by a parent, and values provided by children. If you want a pure reset back to nothing (or a different state) you can provide that as the second argument `reset(id, {})`

Here's a playground with it working: https://formkit.link/27d7f54fe5034729324d743df893adf2

**Comment by aegorx** [comment]
Hi, @justin-schroeder.
While adding built-in attributes is a nice feature, If message uses the transition tag, the style changes ugly, is there any way to add a custom class?

**Comment by justin-schroeder** [comment]
This issue is about programmatic form resetting so I’m a bit confused about this. What transition tag are we talking about here? Is there a different issue this was in regards to?
