### ISSUE TITLE
validation with  a matches regex that includes commas doesn't work

### ISSUE THREAD

**Issue by christiankozalla** [formkit/formkit#960]
### Reproduction

[Reproduction](https://formkit.com/playground?css-framework=genesis&fkv=latest&fileTab=tel.vue&imports=jc%28%27name%21%27ImportMap%27%7Elang%21%27json%27%7Eeditor%21%27%28*+1vue%5C%211https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fvue%403%2Fdist%2Fvue.esm-browser.min.js0*%29*%27%29*%5Cn0%5C%271+0%0110*_&files=jc%5B%28%27name%21%27tel.vue%27%7Eeditor%21%27%3C82%3CFormKit*type7telIlabel7AIplaceholder7BI67D%2F%5EMM54G%24%2FI%3A6-messages7%28*2D+%22A+must+bEin+thEformJ+B%22%2C*%29I6-visibility7dirty1C2%2FL%3C%2F8%27%7Esyntax%21%27html%27%7Eadded%21true%29%5D*C221%5C%272++5%5B0-9%5D%286validJion7%3D18templJeLAPhonEnumberBH-H-HxC%5CnDmJches%3AEe+G%2C%29HxxxI1*JatL%3ECM53G-%01MLJIHGEDCBA876521*_)

### Describe the bug

I have a FormKit input of type="tel" and a validation rule that contains a regex with commas

Example

```
<FormKit
  type="tel"
  validation="matches:/^0\d{2,}-\d{2,}$/"
  validation-visibility="dirty"
/>
```
I tried to reproduce the error, and started at the function `extractRules` in the validation packge:
https://github.com/formkit/formkit/blob/master/packages/validation/src/validation.ts#L613

If I call `extractRules("[matches](matches:/^0\d{2,}-\d{2,})");` I get `["matches", "/^0\d{2", "}-\d{2/", "}$/"]` - i.e. the regular expression split in two parts at the comma ","

The bug boils down to the `parseRule` function in the validation package: https://github.com/formkit/formkit/blob/master/packages/validation/src/validation.ts#L628 

I'd be willing to submit a PR that fixes the issue.

But I think we need to decide how to handle multiple arguments separeted by comma to other validation rules
Reference: https://formkit.com/essentials/validation#string-syntax

Wow! The bug is fixed, if I use the Array-Syntax instead!
So a validation rule of 
` :validation="[['required'], ['matches', /^\d{3,}-\d{3,}-\d{4}$/]] `
is totally working!

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by GustavoFenilli** [comment]
That is indeed not a bug, but a limitation of the string syntax for regex, the documentation https://formkit.com/essentials/validation#matches

> When using the string [String Syntax](https://formkit.com/essentials/validation#string-syntax) you cannot escape characters used to define the validation rules themselves (|,:). To use these characters in your regular expressions you must use the alternative [Array Syntax](https://formkit.com/essentials/validation#array-syntax).

**Comment by christiankozalla** [comment]
Alright, thanks! So I'll use the array syntax :+1:
