### ISSUE TITLE
`<FormKit>` emits `@update:model-value` twice in specific scenario

### ISSUE THREAD

**Issue by DamianGlowala** [formkit/formkit#961]
### Reproduction

https://github.com/DamianGlowala/nuxt-formkit-repro

### Describe the bug

1. `pnpm install` & `pnpm run dev`
2. Visit `localhost:3000`
3. Select `Option 1` from the first combobox.
4. Observe how the `@update:model-value` of the first combobox gets triggered twice when the second combobox is added to the DOM once the `v-if` condition is met.

It is worth adding that moving the second combobox **outside of the form component** removes the issue.

### Environment

n/a

**Comment by DamianGlowala** [comment]
How does running validations corresponds to triggering one of the input's `v-model` event? This feels counter-intuitive (even though you might be totally right with the above!), as to me these are two different aspects. The value of the first input changes only once, yet it appears as if changed twice based on the console output.

**Comment by GustavoFenilli** [comment]
The value doesn't change, but it does trigger a `commit`, when any value from a parent changes it spreads to its children so those values can be passed to the validation, meaning when you add a value to the form, it triggers a commit that goes to all children.

**Comment by justin-schroeder** [comment]
@DamianGlowala — it isn’t really related to validation, but you are correct in general, there is _intentionally_ no event like `@change` in FormKit. Why? Well — there are a number of reasons:

1. Knowing if something changed is expensive. Of course this doesn’t seem true at a surface level, comparing two strings is pretty cheap after all, but comparing deeply nested objects _is_ expensive, especially if the property being manipulated is deep.
2. Change ownership. Usually what people mean when they talk about "Did this input change" is "I want to perform a side effect when the user interacts with the input". In synced tree (like formkit) *what* changed the value of an input is immaterial. FormKit values can be changed by a parent node, a child, programmatically via node, with a plugin, in a hook, etc etc — the ownership of the change should not be important — the *state* should be important. Which brings me to the most important point:
3. Declarative. FormKit tries to encourage you to write your forms declaratively. In general, I wouldn’t recommend performing effects based on changes but rather the current *state* of your form. For example, a form could be hydrated with a given set of values — those values should always recreate the exact state of the form, irregardless of how a user interacted with the form. Event tracking is a slipper slope that often gets your form working in one "view" of your data, but will break when the same state is re-created by another means.

So yeah, in general events in FormKit are noisy — most of the time when people are worried about how many times their event fn is called, I get worried about how the form is structured. That being said, we’re always trying to make FormKit better so if there are valid declarative use cases that aren’t considered please let us know, or if there is some kind of state we aren’t already tracking that we should — also let us know :)

**Comment by GustavoFenilli** [comment]
Also if you use the FormKit event system instead of v-model it might mitigate some noisy behaviour: https://formkit.link/0f7a4300993e422d60d1121f5275e304
