### ISSUE TITLE
Typing issues in latest FormKit versions

### ISSUE THREAD

**Issue by lud-hu** [formkit/formkit#967]
### Reproduction

Only visible in IDE

### Describe the bug

Seems like there are still some typing issues in latest versions even though e.g. https://github.com/formkit/formkit/issues/905 was fixed already:

<img width="566" alt="image" src="https://github.com/formkit/formkit/assets/26108368/4e1d643d-19d3-4971-88fb-8ee39fb06582">

`Property 'closeIcon' does not exist on type 'FormKitTextSlots<FormKitInputs<{ name: string; type: "autocomplete"; autocomplete: string; label: string; validation: string; options: { label: string; value: string; }[]; openOnClick: boolean; clearSearchOnOpen: boolean; value: string | undefined; disabled: boolean; onNode: any; }>>'.`

And another error:
<img width="407" alt="image" src="https://github.com/formkit/formkit/assets/26108368/85b91c98-fe91-4c08-b0fc-c46554fe5603">
`Types of property 'options' are incompatible.`

### Environment

"@formkit/addons": "1.1.0",
"@formkit/icons": "1.1.0",
"@formkit/nuxt": "1.1.0",
"@formkit/pro": "^0.115.10",

**Comment by sashamilenkovic** [comment]
@lud-hu I looked into this. For some reason, assigning an initial value is reverting the slot types to that of a FormKit text input. We're not sure why that is the case. Will take a look.

**Comment by justin-schroeder** [comment]
I dont think this is related to a specific version of FormKit, but instead a version of Volar. Volar ships a lot of changes and they have somewhat unpredictable results for some of these complex type systems.

**Comment by anPalmer** [comment]
Thanks for the response, Justin. Downgrading to version 1.2.0 of Volar has resolved the errors.

**Comment by MalachiDraven** [comment]
Any updates on this? I'm having the same issue.

My site:
![Screenshot 2024-04-06 at 20-44-00 Screenshot](https://github.com/formkit/formkit/assets/21045455/95fc58aa-0306-4e64-9e02-b09282b3fc98)

app.vue:
```html
<template>
  <div>
    <h1>Hello World!</h1>
    <FormKit type="text" prefix-icon="eye" name="password" />
  </div>
</template>
```

This is on a fresh install / new Nuxt project. No other modules/plugins installed.

**Comment by fenilli** [comment]
@MalachiDraven this is not the same problem, your case looks more like your forgot to add the themes.
