### ISSUE TITLE
E-Mail: No German Umlaut in local part allowed

### ISSUE THREAD

**Issue by MortenHe** [formkit/formkit#969]
### Reproduction

https://formkit.link/e981b680821db204a7b326aec3d84d89

### Describe the bug

Formkits email validation does allow German Umlauts (ÄÖÜäöüß) in the local part of the mail which is not allowed.

I think the regex in packages/rules/src/email.ts has to be updated

const isEmail = /^(([^<>()\[\]\.,;:\s@\"]+(\.[^<>()\[\]\.,;:\s@\"]+)*)|(\".+\"))@(([^<>()[\]\.,;:\s@\"]+\.)+[^<>()[\]\.,;:\s@\"]{2,})$/i

In packages/rules/__tests__/email.spec.ts there is even a test to check if the Umlaut ä works in the local part which is not allowed in the email standard

  expect(email(createNode({ value: 'àlphä@❤️.ly' }))).toBe(true))

In my formkit playground example I created 2 inputs. The first is of type email, the second of type search. When submitting the form Chrome gives me a hint for the syntax error but only for the first input as it uses the integrated chrome type email input validation.

In my forms I use type=search for most inputs as it gives me the posibility to clean the input by pressing escape, that's why I need the formkit validation to work the same way as the browser's email validation.

I'd like to create a pull request but the regex was to complex to adjust for me, maybe I should ask ChatGPT? ;-)

### Environment

• OS: Windows
• Browser: Chrome
• Version current version
Formkit 1

**Comment by justin-schroeder** [comment]
Ah — emails are just rough because the standards are slippery. Our stance with the email validation rule is to take a very wide view of allowed emails so people with valid emails wont ever be told they aren’t valid — and nowdays many modern email providers *do* support utf8 characters in email addresses. The specific RFC is here:

https://www.rfc-editor.org/rfc/rfc6531

**Comment by MortenHe** [comment]
Dear justin,
thanks again for quick reply. Always a pleasure to work with formkit and the people behind it.
Your right, utf8 is the best way to go and keep it simple.
I'll add an extra rule the check the Umlauts so that the old openldap in our library software can handle it ;-)
