### ISSUE TITLE
Datepicker is not cleared when its v-model is "reset"

### ISSUE THREAD

**Issue by KoenCa** [formkit/formkit#972]
### Reproduction

[Reproduction link](https://formkit.com/playground?fkv=latest&fileTab=Playground.vue&css-framework=genesis&files=jc%5B('name!'Playground.vue'~editor!'%3Cscrip5Dup3impor5(Af+)+from+7vue711cons5BMAf%7B%7D11functionAD%7B%7D+(*Be.valuM+undefined1)16scriptHC%3E9v-model2Be0JBepickerEG5Input0help2edi5m8to+ge5started0clearableL9JbuttonEReD0@click2reD7LNpre%3E*4((+B8))*6pre36CHstyl8scoped36style3'~added!true)%5D*1407*41%5Cn2%3D73%3E14++5t+6%3C/7%5C'8e+9NGt*4A+reBdatCtemplateDsetE0label2GFormKiH31%3CJtype2L*/3M8%3DN*%3C%01NMLJHGEDCBA9876543210*_)

### Describe the bug

The content of the datepicker input is not cleared when its corresponding v-model is reset like in the reproduction link:
1. Select a date
2. Click the reset button
3. Value is cleared, but the date is still visible in the datepicker.
    - I also added the `clearable` option to showcase it a bit better. The cross icon dissappears after the reset, but the date text still stays in the input.

### Environment

• OS: MacOS
• Browser: chrome
• Version: 1.1 and 1.2

**Comment by justin-schroeder** [comment]
(fix will be deployed shortly)
