### ISSUE TITLE
Textarea auto-height hydration mismatch with Nuxt 3

### ISSUE THREAD

**Issue by juni0r** [formkit/formkit#980]
### Reproduction

https://formkit.link/e576f4c2032e76fd8c7aeb7e1bd0fbce

### Describe the bug

Using the `auto-height` addon on a textarea leads to hydration mismatch with Nuxt 3 SSR.

```vue
<FormKit type="textarea" auto-height name="message" label="Message" />
```
Workaround is apparently to wrap the textarea with `<ClientOnly>`.

<img width="1190" alt="Screenshot 2023-10-08 at 14 09 43" src="https://github.com/formkit/formkit/assets/11867/b3f89f2f-c3a1-4fdd-bca8-2ebabb834ee4">

<img width="1192" alt="Screenshot 2023-10-08 at 14 09 55" src="https://github.com/formkit/formkit/assets/11867/c9cf910a-0724-44f7-8995-fd7a426b2637">

### Environment

- OS: macOS
- Browser: chrome
- Nuxt: 3.7.4
- @formkit/addons: 1.2.2
- @formkit/nuxt: 1.2.2

**Comment by justin-schroeder** [comment]
Fixed on the `@next` tag.
