### ISSUE TITLE
Getting error: Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by phoenixbart** [formkit/formkit#983]
### Reproduction

not applicable

### Describe the bug

After updating to latest formkit versions (see list below) i getting an error: Critical dependency: the request of a dependency is an expression.
I'm using formkit in a laravel project with vue and webpack
After searching on the internet i guess this is coming from webpack because there is a wrong import or something?
When im using version 1.0.0, i don't get this error. All newer versions does

versions from my package.json after updating:
"@formkit/pro": "^0.117.5",
"@formkit/themes": "^1.2.2",
"@formkit/vue": "^1.2.2",

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome]
• Version [e.g. 22]

**Comment by phoenixbart** [comment]
I kept the changelog for the available versions. If I use version 1.0.0 then I don't have that error, but all newer versions do give the error. So from version 1.1.0 according to the changelog at https://formkit.com/changelog

**Comment by justin-schroeder** [comment]
@phoenixbart can you try installing version `1.3.0-a593d1f` (for any `@formkit/*` dependencies).

**Comment by phoenixbart** [comment]
@justin-schroeder If i update '@formkit/vue' to your suggested version the error is gone indeed :D 
Thank you very much for fixing it so quickly!

**Comment by snoozbuster** [comment]
hey @justin-schroeder do you know when this will be released? I attempted to update to 1.2.2 today and got this same warning.
