### ISSUE TITLE
File input: Content inside 'noFiles' slot is still visible even when files were added

### ISSUE THREAD

**Issue by phillipmohr** [formkit/formkit#991]
### Reproduction

https://formkit.com/playground?files=jc%5B%28%27name%21%27C_%3C9Y*%3CS+typeGform7%3E3%3CSN%3ApluginsG%5BpHIZ%5D7NtypeGC7NlabelGIZs7NnameGiZs7NacceptG.jpg%2C.png7NvalidationGrequired7N%3AzesG%28N*innerDbg-gray+px-12+h-56+flex+items-center+justify-center%22N%297N%3Asections-schemaG%28N*prefix%3AXN**ifD%24pHUrlMN**%24elDimgMN**attrs%3AXN***zD%24zes.iZPHMN***srcD%24pHUrl%22N**%29N*%29N%2973multiple3knoFiles%3EN*%3Cbutton+zGmy-fancy-button7%3EUpload+iZEButton%3ENE9kCList%3EE9%3E3ESY*ESYE9Y8%3Cscript+setup+langGts7Yfunction+pHIZ%7Bnode%7DX84%22%2288*node.on%7B%22inputM+%7B%28+J+%29%7D+%3D%3EX3VJM+J%7D3if+%7BArray.isArray%7BJ%7D+%26%26+J.length+%3E+0%7DXNconst+QTJ%5B0%5DNconst+CTQ.CNVQ.CM+Q.C%7D34URL.createObjectURL%7BC%7D3%29+elseX34%22%223%298*%29%7D88*return+false8%298EscriptY8%27%7Esyntax%21%27%27%25%2C%28%27name%21%27FileUploadPH_8%27%7Eremovable%21true%7Esilent%21false%25%5D*++++38**4*node.context.pHUrlT7%5C%278%5Cn9templateCfileD%3A+%22E%3C%2FG%3D7HreviewJpayloadM%22%2CN3*QCWrapperSFormKitT+%3D+Vconsole.log%7B%22X+%28Y%3E8Zmage_.vue%27%7Eeditor%21%27k%3EN%3C9+%23zclass%25%7Eadded%21true%29%01%25zk_ZYXVTSQNMJHGEDC98743*_&css-framework=genesis&fkv=latest&fileTab=file.vue&imports=jc%28%27name%21%27ImportMap%27%7Eeditor%21%27%28*+1vue%5C%211https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fvue%403%2Fdist%2Fvue.esm-browser.min.js0*%29*%27%29*%5Cn0%5C%271+0%0110*_

### Describe the bug

According to the [documentation](https://formkit.com/inputs/file), the noFiles slot should display content only when no files are selected. However, even after adding a file, the content within that slot remains visible.

<img width="922" alt="" src="https://github.com/formkit/formkit/assets/30236221/ad161bb5-586c-4545-881e-aaac7ef4fccd">

### Environment

• OS: macOS
• Browser Chrome
• Version 100

**Comment by sashamilenkovic** [comment]
@phillipmohr Since you are overwriting the `noFiles` slot, you are in charge of setting a conditional yourself. Alternatively, you can target the slot `noFilesIcon` instead, so that conditional is still provided.
