### ISSUE TITLE
Binding Bug on Mask

### ISSUE THREAD

**Issue by glennlaysonjr** [formkit/formkit#992]
### Reproduction

https://formkit.link/b674a2858ea068b1ec7819267e8c395e

### Describe the bug

I am having an issue with the ref not binding with the mask input when using certain types of mask values. For example when I have a ref with a string value '12345' it does not display in the input. But when you add values to the input it does update the ref with the new value. This is not the case using formkit mask for other simple phone, date, and ssn masking that I have used in other components. 

Reproduction: https://formkit.link/b674a2858ea068b1ec7819267e8c395e

Here is it showing it working with non complex mask: https://formkit.link/5951499ca6feaf811a9034ac08fd164b

Here showing if you bring both together in they both stop working: https://formkit.link/dd8dddebdce7baa09087968d94a3a5c4

My Use Case:

```
const form = ref({
 /// other values
    fee: "1234"
})

<FormKit
  type="mask"
  reverse
  prefix="$"
  name="bid"
  mask="{#,##|repeat}#.##"
  show-mask="false"
  allow-incomplete="true"
  v-model="form.fee"
  label="Notary Fee"
  unmask-value="true"
/>
```

### Environment

"@formkit/addons": "^1.2.2",
    "@formkit/icons": "^1.2.2",
    "@formkit/nuxt": "^0.18.5",
    "@formkit/pro": "^0.117.5",
    "@formkit/themes": "^1.2.2",
    "@formkit/vue": "^1.2.2",

**Comment by glennlaysonjr** [comment]
@justin-schroeder @sashamilenkovic Is there any update on this?

**Comment by justin-schroeder** [comment]
No update to speak of yet, but this has to do specifically with running masks in reverse. If you remove the `reverse` prop it should work just fine. I’m going to close this one in favor of #745
