### ISSUE TITLE
Datepicker validation not reactive

### ISSUE THREAD

**Issue by Vant0** [formkit/formkit#998]
### Reproduction

https://formkit.link/c3a84494da93cebca11ce26e8a3930fa

### Describe the bug

In this example, when selecting for both inputs the same day (e.g. 18th of October). The following action is to change the day of the end date to the 17th by using the keyboard. The validation error message for the end date is shown, but not for the start date. When changing the date of the start date to the 18th, then the validation error message is shown for the start date. And finally when changing the end date to the 20th, the validation error message of the start date remains, although it is valid.

### Environment

• OS: macOS 14.0
• Browser Brave
• Version 1.59.117

**Comment by justin-schroeder** [comment]
Closing in favor of #1055
