### ISSUE TITLE
Datepicker keyboard navigation behavior

### ISSUE THREAD

**Issue by KoenCa** [formkit/formkit#999]
### Reproduction

https://formkit.link/fda08767b190cd96416c91d2995154cd

### Describe the bug

Hey, in the datepicker input is it normal that you jump immediately to the year part of the date when it is already filled in? Please see the video. I would expect that I jump to the first part of the date when tabbing into the datepicker which in this case would be the month. When the datepicker has no value, then it does jump to the first part of the date. Is this intended behavior? For me it would be more logical that it always jumps to the first part of the date.

https://github.com/formkit/formkit/assets/17332418/e742fd4c-dfc6-4408-bb19-6f909f62609e

PS: I asked about this on Discord and I was told to make this issue.

### Environment

• OS: MacOS
• Browser: Chrome
• Version: 1.2.x

**Comment by sashamilenkovic** [comment]
@KoenCa This has been addressed at FormKit Pro v0.126.9
